### ISSUE TITLE
TypeError: 'Seq2SeqCollater' object is not callable

### ISSUE THREAD

**Issue by nichongjia** [pytorch/fairseq#1036]
When using speech recognition examples to train models, occured an error like the following:
~/anaconda3/lib/python3.7/site-packages/fairseq-0.8.0-py3.7-linux-x86_64.egg/examples/speech_recognition/models/vggtransformer.py:146: UserWarning: FairseqModel is deprecated, please use FairseqEncoderDecoderModel or BaseFairseqModel instead
  return cls(encoder, decoder)
~/anaconda3/lib/python3.7/site-packages/fairseq-0.8.0-py3.7-linux-x86_64.egg/examples/speech_recognition/models/vggtransformer.py:146: UserWarning: FairseqModel is deprecated, please use FairseqEncoderDecoderModel or BaseFairseqModel instead
  return cls(encoder, decoder)
~/anaconda3/lib/python3.7/site-packages/fairseq-0.8.0-py3.7-linux-x86_64.egg/examples/speech_recognition/models/vggtransformer.py:146: UserWarning: FairseqModel is deprecated, please use FairseqEncoderDecoderModel or BaseFairseqModel instead
  return cls(encoder, decoder)
~/anaconda3/lib/python3.7/site-packages/fairseq-0.8.0-py3.7-linux-x86_64.egg/examples/speech_recognition/models/vggtransformer.py:146: UserWarning: FairseqModel is deprecated, please use FairseqEncoderDecoderModel or BaseFairseqModel instead
  return cls(encoder, decoder)
Traceback (most recent call last):
  File "train.py", line 325, in <module>
    cli_main()
  File "train.py", line 317, in cli_main
    nprocs=args.distributed_world_size,
  File "~/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "~/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "~/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "~/Work/ASR/fairseq_speech_recognition/train.py", line 284, in distributed_main
    main(args, init_distributed=True)
  File "~/Work/ASR/fairseq_speech_recognition/train.py", line 83, in main
    valid_losses = validate(args, trainer, task, epoch_itr, valid_subsets)
  File "~/Work/ASR/fairseq_speech_recognition/train.py", line 227, in validate
    for sample in progress:
  File "~/anaconda3/lib/python3.7/site-packages/fairseq-0.8.0-py3.7-linux-x86_64.egg/fairseq/progress_bar.py", line 125, in __iter__
    for i, obj in enumerate(self.iterable, start=self.offset):
  File "~/anaconda3/lib/python3.7/site-packages/fairseq-0.8.0-py3.7-linux-x86_64.egg/fairseq/data/iterators.py", line 35, in __iter__
    for x in self.iterable:
  File "~/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 346, in __next__
    data = self.dataset_fetcher.fetch(index)  # may raise StopIteration
  File "~/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
TypeError: 'Seq2SeqCollater' object is not callable

**Comment by okhonko** [comment]
Thanks for reporting the bug, @nichongjia !
https://github.com/fairinternal/fairseq-py/commit/918dcc156ea1ab54d784a840754b3396f7a996de
should fix the issue. Please let me know if you can still experience any errors.
