### ISSUE TITLE
unable to open shared memory

### ISSUE THREAD

**Issue by lczhang06** [pytorch/fairseq#1057]
I try to Finetune RoBERTa on Commonsense QA dataset and use CUDA_VISIBLE_DEVICES to set the GPUs. However, I cannot train the model with multiple GPUs, no matter what the setting of batch-size and number of GPUs is. I can only train it on 1 GPU.
How can I solve this problem? Please help. Thank you.

`
| training on 2 GPUs
| max tokens per GPU = None and max sentences per GPU = 4
Overwriting classification_heads.sentence_classification_head.dense.weight
Overwriting classification_heads.sentence_classification_head.dense.bias
Overwriting classification_heads.sentence_classification_head.out_proj.weight
Overwriting classification_heads.sentence_classification_head.out_proj.bias
| loaded checkpoint /home/zlc/RoBERTa-model/roberta.large/model.pt (epoch 0 @ 0 updates)
| loading train data for epoch 0
| Loaded train with 9741 samples
Traceback (most recent call last):
  File "/home/zlc/.local/bin/fairseq-train", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-train')()
  File "/home/zlc/fairseq/fairseq_cli/train.py", line 316, in cli_main
    nprocs=args.distributed_world_size,
  File "/usr/local/lib/python3.5/dist-packages/torch/multiprocessing/spawn.py", line 167, in spawn
    while not spawn_context.join():
  File "/usr/local/lib/python3.5/dist-packages/torch/multiprocessing/spawn.py", line 114, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/zlc/fairseq/fairseq_cli/train.py", line 283, in distributed_main
    main(args, init_distributed=True)
  File "/home/zlc/fairseq/fairseq_cli/train.py", line 79, in main
    train(args, trainer, task, epoch_itr)
  File "/home/zlc/fairseq/fairseq_cli/train.py", line 119, in train
    for i, samples in enumerate(progress, start=epoch_itr.iterations_in_epoch):
  File "/home/zlc/fairseq/fairseq/progress_bar.py", line 186, in __iter__
  File "/home/zlc/fairseq/fairseq/data/iterators.py", line 286, in __next__
  File "/home/zlc/fairseq/fairseq/data/iterators.py", line 40, in __next__
  File "/home/zlc/fairseq/fairseq/data/iterators.py", line 35, in __iter__
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 193, in __iter__
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 469, in __init__
  File "/usr/lib/python3.5/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.5/multiprocessing/context.py", line 212, in _Popen
  File "/usr/lib/python3.5/multiprocessing/context.py", line 274, in _Popen
  File "/usr/lib/python3.5/multiprocessing/popen_spawn_posix.py", line 33, in __init__
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 20, in __init__
  File "/usr/lib/python3.5/multiprocessing/popen_spawn_posix.py", line 48, in _launch
  File "/usr/lib/python3.5/multiprocessing/reduction.py", line 59, in dump
  File "/usr/local/lib/python3.5/dist-packages/torch/multiprocessing/reductions.py", line 315, in reduce_storage
RuntimeError: unable to open shared memory object </torch_12800_2526550622> in read-write mode
`

**Comment by myleott** [comment]
Try `--ddp-backend=no_c10d`
