### ISSUE TITLE
Custom classification - error while running train.py

### ISSUE THREAD

**Issue by subhamkhemka** [pytorch/fairseq#1118]
Hi 

I have followed all the steps in https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.custom_classification.md
However getting error while running train.py.

`Traceback (most recent call last):
  File "train.py", line 326, in <module>
    cli_main()
  File "train.py", line 322, in cli_main
    main(args)
  File "train.py", line 48, in main
    task.load_dataset(valid_sub_split, combine=False, epoch=0)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/fairseq/tasks/sentence_prediction.py", line 174, in load_dataset
    sizes=[src_tokens.sizes],
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/fairseq/data/nested_dictionary_dataset.py", line 60, in __init__
    assert len(v) == len(first), 'dataset lengths must match'`

Please help
Thanks

**Comment by curranmaguire** [comment]
can you post how you fixed this please
