### ISSUE TITLE
Runtime error when running Roberta with multiple GPUs on RACE

### ISSUE THREAD

**Issue by grdtsinghua** [pytorch/fairseq#1126]
I do everything under instruction in README.race.md. But I got this runtime error :

Traceback (most recent call last):
  File "/home/gaorundong/miniconda3/bin/fairseq-train", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-train')()
  File "/home/gaorundong/fairseq/fairseq_cli/train.py", line 318, in cli_main
    nprocs=args.distributed_world_size,
  File "/home/gaorundong/miniconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/gaorundong/miniconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/gaorundong/miniconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/gaorundong/fairseq/fairseq_cli/train.py", line 285, in distributed_main
    main(args, init_distributed=True)
  File "/home/gaorundong/fairseq/fairseq_cli/train.py", line 81, in main
    train(args, trainer, task, epoch_itr)
  File "/home/gaorundong/fairseq/fairseq_cli/train.py", line 122, in train
    log_output = trainer.train_step(samples)
  File "/home/gaorundong/fairseq/fairseq/trainer.py", line 312, in train_step
    raise e
  File "/home/gaorundong/fairseq/fairseq/trainer.py", line 289, in train_step
    ignore_grad
  File "/home/gaorundong/fairseq/fairseq/tasks/fairseq_task.py", line 231, in train_step
    loss, sample_size, logging_output = criterion(model, sample)
  File "/home/gaorundong/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gaorundong/fairseq/fairseq/criterions/sentence_ranking.py", line 49, in forward
    classification_head_name='sentence_classification_head',
  File "/home/gaorundong/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gaorundong/miniconda3/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 442, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/gaorundong/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gaorundong/fairseq/fairseq/models/roberta/model.py", line 99, in forward
    x, extra = self.decoder(src_tokens, features_only, return_all_hiddens, **kwargs)
  File "/home/gaorundong/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gaorundong/fairseq/fairseq/models/roberta/model.py", line 284, in forward
    x, extra = self.extract_features(src_tokens, return_all_hiddens)
  File "/home/gaorundong/fairseq/fairseq/models/roberta/model.py", line 291, in extract_features
    src_tokens, last_state_only=not return_all_hiddens,
  File "/home/gaorundong/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gaorundong/fairseq/fairseq/modules/transformer_sentence_encoder.py", line 210, in forward
    x, _ = layer(x, self_attn_padding_mask=padding_mask)
  File "/home/gaorundong/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gaorundong/fairseq/fairseq/modules/transformer_sentence_encoder_layer.py", line 79, in forward
    attn_mask=self_attn_mask,
  File "/home/gaorundong/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gaorundong/fairseq/fairseq/modules/multihead_attention.py", line 115, in forward
    attn_mask)
  File "/home/gaorundong/miniconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 3112, in multi_head_attention_forward
    q, k, v = linear(query, in_proj_weight, in_proj_bias).chunk(3, dim=-1)
  File "/home/gaorundong/miniconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 1371, in linear
    output = input.matmul(weight.t())
RuntimeError: cublas runtime error : library not initialized at /opt/conda/conda-bld/pytorch_1565272271120/work/aten/src/THC/THCGeneral.cpp:216

What should I do?
Does anyone know?

**Comment by huihuifan** [comment]
Can you provide some other information? Can you use fairseq normally, and it is just for this finetuning that does not work? 

Do you have everything correctly installed? See error: "RuntimeError: cublas runtime error : library not initialized at /opt/conda/conda-bld/pytorch_1565272271120/work/aten/src/THC/THCGeneral.cpp:216"

**Comment by huihuifan** [comment]
sorry closed by accident, meant to hit "comment"

**Comment by grdtsinghua** [comment]
I can use fairseq and pytorch normally. I only met this error on this task.

**Comment by myleott** [comment]
Can you try `--ddp-backend=no_c10d`? Some of the tasks don't work well with the PyTorch DistributedDataParallel module.

**Comment by myleott** [comment]
Confirmed this is working with `--ddp-backend=no_c10d`. Updated the README here: #1155.
