### ISSUE TITLE
Runtime error when running RoBERTa with multiple GPUs on CommonSenseQA

### ISSUE THREAD

**Issue by grdtsinghua** [pytorch/fairseq#1128]
This is the script what I used to running RoBERTa with 2 GPUs on CommonsenseQA.

MAX_UPDATES=3000      # Number of training steps.
WARMUP_UPDATES=150    # Linearly increase LR over this many steps.
LR=1e-05              # Peak LR for polynomial LR scheduler.
MAX_SENTENCES=16      # Batch size.
SEED=1                # Random seed.
UPDATE_FREQ=1
ROBERTA_PATH=/home/gaorundong/cqa_exp/model/roberta.large
DATA_DIR=/home/gaorundong/mrc_data/CommonsenseQA

# we use the --user-dir option to load the task from
# the examples/roberta/commonsense_qa directory:
FAIRSEQ_USER_DIR=/home/gaorundong/cqa_exp/roberta

CUDA_VISIBLE_DEVICES=2,3 fairseq-train --fp16 \
            $DATA_DIR \
                --user-dir $FAIRSEQ_USER_DIR \
                --restore-file $ROBERTA_PATH \
                --reset-optimizer --reset-dataloader --reset-meters \
                --no-epoch-checkpoints --no-last-checkpoints --no-save-optimizer-state \
                --best-checkpoint-metric accuracy --maximize-best-checkpoint-metric \
                --task commonsense_qa --init-token 0 --bpe gpt2 \
                --arch roberta_large --max-positions 512 \
                --dropout 0.1 --attention-dropout 0.1 --weight-decay 0.01 \
                --criterion sentence_ranking --num-classes 5 \
                --optimizer adam --adam-betas '(0.9, 0.98)' --adam-eps 1e-06 --clip-norm 0.0 \
                --lr-scheduler polynomial_decay --lr $LR \
                --update-freq $UPDATE_FREQ \
                --warmup-updates $WARMUP_UPDATES --total-num-update $MAX_UPDATES \
                --max-sentences $MAX_SENTENCES \
                --max-update $MAX_UPDATES \
                --log-format simple --log-interval 25 \
                --seed $SEED

Then I got this runtime error message:

Traceback (most recent call last):
  File "/home/gaorundong/miniconda3/bin/fairseq-train", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-train')()
  File "/home/gaorundong/fairseq/fairseq_cli/train.py", line 318, in cli_main
    nprocs=args.distributed_world_size,
  File "/home/gaorundong/miniconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/gaorundong/miniconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/gaorundong/miniconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
  File "/home/gaorundong/fairseq/fairseq_cli/train.py", line 285, in distributed_main
  File "/home/gaorundong/fairseq/fairseq_cli/train.py", line 81, in main
  File "/home/gaorundong/fairseq/fairseq_cli/train.py", line 121, in train
  File "/home/gaorundong/fairseq/fairseq/progress_bar.py", line 186, in __iter__
  File "/home/gaorundong/fairseq/fairseq/data/iterators.py", line 290, in __next__
  File "/home/gaorundong/fairseq/fairseq/data/iterators.py", line 41, in __next__
  File "/home/gaorundong/fairseq/fairseq/data/iterators.py", line 36, in __iter__
  File "/home/gaorundong/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 278, in __iter__
  File "/home/gaorundong/miniconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 682, in __init__
  File "/home/gaorundong/miniconda3/lib/python3.7/multiprocessing/process.py", line 112, in start
  File "/home/gaorundong/miniconda3/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
  File "/home/gaorundong/miniconda3/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
  File "/home/gaorundong/miniconda3/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
  File "/home/gaorundong/miniconda3/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
  File "/home/gaorundong/miniconda3/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
  File "/home/gaorundong/miniconda3/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
  File "/home/gaorundong/miniconda3/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 323, in reduce_storage
RuntimeError: unable to open shared memory object </torch_26184_1515909845> in read-write mode

I didn't know what caused such error. Can anyone help me?

**Comment by shamanez** [comment]
Any update on this?

**Comment by myleott** [comment]
Use `--ddp-backend=no_c10d`. I'm updating the README to include that flag: #1140.
