### ISSUE TITLE
Unable to open shared memory when training on multi-GPUs

### ISSUE THREAD

**Issue by siddalmia** [pytorch/fairseq#1131]
Hi, 

I am getting the same error only when I use **multiple GPUs**. Have already tried the methods mentioned in https://github.com/pytorch/pytorch/issues/1355#issuecomment-297184037 for example increasing the shared memory size. 

Is there some specific settings that need to be set for increasing workers in multi-gpu training for fairseq? 

The code works just fine if I use 1 GPU and set the number of workers to 10. The machine that I am running my code on is the lambda quads (https://lambdalabs.com/deep-learning/workstations/4-gpu, @stephenbalaban it might be of interest to you). 

I have run code with horovod in the past and it seems to work fine.
Thanks
Sid

_Originally posted by @siddalmia in https://github.com/pytorch/fairseq/issues/1057#issuecomment-530922105_

**Comment by huihuifan** [comment]
Can you post your exact error?

**Comment by siddalmia** [comment]
Hey @huihuifan , 

The error is the same as the one mentioned in - https://github.com/pytorch/fairseq/issues/1057#issue-484476815. I have also posted the same generated from my code with options of `--num-workers 1` and number of gpus 2. 

```
/home/sdalmia/anaconda3/envs/pytorch/lib/python3.7/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 11 leaked semaphores to clean up at shutdown
  len(cache))
Traceback (most recent call last):
  File "train.py", line 324, in <module>
    cli_main()
  File "train.py", line 316, in cli_main
    nprocs=args.distributed_world_size,
  File "/home/sdalmia/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/sdalmia/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/sdalmia/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
  File "/data/ASR1/sdalmia/decoupling/fairseq/train.py", line 283, in distributed_main
    main(args, init_distributed=True)
  File "/data/ASR1/sdalmia/decoupling/fairseq/train.py", line 79, in main
    train(args, trainer, task, epoch_itr)
  File "/data/ASR1/sdalmia/decoupling/fairseq/train.py", line 119, in train
    for i, samples in enumerate(progress, start=epoch_itr.iterations_in_epoch):
  File "/data/ASR1/sdalmia/decoupling/fairseq/fairseq/progress_bar.py", line 125, in __iter__
  File "/data/ASR1/sdalmia/decoupling/fairseq/fairseq/data/iterators.py", line 286, in __next__
  File "/data/ASR1/sdalmia/decoupling/fairseq/fairseq/data/iterators.py", line 40, in __next__
  File "/data/ASR1/sdalmia/decoupling/fairseq/fairseq/data/iterators.py", line 35, in __iter__
  File "/home/sdalmia/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 278, in __iter__
  File "/home/sdalmia/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 682, in __init__
  File "/home/sdalmia/anaconda3/envs/pytorch/lib/python3.7/multiprocessing/process.py", line 112, in start
  File "/home/sdalmia/anaconda3/envs/pytorch/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
  File "/home/sdalmia/anaconda3/envs/pytorch/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
  File "/home/sdalmia/anaconda3/envs/pytorch/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
  File "/home/sdalmia/anaconda3/envs/pytorch/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
  File "/home/sdalmia/anaconda3/envs/pytorch/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
  File "/home/sdalmia/anaconda3/envs/pytorch/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
  File "/home/sdalmia/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 323, in reduce_storage
RuntimeError: unable to open shared memory object </torch_2174_3963114511> in read-write mode
```

Some info about my shared memory related to the ones mentioned in https://github.com/pytorch/pytorch/issues/1355#issuecomment-297184037 - 

```
df -h /dev/shm/
Filesystem      Size  Used Avail Use% Mounted on
tmpfs            63G     0   63G   0% /dev/shm
```
```
ipcs -lm
------ Shared Memory Limits --------
max number of segments = 8192
max seg size (kbytes) = 18014398509465599
max total shared memory (kbytes) = 18014398509481980
min seg size (bytes) = 1
```

**Comment by myleott** [comment]
Please try `--ddp-backend=no_c10d`. The built-in PyTorch DistributedDataParallel backend is quite fragile and doesn't work with some model configurations.

**Comment by myleott** [comment]
Please reopen if this is still an issue after adjusting the flag.

**Comment by siddalmia** [comment]
Hi @myleott, I did try `--ddp-backend=no_c10d` and the same error still persists. 

Also, I can only reopen issues that were closed by me, not if it was closed by a maintainer. I will start a new issue and refer to this one if you are unable to see my message. 

Thanks
Sid

**Comment by jalajthanaki** [comment]
Hi @myleott / @siddalmia , 
Is there any example available where horovod has been used with fairseq? If yes can you please share the link?

Thanks,
Jalaj

**Comment by SebastienEske** [comment]
Hello, I had the same issue. And it had to do with ulimit -n, simply increase it and the problem is solved, I used ulimit -n 500000
