### ISSUE TITLE
Error about fp16

### ISSUE THREAD

**Issue by shuxiaobo** [pytorch/fairseq#1145]
Hi, I Just download the new master branch of this repo, but get error about fp16 operation. I can not search the same issue about it. When I remove the ```--fp16``` parameter , it runs normally.
```
| model roberta_large, criterion SentenceRankingCriterion
| num. model params: 356461658 (num. trained: 356461658)
| training on 1 GPUs
| max tokens per GPU = None and max sentences per GPU = 8
| no existing checkpoint found /data/roberta/model.pt
| loading train data for epoch 0
| Loaded train with 9741 samples
Traceback (most recent call last):
  File "/home/shuxiaobo/anaconda3/bin/fairseq-train", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-train')()
  File "/data/fairseq/fairseq_cli/train.py", line 322, in cli_main
    main(args)
  File "/data/fairseq/fairseq_cli/train.py", line 81, in main
    train(args, trainer, task, epoch_itr)
  File "/data/fairseq/fairseq_cli/train.py", line 122, in train
    log_output = trainer.train_step(samples)
  File "/data/fairseq/fairseq/trainer.py", line 324, in train_step
    raise e
  File "/data/fairseq/fairseq/trainer.py", line 294, in train_step
    ignore_grad
  File "/data/fairseq/fairseq/tasks/fairseq_task.py", line 231, in train_step
    loss, sample_size, logging_output = criterion(model, sample)
  File "/home/shuxiaobo/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/fairseq/fairseq/criterions/sentence_ranking.py", line 49, in forward
    classification_head_name='sentence_classification_head',
  File "/home/shuxiaobo/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/fairseq/fairseq/models/roberta/model.py", line 99, in forward
    x, extra = self.decoder(src_tokens, features_only, return_all_hiddens, **kwargs)
  File "/home/shuxiaobo/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/fairseq/fairseq/models/roberta/model.py", line 284, in forward
    x, extra = self.extract_features(src_tokens, return_all_hiddens)
  File "/data/fairseq/fairseq/models/roberta/model.py", line 291, in extract_features
    src_tokens, last_state_only=not return_all_hiddens,
  File "/home/shuxiaobo/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/fairseq/fairseq/modules/transformer_sentence_encoder.py", line 182, in forward
    x = self.embed_tokens(tokens)
  File "/home/shuxiaobo/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shuxiaobo/anaconda3/lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 114, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/home/shuxiaobo/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 1467, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: _th_index_select not supported on CPUType for Half
```

**Comment by shuxiaobo** [comment]
Script is commonsenseqa which is 
```
#!/usr/bin/env bash
MAX_UPDATES=3000      # Number of training steps.
WARMUP_UPDATES=150    # Linearly increase LR over this many steps.
LR=1e-05              # Peak LR for polynomial LR scheduler.
MAX_SENTENCES=8      # Batch size.
SEED=1                # Random seed.
ROBERTA_PATH=/data/roberta/model.pt
DATA_DIR=data/CommonsenseQA

# we use the --user-dir option to load the task from
# the examples/roberta/commonsense_qa directory:
FAIRSEQ_PATH=/data/fairseq
FAIRSEQ_USER_DIR=${FAIRSEQ_PATH}/examples/roberta/commonsense_qa

CUDA_VISIBLE_DEVICES=1 fairseq-train --fp16 --ddp-backend=no_c10d \
    $DATA_DIR \
    --user-dir $FAIRSEQ_USER_DIR \
    --restore-file $ROBERTA_PATH \
    --reset-optimizer --reset-dataloader --reset-meters \
    --no-epoch-checkpoints --no-last-checkpoints --no-save-optimizer-state \
    --best-checkpoint-metric accuracy --maximize-best-checkpoint-metric \
    --task commonsense_qa --init-token 0 --bpe gpt2 \
    --arch roberta_large --max-positions 512 \
    --dropout 0.1 --attention-dropout 0.1 --weight-decay 0.01 \
    --criterion sentence_ranking --num-classes 5 \
    --optimizer adam --adam-betas '(0.9, 0.98)' --adam-eps 1e-06 --clip-norm 0.0 \
    --lr-scheduler polynomial_decay --lr $LR \
    --warmup-updates $WARMUP_UPDATES --total-num-update $MAX_UPDATES \
    --max-sentences $MAX_SENTENCES \
    --max-update $MAX_UPDATES \
    --log-format simple --log-interval 25 \
    --seed $SEED
```

**Comment by myleott** [comment]
`--fp16` only works on GPU, not CPU. That error message indicates you're training on CPU.

But your command indicates you meant to train on GPU (`CUDA_VISIBLE_DEVICES=1`), is that correct?

How many GPUs do you have in your system? `CUDA_VISIBLE_DEVICES` should be a comma-separated list of the GPU index, starting at 0. So to use the first GPU in your system you should use `CUDA_VISIBLE_DEVICES=0` then it should work :)

**Comment by kristjanArumae** [comment]
@myleott I went through a bit of troubleshooting for this myself.  I am using CUDA 10.1 pytorch 1.4.0, and the latest version of fairseq.  I'm running this on a [p3.16xlarge](https://aws.amazon.com/ec2/instance-types/p3/).  I get the error referenced by @shuxiaobo :
`RuntimeError: _th_index_select not supported on CPUType for Half` 

when running :
```bash
MAX_UPDATES=3000      # Number of training steps.
WARMUP_UPDATES=150    # Linearly increase LR over this many steps.
LR=1e-05              # Peak LR for polynomial LR scheduler.
MAX_SENTENCES=16      # Batch size.
SEED=1                # Random seed.
ROBERTA_PATH=/home/roberta.base/model.pt
DATA_DIR=/home/QA_testing/csqa/data/CommonsenseQA

# we use the --user-dir option to load the task from
# the examples/roberta/commonsense_qa directory:
FAIRSEQ_USER_DIR=/home/QA_testing/fairseq/examples/roberta/commonsense_qa

CUDA_VISIBLE_DEVICES=0,1,2,3 fairseq-train --ddp-backend=no_c10d \
    $DATA_DIR \
    --user-dir $FAIRSEQ_USER_DIR \
    --restore-file $ROBERTA_PATH \
    --reset-optimizer --reset-dataloader --reset-meters \
    --no-epoch-checkpoints --no-last-checkpoints --no-save-optimizer-state \
    --best-checkpoint-metric accuracy --maximize-best-checkpoint-metric \
    --task commonsense_qa --init-token 0 --bpe gpt2 \
    --arch roberta_base --max-positions 512 \
    --dropout 0.1 --attention-dropout 0.1 --weight-decay 0.01 \
    --criterion sentence_ranking --num-classes 5 \
    --optimizer adam --adam-betas '(0.9, 0.98)' --adam-eps 1e-06 --clip-norm 0.0 \
    --lr-scheduler polynomial_decay --lr $LR \
    --warmup-updates $WARMUP_UPDATES --total-num-update $MAX_UPDATES \
    --max-sentences $MAX_SENTENCES \
    --max-update $MAX_UPDATES \
    --log-format simple --log-interval 25 \
    --seed $SEED
```

**Comment by ethanjperez** [comment]
I find the same issue when fine-tuning BART on CNNDM with fp16 as described in the official [instructions](https://github.com/pytorch/fairseq/blob/master/examples/bart/README.summarization.md). The issue only occurs on a 1080ti GPU but not a 2080ti GPU. I'm using a Python 3.7 conda env (Anaconda 3) with pytorch 1.4, CUDA 10.1, GCC 7.4. Is this an apex issue?
