### ISSUE TITLE
Not enough values to unpack

### ISSUE THREAD

**Issue by mortonjt** [pytorch/fairseq#1164]
I'm getting an error shown below

```
| WARNING: 119934 samples have invalid sizes and will be skipped, max_positions=1024, first few sample ids=[92711, 1032347, 174715, 403967, 143104, 1268626, 797114, 206659, 1088957, 753465]
| WARNING: ran out of memory with exception: CUDA out of memory. Tried to allocate 3.07 GiB (GPU 0; 31.72 GiB total capacity; 29.28 GiB already allocated; 767.56 MiB free; 556.92 MiB cached);
 Skipping batch
| WARNING: ran out of memory with exception: CUDA out of memory. Tried to allocate 2.86 GiB (GPU 0; 31.72 GiB total capacity; 26.41 GiB already allocated; 2.17 GiB free; 1.99 GiB cached);
 Skipping batch
| WARNING: ran out of memory with exception: CUDA out of memory. Tried to allocate 2.96 GiB (GPU 0; 31.72 GiB total capacity; 24.85 GiB already allocated; 1.82 GiB free; 3.90 GiB cached);
 Skipping batch
pcn-7-02:343884:343884 [2] NCCL INFO AllReduce: opCount 2 sendbuff 0x2aabca255400 recvbuff 0x2aabca255400 count 65536 datatype 1 op 0 root 0 comm 0x2aabcc001af0 [nranks=4] stream 0x25e0960
pcn-7-02:343882:343882 [0] NCCL INFO AllReduce: opCount 2 sendbuff 0x2aabce297a00 recvbuff 0x2aabce297a00 count 65536 datatype 1 op 0 root 0 comm 0x2aabd4001af0 [nranks=4] stream 0x25e16d0
Traceback (most recent call last):
  File "/home/jmorton/venvs/roberta/bin/fairseq-train", line 10, in <module>
    sys.exit(cli_main())
  File "/home/jmorton/venvs/roberta/lib/python3.6/site-packages/fairseq_cli/train.py", line 317, in cli_main
    nprocs=args.distributed_world_size,
  File "/home/jmorton/venvs/roberta/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/jmorton/venvs/roberta/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception:

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/home/jmorton/venvs/roberta/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/jmorton/venvs/roberta/lib/python3.6/site-packages/fairseq_cli/train.py", line 284, in distributed_main
    main(args, init_distributed=True)
  File "/home/jmorton/venvs/roberta/lib/python3.6/site-packages/fairseq_cli/train.py", line 80, in main
    train(args, trainer, task, epoch_itr)
  File "/home/jmorton/venvs/roberta/lib/python3.6/site-packages/fairseq_cli/train.py", line 121, in train
    log_output = trainer.train_step(samples)
  File "/home/jmorton/venvs/roberta/lib/python3.6/site-packages/fairseq/trainer.py", line 305, in train_step
    [logging_outputs, sample_sizes, ooms, self._prev_grad_norm],
ValueError: not enough values to unpack (expected 4, got 2)
```
The memory issue, is one problem - but I'm not sure why the ValueError is being thrown.
The command that I used is below

```
NPROC_PER_NODE=10
$(which fairseq-train) $DATA_DIR --fp16 \
    --task masked_lm --criterion masked_lm \
    --arch roberta_base --sample-break-mode complete --tokens-per-sample $TOKENS_PER_SAMPLE \
    --optimizer adam --adam-betas '(0.9,0.98)' --adam-eps 1e-6 --clip-norm 0.0 \
    --lr-scheduler polynomial_decay --lr $PEAK_LR --warmup-updates $WARMUP_UPDATES --total-num-update $TOTAL_UPDATES \
    --dropout 0.1 --attention-dropout 0.1 --weight-decay 0.01 \
    --max-sentences $MAX_SENTENCES --update-freq $UPDATE_FREQ \
    --max-update $TOTAL_UPDATES --log-format tqdm --log-interval 1 \
    --num-workers $NPROC_PER_NODE \
    --save-interval-updates 1 \
    --keep-interval-updates 3 \
    --tensorboard-logdir $TB_DIR \
    --save-dir $SAVE_DIR \
    --ddp-backend=no_c10d
```

**Comment by mortonjt** [comment]
I found out that there was an issue with my dictionary (it wasn't properly configured).  Going to close this issue for now, and reopen if I'm able to reproduce this problem.
