### ISSUE TITLE
torch.hub.list('pytorch/fairseq', force_reload=True) error

### ISSUE THREAD

**Issue by yotam319** [pytorch/fairseq#1210]
im trying to run:
```
import torch
torch.hub.list('pytorch/fairseq', force_reload=True)
```
and getting:
```

Downloading: "https://github.com/pytorch/fairseq/archive/master.zip" to /root/.cache/torch/hub/master.zip
Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-b0ca02ad86ac>", line 2, in <module>
    torch.hub.list('pytorch/fairseq', force_reload=True)

  File "/usr/local/lib/python3.5/dist-packages/torch/hub.py", line 285, in list
    hub_module = import_module(MODULE_HUBCONF, repo_dir + '/' + MODULE_HUBCONF)

  File "/usr/local/lib/python3.5/dist-packages/torch/hub.py", line 72, in import_module
    spec.loader.exec_module(module)

  File "<frozen importlib._bootstrap_external>", line 665, in exec_module

  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed

  File "/root/.cache/torch/hub/pytorch_fairseq_master/hubconf.py", line 8, in <module>
    from fairseq.hub_utils import BPEHubInterface as bpe  # noqa

  File "/root/.cache/torch/hub/pytorch_fairseq_master/fairseq/__init__.py", line 10, in <module>
    import fairseq.models  # noqa

  File "/root/.cache/torch/hub/pytorch_fairseq_master/fairseq/models/__init__.py", line 128, in <module>
    module = importlib.import_module('fairseq.models.' + model_name)

  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

  File "/root/.cache/torch/hub/pytorch_fairseq_master/fairseq/models/iterative_nonautoregressive_transformer.py", line 8, in <module>
    from fairseq.models.nonautoregressive_transformer import NATransformerModel

  File "/root/.cache/torch/hub/pytorch_fairseq_master/fairseq/models/nonautoregressive_transformer.py", line 10, in <module>
    from fairseq.models.transformer import (

  File "/root/.cache/torch/hub/pytorch_fairseq_master/fairseq/models/transformer.py", line 242
    **extra_args,
                ^
SyntaxError: invalid syntax
```

im running python 3.5.2 and pytorch 1.2.0

**Comment by FakhriAbbas** [comment]
Were you able to fix this issue?

**Comment by FakhriAbbas** [comment]
For me I did the following:
export MACOSX_DEPLOYMENT_TARGET=10.10 
xcode-select --install
and re-run the fairseq install command and it worked.

**Comment by myleott** [comment]
Unfortunately it doesn't work with Python 3.5. We've tried to maintain compatibility with Python 3.5 but it's been too difficult since all our systems are on 3.6, so inevitably compatibility breaks. We will be updating the documentation to reflect this: https://github.com/pytorch/fairseq/issues/1317
