### ISSUE TITLE
install RoBERTa with pytorch 1.3 and python 3.7

### ISSUE THREAD

**Issue by hanswang73** [pytorch/fairseq#1284]
when I execute the below codes:

import torch
roberta = torch.hub.load('pytorch/fairseq', 'roberta.large')
roberta.eval()

it says :

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\D2L.ai\Miniconda3\lib\site-packages\torch\hub.py", line 341, in load
    model = entry(*args, **kwargs)
  File "C:\Users\hanswang/.cache\torch\hub\pytorch_fairseq_master\fairseq\models\roberta\model.py", line 139, in from_pretrained
    **kwargs,
  File "C:\Users\hanswang/.cache\torch\hub\pytorch_fairseq_master\fairseq\hub_utils.py", line 54, in from_pretrained
    arg_overrides=kwargs,
  File "C:\Users\hanswang/.cache\torch\hub\pytorch_fairseq_master\fairseq\checkpoint_utils.py", line 182, in load_model_ensemble_and_task
    task = tasks.setup_task(args)
  File "C:\Users\hanswang/.cache\torch\hub\pytorch_fairseq_master\fairseq\tasks\__init__.py", line 17, in setup_task
    return TASK_REGISTRY[args.task].setup_task(args, **kwargs)
  File "C:\Users\hanswang/.cache\torch\hub\pytorch_fairseq_master\fairseq\tasks\masked_lm.py", line 70, in setup_task
    dictionary = Dictionary.load(os.path.join(paths[0], 'dict.txt'))
NameError: name 'path' is not defined

when I execute again, it says:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\D2L.ai\Miniconda3\lib\site-packages\torch\hub.py", line 341, in load
    model = entry(*args, **kwargs)
  File "C:\Users\hanswang/.cache\torch\hub\pytorch_fairseq_master\fairseq\models\roberta\model.py", line 139, in from_pretrained
    **kwargs,
  File "C:\Users\hanswang/.cache\torch\hub\pytorch_fairseq_master\fairseq\hub_utils.py", line 54, in from_pretrained
    arg_overrides=kwargs,
  File "C:\Users\hanswang/.cache\torch\hub\pytorch_fairseq_master\fairseq\checkpoint_utils.py", line 182, in load_model_ensemble_and_task
    task = tasks.setup_task(args)
  File "C:\Users\hanswang/.cache\torch\hub\pytorch_fairseq_master\fairseq\tasks\__init__.py", line 17, in setup_task
    return TASK_REGISTRY[args.task].setup_task(args, **kwargs)
  File "C:\Users\hanswang/.cache\torch\hub\pytorch_fairseq_master\fairseq\tasks\masked_lm.py", line 70, in setup_task
    dictionary = Dictionary.load(os.path.join(paths[0], 'dict.txt'))
  File "C:\Users\hanswang/.cache\torch\hub\pytorch_fairseq_master\fairseq\data\dictionary.py", line 188, in load
    d.add_from_file(f, ignore_utf_errors)
  File "C:\Users\hanswang/.cache\torch\hub\pytorch_fairseq_master\fairseq\data\dictionary.py", line 205, in add_from_file
    raise fnfe
  File "C:\Users\hanswang/.cache\torch\hub\pytorch_fairseq_master\fairseq\data\dictionary.py", line 199, in add_from_file
    with open(f, 'r', encoding='utf-8') as fd:
FileNotFoundError: [Errno 2] No such file or directory: 'C\\dict.txt'

**Comment by myleott** [comment]
This might be fixed now, can you try with `force_reload=True`:
```
roberta = torch.hub.load('pytorch/fairseq', 'roberta.large', force_reload=True)
```
