### ISSUE TITLE
NAT generation doesn't work anymore

### ISSUE THREAD

**Issue by Tiiiger** [pytorch/fairseq#1307]
Hi, I think the recent commit `8defa9d` breaks the generation of Levenshtein transformer.

I run the example script 
```
fairseq-generate \
    data-bin/wmt14_en_de_distill \
    --gen-subset test \
    --task translation_lev \
    --path checkpoints/checkpoint_best.pt \
    --iter-decode-max-iter 9 \
    --iter-decode-eos-penalty 0 \
    --beam 1 --remove-bpe \
    --print-step \
    --batch-size 400
```

Here is the error message:
```
Traceback (most recent call last):
  File "/persist/conda/envs/bl/bin/fairseq-generate", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-generate')()
  File "~/fairseq/fairseq_cli/generate.py", line 228, in cli_main
    main(args)
  File "~/fairseq/fairseq_cli/generate.py", line 86, in main
    generator = task.build_generator(args)
  File "~/fairseq/fairseq/tasks/translation_lev.py", line 134, in build_generator
    adaptive=not getattr(args, 'iter_decode_force_max_iter', False))
TypeError: __init__() missing 1 required positional argument: 'tgt_dict'

```

This is on pytorch 1.3.0

**Comment by MultiPath** [comment]
I think it should be fixed right now. Can you try it again? Thanks
