### ISSUE TITLE
TypeError: load_dataset() got an unexpected keyword argument 'data_selector'

### ISSUE THREAD

**Issue by purnasanyal** [pytorch/fairseq#1312]
I am running BERT Training with FAIRSEQ and getting this error
How to fix 'data selector' error

(22): TransformerSentenceEncoderLayer(
          (self_attn): MultiheadAttention(
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (fc1): Linear(in_features=1024, out_features=4096, bias=True)
          (fc2): Linear(in_features=4096, out_features=1024, bias=True)
          (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        )
        (23): TransformerSentenceEncoderLayer(
          (self_attn): MultiheadAttention(
            (out_proj): Linear(in_features=1024, out_features=1024, bias=True)
          )
          (self_attn_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
          (fc1): Linear(in_features=1024, out_features=4096, bias=True)
          (fc2): Linear(in_features=4096, out_features=1024, bias=True)
          (final_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
        )
      )
      (emb_layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    )
    (masked_lm_pooler): Linear(in_features=1024, out_features=1024, bias=True)
    (lm_head_transform_weight): Linear(in_features=1024, out_features=1024, bias=True)
    (layer_norm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
    (sentence_projection_layer): Linear(in_features=1024, out_features=2, bias=False)
  )
)
| model bert_large, criterion MaskedLmLoss
| num. model params: 356462681 (num. trained: 356462681)
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/bin/fairseq-train", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-train')()
  File "/home/ubuntu/fairseq/fairseq_cli/train.py", line 319, in cli_main
    nprocs=torch.cuda.device_count(),
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/ubuntu/fairseq/fairseq_cli/train.py", line 301, in distributed_main
    main(args, init_distributed=True)
  File "/home/ubuntu/fairseq/fairseq_cli/train.py", line 81, in main
    extra_state, epoch_itr = checkpoint_utils.load_checkpoint(args, trainer)
  File "/home/ubuntu/fairseq/fairseq/checkpoint_utils.py", line 130, in load_checkpoint
    epoch_itr = trainer.get_train_iterator(epoch=0, load_dataset=True, data_selector=data_selector)
  File "/home/ubuntu/fairseq/fairseq/trainer.py", line 242, in get_train_iterator
    data_selector=data_selector,
TypeError: load_dataset() got an unexpected keyword argument 'data_selector'

**Comment by myleott** [comment]
Fixed
