### ISSUE TITLE
RuntimeError: unexpected expression in variable initialization of for loop:

### ISSUE THREAD

**Issue by jatinganhotra** [pytorch/fairseq#1326]
Following the article - https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.pretraining.md
Command - 
```
bert/bin/fairseq-train --fp16 data-bin/wikitext-103 --task masked_lm --criterion masked_lm --arch roberta_base --sample-break-mode complete --tokens-per-sample 512 --optimizer adam --adam-betas '(0.9,0.98)' --adam-eps 1e-6 --clip-norm 0.0 --lr-scheduler polynomial_decay --lr 0.0005 --warmup-updates 10000 --total-num-update 2 --dropout 0.1 --attention-dropout 0.1 --weight-decay 0.01 --max-sentences 16 --update-freq 16 --max-update 2 --log-format simple --log-interval 1
```

Error - 
```
Traceback (most recent call last):
  File "conda-envs/bert/bin/fairseq-train", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-train')()
  File "conda-envs/bert/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "conda-envs/bert/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "conda-envs/bert/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "conda-envs/bert/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "fairseq/fairseq_cli/train.py", line 17, in <module>
    from fairseq import checkpoint_utils, distributed_utils, options, progress_bar, tasks, utils
  File "fairseq/fairseq/__init__.py", line 10, in <module>
    import fairseq.models  # noqa
  File "fairseq/fairseq/models/__init__.py", line 128, in <module>
    module = importlib.import_module('fairseq.models.' + model_name)
  File "conda-envs/bert/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "fairseq/fairseq/models/insertion_transformer.py", line 11, in <module>
    from fairseq.models.levenshtein_transformer import (
  File "fairseq/fairseq/models/levenshtein_transformer.py", line 25, in <module>
    from fairseq.models.model_utils import (
  File "fairseq/fairseq/models/model_utils.py", line 13, in <module>
    def script_skip_tensor_list(x: List[Tensor], mask):
  File "conda-envs/bert/lib/python3.7/site-packages/torch/jit/__init__.py", line 824, in script
    fn = torch._C._jit_script_compile(ast, _rcb, get_default_args(obj))
RuntimeError:
unexpected expression in variable initialization of for loop:
@torch.jit.script
def script_skip_tensor_list(x: List[Tensor], mask):
    res = [xi[mask] if xi.size(0) == mask.size(0) else xi[:, mask] for xi in x]
    outputs = []
    for i, t in enumerate(res):
        ~~~~ <--- HERE
        if t.numel() != 0:
            outputs.append(t)
        else:
            outputs.append(x[i])
    return outputs
```

`fairseq` was installed by `pip install --editable .` and downgrading `torch==1.1.0`
```
→ pip list
Package     Version         Location
----------- --------------- --------------------------------
certifi     2019.9.11
cffi        1.13.0
Cython      0.29.13
fairseq     0.8.0           /some_dir/fairseq
fastBPE     0.1.0
mkl-fft     1.0.14
mkl-random  1.1.0
mkl-service 2.3.0
numpy       1.17.2
olefile     0.46
Pillow      6.2.0
pip         19.3.1
portalocker 1.5.1
pycparser   2.19
regex       2019.8.19
sacrebleu   1.4.2
setuptools  41.4.0
six         1.12.0
torch       1.1.0
torchvision 0.4.1a0+d94043a
tqdm        4.36.1
typing      3.7.4.1
wheel       0.33.6
```
Please let me know if you need more information. Thanks

**Comment by mcshen99** [comment]
I think pytorch version is supposed to be >= 1.2.0

**Comment by MultiPath** [comment]
The code has been fixed. Can you try again?

**Comment by jatinganhotra** [comment]
Since the requirements section https://github.com/pytorch/fairseq#requirements-and-installation now lists pytorch >= 1.2.0.

I went ahead with 1.2.0 and was able to get it running.
