### ISSUE TITLE
bug :: translation_lev :: fairseq-generate fails due to problems with jit

### ISSUE THREAD

**Issue by sdll** [pytorch/fairseq#1361]
## Issue

I have trained the Levenshtein Transformer on Gigaword: 95k updates, 6.91 loss, 43.93 val ppl. You can get the weights [here (1.2 GB)](https://storage.googleapis.com/phramer/models/levenshtein/2019-11-10-17-47-41-lev_gigaword.pt).

Unfortunately, the following attempt to generate text fails:

```bash
python3 $FAIRSEQ_PATH/generate.py \
    $DATASET \
    --gen-subset test \
    --task translation_lev \
    --path $MODEL \
    --beam 1 --remove-bpe \
    --batch-size 400 \
    --iter-decode-max-iter 9 \
    --iter-decode-eos-penalty 0
```

It loads the model, but then crashes with the following error:

```
  File "/data/aiillarionov/fairseq-venv/lib/python3.6/site-packages/torch/_utils_internal.py", line 46, in get_source_lines_and_file
    sourcelines, file_lineno = inspect.getsourcelines(obj)
  File "/usr/lib/python3.6/inspect.py", line 955, in getsourcelines
    lines, lnum = findsource(object)
  File "/usr/lib/python3.6/inspect.py", line 786, in findsource
    raise OSError('could not get source code')
OSError: could not get source code

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/aiillarionov/fairseq/generate.py", line 194, in <module>
    cli_main()
  File "/data/aiillarionov/fairseq/generate.py", line 190, in cli_main
    main(args)
  File "/data/aiillarionov/fairseq/generate.py", line 104, in main
    hypos = task.inference_step(generator, models, sample, prefix_tokens)
  File "/data/aiillarionov/fairseq/fairseq/tasks/fairseq_task.py", line 265, in inference_step
    return generator.generate(models, sample, prefix_tokens=prefix_tokens)
  File "/data/aiillarionov/fairseq-venv/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/data/aiillarionov/fairseq/fairseq/iterative_refinement_generator.py", line 157, in generate
    prev_decoder_out, encoder_out, **decoder_options
  File "/data/aiillarionov/fairseq/fairseq/models/levenshtein_transformer.py", line 292, in forward_decoder
    eos_idx: int,
  File "/data/aiillarionov/fairseq-venv/lib/python3.6/site-packages/torch/jit/__init__.py", line 1226, in script
    fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))
  File "/data/aiillarionov/fairseq-venv/lib/python3.6/site-packages/torch/jit/__init__.py", line 1075, in _compile_and_register_class
    ast = get_jit_class_def(obj, obj.__name__)
  File "/data/aiillarionov/fairseq-venv/lib/python3.6/site-packages/torch/jit/frontend.py", line 148, in get_jit_class_def
    self_name=self_name) for method in methods]
  File "/data/aiillarionov/fairseq-venv/lib/python3.6/site-packages/torch/jit/frontend.py", line 148, in <listcomp>
    self_name=self_name) for method in methods]
  File "/data/aiillarionov/fairseq-venv/lib/python3.6/site-packages/torch/jit/frontend.py", line 160, in get_jit_def
    sourcelines, file_lineno, filename = get_source_lines_and_file(fn)
  File "/data/aiillarionov/fairseq-venv/lib/python3.6/site-packages/torch/_utils_internal.py", line 50, in get_source_lines_and_file
    "Make sure original .py files are available. Original error: {}").format(filename, e))
OSError: Can't get source for None. TorchScript requires source access in order to carry out compilation. Make sure original .py files are available. Original error: could not get source code
```

Could you please tell me how to fix this? Is there any way to disable jit compilation just to make it work?

## Environment

- fairseq: a92bcdad5a0dea6a440cc92976e4166811b16671, installed via `pip install -e .`
- pytorch: 1.3.1+cu100
- OS: Ubuntu 18.04.3 LTS

**Comment by sdll** [comment]
The Gigaword dataset has been taken from [here](https://github.com/harvardnlp/sent-summary).

cc: @MultiPath

**Comment by sdll** [comment]
Rolling back to previous versions (eg 50cf3bb596abba70a0770ad2308fed0f4d32a002) did not help, the generation fails with a  RuntimeError. The full trace is below:

```bash
Namespace(beam=1, bpe=None, cpu=False, criterion='cross_entropy', data='/data/aiillarionov/gigaword-bin', dataset_impl=None, decoding_format=None, diverse_beam_groups=-1, diverse_beam_strength=0.5, empty_cache_freq=0, force_anneal=None, fp16=False, fp16_init_scale=128, fp16_scale_tolerance=0.0, fp16_scale_window=None, gen_subset='test', iter_decode_eos_penalty=0.0, iter_decode_force_max_iter=False, iter_decode_max_iter=9, lazy_load=False, left_pad_source='True', left_pad_target='False', lenpen=1, load_alignments=False, log_format=None, log_interval=1000, lr_scheduler='fixed', lr_shrink=0.1, match_source_len=False, max_len_a=0, max_len_b=200, max_sentences=400, max_source_positions=1024, max_target_positions=1024, max_tokens=None, memory_efficient_fp16=False, min_len=1, min_loss_scale=0.0001, model_overrides='{}', momentum=0.99, nbest=1, no_beamable_mm=False, no_early_stop=False, no_progress_bar=False, no_repeat_ngram_size=0, noise='random_delete', num_shards=1, num_workers=1, optimizer='nag', path='/data/aiillarionov/gigaword-checkpoints/checkpoint_best.pt', prefix_size=0, print_alignment=False, print_step=False, quiet=False, raw_text=False, remove_bpe='@@ ', replace_unk=None, required_batch_size_multiple=8, results_path=None, sacrebleu=False, sampling=False, sampling_topk=-1, sampling_topp=-1.0, score_reference=False, seed=1, shard_id=0, skip_invalid_size_inputs_valid_test=False, source_lang=None, target_lang=None, task='translation_lev', tbmf_wrapper=False, temperature=1.0, tensorboard_logdir='', threshold_loss_scale=None, tokenizer=None, unkpen=0, unnormalized=False, upsample_primary=1, user_dir=None, warmup_updates=0, weight_decay=0.0)
| [articles] dictionary: 120416 types
| [summaries] dictionary: 120416 types
| loaded 400000 examples from: /data/aiillarionov/gigaword-bin/test.articles-summaries.articles
| loaded 400000 examples from: /data/aiillarionov/gigaword-bin/test.articles-summaries.summaries
| /data/aiillarionov/gigaword-bin test articles-summaries 400000 examples
| loading model(s) from /data/aiillarionov/gigaword-checkpoints/checkpoint_best.pt
  0%|                                                                               | 0/1000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/aiillarionov/fairseq/generate.py", line 194, in <module>
    cli_main()
  File "/home/aiillarionov/fairseq/generate.py", line 190, in cli_main
    main(args)
  File "/home/aiillarionov/fairseq/generate.py", line 104, in main
    hypos = task.inference_step(generator, models, sample, prefix_tokens)
  File "/home/aiillarionov/fairseq/fairseq/tasks/fairseq_task.py", line 260, in inference_step
    return generator.generate(models, sample, prefix_tokens=prefix_tokens)
  File "/data/aiillarionov/venv/local/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/aiillarionov/fairseq/fairseq/iterative_refinement_generator.py", line 157, in generate
    prev_decoder_out, encoder_out, **decoder_options
  File "/home/aiillarionov/fairseq/fairseq/models/levenshtein_transformer.py", line 470, in forward_decoder
    self.unk,
RuntimeError: ins_words() Expected a value of type 'Tensor' for argument 'word_ins_attn' but instead found type 'NoneType'.
Inferred 'word_ins_attn' to be of type 'Tensor' because it was not annotated with an explicit type.
Position: 3
Value: None
Declaration: ins_words(Tensor output_tokens, Tensor output_scores, Tensor attn, Tensor word_ins_attn, Tensor word_ins_pred, Tensor word_ins_scores, Tensor can_ins_word, int pad_idx, int unk_idx) -> ((Tensor, Tensor, Tensor))
```

**Comment by myleott** [comment]
This should be fixed now, can you please check again?

**Comment by sdll** [comment]
This is indeed fixed now, thanks! Closing the issue.
