### ISSUE TITLE
No dict.txt in RoBERTa custom classification example

### ISSUE THREAD

**Issue by verdimrc** [pytorch/fairseq#1407]
I encounter two errors related to `dict.txt` when trying out `fairseq/examples/roberta/README.custom_classification.md`.

# 1) When preprocessing label

This is the second command in section 4:

```bash
$ fairseq-preprocess \
    --only-source \
    --trainpref "aclImdb/train.label" \
    --validpref "aclImdb/dev.label" \
    --destdir "IMDB-bin/label" \
    --workers 60

Namespace(alignfile=None, bpe=None, cpu=False, criterion='cross_entropy', dataset_impl='mmap', destdir='IMDB-bin/label', fp16=False, fp16_init_scale=128, fp16_scale_tolerance=0.0, fp16_scale_window=None, joined_dictionary=False, log_format=None, log_interval=1000, lr_scheduler='fixed', memory_efficient_fp16=False, min_loss_scale=0.0001, no_progress_bar=False, nwordssrc=-1, nwordstgt=-1, only_source=True, optimizer='nag', padding_factor=8, seed=1, source_lang=None, srcdict=None, target_lang=None, task='translation', tbmf_wrapper=False, tensorboard_logdir='', testpref=None, tgtdict=None, threshold_loss_scale=None, thresholdsrc=0, thresholdtgt=0, tokenizer=None, trainpref='../data/aclImdb/train.label', user_dir=None, validpref='../data/aclImdb/dev.label', workers=2)
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/bin/fairseq-preprocess", line 11, in <module>
    sys.exit(cli_main())
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fairseq_cli/preprocess.py", line 265, in cli_main
    main(args)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fairseq_cli/preprocess.py", line 58, in main
    raise FileExistsError(dict_path(args.source_lang))
FileExistsError: IMDB-bin/label/dict.txt
```

If I add `--srcdict dict.txt` then the command works, although I'd like to confirm is this  fix is correct.

# 2) When training

The train command from section 5 produces this error:

```bash
Namespace(activation_dropout=0.0, activation_fn='gelu', adam_betas='(0.9, 0.98)', adam_eps=1e-06, arch='roberta_large', attention_dropout=0.1, best_checkpoint_metric='accuracy', bpe=None, bucket_cap_mb=25, clip_norm=0.0, cpu=False, criterion='sentence_prediction', curriculum=0, data='IMDB-bin/', dataset_impl=None, ddp_backend='c10d', device_id=0, disable_validation=False, distributed_backend='nccl', distributed_init_method=None, distributed_no_spawn=False, distributed_port=-1, distributed_rank=0, distributed_world_size=1, dropout=0.1, encoder_attention_heads=16, encoder_embed_dim=1024, encoder_ffn_embed_dim=4096, encoder_layers=24, end_learning_rate=0.0, find_unused_parameters=True, fix_batches_to_gpus=False, force_anneal=None, fp16=True, fp16_init_scale=4, fp16_scale_tolerance=0.0, fp16_scale_window=128, init_token=0, keep_interval_updates=-1, keep_last_epochs=-1, log_format=None, log_interval=1000, lr=[1e-05], lr_scheduler='polynomial_decay', max_epoch=10, max_positions=512, max_sentences=8, max_sentences_valid=8, max_tokens=4400, max_tokens_valid=4400, max_update=0, maximize_best_checkpoint_metric=True, memory_efficient_fp16=False, min_loss_scale=0.0001, min_lr=-1, no_epoch_checkpoints=False, no_last_checkpoints=False, no_progress_bar=False, no_save=False, no_save_optimizer_state=False, no_shuffle=False, num_classes=2, num_workers=1, optimizer='adam', optimizer_overrides='dict.txt', pooler_activation_fn='tanh', pooler_dropout=0.0, power=1.0, regression_target=False, required_batch_size_multiple=1, reset_dataloader=True, reset_lr_scheduler=False, reset_meters=True, reset_optimizer=True, restore_file='roberta.large/model.pt', save_dir='checkpoints', save_interval=1, save_interval_updates=0, save_predictions=None, seed=1, sentence_avg=False, separator_token=2, skip_invalid_size_inputs_valid_test=False, task='sentence_prediction', tbmf_wrapper=False, tensorboard_logdir='', threshold_loss_scale=1.0, tokenizer=None, total_num_update=7812, train_subset='train', truncate_sequence=True, update_freq=[4], use_bmuf=False, user_dir=None, valid_subset='valid', validate_interval=1, warmup_updates=469, weight_decay=0.1)
Traceback (most recent call last):
  File "train.py", line 337, in <module>
    cli_main()
  File "train.py", line 333, in cli_main
    main(args)
  File "train.py", line 44, in main
    task = tasks.setup_task(args)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fairseq/tasks/__init__.py", line 17, in setup_task
    return TASK_REGISTRY[args.task].setup_task(args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fairseq/tasks/sentence_prediction.py", line 81, in setup_task
    source=True,
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fairseq/tasks/sentence_prediction.py", line 67, in load_dictionary
    dictionary = Dictionary.load(filename)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fairseq/data/dictionary.py", line 185, in load
    d.add_from_file(f, ignore_utf_errors)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fairseq/data/dictionary.py", line 202, in add_from_file
    raise fnfe
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fairseq/data/dictionary.py", line 196, in add_from_file
    with open(f, 'r', encoding='utf-8') as fd:
FileNotFoundError: [Errno 2] No such file or directory: 'IMDB-bin/input0/dict.txt'
```

Any idea how to fix this error?

**Comment by verdimrc** [comment]
My apology, it's my mistake with wrong path.

**Comment by jack-pan-ai** [comment]
Hi, could you help to elaborate on how to fix the problem? Thanks a lot!!

**Comment by sshleifer** [comment]
Put [this file](https://gist.github.com/sshleifer/fc5b533c94a9540af7ce2f8dbdf58d41) at the proper path
