### ISSUE TITLE
Unable to run wav2vec on wav file

### ISSUE THREAD

**Issue by chrisspen** [pytorch/fairseq#1412]
I'm attempting to run the [wav2vec](https://github.com/pytorch/fairseq/tree/master/examples/wav2vec) example like:

    #!/usr/bin/env python
    import torch, librosa
    from fairseq.models.wav2vec import Wav2VecModel

    cp = torch.load('wav2vec_large.pt', map_location=torch.device('cpu'))
    model = Wav2VecModel.build_model(cp['args'], task=None)
    model.load_state_dict(cp['model'])
    model.eval()

    wave_file_path = 'sample.rate16k-mono.wav'
    signal, sr = librosa.load(wave_file_path)
    tensors = torch.from_numpy(signal)
    z = model.feature_extractor(tensors)
    c = model.feature_aggregator(z)
    print('c:', c)

but it's giving me the exception:

    Traceback (most recent call last):
      File "./test_word2vec.py", line 14, in <module>
        z = model.feature_extractor(tensors)
      File "~/.env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
        result = self.forward(*input, **kwargs)
      File "~/.env/lib/python3.7/site-packages/fairseq/models/wav2vec.py", line 286, in forward
        x = conv(x)
      File "~/.env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
        result = self.forward(*input, **kwargs)
      File "~/.env/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
        input = module(input)
      File "~/.env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
        result = self.forward(*input, **kwargs)
      File "~/.env/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 202, in forward
        self.padding, self.dilation, self.groups)
    RuntimeError: Expected 3-dimensional input for 3-dimensional weight 512 1 10, but got 2-dimensional input of size [63831, 1] instead

I can't find any documentation on how to run word2vec on an arbitrary wav file. Is this possible?

**Comment by ocelot43** [comment]
unsqueeze your input tensor might be work, but i don't know why.
`
tensors = torch.from_numpy(signal).unsqueeze(0)
z = model.feature_extractor(tensors)
c = model.feature_aggregator(z)
print('c:', c)
`

**Comment by huihuifan** [comment]
@alexeib ?

**Comment by SolbiatiAlessandro** [comment]
> unsqueeze your input tensor might be work, but i don't know why.
> 
> ```
> tensors = torch.from_numpy(signal).unsqueeze(0)
> z = model.feature_extractor(tensors) 
> c = model.feature_aggregator(z)
> print('c:', c) 
> ```

is just a reshaping problem, if you use `librosa` you get a shape that looks like
```
>>> tensors.shape
torch.Size([648384])
```
whereas the model expects something like

```
>>> wav_input_16khz.shape
torch.Size([1, 10000])
```

so the unsqueeze mentioned above will work
