### ISSUE TITLE
Error while using Fairseq-Generate

### ISSUE THREAD

**Issue by spprabhu** [pytorch/fairseq#1489]
fairseq-generate data-bin/wmt17_en_de_distill --path checkpoint_last.pt --beam 1 --remove-bpe
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/mmt/bin/fairseq-generate", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-generate')()
  File "/home/ubuntu/miniconda3/envs/mmt/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ubuntu/miniconda3/envs/mmt/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/ubuntu/miniconda3/envs/mmt/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/ubuntu/miniconda3/envs/mmt/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 779, in get_code
  File "<frozen importlib._bootstrap_external>", line 487, in _compile_bytecode
EOFError: marshal data too short

**Comment by spprabhu** [comment]
Hi any updates @kahne @lematt1991

**Comment by myleott** [comment]
This seems like something wrong with your fairseq installation... can you please try reinstalling fairseq?

We've also created new Issue templates, which ask for a bit more information which would help in debugging. I'm going to close this for now -- please reopen using one of the templates if this is still a problem.
