### ISSUE TITLE
Levenshtien Transformer ideal Hyperparameters

### ISSUE THREAD

**Issue by spprabhu** [pytorch/fairseq#1510]
Hey can you please suggest appropriate hyperparameters for training on 4 GPUs,with both normal and FP-16 Version.

Also what would be the parameters if I am using SIngle GPU and FP-16 to achieve same accuracy,should they be same as Base or should they be changed.
@myleott @MultiPath @kahne

**Comment by myleott** [comment]
Hyperparameters typically need to be tuned yourself, depending on the dataset.

FP16 shouldn't require changing any hyperparameters compared to FP32.

When training on fewer GPUs you need to use `--update-freq` to match the batch size.

**Comment by spprabhu** [comment]
Yeah but even that is giving CUDA : Memory error
This is what I am getting

Hi I am getting CUDA ERROR :OUT OF MEMORY.
I am using 4 V100 GPUS.KIndly please suggest appropriate parameters

(base) ubuntu@ip-172-31-8-60:~/fairseq$ fairseq-train data-bin/org --save-dir checkpoints/lv --ddp-backend=no_c10d --task translation_lev --criterion nat_loss --arch levenshtein_transformer --noise random_delete --share-all-embeddings --optimizer adam --adam-betas '(0.9,0.98)' --lr 0.0005 --lr-scheduler inverse_sqrt --min-lr '1e-09' --warmup-updates 10000 --warmup-init-lr '1e-07' --label-smoothing 0.1 --dropout 0.3 --weight-decay 0.01 --decoder-learned-pos --encoder-learned-pos --apply-bert-init --log-format 'simple' --log-interval 100 --fixed-validation-seed 7 --max-tokens 8000 --save-interval-updates 10000
| distributed init (rank 3): tcp://localhost:12081
| distributed init (rank 2): tcp://localhost:12081
| distributed init (rank 1): tcp://localhost:12081
| distributed init (rank 0): tcp://localhost:12081
| initialized host ip-172-31-8-60 as rank 3
| initialized host ip-172-31-8-60 as rank 2
| initialized host ip-172-31-8-60 as rank 1
| initialized host ip-172-31-8-60 as rank 0
Traceback (most recent call last):
File "/home/ubuntu/miniconda3/bin/fairseq-train", line 11, in 
load_entry_point('fairseq', 'console_scripts', 'fairseq-train')()
File "/home/ubuntu/fairseq/fairseq_cli/train.py", line 329, in cli_main
nprocs=args.distributed_world_size,
File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
while not spawn_context.join():
File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
raise Exception(msg)
Exception:

-- Process 3 terminated with the following error:
Traceback (most recent call last):
File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
fn(i, *args)
File "/home/ubuntu/fairseq/fairseq_cli/train.py", line 296, in distributed_main
main(args, init_distributed=True)
File "/home/ubuntu/fairseq/fairseq_cli/train.py", line 35, in main
args.distributed_rank = distributed_utils.distributed_init(args)
File "/home/ubuntu/fairseq/fairseq/distributed_utils.py", line 91, in distributed_init
dist.all_reduce(torch.zeros(1).cuda())
RuntimeError: CUDA error: out of memory

**Comment by myleott** [comment]
Please run `nvidia-smi`. You probably have other zombie processes using your GPU memory.

**Comment by MultiPath** [comment]
@spprabhu You should use --fp16 in order to run on --max-tokens 8000
In order to increase the batch-size, you can set --update-freq larger than 1 to enable gradient accumulation. It will simulate a bigger batch size. 
For example, if you set --max-tokens 8000 --update-freq 8 on single GPU, then you get batch-size as 64K which is the number we used in the paper,

**Comment by lematt1991** [comment]
Closing due to inactivity.
