### ISSUE TITLE
build failed in ppc64le

### ISSUE THREAD

**Issue by mindongjun** [pytorch/fairseq#1518]
I'm trying to install fairseq on our IBM server, that has ppc64le cpu.
I made powerai docker container 1.6.2, which has python3.6, pytorch 1.2.0
And install with pip command.
It worked on other x86 servers. Does it matter with cpu architecture?
Here is my error messages

```
Running setup.py install for fairseq ... error
    ERROR: Command errored out with exit status 1:
     command: /opt/anaconda/envs/wmlce/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ttzxccf7/fairseq/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ttzxccf7/fairseq/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-7g5agz8o/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-ttzxccf7/fairseq/
    Complete output (308 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-ppc64le-3.6
    creating build/lib.linux-ppc64le-3.6/examples
    copying examples/__init__.py -> build/lib.linux-ppc64le-3.6/examples
    creating build/lib.linux-ppc64le-3.6/fairseq
    copying fairseq/__init__.py -> build/lib.linux-ppc64le-3.6/fairseq
    copying fairseq/binarizer.py -> build/lib.linux-ppc64le-3.6/fairseq
    copying fairseq/bleu.py -> build/lib.linux-ppc64le-3.6/fairseq
    copying fairseq/checkpoint_utils.py -> build/lib.linux-ppc64le-3.6/fairseq
    copying fairseq/distributed_utils.py -> build/lib.linux-ppc64le-3.6/fairseq
    copying fairseq/file_utils.py -> build/lib.linux-ppc64le-3.6/fairseq
    copying fairseq/hub_utils.py -> build/lib.linux-ppc64le-3.6/fairseq
    copying fairseq/iterative_refinement_generator.py -> build/lib.linux-ppc64le-3.6/fairseq
    copying fairseq/legacy_distributed_data_parallel.py -> build/lib.linux-ppc64le-3.6/fairseq
    copying fairseq/meters.py -> build/lib.linux-ppc64le-3.6/fairseq
    copying fairseq/options.py -> build/lib.linux-ppc64le-3.6/fairseq
    copying fairseq/pdb.py -> build/lib.linux-ppc64le-3.6/fairseq
    copying fairseq/progress_bar.py -> build/lib.linux-ppc64le-3.6/fairseq
    copying fairseq/registry.py -> build/lib.linux-ppc64le-3.6/fairseq
    copying fairseq/search.py -> build/lib.linux-ppc64le-3.6/fairseq
    copying fairseq/sequence_generator.py -> build/lib.linux-ppc64le-3.6/fairseq
    copying fairseq/sequence_scorer.py -> build/lib.linux-ppc64le-3.6/fairseq
    copying fairseq/tokenizer.py -> build/lib.linux-ppc64le-3.6/fairseq
    copying fairseq/trainer.py -> build/lib.linux-ppc64le-3.6/fairseq
    copying fairseq/utils.py -> build/lib.linux-ppc64le-3.6/fairseq
    creating build/lib.linux-ppc64le-3.6/fairseq_cli
    copying fairseq_cli/__init__.py -> build/lib.linux-ppc64le-3.6/fairseq_cli
    copying fairseq_cli/eval_lm.py -> build/lib.linux-ppc64le-3.6/fairseq_cli
    copying fairseq_cli/generate.py -> build/lib.linux-ppc64le-3.6/fairseq_cli
    copying fairseq_cli/interactive.py -> build/lib.linux-ppc64le-3.6/fairseq_cli
    copying fairseq_cli/preprocess.py -> build/lib.linux-ppc64le-3.6/fairseq_cli
    copying fairseq_cli/score.py -> build/lib.linux-ppc64le-3.6/fairseq_cli
    copying fairseq_cli/setup.py -> build/lib.linux-ppc64le-3.6/fairseq_cli
    copying fairseq_cli/train.py -> build/lib.linux-ppc64le-3.6/fairseq_cli
    creating build/lib.linux-ppc64le-3.6/examples/noisychannel
    copying examples/noisychannel/__init__.py -> build/lib.linux-ppc64le-3.6/examples/noisychannel
    copying examples/noisychannel/rerank.py -> build/lib.linux-ppc64le-3.6/examples/noisychannel
    copying examples/noisychannel/rerank_generate.py -> build/lib.linux-ppc64le-3.6/examples/noisychannel
    copying examples/noisychannel/rerank_options.py -> build/lib.linux-ppc64le-3.6/examples/noisychannel
    copying examples/noisychannel/rerank_score_bw.py -> build/lib.linux-ppc64le-3.6/examples/noisychannel
    copying examples/noisychannel/rerank_score_lm.py -> build/lib.linux-ppc64le-3.6/examples/noisychannel
    copying examples/noisychannel/rerank_tune.py -> build/lib.linux-ppc64le-3.6/examples/noisychannel
    copying examples/noisychannel/rerank_utils.py -> build/lib.linux-ppc64le-3.6/examples/noisychannel
    creating build/lib.linux-ppc64le-3.6/examples/speech_recognition
    copying examples/speech_recognition/__init__.py -> build/lib.linux-ppc64le-3.6/examples/speech_recognition
    copying examples/speech_recognition/infer.py -> build/lib.linux-ppc64le-3.6/examples/speech_recognition
    copying examples/speech_recognition/w2l_decoder.py -> build/lib.linux-ppc64le-3.6/examples/speech_recognition
    creating build/lib.linux-ppc64le-3.6/examples/speech_recognition/criterions
    copying examples/speech_recognition/criterions/ASG_loss.py -> build/lib.linux-ppc64le-3.6/examples/speech_recognition/criterions
    copying examples/speech_recognition/criterions/CTC_loss.py -> build/lib.linux-ppc64le-3.6/examples/speech_recognition/criterions
    copying examples/speech_recognition/criterions/__init__.py -> build/lib.linux-ppc64le-3.6/examples/speech_recognition/criterions
    copying examples/speech_recognition/criterions/cross_entropy_acc.py -> build/lib.linux-ppc64le-3.6/examples/speech_recognition/criterions
    creating build/lib.linux-ppc64le-3.6/examples/speech_recognition/data
    copying examples/speech_recognition/data/__init__.py -> build/lib.linux-ppc64le-3.6/examples/speech_recognition/data
    copying examples/speech_recognition/data/asr_dataset.py -> build/lib.linux-ppc64le-3.6/examples/speech_recognition/data
    copying examples/speech_recognition/data/collaters.py -> build/lib.linux-ppc64le-3.6/examples/speech_recognition/data
    copying examples/speech_recognition/data/data_utils.py -> build/lib.linux-ppc64le-3.6/examples/speech_recognition/data
    copying examples/speech_recognition/data/replabels.py -> build/lib.linux-ppc64le-3.6/examples/speech_recognition/data
    creating build/lib.linux-ppc64le-3.6/examples/speech_recognition/models
    copying examples/speech_recognition/models/__init__.py -> build/lib.linux-ppc64le-3.6/examples/speech_recognition/models
    copying examples/speech_recognition/models/vggtransformer.py -> build/lib.linux-ppc64le-3.6/examples/speech_recognition/models
    copying examples/speech_recognition/models/w2l_conv_glu_enc.py -> build/lib.linux-ppc64le-3.6/examples/speech_recognition/models
    creating build/lib.linux-ppc64le-3.6/examples/speech_recognition/tasks
    copying examples/speech_recognition/tasks/__init__.py -> build/lib.linux-ppc64le-3.6/examples/speech_recognition/tasks
    copying examples/speech_recognition/tasks/speech_recognition.py -> build/lib.linux-ppc64le-3.6/examples/speech_recognition/tasks
    creating build/lib.linux-ppc64le-3.6/fairseq/criterions
    copying fairseq/criterions/__init__.py -> build/lib.linux-ppc64le-3.6/fairseq/criterions
    copying fairseq/criterions/adaptive_loss.py -> build/lib.linux-ppc64le-3.6/fairseq/criterions
    copying fairseq/criterions/binary_cross_entropy.py -> build/lib.linux-ppc64le-3.6/fairseq/criterions
    copying fairseq/criterions/composite_loss.py -> build/lib.linux-ppc64le-3.6/fairseq/criterions
    copying fairseq/criterions/cross_entropy.py -> build/lib.linux-ppc64le-3.6/fairseq/criterions
    copying fairseq/criterions/fairseq_criterion.py -> build/lib.linux-ppc64le-3.6/fairseq/criterions
    copying fairseq/criterions/label_smoothed_cross_entropy.py -> build/lib.linux-ppc64le-3.6/fairseq/criterions
    copying fairseq/criterions/label_smoothed_cross_entropy_with_alignment.py -> build/lib.linux-ppc64le-3.6/fairseq/criterions
    copying fairseq/criterions/legacy_masked_lm.py -> build/lib.linux-ppc64le-3.6/fairseq/criterions
    copying fairseq/criterions/masked_lm.py -> build/lib.linux-ppc64le-3.6/fairseq/criterions
    copying fairseq/criterions/nat_loss.py -> build/lib.linux-ppc64le-3.6/fairseq/criterions
    copying fairseq/criterions/sentence_prediction.py -> build/lib.linux-ppc64le-3.6/fairseq/criterions
    copying fairseq/criterions/sentence_ranking.py -> build/lib.linux-ppc64le-3.6/fairseq/criterions
    creating build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/__init__.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/append_token_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/backtranslation_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/base_wrapper_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/colorize_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/concat_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/concat_sentences_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/data_utils.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/denoising_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/dictionary.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/fairseq_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/id_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/indexed_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/iterators.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/language_pair_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/list_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/lm_context_window_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/lru_cache_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/mask_tokens_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/monolingual_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/multi_corpus_sampled_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/nested_dictionary_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/noising.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/num_samples_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/numel_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/offset_tokens_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/pad_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/plasma_utils.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/prepend_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/prepend_token_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/raw_label_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/replace_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/resampling_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/roll_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/round_robin_zip_datasets.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/sharded_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/sort_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/strip_token_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/subsample_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/token_block_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/transform_eos_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/transform_eos_lang_pair_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    copying fairseq/data/truncate_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data
    creating build/lib.linux-ppc64le-3.6/fairseq/models
    copying fairseq/models/__init__.py -> build/lib.linux-ppc64le-3.6/fairseq/models
    copying fairseq/models/cmlm_transformer.py -> build/lib.linux-ppc64le-3.6/fairseq/models
    copying fairseq/models/composite_encoder.py -> build/lib.linux-ppc64le-3.6/fairseq/models
    copying fairseq/models/distributed_fairseq_model.py -> build/lib.linux-ppc64le-3.6/fairseq/models
    copying fairseq/models/fairseq_decoder.py -> build/lib.linux-ppc64le-3.6/fairseq/models
    copying fairseq/models/fairseq_encoder.py -> build/lib.linux-ppc64le-3.6/fairseq/models
    copying fairseq/models/fairseq_incremental_decoder.py -> build/lib.linux-ppc64le-3.6/fairseq/models
    copying fairseq/models/fairseq_model.py -> build/lib.linux-ppc64le-3.6/fairseq/models
    copying fairseq/models/fconv.py -> build/lib.linux-ppc64le-3.6/fairseq/models
    copying fairseq/models/fconv_lm.py -> build/lib.linux-ppc64le-3.6/fairseq/models
    copying fairseq/models/fconv_self_att.py -> build/lib.linux-ppc64le-3.6/fairseq/models
    copying fairseq/models/insertion_transformer.py -> build/lib.linux-ppc64le-3.6/fairseq/models
    copying fairseq/models/iterative_nonautoregressive_transformer.py -> build/lib.linux-ppc64le-3.6/fairseq/models
    copying fairseq/models/levenshtein_transformer.py -> build/lib.linux-ppc64le-3.6/fairseq/models
    copying fairseq/models/lightconv.py -> build/lib.linux-ppc64le-3.6/fairseq/models
    copying fairseq/models/lightconv_lm.py -> build/lib.linux-ppc64le-3.6/fairseq/models
    copying fairseq/models/lstm.py -> build/lib.linux-ppc64le-3.6/fairseq/models
    copying fairseq/models/masked_lm.py -> build/lib.linux-ppc64le-3.6/fairseq/models
    copying fairseq/models/model_utils.py -> build/lib.linux-ppc64le-3.6/fairseq/models
    copying fairseq/models/multilingual_transformer.py -> build/lib.linux-ppc64le-3.6/fairseq/models
    copying fairseq/models/nonautoregressive_ensembles.py -> build/lib.linux-ppc64le-3.6/fairseq/models
    copying fairseq/models/nonautoregressive_transformer.py -> build/lib.linux-ppc64le-3.6/fairseq/models
    copying fairseq/models/transformer.py -> build/lib.linux-ppc64le-3.6/fairseq/models
    copying fairseq/models/transformer_from_pretrained_xlm.py -> build/lib.linux-ppc64le-3.6/fairseq/models
    copying fairseq/models/transformer_lm.py -> build/lib.linux-ppc64le-3.6/fairseq/models
    copying fairseq/models/wav2vec.py -> build/lib.linux-ppc64le-3.6/fairseq/models
    creating build/lib.linux-ppc64le-3.6/fairseq/modules
    copying fairseq/modules/__init__.py -> build/lib.linux-ppc64le-3.6/fairseq/modules
    copying fairseq/modules/adaptive_input.py -> build/lib.linux-ppc64le-3.6/fairseq/modules
    copying fairseq/modules/adaptive_softmax.py -> build/lib.linux-ppc64le-3.6/fairseq/modules
    copying fairseq/modules/beamable_mm.py -> build/lib.linux-ppc64le-3.6/fairseq/modules
    copying fairseq/modules/character_token_embedder.py -> build/lib.linux-ppc64le-3.6/fairseq/modules
    copying fairseq/modules/conv_tbc.py -> build/lib.linux-ppc64le-3.6/fairseq/modules
    copying fairseq/modules/downsampled_multihead_attention.py -> build/lib.linux-ppc64le-3.6/fairseq/modules
    copying fairseq/modules/dynamic_convolution.py -> build/lib.linux-ppc64le-3.6/fairseq/modules
    copying fairseq/modules/gelu.py -> build/lib.linux-ppc64le-3.6/fairseq/modules
    copying fairseq/modules/grad_multiply.py -> build/lib.linux-ppc64le-3.6/fairseq/modules
    copying fairseq/modules/highway.py -> build/lib.linux-ppc64le-3.6/fairseq/modules
    copying fairseq/modules/layer_norm.py -> build/lib.linux-ppc64le-3.6/fairseq/modules
    copying fairseq/modules/learned_positional_embedding.py -> build/lib.linux-ppc64le-3.6/fairseq/modules
    copying fairseq/modules/lightweight_convolution.py -> build/lib.linux-ppc64le-3.6/fairseq/modules
    copying fairseq/modules/linearized_convolution.py -> build/lib.linux-ppc64le-3.6/fairseq/modules
    copying fairseq/modules/logsumexp_moe.py -> build/lib.linux-ppc64le-3.6/fairseq/modules
    copying fairseq/modules/mean_pool_gating_network.py -> build/lib.linux-ppc64le-3.6/fairseq/modules
    copying fairseq/modules/multihead_attention.py -> build/lib.linux-ppc64le-3.6/fairseq/modules
    copying fairseq/modules/positional_embedding.py -> build/lib.linux-ppc64le-3.6/fairseq/modules
    copying fairseq/modules/scalar_bias.py -> build/lib.linux-ppc64le-3.6/fairseq/modules
    copying fairseq/modules/sinusoidal_positional_embedding.py -> build/lib.linux-ppc64le-3.6/fairseq/modules
    copying fairseq/modules/sparse_multihead_attention.py -> build/lib.linux-ppc64le-3.6/fairseq/modules
    copying fairseq/modules/sparse_transformer_sentence_encoder.py -> build/lib.linux-ppc64le-3.6/fairseq/modules
    copying fairseq/modules/sparse_transformer_sentence_encoder_layer.py -> build/lib.linux-ppc64le-3.6/fairseq/modules
    copying fairseq/modules/transformer_layer.py -> build/lib.linux-ppc64le-3.6/fairseq/modules
    copying fairseq/modules/transformer_sentence_encoder.py -> build/lib.linux-ppc64le-3.6/fairseq/modules
    copying fairseq/modules/transformer_sentence_encoder_layer.py -> build/lib.linux-ppc64le-3.6/fairseq/modules
    copying fairseq/modules/unfold.py -> build/lib.linux-ppc64le-3.6/fairseq/modules
    copying fairseq/modules/vggblock.py -> build/lib.linux-ppc64le-3.6/fairseq/modules
    creating build/lib.linux-ppc64le-3.6/fairseq/optim
    copying fairseq/optim/__init__.py -> build/lib.linux-ppc64le-3.6/fairseq/optim
    copying fairseq/optim/adadelta.py -> build/lib.linux-ppc64le-3.6/fairseq/optim
    copying fairseq/optim/adafactor.py -> build/lib.linux-ppc64le-3.6/fairseq/optim
    copying fairseq/optim/adagrad.py -> build/lib.linux-ppc64le-3.6/fairseq/optim
    copying fairseq/optim/adam.py -> build/lib.linux-ppc64le-3.6/fairseq/optim
    copying fairseq/optim/adamax.py -> build/lib.linux-ppc64le-3.6/fairseq/optim
    copying fairseq/optim/bmuf.py -> build/lib.linux-ppc64le-3.6/fairseq/optim
    copying fairseq/optim/fairseq_optimizer.py -> build/lib.linux-ppc64le-3.6/fairseq/optim
    copying fairseq/optim/fp16_optimizer.py -> build/lib.linux-ppc64le-3.6/fairseq/optim
    copying fairseq/optim/nag.py -> build/lib.linux-ppc64le-3.6/fairseq/optim
    copying fairseq/optim/sgd.py -> build/lib.linux-ppc64le-3.6/fairseq/optim
    creating build/lib.linux-ppc64le-3.6/fairseq/tasks
    copying fairseq/tasks/__init__.py -> build/lib.linux-ppc64le-3.6/fairseq/tasks
    copying fairseq/tasks/audio_pretraining.py -> build/lib.linux-ppc64le-3.6/fairseq/tasks
    copying fairseq/tasks/cross_lingual_lm.py -> build/lib.linux-ppc64le-3.6/fairseq/tasks
    copying fairseq/tasks/denoising.py -> build/lib.linux-ppc64le-3.6/fairseq/tasks
    copying fairseq/tasks/fairseq_task.py -> build/lib.linux-ppc64le-3.6/fairseq/tasks
    copying fairseq/tasks/language_modeling.py -> build/lib.linux-ppc64le-3.6/fairseq/tasks
    copying fairseq/tasks/legacy_masked_lm.py -> build/lib.linux-ppc64le-3.6/fairseq/tasks
    copying fairseq/tasks/masked_lm.py -> build/lib.linux-ppc64le-3.6/fairseq/tasks
    copying fairseq/tasks/multilingual_masked_lm.py -> build/lib.linux-ppc64le-3.6/fairseq/tasks
    copying fairseq/tasks/multilingual_translation.py -> build/lib.linux-ppc64le-3.6/fairseq/tasks
    copying fairseq/tasks/semisupervised_translation.py -> build/lib.linux-ppc64le-3.6/fairseq/tasks
    copying fairseq/tasks/sentence_prediction.py -> build/lib.linux-ppc64le-3.6/fairseq/tasks
    copying fairseq/tasks/sentence_ranking.py -> build/lib.linux-ppc64le-3.6/fairseq/tasks
    copying fairseq/tasks/translation.py -> build/lib.linux-ppc64le-3.6/fairseq/tasks
    copying fairseq/tasks/translation_from_pretrained_xlm.py -> build/lib.linux-ppc64le-3.6/fairseq/tasks
    copying fairseq/tasks/translation_lev.py -> build/lib.linux-ppc64le-3.6/fairseq/tasks
    copying fairseq/tasks/translation_moe.py -> build/lib.linux-ppc64le-3.6/fairseq/tasks
    creating build/lib.linux-ppc64le-3.6/fairseq/data/audio
    copying fairseq/data/audio/__init__.py -> build/lib.linux-ppc64le-3.6/fairseq/data/audio
    copying fairseq/data/audio/raw_audio_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data/audio
    creating build/lib.linux-ppc64le-3.6/fairseq/data/encoders
    copying fairseq/data/encoders/__init__.py -> build/lib.linux-ppc64le-3.6/fairseq/data/encoders
    copying fairseq/data/encoders/fastbpe.py -> build/lib.linux-ppc64le-3.6/fairseq/data/encoders
    copying fairseq/data/encoders/gpt2_bpe.py -> build/lib.linux-ppc64le-3.6/fairseq/data/encoders
    copying fairseq/data/encoders/gpt2_bpe_utils.py -> build/lib.linux-ppc64le-3.6/fairseq/data/encoders
    copying fairseq/data/encoders/hf_bert_bpe.py -> build/lib.linux-ppc64le-3.6/fairseq/data/encoders
    copying fairseq/data/encoders/moses_tokenizer.py -> build/lib.linux-ppc64le-3.6/fairseq/data/encoders
    copying fairseq/data/encoders/nltk_tokenizer.py -> build/lib.linux-ppc64le-3.6/fairseq/data/encoders
    copying fairseq/data/encoders/sentencepiece_bpe.py -> build/lib.linux-ppc64le-3.6/fairseq/data/encoders
    copying fairseq/data/encoders/space_tokenizer.py -> build/lib.linux-ppc64le-3.6/fairseq/data/encoders
    copying fairseq/data/encoders/subword_nmt_bpe.py -> build/lib.linux-ppc64le-3.6/fairseq/data/encoders
    copying fairseq/data/encoders/utils.py -> build/lib.linux-ppc64le-3.6/fairseq/data/encoders
    creating build/lib.linux-ppc64le-3.6/fairseq/data/legacy
    copying fairseq/data/legacy/__init__.py -> build/lib.linux-ppc64le-3.6/fairseq/data/legacy
    copying fairseq/data/legacy/block_pair_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data/legacy
    copying fairseq/data/legacy/masked_lm_dataset.py -> build/lib.linux-ppc64le-3.6/fairseq/data/legacy
    copying fairseq/data/legacy/masked_lm_dictionary.py -> build/lib.linux-ppc64le-3.6/fairseq/data/legacy
    creating build/lib.linux-ppc64le-3.6/fairseq/models/bart
    copying fairseq/models/bart/__init__.py -> build/lib.linux-ppc64le-3.6/fairseq/models/bart
    copying fairseq/models/bart/hub_interface.py -> build/lib.linux-ppc64le-3.6/fairseq/models/bart
    copying fairseq/models/bart/model.py -> build/lib.linux-ppc64le-3.6/fairseq/models/bart
    creating build/lib.linux-ppc64le-3.6/fairseq/models/roberta
    copying fairseq/models/roberta/__init__.py -> build/lib.linux-ppc64le-3.6/fairseq/models/roberta
    copying fairseq/models/roberta/alignment_utils.py -> build/lib.linux-ppc64le-3.6/fairseq/models/roberta
    copying fairseq/models/roberta/hub_interface.py -> build/lib.linux-ppc64le-3.6/fairseq/models/roberta
    copying fairseq/models/roberta/model.py -> build/lib.linux-ppc64le-3.6/fairseq/models/roberta
    creating build/lib.linux-ppc64le-3.6/fairseq/modules/dynamicconv_layer
    copying fairseq/modules/dynamicconv_layer/__init__.py -> build/lib.linux-ppc64le-3.6/fairseq/modules/dynamicconv_layer
    copying fairseq/modules/dynamicconv_layer/cuda_function_gen.py -> build/lib.linux-ppc64le-3.6/fairseq/modules/dynamicconv_layer
    copying fairseq/modules/dynamicconv_layer/dynamicconv_layer.py -> build/lib.linux-ppc64le-3.6/fairseq/modules/dynamicconv_layer
    copying fairseq/modules/dynamicconv_layer/setup.py -> build/lib.linux-ppc64le-3.6/fairseq/modules/dynamicconv_layer
    creating build/lib.linux-ppc64le-3.6/fairseq/modules/lightconv_layer
    copying fairseq/modules/lightconv_layer/__init__.py -> build/lib.linux-ppc64le-3.6/fairseq/modules/lightconv_layer
    copying fairseq/modules/lightconv_layer/cuda_function_gen.py -> build/lib.linux-ppc64le-3.6/fairseq/modules/lightconv_layer
    copying fairseq/modules/lightconv_layer/lightconv_layer.py -> build/lib.linux-ppc64le-3.6/fairseq/modules/lightconv_layer
    copying fairseq/modules/lightconv_layer/setup.py -> build/lib.linux-ppc64le-3.6/fairseq/modules/lightconv_layer
    creating build/lib.linux-ppc64le-3.6/fairseq/optim/lr_scheduler
    copying fairseq/optim/lr_scheduler/__init__.py -> build/lib.linux-ppc64le-3.6/fairseq/optim/lr_scheduler
    copying fairseq/optim/lr_scheduler/cosine_lr_scheduler.py -> build/lib.linux-ppc64le-3.6/fairseq/optim/lr_scheduler
    copying fairseq/optim/lr_scheduler/fairseq_lr_scheduler.py -> build/lib.linux-ppc64le-3.6/fairseq/optim/lr_scheduler
    copying fairseq/optim/lr_scheduler/fixed_schedule.py -> build/lib.linux-ppc64le-3.6/fairseq/optim/lr_scheduler
    copying fairseq/optim/lr_scheduler/inverse_square_root_schedule.py -> build/lib.linux-ppc64le-3.6/fairseq/optim/lr_scheduler
    copying fairseq/optim/lr_scheduler/polynomial_decay_schedule.py -> build/lib.linux-ppc64le-3.6/fairseq/optim/lr_scheduler
    copying fairseq/optim/lr_scheduler/reduce_lr_on_plateau.py -> build/lib.linux-ppc64le-3.6/fairseq/optim/lr_scheduler
    copying fairseq/optim/lr_scheduler/tri_stage_lr_scheduler.py -> build/lib.linux-ppc64le-3.6/fairseq/optim/lr_scheduler
    copying fairseq/optim/lr_scheduler/triangular_lr_scheduler.py -> build/lib.linux-ppc64le-3.6/fairseq/optim/lr_scheduler
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ttzxccf7/fairseq/setup.py", line 161, in <module>
        zip_safe=False,
      File "/opt/anaconda/envs/wmlce/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/opt/anaconda/envs/wmlce/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/anaconda/envs/wmlce/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/opt/anaconda/envs/wmlce/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/anaconda/envs/wmlce/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/opt/anaconda/envs/wmlce/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/opt/anaconda/envs/wmlce/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/anaconda/envs/wmlce/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/anaconda/envs/wmlce/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/opt/anaconda/envs/wmlce/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/anaconda/envs/wmlce/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/anaconda/envs/wmlce/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 84, in run
        _build_ext.run(self)
      File "/opt/anaconda/envs/wmlce/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/opt/anaconda/envs/wmlce/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/opt/anaconda/envs/wmlce/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 243, in build_extensions
        self._check_abi()
      File "/opt/anaconda/envs/wmlce/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 383, in _check_abi
        check_compiler_abi_compatibility(compiler)
      File "/opt/anaconda/envs/wmlce/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 173, in check_compiler_abi_compatibility
        if not check_compiler_ok_for_platform(compiler):
      File "/opt/anaconda/envs/wmlce/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 149, in check_compiler_ok_for_platform
        which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
      File "/opt/anaconda/envs/wmlce/lib/python3.6/subprocess.py", line 356, in check_output
        **kwargs).stdout
      File "/opt/anaconda/envs/wmlce/lib/python3.6/subprocess.py", line 438, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['which', 'g++']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/anaconda/envs/wmlce/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ttzxccf7/fairseq/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ttzxccf7/fairseq/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-7g5agz8o/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
```
#### My environment

 - fairseq Version (e.g., 1.0 or master): 0.8
 - PyTorch Version (e.g., 1.0) 1.2.0
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): pip install fairseq
 - Build command you used (if compiling from source): 
 - Python version: 3.6.9
 - CUDA/cuDNN version:10.1
 - GPU models and configuration:V100
 - Any other relevant information: AC922 IBM ppc64le

**Comment by myleott** [comment]
It looks like g++ isn’t installed, based on the error “Command '['which', 'g++']' returned non-zero exit status 1.” There are some C extensions that require it. Can you please install the gxx and try again?

**Comment by mindongjun** [comment]
Thank you. But first I installed, the error message shows no gcc. so I installed gcc. and then there is no g++ error again. Also I installed g++, the error message was same again.

**Comment by myleott** [comment]
What happens if you run:
```bash
$ which -a g++
```

Also, you're using anaconda, right? Can you install with: `conda install gxx_linux-ppc64le gcc_linux-ppc64le`, then try again?
