### ISSUE TITLE
Levenshtien Multiple Translations Issue

### ISSUE THREAD

**Issue by spprabhu** [pytorch/fairseq#1522]
Hi
I am trying to generate translations for Levenshtien Transformer using Teacher Rescorer .
However I am getting following errors

| [en] dictionary: 40624 types
| [de] dictionary: 40624 types
| loaded 3003 examples from: data-bin/test.en-de.en
| loaded 3003 examples from: data-bin/test.en-de.de
| data-bin test en-de 3003 examples
| loading model(s) from checkpoints/lv/checkpoint_best.pt:checkpoints/lv/checkpoint_baset.pt
  0%|                                                                                                                                        | 0/12 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/bin/fairseq-generate", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-generate')()
  File "/home/ubuntu/fairseq/fairseq_cli/generate.py", line 199, in cli_main
    main(args)
  File "/home/ubuntu/fairseq/fairseq_cli/generate.py", line 104, in main
    hypos = task.inference_step(generator, models, sample, prefix_tokens)
  File "/home/ubuntu/fairseq/fairseq/tasks/fairseq_task.py", line 265, in inference_step
    return generator.generate(models, sample, prefix_tokens=prefix_tokens)
  File "/home/ubuntu/miniconda3/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/ubuntu/fairseq/fairseq/iterative_refinement_generator.py", line 118, in generate
    assert self.beam_size > 1, "Reranking requires multiple translation for each example"

@kahne @myleott @MultiPath

**Comment by spprabhu** [comment]
This is my Generate Command

fairseq-generate     data-bin     --gen-subset test     --task translation_lev     --path checkpoints/lv/checkpoint_best.pt:checkpoints/lv/checkpoint_baset.pt     --iter-decode-max-iter 1           --iter-decode-with-external-reranker   --remove-bpe     --print-step --beam 1

**Comment by MultiPath** [comment]
@spprabhu  Levenshtein Transformer does not support "--iter-decode-with-external-reranker"

**Comment by spprabhu** [comment]
So how do I implement the AR Teacher Rescorer expert policy

**Comment by spprabhu** [comment]
So how do I implement the AR Teacher Rescorer expert policy
@MultiPath @myleott @kahne

**Comment by lematt1991** [comment]
Closing due to inactivity.
