### ISSUE TITLE
ValueError: unregistered extension code 24641

### ISSUE THREAD

**Issue by zhangyi0622** [pytorch/fairseq#1526]
hello, I have some problem following. I'd appreciate it if you could help me.
I processed the wmt17_en_de with command "fairseq-preprocess --source-lang en --target-lang de --joined-dictionary --trainpref $TEXT/train --validpref $TEXT/valid --testpref $TEXT/test --destdir data-bin/wmt_en_de --thresholdtgt 0 --thresholdsrc 0 --workers 20" 
and then I got dataset, put them into the model with command "fairseq-train --ddp-backend='no_c10d' \
    data-bin/wmt17_en_de \
    --max-update 100000 \
    --task translation_moe \
    --method hMoElp --mean-pool-gating-network \
    --num-experts 3 \
    --arch transformer_wmt_en_de --share-all-embeddings \
    --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 \
    --lr-scheduler inverse_sqrt --warmup-init-lr 1e-07 --warmup-updates 4000 \
    --lr 0.0007 --min-lr 1e-09 \
    --dropout 0.1 --weight-decay 0.0 --criterion cross_entropy \
    --max-tokens 3584"
but I got the error following:
| model transformer_wmt_en_de, criterion CrossEntropyCriterion
| num. model params: 66747907 (num. trained: 66747907)
| training on 2 GPUs
| max tokens per GPU = 3584 and max sentences per GPU = None
| no existing checkpoint found checkpoints/checkpoint_last.pt
| loading train data for epoch 0
| loaded 3961179 examples from: data-bin/wmt17_en_de/train.en-de.en
| loaded 3961179 examples from: data-bin/wmt17_en_de/train.en-de.de
| data-bin/wmt17_en_de train en-de 3961179 examples
| epoch 001:   0%|                                                       | 0/18379 [00:00<?, ?it/s]| OOM: Ran out of memory with exception: CUDA out of memory. Tried to allocate 588.00 MiB (GPU 0; 7.93 GiB total capacity; 2.91 GiB already allocated; 99.56 MiB free; 241.52 MiB cached)
| WARNING: attempting to recover from OOM in forward/backward pass
Traceback (most recent call last):                                                                 
  File "/home/zhangyi/.conda/envs/beer/bin/fairseq-train", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-train')()
  File "/home/zhangyi/fairseq/fairseq_cli/train.py", line 332, in cli_main
    nprocs=args.distributed_world_size,
  File "/home/zhangyi/.conda/envs/beer/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/zhangyi/.conda/envs/beer/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/zhangyi/.conda/envs/beer/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/zhangyi/fairseq/fairseq_cli/train.py", line 299, in distributed_main
    main(args, init_distributed=True)
  File "/home/zhangyi/fairseq/fairseq_cli/train.py", line 89, in main
    train(args, trainer, task, epoch_itr)
  File "/home/zhangyi/fairseq/fairseq_cli/train.py", line 130, in train
    log_output = trainer.train_step(samples)
  File "/home/zhangyi/fairseq/fairseq/trainer.py", line 387, in train_step
    [logging_outputs, sample_sizes, ooms, self._prev_grad_norm]
  File "/home/zhangyi/fairseq/fairseq/distributed_utils.py", line 177, in all_gather_list
    result.append(pickle.loads(bytes(out_buffer[2 : size + 2].tolist())))
ValueError: unregistered extension code 24641

my environment:
python  3.7.1
pytorch 1.2.0           py3.7_cuda10.0.130_cudnn7.6.2_0
os: Linux
install fairseq:
git clone https://github.com/pytorch/fairseq
cd fairseq
pip install --editable .
Thank you very much!

**Comment by zhangyi0622** [comment]
the problem is solved in #1294
--max-tokens 3584 is too large
