### ISSUE TITLE
How do I set the encoder layer and the hidden layer during training?

### ISSUE THREAD

**Issue by DonnieZhang586** [pytorch/fairseq#1548]
CUDA_VISIBLE_DEVICES=2,3,4,5,6,7,8  python train.py data-bin/DBNQA_data --encoder-layers 15 --decoder-layers 15  --lr 0.5 --dropout 0.2 --criterion cross_entropy --optimizer sgd --max-tokens 4000 --max-epoch 500 --arch fconv --save-dir checkpoints1/en-sparql

 [en] dictionary: 84016 types
| [sparql] dictionary: 107752 types
| loaded 89449 examples from: data-bin/DBNQA_data/valid.en-sparql.en
| loaded 89449 examples from: data-bin/DBNQA_data/valid.en-sparql.sparql
| data-bin/DBNQA_data valid en-sparql 89449 examples
Traceback (most recent call last):
  File "train.py", line 337, in <module>
    cli_main()
  File "train.py", line 329, in cli_main
    nprocs=args.distributed_world_size,
  File "/home1/zd/anaconda3/envs/fairseq2seq/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home1/zd/anaconda3/envs/fairseq2seq/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/home1/zd/anaconda3/envs/fairseq2seq/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home1/zd/fairseq/train.py", line 296, in distributed_main
    main(args, init_distributed=True)
  File "/home1/zd/fairseq/train.py", line 51, in main
    model = task.build_model(args)
  File "/home1/zd/fairseq/fairseq/tasks/fairseq_task.py", line 185, in build_model
    return models.build_model(args, self)
  File "/home1/zd/fairseq/fairseq/models/__init__.py", line 48, in build_model
    return ARCH_MODEL_REGISTRY[args.arch].build_model(args, task)
  File "/home1/zd/fairseq/fairseq/models/fconv.py", line 114, in build_model
    max_positions=args.max_source_positions,
  File "/home1/zd/fairseq/fairseq/models/fconv.py", line 168, in __init__
    convolutions = extend_conv_spec(convolutions)
  File "/home1/zd/fairseq/fairseq/models/fconv.py", line 559, in extend_conv_spec
    for spec in convolutions:
TypeError: 'int' object is not iterable

**Comment by myleott** [comment]
You specified an invalid format for `--encoder-layers` and `--decoder-layers`. You need to give the convolutions widths as well. See the default config as a reference:

https://github.com/pytorch/fairseq/blob/9b19ede0a986a5362fa0bd78b753c908d613ebb2/fairseq/models/fconv.py#L656-L663
