### ISSUE TITLE
Unable to run interactive.py for a pretrained model. 

### ISSUE THREAD

**Issue by AashJ** [pytorch/fairseq#156]
When running the interactive.py script i run into the following error:

```python interactive.py  --path $MODEL_DIR/model.pt $MODEL_DIR  --beam 5
Namespace(beam=5, cpu=False, data='wmt14.en-fr.fconv-py', gen_subset='test', lenpen=1, log_format=None, log_interval=1000, max_len_a=0, max_len_b=200, max_sentences=None, max_source_positions=1024, max_target_positions=1024, max_tokens=6000, nbest=1, no_beamable_mm=False, no_early_stop=False, no_progress_bar=False, num_shards=1, path=['wmt14.en-fr.fconv-py/model.pt'], prefix_size=0, quiet=False, remove_bpe=None, replace_unk=None, sampling=False, score_reference=False, seed=1, shard_id=0, skip_invalid_size_inputs_valid_test=False, source_lang=None, target_lang=None, unkpen=0, unnormalized=False)
| loading model(s) from wmt14.en-fr.fconv-py/model.pt
Traceback (most recent call last):
  File "interactive.py", line 83, in <module>
    main(args)
  File "interactive.py", line 28, in main
    models, model_args = utils.load_ensemble_for_inference(args.path, data_dir=args.data)
  File "/workspace/fairseq/fairseq/utils.py", line 149, in load_ensemble_for_inference
    model = models.build_model(args, src_dict, dst_dict)
  File "/workspace/fairseq/fairseq/models/__init__.py", line 23, in build_model
    return ARCH_MODEL_REGISTRY[args.arch].build_model(args, src_dict, dst_dict)
  File "/workspace/fairseq/fairseq/models/fconv.py", line 62, in build_model
    if args.encoder_embed_path:
AttributeError: 'Namespace' object has no attribute 'encoder_embed_path'

Any idea on what I'm doing incorrectly?

**Comment by liudany** [comment]
met the same question.
