### ISSUE TITLE
Training failed to start when using multiple GPUs

### ISSUE THREAD

**Issue by TingxunShi** [pytorch/fairseq#1635]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?

When I was trying to train a model using a corpus contains about 100M lines, it crashed and reported a multiprocess related error which probably involves torch:

```
2020-01-20 19:32:08.000 [INFO] [Driver] | model transformer_vaswani_wmt_en_de_big, criterion LabelSmoothedCrossEntropyCriterion
2020-01-20 19:32:08.000 [INFO] [Driver] | num. model params: 260337664 (num. trained: 260337664)
2020-01-20 19:32:41.000 [INFO] [Driver] | training on 4 GPUs
2020-01-20 19:32:41.000 [INFO] [Driver] | max tokens per GPU = 2048 and max sentences per GPU = None
2020-01-20 19:32:41.000 [INFO] [Driver] | no existing checkpoint found checkpoints/checkpoint_last.pt
2020-01-20 19:32:41.000 [INFO] [Driver] | loading train data for epoch 0
2020-01-20 19:32:51.000 [INFO] [Driver] | loaded *** examples from: data_bin/train.zh-en.zh
2020-01-20 19:33:03.000 [INFO] [Driver] | loaded *** examples from: data_bin/train.zh-en.en
2020-01-20 19:33:03.000 [INFO] [Driver] | data_bin train zh-en *** examples
2020-01-20 19:45:24.000 [INFO] [Driver] Traceback (most recent call last):
2020-01-20 19:45:24.000 [INFO] [Driver] File "/opt/conda/bin/fairseq-train", line 11, in <module>
2020-01-20 19:45:24.000 [INFO] [Driver] load_entry_point('fairseq==0.9.0', 'console_scripts', 'fairseq-train')()
2020-01-20 19:45:24.000 [INFO] [Driver] File "/opt/conda/lib/python3.7/site-packages/fairseq_cli/train.py", line 329, in cli_main
2020-01-20 19:45:24.000 [INFO] [Driver] nprocs=args.distributed_world_size,
2020-01-20 19:45:24.000 [INFO] [Driver] File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
2020-01-20 19:45:24.000 [INFO] [Driver] while not spawn_context.join():
2020-01-20 19:45:24.000 [INFO] [Driver] File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 107, in join
2020-01-20 19:45:24.000 [INFO] [Driver] (error_index, name)
2020-01-20 19:45:24.000 [INFO] [Driver] Exception: process 1 terminated with signal SIGKILL
```

I tried to use a single GPU instead and it seems everything was OK (at least it trained several batches but took too long time). What's more, using the same hyperparameters I was able to train a model before.

Please kindly help me to figure out why, thanks a lot.

#### Code

```bash
# Here is my script for training 

data_dir=data_bin
save_dir=checkpoints

fairseq-train $data_dir \
  --task translation \
  --dataset-impl lazy \    # I used the same strategy to preprocess the corpus
  --arch transformer_vaswani_wmt_en_de_big \
  --save-dir $save_dir \
  --optimizer adam \
    --adam-betas "(0.9,0.98)" \
  --clip-norm 0.0 \
  --lr-scheduler inverse_sqrt \
  --lr 0.001 \
  --min-lr 1e-09 \
  --criterion label_smoothed_cross_entropy \
  --log-format json \
  --max-tokens 2048 \
  --update-freq 8 \
  --encoder-normalize-before \
  --decoder-normalize-before \
  --dropout 0.3 \
  --relu-dropout 0.1 \
  --attention-dropout 0.1 \
  --max-update 10000000 \
  --max-epoch 100 \
  --keep-interval-updates 100 \
  --save-interval-updates 5000 \
  --log-interval 100 \
  --share-decoder-input-output-embed \
  --fp16 \
  --warmup-updates 15000 \
  --warmup-init-lr 1e-07
```

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): 0.9
 - PyTorch Version (e.g., 1.0): 1.3 perhaps
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: 10.0
 - GPU models and configuration: Tesla V100
 - Any other relevant information:

**Comment by TingxunShi** [comment]
After adding the option --ddp-backend=no_c10d training seems good now, but still want to confirm this is a right solution = =

**Comment by myleott** [comment]
`--ddp-backend=no_c10d` is fine. It's a bit more robust, but can be slightly slower when training on multiple nodes. Since you're training on a single node it won't make any difference, so might as well use it.

**Comment by TingxunShi** [comment]
@myleott Sorry to update this issue again. The task crashed due to some issue so I restarted it. Although I've added `--ddp-backend=no_c10d`, the same error occured again and I have no idea now. Really appreciate if you could kindly give any other advice

**Comment by myleott** [comment]
Can you try updating to fairseq master and pytorch 1.4? It's possible it's a pytorch bug, and the latest version of fairseq should have better logging in case of some failures.

**Comment by TingxunShi** [comment]
Thanks for the advice
