### ISSUE TITLE
Preprocess BART on WNLI task gives ZeroDivisionError

### ISSUE THREAD

**Issue by vineetk1** [pytorch/fairseq#1675]
### To Reproduce

1. Run cmd './examples/roberta/preprocess_GLUE_tasks.sh glue_data WNLI'
2. See error 'ZeroDivisionError: division by zero'

--2020-02-02 14:42:15--  https://dl.fbaipublicfiles.com/fairseq/gpt2_bpe/encoder.json
Resolving dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)... 104.20.6.166, 104.20.22.166, 2606:4700:10::6814:16a6, ...
Connecting to dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)|104.20.6.166|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1042301 (1018K) [text/plain]
Saving to: ‘encoder.json’

encoder.json                    100%[======================================================>]   1018K  1.16MB/s    in 0.9s    

2020-02-02 14:42:16 (1.16 MB/s) - ‘encoder.json’ saved [1042301/1042301]

--2020-02-02 14:42:16--  https://dl.fbaipublicfiles.com/fairseq/gpt2_bpe/vocab.bpe
Resolving dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)... 104.20.22.166, 104.20.6.166, 2606:4700:10::6814:6a6, ...
Connecting to dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)|104.20.22.166|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 456318 (446K) [text/plain]
Saving to: ‘vocab.bpe’

vocab.bpe                       100%[======================================================>] 445.62K   964KB/s    in 0.5s    

2020-02-02 14:42:17 (964 KB/s) - ‘vocab.bpe’ saved [456318/456318]

--2020-02-02 14:42:17--  https://dl.fbaipublicfiles.com/fairseq/gpt2_bpe/dict.txt
Resolving dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)... 104.20.22.166, 104.20.6.166, 2606:4700:10::6814:6a6, ...
Connecting to dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)|104.20.22.166|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 603290 (589K) [text/plain]
Saving to: ‘dict.txt’

dict.txt                        100%[======================================================>] 589.15K  1.01MB/s    in 0.6s    

2020-02-02 14:42:18 (1.01 MB/s) - ‘dict.txt’ saved [603290/603290]

Preprocessing WNLI
Raw data as downloaded from glue website: glue_data/WNLI
cut: invalid field value ‘glue_data/WNLI/processed/train.tsv’
Try 'cut --help' for more information.
cut: invalid field value ‘glue_data/WNLI/processed/train.tsv’
Try 'cut --help' for more information.
cut: invalid field value ‘glue_data/WNLI/processed/train.tsv’
Try 'cut --help' for more information.
BPE encoding train/input0
BPE encoding train/input1
cut: invalid field value 'glue_data/WNLI/processed/dev.tsv'
Try 'cut --help' for more information.
cut: invalid field value 'glue_data/WNLI/processed/dev.tsv'
Try 'cut --help' for more information.
cut: invalid field value 'glue_data/WNLI/processed/dev.tsv'
Try 'cut --help' for more information.
BPE encoding dev/input0
BPE encoding dev/input1
cut: invalid field value 'glue_data/WNLI/processed/test.tsv'
Try 'cut --help' for more information.
cut: invalid field value 'glue_data/WNLI/processed/test.tsv'
Try 'cut --help' for more information.
BPE encoding test/input0
BPE encoding test/input1
2020-02-02 14:42:25 | INFO | fairseq_cli.preprocess | Namespace(align_suffix=None, alignfile=None, all_gather_list_size=16384, bpe=None, cpu=False, criterion='cross_entropy', dataset_impl='mmap', destdir='WNLI-bin/input0', empty_cache_freq=0, fp16=False, fp16_init_scale=128, fp16_no_flatten_grads=False, fp16_scale_tolerance=0.0, fp16_scale_window=None, joined_dictionary=False, log_format=None, log_interval=1000, lr_scheduler='fixed', memory_efficient_fp16=False, min_loss_scale=0.0001, no_progress_bar=False, nwordssrc=-1, nwordstgt=-1, only_source=True, optimizer='nag', padding_factor=8, seed=1, source_lang=None, srcdict='dict.txt', target_lang=None, task='translation', tensorboard_logdir='', testpref='glue_data/WNLI/processed/test.input0', tgtdict=None, threshold_loss_scale=None, thresholdsrc=0, thresholdtgt=0, tokenizer=None, trainpref='glue_data/WNLI/processed/train.input0', user_dir=None, validpref='glue_data/WNLI/processed/dev.input0', workers=60)
2020-02-02 14:42:26 | INFO | fairseq_cli.preprocess | [None] Dictionary: 50263 types
Traceback (most recent call last):
  File "/home/vin/.local/bin/fairseq-preprocess", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-preprocess')()
  File "/home/vin/bart/fairseq/fairseq_cli/preprocess.py", line 360, in cli_main
    main(args)
  File "/home/vin/bart/fairseq/fairseq_cli/preprocess.py", line 259, in main
    make_all(args.source_lang, src_dict)
  File "/home/vin/bart/fairseq/fairseq_cli/preprocess.py", line 241, in make_all
    make_dataset(vocab, args.trainpref, "train", lang, num_workers=args.workers)
  File "/home/vin/bart/fairseq/fairseq_cli/preprocess.py", line 237, in make_dataset
    make_binary_dataset(vocab, input_prefix, output_prefix, lang, num_workers)
  File "/home/vin/bart/fairseq/fairseq_cli/preprocess.py", line 169, in make_binary_dataset
    100 * sum(replaced.values()) / n_seq_tok[1],
ZeroDivisionError: division by zero

### Environment

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0): 1.3.1
 - OS (e.g., Linux): Linux (ubuntu)
 - How you installed fairseq (`pip`, source): fork and clone from github
 - Build command you used (if compiling from source):
 - Python version: Python 3.6.8 (default, Jan 14 2019, 11:02:34)
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: Nvidia GTX 1080
 - Any other relevant information:

**Comment by pipibjc** [comment]
cc @yinhanliu, @ngoyal2707

**Comment by myleott** [comment]
I see these errors in your log above: `cut: invalid field value 'glue_data/WNLI/processed/dev.tsv'
Try 'cut --help' for more information.`

What operating system are you using?

**Comment by vineetk1** [comment]
I am using Linux 4.15.0-58-generic, Ubuntu 18.04.3 LTS.
Preprocessing works when I use the task QQP but does not work with task WNLI.
I am assuming that tasks that are part of the list in Line 26 work:
`  TASKS="QQP MNLI QNLI MRPC RTE STS-B SST-2 CoLA"
`
Since WNLI is not in the list of tasks, the following variables are incorrectly initialized: INPUT_COLUMNS   TEST_INPUT_COLUMNS   LABEL_COLUMN   INPUT_COUNT. This is my assumption. I have not tested it.

**Comment by myleott** [comment]
Ah right, that script doesn't support WNLI.

**Comment by jinruiyang** [comment]
I got the same errors even on RTE, anyone knows to how to  solve it?
