### ISSUE TITLE
Convert FP32 model to FP16 model and resume training.

### ISSUE THREAD

**Issue by ever4244** [pytorch/fairseq#1739]
What would happen if I train with FP32 for some epochs and then want to convert it to FP16 and continue training?
Can I just add --FP16 option and hope for some force conversion between float32 and float16, or do I have to do something extra manually?

**Comment by myleott** [comment]
I've never tried this before, so not sure. Something might break in the optimizer, but it might also work. Please try it and report back!

**Comment by ever4244** [comment]
> I've never tried this before, so not sure. Something might break in the optimizer, but it might also work. Please try it and report back!

I added:
--fp16 --reset-optimizer

--reset-optimizer is forced to add due to a different optimizer error.

The result is an overflow gradient. 
I am doing this because I want to move from a 1080Ti trained FP32 model to a 2080ti machine with FP16 support.
`
2020-02-25 14:47:06 | INFO | fairseq_cli.train | model laser, criterion CrossEntropyCriterion
2020-02-25 14:47:06 | INFO | fairseq_cli.train | num. model params: 178511292 (num. trained: 178511292)
2020-02-25 14:47:07 | INFO | fairseq_cli.train | training on 3 GPUs
2020-02-25 14:47:07 | INFO | fairseq_cli.train | max tokens per GPU = 2000 and max sentences per GPU = None
2020-02-25 14:47:09 | INFO | fairseq.trainer | loaded checkpoint checkpoints/laser_lstm_fp32_ep6/checkpoint_last.pt (epoch 6 @ 0 updates)
2020-02-25 14:47:09 | INFO | fairseq.trainer | loading train data for epoch 6
2020-02-25 14:47:09 | INFO | fairseq.data.data_utils | loaded 1869785 examples from: data-bin/europarl.de_en_es_fr.bpe40k/train.de-en.de
2020-02-25 14:47:09 | INFO | fairseq.data.data_utils | loaded 1869785 examples from: data-bin/europarl.de_en_es_fr.bpe40k/train.de-en.en
2020-02-25 14:47:09 | INFO | fairseq.tasks.translation | data-bin/europarl.de_en_es_fr.bpe40k train de-en 1869785 examples
2020-02-25 14:47:10 | INFO | fairseq.data.data_utils | loaded 1747420 examples from: data-bin/europarl.de_en_es_fr.bpe40k/train.de-es.de
2020-02-25 14:47:10 | INFO | fairseq.data.data_utils | loaded 1747420 examples from: data-bin/europarl.de_en_es_fr.bpe40k/train.de-es.es
2020-02-25 14:47:10 | INFO | fairseq.tasks.translation | data-bin/europarl.de_en_es_fr.bpe40k train de-es 1747420 examples
2020-02-25 14:47:10 | INFO | fairseq.data.data_utils | loaded 1938685 examples from: data-bin/europarl.de_en_es_fr.bpe40k/train.en-es.en
2020-02-25 14:47:10 | INFO | fairseq.data.data_utils | loaded 1938685 examples from: data-bin/europarl.de_en_es_fr.bpe40k/train.en-es.es
2020-02-25 14:47:10 | INFO | fairseq.tasks.translation | data-bin/europarl.de_en_es_fr.bpe40k train en-es 1938685 examples
2020-02-25 14:47:10 | INFO | fairseq.data.data_utils | loaded 1938685 examples from: data-bin/europarl.de_en_es_fr.bpe40k/train.en-es.es
2020-02-25 14:47:10 | INFO | fairseq.data.data_utils | loaded 1938685 examples from: data-bin/europarl.de_en_es_fr.bpe40k/train.en-es.en
2020-02-25 14:47:10 | INFO | fairseq.tasks.translation | data-bin/europarl.de_en_es_fr.bpe40k train es-en 1938685 examples
2020-02-25 14:47:10 | INFO | fairseq.data.data_utils | loaded 1954044 examples from: data-bin/europarl.de_en_es_fr.bpe40k/train.en-fr.fr
2020-02-25 14:47:11 | INFO | fairseq.data.data_utils | loaded 1954044 examples from: data-bin/europarl.de_en_es_fr.bpe40k/train.en-fr.en
2020-02-25 14:47:11 | INFO | fairseq.tasks.translation | data-bin/europarl.de_en_es_fr.bpe40k train fr-en 1954044 examples
2020-02-25 14:47:11 | INFO | fairseq.data.data_utils | loaded 1895440 examples from: data-bin/europarl.de_en_es_fr.bpe40k/train.es-fr.fr
2020-02-25 14:47:11 | INFO | fairseq.data.data_utils | loaded 1895440 examples from: data-bin/europarl.de_en_es_fr.bpe40k/train.es-fr.es
2020-02-25 14:47:11 | INFO | fairseq.tasks.translation | data-bin/europarl.de_en_es_fr.bpe40k train fr-es 1895440 examples
2020-02-25 15:00:13 | INFO | fairseq.trainer | NOTE: overflow detected, setting loss scale to: 64.0
2020-02-25 15:00:13 | INFO | fairseq.trainer | NOTE: overflow detected, setting loss scale to: 32.0
2020-02-25 15:00:14 | INFO | fairseq.trainer | NOTE: overflow detected, setting loss scale to: 16.0
2020-02-25 15:00:14 | INFO | fairseq.trainer | NOTE: overflow detected, setting loss scale to: 8.0
2020-02-25 15:00:14 | INFO | fairseq.trainer | NOTE: overflow detected, setting loss scale to: 4.0
2020-02-25 15:00:15 | INFO | fairseq.trainer | NOTE: overflow detected, setting loss scale to: 2.0
2020-02-25 15:00:15 | INFO | fairseq.trainer | NOTE: overflow detected, setting loss scale to: 1.0
2020-02-25 15:00:16 | INFO | fairseq.trainer | NOTE: overflow detected, setting loss scale to: 0.5
2020-02-25 15:00:16 | INFO | fairseq.trainer | NOTE: overflow detected, setting loss scale to: 0.25
2020-02-25 15:00:17 | INFO | fairseq.trainer | NOTE: overflow detected, setting loss scale to: 0.125
2020-02-25 15:00:17 | INFO | fairseq.trainer | NOTE: overflow detected, setting loss scale to: 0.0625
2020-02-25 15:00:18 | INFO | fairseq.trainer | NOTE: overflow detected, setting loss scale to: 0.03125
2020-02-25 15:00:18 | INFO | fairseq.trainer | NOTE: overflow detected, setting loss scale to: 0.015625
2020-02-25 15:00:18 | INFO | fairseq.trainer | NOTE: overflow detected, setting loss scale to: 0.0078125
2020-02-25 15:00:19 | INFO | fairseq.trainer | NOTE: overflow detected, setting loss scale to: 0.00390625
2020-02-25 15:00:19 | INFO | fairseq.trainer | NOTE: overflow detected, setting loss scale to: 0.001953125
2020-02-25 15:00:20 | INFO | fairseq.trainer | NOTE: overflow detected, setting loss scale to: 0.0009765625
2020-02-25 15:00:20 | INFO | fairseq.trainer | NOTE: overflow detected, setting loss scale to: 0.00048828125
2020-02-25 15:00:20 | INFO | fairseq.trainer | NOTE: overflow detected, setting loss scale to: 0.000244140625
2020-02-25 15:00:21 | INFO | fairseq.trainer | NOTE: overflow detected, setting loss scale to: 0.0001220703125
Traceback (most recent call last):
  File "/4tssd/wliax/anaconda3/bin/fairseq-train", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-train')()
  File "/4tssd/wliax/research_2020/fairseq/fairseq_cli/train.py", line 303, in cli_main
    nprocs=args.distributed_world_size,
  File "/4tssd/wliax/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/4tssd/wliax/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/4tssd/wliax/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/4tssd/wliax/research_2020/fairseq/fairseq_cli/train.py", line 270, in distributed_main
    main(args, init_distributed=True)
  File "/4tssd/wliax/research_2020/fairseq/fairseq_cli/train.py", line 102, in main
    train(args, trainer, task, epoch_itr)
  File "/4tssd/wliax/anaconda3/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/4tssd/wliax/research_2020/fairseq/fairseq_cli/train.py", line 171, in train
    log_output = trainer.train_step(samples)
  File "/4tssd/wliax/anaconda3/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/4tssd/wliax/research_2020/fairseq/fairseq/trainer.py", line 368, in train_step
    grad_norm = self.optimizer.clip_grad_norm(self.args.clip_norm)
  File "/4tssd/wliax/research_2020/fairseq/fairseq/optim/fp16_optimizer.py", line 175, in clip_grad_norm
    ).format(self.min_loss_scale))
FloatingPointError: Minimum loss scale reached (0.0001). Your loss is probably exploding. Try lowering the learning rate, using gradient clipping or increasing the batch size.
`

**Comment by myleott** [comment]
Hmm, a couple possibilities come to mind:
1) the FP32 weights don't work well in FP16, so you get immediate overflows
2) the FP32 weights work for the first step in FP16, but then the step breaks the model, causing a bunch overflows from steps 2 onward.

Can you try relaunching with `--lr 0.0 --log-interval 1` and see if you get any additional info?

**Comment by ever4244** [comment]
After a few trials, I think we can automatically convert between fp16 and fp32 without obvious problems. The only issue is I have to set --reset-optimizer
