### ISSUE TITLE
fairseq-preprocessing for transformer networks - correct procedure?

### ISSUE THREAD

**Issue by stet-stet** [pytorch/fairseq#1763]
### Before asking:   
1. search the issues.   
2. search the docs.    
*Yes, I am sure I searched quite thoroughly, but information was insufficient.*

#### What is your question?

What are the correct steps to preprocess a corpora with fairseq-preprocessing, so that I can train a translator with `--arch transformer_lm_gpt2_small`?

But even after looking at the documentation(which felt a bit opaque), and issues such as #1540 or #1269, it is hard to see what I could have done wrong.  **What have I done wrong?** (see below)

#### Code

(See below.)

#### What have you tried?

I crafted a ko<->jp parallel corpora, split them into train.val,test set, and saved each into respective files. 
I then trained a sentencepiece model with `spm_train`, encoded by test, val, train sets, and attempted to preprocess & train a new model. It failed. (EDIT) Please look at the comment I made below for relevant information.

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): 0.9.0 
 - PyTorch Version (e.g., 1.0): 1.4.0 [cpuonly]
 - OS (e.g., Linux): WSL 1, Ubuntu 18.04.2 LTS
 - How you installed fairseq (`pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7.6
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information: Will provide on demand

**Comment by stet-stet** [comment]
I now know that I was supposed to pre-segment the sentences with fastBPE or sentencepiece, so I did this:

`spm_encode --model=pultjapanese.model --output_format=piece < train.jp > train.spm.jp`
(repeat for each file)

(the model was made by spm_train, as per #1540.)
then this:

`fairseq-preprocess --source-lang jp --target-lang ko --trainpref $TEXT/train.spm --validpref $TEXT/val.spm --testpref $TEXT/test.spm --destdir data-bin/ --workers 20 --bpe sentencepiece --cpu`

then this:

`fairseq-train     data-bin/     --arch transformer_lm_gpt2_small --share-decoder-input-output-embed     --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0     --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000     --dropout 0.3 --weight-decay 0.0001     --criterion label_smoothed_cross_entropy --label-smoothing 0.1     --max-tokens 4096 --cpu`

which also ended in:

> | model transformer_lm_gpt2_small, criterion LabelSmoothedCrossEntropyCriterion
> | num. model params: 312952832 (num. trained: 312952832)
> | training on 1 GPUs
> | max tokens per GPU = 4096 and max sentences per GPU = None
> | no existing checkpoint found checkpoints/checkpoint_last.pt
> | loading train data for epoch 0
> | loaded 727993 examples from: data-bin/train.jp-ko.jp
> | loaded 727993 examples from: data-bin/train.jp-ko.ko
> | data-bin/ train jp-ko 727993 examples
> Traceback (most recent call last):
>   File "/home/stetstet/anaconda3/envs/nlp/bin/fairseq-train", line 8, in <module>
>     sys.exit(cli_main())
>   File "/home/stetstet/anaconda3/envs/nlp/lib/python3.7/site-packages/fairseq_cli/train.py", line 333, in cli_main
>     main(args)
>   File "/home/stetstet/anaconda3/envs/nlp/lib/python3.7/site-packages/fairseq_cli/train.py", line 70, in main
>     extra_state, epoch_itr = checkpoint_utils.load_checkpoint(args, trainer)
>   File "/home/stetstet/anaconda3/envs/nlp/lib/python3.7/site-packages/fairseq/checkpoint_utils.py", line 140, in load_checkpoint
>     epoch=0, load_dataset=True, **passthrough_args
>   File "/home/stetstet/anaconda3/envs/nlp/lib/python3.7/site-packages/fairseq/trainer.py", line 275, in get_train_iterator
>     self.task.max_positions(), self.model.max_positions()
>   File "/home/stetstet/anaconda3/envs/nlp/lib/python3.7/site-packages/fairseq/utils.py", line 266, in resolve_max_positions
>     max_positions = min(max_positions, arg)
> TypeError: '<' not supported between instances of 'int' and 'tuple'

**Comment by stet-stet** [comment]
Looks like I was a bit hazy when I wrote this, sorry.
