### ISSUE TITLE
building from source failed

### ISSUE THREAD

**Issue by opsuisppn** [pytorch/fairseq#1804]
## 🐛 Bug

Error in building the latest commit from source.
### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. pip install -e .
2. See errr:

Installing collected packages: fairseq
  Attempting uninstall: fairseq
    Found existing installation: fairseq 0.9.0
    Uninstalling fairseq-0.9.0:
      Successfully uninstalled fairseq-0.9.0
  Running setup.py develop for fairseq
    ERROR: Command errored out with exit status 1:
     command: /bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/fairseq/setup.py'"'"'; __file__='"'"'/fairseq/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /fairseq/
    Complete output (86 lines):
    running develop
    running egg_info
    writing fairseq.egg-info/PKG-INFO
    writing dependency_links to fairseq.egg-info/dependency_links.txt
    writing entry points to fairseq.egg-info/entry_points.txt
    writing requirements to fairseq.egg-info/requires.txt
    writing top-level names to fairseq.egg-info/top_level.txt
    reading manifest file 'fairseq.egg-info/SOURCES.txt'
    writing manifest file 'fairseq.egg-info/SOURCES.txt'
    running build_ext
    building 'fairseq.data.data_utils_fast' extension
    Traceback (most recent call last):
      File "/tmp/pip-build-env-llxo99ce/normal/lib64/python3.6/site-packages/numpy/core/__init__.py", line 24, in <module>
        from . import multiarray
      File "/tmp/pip-build-env-llxo99ce/normal/lib64/python3.6/site-packages/numpy/core/multiarray.py", line 14, in <module>
        from . import overrides
      File "/tmp/pip-build-env-llxo99ce/normal/lib64/python3.6/site-packages/numpy/core/overrides.py", line 7, in <module>
        from numpy.core._multiarray_umath import (
    ImportError: /tmp/pip-build-env-llxo99ce/normal/lib64/python3.6/site-packages/numpy/core/_multiarray_umath.cpython-36m-x86_64-linux-gnu.so: failed to map segment from shared object: Operation not permitted

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/fairseq/setup.py", line 161, in <module>
        zip_safe=False,
      File "/tmp/pip-build-env-llxo99ce/overlay/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-env-llxo99ce/overlay/lib/python3.6/site-packages/setuptools/command/develop.py", line 38, in run
        self.install_for_development()
      File "/tmp/pip-build-env-llxo99ce/overlay/lib/python3.6/site-packages/setuptools/command/develop.py", line 140, in install_for_development
        self.run_command('build_ext')
      File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-env-llxo99ce/overlay/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 87, in run
        _build_ext.run(self)
      File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
        self.build_extension(ext)
      File "/tmp/pip-build-env-llxo99ce/overlay/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 208, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 530, in build_extension
        include_dirs=ext.include_dirs,
      File "/fairseq/setup.py", line 35, in include_dirs
        import numpy
      File "/tmp/pip-build-env-llxo99ce/normal/lib64/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
        from . import core
      File "/tmp/pip-build-env-llxo99ce/normal/lib64/python3.6/site-packages/numpy/core/__init__.py", line 54, in <module>
        raise ImportError(msg)
    ImportError:

    IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

    Importing the numpy c-extensions failed.
    - Try uninstalling and reinstalling numpy.
    - If you have already done that, then:
      1. Check that you expected to use Python3.6 from "/bin/python3.6",
         and that you have no directories in your PATH or PYTHONPATH that can
         interfere with the Python and numpy version "1.18.1" you're trying to use.
      2. If (1) looks fine, you can open a new issue at
         https://github.com/numpy/numpy/issues.  Please include details on:
         - how you installed Python
         - how you installed numpy
         - your operating system
         - whether or not you have multiple versions of Python installed
         - if you built from source, your compiler versions and ideally a build log

    - If you're working with a numpy git repository, try `git clean -xdf`
      (removes all files not under version control) and rebuild numpy.

    Note: this error has many possible causes, so please don't comment on
    an existing issue about this - open a new one instead.

    Original error was: /tmp/pip-build-env-llxo99ce/normal/lib64/python3.6/site-packages/numpy/core/_multiarray_umath.cpython-36m-x86_64-linux-gnu.so: failed to map segment from shared object: Operation not permitted

    ----------------------------------------
  Rolling back uninstall of fairseq
  Moving to /bin/fairseq-eval-lm
   from /tmp/pip-uninstall-ec0ydd1c/fairseq-eval-lm
  Moving to /bin/fairseq-generate
   from /tmp/pip-uninstall-ec0ydd1c/fairseq-generate
  Moving to /bin/fairseq-interactive
   from /tmp/pip-uninstall-ec0ydd1c/fairseq-interactive
  Moving to /bin/fairseq-preprocess
   from /tmp/pip-uninstall-ec0ydd1c/fairseq-preprocess
  Moving to /bin/fairseq-score
   from /tmp/pip-uninstall-ec0ydd1c/fairseq-score
  Moving to /bin/fairseq-train
   from /tmp/pip-uninstall-ec0ydd1c/fairseq-train
  Moving to /bin/fairseq-validate
   from /tmp/pip-uninstall-ec0ydd1c/fairseq-validate
  Moving to /lib/python3.6/site-packages/examples/
   from /lib/python3.6/site-packages/~xamples
  Moving to /lib/python3.6/site-packages/fairseq-0.9.0.dist-info/
   from /lib/python3.6/site-packages/~airseq-0.9.0.dist-info
  Moving to /lib/python3.6/site-packages/fairseq/
   from /lib/python3.6/site-packages/~airseq
  Moving to /lib/python3.6/site-packages/fairseq_cli/
   from /lib/python3.6/site-packages/~airseq_cli
ERROR: Command errored out with exit status 1: /bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/fairseq/setup.py'"'"'; __file__='"'"'/fairseq/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by myleott** [comment]
This seems like an issue with your numpy installation, not fairseq, since it happens when `import numpy` is called. Please reinstall numpy/pytorch/etc.

**Comment by opsuisppn** [comment]
Hi @myleott, I have reinstalled numpy and it didn't solve the issue. I have successfully built from source of previous versions. I will check my local setting again to see if there is other possible cause. Thanks.
