### ISSUE TITLE
AttributeError: module 'torch._C' has no attribute 'ScriptFunction'

### ISSUE THREAD

**Issue by markusdr** [pytorch/fairseq#1812]
## 🐛 Bug

I'm getting the following error when I try to run `examples.roberta.multiprocessing_bpe_encoder`:

    AttributeError: module 'torch._C' has no attribute 'ScriptFunction'

The command is part of the instructions here: https://github.com/pytorch/fairseq/blob/master/examples/bart/README.summarization.md

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

0. Install python 3.6 and torch 1.4 and the latest fairseq
1. Run: `python -m examples.roberta.multiprocessing_bpe_encoder`
2. See the error below.

Error:

     $ python -m examples.roberta.multiprocessing_bpe_encoder
    Traceback (most recent call last):
      File "/user/conda/envs/p36/lib/python3.6/runpy.py", line 183, in _run_module_as_main
        mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
      File "/user/conda/envs/p36/lib/python3.6/runpy.py", line 109, in _get_module_details
        __import__(pkg_name)
      File "/home/ec2-user/fairseq/examples/__init__.py", line 8, in <module>
        import examples.noisychannel  # noqa
      File "/home/ec2-user/fairseq/examples/noisychannel/__init__.py", line 6, in <module>
        from .rerank_options import *  # noqa
      File "/home/ec2-user/fairseq/examples/noisychannel/rerank_options.py", line 6, in <module>
        from fairseq import options
      File "/home/ec2-user/fairseq/fairseq/__init__.py", line 12, in <module>
        from fairseq.logging import meters, metrics, progress_bar  # noqa
      File "/home/ec2-user/fairseq/fairseq/logging/progress_bar.py", line 20, in <module>
        import torch
      File "/user/conda/envs/p36/lib/python3.6/site-packages/torch/__init__.py", line 280, in <module>
        from .functional import *
      File "/user/conda/envs/p36/lib/python3.6/site-packages/torch/functional.py", line 2, in <module>
        import torch.nn.functional as F
      File "/user/conda/envs/p36/lib/python3.6/site-packages/torch/nn/__init__.py", line 1, in <module>
        from .modules import *
      File "/user/conda/envs/p36/lib/python3.6/site-packages/torch/nn/modules/__init__.py", line 23, in <module>
        from .rnn import RNNBase, RNN, LSTM, GRU, \
      File "/user/conda/envs/p36/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 399, in <module>
        class LSTM(RNNBase):
      File "/user/conda/envs/p36/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 523, in LSTM
        def forward(self, input, hx=None):  # noqa: F811
      File "/user/conda/envs/p36/lib/python3.6/site-packages/torch/_jit_internal.py", line 489, in _overload_method
        qual_name = _qualified_name(func)
      File "/user/conda/envs/p36/lib/python3.6/site-packages/torch/_jit_internal.py", line 679, in _qualified_name
        if isinstance(obj, torch._C.ScriptFunction):
    AttributeError: module 'torch._C' has no attribute 'ScriptFunction'

When I downgrade to torch==1.3 it gives a different error ("GELU" not found)

### Environment

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0) 1.4
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): `pip install --editable .` from source
 - Build command you used (if compiling from source):
 - Python version: Tested in 3.6 and 3.7
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

### Additional context

The command I'm trying to run is part of the instructions here: https://github.com/pytorch/fairseq/blob/master/examples/bart/README.summarization.md

**Comment by myleott** [comment]
fairseq requires torch 1.4, but I'm not able reproduce this. Can you try reinstall torch?

Then try:
```bash
python -m examples.roberta.multiprocessing_bpe_encoder --help
```

**Comment by markusdr** [comment]
Thanks for looking into this.

Here are the complete steps to reproduce from scratch:

    $ conda create --name xyz python=3.6
    $ source activate  xyz
    $ pip install torch
    Collecting torch
      Using cached torch-1.4.0-cp36-cp36m-manylinux1_x86_64.whl (753.4 MB)
    Successfully installed torch-1.4.0
    $ git clone https://github.com/pytorch/fairseq.git fsq
    $ cd fsq/
    $ pip install --editable .
    Successfully installed cffi-1.14.0 cython-0.29.15 fairseq numpy-1.18.1 portalocker-1.5.2 pycparser-2.20 regex-2020.2.20 sacrebleu-1.4.3 tqdm-4.43.0 typing-3.7.4.1
    $ python -m examples.roberta.multiprocessing_bpe_encoder --help
    Traceback (most recent call last):
      File "/home/ec2-user/anaconda3/envs/xyz/lib/python3.6/runpy.py", line 183, in _run_module_as_main
        mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
      File "/home/ec2-user/anaconda3/envs/xyz/lib/python3.6/runpy.py", line 109, in _get_module_details
        __import__(pkg_name)
      File "/home/ec2-user/fsq/examples/__init__.py", line 8, in <module>
        import examples.noisychannel  # noqa
      File "/home/ec2-user/fsq/examples/noisychannel/__init__.py", line 6, in <module>
        from .rerank_options import *  # noqa
      File "/home/ec2-user/fsq/examples/noisychannel/rerank_options.py", line 6, in <module>
        from fairseq import options
      File "/home/ec2-user/fsq/fairseq/__init__.py", line 12, in <module>
        from fairseq.logging import meters, metrics, progress_bar  # noqa
      File "/home/ec2-user/fsq/fairseq/logging/progress_bar.py", line 20, in <module>
        import torch
      File "/home/ec2-user/anaconda3/envs/xyz/lib/python3.6/site-packages/torch/__init__.py", line 280, in <module>
        from .functional import *
      File "/home/ec2-user/anaconda3/envs/xyz/lib/python3.6/site-packages/torch/functional.py", line 2, in <module>
        import torch.nn.functional as F
      File "/home/ec2-user/anaconda3/envs/xyz/lib/python3.6/site-packages/torch/nn/__init__.py", line 1, in <module>
        from .modules import *
      File "/home/ec2-user/anaconda3/envs/xyz/lib/python3.6/site-packages/torch/nn/modules/__init__.py", line 23, in <module>
        from .rnn import RNNBase, RNN, LSTM, GRU, \
      File "/home/ec2-user/anaconda3/envs/xyz/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 399, in <module>
        class LSTM(RNNBase):
      File "/home/ec2-user/anaconda3/envs/xyz/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 523, in LSTM
        def forward(self, input, hx=None):  # noqa: F811
      File "/home/ec2-user/anaconda3/envs/xyz/lib/python3.6/site-packages/torch/_jit_internal.py", line 489, in _overload_method
        qual_name = _qualified_name(func)
      File "/home/ec2-user/anaconda3/envs/xyz/lib/python3.6/site-packages/torch/_jit_internal.py", line 679, in _qualified_name
        if isinstance(obj, torch._C.ScriptFunction):
    AttributeError: module 'torch._C' has no attribute 'ScriptFunction'

**Comment by markusdr** [comment]
Turns out that `pip install torch` results in a bad or incomplete pytorch installation. 

Installing pytorch using `conda` instead solves the issue:

    conda install pytorch torchvision -c pytorch
