### ISSUE TITLE
CUDA error when training with multiple GPUs and criterion's logging_outputs_can_be_summed() is False

### ISSUE THREAD

**Issue by freewym** [pytorch/fairseq#1826]
## 🐛 Bug

Currently almost all subclass of `FairseqCriterion` 's `logging_outputs_can_be_summed()` returns True, and it trains OK with multiple GPUs. But if I change, for example, `CrossEntropyCriterion`'s  `logging_outputs_can_be_summed ()` to return False and train with 2 GPUs , it gives error:

File "/export/b02/ywang/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/export/b02/ywang/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/ywang/fairseq6/train.py", line 286, in distributed_main
    main(args, init_distributed=True)
  File "/home/ywang/fairseq6/train.py", line 96, in main
    train(args, trainer, task, epoch_itr)
  File "/export/b02/ywang/anaconda3/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/ywang/fairseq6/train.py", line 176, in train
    log_output = trainer.train_step(samples)
  File "/export/b02/ywang/anaconda3/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/ywang/fairseq6/fairseq/trainer.py", line 347, in train_step
    logging_outputs, sample_size, ooms, ignore=is_dummy_batch,
  File "/home/ywang/fairseq6/fairseq/trainer.py", line 616, in _aggregate_logging_outputs
    logging_outputs, *extra_stats_to_sum, ignore=ignore
  File "/home/ywang/fairseq6/fairseq/trainer.py", line 634, in _all_gather_list_sync
    max_size=getattr(self.args, 'all_gather_list_size', 16384),
  File "/home/ywang/fairseq6/fairseq/distributed_utils.py", line 176, in all_gather_list
    result.append(pickle.loads(bytes(out_buffer[header_size:header_size + enc_size].tolist())))
  File "/export/b02/ywang/anaconda3/lib/python3.7/site-packages/torch/storage.py", line 134, in _load_from_bytes
    return torch.load(io.BytesIO(b))
  File "/export/b02/ywang/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/export/b02/ywang/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 702, in _legacy_load
    result = unpickler.load()
  File "/export/b02/ywang/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 665, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/export/b02/ywang/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 156, in default_restore_location
    result = fn(storage, location)
  File "/export/b02/ywang/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 136, in _cuda_deserialize
    return storage_type(obj.size())
  File "/export/b02/ywang/anaconda3/lib/python3.7/site-packages/torch/cuda/__init__.py", line 480, in _lazy_new
    return super(_CudaBase, cls).__new__(cls, *args, **kwargs)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable

The reason why I want it to return False is, I have some stats in logging_output which is a tensor not scalar, to be aggregated in `reduce_matrices()`.

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Just have `CrossEntropyCriterion.logging_outputs_can_be_summed()` to return False and train with multi-GPUs
2. See error

### Environment

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0): 1.4
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration:  GeForce GTX 1080
 - Any other relevant information:

**Comment by myleott** [comment]
Merging the above fix, please reopen if this is still an issue after this is merged!

**Comment by freewym** [comment]
@myleott Thanks for fixing it! However, I still have another problem related this with this fix.  Have you ever try to put a tensor in logging_output that `FairseqCriterion::forward()` returns. I encountered an error right after doing a validation step with multiple GPUs:

Traceback (most recent call last):
  File "/home/ywang/fairseq6/fairseq_cli/train.py", line 348, in <module>
    cli_main()
  File "home/ywang/fairseq6/fairseq_cli/train.py", line 340, in cli_main
    nprocs=args.distributed_world_size,
  File "/export/b02/ywang/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/export/b02/ywang/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/ywang/fairseq6/fairseq/distributed_utils.py", line 177, in all_gather_list
    result.append(pickle.loads(bytes(out_buffer[header_size:header_size + enc_size].tolist())))
_pickle.UnpicklingError: invalid load key, '\xc3'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/export/b02/ywang/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/ywang/fairseq6/fairseq_cli/train.py", line 297, in distributed_main
    main(args, init_distributed=True)
  File "home/ywang/fairseq6/fairseq_cli/train.py", line 97, in main
    train(args, trainer, task, epoch_itr)
  File "/export/b02/ywang/anaconda3/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "home/ywang/fairseq6/fairseq_cli/train.py", line 203, in train
    valid_losses = validate(args, trainer, task, epoch_itr, valid_subsets)
  File "home/ywang/fairseq6/fairseq_cli/train.py", line 267, in validate
    trainer.valid_step(chunk_sample)
  File "/export/b02/ywang/anaconda3/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/ywang/fairseq6/fairseq/trainer.py", line 463, in valid_step
    logging_outputs, sample_size, ignore=is_dummy_batch,
  File "/home/ywang/fairseq6/fairseq/trainer.py", line 613, in _aggregate_logging_outputs
    logging_outputs, *extra_stats_to_sum, ignore=ignore
  File "/home/ywang/fairseq6/fairseq/trainer.py", line 631, in _all_gather_list_sync
    max_size=getattr(self.args, 'all_gather_list_size', 16384),
  File "/home/ywang/fairseq6/fairseq/distributed_utils.py", line 181, in all_gather_list
    'Unable to unpickle data from other workers. all_gather_list requires all '
Exception: Unable to unpickle data from other workers. all_gather_list requires all workers to enter the function together, so this error usually indicates that the workers have fallen out of sync somehow. Workers can fall out of sync if one of them runs out of memory, or if there are other conditions in your training script that can cause one worker to finish an epoch while other workers are still iterating over their portions of the data. Try rerunning with --ddp-backend=no_c10d and see if that helps.


It only happened right after the validation, not in any train_step(), and I already tried `--ddp-backend=no_c10d`.
