### ISSUE TITLE
wmt19 model cannot run on gpu except #0.

### ISSUE THREAD

**Issue by loopdigga96** [pytorch/fairseq#1860]
## 🐛 Bug

I am running [tutorial](https://github.com/pytorch/fairseq/tree/master/examples/wmt19). I successfully loaded model from hub and tried to run it on second gpu (id=1). Which raised an exception that data and model are stored on different GPUs. With gpu(id=0) works fine.
```
Using cache found in /home/vlad/.cache/torch/hub/pytorch_fairseq_master
Loading codes from /home/vlad/.cache/torch/pytorch_fairseq/0695ef328ddefcb8cbcfabc3196182f59c0e41e0468b10cc0db2ae9c91881fcc.bb1be17de4233e13870bd7d6065bfdb03fca0a51dd0f5d0b7edf5c188eda71f1/bpecodes ...
Read 30000 codes from the codes file.
Traceback (most recent call last):
  File "/home/vlad/Documents/coding/experiments/paper-analyzer-Tretyak_Internship/papers/experiments/scientific_generation/scripts/paraphrase.py", line 46, in <module>
    en2de.translate(['hello'])
  File "/home/vlad/.cache/torch/hub/pytorch_fairseq_master/fairseq/hub_utils.py", line 126, in translate
    return self.sample(sentences, beam, verbose, **kwargs)
  File "/home/vlad/.cache/torch/hub/pytorch_fairseq_master/fairseq/hub_utils.py", line 132, in sample
    batched_hypos = self.generate(tokenized_sentences, beam, verbose, **kwargs)
  File "/home/vlad/.cache/torch/hub/pytorch_fairseq_master/fairseq/hub_utils.py", line 165, in generate
    translations = self.task.inference_step(generator, self.models, batch)
  File "/home/vlad/.cache/torch/hub/pytorch_fairseq_master/fairseq/tasks/fairseq_task.py", line 351, in inference_step
    return generator.generate(models, sample, prefix_tokens=prefix_tokens)
  File "/home/vlad/Documents/envs/p3.6/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/vlad/.cache/torch/hub/pytorch_fairseq_master/fairseq/sequence_generator.py", line 93, in generate
    return self._generate(model, sample, **kwargs)
  File "/home/vlad/Documents/envs/p3.6/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/vlad/.cache/torch/hub/pytorch_fairseq_master/fairseq/sequence_generator.py", line 276, in _generate
    tokens[:, :step + 1], encoder_outs, temperature=self.temperature,
  File "/home/vlad/Documents/envs/p3.6/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/vlad/.cache/torch/hub/pytorch_fairseq_master/fairseq/sequence_generator.py", line 549, in forward_decoder
    temperature=temperature,
  File "/home/vlad/.cache/torch/hub/pytorch_fairseq_master/fairseq/sequence_generator.py", line 568, in _decode_one
    tokens, encoder_out=encoder_out, incremental_state=self.incremental_states[model],
  File "/home/vlad/.cache/torch/hub/pytorch_fairseq_master/fairseq/models/fairseq_model.py", line 274, in forward_decoder
    return self.decoder(prev_output_tokens, **kwargs)
  File "/home/vlad/Documents/envs/p3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/vlad/.cache/torch/hub/pytorch_fairseq_master/fairseq/models/transformer.py", line 704, in forward
    alignment_heads=alignment_heads,
  File "/home/vlad/.cache/torch/hub/pytorch_fairseq_master/fairseq/models/transformer.py", line 807, in extract_features
    need_head_weights=bool((idx == alignment_layer)),
  File "/home/vlad/Documents/envs/p3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/vlad/.cache/torch/hub/pytorch_fairseq_master/fairseq/modules/transformer_layer.py", line 297, in forward
    need_head_weights=need_head_weights,
  File "/home/vlad/Documents/envs/p3.6/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/vlad/.cache/torch/hub/pytorch_fairseq_master/fairseq/modules/multihead_attention.py", line 325, in forward
    key_padding_mask.unsqueeze(1).unsqueeze(2).to(torch.bool), float("-inf")
RuntimeError: arguments are located on different GPUs at /pytorch/aten/src/THC/generic/THCTensorMasked.cu:28

Process finished with exit code 1

```

#### Code sample
```
import torch

en2de = torch.hub.load('pytorch/fairseq', 'transformer.wmt19.en-de',
                       checkpoint_file='model1.pt:model2.pt:model3.pt:model4.pt',
                       tokenizer='moses', bpe='fastbpe').to(torch.device('cuda:1'))

result = en2de.translate(['hello'])
```

### Expected behavior

Run without errors

### Environment

 - fairseq Version==0.9.0
 - PyTorch Version ==1.4.0
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed fairseq (`pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: RTX 2080 x 2
 - Any other relevant information:

**Comment by zide05** [comment]
I still have this question when using gpu other than gpu: 0, have the problem been solved ?
