### ISSUE TITLE
Get Error when Execute BART Model Finetuning Code

### ISSUE THREAD

**Issue by areomoon** [pytorch/fairseq#1865]
## 🐛 Bug

Hi, thanks for open source the summarization model BART.  I am following on this [tutorial](https://github.com/pytorch/fairseq/blob/master/examples/bart/README.summarization.md) to finetune the BART model on CNN-DM dataset. However, I get the following error when execute the finetuning code. 
```
2020-03-19 02:21:14 | INFO | fairseq_cli.train | model bart_large, criterion LabelSmoothedCrossEntropyCriterion
2020-03-19 02:21:14 | INFO | fairseq_cli.train | num. model params: 406290432 (num. trained: 406290432)
2020-03-19 02:21:18 | INFO | fairseq_cli.train | training on 1 GPUs
2020-03-19 02:21:18 | INFO | fairseq_cli.train | max tokens per GPU = 2048 and max sentences per GPU = None
2020-03-19 02:21:18 | INFO | fairseq.trainer | no existing checkpoint found /home/cdsw/acoe_auditnlp_bart/finetune_weights/model.pt
2020-03-19 02:21:18 | INFO | fairseq.trainer | loading train data for epoch 0
2020-03-19 02:21:18 | INFO | fairseq.data.data_utils | loaded 80431 examples from: /home/cdsw/acoe_auditnlp_bart/data/newsroom/newsroom-bin/train.source-target.source
2020-03-19 02:21:18 | INFO | fairseq.data.data_utils | loaded 80431 examples from: /home/cdsw/acoe_auditnlp_bart/data/newsroom/newsroom-bin/train.source-target.target
2020-03-19 02:21:18 | INFO | fairseq.tasks.translation | /home/cdsw/acoe_auditnlp_bart/data/newsroom/newsroom-bin train source-target 80431 examples
2020-03-19 02:21:18 | WARNING | fairseq.data.data_utils | 20 samples have invalid sizes and will be skipped, max_positions=(1024, 1024), first few sample ids=[23528, 76618, 76582, 57396, 76508, 54278, 76718, 57490, 6449, 72644]
Traceback (most recent call last):
  File "/home/cdsw/.cache/torch/hub/pytorch_fairseq_master/fairseq/data/data_utils.py", line 221, in batch_by_size
    from fairseq.data.data_utils_fast import batch_by_size_fast
ModuleNotFoundError: No module named 'fairseq.data.data_utils_fast'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 11, in <module>
    cli_main()
  File "/home/cdsw/.cache/torch/hub/pytorch_fairseq_master/fairseq_cli/train.py", line 318, in cli_main
    main(args)
  File "/home/cdsw/.cache/torch/hub/pytorch_fairseq_master/fairseq_cli/train.py", line 81, in main
    extra_state, epoch_itr = checkpoint_utils.load_checkpoint(args, trainer)
  File "/home/cdsw/.cache/torch/hub/pytorch_fairseq_master/fairseq/checkpoint_utils.py", line 153, in load_checkpoint
    epoch=0, load_dataset=True, **passthrough_args
  File "/home/cdsw/.cache/torch/hub/pytorch_fairseq_master/fairseq/trainer.py", line 267, in get_train_iterator
    epoch=epoch,
  File "/home/cdsw/.cache/torch/hub/pytorch_fairseq_master/fairseq/tasks/fairseq_task.py", line 181, in get_batch_iterator
    required_batch_size_multiple=required_batch_size_multiple,
  File "/home/cdsw/.cache/torch/hub/pytorch_fairseq_master/fairseq/data/data_utils.py", line 224, in batch_by_size
    'Please build Cython components with: `pip install --editable .` '
ImportError: Please build Cython components with: `pip install --editable .` or `python setup.py build_ext --inplace`
```
After getting this code, I have tried ```pip3 install cython``` , But it doesn't work.

#### Code sample
```
CUDA_VISIBLE_DEVICES=0 python3 train.py \
    /home/cdsw/data/cnndm/cnndm-bin \
    --restore-file /home/cdsw/finetune_weights/model.pt \
    --max-tokens 2048 \
    --task translation \
    --source-lang source --target-lang target \
    --truncate-source \
    --layernorm-embedding \
    --share-all-embeddings \
    --share-decoder-input-output-embed \
    --reset-optimizer --reset-dataloader --reset-meters \
    --required-batch-size-multiple 1 \
    --arch bart_large \
    --criterion label_smoothed_cross_entropy \
    --label-smoothing 0.1 \
    --dropout 0.1 --attention-dropout 0.1 \
    --weight-decay 0.01 --optimizer adam --adam-betas "(0.9, 0.999)" --adam-eps 1e-08 \
    --clip-norm 0.1 \
    --lr-scheduler polynomial_decay --lr 3e-05 --total-num-update 10000 --warmup-updates 500 \
    --fp16 --update-freq 4 \
    --skip-invalid-size-inputs-valid-test \
    --find-unused-parameters
```

### Expected behavior

- Run without errors 

### Environment

 - fairseq Versio== 0.9.0 
 - PyTorch Version==1.4.0
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed fairseq (`pip`, source): pip3
 - Build command you used (if compiling from source): ``` pip3 install cython```
 - Python version: 3.6.9
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: Tesla V100
 - Any other relevant information:

**Comment by ngoyal2707** [comment]
As the error logs say:
```
ImportError: Please build Cython components with: `pip install --editable .` or `python setup.py build_ext --inplace`
```
