### ISSUE TITLE
Overflow when Reproducing Backtranslation Reverse Model

### ISSUE THREAD

**Issue by nicolasspring** [pytorch/fairseq#1895]
When reproducing the reverse model from the [Understanding Back-Translation at Scale](https://arxiv.org/abs/1808.09381) paper, training fails after `FloatingPointError: Minimum loss scale reached (0.0001)`:
```
2020-03-23 11:38:13 | INFO | train | epoch 002 | loss 9.803 | nll_loss 8.89 | ppl 474.37 | wps 31194.9 | ups 0.07 | wpb 430468 | bsz 14485.4 | num_updates 695 | lr 0.00017375 | gnorm 55.005 | loss_scale 0 | train_wall 4512 | wall 9786
2020-03-23 11:38:31 | INFO | valid | epoch 002 | valid on 'valid' subset | loss 9.393 | nll_loss 8.328 | ppl 321.26 | wps 84912.1 | wpb 11298 | bsz 382.5 | num_updates 695 | best_loss 9.393
2020-03-23 11:38:37 | INFO | fairseq.checkpoint_utils | saved checkpoint checkpoints_en_de_parallel/checkpoint2.pt (epoch 2 @ 695 updates, score 9.393) (writing took 5.761506536975503 seconds)
2020-03-23 11:39:44 | INFO | train_inner | epoch 003:      5 / 356 loss=9.44, nll_loss=8.44, ppl=347.28, wps=30690.8, ups=0.07, wpb=427295, bsz=14390.4, num_updates=700, lr=0.000175, gnorm=156.036, loss_scale=0, train_wall=1281, wall=9877
2020-03-23 11:41:18 | INFO | fairseq.trainer | NOTE: overflow detected, setting loss scale to: 0.00048828125
2020-03-23 11:48:04 | INFO | fairseq.trainer | NOTE: overflow detected, setting loss scale to: 0.000244140625
2020-03-23 11:49:25 | INFO | fairseq.trainer | NOTE: overflow detected, setting loss scale to: 0.0001220703125
Traceback (most recent call last):
  File "/home/cluster/nispri/scratch/fairseq_pip/venvs/env-bt-probing-tasks/bin/fairseq-train", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-train')()
  File "/net/cephfs/scratch/nispri/fairseq_pip/software/fairseq/fairseq_cli/train.py", line 321, in cli_main
    main(args)
  File "/net/cephfs/scratch/nispri/fairseq_pip/software/fairseq/fairseq_cli/train.py", line 96, in main
    train(args, trainer, task, epoch_itr)
  File "/home/cluster/nispri/scratch/fairseq_pip/venvs/env-bt-probing-tasks/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/net/cephfs/scratch/nispri/fairseq_pip/software/fairseq/fairseq_cli/train.py", line 176, in train
    log_output = trainer.train_step(samples)
  File "/home/cluster/nispri/scratch/fairseq_pip/venvs/env-bt-probing-tasks/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/net/cephfs/scratch/nispri/fairseq_pip/software/fairseq/fairseq/trainer.py", line 369, in train_step
    grad_norm = self.optimizer.clip_grad_norm(self.args.clip_norm)
  File "/net/cephfs/scratch/nispri/fairseq_pip/software/fairseq/fairseq/optim/fp16_optimizer.py", line 174, in clip_grad_norm
    ).format(self.min_loss_scale))
FloatingPointError: Minimum loss scale reached (0.0001). Your loss is probably exploding. Try lowering the learning rate, using gradient clipping or increasing the batch size.
```
The training command was taken from [https://github.com/pytorch/fairseq/tree/master/examples/backtranslation#step-2-back-translate-monolingual-german-data](https://github.com/pytorch/fairseq/tree/master/examples/backtranslation#step-2-back-translate-monolingual-german-data) and adapted for 1 GPU:
```
fairseq-train --fp16 \
   data-bin/wmt18_en_de \
    --source-lang de --target-lang en \
    --arch transformer_wmt_en_de_big --share-all-embeddings \
    --dropout 0.3 --weight-decay 0.0 \
    --criterion label_smoothed_cross_entropy --label-smoothing 0.1 \
    --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 \
    --lr 0.001 --lr-scheduler inverse_sqrt --warmup-updates 4000 \
    --max-tokens 14336 --update-freq 32 \
    --max-update 30000 \
    --save-dir $CHECKPOINT_DIR
```

How is it possible for the loss to be that high when using the same training command? Would omitting `--fp16` be the right solution?

Environment:
 - fairseq: 0.9.0
 - PyTorch: 1.4.0
 - Python version: 3.6.10
 - CUDA: 10.0
 - GPU: 1 x Tesla-V100 32GB

**Comment by myleott** [comment]
To adapt for 1 GPU you'd need to multiply update-freq by 8. So `--update-freq 128` 😄

**Comment by bricksdont** [comment]
Hi Myle,

But did you see that `--max-tokens 14336` instead of `3584`? Isn't `--update-freq 32` the right multiplier with this batch size?

**Comment by bricksdont** [comment]
And if you could perhaps clarify: What exactly does "loss overflow" mean and what is causing this overflow? Is it a consequence of using `--fp16`?

**Comment by myleott** [comment]
>   did you see that --max-tokens 14336 instead of 3584? Isn't --update-freq 32 the right  multiplier with this batch size?

Ah good point.

> What exactly does "loss overflow" mean and what is causing this overflow? Is it a consequence of using --fp16?

There's a few things happening here.

The overflows refer to gradients that are too big and overflow the range supported by fp16. We use a [dynamic loss scaler](https://docs.nvidia.com/deeplearning/performance/mixed-precision-training/index.html#faq-general) that scales the gradients to keep them in a reasonable range (and avoid overflow). The "loss overflow" warnings indicate that the dynamic loss scaler is working.

Sometimes, we get a bunch of overflows in a row. This usually means that the loss is exploding, perhaps due to too high of a learning rate or too small of a batch size. The dynamic loss scaler tries to scale down the loss to compensate, and ultimately we raise an exception once the scale hits some minimum threshold (0.0001 by default).

In your case, you're training with a pretty large `--max-tokens` and high update frequency as well. Thus, we're more likely to hit overflows and cause the loss scaler to get small. I think this may be fine, in which case you can just adjust the minimum threshold with: `--min-loss-scale=0.000001`.

I also noticed that your loss and num_updates is less than mine. Here's the first 10 epochs of my training log, please make sure you get comparable results:
```
2020-02-07 13:21:07 | INFO | train | {"epoch": 1, "train_loss": "11.049", "train_nll_loss": "10.399", "train_ppl": "1350.12", "train_wps": "2.39679e+06", "train_ups": "5.95", "train_wpb": "402992", "train_bsz": "14123.2", "train_num_updates": "362", "train_lr": "9.05909e-05", "train_gnorm": "1.682", "train_clip": "0", "train_oom": "0", "train_loss_scale": "20", "train_train_wall": "69", "train_wall": "119"}
2020-02-07 13:21:20 | INFO | valid | {"epoch": 1, "valid_loss": "9.123", "valid_nll_loss": "8.106", "valid_ppl": "275.6", "valid_wps": "3.32992e+06", "valid_wpb": "373365", "valid_bsz": "13099", "valid_num_updates": "362"}
2020-02-07 13:22:53 | INFO | train | {"epoch": 2, "train_loss": "8.472", "train_nll_loss": "7.4", "train_ppl": "168.89", "train_wps": "1.38339e+06", "train_ups": "3.43", "train_wpb": "403000", "train_bsz": "14132.4", "train_num_updates": "728", "train_lr": "0.000182082", "train_gnorm": "1.332", "train_clip": "0", "train_oom": "0", "train_loss_scale": "27", "train_train_wall": "60", "train_wall": "226"}
2020-02-07 13:23:03 | INFO | valid | {"epoch": 2, "valid_loss": "7.393", "valid_nll_loss": "6.055", "valid_ppl": "66.492", "valid_wps": "3.2445e+06", "valid_wpb": "373365", "valid_bsz": "13099", "valid_num_updates": "728", "valid_best_loss": "7.393"}
2020-02-07 13:24:31 | INFO | train | {"epoch": 3, "train_loss": "6.928", "train_nll_loss": "5.619", "train_ppl": "49.153", "train_wps": "1.50297e+06", "train_ups": "3.73", "train_wpb": "402992", "train_bsz": "14125", "train_num_updates": "1093", "train_lr": "0.000273323", "train_gnorm": "1.066", "train_clip": "0", "train_oom": "0", "train_loss_scale": "27", "train_train_wall": "59", "train_wall": "324"}
2020-02-07 13:24:36 | INFO | valid | {"epoch": 3, "valid_loss": "5.941", "valid_nll_loss": "4.292", "valid_ppl": "19.585", "valid_wps": "3.39883e+06", "valid_wpb": "373365", "valid_bsz": "13099", "valid_num_updates": "1093", "valid_best_loss": "5.941"}
2020-02-07 13:26:00 | INFO | train | {"epoch": 4, "train_loss": "5.674", "train_nll_loss": "4.181", "train_ppl": "18.14", "train_wps": "1.65616e+06", "train_ups": "4.11", "train_wpb": "402990", "train_bsz": "14126.5", "train_num_updates": "1458", "train_lr": "0.000364564", "train_gnorm": "0.715", "train_clip": "0", "train_oom": "0", "train_loss_scale": "42", "train_train_wall": "58", "train_wall": "413"}
2020-02-07 13:26:05 | INFO | valid | {"epoch": 4, "valid_loss": "5.127", "valid_nll_loss": "3.356", "valid_ppl": "10.237", "valid_wps": "3.7311e+06", "valid_wpb": "373365", "valid_bsz": "13099", "valid_num_updates": "1458", "valid_best_loss": "5.127"}
2020-02-07 13:27:33 | INFO | train | {"epoch": 5, "train_loss": "4.991", "train_nll_loss": "3.419", "train_ppl": "10.695", "train_wps": "1.58612e+06", "train_ups": "3.94", "train_wpb": "402971", "train_bsz": "14122.9", "train_num_updates": "1823", "train_lr": "0.000455804", "train_gnorm": "0.46", "train_clip": "0", "train_oom": "0", "train_loss_scale": "63", "train_train_wall": "58", "train_wall": "506"}
2020-02-07 13:27:44 | INFO | valid | {"epoch": 5, "valid_loss": "4.676", "valid_nll_loss": "2.889", "valid_ppl": "7.407", "valid_wps": "3.47825e+06", "valid_wpb": "373365", "valid_bsz": "13099", "valid_num_updates": "1823", "valid_best_loss": "4.676"}
2020-02-07 13:29:12 | INFO | train | {"epoch": 6, "train_loss": "4.644", "train_nll_loss": "3.041", "train_ppl": "8.228", "train_wps": "1.48031e+06", "train_ups": "3.67", "train_wpb": "403001", "train_bsz": "14137", "train_num_updates": "2187", "train_lr": "0.000546795", "train_gnorm": "0.369", "train_clip": "0", "train_oom": "0", "train_loss_scale": "65", "train_train_wall": "58", "train_wall": "605"}
2020-02-07 13:29:16 | INFO | valid | {"epoch": 6, "valid_loss": "4.49", "valid_nll_loss": "2.713", "valid_ppl": "6.555", "valid_wps": "3.61145e+06", "valid_wpb": "373365", "valid_bsz": "13099", "valid_num_updates": "2187", "valid_best_loss": "4.49"}
2020-02-07 13:30:42 | INFO | train | {"epoch": 7, "train_loss": "4.433", "train_nll_loss": "2.812", "train_ppl": "7.023", "train_wps": "1.62295e+06", "train_ups": "4.03", "train_wpb": "402987", "train_bsz": "14136.1", "train_num_updates": "2551", "train_lr": "0.000637786", "train_gnorm": "0.327", "train_clip": "0", "train_oom": "0", "train_loss_scale": "65", "train_train_wall": "58", "train_wall": "695"}
2020-02-07 13:30:52 | INFO | valid | {"epoch": 7, "valid_loss": "4.324", "valid_nll_loss": "2.543", "valid_ppl": "5.827", "valid_wps": "4.92262e+06", "valid_wpb": "373365", "valid_bsz": "13099", "valid_num_updates": "2551", "valid_best_loss": "4.324"}
2020-02-07 13:32:19 | INFO | train | {"epoch": 8, "train_loss": "4.293", "train_nll_loss": "2.662", "train_ppl": "6.327", "train_wps": "1.51963e+06", "train_ups": "3.77", "train_wpb": "403001", "train_bsz": "14131.5", "train_num_updates": "2915", "train_lr": "0.000728777", "train_gnorm": "0.316", "train_clip": "0", "train_oom": "0", "train_loss_scale": "40", "train_train_wall": "58", "train_wall": "792"}
2020-02-07 13:32:23 | INFO | valid | {"epoch": 8, "valid_loss": "4.17", "valid_nll_loss": "2.39", "valid_ppl": "5.241", "valid_wps": "4.27018e+06", "valid_wpb": "373365", "valid_bsz": "13099", "valid_num_updates": "2915", "valid_best_loss": "4.17"}
2020-02-07 13:33:47 | INFO | train | {"epoch": 9, "train_loss": "4.194", "train_nll_loss": "2.555", "train_ppl": "5.875", "train_wps": "1.65556e+06", "train_ups": "4.11", "train_wpb": "403014", "train_bsz": "14132.3", "train_num_updates": "3279", "train_lr": "0.000819768", "train_gnorm": "0.313", "train_clip": "0", "train_oom": "0", "train_loss_scale": "38", "train_train_wall": "58", "train_wall": "880"}
2020-02-07 13:33:56 | INFO | valid | {"epoch": 9, "valid_loss": "4.078", "valid_nll_loss": "2.317", "valid_ppl": "4.983", "valid_wps": "3.20249e+06", "valid_wpb": "373365", "valid_bsz": "13099", "valid_num_updates": "3279", "valid_best_loss": "4.078"}
2020-02-07 13:35:21 | INFO | train | {"epoch": 10, "train_loss": "4.127", "train_nll_loss": "2.482", "train_ppl": "5.587", "train_wps": "1.58462e+06", "train_ups": "3.93", "train_wpb": "403010", "train_bsz": "14134.4", "train_num_updates": "3645", "train_lr": "0.000911259", "train_gnorm": "0.327", "train_clip": "0", "train_oom": "0", "train_loss_scale": "32", "train_train_wall": "58", "train_wall": "973"}
2020-02-07 13:35:34 | INFO | valid | {"epoch": 10, "valid_loss": "4.033", "valid_nll_loss": "2.269", "valid_ppl": "4.82", "valid_wps": "3.14724e+06", "valid_wpb": "373365", "valid_bsz": "13099", "valid_num_updates": "3645", "valid_best_loss": "4.033"}
```

**Comment by nicolasspring** [comment]
Thank you for your help and comments Myle,

I was able to get comparable results to yours for the first 10 epochs by working with `--max-tokens 3584 --update-freq 128` and the loss scale did not get smaller than 1.0:
```
2020-03-25 06:29:45 | INFO | train | epoch 008 | loss 4.313 | nll_loss 2.682 | ppl 6.42 | wps 26916.5 | ups 0.07 | wpb 403014 | bsz 14134.9 | num_updates 2910 | lr 0.0007275 | gnorm 0.289 | clip 0 | oom 0 | loss_scale 1 | train_wall 5040 | wall 44215
2020-03-25 06:30:06 | INFO | valid | epoch 008 | valid on 'valid' subset | loss 4.184 | nll_loss 2.413 | ppl 5.33 | wps 71007.8 | wpb 2969.1 | bsz 104.2 | num_updates 2910 | best_loss 4.184
2020-03-25 06:30:12 | INFO | fairseq.checkpoint_utils | saved checkpoint /home/cluster/nispri/scratch/freq128/bt-probing-tasks/checkpoints/checkpoints_de_en_parallel/checkpoint8.pt (epoch 8 @ 2910 updates, score 4.184) (writing took 5.747756943106651 seconds)
2020-03-25 06:55:07 | INFO | fairseq.trainer | NOTE: overflow detected, setting loss scale to: 1.0
2020-03-25 06:55:07 | INFO | train | epoch 009:     99 / 367 loss=4.226, nll_loss=2.588, ppl=6.01, wps=26975.6, ups=0.07, wpb=403516, bsz=14222.1, num_updates=3009, lr=0.00075225, gnorm=0.314, clip=0, oom=0, loss_scale=1, train_wall=1361, wall=45722
2020-03-25 07:20:03 | INFO | train | epoch 009:    199 / 367 loss=4.217, nll_loss=2.579, ppl=5.98, wps=26845.5, ups=0.07, wpb=403669, bsz=14213.5, num_updates=3109, lr=0.00077725, gnorm=0.315, clip=0, oom=0, loss_scale=1, train_wall=2750, wall=47233
2020-03-25 07:44:57 | INFO | train | epoch 009:    299 / 367 loss=4.211, nll_loss=2.573, ppl=5.95, wps=26895.6, ups=0.07, wpb=403537, bsz=14199.4, num_updates=3209, lr=0.00080225, gnorm=0.317, clip=0, oom=0, loss_scale=1, train_wall=4123, wall=48727
2020-03-25 07:59:23 | INFO | fairseq.trainer | NOTE: overflow detected, setting loss scale to: 2.0
2020-03-25 08:01:31 | INFO | train | epoch 009 | loss 4.207 | nll_loss 2.569 | ppl 5.93 | wps 26840 | ups 0.07 | wpb 403005 | bsz 14133.1 | num_updates 3275 | lr 0.00081875 | gnorm 0.319 | clip 0 | oom 0 | loss_scale 1 | train_wall 5038 | wall 49721
2020-03-25 08:01:52 | INFO | valid | epoch 009 | valid on 'valid' subset | loss 4.109 | nll_loss 2.341 | ppl 5.07 | wps 71014.3 | wpb 2969.1 | bsz 104.2 | num_updates 3275 | best_loss 4.109
2020-03-25 08:01:58 | INFO | fairseq.checkpoint_utils | saved checkpoint /home/cluster/nispri/scratch/freq128/bt-probing-tasks/checkpoints/checkpoints_de_en_parallel/checkpoint9.pt (epoch 9 @ 3275 updates, score 4.109) (writing took 6.06958569958806 seconds)
2020-03-25 08:07:41 | INFO | fairseq.trainer | NOTE: overflow detected, setting loss scale to: 1.0
2020-03-25 08:26:52 | INFO | train | epoch 010:     99 / 367 loss=4.145, nll_loss=2.501, ppl=5.66, wps=26695.6, ups=0.07, wpb=403385, bsz=14140.8, num_updates=3374, lr=0.0008435, gnorm=0.319, clip=0, oom=0, loss_scale=1, train_wall=1374, wall=51242
2020-03-25 08:47:36 | INFO | fairseq.trainer | NOTE: overflow detected, setting loss scale to: 1.0
2020-03-25 08:51:50 | INFO | train | epoch 010:    199 / 367 loss=4.139, nll_loss=2.495, ppl=5.64, wps=26692.4, ups=0.07, wpb=403637, bsz=14214, num_updates=3473, lr=0.00086825, gnorm=0.323, clip=0, oom=0, loss_scale=1, train_wall=2750, wall=52740
2020-03-25 09:16:45 | INFO | train | epoch 010:    299 / 367 loss=4.138, nll_loss=2.494, ppl=5.63, wps=26792.8, ups=0.07, wpb=403586, bsz=14203.8, num_updates=3573, lr=0.00089325, gnorm=0.322, clip=0, oom=0, loss_scale=1, train_wall=4123, wall=54236
2020-03-25 09:29:55 | INFO | fairseq.trainer | NOTE: overflow detected, setting loss scale to: 1.0
2020-03-25 09:33:19 | INFO | train | epoch 010 | loss 4.136 | nll_loss 2.492 | ppl 5.63 | wps 26754.3 | ups 0.07 | wpb 402981 | bsz 14135.4 | num_updates 3639 | lr 0.00090975 | gnorm 0.326 | clip 0 | oom 0 | loss_scale 1 | train_wall 5037 | wall 55229
2020-03-25 09:33:40 | INFO | valid | epoch 010 | valid on 'valid' subset | loss 4.042 | nll_loss 2.285 | ppl 4.87 | wps 70974.3 | wpb 2969.1 | bsz 104.2 | num_updates 3639 | best_loss 4.042
2020-03-25 09:33:46 | INFO | fairseq.checkpoint_utils | saved checkpoint /home/cluster/nispri/scratch/freq128/bt-probing-tasks/checkpoints/checkpoints_de_en_parallel/checkpoint10.pt (epoch 10 @ 3639 updates, score 4.042) (writing took 5.878873586654663 seconds)
```

I didn't test omitting `--fp16` as the above solution worked fine.
