### ISSUE TITLE
multilingual_denoising task errors

### ISSUE THREAD

**Issue by moyid** [pytorch/fairseq#1925]
I'm trying to run the 'multilingual_denoising' task for pretraining mbart, and I get this error:
Traceback (most recent call last):
  File "/home/ubuntu/fairseq/train.py", line 11, in <module>
    cli_main()
  File "/home/ubuntu/fairseq/fairseq_cli/train.py", line 321, in cli_main
    main(args)
  File "/home/ubuntu/fairseq/fairseq_cli/train.py", line 59, in main
    task.load_dataset(valid_sub_split, combine=False, epoch=1)
  File "/home/ubuntu/fairseq/fairseq/tasks/multilingual_denoising.py", line 158, in load_dataset
    eos=None if not self.args.add_lang_token else self.source_dictionary.index('[{}]'.format(language)),
  File "/home/ubuntu/fairseq/fairseq/data/denoising_dataset.py", line 133, in __init__
    raise (f'if using subwords, use replace-length=1 or 0')
TypeError: exceptions must derive from BaseException

**Comment by huihuifan** [comment]
Can you provide more detail please? What command are you running, what dataset? @yinhanliu

**Comment by yinhanliu** [comment]
@ngoyal2707 can you take a look? I won't have time until this weekend.

**Comment by ngoyal2707** [comment]
@moyid can you please try giving `replace-length` as `span-poisson`
