### ISSUE TITLE
Transformer is not scriptable

### ISSUE THREAD

**Issue by erip** [pytorch/fairseq#1943]
## 🐛 Bug

`fairseq.model.transformer.Transformer` is not scriptable.

### To Reproduce

1. Load some pretrained transformer `model`. Example below uses `wmt14.en-fr.joined-dict.transformer`.
1. Call `torch.jit.trace_module(model, {"translate": "some dummy message"})`

#### Code sample

```
~/Downloads/wmt14.en-fr.joined-dict.transformer ⌚ 21:28:01
$ python
Python 3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 15:01:53)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from fairseq.models.transformer import TransformerModel
>>> model = TransformerModel.from_pretrained('.', 'model.pt', data_name_or_path='.', bpe='subword_nmt', bpe_codes='bpecodes', remove_bpe=True)
>>> import torch
>>> scripted_model = torch.jit.trace_module(model, {"translate": "What's up, my friends?"})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/erippeth/miniconda3/envs/fairseq-dev/lib/python3.6/site-packages/torch/jit/__init__.py", line 1028, in trace_module
    module = make_module(mod, _module_class, _compilation_unit)
  File "/Users/erippeth/miniconda3/envs/fairseq-dev/lib/python3.6/site-packages/torch/jit/__init__.py", line 727, in make_module
    return _module_class(mod, _compilation_unit=_compilation_unit)
  File "/Users/erippeth/miniconda3/envs/fairseq-dev/lib/python3.6/site-packages/torch/jit/__init__.py", line 1836, in __init__
    tmp_module._modules[name] = make_module(submodule, TracedModule, _compilation_unit=None)
  File "/Users/erippeth/miniconda3/envs/fairseq-dev/lib/python3.6/site-packages/torch/jit/__init__.py", line 727, in make_module
    return _module_class(mod, _compilation_unit=_compilation_unit)
  File "/Users/erippeth/miniconda3/envs/fairseq-dev/lib/python3.6/site-packages/torch/jit/__init__.py", line 1836, in __init__
    tmp_module._modules[name] = make_module(submodule, TracedModule, _compilation_unit=None)
  File "/Users/erippeth/miniconda3/envs/fairseq-dev/lib/python3.6/site-packages/torch/jit/__init__.py", line 723, in make_module
    return torch.jit._recursive.create_script_module_for_tracing(mod, stubs)
  File "/Users/erippeth/miniconda3/envs/fairseq-dev/lib/python3.6/site-packages/torch/jit/_recursive.py", line 281, in create_script_module_for_tracing
    return create_script_module_impl(nn_module, concrete_type, cpp_module, stubs)
  File "/Users/erippeth/miniconda3/envs/fairseq-dev/lib/python3.6/site-packages/torch/jit/_recursive.py", line 336, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/Users/erippeth/miniconda3/envs/fairseq-dev/lib/python3.6/site-packages/torch/jit/__init__.py", line 1593, in _construct
    init_fn(script_module)
  File "/Users/erippeth/miniconda3/envs/fairseq-dev/lib/python3.6/site-packages/torch/jit/_recursive.py", line 328, in init_fn
    scripted = recursive_script(orig_value)
  File "/Users/erippeth/miniconda3/envs/fairseq-dev/lib/python3.6/site-packages/torch/jit/_recursive.py", line 534, in recursive_script
    return create_script_module(nn_module, infer_methods_to_compile(nn_module))
  File "/Users/erippeth/miniconda3/envs/fairseq-dev/lib/python3.6/site-packages/torch/jit/_recursive.py", line 296, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, cpp_module, stubs)
  File "/Users/erippeth/miniconda3/envs/fairseq-dev/lib/python3.6/site-packages/torch/jit/_recursive.py", line 340, in create_script_module_impl
    create_methods_from_stubs(concrete_type, stubs)
  File "/Users/erippeth/miniconda3/envs/fairseq-dev/lib/python3.6/site-packages/torch/jit/_recursive.py", line 259, in create_methods_from_stubs
    concrete_type._create_methods(defs, rcbs, defaults)
  File "/Users/erippeth/miniconda3/envs/fairseq-dev/lib/python3.6/site-packages/torch/jit/_recursive.py", line 574, in compile_unbound_method
    create_methods_from_stubs(concrete_type, (stub,))
  File "/Users/erippeth/miniconda3/envs/fairseq-dev/lib/python3.6/site-packages/torch/jit/_recursive.py", line 259, in create_methods_from_stubs
    concrete_type._create_methods(defs, rcbs, defaults)
RuntimeError:
Module 'TransformerDecoder' has no attribute 'embed_out' :
  File "/Users/erippeth/miniconda3/envs/fairseq-dev/lib/python3.6/site-packages/fairseq/models/transformer.py", line 847
                return F.linear(features, self.embed_tokens.weight)
            else:
                return F.linear(features, self.embed_out)
                                          ~~~~~~~~~~~~~~ <--- HERE
        else:
            return features
'TransformerDecoder.output_layer' is being compiled since it was called from 'TransformerDecoder.forward'
  File "/Users/erippeth/miniconda3/envs/fairseq-dev/lib/python3.6/site-packages/fairseq/models/transformer.py", line 716
        )
        if not features_only:
            x = self.output_layer(x)
            ~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        return x, extra
```

### Expected behavior

Transformer should be scriptable and the above should yield a model that can be exported to TorchScript.

### Environment

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0): 1.4.0
 - OS (e.g., Linux): OS X
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source): `CFLAGS='-stdlib=libc++' pip install ./fairseq`
 - Python version: 3.6.10
 - CUDA/cuDNN version: N/AA
 - GPU models and configuration: N/A
 - Any other relevant information: N/A

### Additional context

Related to #1913

**Comment by myleott** [comment]
Thanks for flagging, I'll look into this. Some folks internally are actively working on scripting the full Transformer + SequenceGenerator code path, but some parts are still missing.

**Comment by erip** [comment]
I've noticed a lot of activity from @liuchen9494 to that end - very exciting. IIRC pytorch/translate had a scriptable transformer, though - did I misremember? I might try that next...

**Comment by gvskalyan** [comment]
Try this https://github.com/pytorch/translate/blob/master/pytorch_translate/test/test_export.py#L241.

**Comment by erip** [comment]
Cheers, @gvskalyan! As I understand it, my fairseq models can't be coverted to pytorch_translate models and thus exported to onnx or TorchScript, but I could train them using pytorch_translate and get that benefit, right?

**Comment by gvskalyan** [comment]
True. They have even scripted Beamsearch. But I have not observed any speed up and unable to convert the torchscripted module to ONNX format.
Please feel free to share your findings.
