### ISSUE TITLE
add_cpu with fp16 training

### ISSUE THREAD

**Issue by moussaKam** [pytorch/fairseq#1959]
Hello, I trained a model for 3 epochs using fp16. When I restored the checkpoint to continue the training I got this error.

Traceback (most recent call last):
  File "/data/home/moussa/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data/home/moussa/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/home/moussa/fairseq/train.py", line 11, in <module>
    cli_main()
  File "/data/home/moussa/fairseq/fairseq_cli/train.py", line 349, in cli_main
    main(args)
  File "/data/home/moussa/fairseq/fairseq_cli/train.py", line 100, in main
    should_end_training = train(args, trainer, task, epoch_itr)
  File "/data/home/moussa/anaconda3/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/data/home/moussa/fairseq/fairseq_cli/train.py", line 176, in train
    log_output = trainer.train_step(samples)
  File "/data/home/moussa/anaconda3/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/data/home/moussa/fairseq/fairseq/trainer.py", line 452, in train_step
    raise e
  File "/data/home/moussa/fairseq/fairseq/trainer.py", line 422, in train_step
    logging_outputs, sample_size, grad_norm,
  File "/data/home/moussa/fairseq/fairseq/trainer.py", line 741, in _reduce_and_log_stats
    metrics.log_scalar("gnorm", grad_norm, priority=400, round=3)
  File "/data/home/moussa/fairseq/fairseq/logging/metrics.py", line 132, in log_scalar
    agg[key].update(value, weight)
  File "/data/home/moussa/fairseq/fairseq/logging/meters.py", line 70, in update
    self.sum = self.sum + (val * n)
RuntimeError: "add_cpu/sub_cpu" not implemented for 'Half'

Here's the command:

python -m train data-bin --arch bart_large --task translation --source-lang source --target-lang target --criterion label_smoothed_cross_entropy --label-smoothing 0.2 --optimizer adam --adam-eps 1e-06 --adam-betas '(0.9, 0.98)' --lr 3e-05 --max-tokens 1024 --update-freq 3 --valid-subset valid --fp16 --memory-efficient-fp16 --skip-invalid-size-inputs-valid-test --restore-file checkpoints/checkpoint3.pt

**Comment by myleott** [comment]
fixed in e9014fb4245d8408ff763a4f67b8a2365c8b6f3e
