### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by AhmedTElthakeb** [pytorch/fairseq#1966]
#### What is your question?
I am trying to train transformer network for speech recognition. I am trying to run on 4 GPUs
Before it starts to train, i get this error:
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

#### Code/Command line
python train.py $PATH/librispeech_final/ --save-dir model_save --max-epoch 80 --task speech_recognition --arch vggtransformer_2 --optimizer adadelta --lr 1.0 --adadelta-eps 1e-8 --adadelta-rho 0.95 --clip-norm 10.0  --max-tokens 5000 --log-format json --log-interval 1 --criterion cross_entropy_acc --user-dir examples/speech_recognition/ --num-workers 4 --fp16

#### What's your environment?

 - fairseq Version: master
 - PyTorch Version: 1.4.0
 - OS (e.g., Linux):
Linux version 4.15.0-91-generic (buildd@lgw01-amd64-013) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020
- Python 3.8.2
 - CUDA/cuDNN version: Cuda compilation tools, release 10.0, V10.0.130
 - GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti (UUID: GPU-cc00908a-78fe-231a-b153-5292607abcef)
GPU 1: GeForce RTX 2080 Ti (UUID: GPU-ab293498-6452-3089-ff04-eeb1e53a8c65)
GPU 2: GeForce RTX 2080 Ti (UUID: GPU-494342ab-818b-ebfb-b128-8eb2cac5308a)
GPU 3: GeForce RTX 2080 Ti (UUID: GPU-215eb25d-e368-8517-4ec1-8a14cb0cac3e)

#### ERROR 

2020-04-05 09:21:22 | INFO | fairseq_cli.train | model vggtransformer_2, criterion CrossEntropyWithAccCriterion
2020-04-05 09:21:22 | INFO | fairseq_cli.train | num. model params: 315190057 (num. trained: 315190057)
2020-04-05 09:21:22 | INFO | fairseq_cli.train | training on 4 GPUs
2020-04-05 09:21:22 | INFO | fairseq_cli.train | max tokens per GPU = 5000 and max sentences per GPU = None
2020-04-05 09:21:22 | INFO | fairseq.trainer | no existing checkpoint found model_save/checkpoint_last.pt
2020-04-05 09:21:22 | INFO | fairseq.trainer | loading train data for epoch 1
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    cli_main()
  File "/home/ahmed/projects/asr_quant/fairseq/fairseq_cli/train.py", line 336, in cli_main
    torch.multiprocessing.spawn(
  File "/root/anaconda3/envs/my_env/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/root/anaconda3/envs/my_env/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/root/anaconda3/envs/my_env/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/ahmed/projects/asr_quant/fairseq/fairseq_cli/train.py", line 308, in distributed_main
    main(args, init_distributed=True)
  File "/home/ahmed/projects/asr_quant/fairseq/fairseq_cli/train.py", line 100, in main
    valid_losses = train(args, trainer, task, epoch_itr, max_update)
  File "/root/anaconda3/envs/my_env/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/ahmed/projects/asr_quant/fairseq/fairseq_cli/train.py", line 171, in train
    log_output = trainer.train_step(samples)
  File "/root/anaconda3/envs/my_env/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/ahmed/projects/asr_quant/fairseq/fairseq/trainer.py", line 380, in train_step
    raise e
  File "/home/ahmed/projects/asr_quant/fairseq/fairseq/trainer.py", line 352, in train_step
    loss, sample_size_i, logging_output = self.task.train_step(
  File "/home/ahmed/projects/asr_quant/fairseq/fairseq/tasks/fairseq_task.py", line 337, in train_step
    loss, sample_size, logging_output = criterion(model, sample)
  File "/root/anaconda3/envs/my_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ahmed/projects/asr_quant/fairseq/examples/speech_recognition/criterions/cross_entropy_acc.py", line 92, in forward
    net_output = model(**sample["net_input"])
  File "/root/anaconda3/envs/my_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/my_env/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 447, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/root/anaconda3/envs/my_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ahmed/projects/asr_quant/fairseq/fairseq/models/fairseq_model.py", line 267, in forward
    encoder_out = self.encoder(src_tokens, src_lengths=src_lengths, **kwargs)
  File "/root/anaconda3/envs/my_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ahmed/projects/asr_quant/fairseq/examples/speech_recognition/models/vggtransformer.py", line 331, in forward
    x = self.conv_layers[layer_idx](x)
  File "/root/anaconda3/envs/my_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ahmed/projects/asr_quant/fairseq/fairseq/modules/vggblock.py", line 115, in forward
    x = self.layers[i](x)
  File "/root/anaconda3/envs/my_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/my_env/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "/root/anaconda3/envs/my_env/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 341, in conv2d_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

**Comment by HiroshigeAoki** [comment]
Hello,
I encounter the same issue. How did you solve it?
