### ISSUE TITLE
Loading adaptive language models from Torch Hub fails: FileNotFoundError

### ISSUE THREAD

**Issue by aryamccarthy** [pytorch/fairseq#1978]
## 🐛 Bug

Loading adaptive language models from Torch Hub fails; there's a `FileNotFoundError`. The "missing" file is actually one level down in the directory structure. I haven't tested this with other models besides LMs. This is not broken, though, for the WMT language models.

### To Reproduce

1. Attempt to load a language model.
```
# Using the command from https://github.com/pytorch/fairseq/tree/master/examples/language_model
TORCH_HOME=/tmp python -c "import torch; en_lm = torch.hub.load('pytorch/fairseq', 'transformer_lm.wiki103.adaptive', tokenizer='moses', bpe='fastbpe')"
```
2. See error
```
copying build/lib.linux-x86_64-3.7/fairseq/libbleu.cpython-37m-x86_64-linux-gnu.so -> fairseq
copying build/lib.linux-x86_64-3.7/fairseq/data/data_utils_fast.cpython-37m-x86_64-linux-gnu.so -> fairseq/data
copying build/lib.linux-x86_64-3.7/fairseq/data/token_block_utils_fast.cpython-37m-x86_64-linux-gnu.so -> fairseq/data
copying build/lib.linux-x86_64-3.7/fairseq/libnat.cpython-37m-x86_64-linux-gnu.so -> fairseq
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1383631246/1383631246 [07:03<00:00, 3263955.74B/s]               │
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/arya/anaconda3/envs/transformer_lm/lib/python3.7/site-packages/torch/hub.py", line 366, in load
    model = entry(*args, **kwargs)
  File "/tmp/hub/pytorch_fairseq_master/fairseq/models/fairseq_model.py", line 218, in from_pretrained
    **kwargs,
  File "/tmp/hub/pytorch_fairseq_master/fairseq/hub_utils.py", line 73, in from_pretrained
    arg_overrides=kwargs,
  File "/tmp/hub/pytorch_fairseq_master/fairseq/checkpoint_utils.py", line 206, in load_model_ensemble_and_task
    task = tasks.setup_task(args)
  File "/tmp/hub/pytorch_fairseq_master/fairseq/tasks/__init__.py", line 17, in setup_task
    return TASK_REGISTRY[args.task].setup_task(args, **kwargs)
  File "/tmp/hub/pytorch_fairseq_master/fairseq/tasks/language_modeling.py", line 115, in setup_task
    dictionary = Dictionary.load(os.path.join(paths[0], "dict.txt"))
  File "/tmp/hub/pytorch_fairseq_master/fairseq/data/dictionary.py", line 195, in load
    d.add_from_file(f)
  File "/tmp/hub/pytorch_fairseq_master/fairseq/data/dictionary.py", line 208, in add_from_file
    raise fnfe
  File "/tmp/hub/pytorch_fairseq_master/fairseq/data/dictionary.py", line 205, in add_from_file
    with PathManager.open(f, "r", encoding="utf-8") as fd:
  File "/tmp/hub/pytorch_fairseq_master/fairseq/file_io.py", line 51, in open
    newline=newline,
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pytorch_fairseq/8f5513900ccbfa5196131abf5c673ce3b924f1b01df911ee9b70c3aedf3eaf09.313c555a1dd483cb77c344f7e3361a50ebcac3792ab221e999bc1c9f735f2db2/dict.txt'

```

3. Go into the directory.

```
ls /tmp/pytorch_fairseq/8f5513900ccbfa5196131abf5c673ce3b924f1b01df911ee9b70c3aedf3eaf09.313c555a1dd483cb77c344f7e3361a50ebcac3792ab221e999bc1c9f735f2db2
# data-bin/  eval.sh  model.pt
ls !$/data-bin/
# dict.txt  test.bin  test.idx  valid.bin  valid.idx
```

4. Scratch head—there's the missing file, just one level down!

### Expected behavior

Well, sure hope the file would be found! 

### Environment

 - fairseq Version (e.g., 1.0 or master): 0.9.0
 - PyTorch Version (e.g., 1.0): 1.4.0
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): `pip`
 - Build command you used (if compiling from source): N/A
 - Python version: 3.7.7
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information: N/A

**Comment by huihuifan** [comment]
@alexeib

**Comment by myleott** [comment]
Huh, good catch. I've fixed the model archives, please try again with `torch.hub.load(..., force_reload=True)`
