### ISSUE TITLE
Training crashes after a few steps with some worker encounter OOM ?

### ISSUE THREAD

**Issue by gm0616** [pytorch/fairseq#2013]
hi, team
I met an error when training on my 8GPUs machine. It is weird that the same process has been located on different GPU devices, I am confused about why this happens.
```text
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage ===============================================================|
|    0      3504      C   ...guimin.gm/miniconda3/envs/pt/bin/python 14023MiB |
|    0      3505      C   ...guimin.gm/miniconda3/envs/pt/bin/python   745MiB |
|    0      3506      C   ...guimin.gm/miniconda3/envs/pt/bin/python   745MiB |
|    0      3507      C   ...guimin.gm/miniconda3/envs/pt/bin/python   745MiB |
|    1      3504      C   ...guimin.gm/miniconda3/envs/pt/bin/python   745MiB |
|    1      3505      C   ...guimin.gm/miniconda3/envs/pt/bin/python 14023MiB |
|    1      3506      C   ...guimin.gm/miniconda3/envs/pt/bin/python   745MiB |
|    1      3507      C   ...guimin.gm/miniconda3/envs/pt/bin/python   745MiB |
|    2      3504      C   ...guimin.gm/miniconda3/envs/pt/bin/python   745MiB |
|    2      3505      C   ...guimin.gm/miniconda3/envs/pt/bin/python   745MiB |
|    2      3506      C   ...guimin.gm/miniconda3/envs/pt/bin/python 13881MiB |
|    2      3507      C   ...guimin.gm/miniconda3/envs/pt/bin/python   745MiB |
|    3      3504      C   ...guimin.gm/miniconda3/envs/pt/bin/python   745MiB |
|    3      3505      C   ...guimin.gm/miniconda3/envs/pt/bin/python   745MiB |
|    3      3506      C   ...guimin.gm/miniconda3/envs/pt/bin/python   745MiB |
|    3      3507      C   ...guimin.gm/miniconda3/envs/pt/bin/python 13851MiB |
+-----------------------------------------------------------------------------+
```

After about half of the first epoch, the training crashed, here is the reported error:
```text
Traceback (most recent call last):
  File "../../train.py", line 344, in <module>
    cli_main()
  File "../../train.py", line 336, in cli_main
    nprocs=args.distributed_world_size,
  File "/home/guimin.gm/miniconda3/envs/pt/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/guimin.gm/miniconda3/envs/pt/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception:

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/gruntdata/guimin.gm/bart/fairseq-master/fairseq/distributed_utils.py", line 177, in all_gather_list
    result.append(pickle.loads(bytes(out_buffer[2 : size + 2].tolist())))
_pickle.UnpicklingError: could not find MARK

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/guimin.gm/miniconda3/envs/pt/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/gruntdata/guimin.gm/bart/fairseq-master/train.py", line 303, in distributed_main
    main(args, init_distributed=True)
  File "/gruntdata/guimin.gm/bart/fairseq-master/train.py", line 86, in main
    train(args, trainer, task, epoch_itr)
  File "/gruntdata/guimin.gm/bart/fairseq-master/train.py", line 127, in train
    log_output = trainer.train_step(samples)
  File "/gruntdata/guimin.gm/bart/fairseq-master/fairseq/trainer.py", line 397, in train_step
    [logging_outputs, sample_sizes, ooms, self._prev_grad_norm]
  File "/gruntdata/guimin.gm/bart/fairseq-master/fairseq/distributed_utils.py", line 181, in all_gather_list
    'Unable to unpickle data from other workers. all_gather_list requires all '
Exception: Unable to unpickle data from other workers. all_gather_list requires all workers to enter the function together, so this error usually indicates that the workers have fallen out of sync somehow. Workers can fall out of sync if one of them runs out of memory, or if there are other conditions in your training script that can cause one worker to finish an epoch while other workers are still iterating over their portions of the data.
```
The task is about summarization and my command is:
```shell
TOTAL_NUM_UPDATES=10000
WARMUP_UPDATES=500
LR=3e-05
MAX_TOKENS=1024
UPDATE_FREQ=4
BART_PATH=/gruntdata/guimin.gm/bart/fairseq-master/bart-pt/bart.large.cnn/finetuned_best.pt
CUDA_VISIBLE_DEVICES=0,1,2,3 python ../../train.py /home/guimin.gm/cnndm/cnndm-data/finished_files/cnn_dm-bin \
    --restore-file $BART_PATH --seed 111\
    --max-tokens $MAX_TOKENS \
    --save-dir ../../log/align3/ \
    --task translation\
    --source-lang source --target-lang target \
    --truncate-source\
    --layernorm-embedding \
    --share-all-embeddings \
    --share-decoder-input-output-embed \
    --reset-optimizer --reset-dataloader --reset-meters \
    --required-batch-size-multiple 1 \
    --arch bart_large \
    --criterion label_smoothed_cross_entropy \
    --label-smoothing 0.1 \
    --dropout 0.1 --attention-dropout 0.1 \
    --weight-decay 0.01 --optimizer adam --adam-betas "(0.9, 0.999)" --adam-eps 1e-08 \
    --clip-norm 0.1 \
    --lr-scheduler polynomial_decay --lr $LR --total-num-update $TOTAL_NUM_UPDATES --warmup-updates $WARMUP_UPDATES \
    --update-freq $UPDATE_FREQ \
    --skip-invalid-size-inputs-valid-test \
    --find-unused-parameters;
```

PyTorch Version 1.2
CUDA/cuDNN version: 9.2
Python version: Python 3.6
GPU models and configuration: P100

Thanks a lot !

**Comment by huihuifan** [comment]
Can you reduce the batch size?

**Comment by Liatwilight** [comment]
I`ve tried to reduce the UPDATE_FREQ from 4 to 3 and set the max-sentences to 1. However, it still encounters the same problem.
