### ISSUE TITLE
I got AttributeError: module 'sacrebleu' has no attribute 'DEFAULT_TOKENIZER'.

### ISSUE THREAD

**Issue by pdc-kaminaga** [pytorch/fairseq#2049]
#### What have you tried?
!time fairseq-train \
    data-bin/iwslt14.tokenized.de-en \
    --arch transformer_iwslt_de_en --share-decoder-input-output-embed \
    --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 \
    --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 \
    --dropout 0.3 --weight-decay 0.0001 \
    --criterion label_smoothed_cross_entropy --label-smoothing 0.1 \
    --max-tokens 4096 \
    --eval-bleu \
    --eval-bleu-args '{"beam": 5, "max_len_a": 1.2, "max_len_b": 10}' \
    --eval-bleu-detok moses \
    --eval-bleu-remove-bpe \
    --eval-bleu-print-samples \
    --best-checkpoint-metric bleu --maximize-best-checkpoint-metric

2020-04-23 00:55:17 | INFO | fairseq.tasks.translation | data-bin/iwslt14.tokenized.de-en train de-en 160239 examples
epoch 001 | loss 9.592 | nll_loss 9.072 | ppl 538.049 | wps 9749.7 | ups 2.72 | wpb 3586.8 | bsz 145.5 | num_updates 1101 | lr 0.000137625 | gnorm 1.687 | clip 0 | oom 0 | train_wall 401 | wall 411
epoch 001 | valid on 'valid' subset:   0% 0/62 [00:00<?, ?it/s]2020-04-23 01:02:06 | INFO | fairseq.tasks.translation | example hypothesis: so this is so you know, you can see this is this is.
2020-04-23 01:02:06 | INFO | fairseq.tasks.translation | example reference: that's about that big.
Traceback (most recent call last):
  File "/usr/local/bin/fairseq-train", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-train')()
  File "/content/drive/My Drive/Colab Notebooks/BERT/BERTによる翻訳/fairseq/fairseq_cli/train.py", line 307, in cli_main
    main(args)
  File "/content/drive/My Drive/Colab Notebooks/BERT/BERTによる翻訳/fairseq/fairseq_cli/train.py", line 105, in main
    valid_losses = validate(args, trainer, task, epoch_itr, valid_subsets)
  File "/content/drive/My Drive/Colab Notebooks/BERT/BERTによる翻訳/fairseq/fairseq_cli/train.py", line 242, in validate
    trainer.valid_step(sample)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/content/drive/My Drive/Colab Notebooks/BERT/BERTによる翻訳/fairseq/fairseq/trainer.py", line 437, in valid_step
    sample, self.model, self.criterion
  File "/content/drive/My Drive/Colab Notebooks/BERT/BERTによる翻訳/fairseq/fairseq/tasks/translation.py", line 269, in valid_step
    bleu = self._inference_with_bleu(self.sequence_generator, sample, model)
  File "/content/drive/My Drive/Colab Notebooks/BERT/BERTによる翻訳/fairseq/fairseq/tasks/translation.py", line 356, in _inference_with_bleu
    tokenize = sacrebleu.DEFAULT_TOKENIZER if not self.args.eval_tokenized_bleu else 'none'
AttributeError: module 'sacrebleu' has no attribute 'DEFAULT_TOKENIZER'

#### What's your environment?
!pip install fairseq
Successfully installed fairseq-0.9.0 mecab-python3-0.996.5 portalocker-1.7.0 sacrebleu-1.4.7
Python 3.6.9
torch 1.4.0
Google Colab GPU

**Comment by pdc-kaminaga** [comment]
Train.py was the same.

!time python train.py \
    examples/translation/data-bin/iwslt14.tokenized.de-en \
    --arch transformer_iwslt_de_en --share-decoder-input-output-embed \
    --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 \
    --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 \
    --dropout 0.3 --weight-decay 0.0001 \
    --criterion label_smoothed_cross_entropy --label-smoothing 0.1 \
    --max-tokens 4096 \
    --eval-bleu \
    --eval-bleu-args '{"beam": 5, "max_len_a": 1.2, "max_len_b": 10}' \
    --eval-bleu-detok moses \
    --eval-bleu-remove-bpe \
    --eval-bleu-print-samples \
    --best-checkpoint-metric bleu --maximize-best-checkpoint-metric
    
2020-04-23 02:26:59 | INFO | fairseq_cli.train | model transformer_iwslt_de_en, criterion LabelSmoothedCrossEntropyCriterion
2020-04-23 02:26:59 | INFO | fairseq_cli.train | num. model params: 39469056 (num. trained: 39469056)
2020-04-23 02:27:02 | INFO | fairseq_cli.train | training on 1 GPUs
2020-04-23 02:27:02 | INFO | fairseq_cli.train | max tokens per GPU = 4096 and max sentences per GPU = None
2020-04-23 02:27:02 | INFO | fairseq.trainer | no existing checkpoint found checkpoints/checkpoint_last.pt
2020-04-23 02:27:02 | INFO | fairseq.trainer | loading train data for epoch 0
2020-04-23 02:27:02 | INFO | fairseq.data.data_utils | loaded 160239 examples from: examples/translation/data-bin/iwslt14.tokenized.de-en/train.de-en.de
2020-04-23 02:27:02 | INFO | fairseq.data.data_utils | loaded 160239 examples from: examples/translation/data-bin/iwslt14.tokenized.de-en/train.de-en.en
2020-04-23 02:27:02 | INFO | fairseq.tasks.translation | examples/translation/data-bin/iwslt14.tokenized.de-en train de-en 160239 examples
epoch 001 | loss 9.592 | nll_loss 9.072 | ppl 538.049 | wps 9659.3 | ups 2.69 | wpb 3586.8 | bsz 145.5 | num_updates 1101 | lr 0.000137625 | gnorm 1.687 | clip 0 | oom 0 | train_wall 405 | wall 410
epoch 001 | valid on 'valid' subset:   0% 0/62 [00:00<?, ?it/s]2020-04-23 02:33:54 | INFO | fairseq.tasks.translation | example hypothesis: so this is so you know, you can see this is this is.
2020-04-23 02:33:54 | INFO | fairseq.tasks.translation | example reference: that's about that big.
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    cli_main()
  File "/content/drive/My Drive/Colab Notebooks/BERT/BERTによる翻訳/fairseq/fairseq_cli/train.py", line 307, in cli_main
    main(args)
  File "/content/drive/My Drive/Colab Notebooks/BERT/BERTによる翻訳/fairseq/fairseq_cli/train.py", line 105, in main
    valid_losses = validate(args, trainer, task, epoch_itr, valid_subsets)
  File "/content/drive/My Drive/Colab Notebooks/BERT/BERTによる翻訳/fairseq/fairseq_cli/train.py", line 242, in validate
    trainer.valid_step(sample)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/content/drive/My Drive/Colab Notebooks/BERT/BERTによる翻訳/fairseq/fairseq/trainer.py", line 437, in valid_step
    sample, self.model, self.criterion
  File "/content/drive/My Drive/Colab Notebooks/BERT/BERTによる翻訳/fairseq/fairseq/tasks/translation.py", line 269, in valid_step
    bleu = self._inference_with_bleu(self.sequence_generator, sample, model)
  File "/content/drive/My Drive/Colab Notebooks/BERT/BERTによる翻訳/fairseq/fairseq/tasks/translation.py", line 356, in _inference_with_bleu
    tokenize = sacrebleu.DEFAULT_TOKENIZER if not self.args.eval_tokenized_bleu else 'none'
AttributeError: module 'sacrebleu' has no attribute 'DEFAULT_TOKENIZER'

**Comment by pdc-kaminaga** [comment]
The latest code download solved it.
Thank you.

**Comment by irugina** [comment]
Hello! I'm running into the same issue and cannot afford to try the most recent fairseq version. Does anyone know exactly where this problem comes from? Thank you!

**Comment by myleott** [comment]
@irugina, it's due to an upstream change in sacrebleu. Here's the fix: adff51b4a67c5000aabbe0e00a7bc4b28e855794
