### ISSUE TITLE
AssertionError: sentence at index 2618 of size 513 exceeds max_tokens limit of 512!

### ISSUE THREAD

**Issue by wasiahmad** [pytorch/fairseq#2063]
I am training BART on a summarization dataset and encountered the following error.

```
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/local/wasiahmad/software/anaconda3/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/wasiahmad/workspace/git_repos/fairseq/fairseq_cli/train.py", line 324, in distributed_main
    main(args, init_distributed=True)
  File "/home/wasiahmad/workspace/git_repos/fairseq/fairseq_cli/train.py", line 117, in main
    valid_losses = train(args, trainer, task, epoch_itr, max_update)
  File "/local/wasiahmad/software/anaconda3/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/wasiahmad/workspace/git_repos/fairseq/fairseq_cli/train.py", line 201, in train
    valid_losses = validate_and_save(args, trainer, task, epoch_itr, valid_subsets)
  File "/home/wasiahmad/workspace/git_repos/fairseq/fairseq_cli/train.py", line 241, in validate_and_save
    valid_losses = validate(args, trainer, task, epoch_itr, valid_subsets)
  File "/home/wasiahmad/workspace/git_repos/fairseq/fairseq_cli/train.py", line 278, in validate
    num_workers=args.num_workers,
  File "/home/wasiahmad/workspace/git_repos/fairseq/fairseq/tasks/fairseq_task.py", line 181, in get_batch_iterator
    required_batch_size_multiple=required_batch_size_multiple,
  File "/home/wasiahmad/workspace/git_repos/fairseq/fairseq/data/data_utils.py", line 234, in batch_by_size
    return batch_by_size_fast(indices, num_tokens_fn, max_tokens, max_sentences, bsz_mult)
  File "fairseq/data/data_utils_fast.pyx", line 27, in fairseq.data.data_utils_fast.batch_by_size_fast
  File "fairseq/data/data_utils_fast.pyx", line 50, in fairseq.data.data_utils_fast.batch_by_size_fast
AssertionError: sentence at index 2618 of size 513 exceeds max_tokens limit of 512!
```

I am following this [documentation](https://github.com/pytorch/fairseq/blob/master/examples/bart/README.summarization.md). I checked Fairseq documentation but couldn't find how to resolve this issue. Please help!

**Comment by lematt1991** [comment]
Try adding `--skip-invalid-size-inputs-valid-test` to your command

**Comment by sajastu** [comment]
@lematt1991 Is there any option that the input is truncated instead of skipping?
