### ISSUE TITLE
Can not train with multi-gpus

### ISSUE THREAD

**Issue by Jambalaya11** [pytorch/fairseq#2064]
## ❓ Questions and Help
Starting with  IWSLT 2014 dataset,  train.py works fine only if CUDA_VISIBLE_DEVICES is set with only one GPU. 
* If I use Multi-GPUs by setting CUDA_VISIBLE_DEVICES=0,1,2,3 or just removing CUDA_VISIBLE_DEVICES option from command line
```
Error: mkl-service + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp.so.1 library.
	Try to import numpy first or set the threading layer accordingly. Set MKL_SERVICE_FORCE_INTEL to force it.
Error: mkl-service + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp.so.1 library.
	Try to import numpy first or set the threading layer accordingly. Set MKL_SERVICE_FORCE_INTEL to force it.
Error: mkl-service + Intel(R) MKL: MKL_THREADING_LAYER=INTEL is incompatible with libgomp.so.1 library.
	Try to import numpy first or set the threading layer accordingly. Set MKL_SERVICE_FORCE_INTEL to force it.
Traceback (most recent call last):
  File "/home/anaconda3/bin/fairseq-train", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-train')()
  File "/workhub/codes/fairseq/fairseq_cli/train.py", line 339, in cli_main
    nprocs=args.distributed_world_size,
  File "/home/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/home/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 113, in join
    (error_index, exitcode)
Exception: process 1 terminated with exit code 1
```
* If I use torch.distributed.launch, python -m torch.distributed.launch --nproc_per_node 1 train.py data-bin/iwslt14.tokenized.de-en  --lr 0.25 --clip-norm 0.1 --dropout 0.2 --max-tokens 400
```
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    cli_main()
  File "/workhub/codes/fairseq/fairseq_cli/train.py", line 326, in cli_main
    nprocs=torch.cuda.device_count(),
  File "/home/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/home/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception:

-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/workhub/codes/fairseq/fairseq_cli/train.py", line 308, in distributed_main
    main(args, init_distributed=True)
  File "/workhub/codes/fairseq/fairseq_cli/train.py", line 48, in main
    args.distributed_rank = distributed_utils.distributed_init(args)
  File "/workhub/codes/fairseq/fairseq/distributed_utils.py", line 81, in distributed_init
    raise ValueError('Cannot initialize distributed with distributed_world_size=1')
ValueError: Cannot initialize distributed with distributed_world_size=1

Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/anaconda3/bin/python', '-u', 'train.py', '--local_rank=0', 'data-bin/iwslt14.tokenized.de-en', '--lr', '0.25', '--clip-norm', '0.1', '--dropout', '0.2', '--max-tokens', '400']' returned non-zero exit status 1.
```
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
I installed NCCL as it's shown in 3.1 https://docs.nvidia.com/deeplearning/sdk/nccl-install-guide/index.html. And I'm not sure if the error is relevant with nccl.
#### What's your environment?

 - fairseq Version (0.9.0)
 - PyTorch Version (1.5.0)
 - OS (Linux Ubuntu18.04)
 - How you installed fairseq (pip install --editable .):
 - Python version: 3.7
 - CUDA/cuDNN version: 10.2/7.6.5
 - GPU models and configuration: Tesla K80
 - Any other relevant information: NCCL 2.6.4

**Comment by Jambalaya11** [comment]
The problem is solved by downgrading pytorch from 1.5.0 to 1.4.0.

**Comment by myleott** [comment]
If it works on one GOU, then seems like an issue with your environment rather than fairseq. Can you try running some of the nccl-tests: https://github.com/NVIDIA/nccl-tests and also the pytorch distributed tests: https://github.com/pytorch/pytorch/tree/master/test/distributed

**Comment by alexholdenmiller** [comment]
For what it's worth, I got same error in completely unrelated (single-GPU) code due to upgrading to PyTorch 1.5.0. Setting `MKL_SERVICE_FORCE_INTEL=1` made the error message go away and the code worked but I don't know what side effects it may have had in performance.

Related bug on pytorch repo: https://github.com/pytorch/pytorch/issues/37377

**Comment by rishabhjoshi** [comment]
@alexholdenmiller Can you confirm if there were any side effects in terms of performance?

**Comment by alexholdenmiller** [comment]
I didn't benchmark it carefully in this case (and note that this appeared to be necessary in pytorch 1.6 as well), though it would be hard to tell if it was due to changing this flag or due to the new version though since both happened at once. However, I didn't notice any drastic change in performance (positive or negative) with the version changes in my code base.

**Comment by protonish** [comment]
The error persists in PyTorch 1.7 when using `fairseq`.

The ugly fix that works for sure is to use either of `os.environ['MKL_THREADING_LAYER'] = 'GNU' ` or `os.environ['MKL_SERVICE_FORCE_INTEL'] = '1'` . 

The problem, however, because of this workaround is that when training on multiple GPUs, once the training is done, the process won't quit and will just sit there hogging the GPUs. When I manually `ctrl + c` the process, it abruptly exits with a bunch of `multiprocessing.py` errors, followed by `{integer} semaphores leaked to clean up at shut down` warning message.
```
^CTraceback (most recent call last):
  File "train.py", line 15, in <module>
Process SpawnProcess-1:
    cli_main()
  File "/abc/fair/fairmod2/fairseq_cli/train.py", line 462, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/abc/fair/fairmod2/fairseq/distributed/utils.py", line 338, in call_main
    torch.multiprocessing.spawn(
  File "/xyz/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
2021-03-15 18:44:32 | INFO | wandb.sdk.internal.internal | Internal process exited
2021-03-15 18:44:32 | INFO | wandb.sdk.internal.internal | Internal process exited
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/xyz/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/xyz/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 75, in join
    ready = multiprocessing.connection.wait(
  File "/xyz/lib/python3.8/multiprocessing/connection.py", line 931, in wait
    ready = selector.select(timeout)
  File "/xyz/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
Traceback (most recent call last):
2021-03-15 18:44:32 | INFO | wandb.sdk.internal.internal | Internal process exited
  File "/xyz/lib/python3.8/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
  File "/xyz/lib/python3.8/multiprocessing/util.py", line 357, in _exit_function
    p.join()
  File "/xyz/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/xyz/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/xyz/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
```

Its annoying that the process won't quit by itself even hours after training is done. It just sits there. I haven't encountered this when using on a single GPU.

[This PyTorch bug](https://github.com/pytorch/pytorch/issues/37377) talks about this issue as well.

**Comment by senchfu** [comment]
> The error persists with PyTorch 1.7 when using `fairseq`.
> 
> The ugly fix that works for sure is to use either of `os.environ['MKL_THREADING_LAYER'] = 'GNU' ` or `os.environ['MKL_SERVICE_FORCE_INTEL'] = '1'` . This lets the code run as expected.
> 
> The problem, however, because of this workaround is that when training on multiple GPUs, once the training is done, the process won't quit and will just sit there hogging the GPUs. When I manually `ctrl + c` the process, it abruptly exits with a bunch of `multiprocessing` errors, followed by `{integer} semaphores leaked to clean up at shut down` warning message.
> 
> ```
> ^CTraceback (most recent call last):
>   File "train.py", line 15, in <module>
> Process SpawnProcess-1:
>     cli_main()
>   File "/abc/fair/fairmod2/fairseq_cli/train.py", line 462, in cli_main
>     distributed_utils.call_main(cfg, main)
>   File "/abc/fair/fairmod2/fairseq/distributed/utils.py", line 338, in call_main
>     torch.multiprocessing.spawn(
>   File "/xyz/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
> 2021-03-15 18:44:32 | INFO | wandb.sdk.internal.internal | Internal process exited
> 2021-03-15 18:44:32 | INFO | wandb.sdk.internal.internal | Internal process exited
>     return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
>   File "/xyz/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
>     while not context.join():
>   File "/xyz/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 75, in join
>     ready = multiprocessing.connection.wait(
>   File "/xyz/lib/python3.8/multiprocessing/connection.py", line 931, in wait
>     ready = selector.select(timeout)
>   File "/xyz/lib/python3.8/selectors.py", line 415, in select
>     fd_event_list = self._selector.poll(timeout)
> KeyboardInterrupt
> Traceback (most recent call last):
> 2021-03-15 18:44:32 | INFO | wandb.sdk.internal.internal | Internal process exited
>   File "/xyz/lib/python3.8/multiprocessing/process.py", line 318, in _bootstrap
>     util._exit_function()
>   File "/xyz/lib/python3.8/multiprocessing/util.py", line 357, in _exit_function
>     p.join()
>   File "/xyz/lib/python3.8/multiprocessing/process.py", line 149, in join
>     res = self._popen.wait(timeout)
>   File "/xyz/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
>     return self.poll(os.WNOHANG if timeout == 0.0 else 0)
>   File "/xyz/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
>     pid, sts = os.waitpid(self.pid, flag)
> KeyboardInterrupt
> 
> /xyz/lib/python3.8/multiprocessing/resource_tracker.py:216: 
> UserWarning: resource_tracker: There appear to be 12 leaked semaphore objects to clean up at shutdown
> ```
> 
> Its annoying that the process won't quit by itself even hours after training is done. It just sits there. I haven't encountered this when using on a single GPU.
> 
> [This PyTorch bug](https://github.com/pytorch/pytorch/issues/37377) talks about this issue as well.

I meet the same problem like you.
