### ISSUE TITLE
Help: Understanding why multiprocessing_bpe_encoder.py adds sentences to dataset and how to proceed with my classification task

### ISSUE THREAD

**Issue by rm3887** [pytorch/fairseq#2102]
## What is your question?
I am following the steps in the custom_classification.md regarding fine-tuning RoBERTa on my classification task. I noticed that when I run multiprocessing_bpe_encoder.py on my train, val, test datasets, it is processing more lines than in the original dataset. This is shown below when I preprocess train, val, test.
#### Code
```
!python /content/fairseq_repo/examples/roberta/multiprocessing_bpe_encoder.py \
      --encoder-json '/tmp/model-0/content/pretraining_output/tk-vocab.json' \
      --vocab-bpe '/tmp/model-0/content/pretraining_output/tk-merges.txt' \
      --inputs "/content/data/train_texts.tsv" \
      --outputs "/content/data/train.input0.bpe" \
      --workers 60 \
      --keep-empty

!python /content/fairseq_repo/examples/roberta/multiprocessing_bpe_encoder.py \
      --encoder-json '/tmp/model-0/content/pretraining_output/tk-vocab.json' \
      --vocab-bpe '/tmp/model-0/content/pretraining_output/tk-merges.txt' \
      --inputs "/content/data/train_labels.tsv" \
      --outputs "/content/data/train.label" \
      --workers 60 \
      --keep-empty
```

```
2020-05-07 20:05:41 | INFO | fairseq_cli.preprocess | Namespace(align_suffix=None, alignfile=None, bpe='gpt2', cpu=False, criterion='cross_entropy', dataset_impl='mmap', destdir='/content/reddit-bin/input0', empty_cache_freq=0, fp16=False, fp16_init_scale=128, fp16_scale_tolerance=0.0, fp16_scale_window=None, joined_dictionary=False, log_format=None, log_interval=1000, lr_scheduler='fixed', memory_efficient_fp16=False, min_loss_scale=0.0001, no_progress_bar=False, nwordssrc=-1, nwordstgt=-1, only_source=True, optimizer='nag', padding_factor=8, seed=1, source_lang=None, srcdict='dict.txt', target_lang=None, task='translation', tensorboard_logdir='', testpref='/content/data/test.input0.bpe', tgtdict=None, threshold_loss_scale=None, thresholdsrc=0, thresholdtgt=0, tokenizer=None, trainpref='/content/data/train.input0.bpe', user_dir=None, validpref='/content/data/val.input0.bpe', workers=60)
2020-05-07 20:05:41 | INFO | fairseq_cli.preprocess | [None] Dictionary: 50263 types
2020-05-07 20:05:46 | INFO | fairseq_cli.preprocess | [None] /content/data/train.input0.bpe: 17486 sents, 530589 tokens, 1.02% replaced by <unk>
2020-05-07 20:05:46 | INFO | fairseq_cli.preprocess | [None] Dictionary: 50263 types
2020-05-07 20:05:48 | INFO | fairseq_cli.preprocess | [None] /content/data/val.input0.bpe: 3892 sents, 116555 tokens, 1.08% replaced by <unk>
2020-05-07 20:05:48 | INFO | fairseq_cli.preprocess | [None] Dictionary: 50263 types
2020-05-07 20:05:51 | INFO | fairseq_cli.preprocess | [None] /content/data/test.input0.bpe: 3562 sents, 106116 tokens, 0.999% replaced by <unk>
2020-05-07 20:05:51 | INFO | fairseq_cli.preprocess | Wrote preprocessed data to /content/reddit-bin/input0
2020-05-07 20:05:53 | INFO | fairseq_cli.preprocess | Namespace(align_suffix=None, alignfile=None, bpe='gpt2', cpu=False, criterion='cross_entropy', dataset_impl='mmap', destdir='/content/reddit-bin/label', empty_cache_freq=0, fp16=False, fp16_init_scale=128, fp16_scale_tolerance=0.0, fp16_scale_window=None, joined_dictionary=False, log_format=None, log_interval=1000, lr_scheduler='fixed', memory_efficient_fp16=False, min_loss_scale=0.0001, no_progress_bar=False, nwordssrc=-1, nwordstgt=-1, only_source=True, optimizer='nag', padding_factor=8, seed=1, source_lang=None, srcdict=None, target_lang=None, task='translation', tensorboard_logdir='', testpref='/content/data/test.label', tgtdict=None, threshold_loss_scale=None, thresholdsrc=0, thresholdtgt=0, tokenizer=None, trainpref='/content/data/train.label', user_dir=None, validpref='/content/data/val.label', workers=60)
2020-05-07 20:05:54 | INFO | fairseq_cli.preprocess | [None] Dictionary: 7 types
2020-05-07 20:05:54 | INFO | fairseq_cli.preprocess | [None] /content/data/train.label: 9560 sents, 19120 tokens, 0.0% replaced by <unk>
2020-05-07 20:05:54 | INFO | fairseq_cli.preprocess | [None] Dictionary: 7 types
2020-05-07 20:05:55 | INFO | fairseq_cli.preprocess | [None] /content/data/val.label: 2048 sents, 4096 tokens, 0.0% replaced by <unk>
2020-05-07 20:05:55 | INFO | fairseq_cli.preprocess | [None] Dictionary: 7 types
2020-05-07 20:05:55 | INFO | fairseq_cli.preprocess | [None] /content/data/test.label: 2048 sents, 4096 tokens, 0.0% replaced by <unk>
2020-05-07 20:05:55 | INFO | fairseq_cli.preprocess | Wrote preprocessed data to /content/reddit-bin/label   
```

As you can see above, train.input0.bpe has 17486 sents, while train.label has 9560 sents. This is causing issues with training the model since the two datasets are not equal length.
```
TOTAL_UPDATES=125000    # Total number of training steps
WARMUP_UPDATES=10000    # Warmup the learning rate over this many updates
PEAK_LR=1e-05         # Peak learning rate, adjust as needed
TOKENS_PER_SAMPLE=512   # Max sequence length
NUM_CLASSES=2
MAX_POSITIONS=512       # Num. positional embeddings (usually same as above)
MAX_SENTENCES=16        # Number of sequences per batch (batch size)
UPDATE_FREQ=16          # Increase the batch size 16x
ROBERTA_PATH=r'/content/drive/My\Drive/Colab\Notebooks/NLU/checkpoint_best.pt'    

!python /usr/local/lib/python3.6/dist-packages/fairseq_cli/train.py \
    --fp16 /content/reddit-bin/ \
    --restore-file $ROBERTA_PATH \
    --num-classes $NUM_CLASSES \
    --max-positions $MAX_POSITIONS \
    --task sentence_prediction \
    --criterion sentence_prediction \
    --arch roberta_base \
    --max-sentences-valid 2048 \
    --optimizer adam --adam-betas '(0.9,0.98)' --adam-eps 1e-6 --clip-norm 0.0 \
    --lr-scheduler polynomial_decay --lr $PEAK_LR --warmup-updates $WARMUP_UPDATES --total-num-update $TOTAL_UPDATES \
    --dropout 0.1 --attention-dropout 0.1 --weight-decay 0.1 \
    --max-sentences $MAX_SENTENCES --update-freq $UPDATE_FREQ \
    --max-update $TOTAL_UPDATES --log-format simple --log-interval 1 \
    --skip-invalid-size-inputs-valid-test \
    --num-workers	1 \
    --me 8 \
    --reset-optimizer --reset-dataloader --reset-meters \
    --best-checkpoint-metric accuracy --maximize-best-checkpoint-metric \
    --truncate-sequence \
    --find-unused-parameters \
    --update-freq 4 \
    --save-dir DRIVE
```

```
Namespace(activation_dropout=0.0, activation_fn='gelu', adam_betas='(0.9,0.98)', adam_eps=1e-06, add_prev_output_tokens=False, arch='roberta_base', attention_dropout=0.1, best_checkpoint_metric='accuracy', bpe=None, bucket_cap_mb=25, clip_norm=0.0, cpu=False, criterion='sentence_prediction', curriculum=0, data='/content/reddit-bin/', dataset_impl=None, ddp_backend='c10d', device_id=0, disable_validation=False, distributed_backend='nccl', distributed_init_method=None, distributed_no_spawn=False, distributed_port=-1, distributed_rank=0, distributed_world_size=1, dropout=0.1, empty_cache_freq=0, encoder_attention_heads=12, encoder_embed_dim=768, encoder_ffn_embed_dim=3072, encoder_layerdrop=0, encoder_layers=12, encoder_layers_to_keep=None, end_learning_rate=0.0, fast_stat_sync=False, find_unused_parameters=True, fix_batches_to_gpus=False, fixed_validation_seed=None, force_anneal=None, fp16=True, fp16_init_scale=128, fp16_scale_tolerance=0.0, fp16_scale_window=None, init_token=None, keep_interval_updates=-1, keep_last_epochs=-1, log_format='simple', log_interval=1, lr=[1e-05], lr_scheduler='polynomial_decay', max_epoch=8, max_positions=512, max_sentences=16, max_sentences_valid=2048, max_tokens=None, max_tokens_valid=None, max_update=125000, maximize_best_checkpoint_metric=True, memory_efficient_fp16=False, min_loss_scale=0.0001, min_lr=-1, no_epoch_checkpoints=False, no_last_checkpoints=False, no_progress_bar=False, no_save=False, no_save_optimizer_state=False, no_shuffle=False, num_classes=2, num_workers=1, optimizer='adam', optimizer_overrides='{}', pooler_activation_fn='tanh', pooler_dropout=0.0, power=1.0, regression_target=False, required_batch_size_multiple=8, reset_dataloader=True, reset_lr_scheduler=False, reset_meters=True, reset_optimizer=True, restore_file='/content/drive/MyDrive/ColabNotebooks/NLU/checkpoint_best.pt', save_dir='DRIVE', save_interval=1, save_interval_updates=0, save_predictions=None, seed=1, sentence_avg=False, separator_token=None, skip_invalid_size_inputs_valid_test=True, task='sentence_prediction', tensorboard_logdir='', threshold_loss_scale=None, tokenizer=None, total_num_update=125000, train_subset='train', truncate_sequence=True, update_freq=[4], use_bmuf=False, user_dir=None, valid_subset='valid', validate_interval=1, warmup_updates=10000, weight_decay=0.1)
| [input] dictionary: 50265 types
| [label] dictionary: 9 types
| loaded 3892 examples from: /content/reddit-bin/input0/valid
| loaded 2048 examples from: /content/reddit-bin/label/valid
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/fairseq_cli/train.py", line 337, in <module>
    cli_main()
  File "/usr/local/lib/python3.6/dist-packages/fairseq_cli/train.py", line 333, in cli_main
    main(args)
  File "/usr/local/lib/python3.6/dist-packages/fairseq_cli/train.py", line 48, in main
    task.load_dataset(valid_sub_split, combine=False, epoch=0)
  File "/usr/local/lib/python3.6/dist-packages/fairseq/tasks/sentence_prediction.py", line 189, in load_dataset
    sizes=[src_tokens.sizes],
  File "/usr/local/lib/python3.6/dist-packages/fairseq/data/nested_dictionary_dataset.py", line 60, in __init__
    assert len(v) == len(first), 'dataset lengths must match'
AssertionError: dataset lengths must match
```

## Environment
I'm working on Google Colab.

**Comment by curranmaguire** [comment]
can you post the fix please
