### ISSUE TITLE
Inconsistent dictionary for released wikitext-103 models

### ISSUE THREAD

**Issue by Sohyo** [pytorch/fairseq#2124]
Hello

I am basically want to evaluate the perplexity of the pre-trained language models. Therefore I replicate the example from [here](https://github.com/pytorch/fairseq/blob/master/examples/language_model/README.md). 

My command line is like this

`fairseq-eval-lm data-bin/wikitext-103 \
    --path data-bin/adaptive_lm_wiki103/model.pt \
    --max-sentences 2 \
    --tokens-per-sample 512 \
    --context-window 2000`

This works few days ago even though the perplexity was pretty high ( it was around 197..).
And after commit [6209d7d](https://github.com/pytorch/fairseq/commit/6209d7d6b2c41fccb01e00671261be80ba86029a), when 
I run the same command line, I have runtime error like below:

`  File "/data/s3475743/venv/bin/fairseq-eval-lm", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-eval-lm')()
  File "/data/s3475743/download_LM/fairseq/fairseq_cli/eval_lm.py", line 252, in cli_main
    distributed_utils.call_main(args, main)
  File "/data/s3475743/download_LM/fairseq/fairseq/distributed_utils.py", line 173, in call_main
    main(args, **kwargs)
  File "/data/s3475743/download_LM/fairseq/fairseq_cli/eval_lm.py", line 80, in main
    suffix=getattr(parsed_args, "checkpoint_suffix", ""),
  File "/data/s3475743/download_LM/fairseq/fairseq/checkpoint_utils.py", line 190, in load_model_ensemble
    filenames, arg_overrides, task, strict, suffix,
  File "/data/s3475743/download_LM/fairseq/fairseq/checkpoint_utils.py", line 211, in load_model_ensemble_and_task
    model.load_state_dict(state["model"], strict=strict, args=args)
  File "/data/s3475743/download_LM/fairseq/fairseq/models/fairseq_model.py", line 93, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/data/s3475743/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for TransformerLanguageModel:
	Missing key(s) in state_dict: "decoder.output_projection.weight". `

Also, I did not train the model, so I basically download it and evaluate the same wiki-103 dataset.

Thank you in advance

**Comment by myleott** [comment]
Thanks, this is an issue with adaptive softmax + recent changes that broke backward compatibility. I'll submit a fix shortly.

After the fix, this is what I get:
```bash
$ fairseq-eval-lm data-bin/wikitext-103 --path adaptive_lm_wiki103/model.pt --max-sentences 2 --tokens-per-sample 512 --context-window 2000
# (...)
# 2020-05-13 06:59:43 | INFO | fairseq_cli.eval_lm | Loss (base 2): 4.2274, Perplexity: 18.73
```

**Comment by Sohyo** [comment]
Thank you so much for your reply!!

I just pulled git and tried out what you suggested.
However, I still has the same error.


`fairseq-eval-lm data-bin/wikitext-103 --path data-bin/adaptive_lm_wiki103/model.pt --max-sentences 2 --tokens-per-sample 512 --context-window 2000`

`Traceback (most recent call last):
  File "/data/s3475743/venv/bin/fairseq-eval-lm", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-eval-lm')()
  File "/data/s3475743/download_LM/fairseq/fairseq_cli/eval_lm.py", line 252, in cli_main
    distributed_utils.call_main(args, main)
  File "/data/s3475743/download_LM/fairseq/fairseq/distributed_utils.py", line 173, in call_main
    main(args, **kwargs)
  File "/data/s3475743/download_LM/fairseq/fairseq_cli/eval_lm.py", line 80, in main
    suffix=getattr(parsed_args, "checkpoint_suffix", ""),
  File "/data/s3475743/download_LM/fairseq/fairseq/checkpoint_utils.py", line 190, in load_model_ensemble
    filenames, arg_overrides, task, strict, suffix,
  File "/data/s3475743/download_LM/fairseq/fairseq/checkpoint_utils.py", line 211, in load_model_ensemble_and_task
    model.load_state_dict(state["model"], strict=strict, args=args)
  File "/data/s3475743/download_LM/fairseq/fairseq/models/fairseq_model.py", line 94, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/data/s3475743/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for TransformerLanguageModel:
	Missing key(s) in state_dict: "decoder.output_projection.weight".`

Do you think I still miss out something?

**Comment by Sohyo** [comment]
Thank you so much for your reply!
I tried with your fix and now I can get perplexity.

However, the perplexity score is pretty higher than yours. I am not so sure why mine is way higher.

This is what I got  :

`fairseq-eval-lm data-bin/wikitext-103 --path data-bin/adaptive_lm_wiki103/model.pt --max-sentences 2 --tokens-per-sample 512 --context-window 2000`

And this is the results:

`
2020-05-14 11:41:34 | INFO | fairseq.tasks.language_modeling | dictionary: 267744 types
2020-05-14 11:41:34 | INFO | fairseq_cli.eval_lm | loading model(s) from data-bin/adaptive_lm_wiki103/model.pt
2020-05-14 11:41:43 | INFO | fairseq.tasks.language_modeling | dictionary: 267744 types
2020-05-14 11:41:43 | INFO | fairseq.data.data_utils | loaded 4358 examples from: data-bin/wikitext-103/test
2020-05-14 11:41:44 | INFO | fairseq_cli.eval_lm | data-bin/wikitext-103 test 230 examples
2020-05-14 11:41:52 | INFO | fairseq_cli.eval_lm | num. model params: 246933504

2020-05-14 11:42:38 | INFO | fairseq.logging.progress_bar | :    101 / 115 wps=4638
2020-05-14 11:42:45 | INFO | fairseq_cli.eval_lm | Evaluated 245569 tokens in 52.2s (4699.92 tokens/s)
2020-05-14 11:42:45 | INFO | fairseq_cli.eval_lm | Loss (base 2): 7.6252, Perplexity: 197.43
`

Again, thanks for fix!

**Comment by myleott** [comment]
Ah, shoot, I figured it out. The wikitext-103 dictionary used for that model isn't the same as the one originally used (`dict.txt` had a slightly different order, since it was generated before this fix: https://github.com/pytorch/fairseq/commit/10ad74953f671168c474d0da5700d91661e2b5a2).

So you'll need to preprocess wikitext-103 using that dictionary.

I'm going to update the docs with info about this.

**Comment by AmirAktify** [comment]
Just to ask, does this bug also effect the `WMT-19` English language models? Or was it generated after the dictionary order was made deterministic?

**Comment by myleott** [comment]
> Just to ask, does this bug also effect the WMT-19 English language models? Or was it generated after the dictionary order was made deterministic?

No, the issue here is if you download the wikitext-103 dataset and preprocess it from scratch, it generates a dictionary that's not compatible with the released wikitext-103 model checkpoint. The workaround is to preprocess the data using the dictionary provided in the model archive.

For the WMT'19 language models, since we don't release instructions for preparing the data from scratch, this isn't really an issue -- you're always going to use the provided dictionary file since that's the only option available.

**Comment by myleott** [comment]
I've retrained the model to use the new dictionary (the one produced on master), available here: https://dl.fbaipublicfiles.com/fairseq/models/lm/adaptive_lm_wiki103.v2.tar.bz2
