### ISSUE TITLE
No module named 'fairseq.data.data_utils_fast' 

### ISSUE THREAD

**Issue by dahaogewsh** [pytorch/fairseq#2165]
my question is  No module named 'fairseq.data.data_utils_fast' when i eval the transformer model.
this is my error

Traceback (most recent call last):
  File "/data/dev/wangsenhao/pascal/fairseq/fairseq/data/data_utils.py", line 219, in batch_by_size
    from fairseq.data.data_utils_fast import batch_by_size_fast
ModuleNotFoundError: No module named 'fairseq.data.data_utils_fast'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generate.py", line 11, in <module>
    cli_main()
  File "/data/dev/wangsenhao/pascal/fairseq/fairseq_cli/generate.py", line 269, in cli_main
    main(args)
  File "/data/dev/wangsenhao/pascal/fairseq/fairseq_cli/generate.py", line 36, in main
    return _main(args, sys.stdout)
  File "/data/dev/wangsenhao/pascal/fairseq/fairseq_cli/generate.py", line 103, in _main
    num_workers=args.num_workers,
  File "/data/dev/wangsenhao/pascal/fairseq/fairseq/tasks/fairseq_task.py", line 181, in get_batch_iterator
    required_batch_size_multiple=required_batch_size_multiple,
  File "/data/dev/wangsenhao/pascal/fairseq/fairseq/data/data_utils.py", line 222, in batch_by_size
    'Please build Cython components with: `pip install --editable .` '

i have tried this: 
1.pip install --editable . and python setup.py build_ext --inplace in my fairseq root catalogue, no use;
2.i start python and write this code“ from fairseq.data.data_utils_fast import batch_by_size_fast ”，there is no error arised.

my enviroment:

 - fairseq Version (0.9.0):
 - PyTorch Version (1.5.0+cu101)
 - OS (Linux):
 - How you installed fairseq (source):
 - Build command you used (if compiling from source):
python generate.py $DATA_PATH \
          --tags-data $TAGS_PATH \
          --gen-subset $split \
          --task tags_translation \
          --path $CKPT_PATH/checkpoint_best.pt \
          --cpu \
          --batch-size 128 \
          --remove-bpe \
          --beam 12 \
          --lenpen 0.6 \
          > $OUTPUT_FN

 - Python version:3.6.7
 - CUDA/cuDNN version:10.1

**Comment by vxltersmxth** [comment]
same thing

`Traceback (most recent call last):
  File "./fairseq/train.py", line 11, in <module>
    cli_main()
  File "/workspace/jasper/fairseq/fairseq_cli/train.py", line 365, in cli_main
    nprocs=args.distributed_world_size,
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 194, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/workspace/jasper/fairseq/fairseq/data/data_utils.py", line 220, in batch_by_size
    from fairseq.data.data_utils_fast import batch_by_size_fast
ModuleNotFoundError: No module named 'fairseq.data.data_utils_fast'
`

**Comment by Riya-11** [comment]
Hey, I am facing a similar issue for the speech_to_text module. I get this error - `ModuleNotFoundError: No module named 'examples.speech_to_text' when trying to run`
`!python examples/speech_to_text/prep_librispeech_data.py --output-root ${LS_ROOT} --vocab-type unigram --vocab-size 10000` in colab.

I followed the following installation steps -

```
!git clone https://github.com/pytorch/fairseq
os.chdir('fairseq')
!pip install ./

```
Please let us know if you found a solution to this problem. Thanks!
