### ISSUE TITLE
OverflowError: cannot serialize a bytes object larger than 4 GiB

### ISSUE THREAD

**Issue by yuan-commits** [pytorch/fairseq#2166]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?

I am using a sentence-level corpus (about 405M sentences) to training LM following instruction [here](https://github.com/pytorch/fairseq/tree/master/examples/language_model). 

The same preprocess command and training command are used, except setting sample-break-mode to **eos**, as the dataset is sentence level and the neighborhood sentence may not in one document. However it shows OverflowError as bebow.

Question:
- how to fix the overflowerror, to training large-scale corpus on sentence level?
- does the default "eos" dataloader using bucket (putting the samples with similar length in one batch)?

#### Error log
```
   File "/opt/conda/bin/fairseq-train", line 11, in <module>
     load_entry_point('fairseq', 'console_scripts', 'fairseq-train')()
   File "/code/fairseq/fairseq_cli/train.py", line 370, in cli_main
     nprocs=args.distributed_world_size,
   File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
     while not spawn_context.join():
   File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
     raise Exception(msg)
   File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
     fn(i, *args)
   File "/code/fairseq/fairseq_cli/train.py", line 338, in distributed_main
     main(args, init_distributed=True)
   File "/code/fairseq/fairseq_cli/train.py", line 121, in main
     valid_losses = train(args, trainer, task, epoch_itr, max_update)
   File "/opt/conda/lib/python3.7/contextlib.py", line 74, in inner
     return func(*args, **kwds)
   File "/code/fairseq/fairseq_cli/train.py", line 204, in train
     for samples in progress:
   File "/code/fairseq/fairseq/logging/progress_bar.py", line 245, in __iter__
     for i, obj in enumerate(self.iterable, start=self.n):
   File "/code/fairseq/fairseq/data/iterators.py", line 58, in __iter__
     for x in self.iterable:
   File "/code/fairseq/fairseq/data/iterators.py", line 374, in _chunk_iterator
     for x in itr:
   File "/code/fairseq/fairseq/data/iterators.py", line 58, in __iter__
     for x in self.iterable:
   File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 279, in __iter__
     return _MultiProcessingDataLoaderIter(self)
   File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 719, in __init__
     w.start()
   File "/opt/conda/lib/python3.7/multiprocessing/process.py", line 112, in start
     self._popen = self._Popen(self)
   File "/opt/conda/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
     return _default_context.get_context().Process._Popen(process_obj)
   File "/opt/conda/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
     return Popen(process_obj)
   File "/opt/conda/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
     super().__init__(process_obj)
   File "/opt/conda/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
     self._launch(process_obj)
   File "/opt/conda/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
     reduction.dump(process_obj, fp)
   File "/opt/conda/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
     ForkingPickler(file, protocol).dump(obj)
  OverflowError: cannot serialize a bytes object larger than 4 GiB
```

#### Code

   
``` bash
fairseq-train --task language_modeling \
  "$DATA_DIR" \
  --save-dir "$SAVE_DIR" \
  --arch transformer_lm --share-decoder-input-output-embed \
  --dropout 0.1 \
  --optimizer adam --adam-betas '(0.9, 0.98)' --weight-decay 0.01 --clip-norm 0.0 \
  --lr 0.0005 --lr-scheduler inverse_sqrt --warmup-updates 4000 --warmup-init-lr 1e-07 \
  --tokens-per-sample 512 --sample-break-mode eos \
  --max-tokens 2048 --update-freq 4 \
  --fp16 \
  --save-interval-updates 1000 \
  --keep-interval-updates 1
```
#### What have you tried?

I also try wikitext-103 data on eos setting, and can train successfully. My training data contains 405M sentences, and the vocabulary size is 200k.

**Update:**
I also try "eos" with the same training data (405M sentences) on only 1 gpu without DPP. It works well and do not show the error.

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0) 1.4.0
 - OS (e.g., Linux): Ubuntu 16.04.6 LTS
 - How you installed fairseq (`pip`, source): 
editable mode by using:
``` bash
git clone https://github.com/pytorch/fairseq
cd fairseq
pip install --editable .
```
 - Build command you used (if compiling from source): None
 - Python version: 3.7
 - CUDA/cuDNN version: 
CUDA runtime version: 10.0.130
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
 - GPU models and configuration: V100 32G * 8
 - Any other relevant information:

**Comment by Tetratrio** [comment]
Each line in your data is treated as a sentence if I understand correctly. So if you only have a single line containing all sentences of a corpus document, that error could occur. The breakmode "eos" does not crop sentences longer than the specified size.

Thats the only reason for your error I can think of right now. Might be something else

**Comment by yuan-commits** [comment]
@Tetratrio 

Thanks for reply. But the format of train data file is "each sentence each line", which is similar with wikitext103, while removing the blank lines, each line for each sentence rather than title and article.

**Comment by myleott** [comment]
This is an artifact of PyTorch's DataLoader. We have a workaround that should apply automatically if you have pyarrow installed. Can you try `pip install pyarrow` and rerun?

**Comment by yuan-commits** [comment]
> This is an artifact of PyTorch's DataLoader, which causes large numpy arrays to be pickled. We have a workaround that should apply automatically if you have pyarrow installed. Can you try `pip install pyarrow` and rerun?
> 
> This will enable PlasmaArray and avoid pickling the numpy arrays: https://github.com/pytorch/fairseq/blob/master/fairseq/data/plasma_utils.py#L10-L16

Thank you myleott. Glad to know you have a work around and it looks cool! I will try it and update if it works. 

I also found that the error seemly to be caused from the python multiprocessing package, there are also some discussion listed as below although I haven't not try them. I think the method of myleott is better than modify the python source code.
[https://github.com/flatironinstitute/CaImAn/issues/356](https://github.com/flatironinstitute/CaImAn/issues/356)
[https://discuss.pytorch.org/t/pytorch-windows-eoferror-ran-out-of-input-when-num-workers-0/25918/15](https://discuss.pytorch.org/t/pytorch-windows-eoferror-ran-out-of-input-when-num-workers-0/25918/15)

**Comment by yuan-commits** [comment]
Hi @myleott 

It do not show the OverflowError after ```conda install pyarrow```, but show the following error. Wondering if you have any ideas about this?
```
 2020-05-22 15:34:29 | INFO | fairseq_cli.train | model transformer_lm, criterion CrossEntropyCriterion
 2020-05-22 15:34:29 | INFO | fairseq_cli.train | num. model params: 130727936 (num. trained: 130727936)
 2020-05-22 15:34:29 | INFO | fairseq.trainer | detected shared parameter: decoder.embed_tokens.weight <- decoder.output_projection.weight
 2020-05-22 15:34:29 | INFO | fairseq_cli.train | training on 8 devices (GPUs/TPUs)
 2020-05-22 15:34:29 | INFO | fairseq_cli.train | max tokens per GPU = 2048 and max sentences per GPU = None
 2020-05-22 15:34:29 | INFO | fairseq.trainer | no existing checkpoint found /mnt/output/users/yuanz/fairseq_exp/output/lm_6l_eos_base_wu_ar/checkpoint_last.pt
 2020-05-22 15:34:29 | INFO | fairseq.trainer | loading train data for epoch 1
 2020-05-22 15:36:40 | INFO | fairseq.data.data_utils | loaded 406129439 examples from: /mnt/default/users/yuanz/fairseq_exp/newdata_base/train
 WARNING: Logging before InitGoogleLogging() is written to STDERR
 E0522 15:46:15.857141    94 io.cc:168] Connection to IPC socket failed for pathname /tmp/tmpfmgr7htt, retrying 20 more times
 WARNING: Logging before InitGoogleLogging() is written to STDERR
 I0522 15:46:16.100330   463 store.cc:1149] Allowing the Plasma store to use up to 3.41149GB of memory.
 I0522 15:46:16.100394   463 store.cc:1176] Starting object store with directory /dev/shm and huge page support disabled
 E0522 15:46:17.986553    94 io.cc:168] Connection to IPC socket failed for pathname /tmp/tmp15zlnvmm, retrying 20 more times
 WARNING: Logging before InitGoogleLogging() is written to STDERR
 I0522 15:46:18.230484   508 store.cc:1149] Allowing the Plasma store to use up to 6.82297GB of memory.
 I0522 15:46:18.230547   508 store.cc:1176] Starting object store with directory /dev/shm and huge page support disabled
 E0522 15:46:20.812652    94 io.cc:168] Connection to IPC socket failed for pathname /tmp/tmphn4y37so, retrying 20 more times
 WARNING: Logging before InitGoogleLogging() is written to STDERR
 I0522 15:46:21.051435   513 store.cc:1149] Allowing the Plasma store to use up to 10.2345GB of memory.
 I0522 15:46:21.051498   513 store.cc:1176] Starting object store with directory /dev/shm and huge page support disabled
 W0522 15:46:21.051520   513 store.cc:1193] System memory request exceeds memory available in /dev/shm. The request is for 10234461862 bytes, and the amount available is 6689334067 bytes. You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you may need to pass an argument with the flag '--shm-size' to 'docker run'.
 Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fe26738b0e0>
 Traceback (most recent call last):
   File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 961, in __del__
     self._shutdown_workers()
   File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 917, in _shutdown_workers
     if not self._shutdown:
 AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute '_shutdown'
 Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7fa9e8e5f0e0>
 Traceback (most recent call last):
   File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 961, in __del__
     self._shutdown_workers()
   File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 917, in _shutdown_workers
     if not self._shutdown:
 AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute '_shutdown'
 Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7f8d440da0e0>
 Traceback (most recent call last):
   File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 961, in __del__
     self._shutdown_workers()
   File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 917, in _shutdown_workers
     if not self._shutdown:
 AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute '_shutdown'
 Exception ignored in: <function _MultiProcessingDataLoaderIter.__del__ at 0x7ffaa8bbc0e0>
 Traceback (most recent call last):
   File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 961, in __del__
     self._shutdown_workers()
   File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 917, in _shutdown_workers
     if not self._shutdown:
 AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute '_shutdown'
 I0522 15:47:52.830507   513 store.cc:732] Disconnecting client on fd 6
 I0522 15:47:52.830516   463 store.cc:732] Disconnecting client on fd 6
 I0522 15:47:52.830543   508 store.cc:732] Disconnecting client on fd 6
 WARNING: Logging before InitGoogleLogging() is written to STDERR
 E0522 15:48:46.343557    97 io.cc:168] Connection to IPC socket failed for pathname /tmp/tmpe3_r5rxg, retrying 20 more times
  WARNING: Logging before InitGoogleLogging() is written to STDERR
 I0522 15:48:46.587915   520 store.cc:1149] Allowing the Plasma store to use up to 3.41149GB of memory.
 I0522 15:48:46.587980   520 store.cc:1176] Starting object store with directory /dev/shm and huge page support disabled
 W0522 15:48:46.587999   520 store.cc:1193] System memory request exceeds memory available in /dev/shm. The request is for 3411487287 bytes, and the amount available is 25804 bytes. You may be able to free up space by deleting files in /dev/shm. If you are inside a Docker container, you may need to pass an argument with the flag '--shm-size' to 'docker run'.
 I0522 15:49:18.477819   520 store.cc:732] Disconnecting client on fd 6
 Traceback (most recent call last):
   File "/opt/conda/bin/fairseq-train", line 11, in <module>
     load_entry_point('fairseq', 'console_scripts', 'fairseq-train')()
   File "/code/fairseq/fairseq_cli/train.py", line 370, in cli_main
     nprocs=args.distributed_world_size,
   File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
     while not spawn_context.join():
   File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
     raise Exception(msg)
 Exception: 
 
 -- Process 5 terminated with the following error:
 Traceback (most recent call last):
   File "/opt/conda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
     fn(i, *args)
   File "/code/fairseq/fairseq_cli/train.py", line 338, in distributed_main
     main(args, init_distributed=True)
   File "/code/fairseq/fairseq_cli/train.py", line 121, in main
     valid_losses = train(args, trainer, task, epoch_itr, max_update)
   File "/opt/conda/lib/python3.7/contextlib.py", line 74, in inner
     return func(*args, **kwds)
   File "/code/fairseq/fairseq_cli/train.py", line 204, in train
     for samples in progress:
   File "/code/fairseq/fairseq/logging/progress_bar.py", line 245, in __iter__
     for i, obj in enumerate(self.iterable, start=self.n):
   File "/code/fairseq/fairseq/data/iterators.py", line 58, in __iter__
     for x in self.iterable:
   File "/code/fairseq/fairseq/data/iterators.py", line 374, in _chunk_iterator
     for x in itr:
   File "/code/fairseq/fairseq/data/iterators.py", line 58, in __iter__
     for x in self.iterable:
   File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 279, in __iter__
     return _MultiProcessingDataLoaderIter(self)
   File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 684, in __init__
     self._worker_result_queue = multiprocessing_context.Queue()
   File "/opt/conda/lib/python3.7/multiprocessing/context.py", line 102, in Queue
     return Queue(maxsize, ctx=self.get_context())
   File "/opt/conda/lib/python3.7/multiprocessing/queues.py", line 42, in __init__
     self._rlock = ctx.Lock()
   File "/opt/conda/lib/python3.7/multiprocessing/context.py", line 67, in Lock
     return Lock(ctx=self.get_context())
   File "/opt/conda/lib/python3.7/multiprocessing/synchronize.py", line 162, in __init__
     SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
   File "/opt/conda/lib/python3.7/multiprocessing/synchronize.py", line 59, in __init__
     unlink_now)
 OSError: [Errno 28] No space left on device
```

**Comment by myleott** [comment]
Maybe you don't have enough space in `/tmp`? Can you try setting the temporary directory to some other location which has enough storage space?

Something like:
```bash
TMPDIR=/path/to/tmp/dir fairseq-train (...)
```

**Comment by yuan-commits** [comment]
Hi @myleott 

I am wondering how much memory does pyarrow acquire in /dev/shm. In my case, it is 16G. According to [issue](https://github.com/pytorch/pytorch/issues/2244), does out-of-memory result in the failure "Exception: process 3 terminated with signal SIGBUS".

What if there is insuffient memory for /dev/shm? Can I use pyarrow in this case? Thank you!

**Comment by yuan-commits** [comment]
The problems have been solved by increase /dev/shm. If using a docker container, refer [https://docs.docker.com/engine/reference/run/](https://docs.docker.com/engine/reference/run/).

I also try to use protocol 4 for dump but doesn't work.
