### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for BARTModel  (in en-zh fine tune process)

### ISSUE THREAD

**Issue by Daisy-123** [pytorch/fairseq#2247]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
I used the mbart dictionary which in mbart.CC25.tar.gz .
But I got the size mismatch error ?
#### Code
`python train.py destdir/MixData/ --encoder-normalize-before --decoder-normalize-before  --arch mbart_large --task translation_from_pretrained_bart  --source-lang en --target-lang zh --criterion label_smoothed_cross_entropy --label-smoothing 0.2 --dataset-impl mmap --optimizer adam --adam-eps 1e-06 --adam-betas '(0.9, 0.98)' --lr-scheduler polynomial_decay --lr 3e-05 --min-lr -1 --warmup-updates 2500 --total-num-update 40000 --dropout 0.3 --attention-dropout 0.1  --weight-decay 0.0 --max-tokens 1024 --update-freq 2 --save-interval 1 --save-interval-updates 5000 --keep-interval-updates 10 --no-epoch-checkpoints --seed 222 --log-format simple --log-interval 2 --reset-optimizer --reset-meters --reset-dataloader --reset-lr-scheduler --restore-file $PRETRAIN --langs $langs --layernorm-embedding  --ddp-backend no_c10d`
   
## My Log file : ##
2020-06-17 14:57:38 | INFO | fairseq.tasks.translation | [en] dictionary: 250001 types
2020-06-17 14:57:38 | INFO | fairseq.tasks.translation | [zh] dictionary: 250001 types
2020-06-17 14:57:38 | INFO | fairseq.data.data_utils | loaded 113665 examples from: destdir/MixData/valid.en-zh.en
2020-06-17 14:57:38 | INFO | fairseq.data.data_utils | loaded 113665 examples from: destdir/MixData/valid.en-zh.zh
2020-06-17 14:57:38 | INFO | fairseq.tasks.translation | destdir/MixData/ valid en-zh 113665 examples
2020-06-17 14:57:55 | INFO | fairseq_cli.train | BARTModel(
  (encoder): TransformerEncoder(
.
.
.
.

2020-06-17 14:57:55 | INFO | fairseq_cli.train | model mbart_large, criterion LabelSmoothedCrossEntropyCriterion
2020-06-17 14:57:55 | INFO | fairseq_cli.train | num. model params: 610827264 (num. trained: 610827264)
2020-06-17 14:58:01 | INFO | fairseq.trainer | detected shared parameter: encoder.embed_tokens.weight <- decoder.embed_tokens.weight
2020-06-17 14:58:01 | INFO | fairseq.trainer | detected shared parameter: encoder.embed_tokens.weight <- decoder.output_projection.weight
2020-06-17 14:58:01 | INFO | fairseq_cli.train | training on 1 devices (GPUs/TPUs)
2020-06-17 14:58:01 | INFO | fairseq_cli.train | max tokens per GPU = 1024 and max sentences per GPU = None
Traceback (most recent call last):
  File "/home/u00icw00/fairseq/fairseq/trainer.py", line 238, in load_checkpoint
    state["model"], strict=True, args=self.args
  File "/home/u00icw00/fairseq/fairseq/models/fairseq_model.py", line 94, in load_state_dict
    return super().load_state_dict(state_dict, strict)
  File "/home/u00icw00/.conda/envs/fairseq/lib/python3.6/site-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for BARTModel:
        size mismatch for encoder.embed_tokens.weight: copying a param with shape torch.Size([250027, 1024]) from checkpoint, the shape in current model is torch.Size([250003, 1024]).
        size mismatch for decoder.embed_tokens.weight: copying a param with shape torch.Size([250027, 1024]) from checkpoint, the shape in current model is torch.Size([250003, 1024]).
        size mismatch for decoder.output_projection.weight: copying a param with shape torch.Size([250027, 1024]) from checkpoint, the shape in current model is torch.Size([250003, 1024]).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 11, in <module>
    cli_main()
  File "/home/u00icw00/fairseq/fairseq_cli/train.py", line 377, in cli_main
    main(args)
  File "/home/u00icw00/fairseq/fairseq_cli/train.py", line 104, in main
    extra_state, epoch_itr = checkpoint_utils.load_checkpoint(args, trainer)
  File "/home/u00icw00/fairseq/fairseq/checkpoint_utils.py", line 137, in load_checkpoint
    reset_meters=args.reset_meters,
  File "/home/u00icw00/fairseq/fairseq/trainer.py", line 247, in load_checkpoint
    "please ensure that the architectures match.".format(filename)
Exception: Cannot load model parameters from checkpoint examples/mbart/mbart.cc25/model.pt; please ensure that the architectures match.

#### What have you tried?
No , but it can run in cpu.
 
#### What's your environment?

 - fairseq Version : 0.9.0
 - PyTorch Version 1.5.0
 - OS : Linux
 - How you installed fairseq :  pip
 - Build command you used (if compiling from source): pip install --editable ./
 - Python version: 3.6
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration:  32G GPU 
 - Any other relevant information:

**Comment by thpun** [comment]
Did you set `$langs`?
```bash
langs=ar_AR,cs_CZ,de_DE,en_XX,es_XX,et_EE,fi_FI,fr_XX,gu_IN,hi_IN,it_IT,ja_XX,kk_KZ,ko_KR,lt_LT,lv_LV,my_MM,ne_NP,nl_XX,ro_RO,ru_RU,si_LK,tr_TR,vi_VN,zh_CN
```

I think you need to list out all 25 languages used in pretraining when using mBART.cc25, as said in the source code.
https://github.com/pytorch/fairseq/blob/fc29aab2030055585a087727d93a2083edbb1678/fairseq/tasks/translation_from_pretrained_bart.py#L41-L46

**Comment by Daisy-123** [comment]
@thpun I tried `langs=ar_AR,cs_CZ,de_DE,en_XX,es_XX,et_EE,fi_FI,fr_XX,gu_IN,hi_IN,it_IT,ja_XX,kk_KZ,ko_KR,lt_LT,lv_LV,my_MM,ne_NP,nl_XX,ro_RO,ru_RU,si_LK,tr_TR,vi_VN,zh_CN `
but still get the same error !

**Comment by thpun** [comment]
How about using `en_XX` and `zh_CN` as the source and target language id instead of just `en` and `zh`?

**Comment by krishnardt** [comment]
Hi,

Is there any solution to this issue?
I am also facing this issue currently.
I have given all the languages as suggested.
Does anyone have solution for it?

**Comment by abhirut** [comment]
Same issue.

```

Exception in device=TPU:2: Cannot load model parameters from checkpoint /home/abhirut/mbart.cc25.v2/model.pt; please ensure that the architectures match.
Traceback (most recent call last):
  File "/home/abhirut/fairseq/fairseq/trainer.py", line 496, in load_checkpoint
    state["model"], strict=True, model_cfg=self.cfg.model
  File "/home/abhirut/fairseq/fairseq/distributed/module_proxy_wrapper.py", line 52, in load_state_dict
    return self.module.module.load_state_dict(*args, **kwargs)
  File "/home/abhirut/fairseq/fairseq/models/fairseq_model.py", line 125, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/anaconda3/envs/torch-xla-1.8/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1224, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for BARTModel:
        Missing key(s) in state_dict: "decoder.output_projection.weight". 
        Unexpected key(s) in state_dict: "encoder.embed_positions.weight", "encoder.layers.6.self_attn.in_proj_weight", "encoder.layers.6.self_attn.in_proj_bias", "encoder.layers.6.self_attn.out_proj.weight", "encoder.layers.6.se
lf_attn.out_proj.bias", "encoder.layers.6.fc1.weight", "encoder.layers.6.fc1.bias", "encoder.layers.6.fc2.weight", "encoder.layers.6.fc2.bias", "encoder.layers.6.layer_norms.0.weight", "encoder.layers.6.layer_norms.0.bias", "enco
der.layers.6.layer_norms.1.weight", "encoder.layers.6.layer_norms.1.bias", "encoder.layers.7.self_attn.in_proj_weight", "encoder.layers.7.self_attn.in_proj_bias", "encoder.layers.7.self_attn.out_proj.weight", "encoder.layers.7.se
lf_attn.out_proj.bias", "encoder.layers.7.fc1.weight", "encoder.layers.7.fc1.bias", "encoder.layers.7.fc2.weight", "encoder.layers.7.fc2.bias", "encoder.layers.7.layer_norms.0.weight", "encoder.layers.7.layer_norms.0.bias", "enco
der.layers.7.layer_norms.1.weight", "encoder.layers.7.layer_norms.1.bias", "encoder.layers.8.self_attn.in_proj_weight", "encoder.layers.8.self_attn.in_proj_bias", "encoder.layers.8.self_attn.out_proj.weight", "encoder.layers.8.se
lf_attn.out_proj.bias", "encoder.layers.8.fc1.weight", "encoder.layers.8.fc1.bias", "encoder.layers.8.fc2.weight", "encoder.layers.8.fc2.bias", "encoder.layers.8.layer_norms.0.weight", "encoder.layers.8.layer_norms.0.bias", "enco
der.layers.8.layer_norms.1.weight", "encoder.layers.8.layer_norms.1.bias", "encoder.layers.9.self_attn.in_proj_weight", "encoder.layers.9.self_attn.in_proj_bias", "encoder.layers.9.self_attn.out_proj.weight", "encoder.layers.9.se
lf_attn.out_proj.bias", "encoder.layers.9.fc1.weight", "encoder.layers.9.fc1.bias", "encoder.layers.9.fc2.weight", "encoder.layers.9.fc2.bias", "encoder.layers.9.layer_norms.0.weight", "encoder.layers.9.layer_norms.0.bias", "enco
der.layers.9.layer_norms.1.weight", "encoder.layers.9.layer_norms.1.bias", "encoder.layers.10.self_attn.in_proj_weight", "encoder.layers.10.self_attn.in_proj_bias", "encoder.layers.10.self_attn.out_proj.weight", "encoder.layers.1
0.self_attn.out_proj.bias", "encoder.layers.10.fc1.weight", "encoder.layers.10.fc1.bias", "encoder.layers.10.fc2.weight", "encoder.layers.10.fc2.bias", "encoder.layers.10.layer_norms.0.weight", "encoder.layers.10.layer_norms.0.bi
as", "encoder.layers.10.layer_norms.1.weight", "encoder.layers.10.layer_norms.1.bias", "encoder.layers.11.self_attn.in_proj_weight", "encoder.layers.11.self_attn.in_proj_bias", "encoder.layers.11.self_attn.out_proj.weight", "enco
der.layers.11.self_attn.out_proj.bias", "encoder.layers.11.fc1.weight", "encoder.layers.11.fc1.bias", "encoder.layers.11.fc2.weight", "encoder.layers.11.fc2.bias", "encoder.layers.11.layer_norms.0.weight", "encoder.layers.11.laye
r_norms.0.bias", "encoder.layers.11.layer_norms.1.weight", "encoder.layers.11.layer_norms.1.bias", "decoder.embed_positions.weight", "decoder.layers.6.self_attn.in_proj_weight", "decoder.layers.6.self_attn.in_proj_bias", "decoder
.layers.6.self_attn.out_proj.weight", "decoder.layers.6.self_attn.out_proj.bias", "decoder.layers.6.self_attn_layer_norm.weight", "decoder.layers.6.self_attn_layer_norm.bias", "decoder.layers.6.encoder_attn.in_proj_weight", "deco
der.layers.6.encoder_attn.in_proj_bias", "decoder.layers.6.encoder_attn.out_proj.weight", "decoder.layers.6.encoder_attn.out_proj.bias", "decoder.layers.6.encoder_attn_layer_norm.weight", "decoder.layers.6.encoder_attn_layer_norm
.bias", "decoder.layers.6.fc1.weight", "decoder.layers.6.fc1.bias", "decoder.layers.6.fc2.weight", "decoder.layers.6.fc2.bias", "decoder.layers.6.final_layer_norm.weight", "decoder.layers.6.final_layer_norm.bias", "decoder.layers
.7.self_attn.in_proj_weight", "decoder.layers.7.self_attn.in_proj_bias", "decoder.layers.7.self_attn.out_proj.weight", "decoder.layers.7.self_attn.out_proj.bias", "decoder.layers.7.self_attn_layer_norm.weight", "decoder.layers.7.
self_attn_layer_norm.bias", "decoder.layers.7.encoder_attn.in_proj_weight", "decoder.layers.7.encoder_attn.in_proj_bias", "decoder.layers.7.encoder_attn.out_proj.weight", "decoder.layers.7.encoder_attn.out_proj.bias", "decoder.la
yers.7.encoder_attn_layer_norm.weight", "decoder.layers.7.encoder_attn_layer_norm.bias", "decoder.layers.7.fc1.weight", "decoder.layers.7.fc1.bias", "decoder.layers.7.fc2.weight", "decoder.layers.7.fc2.bias", "decoder.layers.7.fi
nal_layer_norm.weight", "decoder.layers.7.final_layer_norm.bias", "decoder.layers.8.self_attn.in_proj_weight", "decoder.layers.8.self_attn.in_proj_bias", "decoder.layers.8.self_attn.out_proj.weight", "decoder.layers.8.self_attn.o
ut_proj.bias", "decoder.layers.8.self_attn_layer_norm.weight", "decoder.layers.8.self_attn_layer_norm.bias", "decoder.layers.8.encoder_attn.in_proj_weight", "decoder.layers.8.encoder_attn.in_proj_bias", "decoder.layers.8.encoder_
attn.out_proj.weight", "decoder.layers.8.encoder_attn.out_proj.bias", "decoder.layers.8.encoder_attn_layer_norm.weight", "decoder.layers.8.encoder_attn_layer_norm.bias", "decoder.layers.8.fc1.weight", "decoder.layers.8.fc1.bias",
 "decoder.layers.8.fc2.weight", "decoder.layers.8.fc2.bias", "decoder.layers.8.final_layer_norm.weight", "decoder.layers.8.final_layer_norm.bias", "decoder.layers.9.self_attn.in_proj_weight", "decoder.layers.9.self_attn.in_proj_b
ias", "decoder.layers.9.self_attn.out_proj.weight", "decoder.layers.9.self_attn.out_proj.bias", "decoder.layers.9.self_attn_layer_norm.weight", "decoder.layers.9.self_attn_layer_norm.bias", "decoder.layers.9.encoder_attn.in_proj_
weight", "decoder.layers.9.encoder_attn.in_proj_bias", "decoder.layers.9.encoder_attn.out_proj.weight", "decoder.layers.9.encoder_attn.out_proj.bias", "decoder.layers.9.encoder_attn_layer_norm.weight", "decoder.layers.9.encoder_a
ttn_layer_norm.bias", "decoder.layers.9.fc1.weight", "decoder.layers.9.fc1.bias", "decoder.layers.9.fc2.weight", "decoder.layers.9.fc2.bias", "decoder.layers.9.final_layer_norm.weight", "decoder.layers.9.final_layer_norm.bias", "
decoder.layers.10.self_attn.in_proj_weight", "decoder.layers.10.self_attn.in_proj_bias", "decoder.layers.10.self_attn.out_proj.weight", "decoder.layers.10.self_attn.out_proj.bias", "decoder.layers.10.self_attn_layer_norm.weight",
 "decoder.layers.10.self_attn_layer_norm.bias", "decoder.layers.10.encoder_attn.in_proj_weight", "decoder.layers.10.encoder_attn.in_proj_bias", "decoder.layers.10.encoder_attn.out_proj.weight", "decoder.layers.10.encoder_attn.out
_proj.bias", "decoder.layers.10.encoder_attn_layer_norm.weight", "decoder.layers.10.encoder_attn_layer_norm.bias", "decoder.layers.10.fc1.weight", "decoder.layers.10.fc1.bias", "decoder.layers.10.fc2.weight", "decoder.layers.10.f
c2.bias", "decoder.layers.10.final_layer_norm.weight", "decoder.layers.10.final_layer_norm.bias", "decoder.layers.11.self_attn.in_proj_weight", "decoder.layers.11.self_attn.in_proj_bias", "decoder.layers.11.self_attn.out_proj.wei
ght", "decoder.layers.11.self_attn.out_proj.bias", "decoder.layers.11.self_attn_layer_norm.weight", "decoder.layers.11.self_attn_layer_norm.bias", "decoder.layers.11.encoder_attn.in_proj_weight", "decoder.layers.11.encoder_attn.i
n_proj_bias", "decoder.layers.11.encoder_attn.out_proj.weight", "decoder.layers.11.encoder_attn.out_proj.bias", "decoder.layers.11.encoder_attn_layer_norm.weight", "decoder.layers.11.encoder_attn_layer_norm.bias", "decoder.layers
.11.fc1.weight", "decoder.layers.11.fc1.bias", "decoder.layers.11.fc2.weight", "decoder.layers.11.fc2.bias", "decoder.layers.11.final_layer_norm.weight", "decoder.layers.11.final_layer_norm.bias". 
        size mismatch for encoder.embed_tokens.weight: copying a param with shape torch.Size([250027, 1024]) from checkpoint, the shape in current model is torch.Size([250027, 512]).
        size mismatch for encoder.layernorm_embedding.weight: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for encoder.layernorm_embedding.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for encoder.layers.0.self_attn.k_proj.weight: copying a param with shape torch.Size([1024, 1024]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for encoder.layers.0.self_attn.k_proj.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for encoder.layers.0.self_attn.v_proj.weight: copying a param with shape torch.Size([1024, 1024]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for encoder.layers.0.self_attn.v_proj.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for encoder.layers.0.self_attn.q_proj.weight: copying a param with shape torch.Size([1024, 1024]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for encoder.layers.0.self_attn.q_proj.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
        size mismatch for encoder.layers.0.self_attn.out_proj.weight: copying a param with shape torch.Size([1024, 1024]) from checkpoint, the shape in current model is torch.Size([512, 512]).
        size mismatch for encoder.layers.0.self_attn.out_proj.bias: copying a param with shape torch.Size([1024]) from checkpoint, the shape in current model is torch.Size([512]).
...
```
