### ISSUE TITLE
Fine-tuning Bart on QQP task gives an error

### ISSUE THREAD

**Issue by vineetk1** [pytorch/fairseq#2249]
### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd 'BART_PATH=/home/vin/.cache/torch/pytorch_fairseq/40858f8de84f479771b2807266d806749e9ad0f8cb547921c35a76ae9c3ed0f6.099ef973524a5edb31b1211569b67bcc2863bc6d00781b79bac752acf8e48991/model.pt
CUDA_VISIBLE_DEVICES=0 python3 train.py QQP-bin/    --restore-file $BART_PATH                     --max-sentences 4    --max-tokens 4400    --task sentence_prediction      --add-prev-output-tokens    --layernorm-embedding     --share-all-embeddings  --share-decoder-input-output-embed    --reset-optimizer     --reset-dataloader     --reset-meters  --required-batch-size-multiple 1    --init-token 0    --arch bart_large    --criterion sentence_prediction     --num-classes 2    --dropout 0.1 --attention-dropout 0.1       --weight-decay 0.01    --optimizer adam    --adam-betas "(0.9, 0.98)"     --adam-eps 1e-08  --clip-norm 0.0    --lr-scheduler polynomial_decay    --lr 1e-05    --total-num-update 113272    --warmup-updates 6796    --threshold-loss-scale 1    --max-epoch 10     --find-unused-parameters       --best-checkpoint-metric accuracy --maximize-best-checkpoint-metric'
2. See error
AttributeError: 'Namespace' object has no attribute 'max_positions'
    

2020-06-17 10:04:48 | INFO | fairseq_cli.train | Namespace(activation_fn='gelu', adam_betas='(0.9, 0.98)', adam_eps=1e-08, adaptive_softmax_cutoff=None, adaptive_softmax_dropout=0, add_prev_output_tokens=True, all_gather_list_size=16384, arch='bart_large', attention_dropout=0.1, best_checkpoint_metric='accuracy', bf16=False, bpe=None, broadcast_buffers=False, bucket_cap_mb=25, checkpoint_suffix='', classification_head_name='sentence_classification_head', clip_norm=0.0, cpu=False, criterion='sentence_prediction', cross_self_attention=False, curriculum=0, data='QQP-bin/', data_buffer_size=2, dataset_impl=None, ddp_backend='c10d', decoder_attention_heads=16, decoder_embed_dim=1024, decoder_embed_path=None, decoder_ffn_embed_dim=4096, decoder_input_dim=1024, decoder_layerdrop=0, decoder_layers=12, decoder_layers_to_keep=None, decoder_learned_pos=True, decoder_normalize_before=False, decoder_output_dim=1024, device_id=0, disable_validation=False, distributed_backend='nccl', distributed_init_method=None, distributed_no_spawn=False, distributed_port=-1, distributed_rank=0, distributed_world_size=1, distributed_wrapper='DDP', dropout=0.1, empty_cache_freq=0, encoder_attention_heads=16, encoder_embed_dim=1024, encoder_embed_path=None, encoder_ffn_embed_dim=4096, encoder_layerdrop=0, encoder_layers=12, encoder_layers_to_keep=None, encoder_learned_pos=True, encoder_normalize_before=False, end_learning_rate=0.0, fast_stat_sync=False, find_unused_parameters=True, fix_batches_to_gpus=False, fixed_validation_seed=None, force_anneal=None, fp16=False, fp16_init_scale=128, fp16_no_flatten_grads=False, fp16_scale_tolerance=0.0, fp16_scale_window=None, init_token=0, keep_best_checkpoints=-1, keep_interval_updates=-1, keep_last_epochs=-1, layernorm_embedding=True, localsgd_frequency=3, log_format=None, log_interval=100, lr=[1e-05], lr_scheduler='polynomial_decay', max_epoch=10, max_sentences=4, max_sentences_valid=4, max_source_positions=1024, max_target_positions=1024, max_tokens=4400, max_tokens_valid=4400, max_update=0, maximize_best_checkpoint_metric=True, memory_efficient_bf16=False, memory_efficient_fp16=False, min_loss_scale=0.0001, min_lr=-1, model_parallel_size=1, no_cross_attention=False, no_epoch_checkpoints=False, no_last_checkpoints=False, no_progress_bar=False, no_save=False, no_save_optimizer_state=False, no_scale_embedding=True, no_shuffle=False, no_token_positional_embeddings=False, nprocs_per_node=1, num_classes=2, num_workers=1, optimizer='adam', optimizer_overrides='{}', patience=-1, pooler_activation_fn='tanh', pooler_dropout=0.0, power=1.0, quant_noise_pq=0, quant_noise_pq_block_size=8, quant_noise_scalar=0, quantization_config_path=None, regression_target=False, relu_dropout=0.0, required_batch_size_multiple=1, reset_dataloader=True, reset_lr_scheduler=False, reset_meters=True, reset_optimizer=True, restore_file='/home/vin/.cache/torch/pytorch_fairseq/40858f8de84f479771b2807266d806749e9ad0f8cb547921c35a76ae9c3ed0f6.099ef973524a5edb31b1211569b67bcc2863bc6d00781b79bac752acf8e48991/model.pt', save_dir='checkpoints', save_interval=1, save_interval_updates=0, seed=1, sentence_avg=False, separator_token=None, share_all_embeddings=True, share_decoder_input_output_embed=True, shorten_data_split_whitelist='', shorten_method='none', skip_invalid_size_inputs_valid_test=False, slowmo_algorithm='LocalSGD', slowmo_momentum=None, task='sentence_prediction', tensorboard_logdir='', threshold_loss_scale=1.0, tokenizer=None, total_num_update=113272, tpu=False, train_subset='train', update_freq=[1], use_bmuf=False, use_old_adam=False, user_dir=None, valid_subset='valid', validate_interval=1, warmup_updates=6796, weight_decay=0.01)
2020-06-17 10:04:48 | INFO | fairseq.tasks.sentence_prediction | [input] dictionary: 50265 types
2020-06-17 10:04:48 | INFO | fairseq.tasks.sentence_prediction | [label] dictionary: 9 types
2020-06-17 10:04:48 | INFO | fairseq.data.data_utils | loaded 40430 examples from: QQP-bin/input0/valid
2020-06-17 10:04:48 | INFO | fairseq.data.data_utils | loaded 40430 examples from: QQP-bin/input1/valid
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    cli_main()
  File "/home/vin/fairseq/fairseq_cli/train.py", line 377, in cli_main
    main(args)
  File "/home/vin/fairseq/fairseq_cli/train.py", line 68, in main
    task.load_dataset(valid_sub_split, combine=False, epoch=1)
  File "/home/vin/fairseq/fairseq/tasks/sentence_prediction.py", line 154, in load_dataset
    self.args.max_positions,
AttributeError: 'Namespace' object has no attribute 'max_positions'

### Environment

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0): PyTorch 1.4.0
 - OS (e.g., Linux): Ubuntu 18.04.4 LTS
 - How you installed fairseq (`pip`, source): fork and clone from github
 - Build command you used (if compiling from source):
 - Python version: Python 3.6.9
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: NVIDIA Corporation GP104 [GeForce GTX 1080] (rev a1)
 - Any other relevant information:

**Comment by vineetk1** [comment]
Possible Solution in file    _fairseq/tasks/sentence_prediction.py_
Replace code in Line 1:
`self.args.max_positions`
with the following code:
`self.max_positions(),`

**Comment by vineetk1** [comment]
In the previous comment, there is a mistake. Instead of "Line 1", it should be "Line 154".
