### ISSUE TITLE
Fine-tuning Bart on QQP task gives another error

### ISSUE THREAD

**Issue by vineetk1** [pytorch/fairseq#2256]
## 🐛 Bug

After locally fixing a possible bug in Issue #2249,  there is another possible error as described below.

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd 'BART_PATH=/home/vin/.cache/torch/pytorch_fairseq/40858f8de84f479771b2807266d806749e9ad0f8cb547921c35a76ae9c3ed0f6.099ef973524a5edb31b1211569b67bcc2863bc6d00781b79bac752acf8e48991/model.pt
CUDA_VISIBLE_DEVICES=0 python3 train.py QQP-bin/    --restore-file $BART_PATH                     --max-sentences 4    --max-tokens 4400    --task sentence_prediction      --add-prev-output-tokens    --layernorm-embedding     --share-all-embeddings  --share-decoder-input-output-embed    --reset-optimizer     --reset-dataloader     --reset-meters  --required-batch-size-multiple 1    --init-token 0    --arch bart_large    --criterion sentence_prediction     --num-classes 2    --dropout 0.1 --attention-dropout 0.1       --weight-decay 0.01    --optimizer adam    --adam-betas "(0.9, 0.98)"     --adam-eps 1e-08  --clip-norm 0.0    --lr-scheduler polynomial_decay    --lr 1e-05    --total-num-update 113272    --warmup-updates 6796    --threshold-loss-scale 1    --max-epoch 10     --find-unused-parameters       --best-checkpoint-metric accuracy --maximize-best-checkpoint-metric'
2. See error
RuntimeError: received 0 items of ancdata

2020-06-20 13:25:03 | INFO | fairseq_cli.train | model bart_large, criterion SentencePredictionCriterion
2020-06-20 13:25:03 | INFO | fairseq_cli.train | num. model params: 407343106 (num. trained: 407343106)
2020-06-20 13:25:05 | INFO | fairseq.trainer | detected shared parameter: encoder.embed_tokens.weight <- decoder.embed_tokens.weight
2020-06-20 13:25:05 | INFO | fairseq.trainer | detected shared parameter: encoder.embed_tokens.weight <- decoder.output_projection.weight
2020-06-20 13:25:05 | INFO | fairseq_cli.train | training on 1 devices (GPUs/TPUs)
2020-06-20 13:25:05 | INFO | fairseq_cli.train | max tokens per GPU = 4400 and max sentences per GPU = 4
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "train.py", line 11, in <module>
    cli_main()
  File "/home/vin/fairseq/fairseq_cli/train.py", line 377, in cli_main
    main(args)
  File "/home/vin/fairseq/fairseq_cli/train.py", line 104, in main
    extra_state, epoch_itr = checkpoint_utils.load_checkpoint(args, trainer)
  File "/home/vin/fairseq/fairseq/checkpoint_utils.py", line 137, in load_checkpoint
    reset_meters=args.reset_meters,
  File "/home/vin/fairseq/fairseq/trainer.py", line 238, in load_checkpoint
    state["model"], strict=True, args=self.args
  File "/home/vin/fairseq/fairseq/models/fairseq_model.py", line 91, in load_state_dict
    self.upgrade_state_dict(state_dict)
  File "/home/vin/fairseq/fairseq/models/fairseq_model.py", line 97, in upgrade_state_dict
    self.upgrade_state_dict_named(state_dict, "")
  File "/home/vin/fairseq/fairseq/models/bart/model.py", line 229, in upgrade_state_dict_named
    logger.info('Overwriting', prefix + 'classification_heads.' + k)
Message: 'Overwriting'
Arguments: ('classification_heads.sentence_classification_head.dense.weight',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "train.py", line 11, in <module>
    cli_main()
  File "/home/vin/fairseq/fairseq_cli/train.py", line 377, in cli_main
    main(args)
  File "/home/vin/fairseq/fairseq_cli/train.py", line 104, in main
    extra_state, epoch_itr = checkpoint_utils.load_checkpoint(args, trainer)
  File "/home/vin/fairseq/fairseq/checkpoint_utils.py", line 137, in load_checkpoint
    reset_meters=args.reset_meters,
  File "/home/vin/fairseq/fairseq/trainer.py", line 238, in load_checkpoint
    state["model"], strict=True, args=self.args
  File "/home/vin/fairseq/fairseq/models/fairseq_model.py", line 91, in load_state_dict
    self.upgrade_state_dict(state_dict)
  File "/home/vin/fairseq/fairseq/models/fairseq_model.py", line 97, in upgrade_state_dict
    self.upgrade_state_dict_named(state_dict, "")
  File "/home/vin/fairseq/fairseq/models/bart/model.py", line 229, in upgrade_state_dict_named
    logger.info('Overwriting', prefix + 'classification_heads.' + k)
Message: 'Overwriting'
Arguments: ('classification_heads.sentence_classification_head.dense.bias',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "train.py", line 11, in <module>
    cli_main()
  File "/home/vin/fairseq/fairseq_cli/train.py", line 377, in cli_main
    main(args)
  File "/home/vin/fairseq/fairseq_cli/train.py", line 104, in main
    extra_state, epoch_itr = checkpoint_utils.load_checkpoint(args, trainer)
  File "/home/vin/fairseq/fairseq/checkpoint_utils.py", line 137, in load_checkpoint
    reset_meters=args.reset_meters,
  File "/home/vin/fairseq/fairseq/trainer.py", line 238, in load_checkpoint
    state["model"], strict=True, args=self.args
  File "/home/vin/fairseq/fairseq/models/fairseq_model.py", line 91, in load_state_dict
    self.upgrade_state_dict(state_dict)
  File "/home/vin/fairseq/fairseq/models/fairseq_model.py", line 97, in upgrade_state_dict
    self.upgrade_state_dict_named(state_dict, "")
  File "/home/vin/fairseq/fairseq/models/bart/model.py", line 229, in upgrade_state_dict_named
    logger.info('Overwriting', prefix + 'classification_heads.' + k)
Message: 'Overwriting'
Arguments: ('classification_heads.sentence_classification_head.out_proj.weight',)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "train.py", line 11, in <module>
    cli_main()
  File "/home/vin/fairseq/fairseq_cli/train.py", line 377, in cli_main
    main(args)
  File "/home/vin/fairseq/fairseq_cli/train.py", line 104, in main
    extra_state, epoch_itr = checkpoint_utils.load_checkpoint(args, trainer)
  File "/home/vin/fairseq/fairseq/checkpoint_utils.py", line 137, in load_checkpoint
    reset_meters=args.reset_meters,
  File "/home/vin/fairseq/fairseq/trainer.py", line 238, in load_checkpoint
    state["model"], strict=True, args=self.args
  File "/home/vin/fairseq/fairseq/models/fairseq_model.py", line 91, in load_state_dict
    self.upgrade_state_dict(state_dict)
  File "/home/vin/fairseq/fairseq/models/fairseq_model.py", line 97, in upgrade_state_dict
    self.upgrade_state_dict_named(state_dict, "")
  File "/home/vin/fairseq/fairseq/models/bart/model.py", line 229, in upgrade_state_dict_named
    logger.info('Overwriting', prefix + 'classification_heads.' + k)
Message: 'Overwriting'
Arguments: ('classification_heads.sentence_classification_head.out_proj.bias',)
2020-06-20 13:25:06 | INFO | fairseq.trainer | loaded checkpoint /home/vin/.cache/torch/pytorch_fairseq/40858f8de84f479771b2807266d806749e9ad0f8cb547921c35a76ae9c3ed0f6.099ef973524a5edb31b1211569b67bcc2863bc6d00781b79bac752acf8e48991/model.pt (epoch 41 @ 0 updates)
2020-06-20 13:25:06 | INFO | fairseq.trainer | world size changed from checkpoint: 256 -> 1
2020-06-20 13:25:07 | INFO | fairseq.trainer | loading train data for epoch 1
2020-06-20 13:25:07 | INFO | fairseq.data.data_utils | loaded 363849 examples from: QQP-bin/input0/train
2020-06-20 13:25:07 | INFO | fairseq.data.data_utils | loaded 363849 examples from: QQP-bin/input1/train
2020-06-20 13:25:07 | INFO | fairseq.data.data_utils | loaded 363849 examples from: QQP-bin/label/train
2020-06-20 13:25:07 | INFO | fairseq.tasks.sentence_prediction | Loaded train with #samples: 363849
epoch 001:   0%| | 196/90963 [00:55<7:07:17,  3.54it/s, loss=0.997, nll_loss=0.033, accuracy=52.5, wps=418.7, ups=3.51, wpb=119Traceback (most recent call last):
  File "train.py", line 11, in <module>
    cli_main()
  File "/home/vin/fairseq/fairseq_cli/train.py", line 377, in cli_main
    main(args)
  File "/home/vin/fairseq/fairseq_cli/train.py", line 120, in main
    valid_losses, should_stop = train(args, trainer, task, epoch_itr)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/vin/fairseq/fairseq_cli/train.py", line 204, in train
    for samples in progress:
  File "/home/vin/.local/lib/python3.6/site-packages/tqdm/std.py", line 1107, in __iter__
    for obj in iterable:
  File "/home/vin/fairseq/fairseq/data/iterators.py", line 60, in __iter__
    for x in self.iterable:
  File "/home/vin/fairseq/fairseq/data/iterators.py", line 420, in ichunked
    item = next(source)
  File "/home/vin/fairseq/fairseq/data/iterators.py", line 60, in __iter__
    for x in self.iterable:
  File "/home/vin/fairseq/fairseq/data/iterators.py", line 515, in __next__
    raise item
  File "/home/vin/fairseq/fairseq/data/iterators.py", line 473, in run
    for item in self._source:
  File "/home/vin/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/vin/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 841, in _next_data
    idx, data = self._get_data()
  File "/home/vin/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 808, in _get_data
    success, data = self._try_get_data()
  File "/home/vin/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 761, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/home/vin/.local/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 294, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.6/multiprocessing/resource_sharer.py", line 58, in detach
    return reduction.recv_handle(conn)
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 182, in recv_handle
    return recvfds(s, 1)[0]
  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 161, in recvfds
    len(ancdata))
RuntimeError: received 0 items of ancdata

### Environment

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0): PyTorch 1.4.0
 - OS (e.g., Linux): Ubuntu 18.04.4 LTS
 - How you installed fairseq (`pip`, source): fork and clone from github
 - Build command you used (if compiling from source):
 - Python version: Python 3.6.9
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: NVIDIA Corporation GP104 [GeForce GTX 1080] (rev a1)
 - Any other relevant information:

**Comment by claudiecakes** [comment]
I get the same error while running bart.base model. Did you get to fix it?

**Comment by vineetk1** [comment]
So far I have not figured out how to fix  this problem. I am waiting for Facebook to assign someone to fix it. This code used to work about 2 months ago.

**Comment by shamanez** [comment]
I finetuned Bart. large did not give me any error.   I think this error is associated with initializing a classification head.  Probably there is a miss-match in the checkpoint head name.

**Comment by vineetk1** [comment]
I am also using Bart Large. It used to work until I updated my repo to the latest code in the master. I also updated the Bart Large model. This is when I started seeing this error. 
How would I check if there is a miss-match in the checkpoint head name?
