### ISSUE TITLE
python generate.py encountered the error "RuntimeError: CUDA error: device-side assert triggered"

### ISSUE THREAD

**Issue by deepTransformer** [pytorch/fairseq#2286]
### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd '....'
```
python -u .//generate.py processed_convai2_none/bin --path ./models_convai2/model_bert_encoder_embedding/checkpoint9.pt --beam 6 --nbest 6 --gen-subset valid --max-sentences 196 --max-tokens 5000 --max-len-b 25 --remove-bpe ' ##' --sampling --sampling-topp 0.9 --no-repeat-ngram-size 2 --temperature 0.7
```
processed_convai2_none/bin  is the data path, checkpoint9.pt is the model I have trained
2. See error
```
/opt/conda/conda-bld/pytorch_1579027003190/work/aten/src/ATen/native/cuda/MultinomialKernel.cu:256: void at::native::<unnamed>::sampleMultinomialOnce(long *, long, int, scalar_t *, scalar_t *, int, int) [with scalar_t = float, accscalar_t = float]: block: [2,0,0], thread: [0,0,0] Assertion `sum > accZero` failed.
Traceback (most recent call last):
  File ".//generate.py", line 11, in <module>
    cli_main()
  File "/home/research/haha/research-transfer-dialouge/fairseq/fairseq_cli/generate.py", line 269, in cli_main
    main(args)
  File "/home/research/haha/research-transfer-dialouge/fairseq/fairseq_cli/generate.py", line 36, in main
    return _main(args, sys.stdout)
  File "/home/research/haha/research-transfer-dialouge/fairseq/fairseq_cli/generate.py", line 145, in _main
    hypos = task.inference_step(generator, models, sample, prefix_tokens)
  File "/home/research/haha/research-transfer-dialouge/fairseq/fairseq/tasks/fairseq_task.py", line 356, in inference_step
    return generator.generate(models, sample, prefix_tokens=prefix_tokens)
  File "/home/research/miniconda3/envs/torch1.4/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/research/haha/research-transfer-dialouge/fairseq/fairseq/sequence_generator.py", line 161, in generate
    return self._generate(sample, **kwargs)
  File "/home/research/haha/research-transfer-dialouge/fairseq/fairseq/sequence_generator.py", line 310, in _generate
    scores.view(bsz, beam_size, -1)[:, :, :step],
  File "/home/research/haha/research-transfer-dialouge/fairseq/fairseq/search.py", line 272, in step
    beams_buf = torch.arange(0, beam_size).to(indices_buf).repeat(bsz, 1)
RuntimeError: CUDA error: device-side assert triggered
```

### Expected behavior
In the `sequence_generator.py`, when the `step == max_len`, the `lprobs` will be assigned `-math.inf` expect `eos`, we wish the generator generate the `eos` token.
```
if step >= max_len:
    lprobs[:, : self.eos] = -math.inf
    lprobs[:, self.eos + 1 :] = -math.inf
```
the following code 
```python
if self.no_repeat_ngram_size > 0:
    lprobs = self._no_repeat_ngram(tokens, lprobs, bsz, beam_size, step)
```
However，sometimes all elements of `lprobs` will be assigned `-math.inf` include `eos` 
when running the code in `search.py`, I encountered the error, because all elements of `lprobs` is 0, we can't use torch.multinomial to sample
```python
indices_buf = torch.multinomial(
    probs.view(bsz * beam_size, -1),
    1,
    replacement=True,
).view(bsz, beam_size)
```

### Environment

 - fairseq Version (e.g., 0.9 or master):
 - PyTorch Version (e.g., 1.4)
 - OS (e.g., Linux): Linux 
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source):pip install --editable ./
 - Python version:3.6.10
 - CUDA/cuDNN version: 10.0
 - GPU models and configuration:
 - Any other relevant information:

**Comment by lematt1991** [comment]
You'll want to re-run with the following environment variable: `CUDA_LAUNCH_BLOCKING=1`.  This should give you a more informative error message.

**Comment by deepTransformer** [comment]
```
/opt/conda/conda-bld/pytorch_1579027003190/work/aten/src/ATen/native/cuda/MultinomialKernel.cu:256: void at::native::<unnamed>::sampleMultinomialOnce(long *, long, int, scalar_t *, scalar_t *, int, int) [with scalar_t = float, accscalar_t = float]: block: [4,0,0], thread: [0,0,0] Assertion `sum > accZero` failed.
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1579027003190/work/aten/src/THC/generic/THCTensorScatterGather.cu line=71 error=59 : device-side assert triggered
Traceback (most recent call last):
  File ".//generate.py", line 11, in <module>
    cli_main()
  File "/home/research/haha/research-transfer-dialouge/fairseq/fairseq_cli/generate.py", line 269, in cli_main
    main(args)
  File "/home/research/haha/research-transfer-dialouge/fairseq/fairseq_cli/generate.py", line 36, in main
    return _main(args, sys.stdout)
  File "/home/research/haha/research-transfer-dialouge/fairseq/fairseq_cli/generate.py", line 145, in _main
    hypos = task.inference_step(generator, models, sample, prefix_tokens)
  File "/home/research/haha/research-transfer-dialouge/fairseq/fairseq/tasks/fairseq_task.py", line 356, in inference_step
    return generator.generate(models, sample, prefix_tokens=prefix_tokens)
  File "/home/research/miniconda3/envs/torch1.4/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/research/haha/research-transfer-dialouge/fairseq/fairseq/sequence_generator.py", line 161, in generate
    return self._generate(sample, **kwargs)
  File "/home/research/haha/research-transfer-dialouge/fairseq/fairseq/sequence_generator.py", line 310, in _generate
    scores.view(bsz, beam_size, -1)[:, :, :step],
  File "/home/research/haha/research-transfer-dialouge/fairseq/fairseq/search.py", line 257, in step
    probs, dim=2, index=indices_buf.unsqueeze(-1)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1579027003190/work/aten/src/THC/generic/THCTensorScatterGather.cu:71
```

**Comment by deepTransformer** [comment]
> You'll want to re-run with the following environment variable: `CUDA_LAUNCH_BLOCKING=1`. This should give you a more informative error message.

```
/opt/conda/conda-bld/pytorch_1579027003190/work/aten/src/ATen/native/cuda/MultinomialKernel.cu:256: void at::native::<unnamed>::sampleMultinomialOnce(long *, long, int, scalar_t *, scalar_t *, int, int) [with scalar_t = float, accscalar_t = float]: block: [4,0,0], thread: [0,0,0] Assertion `sum > accZero` failed.
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1579027003190/work/aten/src/THC/generic/THCTensorScatterGather.cu line=71 error=59 : device-side assert triggered
Traceback (most recent call last):
  File ".//generate.py", line 11, in <module>
    cli_main()
  File "/home/research/haha/research-transfer-dialouge/fairseq/fairseq_cli/generate.py", line 269, in cli_main
    main(args)
  File "/home/research/haha/research-transfer-dialouge/fairseq/fairseq_cli/generate.py", line 36, in main
    return _main(args, sys.stdout)
  File "/home/research/haha/research-transfer-dialouge/fairseq/fairseq_cli/generate.py", line 145, in _main
    hypos = task.inference_step(generator, models, sample, prefix_tokens)
  File "/home/research/haha/research-transfer-dialouge/fairseq/fairseq/tasks/fairseq_task.py", line 356, in inference_step
    return generator.generate(models, sample, prefix_tokens=prefix_tokens)
  File "/home/research/miniconda3/envs/torch1.4/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/research/haha/research-transfer-dialouge/fairseq/fairseq/sequence_generator.py", line 161, in generate
    return self._generate(sample, **kwargs)
  File "/home/research/haha/research-transfer-dialouge/fairseq/fairseq/sequence_generator.py", line 310, in _generate
    scores.view(bsz, beam_size, -1)[:, :, :step],
  File "/home/research/haha/research-transfer-dialouge/fairseq/fairseq/search.py", line 257, in step
    probs, dim=2, index=indices_buf.unsqueeze(-1)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1579027003190/work/aten/src/THC/generic/THCTensorScatterGather.cu:71
```

**Comment by hyunwoongko** [comment]
I have same error.

invalid multinomial distribution (sum of probabilities <= 0)

**Comment by thinkwee** [comment]
have the same problem

**Comment by ryonakamura** [comment]
Is there any way to avoid this?
For example, by adding some kind of modification to the logits before softmax.

**Comment by ryonakamura** [comment]
This problem can be solved by assigning `1` to the eos element in `fairseq/sequence_generator.py`.

Before:

```python
# handle max length constraint
if step >= max_len:
    lprobs[:, : self.eos] = -math.inf
    lprobs[:, self.eos + 1 :] = -math.inf
```

After:

```python
# handle max length constraint
if step >= max_len:
    lprobs[:, : self.eos] = -math.inf
    lprobs[:, self.eos + 1 :] = -math.inf
    lprobs[:, self.eos] = 1
```

**Comment by Niuyuhang03** [comment]
Have the same problem. Is there any solution that don't have to modify the source code of fairseq/sequence_generator.py?
