### ISSUE TITLE
Gpu trained model not loading on cpu.

### ISSUE THREAD

**Issue by GandharvSikri** [pytorch/fairseq#2306]
#### What is your question?
I am trying to load a gpu trained model on a cpu(linux environment), but below error trace is produced.
Please suggest some method to successfully load gpu trained pytorch(fairseq model) on cpu.

#### Code
$ python Filetrans.py -src='en' -file='./Input_eng.txt'
2020-07-07 01:04:01.598612: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2020-07-07 01:04:01.598937: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2020-07-07 01:04:01.598952: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2020-07-07 01:04:02 | INFO | fairseq_cli.preprocess | Namespace(align_suffix='align', alignfile=None, all_gather_list_size=16384, bf16=False, bpe='subword_nmt', checkpoint_suffix='', cpu=True, criterion='cross_entropy', dataset_impl='mmap', destdir='data-bin_en/', empty_cache_freq=0, fp16=False, fp16_init_scale=128, fp16_no_flatten_grads=False, fp16_scale_tolerance=0.0, fp16_scale_window=None, joined_dictionary=False, log_format=None, log_interval=100, lr_scheduler='fixed', memory_efficient_bf16=False, memory_efficient_fp16=False, min_loss_scale=0.0001, model_parallel_size=1, no_progress_bar=False, nwordssrc=-1, nwordstgt=-1, only_source=False, optimizer='nag', padding_factor=8, profile=False, quantization_config_path=None, seed=1, source_lang='en', srcdict='data-bin_en/dict.en.txt', target_lang='es', task='translation', tensorboard_logdir='', testpref='data-bin_en/test', tgtdict='data-bin_en/dict.es.txt', threshold_loss_scale=None, thresholdsrc=0, thresholdtgt=0, tokenizer='moses', tpu=False, trainpref=None, user_dir=None, validpref=None, workers=64)
2020-07-07 01:04:02 | INFO | fairseq_cli.preprocess | [en] Dictionary: 34552 types
2020-07-07 01:04:03 | INFO | fairseq_cli.preprocess | [en] data-bin_en/test.en: 58 sents, 1116 tokens, 0.0% replaced by <unk>
2020-07-07 01:04:03 | INFO | fairseq_cli.preprocess | [es] Dictionary: 34920 types
2020-07-07 01:04:04 | INFO | fairseq_cli.preprocess | [es] data-bin_en/test.es: 58 sents, 1116 tokens, 40.8% replaced by <unk>
2020-07-07 01:04:04 | INFO | fairseq_cli.preprocess | Wrote preprocessed data to data-bin_en/
2020-07-07 01:04:06.914191: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory
2020-07-07 01:04:06.914271: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory
2020-07-07 01:04:06.914282: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "generate.py", line 274, in <module>
    cli_main()
  File "generate.py", line 270, in cli_main
    main(args)
  File "generate.py", line 36, in main
    return _main(args, sys.stdout)
  File "generate.py", line 73, in _main
    suffix=getattr(args, "checkpoint_suffix", ""),
  File "/flucast/fairseq/fairseq/checkpoint_utils.py", line 190, in load_model_ensemble
    filenames, arg_overrides, task, strict, suffix,
  File "/flucast/fairseq/fairseq/checkpoint_utils.py", line 203, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/flucast/fairseq/fairseq/checkpoint_utils.py", line 169, in load_checkpoint_to_cpu
    f, map_location=lambda s, l: default_restore_location(s, "cpu")
  File "/flucast/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/flucast/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 763, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
MemoryError

#### What have you tried?
Tried below parameters :
--cpu \
--distributed-world-size 0 \
> loading gpu model with command : 
model = torch.load(m, map_location=torch.device("cpu"))
torch.save(model,dpath + "data-bin/newmodel.pt")

#### What's your environment?
 - fairseq Version (e.g., 1.0 or master): 0.9.0
 - PyTorch Version: 1.5.1
 - OS : Linux
 - How you installed fairseq (`pip`, source): Pip
 - Build command you used (if compiling from source):
 - Python version: 3.7.6
 - CUDA/cuDNN version: V10.0.130(For GPU training)
 - GPU models and configuration: 4GPU Nvidia 
 - Any other relevant information:

**Comment by GandharvSikri** [comment]
Below is the bash script used in above command : 
# Apply Preprocessing to test data to generate dict index files
python preprocess.py \
  --source-lang en \
  --target-lang es \
  --tokenizer moses \
  --bpe subword_nmt \
  --cpu \
  --srcdict data-bin_en/dict.en.txt \
  --tgtdict data-bin_en/dict.es.txt \
  --testpref data-bin_en/test \
  --destdir  data-bin_en/ \
  --align-suffix align \
  --workers 64

# Apply trained model to generate result in Results.log
python generate.py > data-bin_en/Results.log \
  ./data-bin_en/ \
  --path ./data-bin_en/E_to_S.pt \
  --gen-subset test \
  --cpu \
  --remove-bpe

**Comment by GandharvSikri** [comment]
Issue resolved with below changes in bash script : 

-# Apply Preprocessing to test data to generate dict index files
python preprocess.py \
  --source-lang en \
  --target-lang es \
  --tokenizer moses \
  --bpe subword_nmt \
  --cpu \
  --srcdict data-bin_en/dict.en.txt \
  --tgtdict data-bin_en/dict.es.txt \
  --testpref data-bin_en/test \
  --destdir  data-bin_en/ \
  --align-suffix align \
  --workers 7 

-# Apply trained model to generate result in Results.log
python generate.py > data-bin_en/Results.log \
  ./data-bin_en/ \
  --path ./data-bin_en/E_to_S.pt \
  --gen-subset test \
  --cpu \
  --distributed-world-size 1 \
  --remove-bpe


Also while moving file from gpu machine to cpu machine use tar command to archive and extract file : 
tar -czvf name-of-archive.tar.gz /path/to/directory-or-file
tar -zxvf archive.tar.gz
