### ISSUE TITLE
AssertionError: sentence at index 454 of size 518 exceeds max_tokens limit of 512!

### ISSUE THREAD

**Issue by thpun** [pytorch/fairseq#2318]
#### What is your question?

Similar to #2063 , doing mBART multilingual denoising pretraining. Encountered this error:
```
-- Process 12 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/workspace/fairseq/fairseq_cli/train.py", line 354, in distributed_main
    args, init_distributed=True, after_distributed_init_fn=after_distributed_init_fn
  File "/workspace/fairseq/fairseq_cli/train.py", line 135, in main
    valid_losses, should_stop = train(args, trainer, task, epoch_itr)
  File "/opt/conda/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/workspace/fairseq/fairseq_cli/train.py", line 242, in train
    args, trainer, task, epoch_itr, valid_subsets, end_of_epoch
  File "/workspace/fairseq/fairseq_cli/train.py", line 271, in validate_and_save
    valid_losses = validate(args, trainer, task, epoch_itr, valid_subsets)
  File "/workspace/fairseq/fairseq_cli/train.py", line 302, in validate
    itr = trainer.get_valid_iterator(subset).next_epoch_itr(shuffle=False)
  File "/workspace/fairseq/fairseq/trainer.py", line 361, in get_valid_iterator
    num_workers=self.args.num_workers
  File "/workspace/fairseq/fairseq/tasks/fairseq_task.py", line 180, in get_batch_iterator
    required_batch_size_multiple=required_batch_size_multiple,
  File "/workspace/fairseq/fairseq/data/fairseq_dataset.py", line 122, in batch_by_size
    fixed_shapes=fixed_shapes,
  File "/workspace/fairseq/fairseq/data/data_utils.py", line 245, in batch_by_size
    indices, num_tokens_fn, max_tokens, max_sentences, bsz_mult,
  File "fairseq/data/data_utils_fast.pyx", line 27, in fairseq.data.data_utils_fast.batch_by_size_fast
  File "fairseq/data/data_utils_fast.pyx", line 50, in fairseq.data.data_utils_fast.batch_by_size_fast
AssertionError: sentence at index 454 of size 518 exceeds max_tokens limit of 512!
```

#### What have you tried?
Tried adding `--skip-invalid-size-inputs-valid-test` to the command but the issue persists.

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): master, commit 5d88d379cab13c8351b39341306d7a30a2a8acb8
 - PyTorch Version (e.g., 1.0) `1.5.0a0+8f84ded`
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): source 
 - Build command you used (if compiling from source): `pip install --editable ./`
 - Python version: `Python 3.6.9`
 - CUDA/cuDNN version: CUDA 10.2
 - GPU models and configuration: 8x V100 32GB
 - Any other relevant information:
Running in Nvidia docker `nvcr.io/nvidia/pytorch:20.03-py3`, APEX & PyArrow are preinstalled in the image.

**Comment by myleott** [comment]
Probably you have an input example with too long of a length.

We should add a `--shorten-method=truncate` option similar to this: https://github.com/pytorch/fairseq/blob/master/fairseq/tasks/masked_lm.py#L62-L64

Until then, you can set `--sample-break-mode=none`, which will train on blocks of 512 tokens.
