### ISSUE TITLE
TensorboardX not working in multi-GPU training

### ISSUE THREAD

**Issue by lorelupo** [pytorch/fairseq#2357]
## 🐛 Bug

When training a model on multiple-GPUs and logging with tensorboardX, the multiprocess throw an EOFerror at the end of the training.

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd
```
fairseq-train $data_dir \
    --task translation \
    --optimizer adam --lr-scheduler inverse_sqrt --lr 1e-4 \
    --warmup-init-lr 1e-7 --warmup-updates 4000\
    --max-epoch 2 \
    --max-tokens 1000 \
    --max-source-positions 1000 \
    --max-target-positions 1000 \
    --arch transformer \
    -- --tensorboard-logdir $tb_logdir
```
2. See error

```
2020-07-21 12:02:23 | INFO | fairseq_cli.train | done training in 9.2 seconds
Exception in thread Thread-3:
Exception in thread Thread-4:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/getalp/lupol/anaconda3/envs/fairenv/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/home/getalp/lupol/anaconda3/envs/fairenv/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/getalp/lupol/anaconda3/envs/fairenv/lib/python3.8/site-packages/tensorboardX/event_file_writer.py", line 202, in run
    self.run()
  File "/home/getalp/lupol/anaconda3/envs/fairenv/lib/python3.8/site-packages/tensorboardX/event_file_writer.py", line 202, in run
    data = self._queue.get(True, queue_wait_duration)
  File "/home/getalp/lupol/anaconda3/envs/fairenv/lib/python3.8/multiprocessing/queues.py", line 111, in get
    data = self._queue.get(True, queue_wait_duration)
  File "/home/getalp/lupol/anaconda3/envs/fairenv/lib/python3.8/multiprocessing/queues.py", line 111, in get
    res = self._recv_bytes()
  File "/home/getalp/lupol/anaconda3/envs/fairenv/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    res = self._recv_bytes()
  File "/home/getalp/lupol/anaconda3/envs/fairenv/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/getalp/lupol/anaconda3/envs/fairenv/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/getalp/lupol/anaconda3/envs/fairenv/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/home/getalp/lupol/anaconda3/envs/fairenv/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    buf = self._recv(4)
  File "/home/getalp/lupol/anaconda3/envs/fairenv/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
    raise EOFError
EOFError
```

### Expected behavior

TensorboardX writes logs without errors.

### Environment

I set up my conda environment as follow:

```
conda create --name fairenv python=3.8
conda activate fairenv
conda  install pytorch torchvision cudatoolkit=10.1 -c pytorch
cd anaconda3/envs/fairenv/lib/python3.8/site-packages/
git clone https://github.com/pytorch/fairseq.git
cd fairseq
pip install --editable .
conda install -c conda-forge tensorboardx
```
`cat /usr/local/cuda/version.txt` -> CUDA Version 8.0.61 

I encountered the same problem running on different types of GPUs.

**Comment by FaridDelgadoTR** [comment]
Getting the same error here.

I am running the training in a 8-GPU instance type and getting the error - using the same training data in a single GPU instance doesn't raise the exception.

**Comment by linzhk** [comment]
I think this is because you use tensorboardX in the process but fail to close before process destoryed.The EventFileWriter are waiting data to read or the connection object is closed, so it raise the EOF Error.See the [multiprocessing doc](https://docs.python.org/zh-cn/3/library/multiprocessing.html)

```python3
mp.spawn(main, nprocs=args.gpus, args=(args,)) 
def main(args):
    writer = SummaryWriter(args.save_record_dir+'/log/SummaryWriter/', comment=args.save_model)
    # here is your code
    writer.close() # maybe you miss this one
```
