### ISSUE TITLE
[Distributed training] when I restart my worker node, it crashes.  

### ISSUE THREAD

**Issue by xx-zhou16** [pytorch/fairseq#2386]
### Before asking:   
I try to search for a similar issue but cannot find one.  
If there is any, please just drop me a link.   

#### What is your question?

I run distributed training across two machines. Each machine is with 4 GPUs (V100).   
When I restart my worker node program, it crashes as the following.   
```
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal per
formance in your application as needed.
*****************************************
2020-07-28 07:40:23 | INFO | fairseq.distributed_utils | distributed init (rank 5): env://
2020-07-28 07:40:23 | INFO | fairseq.distributed_utils | initialized host 5b1a1be8c7a14bc9aa7a607f04a78f16000007 as rank 5
2020-07-28 07:40:23 | INFO | fairseq.distributed_utils | distributed init (rank 4): env://
2020-07-28 07:40:23 | INFO | fairseq.distributed_utils | initialized host 5b1a1be8c7a14bc9aa7a607f04a78f16000007 as rank 4
2020-07-28 07:40:23 | INFO | fairseq.distributed_utils | distributed init (rank 6): env://
2020-07-28 07:40:23 | INFO | fairseq.distributed_utils | distributed init (rank 7): env://
2020-07-28 07:40:23 | INFO | fairseq.distributed_utils | initialized host 5b1a1be8c7a14bc9aa7a607f04a78f16000007 as rank 6
2020-07-28 07:40:23 | INFO | fairseq.distributed_utils | initialized host 5b1a1be8c7a14bc9aa7a607f04a78f16000007 as rank 7
Traceback (most recent call last):
  File "/home/msrauser/anaconda3/envs/fairseq-py36-torch14/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/home/msrauser/xiangxin/project/fairseq/fairseq_cli/train.py", line 366, in cli_main
    cli_main_helper(args)
  File "/home/msrauser/xiangxin/project/fairseq/fairseq_cli/train.py", line 384, in cli_main_helper
    distributed_main(args.device_id, args)
  File "/home/msrauser/xiangxin/project/fairseq/fairseq_cli/train.py", line 354, in distributed_main
    args, init_distributed=True, after_distributed_init_fn=after_distributed_init_fn
  File "/home/msrauser/xiangxin/project/fairseq/fairseq_cli/train.py", line 63, in main
    args.distributed_rank = distributed_utils.distributed_init(args)
  File "/home/msrauser/xiangxin/project/fairseq/fairseq/distributed_utils.py", line 99, in distributed_init
    dist.all_reduce(torch.zeros(1).cuda())
  File "/home/msrauser/anaconda3/envs/fairseq-py36-torch14/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 902, in all_reduce
    work = _default_pg.allreduce([tensor], opts)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1579022034529/work/torch/lib/c10d/ProcessGroupNCCL.cpp:410, unhandled system error, NCCL version 2.4.8
Traceback (most recent call last):
  File "/home/msrauser/anaconda3/envs/fairseq-py36-torch14/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/home/msrauser/xiangxin/project/fairseq/fairseq_cli/train.py", line 366, in cli_main
    cli_main_helper(args)
  File "/home/msrauser/xiangxin/project/fairseq/fairseq_cli/train.py", line 384, in cli_main_helper
    distributed_main(args.device_id, args)
  File "/home/msrauser/xiangxin/project/fairseq/fairseq_cli/train.py", line 354, in distributed_main
    args, init_distributed=True, after_distributed_init_fn=after_distributed_init_fn
  File "/home/msrauser/xiangxin/project/fairseq/fairseq_cli/train.py", line 63, in main
    args.distributed_rank = distributed_utils.distributed_init(args)
  File "/home/msrauser/xiangxin/project/fairseq/fairseq/distributed_utils.py", line 99, in distributed_init
    dist.all_reduce(torch.zeros(1).cuda())
  File "/home/msrauser/anaconda3/envs/fairseq-py36-torch14/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 902, in all_reduce
    work = _default_pg.allreduce([tensor], opts)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1579022034529/work/torch/lib/c10d/ProcessGroupNCCL.cpp:410, unhandled system error, NCCL version 2.4.8
Traceback (most recent call last):
  File "/home/msrauser/anaconda3/envs/fairseq-py36-torch14/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/home/msrauser/xiangxin/project/fairseq/fairseq_cli/train.py", line 366, in cli_main
    cli_main_helper(args)
  File "/home/msrauser/xiangxin/project/fairseq/fairseq_cli/train.py", line 384, in cli_main_helper
    distributed_main(args.device_id, args)
  File "/home/msrauser/xiangxin/project/fairseq/fairseq_cli/train.py", line 354, in distributed_main
    args, init_distributed=True, after_distributed_init_fn=after_distributed_init_fn
  File "/home/msrauser/xiangxin/project/fairseq/fairseq_cli/train.py", line 63, in main
    args.distributed_rank = distributed_utils.distributed_init(args)
  File "/home/msrauser/xiangxin/project/fairseq/fairseq/distributed_utils.py", line 99, in distributed_init
    dist.all_reduce(torch.zeros(1).cuda())
  File "/home/msrauser/anaconda3/envs/fairseq-py36-torch14/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 902, in all_reduce
    work = _default_pg.allreduce([tensor], opts)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1579022034529/work/torch/lib/c10d/ProcessGroupNCCL.cpp:410, unhandled system error, NCCL version 2.4.8
Traceback (most recent call last):
  File "/home/msrauser/anaconda3/envs/fairseq-py36-torch14/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/home/msrauser/xiangxin/project/fairseq/fairseq_cli/train.py", line 366, in cli_main
    cli_main_helper(args)
  File "/home/msrauser/xiangxin/project/fairseq/fairseq_cli/train.py", line 384, in cli_main_helper
    distributed_main(args.device_id, args)
  File "/home/msrauser/xiangxin/project/fairseq/fairseq_cli/train.py", line 354, in distributed_main
    args, init_distributed=True, after_distributed_init_fn=after_distributed_init_fn
  File "/home/msrauser/xiangxin/project/fairseq/fairseq_cli/train.py", line 63, in main
    args.distributed_rank = distributed_utils.distributed_init(args)
  File "/home/msrauser/xiangxin/project/fairseq/fairseq/distributed_utils.py", line 99, in distributed_init
    dist.all_reduce(torch.zeros(1).cuda())
  File "/home/msrauser/anaconda3/envs/fairseq-py36-torch14/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 902, in all_reduce
    work = _default_pg.allreduce([tensor], opts)
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1579022034529/work/torch/lib/c10d/ProcessGroupNCCL.cpp:410, unhandled system error, NCCL version 2.4.8
Traceback (most recent call last):
  File "/home/msrauser/anaconda3/envs/fairseq-py36-torch14/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/msrauser/anaconda3/envs/fairseq-py36-torch14/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/msrauser/anaconda3/envs/fairseq-py36-torch14/lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/msrauser/anaconda3/envs/fairseq-py36-torch14/lib/python3.6/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/msrauser/anaconda3/envs/fairseq-py36-torch14/bin/python', '-u', '/home/msrauser/anaconda3/envs/fairseq-py36-torch14/bin/f
airseq-train', '--local_rank=3', '/mnt/distributed/bin', '--task', 'language_modeling', '--share-decoder-input-output-embed', '--arch', '
transformer_lm', '--clip-norm', '0.0', '--lr-scheduler', 'inverse_sqrt', '--warmup-init-lr', '1e-07', '--warmup-updates', '8000', '--optimizer', 'adam', '--adam-betas',
'(0.9, 0.98)', '--decoder-layers', '3', '--decoder-embed-dim', '1024', '--decoder-ffn-embed-dim', '4096', '--decoder-attention-heads', '16', '--lr', '0.0007', '--min-lr'
, '1e-09', '--weight-decay', '0.0', '--criterion', 'cross_entropy', '--dropout', '0.0', '--save-dir', '/mnt/distributed/checkpoints/trans
former_lm/1blm-3L-1024ED-4096FD-16H-shared-lr0.0007-SEED1-DROPOUT0.0-CRITERIONcross_entropy', '--max-epoch', '200', '--max-tokens', '8000', '--update-
freq', '8', '--no-progress-bar', '--seed', '1', '--sample-break-mode', 'eos', '--num-workers', '20', '--tensorboard-logdir', '/mnt/distributed/sampling-di
still/checkpoints/transformer_lm/1blm-3L-1024ED-4096FD-16H-shared-lr0.0007-SEED1-DROPOUT0.0-CRITERIONcross_entropy', '--distributed-backend', 'nccl',
'--distributed-no-spawn']' returned non-zero exit status 1.

```

#### Code

My training script is as the following: 
```
MASTER_IP="127.0.0.1"
MASTER_PORT=1234
TOTAL_NODES_NUM=2
NODE_RANK=$1

DATA_DIR=/mnt/distributed/bin

arch=transformer_lm
seed=1
lr=0.0007
decoder_layers=3
decoder_embed_dim=1024
decoder_ffn_embed_dim=4096
decoder_attention_heads=16
dropout=0.0
criterion=cross_entropy
label_smoothing=0.0

SAVE_DIR=/mnt/distributed/checkpoints/${arch}/1blm-${decoder_layers}L-${decoder_embed_dim}ED-${decoder_ffn_embed_dim}FD-${decoder_attention_heads}H-shared-lr${lr}-SEED${seed}-DROPOUT${dropout}-CRITERION${criterion}

RESTORE_FILE=/mnt/distributed/restore-checkpoint/checkpoint23.pt

RESTORE_FILE=/mnt/distributed-xiangxin-${SERVER_PORT}/sampling-distill/restore-checkpoint/checkpoint23.pt
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 \
    --nnodes=${TOTAL_NODES_NUM} --node_rank=${NODE_RANK} --master_addr=${MASTER_IP} \
    --master_port=${MASTER_PORT} \
    $(which fairseq-train) ${DATA_DIR} \
    --task language_modeling \
    --share-decoder-input-output-embed \
    --arch ${arch} \
    --clip-norm 0.0 --lr-scheduler inverse_sqrt --warmup-init-lr 1e-07 --warmup-updates 8000 \
    --optimizer adam --adam-betas '(0.9, 0.98)' \
    --decoder-layers ${decoder_layers} \
    --decoder-embed-dim ${decoder_embed_dim} \
    --decoder-ffn-embed-dim ${decoder_ffn_embed_dim} \
    --decoder-attention-heads ${decoder_attention_heads} \
    --lr ${lr} --min-lr 1e-09 --weight-decay 0.0 \
    --criterion ${criterion} --dropout ${dropout} \
    --save-dir ${SAVE_DIR} \
    --max-epoch 200 --max-tokens 8000 --update-freq 8 \
    --no-progress-bar --seed ${seed} \
    --sample-break-mode eos \
    --num-workers 20 \
    --tensorboard-logdir ${SAVE_DIR} \
    --distributed-backend nccl \
    --distributed-no-spawn \
```
   

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by myleott** [comment]
I wasn't able to reproduce this. Can you confirm this is still an issue on the latest version of fairseq? Also, I don't think you need to set `--distributed-no-spawn` explicitly.
