### ISSUE TITLE
load lightconv.glu.wmt17.zh-en fail  with TypeError: expected str, bytes or os.PathLike object, not NoneType?

### ISSUE THREAD

**Issue by jingmouren** [pytorch/fairseq#2398]
I try
zh2en = torch.hub.load('pytorch/fairseq', 'lightconv.glu.wmt17.zh-en', tokenizer='moses', bpe='subword_nmt')
as  in  https://github.com/pytorch/fairseq/tree/master/examples/pay_less_attention_paper/pay_less_attention_paper/README.md

and get error

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jingmouren/miniconda3/lib/python3.7/site-packages/torch/hub.py", line 369, in load
    model = entry(*args, **kwargs)
  File "/home/jingmouren/.cache/torch/hub/pytorch_fairseq_master/fairseq/models/fairseq_model.py", line 255, in from_pretrained
    **kwargs,
  File "/home/jingmouren/.cache/torch/hub/pytorch_fairseq_master/fairseq/hub_utils.py", line 56, in from_pretrained
    kwargs['data'] = os.path.abspath(os.path.join(model_path, data_name_or_path))
  File "/home/jingmouren/miniconda3/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

How to fix the problem?

**Comment by XChuanLee** [comment]
Excuse me, have you solved the probliem? I met it, too...

**Comment by VikasRajashekar** [comment]
What is the solution for this?
