### ISSUE TITLE
Layerdrop related question: couldn't load pruned model from RobertaModel.from_pretrained

### ISSUE THREAD

**Issue by qjin2016** [pytorch/fairseq#2507]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
Hi there,

I finetuned a roberta with layerdrop on WSC dataset by following this tutorial with a bit of change: https://github.com/pytorch/fairseq/tree/master/examples/roberta/wsc#roberta-training-on-winogrande-dataset . But the pruned model couldn't be loaded. Any suggestion would be appreciated!

### script for finetuning
```bash
TOTAL_NUM_UPDATES=2000  # Total number of training steps.
WARMUP_UPDATES=250      # Linearly increase LR over this many steps.
LR=2e-05                # Peak LR for polynomial LR scheduler.
MAX_SENTENCES=16        # Batch size per GPU.
SEED=1                  # Random seed.
ROBERTA_PATH=/export/home/fairseq/models/roberta.base/model.pt

# we use the --user-dir option to load the task and criterion
# from the examples/roberta/wsc directory:
FAIRSEQ_PATH=/export/home/fairseq
FAIRSEQ_USER_DIR=${FAIRSEQ_PATH}/examples/roberta/wsc

CUDA_VISIBLE_DEVICES=0 fairseq-train /export/home/data/WSC/ \
    --reset-optimizer --reset-dataloader --reset-meters \
    --no-epoch-checkpoints --no-last-checkpoints --no-save-optimizer-state \
    --best-checkpoint-metric accuracy --maximize-best-checkpoint-metric \
    --valid-subset val \
    --fp16 --ddp-backend no_c10d \
    --user-dir $FAIRSEQ_USER_DIR \
    --task wsc --criterion wsc --wsc-cross-entropy \
    --arch roberta_base --bpe gpt2 --max-positions 512 \
    --dropout 0.1 --attention-dropout 0.1 --weight-decay 0.01 \
    --optimizer adam --adam-betas '(0.9, 0.98)' --adam-eps 1e-06 \
    --lr-scheduler polynomial_decay --lr $LR \
    --warmup-updates $WARMUP_UPDATES --total-num-update $TOTAL_NUM_UPDATES \
    --max-sentences $MAX_SENTENCES \
    --max-update $TOTAL_NUM_UPDATES \
    --log-format simple --log-interval 200 \
    --seed $SEED \
    --encoder-layerdrop 0.2 \
    --encoder-layers-to-keep 0,2,4,6,8,10,12,14
```

### error message 
```
>>> roberta = RobertaModel.from_pretrained('/export/home/fairseq/models/checkpoints', 'checkpoint_best.pt', '/export/home/data/WSC/')
| dictionary: 50265 types



Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/export/home/fairseq/fairseq/models/roberta/model.py", line 169, in from_pretrained
    **kwargs,
  File "/export/home/fairseq/fairseq/hub_utils.py", line 73, in from_pretrained
    arg_overrides=kwargs,
  File "/export/home/fairseq/fairseq/checkpoint_utils.py", line 242, in load_model_ensemble_and_task
    model.load_state_dict(state["model"], strict=strict, args=args)
  File "/export/home/fairseq/fairseq/models/fairseq_model.py", line 93, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/anaconda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for RobertaModel:
	Missing key(s) in state_dict: "encoder.sentence_encoder.layers.4.self_attn.k_proj.weight", "encoder.sentence_encoder.layers.4.self_attn.k_proj.bias", "encoder.sentence_encoder.layers.4.self_attn.v_proj.weight", "encoder.sentence_encoder.layers.4.self_attn.v_proj.bias", "encoder.sentence_encoder.layers.4.self_attn.q_proj.weight", "encoder.sentence_encoder.layers.4.self_attn.q_proj.bias", "encoder.sentence_encoder.layers.4.self_attn.out_proj.weight", "encoder.sentence_encoder.layers.4.self_attn.out_proj.bias", "encoder.sentence_encoder.layers.4.self_attn_layer_norm.weight", "encoder.sentence_encoder.layers.4.self_attn_layer_norm.bias", "encoder.sentence_encoder.layers.4.fc1.weight", "encoder.sentence_encoder.layers.4.fc1.bias", "encoder.sentence_encoder.layers.4.fc2.weight", "encoder.sentence_encoder.layers.4.fc2.bias", "encoder.sentence_encoder.layers.4.final_layer_norm.weight", "encoder.sentence_encoder.layers.4.final_layer_norm.bias", "encoder.sentence_encoder.layers.5.self_attn.k_proj.weight", "encoder.sentence_encoder.layers.5.self_attn.k_proj.bias", "encoder.sentence_encoder.layers.5.self_attn.v_proj.weight", "encoder.sentence_encoder.layers.5.self_attn.v_proj.bias", "encoder.sentence_encoder.layers.5.self_attn.q_proj.weight", "encoder.sentence_encoder.layers.5.self_attn.q_proj.bias", "encoder.sentence_encoder.layers.5.self_attn.out_proj.weight", "encoder.sentence_encoder.layers.5.self_attn.out_proj.bias", "encoder.sentence_encoder.layers.5.self_attn_layer_norm.weight", "encoder.sentence_encoder.layers.5.self_attn_layer_norm.bias", "encoder.sentence_encoder.layers.5.fc1.weight", "encoder.sentence_encoder.layers.5.fc1.bias", "encoder.sentence_encoder.layers.5.fc2.weight", "encoder.sentence_encoder.layers.5.fc2.bias", "encoder.sentence_encoder.layers.5.final_layer_norm.weight", "encoder.sentence_encoder.layers.5.final_layer_norm.bias", "encoder.sentence_encoder.layers.6.self_attn.k_proj.weight", "encoder.sentence_encoder.layers.6.self_attn.k_proj.bias", "encoder.sentence_encoder.layers.6.self_attn.v_proj.weight", "encoder.sentence_encoder.layers.6.self_attn.v_proj.bias", "encoder.sentence_encoder.layers.6.self_attn.q_proj.weight", "encoder.sentence_encoder.layers.6.self_attn.q_proj.bias", "encoder.sentence_encoder.layers.6.self_attn.out_proj.weight", "encoder.sentence_encoder.layers.6.self_attn.out_proj.bias", "encoder.sentence_encoder.layers.6.self_attn_layer_norm.weight", "encoder.sentence_encoder.layers.6.self_attn_layer_norm.bias", "encoder.sentence_encoder.layers.6.fc1.weight", "encoder.sentence_encoder.layers.6.fc1.bias", "encoder.sentence_encoder.layers.6.fc2.weight", "encoder.sentence_encoder.layers.6.fc2.bias", "encoder.sentence_encoder.layers.6.final_layer_norm.weight", "encoder.sentence_encoder.layers.6.final_layer_norm.bias", "encoder.sentence_encoder.layers.7.self_attn.k_proj.weight", "encoder.sentence_encoder.layers.7.self_attn.k_proj.bias", "encoder.sentence_encoder.layers.7.self_attn.v_proj.weight", "encoder.sentence_encoder.layers.7.self_attn.v_proj.bias", "encoder.sentence_encoder.layers.7.self_attn.q_proj.weight", "encoder.sentence_encoder.layers.7.self_attn.q_proj.bias", "encoder.sentence_encoder.layers.7.self_attn.out_proj.weight", "encoder.sentence_encoder.layers.7.self_attn.out_proj.bias", "encoder.sentence_encoder.layers.7.self_attn_layer_norm.weight", "encoder.sentence_encoder.layers.7.self_attn_layer_norm.bias", "encoder.sentence_encoder.layers.7.fc1.weight", "encoder.sentence_encoder.layers.7.fc1.bias", "encoder.sentence_encoder.layers.7.fc2.weight", "encoder.sentence_encoder.layers.7.fc2.bias", "encoder.sentence_encoder.layers.7.final_layer_norm.weight", "encoder.sentence_encoder.layers.7.final_layer_norm.bias".
```

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): 0.9.0
 - PyTorch Version (e.g., 1.0): 1.6.0
 - OS (e.g., Linux): linux
 - How you installed fairseq (`pip`, source): followed https://github.com/pytorch/fairseq
 - Build command you used (if compiling from source): pip install --editable ./
 - Python version: 3.6.10
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: Tesla V100-SXM2-16GB

**Comment by qjin2016** [comment]
> Hmm, your finetuning command doesn’t actually use ROBERTA_PATH, don’t you need to specify --restore-file?

Right, I added this parameter and trained again. But without this parameter the code will download a pretrained model, which is the same as the one I kept locally.

> Separately, I’m not sure how --encoder-layers-to-keep will work at training time like that. Does the printed model have those layers removed?

I think the layers are removed since the final model is smaller than a full model. If having this parameter during training doesn't seem to be correct, what's the right way to prune a full model?

> Finally, can your try specifying encoder_layers_to_keep=... as a kwarg to from_pretrained?

Doesn't seem to work, same error ;-(
