### ISSUE TITLE
Process 0 terminated with exit code 17

### ISSUE THREAD

**Issue by neel04** [pytorch/fairseq#2527]
@myleott Hi, I am training my model on TPU device but am encountering this error:-

    2020-08-25 13:00:20 | WARNING | root | TPU has started up successfully with version pytorch-1.6

    WARNING:root:TPU has started up successfully with version pytorch-1.6
    Exception in device=TPU:0:
    Traceback (most recent call last):
    File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 231, in _start_fn
    fn(gindex, *args)
    File "/content/fairseq/fairseq/distributed_utils.py", line 150, in distributed_main
    args.distributed_rank = distributed_init(args)
    File "/content/fairseq/fairseq/distributed_utils.py", line 112, in distributed_init
    assert xm.xrt_world_size() == args.distributed_world_size
    AssertionError
    Traceback (most recent call last):
    File "/usr/local/bin/fairseq-train", line 33, in
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
    File "/content/fairseq/fairseq_cli/train.py", line 333, in cli_main
    distributed_utils.call_main(args, main)
    File "/content/fairseq/fairseq/distributed_utils.py", line 185, in call_main
    nprocs=8, # use all 8 TPU cores
    File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 296, in spawn
    start_method=start_method)
    File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
    File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 113, in join
    (error_index, exitcode)
    Exception: process 0 terminated with exit code 17

I am trying to do a seq2seq problem and am using preprocessed data using the commands provided in FAIRseq docs. the data was preprocessed successfully, I am presumably running my code on a TPUv2 and have PyTorch along with XLA installed. In both the Tracebacks, the error does not clearly specify what exactly went wrong. This is the training code:-

>%%bash
>fairseq-train /content/drive/'My Drive'/HashPro/preprocessed/  \
>--lr 0.02 --clip-norm 0.1 --optimizer sgd --bpe characters --dropout 0.2 --tpu --bf16 \
>--arch bart_large --save-dir /content/drive/'My Drive'/HashPro/Checkpoints/ 

Any ideas on what the problem might be?

**Comment by neel04** [comment]
Any help would be highly appreciated!

**Comment by neel04** [comment]
Apparently, #2503 has the same error which also hasn't been resolved. The problem may be in `xla` and not causing it to work on TPU's (since it gives an AssertionError for me) but please do understand that these large models take a lot of processing power requiring multiple GPU's or using a few TPU's. GPU costs after 4 start to become prohibitive so TPU support is highly critical for users to run their code. 

I am attaching my TraceBack if it may help somehow:-
```
2020-09-03 14:49:24 | WARNING | root | Waiting for TPU to be start up with version pytorch-1.6...
2020-09-03 14:49:34 | WARNING | root | Waiting for TPU to be start up with version pytorch-1.6...
2020-09-03 14:49:44 | WARNING | root | Waiting for TPU to be start up with version pytorch-1.6...
2020-09-03 14:49:54 | WARNING | root | TPU has started up successfully with version pytorch-1.6

WARNING:root:TPU has started up successfully with version pytorch-1.6
Exception in device=TPU:0: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 231, in _start_fn
    fn(gindex, *args)
  File "/content/fairseq/fairseq/distributed_utils.py", line 148, in distributed_main
    args.distributed_rank = distributed_init(args)
  File "/content/fairseq/fairseq/distributed_utils.py", line 112, in distributed_init
    assert xm.xrt_world_size() == args.distributed_world_size
AssertionError
Traceback (most recent call last):
  File "/usr/local/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/content/fairseq/fairseq_cli/train.py", line 343, in cli_main
    distributed_utils.call_main(args, main)
  File "/content/fairseq/fairseq/distributed_utils.py", line 183, in call_main
    nprocs=8,  # use all 8 TPU cores
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 296, in spawn
    start_method=start_method)
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 113, in join
    (error_index, exitcode)
Exception: process 0 terminated with exit code 17

```

**Comment by neel04** [comment]
Any update on TPU support?

**Comment by myleott** [comment]
You need to explicitly pass --distributed-world-size and it should work (this should equal the number of TPU devices).

**Comment by neel04** [comment]
@myleott No, same error as before:-
```
2020-09-14 16:00:27 | WARNING | root | TPU has started up successfully with version pytorch-1.6
WARNING:root:TPU has started up successfully with version pytorch-1.6
Exception in device=TPU:0: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 235, in _mp_start_fn
    _start_fn(index, pf_cfg, fn, args)
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 229, in _start_fn
    fn(gindex, *args)
  File "/content/fairseq/fairseq/distributed_utils.py", line 218, in distributed_main
    args.distributed_rank = distributed_init(args)
  File "/content/fairseq/fairseq/distributed_utils.py", line 182, in distributed_init
    assert xm.xrt_world_size() == args.distributed_world_size
AssertionError
Traceback (most recent call last):
  File "/usr/local/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/content/fairseq/fairseq_cli/train.py", line 350, in cli_main
    distributed_utils.call_main(args, main)
  File "/content/fairseq/fairseq/distributed_utils.py", line 250, in call_main
    nprocs=8,  # use all 8 TPU cores
  File "/usr/local/lib/python3.6/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 300, in spawn
    start_method=start_method)
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 113, in join
    (error_index, exitcode)
Exception: process 0 terminated with exit code 17
```

**Comment by JunjieHu** [comment]
@myleott I had the exact same problem running *bart* model on TPU v3-8 even after adding --distributed-world-size=1 for one TPU. Here are my commends.

`
REPO=/home/junjie_j_hu/cap
DATA=$REPO/data/cnn_dm-bin
OUTDIR=$REPO/outputs/bart-cnn-dm
mkdir -p $OUTDIR

python $REPO/fairseq/train.py \
$DATA \
--log-interval=10 \
--tpu \
--distributed-world-size=1 \
--log-format=json \
--no-progress-bar \
--tensorboard-logdir=$OUTDIR \
--seed=1 \
--min-loss-scale=0.0001 \
--model-parallel-size=1 \
--criterion=cross_entropy \
--optimizer=adam \
--lr-scheduler=polynomial_decay \
--task=denoising \
--num-workers=4 \
--skip-invalid-size-inputs-valid-test \
--required-batch-size-multiple=1 \
--train-subset=train \
--valid-subset=valid \
--validate-interval=1 \
--bucket-cap-mb=25 \
--arch=bart_base \
--max-update=500000 \
--clip-norm=0.1 \
--update-freq=[2] \
--lr=[0.0006] \
--min-lr=-1 \
--save-dir=$OUTDIR \
--restore-file=checkpoint_last.pt \
--optimizer-overrides={} \
--save-interval=1 \
--save-interval-updates=50 \
--keep-interval-updates=-1 \
--keep-last-epochs=-1 \
--keep-best-checkpoints=-1 \
--no-epoch-checkpoints \
--best-checkpoint-metric=loss \
--patience=-1 \
--adam-betas="(0.9, 0.98)" \
--adam-eps=1e-06 \
--weight-decay=0.01 \
--warmup-updates=10000 \
--power=1 \
--total-num-update=100 \
--tokens-per-sample=64 \
--max-sentences=16 \
--sample-break-mode=complete_doc \
--mask=0.3 \
--mask-random=0.1 \
--poisson-lambda=3.5 \
--permute-sentences=1 \
--mask-length=span-poisson \
--replace-length=1 \
--max-source-positions=64 \
--max-target-positions=64 \
--dropout=0.1 \
--attention-dropout=0.1 \
--share-all-embeddings \
--layernorm-embedding \
--share-decoder-input-output-embed`

**Comment by neel04** [comment]
@JunjieHu Can you tell me the number of workers for your TPU? I am using `Colab` TPU which I think has 8 workers, but it doesn't work on that at all.

**Comment by neel04** [comment]
@myleott I set `--distributed-world-size=1` to get the code to work and the model to train, but the training is extremely slow. I have 2.5Million iterations to do in 1 epoch and each iteration takes like half a minute. Clearly, my TPU is not being used fully. Can you suggest any fix for it?

**Comment by JunjieHu** [comment]
@neel04, I use the TPU v3-8 which I think has 8 workers. I finally end up modifying a lots in Fairseq by referring to the code under this folder `/usr/share/torch-xla-1.6/tpu-examples/deps/fairseq/` in a GCP instance, based on [the GCP's tutorial ](https://cloud.google.com/tpu/docs/tutorials/transformer-pytorch#set_up_a_instance).

**Comment by neel04** [comment]
@myleott I fixed some code that doesn't install Nvidia's Apex properly, and now it all works, I am able to pass `--distributed-world-size=8` but the speed doesn't show any improvement at all (The epoch is estimated to be completed in about ~70-ish hrs). Would you have any idea why it happens?

**Comment by dhruvrnaik** [comment]
@neel04  did installing Nvidia/Apex properly solve this issue for you? I seem to have the same issue. Works with `distributed-world-size=1 `but not with `=8`

**Comment by neel04** [comment]
@dhruvrnaik I think that the TPU code isn't really ready/working. Better ping the maintainers for that. It was working for me before but I updated my repo and now I can use `--distributed-world-size=8`. But note that the flags for TPU like `--bf16` etc. do not seem to be available, so I think they want to close TPU feature entirely...

**Comment by dhruvrnaik** [comment]
Yeah, my code seems to work without the `--bf16` flag

**Comment by neel04** [comment]
Of course, since it won't use the TPU then to its full limit; it would likely be worse than your CPU. Better to use a GPU

**Comment by praveenphatate** [comment]
I am getting the same error for this 
``import torch
import torch.distributed as dist
import torch.multiprocessing as mp

def init_process(rank, size, backend='gloo'):
    """ Initialize the distributed environment. """
    os.environ['MASTER_ADDR'] = '127.0.0.1'
    os.environ['MASTER_PORT'] = '29500'
    dist.init_process_group(backend, rank=rank, world_size=size)

def train(rank, num_epochs, world_size):
    init_process(rank, world_size)
    print(
        f"Rank {rank + 1}/{world_size} process initialized.\n"
    )
    # rest of the training script goes here!

WORLD_SIZE = torch.cuda.device_count()
NUM_EPOCHS = 8

mp.spawn(
        train, args=(NUM_EPOCHS, WORLD_SIZE),
        nprocs=1, 
        join=True)

**Comment by neel04** [comment]
@myleott Any update?

**Comment by neel04** [comment]
@myleott tried with the New Fairseq version, PyTorch, and XLA version but still got a similar error. Any idea what is happening?
