### ISSUE TITLE
"ValueError: negative dimensions are not allowed" when calling fairseq-eval-lm

### ISSUE THREAD

**Issue by eshaan-pathak** [pytorch/fairseq#2531]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
Has anybody ran into this ValueError when trying to evaluate their trained LM? I am able to encode my text into BPE, preprocess, train, and generate (using fairseq-interactive) without any problems, but I run into issues when calling fairseq-eval-lm. When SSH'd into a different machine in the past with this fairseq commit, I would be able to evaluate an LM without any problems.

#### Code

I run the following code snippet after preprocessing and have tried various combinations of commenting out the lines after "--context-window 400", but I keep getting the same error shown below this command. CHECKPOINT_DIR is the directory where the checkpoint, binary, and index files are located.

Command:
`fairseq-eval-lm ${CHECKPOINT_DIR} --path ${CHECKPOINT_DIR}/checkpoint_best.pt --max-sentences 2 --tokens-per-sample 512 --context-window 400 --bpe gpt2 --gpt2-encoder-json gpt2_bpe/encoder.json --gpt2-vocab-bpe gpt2_bpe/vocab.bpe --fp16`

Output:
`Namespace(add_bos_token=False, bpe='gpt2', context_window=400, cpu=False, criterion='cross_entropy', data='../checkpoints/base/donald/tokens/normal/10', dataset_impl=None, empty_cache_freq=0, force_anneal=None, fp16=True, fp16_init_scale=128, fp16_scale_tolerance=0.0, fp16_scale_window=None, future_target=False, gen_subset='test', gpt2_encoder_json='gpt2_bpe/encoder.json', gpt2_vocab_bpe='gpt2_bpe/vocab.bpe', lazy_load=False, log_format=None, log_interval=1000, lr_scheduler='fixed', lr_shrink=0.1, max_sentences=2, max_target_positions=None, max_tokens=None, memory_efficient_fp16=False, min_loss_scale=0.0001, model_overrides='{}', momentum=0.99, no_progress_bar=False, num_shards=1, num_workers=1, optimizer='nag', output_dictionary_size=-1, output_word_probs=False, output_word_stats=False, past_target=False, path='../checkpoints/base/donald/tokens/normal/10/checkpoint_best.pt', quiet=False, raw_text=False, remove_bpe=None, required_batch_size_multiple=8, results_path=None, sample_break_mode='none', seed=1, self_target=False, shard_id=0, skip_invalid_size_inputs_valid_test=False, softmax_batch=9223372036854775807, task='language_modeling', tensorboard_logdir='', threshold_loss_scale=None, tokenizer=None, tokens_per_sample=512, user_dir=None, warmup_updates=0, weight_decay=0.0)
| dictionary: 49776 types
| loading model(s) from ../checkpoints/base/donald/tokens/normal/10/checkpoint_best.pt
| dictionary: 49776 types
| loaded 1063395 examples from: ../checkpoints/base/donald/tokens/normal/10/test`

Error:
`Traceback (most recent call last):
  File "/home/miniconda3/envs/eshaan/bin/fairseq-eval-lm", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-eval-lm')())
  File "/home/eshaan/fairseq/fairseq_cli/eval_lm.py", line 223, in cli_main
    main(args)
  File "/home/eshaan/fairseq/fairseq_cli/eval_lm.py", line 77, in main
    task.load_dataset(args.gen_subset)
  File "/home/eshaan/fairseq/fairseq/tasks/language_modeling.py", line 179, in load_dataset
    include_targets=True,
  File "/home/eshaan/fairseq/fairseq/data/token_block_dataset.py", line 78, in __init__
    slice_indices = _get_slice_indices_fast(sizes, break_mode, block_size, document_sep_len)
  File "fairseq/data/token_block_utils_fast.pyx", line 50, in fairseq.data.token_block_utils_fast._get_slice_indices_fast
  File "fairseq/data/token_block_utils_fast.pyx", line 62, in fairseq.data.token_block_utils_fast._get_slice_indices_fast
  File "fairseq/data/token_block_utils_fast.pyx", line 25, in fairseq.data.token_block_utils_fast._get_slice_indices_none_mode
ValueError: negative dimensions are not allowed`

#### What have you tried?
I have tried calling fairseq-eval-lm with various combinations of the flags stated above in case there were any issues with BPE. I also deleted the repository and tried recloning my repository to ensure I didn't change anything in the v0.9.0 release.. 

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): v0.9.0 which is this commit: https://github.com/pytorch/fairseq/tree/df2f84ce619edddb80e720a56abc74d5490fed99
 - PyTorch Version (e.g., 1.0): 1.4.0
 - OS (e.g., Linux): Ubuntu Linux
 - How you installed fairseq (`pip`, source): `pip install -e fairseq/`
 - Build command you used (if compiling from source):
 - Python version: 3.7.6
 - CUDA/cuDNN version: CUDA version 10.1.168
 - GPU models and configuration: 2x NVIDIA Quadro RTX 6000
 - Any other relevant information: Using a miniconda3 environment.

**Comment by eshaan-pathak** [comment]
I finally figured it out after 15 hours of debugging... it was a silly mistake. My tokens-per-sample was not the same value between training and evaluating. I was using 256 in training whereas I was using 512 in the eval example. Closing this issue now.
