### ISSUE TITLE
max_positions Error

### ISSUE THREAD

**Issue by luosmart** [pytorch/fairseq#257]
```
Traceback (most recent call last):
  File "train.py", line 349, in <module>
    main(args)
  File "train.py", line 92, in main
    valid_losses = validate(args, trainer, task, epoch_itr, valid_subsets)
  File "train.py", line 204, in validate
    shard_id=args.distributed_rank,
  File "/mnt/jchluo/fairseq/fairseq/data/data_utils.py", line 136, in __init__
    self.frozen_batches = tuple(self._batch_generator())
  File "/mnt/jchluo/fairseq/fairseq/data/data_utils.py", line 219, in _batch_generator
    ).format(idx, self.max_positions))
Exception: Size of sample #14194 is invalid, max_positions=(1022, 1022), skip this example with --skip-invalid-size-inputs-valid-test
```
I mean this error, how to solve it ? Thank you very much.

**Comment by narfanar** [comment]
Please do not close issues without documenting how you solved them.
