### ISSUE TITLE
How can I use the feature_extractor with wav2vec 2.0?

### ISSUE THREAD

**Issue by shamoons** [pytorch/fairseq#2580]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
When trying to use `feature_extractor`, I get an error:
```
Traceback (most recent call last):
  File "create_data.py", line 22, in <module>
    start_split(model_path=model_path)
  File "create_data.py", line 9, in start_split
    model.load_state_dict(cp['model'])
  File "/Users/shamoon/.local/share/virtualenvs/Vec2Wav-FhgzxqaM/lib/python3.7/site-packages/fairseq/models/fairseq_model.py", line 71, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/Users/shamoon/.local/share/virtualenvs/Vec2Wav-FhgzxqaM/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Wav2VecModel:
        Missing key(s) in state_dict: "feature_extractor.conv_layers.1.2.weight", "feature_extractor.conv_layers.1.2.bias", "feature_extractor.conv_layers.2.2.weight", "feature_extractor.conv_layers.2.2.bias", "feature_extractor.conv_layers.3.2.weight", "feature_extractor.conv_layers.3.2.bias", "feature_extractor.conv_layers.4.2.weight", "feature_extractor.conv_layers.4.2.bias", "feature_extractor.conv_layers.5.2.weight", "feature_extractor.conv_layers.5.2.bias", "feature_extractor.conv_layers.6.2.weight", "feature_extractor.conv_layers.
```

#### Code
```
model_path = os.path.abspath("data/models/libri960_big.pt")
cp = torch.load(model_path, map_location=torch.device('cpu'))
model = Wav2VecModel.build_model(cp['args'], task=None)
model.load_state_dict(cp['model'])
model.eval()

wav_input_16khz = torch.randn(1, 512)

z = model.feature_extractor(wav_input_16khz)
```

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): `master`
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by shamoons** [comment]
For what it's worth, https://stackoverflow.com/questions/54058256/runtimeerror-errors-in-loading-state-dict-for-resnet/54058284#54058284 and https://github.com/pytorch/fairseq/issues/1811 helped fix it.

Needed to change to: `model.load_state_dict(cp['model'], strict=False)`

I'm not sure what `strict=False` does though

**Comment by lematt1991** [comment]
I'm unable to reproduce this.  I ran the following code:

```Python
import torch
from fairseq.models.wav2vec import Wav2VecModel
from subprocess import check_call
import os

if not os.path.exists('wav2vec_large.pt'):
    url = 'https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_large.pt'
    check_call(['wget', url])


cp = torch.load('wav2vec_large.pt')
model = Wav2VecModel.build_model(cp['args'], task=None)
model.load_state_dict(cp['model'])
model.eval()

wav_input_16khz = torch.randn(1,10000)
z = model.feature_extractor(wav_input_16khz)
c = model.feature_aggregator(z)
```

Can you post a reproducible example?  The `strict=False` tells pytorch to not throw an exception if the keys don't match up properly.
