### ISSUE TITLE
why not support transformer xl?

### ISSUE THREAD

**Issue by ismymajia** [pytorch/fairseq#2592]
how to choose transformer xl arch?

**Comment by lematt1991** [comment]
Feel free to submit a PR!

**Comment by myleott** [comment]
We support this now: https://github.com/pytorch/fairseq/tree/master/examples/truncated_bptt

**Comment by YuxianMeng** [comment]
@myleott Hi, thanks for your implementation on Transformer-XL. I am trying your code by following your `README.md` to reproduce results on Wiki-103. I found that the codes work well on single gpu, but raises following error when distributed training: 
```
2021-08-19 15:09:59 | INFO | fairseq_cli.train | training on 2 devices (GPUs/TPUs)
2021-08-19 15:09:59 | INFO | fairseq_cli.train | max tokens per device = None and max sentences per device = 15
2021-08-19 15:09:59 | INFO | fairseq.trainer | Preparing to load checkpoint /data/yuxian/train_logs/debug/checkpoint_last.pt
2021-08-19 15:09:59 | INFO | fairseq.trainer | No existing checkpoint found /data/yuxian/train_logs/debug/checkpoint_last.pt
2021-08-19 15:09:59 | INFO | fairseq.trainer | loading train data for epoch 1
2021-08-19 15:10:03 | INFO | fairseq.data.data_utils | loaded 1,801,350 examples from: /data/nfsdata2/nlp_application/datasets/corpus/english/wikitext-103/data-bin/train
2021-08-19 15:10:03 | INFO | fairseq.trainer | begin training epoch 1
2021-08-19 15:10:03 | INFO | fairseq_cli.train | Start iterating over samples
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mengyuxian/.conda/envs/pretrain/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/home/mengyuxian/.conda/envs/pretrain/lib/python3.6/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "/home/mengyuxian/fairseq/fairseq/tasks/fairseq_task.py", line 41, in __getattr__
    if name not in self._state and name in self._factories:
  File "/home/mengyuxian/fairseq/fairseq/tasks/fairseq_task.py", line 41, in __getattr__
    if name not in self._state and name in self._factories:
  File "/home/mengyuxian/fairseq/fairseq/tasks/fairseq_task.py", line 41, in __getattr__
    if name not in self._state and name in self._factories:
  [Previous line repeated 329 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mengyuxian/.conda/envs/pretrain/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/home/mengyuxian/.conda/envs/pretrain/lib/python3.6/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "/home/mengyuxian/fairseq/fairseq/tasks/fairseq_task.py", line 41, in __getattr__
    if name not in self._state and name in self._factories:
  File "/home/mengyuxian/fairseq/fairseq/tasks/fairseq_task.py", line 41, in __getattr__
    if name not in self._state and name in self._factories:
  File "/home/mengyuxian/fairseq/fairseq/tasks/fairseq_task.py", line 41, in __getattr__
    if name not in self._state and name in self._factories:
  [Previous line repeated 329 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
``` 
Could you please take a look at this?

**Comment by rashadmoarref** [comment]
@YuxianMeng I'm curious were you able to resolve the recursion error? I'm facing a similar problem.

**Comment by freddy5566** [comment]
I am facing the same issue, can anyone help me to fix it?

**Comment by Charlottehoo** [comment]
same
