### ISSUE TITLE
speech recognition inference with kenlm

### ISSUE THREAD

**Issue by sooftware** [pytorch/fairseq#2608]
## ❓ Questions and Help
  
Thank you for releasing such a good toolkit.  
It's helping a lot with the research.
  
I'm going to deduce the model I've learned with the speech_recognion example with KenLM.
The command I used was as follows.  
```
python examples/speech_recognition/infer.py $PREPROCESSED_DIR \
--task speech_recognition --seed 1 --nbest 1 --path $MODEL_PATH \
--gen-subset test-clean --results-path $RESULT_PATH --w2l-decoder kenlm \
--kenlm-model lm_librispeech_kenlm_word_4g_200kvocab.bin \
--lexicon ./manifest/librispeech-train+dev-unigram-10000-nbest10.lexicon \
--beam 200 --beam-threshold 15 --lm-weight 1.5 --word-score 1.5 --sil-weight -0.3 --criterion asg_loss \
--max-replabel 2 --user-dir examples/speech_recognition
```
I download kenlm model file and lexicon at wav2letter repository  ([kenlm](https://dl.fbaipublicfiles.com/wav2letter/lexicon_free/librispeech/models/lm/lm_librispeech_kenlm_word_4g_200kvocab.bin), [Lexicon](https://dl.fbaipublicfiles.com/wav2letter/lexicon_free/librispeech/models/lm/lm_librispeech_kenlm_word_4g_200kvocab.bin))  
  
But, I got an error message following:
```
INFO:__main__:| /data/public/rw/datasets/LibriSpeech/preprocessed test-clean 2620 examples
INFO:__main__:| decoding with criterion asg_loss
INFO:__main__:| loading model(s) from /data/project/rw/kaki/fairseq-asr-example/checkpoint_last.pt
Traceback (most recent call last):
  File "examples/speech_recognition/infer.py", line 428, in <module>
    cli_main()
  File "examples/speech_recognition/infer.py", line 424, in cli_main
    main(args)
  File "examples/speech_recognition/infer.py", line 268, in main
    model_state=model_state,
  File "examples/speech_recognition/infer.py", line 193, in load_models_and_criterions
    model.load_state_dict(state["model"], strict=True)
  File "/root/brainspeech/fairseq/models/fairseq_model.py", line 93, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1045, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for VGGTransformerModel:
        size mismatch for decoder.embed_tokens.weight: copying a param with shape torch.Size([5001, 512]) from checkpoint, the shape in current model is torch.Size([5003, 512]).
        size mismatch for decoder.fc_out.weight: copying a param with shape torch.Size([5001, 1024]) from checkpoint, the shape in current model is torch.Size([5003, 1024]).
        size mismatch for decoder.fc_out.bias: copying a param with shape torch.Size([5001]) from checkpoint, the shape in current model is torch.Size([5003]).
```
  
I'd appreciate it if you could tell me what I did wrong.  
Thank You !

**Comment by lematt1991** [comment]
CC @alexeib

**Comment by alexeib** [comment]
looks like it can't load the fairseq vgg model. where did you get it? did you train it yourself or download a pre-trained model?

**Comment by sooftware** [comment]
Read README.md in `speech_recognition` example, and I trained the model.

**Comment by sooftware** [comment]
what means 5001 and 5003?
