### ISSUE TITLE
Issue in fine tuning Wav2Vec2: getting 'ascii' codec can't decode byte 

### ISSUE THREAD

**Issue by 008karan** [pytorch/fairseq#2655]
## ❓ Questions and Help

I am fine-tuning  wav2vec2 on my data using ctc. I ran the script with librispeech dara and was running fine. When running on my data is throwing:
```
 weight_decay=0.0, wer_args=None, zero_infinity=True, zero_sharding='none')
2020-09-25 18:06:08 | INFO | fairseq.data.audio.raw_audio_dataset | loaded 8513, skipped 0 samples
Traceback (most recent call last):
  File "train.py", line 14, in <module>
    cli_main()
  File "/data/fairseq/fairseq_cli/train.py", line 343, in cli_main
    distributed_utils.call_main(args, main)
  File "/data/fairseq/fairseq/distributed_utils.py", line 172, in call_main
    args.distributed_world_size,
  File "/data/wav/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/data/wav/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/data/wav/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception:

-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/data/wav/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/data/fairseq/fairseq/distributed_utils.py", line 154, in distributed_main
    main(args, **kwargs)
  File "/data/fairseq/fairseq_cli/train.py", line 65, in main
    task.load_dataset(valid_sub_split, combine=False, epoch=1)
  File "/data/fairseq/fairseq/tasks/audio_pretraining.py", line 110, in load_dataset
    for line in f:
  File "/data/wav/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4924: ordinal not in range(128)
```
its seems not able to read data files. But have followed the same preprocessing steps.

**train.wrd**:
```
AVENGER
FOUR. THREE. TWO. ONE. SIX. FIVE. ZERO. NINE. EIGHT. SEVEN.
LISTENING MUSIC
YES
```
**train.ltr**:
```
A V E N G E R |
F O U R . | T H R E E . | T W O . | O N E . | S I X . | F I V E . | Z E R O . | N I N E . | E I G H T . | S E V E N . |
L I S T E N I N G | M U S I C |
Y E S |
```
**train.tsv**:
```
/data/fairseq/IE/
1143-GR/M1IE041143GENC0005.wav	21440
1143-GR/M1IE041143DGSQ1143.wav	69120
1143-GR/M1IE041143GENC0004.wav	17920
```
**Any suggestions? what could be wrong**

**Comment by srinath-zapr** [comment]
@008karan I am getting the same error. Can you mention how did you solve this?

**Comment by 008karan** [comment]
you need to check whether your path is correct or not for input and input data formats.
