### ISSUE TITLE
How to load pre-train after fine-tuned model mBart for translation

### ISSUE THREAD

**Issue by hungnmai** [pytorch/fairseq#2700]
Hello all!
I have just fine-tuned mBART for translation. But i don't know load model for generating. Can u help me! Thanks a lot!!!
`path_sentencepiece_vocab = os.path.join(BASEDIR, 'sentence.bpe.model')

bart = BARTModel.from_pretrained(
        BASEDIR,
        checkpoint_file='checkpoint_best.pt',
        bpe='sentencepiece',
        task="translation_from_pretrained_bart",
        sentencepiece_vocab=path_sentencepiece_vocab)
bart.eval()`

This is error
`/usr/local/lib/python3.6/dist-packages/fairseq/checkpoint_utils.py in _upgrade_state_dict(state)
    347 
    348     # set any missing default values in the task, model or other registries
--> 349     registry.set_defaults(state["args"], tasks.TASK_REGISTRY[state["args"].task])
    350     registry.set_defaults(state["args"], models.ARCH_MODEL_REGISTRY[state["args"].arch])
    351     for registry_name, REGISTRY in registry.REGISTRIES.items():

KeyError: 'translation_from_pretrained_bart'`

**Comment by PYMAQ** [comment]
I have same question！who can solve it？
2021-03-31 07:56:52 | INFO | fairseq_cli.train | model bart_large, criterion LabelSmoothedCrossEntropyCriterion
2021-03-31 07:56:52 | INFO | fairseq_cli.train | num. model params: 416791552 (num. trained: 416791552)
2021-03-31 07:56:58 | INFO | fairseq_cli.train | training on 1 GPUs
2021-03-31 07:56:58 | INFO | fairseq_cli.train | max tokens per GPU = 800 and max sentences per GPU = None
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    cli_main()
  File "/tf/pym/Multi-View-Seq2Seq-master/fairseq_multi_view/fairseq_cli/train.py", line 440, in cli_main
    main(args)
  File "/tf/pym/Multi-View-Seq2Seq-master/fairseq_multi_view/fairseq_cli/train.py", line 88, in main
    extra_state, epoch_itr = checkpoint_utils.load_checkpoint(args, trainer)
  File "/tf/pym/Multi-View-Seq2Seq-master/fairseq_multi_view/fairseq/checkpoint_utils.py", line 133, in load_checkpoint
    reset_meters=args.reset_meters,
  File "/tf/pym/Multi-View-Seq2Seq-master/fairseq_multi_view/fairseq/trainer.py", line 269, in load_checkpoint
    state = checkpoint_utils.load_checkpoint_to_cpu(filename)
  File "/tf/pym/Multi-View-Seq2Seq-master/fairseq_multi_view/fairseq/checkpoint_utils.py", line 172, in load_checkpoint_to_cpu
    state = _upgrade_state_dict(state)
  File "/tf/pym/Multi-View-Seq2Seq-master/fairseq_multi_view/fairseq/checkpoint_utils.py", line 354, in _upgrade_state_dict
    registry.set_defaults(state["args"], tasks.TASK_REGISTRY[state["args"].task])
KeyError: 'translation_from_pretrained_bart'
