### ISSUE TITLE
multiprocessing causing RunTimeError

### ISSUE THREAD

**Issue by Tian312** [pytorch/fairseq#272]
Hi, 

I'm trying to test the story generation example. However, the RunTimeError occurred during the training process. Could you help look into it and let me know how to solve the error? The error message is attached
I'm using python 3.6 and my pytorch version is 0.4.1. Thank you.

Traceback (most recent call last):
  File "train.py", line 360, in <module>
    multiprocessing_main(args)
  File "/home/tk2624/projects/fairseq/multiprocessing_train.py", line 41, in main
    p.join()
  File "/home/tk2624/anaconda3/lib/python3.6/multiprocessing/process.py", line 124, in join
    res = self._popen.wait(timeout)
  File "/home/tk2624/anaconda3/lib/python3.6/multiprocessing/popen_fork.py", line 50, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/tk2624/anaconda3/lib/python3.6/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/home/tk2624/projects/fairseq/multiprocessing_train.py", line 82, in signal_handler
    raise Exception(msg)
Exception: 

-- Tracebacks above this line can probably be ignored --

Traceback (most recent call last):
  File "/home/tk2624/projects/fairseq/multiprocessing_train.py", line 46, in run
    single_process_main(args)
  File "/home/tk2624/projects/fairseq/train.py", line 98, in main
    valid_losses = validate(args, trainer, task, epoch_itr, valid_subsets)
  File "/home/tk2624/projects/fairseq/train.py", line 214, in validate
    shard_id=args.distributed_rank,
  File "/home/tk2624/projects/fairseq/fairseq/tasks/fairseq_task.py", line 115, in get_batch_iterator
    shard_id=shard_id,
  File "/home/tk2624/projects/fairseq/fairseq/data/iterators.py", line 80, in __init__
    self.frozen_batches = tuple(batch_sampler)
  File "/home/tk2624/projects/fairseq/fairseq/data/data_utils.py", line 148, in batch_by_size
    for idx in indices:
  File "/home/tk2624/projects/fairseq/fairseq/data/data_utils.py", line 101, in filter_by_size
    ).format(idx, size_fn(idx), max_positions))
Exception: Size of sample #1740 is invalid (=(6, 167)) since max_positions=(1022, 1022), skip this example with --skip-invalid-size-inputs-valid-test

Process SpawnProcess-2:
Exception ignored in: <bound method tqdm.__del__ of | epoch 001:  99%|▉| 191/192 [01:08<00:00,  2.80it/s, loss=9.328, nll_loss=9.328, ppl=642.64, wps=11930, ups=2.8, wpb=4196, bsz=9, num_updates=191, lr=0.25, gnorm=4.080, clip=100%, oom=0, wall=68, train_wall=67]>
Traceback (most recent call last):
  File "/home/tk2624/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 885, in __del__
    self.close()
  File "/home/tk2624/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1090, in close
    self._decr_instances(self)
  File "/home/tk2624/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 454, in _decr_instances
    cls.monitor.exit()
  File "/home/tk2624/anaconda3/lib/python3.6/site-packages/tqdm/_monitor.py", line 52, in exit
Exception ignored in: <bound method tqdm.__del__ of | epoch 001:  99%|▉| 191/192 [01:07<00:00,  2.81it/s, loss=9.328, nll_loss=9.328, ppl=642.64, wps=11923, ups=2.8, wpb=4196, bsz=9, num_updates=191, lr=0.25, gnorm=4.080, clip=100%, oom=0, wall=68, train_wall=67]>
Traceback (most recent call last):
  File "/home/tk2624/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 885, in __del__
    self.join()
  File "/home/tk2624/anaconda3/lib/python3.6/threading.py", line 1053, in join
    self.close()
  File "/home/tk2624/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1090, in close
    self._decr_instances(self)
  File "/home/tk2624/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 454, in _decr_instances
    cls.monitor.exit()
  File "/home/tk2624/anaconda3/lib/python3.6/site-packages/tqdm/_monitor.py", line 52, in exit
    raise RuntimeError("cannot join current thread")
    self.join()
  File "/home/tk2624/anaconda3/lib/python3.6/threading.py", line 1053, in join
RuntimeError: cannot join current thread
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread

**Comment by myleott** [comment]
Hmm, looks like it's due to the recent changes to max_positions, so it thinks the example is too long when it's not. I'll submit a fix.

**Comment by myleott** [comment]
Actually, this is due to not filtering the dataset correctly. Please refer to the recently added filtering instructions here: https://github.com/pytorch/fairseq/commit/5d00e8eea2644611f397d05c6c8f15083388b8b4

I confirmed that applying that filtering fixes training.
