### ISSUE TITLE
Wav2Vec Fine-tuning step cannot locate wav2letter python bindings.

### ISSUE THREAD

**Issue by ngoel17** [pytorch/fairseq#2730]
I installed the python bindings for wav2letter as follows. I am using Anaconda (base is the enviornment) inside a docker container. When I run the finetuning step of wav2letter, I still get the - bindings not found - error as listed below. Please advise how I can help it find the bindings / verify the bindings installation.  I also see an assertion error below regarding the dictionary. The meaning of that error is not very clear. 

(base) root@ddde7c3df79d:~/wav2letter/bindings/python# pip install -e .                 
Obtaining file:///root/wav2letter/bindings/python
Installing collected packages: wav2letter
  Attempting uninstall: wav2letter
    Found existing installation: wav2letter 0.0.2
    Uninstalling wav2letter-0.0.2:
      Successfully uninstalled wav2letter-0.0.2
  Running setup.py develop for wav2letter
Successfully installed wav2letter
(base) root@ddde7c3df79d:~/wav2letter/bindings/python# cd ../../../fairseq/
(base) root@ddde7c3df79d:~/fairseq# source finetune.sh 
2020-10-13 21:11:56 | INFO | fairseq_cli.train | Namespace(activation_dropout=0.1, adam_betas='(0.9, 0.98)', adam_eps=1e-08, all_gather_list_size=16384, apply_mask=True, arch='wav2vec_ctc', attention_dropout=0.0, batch_size=None, batch_size_valid=None, best_checkpoint_metric='wer', bf16=False, bpe=None, broadcast_buffers=False, bucket_cap_mb=25, checkpoint_suffix='', clip_norm=25.0, cpu=False, criterion='ctc', curriculum=0, data='/app/home/ngoel-00171/dh_clean_nounk_noseg/wav2vec/', data_buffer_size=10, dataset_impl=None, ddp_backend='no_c10d', decay_steps=40000, device_id=0, disable_validation=False, distributed_backend='nccl', distributed_init_method=None, distributed_no_spawn=False, distributed_num_procs=0, distributed_port=-1, distributed_rank=0, distributed_world_size=1, distributed_wrapper='DDP', dropout=0.0, dropout_input=0, empty_cache_freq=0, enable_padding=False, fast_stat_sync=False, feature_grad_mult=0.0, final_dropout=0.0, final_lr_scale=0.05, find_unused_parameters=False, finetune_from_model=None, fix_batches_to_gpus=False, fixed_validation_seed=None, fp16=True, fp16_init_scale=128, fp16_no_flatten_grads=False, fp16_scale_tolerance=0.0, fp16_scale_window=None, freeze_finetune_updates=10000, gen_subset='test', hold_steps=32000, init_lr_scale=0.01, keep_best_checkpoints=-1, keep_interval_updates=-1, keep_last_epochs=-1, labels='ltr', layerdrop=0.1, local_rank=0, localsgd_frequency=3, log_format='json', log_interval=500, lr=[2e-05], lr_scheduler='tri_stage', mask_channel_length=64, mask_channel_other=0.0, mask_channel_prob=0.5, mask_channel_selection='static', mask_length=10, mask_other=0.0, mask_prob=0.5, mask_selection='static', max_epoch=0, max_sample_size=None, max_tokens=1280000, max_tokens_valid=1280000, max_update=80000, maximize_best_checkpoint_metric=False, memory_efficient_bf16=False, memory_efficient_fp16=False, min_loss_scale=0.0001, min_lr=-1.0, min_sample_size=None, model_parallel_size=1, no_epoch_checkpoints=True, no_last_checkpoints=False, no_mask_channel_overlap=False, no_mask_overlap=False, no_pretrained_weights=False, no_progress_bar=False, no_save=False, no_save_optimizer_state=False, no_seed_provided=False, normalize=False, nprocs_per_node=1, num_shards=1, num_workers=8, optimizer='adam', optimizer_overrides='{}', patience=-1, pipeline_balance=None, pipeline_checkpoint='never', pipeline_chunks=0, pipeline_devices=None, pipeline_model_parallel=False, profile=False, quantization_config_path=None, remove_bpe='letter', required_batch_size_multiple=8, required_seq_len_multiple=1, reset_dataloader=False, reset_lr_scheduler=False, reset_meters=False, reset_optimizer=False, restore_file='checkpoint_last.pt', sample_rate=16000, save_dir='/app/home/ngoel-00171/dh_clean_nounk_noseg/wav2vec/', save_interval=1, save_interval_updates=0, scoring='bleu', seed=2337, sentence_avg=True, shard_id=0, skip_invalid_size_inputs_valid_test=False, slowmo_algorithm='LocalSGD', slowmo_momentum=None, stop_time_hours=0, task='audio_pretraining', tensorboard_logdir=None, threshold_loss_scale=None, tokenizer=None, tpu=False, train_subset='train', update_freq=[24], use_bmuf=False, use_old_adam=False, user_dir=None, valid_subset='valid', validate_after_updates=10000, validate_interval=1, validate_interval_updates=0, w2v_path='/app/home/ngoel-00171/wav2vec_out2/checkpoint_best.pt', warmup_steps=8000, weight_decay=0.0, wer_args='("/app/home/ngoel-00171/latest_LM/lm.bin","/app/home/ngoel-00171/latest_LM/lexicon.txt",2,-1)', zero_infinity=True, zero_sharding='none')
2020-10-13 21:11:56 | INFO | fairseq.data.audio.raw_audio_dataset | loaded 8492, skipped 0 samples
/root/fairseq/examples/speech_recognition/w2l_decoder.py:38: UserWarning: wav2letter python bindings are required to use this functionality. Please install from https://github.com/facebookresearch/wav2letter/wiki/Python-bindings
  warnings.warn(
Traceback (most recent call last):
  File "train.py", line 14, in <module>
    cli_main()
  File "/root/fairseq/fairseq_cli/train.py", line 352, in cli_main
    distributed_utils.call_main(args, main)
  File "/root/fairseq/fairseq/distributed_utils.py", line 258, in call_main
    main(args, **kwargs)
  File "/root/fairseq/fairseq_cli/train.py", line 69, in main
    criterion = task.build_criterion(args)
  File "/root/fairseq/fairseq/tasks/fairseq_task.py", line 553, in build_criterion
    return criterions.build_criterion(args, self)
  File "/root/fairseq/fairseq/criterions/__init__.py", line 30, in build_criterion
    return build_criterion_(criterion_cfg, task)
  File "/root/fairseq/fairseq/registry.py", line 54, in build_x
    return builder(args, *extra_args, **extra_kwargs)
  File "/root/fairseq/fairseq/criterions/fairseq_criterion.py", line 61, in build_criterion
    return cls(**init_args)
  File "/root/fairseq/fairseq/criterions/ctc.py", line 45, in __init__
    self.w2l_decoder = W2lKenLMDecoder(dec_args, task.target_dictionary)
  File "/root/fairseq/examples/speech_recognition/w2l_decoder.py", line 150, in __init__
    assert (
AssertionError: ['z', 'ay', 'r', 'ah', 'l'] [36, 3, 13, 3, 15]

#### What's your environment?

 - fairseq Version (master)
 - PyTorch Version (1.4)
 - OS (e.g., Linux): Ubuntu 14
 - How you installed fairseq (`pip`, source): Got the wav2letter docker image, then did git pull, and git clone for fair seq and followed install instructions from the documentation.
 - Build command you used (if compiling from source): Standard as documented. typically cmake .. ; make -j 16 ; make install
 - Python version: 3.8.3
 - CUDA/cuDNN version: 10.0
 - GPU models and configuration: Tesla V100

**Comment by medabalimi** [comment]
I've been able to use wav2letter without any issue:
My environment has been Ubuntu 20.04, Python 3.8.5, Cuda 11.1

How did you build wav2letter? Did you use v0.2 branch? Did you follow the instructions from https://github.com/facebookresearch/wav2letter/wiki/Building-Python-bindings

**Comment by nosyrev** [comment]
Probably that warning is about LexiconFreeDecoder that is missing in wav2letter in v0.2
It isn't required though, but you can add it manually like described here:https://github.com/facebookresearch/wav2letter/issues/775

Assertion error is coming most probably because of incorrect lexicon and is not related to missing class in binding

**Comment by ngoel17** [comment]
Got it. Wonderful. So is my understanding correct that the lexicon could be
phonetic?

**Comment by nosyrev** [comment]
I guess lexicon can be anything as far as it corresponds to training data the model was trained. In w2v2 example it's letters, so lexicon should look like
```
A       A |
A''S    A ' ' S |
A'BODY  A ' B O D Y |
A'COURT A ' C O U R T |
A'D     A ' D |
A'GHA   A ' G H A |
A'GOIN  A ' G O I N |
```
for example in the README

**Comment by ngoel17** [comment]
Thank You. I am guessing that "|" is the end of word marker and is
required, and cannot be anywhere else, and the individual letters like "A"
could also be 2 letters like "ax". is that correct?

**Comment by nosyrev** [comment]
If I correctly understood your question, no "A" couldn't be ax. I am talking about example in the readme when we have specific `dict.ltr.txt`. It is just letters based and if you will look how training data looks like when prepared you'll understand the point.
Corresponding lexicon to it is [that one](https://dl.fbaipublicfiles.com/fairseq/wav2vec/librispeech_lexicon.lst), it is not in the readme and is hided somewhere in the tickets, that's probably is the source of confusion.
If for example you trained on sentence pieces instead of letters, then lexicon should have mapping from words to sentence pieces.

**Comment by ngoel17** [comment]
I am not sure if I explained myself well. So what I meant is that if I were
to use a phonetic lexicon instead will it be syntactically correct to have
it look like the following:

ABDEL  AE B D EH L |
ABDELLA  AE B D EH L AH |
ABDICATE  AE B D AH K EY T |
ABDICATED  AE B D AH K EY T AH D |
ABDICATES  AE B D AH K EY T S |
ABDICATING  AE B D IH K EY T IH NG |
ABDICATION  AE B D IH K EY SH AH N |
ABDNOR  AE B D N ER |
ABDO  AE B D OW |
ABDOLLAH  AE B D AA L AH |
ABDOMEN  AE B D OW M AH N |

**Comment by nosyrev** [comment]
Sure, don't see any reasons why not. But you will need to prepare your training data accordingly and have "AE", "B", "EH" etc in dict.ltr.txt + probably use something else instead of `--labels ltr --post-process letter` during finetuning stage.
So from my point of view lexicon here is just mapping from symbols that were used during the training to actual words in the LM

**Comment by ngoel17** [comment]
It will be great to know the alternate options to --post-process letter. Maybe there is some documentation explaining the toolkit. However, that's probably a different issue.
