### ISSUE TITLE
torch script error for fairseq language model

### ISSUE THREAD

**Issue by ismymajia** [pytorch/fairseq#2741]
## ❓ Questions and Help
export_pt.py ：
    model = load_model_ensemble_and_task([args.input_model])[0][0]
    model.eval()
    model_dict = model.decoder.dictionary
    generator = SequenceGenerator([model], model_dict, beam_size=args.beam_size)
    scripted_generator = torch.jit.script(generator)
    scripted_generator.save(args.output_model)

But the following problem occurs：

File "export_pt.py", line 62, in <module>
    main()
  File "export_pt.py", line 55, in main
    return create_script_module(nn_module, infer_methods_to_compile(nn_module))
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 296, in create_script_module
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 336, in create_script_module_impl
Traceback (most recent call last):
    scripted_generator = torch.jit.script(generator)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 1255, in script
    return torch.jit._recursive.recursive_script(obj)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 534, in recursive_script
    return create_script_module_impl(nn_module, concrete_type, cpp_module, stubs)
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 1593, in _construct
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 534, in recursive_script
    return create_script_module(nn_module, infer_methods_to_compile(nn_module))
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 296, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, cpp_module, stubs)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 336, in create_script_module_impl
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py", line 1593, in _construct
    scripted = recursive_script(orig_value)
    return create_script_module(nn_module, infer_methods_to_compile(nn_module))
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 493, in infer_methods_to_compile
    stubs.append(make_stub_from_method(nn_module, method))
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 40, in make_stub_from_method
    ast = torch.jit.get_jit_def(func, self_name="RecursiveScriptModule")
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/frontend.py", line 171, in get_jit_def
    return build_def(ctx, py_ast.body[0], type_line, self_name)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/frontend.py", line 223, in build_param_list
        """
        Run the forward pass for a decoder-only model.
    init_fn(script_module)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 328, in init_fn
    scripted = recursive_script(orig_value)
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
    init_fn(script_module)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 328, in init_fn
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 534, in recursive_script
    return make_stub(func)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/_recursive.py", line 33, in make_stub
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/frontend.py", line 201, in build_def
    param_list = build_param_list(ctx, py_def.args, self_name)
    raise NotSupportedError(ctx_range, _vararg_kwarg_err)
torch.jit.frontend.NotSupportedError: Compiled functions can't take variable number of arguments or use keyword-only arguments with defaults:
  File "/usr/local/lib/python3.6/dist-packages/fairseq/models/fairseq_model.py", line 435
    def forward(self, src_tokens, **kwargs):
                                   ~~~~~~~ <--- HERE


#### What's your environment?

 - fairseq Version (e.g., 0.9 ):
 - PyTorch Version (e.g., 1.4)
 - OS (e.g., Linux): centos 7
 - How you installed fairseq (source):  git checkout 9f25ffb02ab54a443ba181f732d5dcc00db7bea8
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version: cu100
 - GPU models and configuration:
 - Any other relevant information:

**Comment by ismymajia** [comment]
I looked at the code and found that the forward function has variable parameters：
https://github.com/pytorch/fairseq/blob/a48f235636557b8d3bc4922a6fa90f3a0fa57955/fairseq/models/fairseq_model.py#L464

but several forward function parameters of several subclasses are different and many：
https://github.com/pytorch/fairseq/blob/a48f235636557b8d3bc4922a6fa90f3a0fa57955/fairseq/models/transformer.py#L253
https://github.com/pytorch/fairseq/blob/2d900bf30814d64035dc78012f9cc7b4fc063ea1/fairseq/modules/transformer_layer.py#L252

How do I need to modify it？Many places need to be modified. Is there official support?
