### ISSUE TITLE
M2M: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by lxww302** [pytorch/fairseq#2779]
## 🐛 Bug

When running [m2m example](https://github.com/pytorch/fairseq/blob/master/examples/m2m_100/README.md) for inference on two V100 32G GPU. I got a "CUDA error: an illegal memory access was encountered" error. It seems that the data and the model are in different CUDA devices.

full error messages are:
`Traceback (most recent call last):
  File "~/.miniconda3/bin/fairseq-generate", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-generate')())
  File "~/code/fairseq/fairseq_cli/generate.py", line 392, in cli_main
    main(args)
  File "~/code/fairseq/fairseq_cli/generate.py", line 53, in main
    return _main(cfg, sys.stdout)
  File "~/code/fairseq/fairseq_cli/generate.py", line 202, in _main
    hypos = task.inference_step(
  File "~/code/fairseq/fairseq/tasks/translation_multi_simple_epoch.py", line 225, in inference_step
    return generator.generate(
  File "~/.miniconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "~/code/fairseq/fairseq/sequence_generator.py", line 177, in generate
    return self._generate(sample, **kwargs)
  File "~/code/fairseq/fairseq/sequence_generator.py", line 312, in _generate
    lprobs, avg_attn_scores = self.model.forward_decoder(
  File "~/code/fairseq/fairseq/sequence_generator.py", line 830, in forward_decoder
    decoder_out = model.decoder.forward(tokens, encoder_out=encoder_out)
  File "~/code/fairseq/fairseq/model_parallel/models/pipeline_parallel_transformer/model.py", line 638, in forward
    state = self.decoder_layers(embed_layer_output)
  File "~/.miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "~/.miniconda3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "~/.miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "~/code/fairseq/fairseq/model_parallel/models/pipeline_parallel_transformer/layers.py", line 506, in forward
    x = self.maybe_layer_norm(self.self_attn_layer_norm, x, before=True)
  File "~/code/fairseq/fairseq/model_parallel/models/pipeline_parallel_transformer/layers.py", line 580, in maybe_layer_norm
    return layer_norm(x)
  File "~/.miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "~/.miniconda3/lib/python3.8/site-packages/torch/nn/modules/normalization.py", line 169, in forward
    return F.layer_norm(
  File "~/.miniconda3/lib/python3.8/site-packages/torch/nn/functional.py", line 2048, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps,
RuntimeError: CUDA error: an illegal memory access was encountered`

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

`export CUDA_VISIBLE_DEVICES=4,5,6,7
fairseq-generate \
    data_bin \
    --batch-size 1 \
    --path 12b_last_checkpoint.pt \
    --fixed-dictionary model_dict.128k.txt \
    -s de -t fr \
    --remove-bpe 'sentencepiece' \
    --beam 5 \
    --task translation_multi_simple_epoch \
    --lang-pairs language_pairs.txt \
    --decoder-langtok --encoder-langtok src \
    --gen-subset test \
    --fp16 \
    --dataset-impl mmap \
    --distributed-world-size 1 --distributed-no-spawn \
    --pipeline-model-parallel \
    --pipeline-chunks 1 \
    --pipeline-encoder-balance '[26]' \
    --pipeline-encoder-devices '[0]' \
    --pipeline-decoder-balance '[1,24,1]' \
    --pipeline-decoder-devices '[0,1,0]' > gen_out`

### Environment

 - fairseq Version (e.g., 1.0 or master): 0.9 
 - PyTorch Version (e.g., 1.0) 1.6.0
 - OS (e.g., Linux): linux
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source):
 - Python version: 3.8.3
 - CUDA/cuDNN version: py3.8_cuda10.1.243_cudnn7.6.3_0
 - GPU models and configuration: 
 - Any other relevant information:

**Comment by shruti-bh** [comment]
@lxww302 Yes, there are indeed some issues in generating with the `12b_last_checkpoint.pt` in different GPU environments. But I cannot reproduce this error with two 32GB V100 gpus. Planning to dig deeper and get this resolved within the next week. I will update this thread when there  is a fix.

**Comment by lxww302** [comment]
Thanks. To reproduce this error, we will firstly need to fix another bug in https://github.com/pytorch/fairseq/blob/master/fairseq/model_parallel/models/pipeline_parallel_transformer/model.py#L323, where the `cfg` parameter should be `model_cfg` passed in by https://github.com/pytorch/fairseq/blob/master/fairseq/checkpoint_utils.py#L304. Then run the script above and we will get this error.

**Comment by shruti-bh** [comment]
@lxww302 I was able to reproduce and fix this issue on my end (Please refer to the latest version of the README https://github.com/pytorch/fairseq/tree/master/examples/m2m_100 for checkpoints and pipeline arguments for different hardware configurations) Let us know if you continue facing issues.
