### ISSUE TITLE
Error when loading finetuned BART

### ISSUE THREAD

**Issue by mohammadKhalifa** [pytorch/fairseq#2800]
## 🐛 Bug

I finetuned BART on my own data following the scripts [here](https://github.com/pytorch/fairseq/blob/master/examples/bart/README.summarization.md)

Now when I try to load the model using 
```
>>> bart = BARTModel.from_pretrained('trained_models/my_bart_large', checkpoint_file='checkpoint_last.pt')
loading archive file trained_models/my_bart_large
```
I get the following error 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/khalfad/fairseq-0.9.0/fairseq/models/bart/model.py", line 104, in from_pretrained
    **kwargs,
  File "/home/ubuntu/khalfad/fairseq-0.9.0/fairseq/hub_utils.py", line 68, in from_pretrained
    arg_overrides=kwargs,
  File "/home/ubuntu/khalfad/fairseq-0.9.0/fairseq/checkpoint_utils.py", line 190, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/home/ubuntu/khalfad/fairseq-0.9.0/fairseq/checkpoint_utils.py", line 165, in load_checkpoint_to_cpu
    setattr(args, arg_name, arg_val)
AttributeError: 'NoneType' object has no attribute 'bpe'
```

### Environment

 - fairseq Version: 0.9
 - PyTorch Version: 1.6
 - OS (e.g., Linux): Ubuntu 16.04

**Comment by mohammadKhalifa** [comment]
found the issue. I was using different fairseq versions for training and loading the model
