### ISSUE TITLE
Sentencepiece is broken by migration to hydra

### ISSUE THREAD

**Issue by erip** [pytorch/fairseq#2847]
### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. 

```sh
fairseq-train \
    data-bin \
    --arch transformer --share-decoder-input-output-embed \
    --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 \
    --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 \
    --dropout 0.3 --weight-decay 0.0001 \
    --decoder-attention-heads 2 \
    --encoder-attention-heads 2 \
    --criterion label_smoothed_cross_entropy --label-smoothing 0.1 \
    --max-tokens 4000 \
    --max-epoch 10
```
2. 
```sh
mkdir model

cp checkpoints/checkpoint_best.pt model/
cp sentencepiece* model/
cp data-bin/dict* model/
```
3.

```python
#!/usr/bin/env python3

from fairseq.models.transformer import TransformerModel

if __name__ == "__main__":
    model = TransformerModel.from_pretrained("model", "checkpoint_best.pt", "model", bpe="sentencepiece", sentencepiece_model="model/sentencepiece.bpe.model")
    print(model.translate("abcd"))
```

4. 

```log
Traceback (most recent call last):
  File "test_inference.py", line 6, in <module>
    model = TransformerModel.from_pretrained("model", "checkpoint_best.pt", "model", bpe="sentencepiece", sentencepiece_model="model/sentencepiece.bpe.model")
  File "/Users/erip/Code/fairseq/fairseq/models/fairseq_model.py", line 280, in from_pretrained
    return hub_utils.GeneratorHubInterface(x["args"], x["task"], x["models"])
  File "/Users/erip/Code/fairseq/fairseq/hub_utils.py", line 106, in __init__
    self.bpe = encoders.build_bpe(cfg.bpe)
  File "/Users/erip/Code/fairseq/fairseq/registry.py", line 52, in build_x
    return builder(cfg, *extra_args, **extra_kwargs)
  File "/Users/erip/Code/fairseq/fairseq/data/encoders/sentencepiece_bpe.py", line 23, in __init__
    sentencepiece_model = file_utils.cached_path(cfg.sentencepiece_model)
  File "/Users/erip/Code/fairseq/fairseq/file_utils.py", line 166, in cached_path
    raise EnvironmentError("file {} not found".format(url_or_filename))
OSError: file ??? not found
```

#### Code sample

Reproducer coming soon.

### Expected behavior

It shouldn't crash. 😄 

### Environment

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0) 1.7.0
 - OS (e.g., Linux): all
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source): `pip install -e .`
 - Python version: 3.6.x
 - CUDA/cuDNN version: n/a
 - GPU models and configuration: n/a
 - Any other relevant information: n/a

**Comment by erip** [comment]
Reproducer [here](https://github.com/erip/fairseq-hello-world).
