### ISSUE TITLE
All elements in the dataset have been skipped when I tried to change the dataset in example(translation)

### ISSUE THREAD

**Issue by Arvid-pku** [pytorch/fairseq#2853]
#### What is your question?
I want to run the example/translation example to learn the fairseq just as the https://github.com/pytorch/fairseq/tree/master/examples/translation#training-a-new-model says.
But "All elements in the dataset have been skipped" error happened when I tried to change the dataset.
The dataset I want to use is rotowire( a data2text dataset https://github.com/harvardnlp/boxscore-data/)
I am a beginner in this tool, thank you very much.

#### Error
2020-11-05 20:00:50 | WARNING | fairseq.tasks.fairseq_task | 3398 samples have invalid sizes and will be skipped, max_positions=(1024, 1024), first few sample ids=[1035, 2535, 2688, 1554, 819, 1769, 3083, 1329, 3304, 905]
Traceback (most recent call last):
  File "anaconda3/envs/fairseq/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "mycode/dataec/fairseq/fairseq_cli/train.py", line 392, in cli_main
    distributed_utils.call_main(cfg, main)
  File "mycode/dataec/fairseq/fairseq/distributed_utils.py", line 319, in call_main
    main(cfg, **kwargs)
  File "mycode/dataec/fairseq/fairseq_cli/train.py", line 121, in main
    disable_iterator_cache=task.has_sharded_data("train"),
  File "mycode/dataec/fairseq/fairseq/checkpoint_utils.py", line 217, in load_checkpoint
    epoch=1, load_dataset=True, **passthrough_args
  File "mycode/dataec/fairseq/fairseq/trainer.py", line 436, in get_train_iterator
    self.reset_dummy_batch(batch_iterator.first_batch)
  File "mycode/dataec/fairseq/fairseq/data/iterators.py", line 276, in first_batch
    "The dataset is empty. This could indicate "
Exception: The dataset is empty. This could indicate that all elements in the dataset have been skipped. Try increasing the max number of allowed tokens or using a larger dataset.

#### What have you tried?
I guess it may be related to the length of the sentences in dataset, but I can't find the parameter to correct it.

#### What's your environment?

 - fairseq Version 1.0 
 - PyTorch Version  1.6
 - OS Linux:

**Comment by alexeib** [comment]
have you tried increasing --max-positions?? this error means all examples in your dataset are longer than 1024 tokens (either on source or target side)

**Comment by Arvid-pku** [comment]
Yeah, that's just what I think too. I will try it later.(it is too late:)
thanks

**Comment by rishabhjain16** [comment]
@Arvid-pku were you able to solve this issue? I tried changing the token size in the latest fairseq implementation of wav2vec2 but still the same error.

**Comment by sathyagorla** [comment]
@rishabhjain16 I am also facing same issue, can you please help me how to create the train.tsv and valid.tsv files
