### ISSUE TITLE
Getting CUDA OOM when doing a CPU training

### ISSUE THREAD

**Issue by alealv** [pytorch/fairseq#2879]
## 🐛 Bug

I'm getting an OOM CUDA error when passing `--cpu` option, which makes no sense.
I got it working when I disable all GPUs: 

```sh
env CUDA_VISIBLE_DEVICES= python train.py ....
```

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

```sh
python -W ignore train.py /mnt/data/ale/manifest_ml2 \
--save-dir ~/trainings \
--wer-args '("/mnt/data/ale/kenlm-models/openwebtext/v5/4-gram-265M-25-10-2020-pruned-300K-1.bin","/mnt/data/ale/manifest_ml2/dev.lex",2,-1)' \
--post-process letter  \
--valid-subset dev \
--best-checkpoint-metric wer  \
--num-workers 10 \
--max-update 80000  \
--sentence-avg  \
--task audio_pretraining  \
--arch wav2vec_ctc  \
--w2v-path /mnt/data/ale/models/wav2vec_vox_new.pt \
--labels ltr  \
--apply-mask  \
--mask-selection static  \
--mask-other 0  \
--mask-length 10  \
--mask-prob 0.5  \
--layerdrop 0.1 \
--mask-channel-selection static  \
--mask-channel-other 0  \
--mask-channel-length 64  \
--mask-channel-prob 0.5  \
--zero-infinity \
--feature-grad-mult 0.0  \
--freeze-finetune-updates 10000  \
--validate-after-updates 10000  \
--optimizer adam \
--adam-betas '(0.9, 0.98)'  \
--adam-eps 1e-08  \
--lr 2e-05  \
--lr-scheduler tri_stage  \
--warmup-steps 8000  \
--hold-steps 32000 \
--decay-steps 40000  \
--final-lr-scale 0.05  \
--final-dropout 0.0  \
--dropout 0.0  \
--activation-dropout 0.1  \
--criterion ctc \
--attention-dropout 0.0  \
--seed 2337  \
--log-format json  \
--log-interval 500  \
--ddp-backend no_c10d \
--normalize \
--batch-size 10 \
--cpu \
#--memory-efficient-fp16 \
#--fp16 \
#--empty-cache-freq 10 \
#--update-freq 10 \
#--max-tokens  100000 \
#--model-parallel-size 10 \
#--distributed-world-size 10 \


2020-11-10 16:42:10 | INFO | fairseq.distributed_utils | distributed init (rank 3): tcp://localhost:17973
2020-11-10 16:42:10 | INFO | fairseq.distributed_utils | distributed init (rank 0): tcp://localhost:17973
2020-11-10 16:42:11 | INFO | fairseq.distributed_utils | distributed init (rank 1): tcp://localhost:17973
2020-11-10 16:42:11 | INFO | fairseq.distributed_utils | distributed init (rank 5): tcp://localhost:17973
2020-11-10 16:42:11 | INFO | fairseq.distributed_utils | distributed init (rank 2): tcp://localhost:17973
2020-11-10 16:42:11 | INFO | fairseq.distributed_utils | distributed init (rank 4): tcp://localhost:17973
2020-11-10 16:42:11 | INFO | fairseq.distributed_utils | distributed init (rank 7): tcp://localhost:17973
2020-11-10 16:42:11 | INFO | fairseq.distributed_utils | distributed init (rank 9): tcp://localhost:17973
2020-11-10 16:42:11 | INFO | fairseq.distributed_utils | distributed init (rank 6): tcp://localhost:17973
2020-11-10 16:42:11 | INFO | fairseq.distributed_utils | distributed init (rank 8): tcp://localhost:17973
2020-11-10 16:42:20 | INFO | fairseq.distributed_utils | initialized host ml-2 as rank 8
2020-11-10 16:42:20 | INFO | fairseq.distributed_utils | initialized host ml-2 as rank 1
2020-11-10 16:42:20 | INFO | fairseq.distributed_utils | initialized host ml-2 as rank 9
2020-11-10 16:42:20 | INFO | fairseq.distributed_utils | initialized host ml-2 as rank 6
2020-11-10 16:42:20 | INFO | fairseq.distributed_utils | initialized host ml-2 as rank 7
2020-11-10 16:42:20 | INFO | fairseq.distributed_utils | initialized host ml-2 as rank 0
2020-11-10 16:42:20 | INFO | fairseq.distributed_utils | initialized host ml-2 as rank 3
2020-11-10 16:42:20 | INFO | fairseq.distributed_utils | initialized host ml-2 as rank 5
2020-11-10 16:42:20 | INFO | fairseq.distributed_utils | initialized host ml-2 as rank 4
2020-11-10 16:42:20 | INFO | fairseq.distributed_utils | initialized host ml-2 as rank 2
2020-11-10 16:42:20 | INFO | fairseq_cli.train | {'common': ..............

Traceback (most recent call last):
  File "train.py", line 12, in <module>
    main()
  File "train.py", line 8, in main
    cli_main()
  File "/home/aalvarez/Projects/fairseq/fairseq_cli/train.py", line 392, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home/aalvarez/Projects/fairseq/fairseq/distributed_utils.py", line 313, in call_main
    torch.multiprocessing.spawn(
  File "/home/aalvarez/.virtualenvs/wav2vec-training-XQtg4Z6z-py3.8/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/aalvarez/.virtualenvs/wav2vec-training-XQtg4Z6z-py3.8/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/home/aalvarez/.virtualenvs/wav2vec-training-XQtg4Z6z-py3.8/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 9 terminated with the following error:
Traceback (most recent call last):
  File "/home/aalvarez/.virtualenvs/wav2vec-training-XQtg4Z6z-py3.8/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/aalvarez/Projects/fairseq/fairseq/distributed_utils.py", line 294, in distributed_main
    cfg.distributed_training.distributed_rank = distributed_init(cfg)
  File "/home/aalvarez/Projects/fairseq/fairseq/distributed_utils.py", line 248, in distributed_init
    dist.all_reduce(torch.zeros(1).cuda())
RuntimeError: CUDA error: out of memory
```

### Environment

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0): 1.7+cuda11
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed fairseq (`pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: v3.8
 - CUDA/cuDNN version: CUDA v11.1 cuDNN v8
 - GPU models and configuration: 10 RTX 2080 Ti
 - Any other relevant information:

**Comment by myleott** [comment]
By default fairseq tries to use all visible GPUs and will setup distributed training across them. When you combine this with `--cpu` it will try to do this over CPU (using 10 processes in this case), but we don't currently support distributed training on CPU.

We'll likely add support for distributed CPU training soon, although mostly for CI purposes. I wouldn't expect particularly good training throughput on CPU...

**Comment by undertherain** [comment]
Well there are different types of CPUs.

We have a cluster of 100K nodes (yes, a hundred thousands) of A64FX CPUs
this are new ARM-based chips made by Fujitsu, having close to GPU compute performance and same memory bandwidths (1TB/s). 
Deep learning runs on it nicely, except in fairseq distributed_fairseq_model checking device_id etc is hard-coded - that's a big bummer :(
