### ISSUE TITLE
hydra.errors.MissingConfigException: Could not load hydra/hydra_logging/default

### ISSUE THREAD

**Issue by kokeman** [pytorch/fairseq#2882]
## 🐛 Bug

I installed fairseq as described in the README and ran the command as described [IWSLT'14 German to English (Transformer)](https://github.com/pytorch/fairseq/blob/master/examples/translation/README.md#iwslt14-german-to-english-transformer)

Then the following error occurred at training step.
```
CUDA_VISIBLE_DEVICES=0 fairseq-train \
    data-bin/iwslt14.tokenized.de-en \
    --arch transformer_iwslt_de_en --share-decoder-input-output-embed \
    --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 \
    --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 \
    --dropout 0.3 --weight-decay 0.0001 \
    --criterion label_smoothed_cross_entropy --label-smoothing 0.1 \
    --max-tokens 4096 \
    --eval-bleu \
    --eval-bleu-args '{"beam": 5, "max_len_a": 1.2, "max_len_b": 10}' \
    --eval-bleu-detok moses \
    --eval-bleu-remove-bpe \
    --eval-bleu-print-samples \
    --best-checkpoint-metric bleu --maximize-best-checkpoint-metric
Traceback (most recent call last):
  File "/home/hoge/.pyenv/versions/3.6.6/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/work/yoshimura/fairseq/fairseq_cli/train.py", line 385, in cli_main
    cfg = convert_namespace_to_omegaconf(args)
  File "/work/yoshimura/fairseq/fairseq/dataclass/utils.py", line 324, in convert_namespace_to_omegaconf
    composed_cfg = compose("config", overrides=overrides, strict=False)
  File "/home/hoge/.pyenv/versions/3.6.6/lib/python3.6/site-packages/hydra/experimental/compose.py", line 37, in compose
    with_log_configuration=False,
  File "/home/hoge/.pyenv/versions/3.6.6/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 512, in compose_config
    from_shell=from_shell,
  File "/home/hoge/.pyenv/versions/3.6.6/lib/python3.6/site-packages/hydra/_internal/config_loader_impl.py", line 156, in load_configuration
    from_shell=from_shell,
  File "/home/hoge/.pyenv/versions/3.6.6/lib/python3.6/site-packages/hydra/_internal/config_loader_impl.py", line 262, in _load_configuration
    run_mode=run_mode,
  File "/home/hoge/.pyenv/versions/3.6.6/lib/python3.6/site-packages/hydra/_internal/config_loader_impl.py", line 804, in _merge_defaults_into_config
    hydra_cfg = merge_defaults_list_into_config(hydra_cfg, system_list)
  File "/home/hoge/.pyenv/versions/3.6.6/lib/python3.6/site-packages/hydra/_internal/config_loader_impl.py", line 783, in merge_defaults_list_into_config
    package_override=default1.package,
  File "/home/hoge/.pyenv/versions/3.6.6/lib/python3.6/site-packages/hydra/_internal/config_loader_impl.py", line 715, in _merge_config
    raise MissingConfigException(msg, new_cfg, options)
hydra.errors.MissingConfigException: Could not load hydra/hydra_logging/default
```
### Expected behavior
I tried the following:
1.  ```pip uninstall hydra-core``` and ```pip install hydra-core --upgrade```
2. ```pip uninstall hydra-core``` and ```pip uninstall fairseq``` and  reinstall fairseq ```(pip install --editable .)```

but, it didn't work (same error)

### Environment
 - fairseq:  1.0.0a0+6815772
 - PyTorch: 1.5.0
 - OS: Ubuntu
 - How you installed fairseq (`pip`, source): source 
 - Build command you used (if compiling from source): pip install --editable .
 - Python version: 3.6.6

**Comment by alexeib** [comment]
@omry do you know whats going on here?

**Comment by omry** [comment]
No. I have never seen this.
I am not familiar with fairseq-train. is it an argparse based app using the Compose API?

1. Can you show the output of pip freeze?
2. Can you try to run one of the standard Hydra example apps from the Hydra repo and see if they run?

**Comment by myleott** [comment]
Is this still an issue? I wasn't able to reproduce it on master or the latest stable release (0.10.1). Can you try one of those and reopen if this is still a problem?

**Comment by jingmu123** [comment]
It could be a version issue of hydra-core(1.0.6? or 1.1.2 for different versions of fairseq)

**Comment by jingmu123** [comment]
@kokeman, It could be a version issue of hydra-core(1.0.6? or 1.1.2 for different versions of fairseq)
