### ISSUE TITLE
Unable to interact with trained model

### ISSUE THREAD

**Issue by zyddnys** [pytorch/fairseq#2898]
I was following Google's fairseq TPU tutorial in https://cloud.google.com/tpu/docs/tutorials/transformer-pytorch \
After training I installed the latest version of fairseq (installed from source 20 minutes ago) on the cloud machine. \
I ran the example interactive code:
```
fairseq-interactive pytorch-tutorial-data/wmt18_en_de_bpej32k --path en-de/model.pt --beam 5
```
But I got the following error:
```
2020-11-16 19:29:34 | INFO | fairseq.tasks.translation | [en] dictionary: 35662 types
2020-11-16 19:29:34 | INFO | fairseq.tasks.translation | [de] dictionary: 35662 types
2020-11-16 19:29:34 | INFO | fairseq_cli.interactive | loading model(s) from en-de/model.pt
Traceback (most recent call last):
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/hydra/_internal/config_loader_impl.py", line 513, in _apply_overrides_to_config
    OmegaConf.update(cfg, key, value, merge=True)
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/omegaconf/omegaconf.py", line 613, in update
    root.__setattr__(last_key, value)
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/omegaconf/dictconfig.py", line 277, in __setattr__
    raise e
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/omegaconf/dictconfig.py", line 274, in __setattr__
    self.__set_impl(key, value)
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/omegaconf/dictconfig.py", line 258, in __set_impl
    self._set_item_impl(key, value)
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/omegaconf/basecontainer.py", line 398, in _set_item_impl
    self._validate_set(key, value)
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/omegaconf/dictconfig.py", line 135, in _validate_set
    self._validate_set_merge_impl(key, value, is_assign=True)
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/omegaconf/dictconfig.py", line 151, in _validate_set_merge_impl
    cause=ValidationError("child '$FULL_KEY' is not Optional"),
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/omegaconf/base.py", line 101, in _format_and_raise
    type_override=type_override,
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/omegaconf/_utils.py", line 694, in format_and_raise
    _raise(ex, cause)
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.ValidationError: child 'common.log_interval' is not Optional
        full_key: common.log_interval
        reference_type=CommonConfig
        object_type=CommonConfig

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/anaconda3/envs/torch-xla-1.7/bin/fairseq-interactive", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-interactive')())
  File "/home/idolatrizeworld/fairseq/fairseq_cli/interactive.py", line 318, in cli_main
    distributed_utils.call_main(convert_namespace_to_omegaconf(args), main)
  File "/home/idolatrizeworld/fairseq/fairseq/distributed_utils.py", line 334, in call_main
    main(cfg, **kwargs)
  File "/home/idolatrizeworld/fairseq/fairseq_cli/interactive.py", line 158, in main
    num_shards=cfg.checkpoint.checkpoint_shard_count,
  File "/home/idolatrizeworld/fairseq/fairseq/checkpoint_utils.py", line 262, in load_model_ensemble
    state,
  File "/home/idolatrizeworld/fairseq/fairseq/checkpoint_utils.py", line 289, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/home/idolatrizeworld/fairseq/fairseq/checkpoint_utils.py", line 237, in load_checkpoint_to_cpu
    state = _upgrade_state_dict(state)
  File "/home/idolatrizeworld/fairseq/fairseq/checkpoint_utils.py", line 462, in _upgrade_state_dict
    state["cfg"] = convert_namespace_to_omegaconf(state["args"])
  File "/home/idolatrizeworld/fairseq/fairseq/dataclass/utils.py", line 325, in convert_namespace_to_omegaconf
    composed_cfg = compose("config", overrides=overrides, strict=False)
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/hydra/experimental/compose.py", line 37, in compose
    with_log_configuration=False,
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 512, in compose_config
    from_shell=from_shell,
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/hydra/_internal/config_loader_impl.py", line 156, in load_configuration
    from_shell=from_shell,
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/hydra/_internal/config_loader_impl.py", line 277, in _load_configuration
    ConfigLoaderImpl._apply_overrides_to_config(config_overrides, cfg)
  File "/anaconda3/envs/torch-xla-1.7/lib/python3.6/site-packages/hydra/_internal/config_loader_impl.py", line 522, in _apply_overrides_to_config
    ) from ex
hydra.errors.ConfigCompositionException: Error merging override common.log_interval=null
```
I have googled and seems no one has this problem.

**Comment by myleott** [comment]
I wasn't able to reproduce this. Can you try installing the latest stable release (0.10.1) with `pip install --upgrade fairseq`?

**Comment by guoriyue** [comment]
I also met this

**Comment by guoriyue** [comment]
I sloved the problem!

**Comment by guoriyue** [comment]
I just initialize the null hyperparameter and it will have a proper value.
