### ISSUE TITLE
update wav2vec finetuning to support hydra

### ISSUE THREAD

**Issue by alealv** [pytorch/fairseq#2905]
## 🐛 Bug

I tried to launch the training of `wav2vec2.0` with `hydra_train.py` but I found that if I don't define all the [optional arguments defined in the model](https://github.com/pytorch/fairseq/blob/master/fairseq/models/wav2vec/wav2vec2_asr.py#L28) I get an error

```sh
2020-11-17 16:54:32 | INFO | fairseq.data.audio.raw_audio_dataset | loaded 12102, skipped 0 samples
Traceback (most recent call last):
  File "/home/aalvarez/Projects/fairseq/fairseq_cli/hydra_train.py", line 48, in <module>
    hydra_main()
  File "/home/aalvarez/.virtualenvs/wav2vec_training/lib/python3.8/site-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/home/aalvarez/.virtualenvs/wav2vec_training/lib/python3.8/site-packages/hydra/_internal/utils.py", line 346, in _run_hydra
    run_and_report(
  File "/home/aalvarez/.virtualenvs/wav2vec_training/lib/python3.8/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/home/aalvarez/.virtualenvs/wav2vec_training/lib/python3.8/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/home/aalvarez/.virtualenvs/wav2vec_training/lib/python3.8/site-packages/hydra/_internal/utils.py", line 347, in <lambda>
    lambda: hydra.run(
  File "/home/aalvarez/.virtualenvs/wav2vec_training/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 107, in run
    return run_job(
  File "/home/aalvarez/.virtualenvs/wav2vec_training/lib/python3.8/site-packages/hydra/core/utils.py", line 125, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/aalvarez/Projects/fairseq/fairseq_cli/hydra_train.py", line 35, in hydra_main
    distributed_utils.call_main(cfg, pre_main)
  File "/home/aalvarez/Projects/fairseq/fairseq/distributed_utils.py", line 313, in call_main
    torch.multiprocessing.spawn(
  File "/home/aalvarez/.virtualenvs/wav2vec_training/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/aalvarez/.virtualenvs/wav2vec_training/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/home/aalvarez/.virtualenvs/wav2vec_training/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/aalvarez/.virtualenvs/wav2vec_training/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/aalvarez/Projects/fairseq/fairseq/distributed_utils.py", line 300, in distributed_main
    main(cfg, **kwargs)
  File "/home/aalvarez/Projects/fairseq/fairseq_cli/train.py", line 74, in main
    model = task.build_model(cfg.model)
  File "/home/aalvarez/Projects/fairseq/fairseq/tasks/audio_pretraining.py", line 201, in build_model
    model = super().build_model(model_cfg)
  File "/home/aalvarez/Projects/fairseq/fairseq/tasks/fairseq_task.py", line 282, in build_model
    model = models.build_model(cfg, self)
  File "/home/aalvarez/Projects/fairseq/fairseq/models/__init__.py", line 86, in build_model
    return model.build_model(cfg, task)
  File "/home/aalvarez/Projects/fairseq/fairseq/models/wav2vec/wav2vec2_asr.py", line 167, in build_model
    base_architecture(args)
  File "/home/aalvarez/Projects/fairseq/fairseq/models/wav2vec/wav2vec2_asr.py", line 640, in base_architecture
    args.no_pretrained_weights = getattr(args, "no_pretrained_weights", False)
  File "/home/aalvarez/.virtualenvs/wav2vec_training/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 277, in __setattr__
    raise e
  File "/home/aalvarez/.virtualenvs/wav2vec_training/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 274, in __setattr__
    self.__set_impl(key, value)
  File "/home/aalvarez/.virtualenvs/wav2vec_training/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 258, in __set_impl
    self._set_item_impl(key, value)
  File "/home/aalvarez/.virtualenvs/wav2vec_training/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 398, in _set_item_impl
    self._validate_set(key, value)
  File "/home/aalvarez/.virtualenvs/wav2vec_training/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 135, in _validate_set
    self._validate_set_merge_impl(key, value, is_assign=True)
  File "/home/aalvarez/.virtualenvs/wav2vec_training/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 168, in _validate_set_merge_impl
    target = self._get_node(key)
  File "/home/aalvarez/.virtualenvs/wav2vec_training/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 375, in _get_node
    self._validate_get(key)
  File "/home/aalvarez/.virtualenvs/wav2vec_training/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 127, in _validate_get
    self._format_and_raise(
  File "/home/aalvarez/.virtualenvs/wav2vec_training/lib/python3.8/site-packages/omegaconf/base.py", line 95, in _format_and_raise
    format_and_raise(
  File "/home/aalvarez/.virtualenvs/wav2vec_training/lib/python3.8/site-packages/omegaconf/_utils.py", line 694, in format_and_raise
    _raise(ex, cause)
  File "/home/aalvarez/.virtualenvs/wav2vec_training/lib/python3.8/site-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.ConfigAttributeError: Key 'no_pretrained_weights' is not in struct
	full_key: model.no_pretrained_weights
	reference_type=Any
	object_type=dict
```

### To Reproduce

I launch the training with:
```sh
env HYDRA_FULL_ERROR=1 CUDA_VISIBLE_DEVICES=0,1,2,3 python ~/Projects/fairseq/fairseq_cli/hydra_train.py --config-path ~/Projects/wav2vec_training/scripts --config-name prx_finetunning.yaml
```

where prx_finetunning.yaml is :

```yaml
# @package _group_

common:
  log_interval: 500
  log_format: json 
  seed: 2337 
  fp16: True
  empty_cache_freq: 0
  model_parallel_size: 1
criterion:
  _name: ctc
  wer_args: '("/mnt/data/ale/kenlm-models/openwebtext/v5/4-gram-265M-25-10-2020-pruned-300K-1.bin","/mnt/data/ale/manifest_ml2/dev.lex",2,-1)'
  zero_infinity: True
  post_process: letter
optimizer:
  _name: adam
  adam_betas: '(0.9, 0.9: )'
  adam_eps: 1e-08
lr_scheduler:
  _name: tri_stage
  final_lr_scale: 0.05
  warmup_steps: 8000
task:
  _name: audio_pretraining
  data: /mnt/data/ale/manifest_ml2
  labels: ltr
  sample_rate: 16000
dataset:
  batch_size: 1
  num_workers: 10
  train_subset: train
  valid_subset: dev
  validate_after_updates: 10000
distributed_training:
  distributed_world_size: 4
  ddp_backend: no_c10d
optimization:
  max_epoch: 0
  max_update: 50000
  sentence_avg: True
  lr: [2e-05]
  update_freq: [1]
checkpoint:
  #finetune_from_model: False
  save_dir: ~/trainings
  best_checkpoint_metric: wer
model:
  _name: wav2vec_ctc
  w2v_path: /mnt/data/ale/models/wav2vec_vox_new.pt
  mask_selection: static 
  mask_other: 0
  mask_length: 10
  mask_prob: 0.5 
  mask_channel_selection: static 
  mask_channel_other: 0
  mask_channel_length: 64
  mask_channel_prob: 0.5
  feature_grad_mult: 0.0
  freeze_finetune_updates: 10000
  hold_steps: 32000
  decay_steps: 40000
  final_dropout: 0.0
  dropout: 0.0
  activation_dropout: 0.1
  attention_dropout: 0.0
```

### Environment

- fairseq Version (e.g., 1.0 or master): master
- PyTorch Version (e.g., 1.0): 1.7+cuda11
- OS (e.g., Linux): Ubuntu 20.04
- How you installed fairseq (pip, source): pip
- Build command you used (if compiling from source):
- Python version: v3.8
- CUDA/cuDNN version: CUDA v11.1 cuDNN v8
- GPU models and configuration: RTX 2080 Ti

**Comment by alexeib** [comment]
so far i've only migrated pre-training wav2vec to hydra
finetuning hasnt been migrated yet. should be out today or tomorrow, then your config-based training should work
