### ISSUE TITLE
OOM in the final of the fairseq-generate

### ISSUE THREAD

**Issue by jemmryx** [pytorch/fairseq#2909]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
OOM when the final of the fairseq-generate
#### Code
Traceback (most recent call last):
  File "/home/jiaxin/tools/py38tc150/bin/fairseq-generate", line 8, in <module>
    sys.exit(cli_main())
  File "/home/jiaxin/tools/py38tc150/lib/python3.8/site-packages/fairseq_cli/generate.py", line 199, in cli_main
    main(args)
  File "/home/jiaxin/tools/py38tc150/lib/python3.8/site-packages/fairseq_cli/generate.py", line 104, in main
    hypos = task.inference_step(generator, models, sample, prefix_tokens)
  File "/home/jiaxin/tools/py38tc150/lib/python3.8/site-packages/fairseq/tasks/fairseq_task.py", line 265, in inference_step
    return generator.generate(models, sample, prefix_tokens=prefix_tokens)
  File "/home/jiaxin/tools/py38tc150/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/jiaxin/tools/py38tc150/lib/python3.8/site-packages/fairseq/sequence_generator.py", line 113, in generate
    return self._generate(model, sample, **kwargs)
  File "/home/jiaxin/tools/py38tc150/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/jiaxin/tools/py38tc150/lib/python3.8/site-packages/fairseq/sequence_generator.py", line 291, in _generate
    model.reorder_incremental_state(reorder_state)
  File "/home/jiaxin/tools/py38tc150/lib/python3.8/site-packages/fairseq/sequence_generator.py", line 612, in reorder_incremental_state
    model.decoder.reorder_incremental_state(self.incremental_states[model], new_order)
  File "/home/jiaxin/tools/py38tc150/lib/python3.8/site-packages/fairseq/models/fairseq_incremental_decoder.py", line 75, in reorder_incremental_state
    self.apply(apply_reorder_incremental_state)
  File "/home/jiaxin/tools/py38tc150/lib/python3.8/site-packages/torch/nn/modules/module.py", line 289, in apply
    module.apply(fn)
  File "/home/jiaxin/tools/py38tc150/lib/python3.8/site-packages/torch/nn/modules/module.py", line 289, in apply
    module.apply(fn)
  File "/home/jiaxin/tools/py38tc150/lib/python3.8/site-packages/torch/nn/modules/module.py", line 289, in apply
    module.apply(fn)
  File "/home/jiaxin/tools/py38tc150/lib/python3.8/site-packages/torch/nn/modules/module.py", line 290, in apply
    fn(self)
  File "/home/jiaxin/tools/py38tc150/lib/python3.8/site-packages/fairseq/models/fairseq_incremental_decoder.py", line 73, in apply_reorder_incremental_state
    module.reorder_incremental_state(incremental_state, new_order)
  File "/home/jiaxin/tools/py38tc150/lib/python3.8/site-packages/fairseq/modules/multihead_attention.py", line 314, in reorder_incremental_state
    input_buffer[k] = input_buffer[k].index_select(0, new_order)
RuntimeError: CUDA out of memory. Tried to allocate 320.00 MiB (GPU 0; 10.76 GiB total capacity; 9.33 GiB already allocated; 261.44 MiB free; 9.66 GiB reserved in total by PyTorch)
   

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):0.9.0
 - PyTorch Version (e.g., 1.0)1.5.0
 - OS (e.g., Linux):unbuntu 20.4
 - How you installed fairseq (`pip`, source):pip
 - Build command you used (if compiling from source):
 - Python version:3.8.5
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by lematt1991** [comment]
What is your question?  Please follow the issue templates

**Comment by junwen-austin** [comment]
@lematt1991 Happy New Year.

I am having the same issue where out of memory error on CUDA appears to be at the 99% of fairest-generate which is used to translate bulk text. I checked the last few batches and it does not appear to have extremely long sentences. so I do not understand why the error would occur. I would appreciate if you could shed some light on possible cause. 

Thank you so much!
