### ISSUE TITLE
Command for reproducing "Scaling Neural Machine Translation" doesn't run

### ISSUE THREAD

**Issue by eric-haibin-lin** [pytorch/fairseq#294]
Running
```
python3 train.py data-bin/wmt14_en_de_joined_dict   --arch transformer_vaswani_wmt_en_de_big --share-all-embeddings   --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0   --lr-scheduler inverse_sqrt --warmup-init-lr 1e-07 --warmup-updates 4000   --lr 0.0005 --min-lr 1e-09   --dropout 0.3 --weight-decay 0.0 --criterion label_smoothed_cross_entropy --label-smoothing 0.1   --max-tokens 3584   --fp16
```
Gives me:
```
.....
.....
.....
.....
.....

    from .._functions.thnn import _all_functions as _thnn_functions
  File "/home/ubuntu/.local/lib/python3.5/site-packages/torch/nn/_functions/thnn/__init__.py", line 5, in <module>
  File "/home/ubuntu/.local/lib/python3.5/site-packages/torch/nn/_functions/thnn/__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap_external>", line 478, in _compile_bytecode
  File "<frozen importlib._bootstrap>", line 106, in acquire
    from .._functions.thnn import _all_functions as _thnn_functions
  File "/home/ubuntu/.local/lib/python3.5/site-packages/torch/nn/_functions/thnn/__init__.py", line 3, in <module>
    from .auto import *
    from .fold import *
  File "/home/ubuntu/.local/lib/python3.5/site-packages/torch/nn/_functions/thnn/auto.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap_external>", line 366, in _verbose_message
    from .auto import *
  File "/home/ubuntu/.local/lib/python3.5/site-packages/torch/nn/_functions/thnn/auto.py", line 363, in <module>
KeyboardInterrupt
    @staticmethod
KeyboardInterrupt
    from torch._thnn.utils import parse_header, THNN_H_PATH
  File "/home/ubuntu/.local/lib/python3.5/site-packages/torch/_thnn/__init__.py", line 52, in <module>
KeyboardInterrupt
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 886, in _find_spec
    _thnn_headers = parse_header(THNN_H_PATH)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/torch/_thnn/utils.py", line 86, in parse_header
KeyboardInterrupt
    _generate_function_classes(locals())
  File "/home/ubuntu/.local/lib/python3.5/site-packages/torch/nn/_functions/thnn/auto.py", line 270, in _generate_function_classes
    for l, c in lines:
  File "/home/ubuntu/.local/lib/python3.5/site-packages/torch/_thnn/utils.py", line 83, in <lambda>
    lines = map(lambda l: (l[0].split(','), l[1]), lines)
KeyboardInterrupt
    function_list = parse_header(THNN_H_PATH)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/torch/_thnn/utils.py", line 116, in parse_header
    generic_functions[-1].add_argument(Argument(t, name, '[OPTIONAL]' in c))
  File "/home/ubuntu/.local/lib/python3.5/site-packages/torch/_thnn/utils.py", line 61, in __init__
    def __init__(self, _type, name, is_optional):
KeyboardInterrupt
    FrameInfo = namedtuple('FrameInfo', ('frame',) + Traceback._fields)
  File "/usr/lib/python3.5/collections/__init__.py", line 418, in namedtuple
    arg_list = repr(tuple(field_names)).replace("'", "")[1:-1],
KeyboardInterrupt
Traceback (most recent call last):
  File "train.py", line 357, in <module>
    multiprocessing_main(args)
  File "/home/ubuntu/fairseq/multiprocessing_train.py", line 42, in main
    p.join()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 121, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 51, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/usr/lib/python3.5/multiprocessing/popen_fork.py", line 29, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/home/ubuntu/fairseq/multiprocessing_train.py", line 84, in signal_handler
    raise Exception(msg)
Exception:

-- Tracebacks above this line can probably be ignored --

Traceback (most recent call last):
  File "/home/ubuntu/fairseq/multiprocessing_train.py", line 47, in run
    args.distributed_rank = distributed_utils.distributed_init(args)
  File "/home/ubuntu/fairseq/fairseq/distributed_utils.py", line 56, in distributed_init
    init_fn = dist_c10d.init_process_group
AttributeError: module 'torch.distributed.c10d' has no attribute 'init_process_group'

```
And I'm using pytorch 0.4.1 installed from pip:
```
>>> import torch
>>> torch.__version__
'0.4.1'
```

What did I miss?

**Comment by myleott** [comment]
Sorry, this should be fixed in b14c7cf
