### ISSUE TITLE
omegaconf.errors.ConfigAttributeError: Key 'min_lr' not in 'CosineLRScheduleConfig'

### ISSUE THREAD

**Issue by olesyaksyon** [pytorch/fairseq#2960]
Hi, I've created manifest and I'm trying to train wav2vec model from scratch by following command:

python train.py path/to/manifest --save-dir models/ --num-workers 1 --fp16 --max-update 400000 \
--save-interval 1 --no-epoch-checkpoints --arch wav2vec --task audio_pretraining --lr 1e-06 --min-lr 1e-09 \
--optimizer adam --min-lr 1e-09 --max-lr 1e-05 --lr-scheduler cosine \
--conv-feature-layers "[(512, 10, 5), (512, 8, 4), (512, 4, 2), (512, 4, 2), (512, 4, 2), (512, 1, 1), (512, 1, 1), (512, 1, 1)]" \
--conv-aggregator-layers "[(512, 2, 1), (512, 3, 1), (512, 4, 1), (512, 5, 1), (512, 6, 1), (512, 7, 1), (512, 8, 1), (512, 9, 1), (512, 10, 1), (512, 11, 1), (512, 12, 1), (512, 13, 1)]" \
--vq-type gumbel --vq-groups 2 --vq-depth 2 \
--combine-groups --vq-vars 320 --vq-temp "(2,0.5,0.999995)" --prediction-steps 12 --warmup-updates 1000 \
--warmup-init-lr 1e-07 --criterion wav2vec --num-negatives 10 --max-sample-size 150000 \
--max-tokens 300000 --cross-sample-negatives 0 --update-freq 1 --seed 2 --skip-invalid-size-inputs-valid-test

But after running I get error:

Traceback (most recent call last):
  File "train.py", line 14, in <module>
    cli_main()
  File "/home/olesya/fairseq/fairseq_cli/train.py", line 392, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home/olesya/fairseq/fairseq/distributed_utils.py", line 334, in call_main
    main(cfg, **kwargs)
  File "/home/olesya/fairseq/fairseq_cli/train.py", line 121, in main
    disable_iterator_cache=task.has_sharded_data("train"),
  File "/home/olesya/fairseq/fairseq/checkpoint_utils.py", line 219, in load_checkpoint
    trainer.lr_step(epoch_itr.epoch)
  File "/home/olesya/fairseq/fairseq/trainer.py", line 837, in lr_step
    self.lr_scheduler.step(epoch, val_loss)
  File "/home/olesya/fairseq/fairseq/trainer.py", line 200, in lr_scheduler
    self._build_optimizer()  # this will initialize self._lr_scheduler
  File "/home/olesya/fairseq/fairseq/trainer.py", line 254, in _build_optimizer
    self.optimizer,
  File "/home/olesya/fairseq/fairseq/optim/lr_scheduler/__init__.py", line 29, in build_lr_scheduler
    return build_lr_scheduler_(cfg, optimizer)
  File "/home/olesya/fairseq/fairseq/registry.py", line 61, in build_x
    return builder(cfg, *extra_args, **extra_kwargs)
  File "/home/olesya/fairseq/fairseq/optim/lr_scheduler/cosine_lr_scheduler.py", line 84, in __init__
    self.min_lr = cfg.min_lr if cfg.min_lr > 0.0 else 0.0
  File "/opt/conda/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 297, in __getattr__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/opt/conda/lib/python3.7/site-packages/omegaconf/base.py", line 101, in _format_and_raise
    type_override=type_override,
  File "/opt/conda/lib/python3.7/site-packages/omegaconf/_utils.py", line 629, in format_and_raise
    _raise(ex, cause)
  File "/opt/conda/lib/python3.7/site-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
  File "/opt/conda/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 295, in __getattr__
    return self._get_impl(key=key, default_value=DEFAULT_VALUE_MARKER)
  File "/opt/conda/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 353, in _get_impl
    node = self._get_node(key=key)
  File "/opt/conda/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 375, in _get_node
    self._validate_get(key)
  File "/opt/conda/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 128, in _validate_get
    key=key, value=value, cause=ConfigAttributeError(msg)
  File "/opt/conda/lib/python3.7/site-packages/omegaconf/base.py", line 101, in _format_and_raise
    type_override=type_override,
  File "/opt/conda/lib/python3.7/site-packages/omegaconf/_utils.py", line 694, in format_and_raise
    _raise(ex, cause)
  File "/opt/conda/lib/python3.7/site-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.ConfigAttributeError: Key 'min_lr' not in 'CosineLRScheduleConfig'
	full_key: min_lr
	reference_type=Any
	object_type=CosineLRScheduleConfig

**Comment by myleott** [comment]
Fixed by 4817a9142f49793ec2eedbd71fe5bd872e58e7b5
