### ISSUE TITLE
Error(s) in loading state_dict for Wav2VecCtc

### ISSUE THREAD

**Issue by mironnn** [pytorch/fairseq#2980]
## 🐛 Bug

Have traceback with error `Error(s) in loading state_dict for Wav2VecCtc:`

On commit 68157726 speech recognition example worked. on last changes have traceback.

I use infer.py from speech_recognition example and pre-trained model Wav2Vec 2.0 Large (LV-60) + Self Training.
```
INFO:__main__:Namespace(all_gather_list_size=16384, batch_size=None, batch_size_valid=None, beam=200, beam_size_token=100, beam_threshold=15.0, best_checkpoint_metric='loss', bf16=False, bpe=None, broadcast_buffers=False, bucket_cap_mb=25, checkpoint_shard_count=1, checkpoint_suffix='', constraints=None, cpu=False, criterion='ctc', curriculum=0, data='/root/host/audio/', data_buffer_size=10, dataset_impl=None, ddp_backend='c10d', decoding_format=None, device_id=0, disable_validation=False, distributed_backend='nccl', distributed_init_method=None, distributed_no_spawn=False, distributed_port=-1, distributed_rank=0, distributed_world_size=1, distributed_wrapper='DDP', diverse_beam_groups=-1, diverse_beam_strength=0.5, diversity_rate=-1.0, dump_emissions=None, dump_features=None, empty_cache_freq=0, eos=2, fast_stat_sync=False, find_unused_parameters=False, finetune_from_model=None, fix_batches_to_gpus=False, fixed_validation_seed=None, force_anneal=None, fp16=False, fp16_init_scale=128, fp16_no_flatten_grads=False, fp16_scale_tolerance=0.0, fp16_scale_window=None, gen_subset='valid', iter_decode_eos_penalty=0.0, iter_decode_force_max_iter=False, iter_decode_max_iter=10, iter_decode_with_beam=1, iter_decode_with_external_reranker=False, keep_best_checkpoints=-1, keep_interval_updates=-1, keep_last_epochs=-1, kenlm_model='/root/host/model/lm_librispeech_kenlm_word_4g_200kvocab.bin', kspmodel=None, lenpen=1, lexicon='/root/host/model/librispeech_lexicon.lst', lm_path=None, lm_weight=1.5, load_emissions=None, localsgd_frequency=3, log_format=None, log_interval=100, lr_scheduler='fixed', lr_shrink=0.1, match_source_len=False, max_len_a=0, max_len_b=200, max_source_positions=9223372036854775807, max_target_positions=1024, max_tokens=4000000, max_tokens_valid=None, maximize_best_checkpoint_metric=False, memory_efficient_bf16=False, memory_efficient_fp16=False, min_len=1, min_loss_scale=0.0001, model_overrides='{}', model_parallel_size=1, nbest=1, no_beamable_mm=False, no_early_stop=False, no_epoch_checkpoints=False, no_last_checkpoints=False, no_progress_bar=False, no_repeat_ngram_size=0, no_save=False, no_save_optimizer_state=False, no_seed_provided=False, nprocs_per_node=1, num_shards=1, num_workers=1, optimizer=None, optimizer_overrides='{}', pad=1, path='/root/host/model/wav2vec_vox_960h_pl.pt', patience=-1, pipeline_balance=None, pipeline_checkpoint='never', pipeline_chunks=0, pipeline_decoder_balance=None, pipeline_decoder_devices=None, pipeline_devices=None, pipeline_encoder_balance=None, pipeline_encoder_devices=None, pipeline_model_parallel=False, post_process='word', prefix_size=0, print_alignment=False, print_step=False, profile=False, quantization_config_path=None, quiet=False, replace_unk=None, required_batch_size_multiple=8, required_seq_len_multiple=1, reset_dataloader=False, reset_logging=True, reset_lr_scheduler=False, reset_meters=False, reset_optimizer=False, restore_file='checkpoint_last.pt', results_path='/root/host/out/hypo_calls', retain_dropout=False, retain_dropout_modules=None, retain_iter_history=False, rnnt_decoding_type='greedy', rnnt_len_penalty=-0.5, sacrebleu=False, sampling=False, sampling_topk=-1, sampling_topp=-1.0, save_dir='checkpoints', save_interval=1, save_interval_updates=0, score_reference=False, scoring='bleu', seed=1, shard_id=0, sil_weight=-0.3, silence_token='\u2581', skip_invalid_size_inputs_valid_test=False, slowmo_algorithm='LocalSGD', slowmo_momentum=None, task='speech_recognition', temperature=1.0, tensorboard_logdir=None, threshold_loss_scale=None, tokenizer=None, tpu=False, train_subset='train', unit_lm=False, unk=3, unk_weight=-inf, unkpen=0, unnormalized=False, user_dir='examples/speech_recognition', valid_subset='valid', validate_after_updates=0, validate_interval=1, validate_interval_updates=0, w2l_decoder='kenlm', wandb_project=None, warmup_updates=0, wer_args=None, wer_kenlm_model=None, wer_lexicon=None, wer_lm_weight=2.0, wer_word_score=-1.0, wfstlm=None, word_score=1.5, zero_infinity=False, zero_sharding='none')
INFO:__main__:| decoding with criterion ctc
| dictionary: 221456 types
INFO:__main__:| loading model(s) from /root/host/model/wav2vec_vox_960h_pl.pt
Traceback (most recent call last):
  File "/root/fairseq/examples/speech_recognition/infer.py", line 428, in <module>
    cli_main()
  File "/root/fairseq/examples/speech_recognition/infer.py", line 424, in cli_main
    main(args)
  File "/root/fairseq/examples/speech_recognition/infer.py", line 237, in main
    state=model_state,
  File "/root/fairseq/fairseq/checkpoint_utils.py", line 269, in load_model_ensemble
    state,
  File "/root/fairseq/fairseq/checkpoint_utils.py", line 320, in load_model_ensemble_and_task
    model.load_state_dict(state["model"], strict=strict, model_cfg=cfg.model)
  File "/root/fairseq/fairseq/models/fairseq_model.py", line 115, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Wav2VecCtc:
	size mismatch for w2v_encoder.proj.weight: copying a param with shape torch.Size([32, 1024]) from checkpoint, the shape in current model is torch.Size([221456, 1024]).
	size mismatch for w2v_encoder.proj.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([221456]).

```

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. run with 

```
python3  /root/fairseq/examples/speech_recognition/infer.py /root/host/audio/ \
--task speech_recognition \
--seed 1 \
--nbest 1 \
--path /root/host/model/wav2vec_vox_960h_pl.pt \
--gen-subset valid \
--results-path /root/host/out/hypo_calls \
--w2l-decoder kenlm \
--kenlm-model /root/host/model/lm_librispeech_kenlm_word_4g_200kvocab.bin \
--lexicon /root/host/model/librispeech_lexicon.lst \
--beam 200 \
--beam-threshold 15 \
--lm-weight 1.5 \
--word-score 1.5 \
--sil-weight -0.3 \
--criterion ctc \
--user-dir examples/speech_recognition \
--post-process word
```

Please advise me, if I needed to provide additional tech details.

**Comment by mironnn** [comment]
Can somebody advise what's the issue?

**Comment by JINGZIjingzi** [comment]
I have met the similar situation, which caused by "dict.ltr.txt".

Make sure the dicts used to train/finetune and infer are the same.
