### ISSUE TITLE
TypeError: tuple indices must be integers or slices, not str when running encoder_out["encoder_out"]

### ISSUE THREAD

**Issue by ZLKong** [pytorch/fairseq#2983]
I ran command in Speech Recognition (ASR) on LibriSpeech
https://github.com/pytorch/fairseq/tree/master/examples/speech_to_text#training 
`CUDA_VISIBLE_DEVICES=1 fairseq-train /data/ --train-subset train-clean-100 --valid-subset dev-clean --save-dir /data/ --num-workers 4 --max-tokens 40000 --task speech_to_text --criterion label_smoothed_cross_entropy --max-update 300000 --arch s2t_transformer_s --optimizer adam --lr 2e-3 --lr-scheduler inverse_sqrt --warmup-updates 10000 --clip-norm 10.0 --seed 1 --update-freq 8`

and got the tuple indices error: `TypeError: tuple indices must be integers or slices, not str . ` 

It has something to do with the `encoder_out["encoder_out"] ` in transformer.py 

https://github.com/pytorch/fairseq/blob/0db28cdd0e50cad9c36e5e47ffceff40beaf6f60/fairseq/models/transformer.py#L807-L810

You can just `print(encoder_out["encoder_out"])`or  `print(len(encoder_out["encoder_out"]))` and get the same error.

**Full Traceback** 
```
Traceback (most recent call last):
File "/home/zhk20002/anaconda2/envs/ASR/bin/fairseq-train", line 33, in
sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
File "/home/zhk20002/SAM/fairseq/fairseq_cli/train.py", line 392, in cli_main
distributed_utils.call_main(cfg, main)
File "/home/zhk20002/SAM/fairseq/fairseq/distributed_utils.py", line 334, in call_main
main(cfg, **kwargs)
File "/home/zhk20002/SAM/fairseq/fairseq_cli/train.py", line 130, in main
valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
File "/home/zhk20002/anaconda2/envs/ASR/lib/python3.6/contextlib.py", line 52, in inner
return func(*args, **kwds)
File "/home/zhk20002/SAM/fairseq/fairseq_cli/train.py", line 219, in train
log_output = trainer.train_step(samples)
File "/home/zhk20002/anaconda2/envs/ASR/lib/python3.6/contextlib.py", line 52, in inner
return func(*args, **kwds)
File "/home/zhk20002/SAM/fairseq/fairseq/trainer.py", line 537, in train_step
ignore_grad=is_dummy_batch,
File "/home/zhk20002/SAM/fairseq/fairseq/tasks/fairseq_task.py", line 428, in train_step
loss, sample_size, logging_output = criterion(model, sample)
File "/home/zhk20002/anaconda2/envs/ASR/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in call
result = self.forward(*input, **kwargs)
File "/home/zhk20002/SAM/fairseq/fairseq/criterions/label_smoothed_cross_entropy.py", line 69, in forward
net_output = model(**sample["net_input"])
File "/home/zhk20002/anaconda2/envs/ASR/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in call
result = self.forward(*input, **kwargs)
File "/home/zhk20002/SAM/fairseq/fairseq/models/speech_to_text/s2t_transformer.py", line 258, in forward
prev_output_tokens=prev_output_tokens, encoder_out=encoder_out
File "/home/zhk20002/anaconda2/envs/ASR/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in call
result = self.forward(*input, **kwargs)
File "/home/zhk20002/SAM/fairseq/fairseq/models/transformer.py", line 699, in forward
alignment_heads=alignment_heads,
File "/home/zhk20002/SAM/fairseq/fairseq/models/speech_to_text/s2t_transformer.py", line 385, in extract_features
alignment_heads,
File "/home/zhk20002/SAM/fairseq/fairseq/models/transformer.py", line 810, in extract_features_scriptable
if (encoder_out is not None and len(encoder_out["encoder_out"]) > 0)
TypeError: tuple indices must be integers or slices, not str
```

**Comment by kahne** [comment]
ressolved in #2971
