### ISSUE TITLE
Errors when fine-tune Wav2Vec 2.0 Base Model. Config mismatch

### ISSUE THREAD

**Issue by mailong25** [pytorch/fairseq#3005]
## 🐛 Bug

omegaconf.errors.ConfigAttributeError: Key 'normalize' is not in struct

### To Reproduce

1. Run cmd '....'

fairseq-hydra-train task.data=/mnt/disks2/wav2vec/dataset distributed_training.distributed_world_size=2 +optimization.update_freq='[12]' model.w2v_path=/mnt/disks2/wav2vec/wav2vec_small_vie.pt dataset.num_workers=8 dataset.valid_subset=valid --config-dir /mnt/disks2/wav2vec/fairseq/examples/wav2vec/config/finetuning --config-name base_100h

2. See error

2020-12-08 17:44:50 | INFO | fairseq.distributed_utils | distributed init (rank 1): tcp://localhost:15186
2020-12-08 17:44:50 | INFO | fairseq.distributed_utils | distributed init (rank 0): tcp://localhost:15186
2020-12-08 17:44:51 | INFO | fairseq.distributed_utils | initialized host longsg-vm.c.vnlp-tts.internal as rank 1
2020-12-08 17:44:51 | INFO | fairseq.distributed_utils | initialized host longsg-vm.c.vnlp-tts.internal as rank 0
2020-12-08 17:44:56 | INFO | fairseq_cli.train | {'_name': None, 'common': {'_name': None, 'no_progress_bar': False, 'log_interval': 200, 'log_format': 'json', 'tensorboard_logdir': None, 'wandb_project': None, 'seed': 1, 'cpu': False, 'tpu': False, 'bf16': False, 'memory_efficient_bf16': False, 'fp16': True, 'memory_efficient_fp16': False, 'fp16_no_flatten_grads': False, 'fp16_init_scale': 128, 'fp16_scale_window': None, 'fp16_scale_tolerance': 0.0, 'min_loss_scale': 0.0001, 'threshold_loss_scale': None, 'user_dir': None, 'empty_cache_freq': 0, 'all_gather_list_size': 16384, 'model_parallel_size': 1, 'quantization_config_path': None, 'profile': False, 'reset_logging': True}, 'common_eval': {'_name': None, 'path': None, 'post_process': None, 'quiet': False, 'model_overrides': '{}', 'results_path': None}, 'distributed_training': {'_name': None, 'distributed_world_size': 2, 'distributed_rank': 0, 'distributed_backend': 'nccl', 'distributed_init_method': 'tcp://localhost:15186', 'distributed_port': -1, 'device_id': 0, 'distributed_no_spawn': False, 'ddp_backend': 'no_c10d', 'bucket_cap_mb': 25, 'fix_batches_to_gpus': False, 'find_unused_parameters': False, 'fast_stat_sync': False, 'broadcast_buffers': False, 'distributed_wrapper': 'DDP', 'slowmo_momentum': None, 'slowmo_algorithm': 'LocalSGD', 'localsgd_frequency': 3, 'nprocs_per_node': 2, 'pipeline_model_parallel': False, 'pipeline_balance': None, 'pipeline_devices': None, 'pipeline_chunks': 0, 'pipeline_encoder_balance': None, 'pipeline_encoder_devices': None, 'pipeline_decoder_balance': None, 'pipeline_decoder_devices': None, 'pipeline_checkpoint': 'never', 'zero_sharding': 'none', 'tpu': False, 'distributed_num_procs': 2}, 'dataset': {'_name': None, 'num_workers': 8, 'skip_invalid_size_inputs_valid_test': True, 'max_tokens': 3200000, 'batch_size': None, 'required_batch_size_multiple': 8, 'required_seq_len_multiple': 1, 'dataset_impl': None, 'data_buffer_size': 10, 'train_subset': 'train', 'valid_subset': 'valid', 'validate_interval': 1, 'validate_interval_updates': 0, 'validate_after_updates': 0, 'fixed_validation_seed': None, 'disable_validation': False, 'max_tokens_valid': 3200000, 'batch_size_valid': None, 'curriculum': 0, 'gen_subset': 'test', 'num_shards': 1, 'shard_id': 0}, 'optimization': {'_name': None, 'max_epoch': 0, 'max_update': 80000, 'stop_time_hours': 0.0, 'clip_norm': 0.0, 'sentence_avg': True, 'update_freq': [12], 'lr': [3e-05], 'stop_min_lr': -1.0, 'use_bmuf': False}, 'checkpoint': {'_name': None, 'save_dir': 'checkpoints', 'restore_file': 'checkpoint_last.pt', 'finetune_from_model': None, 'reset_dataloader': False, 'reset_lr_scheduler': False, 'reset_meters': False, 'reset_optimizer': False, 'optimizer_overrides': '{}', 'save_interval': 1, 'save_interval_updates': 0, 'keep_interval_updates': -1, 'keep_last_epochs': -1, 'keep_best_checkpoints': -1, 'no_save': False, 'no_epoch_checkpoints': True, 'no_last_checkpoints': False, 'no_save_optimizer_state': False, 'best_checkpoint_metric': 'wer', 'maximize_best_checkpoint_metric': False, 'patience': -1, 'checkpoint_suffix': '', 'checkpoint_shard_count': 1, 'load_checkpoint_on_all_dp_ranks': False, 'model_parallel_size': 1, 'distributed_rank': 0}, 'bmuf': {'_name': None, 'block_lr': 1.0, 'block_momentum': 0.875, 'global_sync_iter': 50, 'warmup_iterations': 500, 'use_nbm': False, 'average_sync': False, 'distributed_world_size': 2}, 'generation': {'_name': None, 'beam': 5, 'nbest': 1, 'max_len_a': 0.0, 'max_len_b': 200, 'min_len': 1, 'match_source_len': False, 'unnormalized': False, 'no_early_stop': False, 'no_beamable_mm': False, 'lenpen': 1.0, 'unkpen': 0.0, 'replace_unk': None, 'sacrebleu': False, 'score_reference': False, 'prefix_size': 0, 'no_repeat_ngram_size': 0, 'sampling': False, 'sampling_topk': -1, 'sampling_topp': -1.0, 'constraints': None, 'temperature': 1.0, 'diverse_beam_groups': -1, 'diverse_beam_strength': 0.5, 'diversity_rate': -1.0, 'print_alignment': False, 'print_step': False, 'lm_path': None, 'lm_weight': 0.0, 'iter_decode_eos_penalty': 0.0, 'iter_decode_max_iter': 10, 'iter_decode_force_max_iter': False, 'iter_decode_with_beam': 1, 'iter_decode_with_external_reranker': False, 'retain_iter_history': False, 'retain_dropout': False, 'retain_dropout_modules': None, 'decoding_format': None, 'no_seed_provided': False}, 'eval_lm': {'_name': None, 'output_word_probs': False, 'output_word_stats': False, 'context_window': 0, 'softmax_batch': 9223372036854775807}, 'interactive': {'_name': None, 'buffer_size': 0, 'input': '-'}, 'model': {'_name': 'wav2vec_ctc', 'w2v_path': '/mnt/disks2/wav2vec/wav2vec_small_vie.pt', 'apply_mask': True, 'mask_prob': 0.65, 'mask_channel_prob': 0.5, 'mask_channel_length': 64, 'layerdrop': 0.1, 'activation_dropout': 0.1, 'feature_grad_mult': 0.0, 'freeze_finetune_updates': 0}, 'task': {'_name': 'audio_pretraining', 'data': '/mnt/disks2/wav2vec/dataset', 'normalize': False, 'labels': 'ltr'}, 'criterion': {'_name': 'ctc', 'zero_infinity': True}, 'optimizer': {'_name': 'adam', 'adam_betas': '(0.9,0.98)', 'adam_eps': 1e-08}, 'lr_scheduler': {'_name': 'tri_stage', 'phase_ratio': [0.1, 0.4, 0.5], 'final_lr_scale': 0.05}, 'scoring': None, 'bpe': None, 'tokenizer': None}
2020-12-08 17:44:56 | INFO | fairseq.data.audio.raw_audio_dataset | loaded 688, skipped 0 samples
2020-12-08 17:44:56 | INFO | wandb.sdk.internal.internal | Internal process exited
Traceback (most recent call last):
  File "/mnt/disks2/wav2vec/fairseq/fairseq_cli/hydra_train.py", line 38, in hydra_main
    distributed_utils.call_main(cfg, pre_main)
  File "/mnt/disks2/wav2vec/fairseq/fairseq/distributed_utils.py", line 320, in call_main
    cfg.distributed_training.distributed_world_size,
  File "/mnt/disks2/miniconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/mnt/disks2/miniconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/mnt/disks2/miniconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/mnt/disks2/miniconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/mnt/disks2/wav2vec/fairseq/fairseq/distributed_utils.py", line 302, in distributed_main
    main(cfg, **kwargs)
  File "/mnt/disks2/wav2vec/fairseq/fairseq_cli/train.py", line 74, in main
    model = task.build_model(cfg.model)
  File "/mnt/disks2/wav2vec/fairseq/fairseq/tasks/audio_pretraining.py", line 201, in build_model
    model = super().build_model(model_cfg)
  File "/mnt/disks2/wav2vec/fairseq/fairseq/tasks/fairseq_task.py", line 282, in build_model
    model = models.build_model(cfg, self)
  File "/mnt/disks2/wav2vec/fairseq/fairseq/models/__init__.py", line 96, in build_model
    return model.build_model(cfg, task)
  File "/mnt/disks2/wav2vec/fairseq/fairseq/models/wav2vec/wav2vec2_asr.py", line 147, in build_model
    w2v_encoder = Wav2VecEncoder(cfg, task.target_dictionary)
  File "/mnt/disks2/wav2vec/fairseq/fairseq/models/wav2vec/wav2vec2_asr.py", line 292, in __init__
    assert cfg.normalize == w2v_args.task.normalize, (
  File "/mnt/disks2/miniconda3/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 297, in __getattr__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/mnt/disks2/miniconda3/lib/python3.7/site-packages/omegaconf/base.py", line 101, in _format_and_raise
    type_override=type_override,
  File "/mnt/disks2/miniconda3/lib/python3.7/site-packages/omegaconf/_utils.py", line 629, in format_and_raise
    _raise(ex, cause)
  File "/mnt/disks2/miniconda3/lib/python3.7/site-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
  File "/mnt/disks2/miniconda3/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 295, in __getattr__
    return self._get_impl(key=key, default_value=DEFAULT_VALUE_MARKER)
  File "/mnt/disks2/miniconda3/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 353, in _get_impl
    node = self._get_node(key=key)
  File "/mnt/disks2/miniconda3/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 375, in _get_node
    self._validate_get(key)
  File "/mnt/disks2/miniconda3/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 128, in _validate_get
    key=key, value=value, cause=ConfigAttributeError(msg)
  File "/mnt/disks2/miniconda3/lib/python3.7/site-packages/omegaconf/base.py", line 101, in _format_and_raise
    type_override=type_override,
  File "/mnt/disks2/miniconda3/lib/python3.7/site-packages/omegaconf/_utils.py", line 694, in format_and_raise
    _raise(ex, cause)
  File "/mnt/disks2/miniconda3/lib/python3.7/site-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.ConfigAttributeError: Key 'normalize' is not in struct
	full_key: task.normalize
	reference_type=Any
	object_type=dict

### Environment

 - fairseq Version (1.0.0a0+4817a91):
 - PyTorch Version (1.6)
 - OS ( Linux):
 - How you installed fairseq (pip install --editable ./):
 - Build command you used (if compiling from source):
 - Python version:3.7.6
 - CUDA/cuDNN version:10.1
 - GPU models and configuration:Tesla V100
 - Any other relevant information:

**Comment by mailong25** [comment]
It's seen that the code written in fairseq/models/wav2vec/wav2vec2_asr.py is for the wav2vec_large model only.
I saw mismatchs between the wav2vec_base config with the coden in wav2vec2_asr.py file:

This [line](https://github.com/pytorch/fairseq/blob/feb5f07ff4220b7908ff12c6692685784c7c9a71/fairseq/models/wav2vec/wav2vec2_asr.py#L292)
assert cfg.normalize == w2v_args.task.normalize, (
            "Fine-tuning works best when data normalization is the same. "
            "Please check that --normalize is set or unset for both pre-training and here"
        )

the normalize arg was not introduce in the wav2vec_base config file

This [line](https://github.com/pytorch/fairseq/blob/feb5f07ff4220b7908ff12c6692685784c7c9a71/fairseq/models/wav2vec/wav2vec2_asr.py#L308)
 d = w2v_args.model.encoder_embed_dim

the encoder_embed_dim arg was not introduce in the wav2vec_base config file

**Comment by kwasnydam** [comment]
I actually updated to master recently (commit a700e14ea3cbf3e99ca729caa30b5b1c0305c4c4), hoping that some of the problems with fine-tuning I had before would disappear and I encountered the same exact problem as you, i.e. a small base model trained from scratch crashes on ctc finetuning due to the configuration mismatch and exactly the same config entires are missing in my case.

**Comment by yaguanghu** [comment]
I met the same problem, have you solved it now?

**Comment by kwasnydam** [comment]
For now, I added these keys to the config I used for training the base model:
```
model:
  _name: wav2vec2
  quantize_targets: true
  final_dim: 256
  encoder_layerdrop: 0.05
  dropout_input: 0.1
  dropout_features: 0.1
  dropout: 0.1
  attention_dropout: 0.1
  feature_grad_mult: 0.1

  encoder_layers: 12
  encoder_embed_dim: 768
  encoder_ffn_embed_dim: 3072
  encoder_attention_heads: 12
``` 
(values taken from defaults specified in https://github.com/pytorch/fairseq/blob/master/fairseq/models/wav2vec/wav2vec2.py)
and then restarted the pretraining from the checkpoint directory (with `checkpoint.save_dir` CLI entry to `fairseq-hydra-train`). I then waited for a new checkpoint to be saved and used this checkpoint for ctc fine-tuning. The fine-tuning code now works, though on the default settings I ran into an OOM so now I restart (hoped that on 25GB RTX3090 I can afford default settings but does not seem so :P )

**Comment by mailong25** [comment]
I also experienced some problems during inference, caused by the script in fairseq/tasks/audio_pretraining

```
        manifest = os.path.join(data_path, "{}.tsv".format(split))
        self.datasets[split] = FileAudioDataset(
            manifest,
            sample_rate=task_cfg.sample_rate,
            max_sample_size=self.cfg.max_sample_size,
            min_sample_size=self.cfg.max_sample_size,
            min_length=self.cfg.min_sample_size,
            pad=task_cfg.labels is not None or task_cfg.enable_padding,
            normalize=task_cfg.normalize,
        )
```
sample_rate and normalize are not attributes of task_cfg, so I fix it by:
```
sample_rate=task_cfg.sample_rate ---> sample_rate=self.cfg.sample_rate
normalize=False
```
and also:

```
# upgrade old task
if isinstance(task_cfg, Namespace):
    if not hasattr(task_cfg, "autoregressive"):
        task_cfg.autoregressive = not task_cfg.criterion == 'ctc'
```
task_cfg was not isinstance of Namespace. Therefore, task_cfg.autoregressive is not set after the above code, which caused some errors later. I fix it by removing the "if " condition:

`task_cfg.autoregressive = not task_cfg.criterion == 'ctc'`

**Comment by abirkorched** [comment]
I solved this problem by adding parameters to the pre-training configuration file:

```

task:
  _name: audio_pretraining
  data:???
  max_sample_size: 250000
  min_sample_size: 32000
  **normalize: true**

model:
  _name: wav2vec2
  quantize_targets: true
  final_dim: 256
  encoder_layerdrop: 0.05
  dropout_input: 0.1
  dropout_features: 0.1
  dropout: 0.1
  attention_dropout: 0.1
  feature_grad_mult: 0.1
  **encoder_embed_dim: 768**
```

**Comment by AmirHussein96** [comment]
> I also experienced some problems during inference, caused by the script in fairseq/tasks/audio_pretraining
> 
> ```
>         manifest = os.path.join(data_path, "{}.tsv".format(split))
>         self.datasets[split] = FileAudioDataset(
>             manifest,
>             sample_rate=task_cfg.sample_rate,
>             max_sample_size=self.cfg.max_sample_size,
>             min_sample_size=self.cfg.max_sample_size,
>             min_length=self.cfg.min_sample_size,
>             pad=task_cfg.labels is not None or task_cfg.enable_padding,
>             normalize=task_cfg.normalize,
>         )
> ```
> 
> sample_rate and normalize are not attributes of task_cfg, so I fix it by:
> 
> ```
> sample_rate=task_cfg.sample_rate ---> sample_rate=self.cfg.sample_rate
> normalize=False
> ```
> 
> and also:
> 
> ```
> # upgrade old task
> if isinstance(task_cfg, Namespace):
>     if not hasattr(task_cfg, "autoregressive"):
>         task_cfg.autoregressive = not task_cfg.criterion == 'ctc'
> ```
> 
> task_cfg was not isinstance of Namespace. Therefore, task_cfg.autoregressive is not set after the above code, which caused some errors later. I fix it by removing the "if " condition:
> 
> `task_cfg.autoregressive = not task_cfg.criterion == 'ctc'`

Hi @mailong25 , I finetuned the base wav2vec model and got similar issues that you mentioned. Thank you for pointing how to solve them. However after removing the if statement for the autoregressive part `task_cfg.autoregressive = not task_cfg.criterion == 'ctc'` I get `Key 'criterion' is not in struct`.  I am running the following command for inference without LM model : 

python examples/speech_recognition/infer.py examples/wav2vec/data/ --task audio_pretraining --nbest 1 --path examples/wav2vec/outputs/2021-01-03/21-08-21/checkpoints/checkpoint_best.pt --gen-subset dev_other --results-path examples/wav2vec/results/ --word-score -1 --sil-weight 0 --criterion ctc --labels ltr --max-tokens 4000000 --post-process letter

Also, did you have to use the LM model or you can do inference without LM?

**Comment by mailong25** [comment]
You can set` task_cfg.autoregressive = False`

For inference without LM, you can use the viterbi decoder
`python examples/speech_recognition/infer.py examples/wav2vec/data/ --task audio_pretraining --nbest 1 --path examples/wav2vec/outputs/2021-01-03/21-08-21/checkpoints/checkpoint_best.pt --gen-subset dev_other --results-path examples/wav2vec/results/ --w2l-decoder viterbi --word-score -1 --sil-weight 0 --criterion ctc --labels ltr --max-tokens 4000000 --post-process letter
`

**Comment by harveenchadha** [comment]
Note: this is for the base model

If you have already trained your model, as a quick fix do the following:

In wav2vec2_asr.py file, comment out lines from 310-313


```
assert cfg.normalize == w2v_args.task.normalize, (
"Fine-tuning works best when data normalization is the same. "
"Please check that --normalize is set or unset for both pre-training and here"
)
```

On line 326 change:

```
d = w2v_args.model.encoder_embed_dim  --> d = 768
```

**Comment by alexeib** [comment]
@myleott is landing a fix for this, but in general this issue shouldnt happen anymore since we landed another fix that adds default parameters into config (that gets saved into checkpoint) for new models

re: 
```
assert cfg.normalize == w2v_args.task.normalize, (
"Fine-tuning works best when data normalization is the same. "
"Please check that --normalize is set or unset for both pre-training and here"
)
```

if you remove this check because a param is missing in the checkpoint, then make sure normalization is actually used in the same way for pre-training and finetuning. you will see that the models still kinda work when its mismatched, but with some accuracy degradation
