### ISSUE TITLE
An error occurs when finetune wav2vec 2.0 with hydra-train

### ISSUE THREAD

**Issue by monhoney** [pytorch/fairseq#3008]
## 🐛 Bug

I am trying to finetuning using the wav2vec 2.0 base pretrained model. 
I downloaded the wav2vec_small_100h.pt model and changed the name to wav2vec_small.pt.
I ran finetune according to the manual, but the following error occurs:

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd 
```
fairseq-hydra-train \
    distributed_training.distributed_port=22000 \
    task.data=/work/volumes/manifest \
    model.w2v_path=/work/volumes/pretrained_model/wav2vec_small.pt \
    --config-dir /work/fairseq/examples/wav2vec/config/finetuning \
    --config-name base_100h
```

2. See error

```
Traceback (most recent call last):
  File "/opt/conda/bin/fairseq-hydra-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-hydra-train')())
  File "/work/fairseq/fairseq_cli/hydra_train.py", line 66, in cli_main
    hydra_main()
  File "/opt/conda/lib/python3.6/site-packages/hydra/main.py", line 37, in decorated_main
    strict=strict,
  File "/opt/conda/lib/python3.6/site-packages/hydra/_internal/utils.py", line 347, in _run_hydra
    lambda: hydra.run(
  File "/opt/conda/lib/python3.6/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/opt/conda/lib/python3.6/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/opt/conda/lib/python3.6/site-packages/hydra/_internal/utils.py", line 350, in <lambda>
    overrides=args.overrides,
  File "/opt/conda/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 112, in run
    configure_logging=with_log_configuration,
  File "/opt/conda/lib/python3.6/site-packages/hydra/core/utils.py", line 125, in run_job
    ret.return_value = task_function(task_cfg)
  File "/work/fairseq/fairseq_cli/hydra_train.py", line 38, in hydra_main
    distributed_utils.call_main(cfg, pre_main)
  File "/work/fairseq/fairseq/distributed_utils.py", line 334, in call_main
    main(cfg, **kwargs)
  File "/work/fairseq/fairseq_cli/train.py", line 74, in main
    model = task.build_model(cfg.model)
  File "/work/fairseq/fairseq/tasks/audio_pretraining.py", line 201, in build_model
    model = super().build_model(model_cfg)
  File "/work/fairseq/fairseq/tasks/fairseq_task.py", line 282, in build_model
    model = models.build_model(cfg, self)
  File "/work/fairseq/fairseq/models/__init__.py", line 86, in build_model
    return model.build_model(cfg, task)
  File "/work/fairseq/fairseq/models/wav2vec/wav2vec2_asr.py", line 147, in build_model
    w2v_encoder = Wav2VecEncoder(cfg, task.target_dictionary)
  File "/work/fairseq/fairseq/models/wav2vec/wav2vec2_asr.py", line 304, in __init__
    model.remove_pretraining_modules()
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 779, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'Wav2VecCtc' object has no attribute 'remove_pretraining_modules'
```

### Environment

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): pip install --editable ./
 - Build command you used (if compiling from source):
 - Python version: 
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by monhoney** [comment]
I read this link(https://github.com/pytorch/fairseq/issues/2539#issuecomment-683292257) and it worked. Thank you.

**Comment by Esdsnqxz** [comment]
hi @monhoney,i'm facing the same problem as above, how do you solve it?

**Comment by monhoney** [comment]
> hi @monhoney,i'm facing the same problem as above, how do you solve it?

To do fine tune, you need to download and use the no-finetune model in model.w2v_path.

**Comment by jinggaizi** [comment]
Does it work if use feature encoder representations to feed  to a separate downstream model。

**Comment by Mayankd2019** [comment]
hi @monhoney facing same  issue . The comment that you mentioned also asks to set various --reset-x flags as well so what did you for  that?
