### ISSUE TITLE
can't open input file `CoVoST/fr/raw/clips/common_voice_fr_19528232.mp3'

### ISSUE THREAD

**Issue by pyyush** [pytorch/fairseq#3026]
### To Reproduce

1. Run cmd 'python3 examples/speech_to_text/prep_covost_data.py --data-root CoVoST --vocab-type char --src-lang fr --tgt-lang en'
2. See error - formats: can't open input file `CoVoST/fr/raw/clips/common_voice_fr_19528232.mp3': 
 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                         | 168928/207374 [1:04:51<14:45, 43.41it/s]
Traceback (most recent call last):
  File "examples/speech_to_text/prep_covost_data.py", line 290, in <module>
    main()
  File "examples/speech_to_text/prep_covost_data.py", line 286, in main
    process(args)
  File "examples/speech_to_text/prep_covost_data.py", line 222, in process
    for waveform, sample_rate, _, _, _, utt_id in tqdm(dataset):
  File "/usr/local/lib/python3.7/site-packages/tqdm/std.py", line 1129, in __iter__
    for obj in iterable:
  File "examples/speech_to_text/prep_covost_data.py", line 201, in __getitem__
    waveform, sample_rate = torchaudio.load(path)
  File "/usr/local/lib/python3.7/site-packages/torchaudio/backend/sox_backend.py", line 56, in load
    filetype
RuntimeError: Error opening audio file

**Comment by cromz22** [comment]
I have encountered the same problem (https://github.com/pytorch/fairseq/issues/2971).
That is because the CoVoST2 dataset contains some empty clips.
I used this script to remove the empty clips.
https://gist.github.com/cromz22/2fd6878e06efeba99a6e7cbdebf68217
Hope this is helpful!

**Comment by kahne** [comment]
@pyyush and @cromz22, thanks for reporting this issue! Yes, this is due to the empty audios in Common Voice. We can skip them by performing filtering in [L173](https://github.com/pytorch/fairseq/blob/master/examples/speech_to_text/prep_covost_data.py#L173). I will update the code shortly.

@cromz22, thanks for sharing your script!
