### ISSUE TITLE
Reuse dictionary  in preprocess

### ISSUE THREAD

**Issue by patelrajnath** [pytorch/fairseq#303]
Hi, I'm trying to reuse the dictionary to preprocess the data for fine-tuning. It complains about the following error.

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/fairseq-0.5.0-py3.6-linux-x86_64.egg/fairseq/preprocess.py", line 215, in <module>
    main(args)
  File "/usr/local/lib/python3.6/dist-packages/fairseq-0.5.0-py3.6-linux-x86_64.egg/fairseq/preprocess.py", line 109, in main
    padding_factor=args.padding_factor,
  File "/usr/local/lib/python3.6/dist-packages/fairseq-0.5.0-py3.6-linux-x86_64.egg/fairseq/data/dictionary.py", line 138, in finalize
    assert len(new_symbols) == len(new_indices)
AssertionError

**Comment by edunov** [comment]
@patelrajnath can you please share the exact command that results in this error and if possible the dictionary that you're trying to reuse?

**Comment by patelrajnath** [comment]
@edunov 
I guess the issue is that it is loading the special symbols twice. One instance of the special symbols is already there (in the dict being loaded) and another one is added when it loads the dictionary as it creates a new instance of the Dictionary class.

**Comment by patelrajnath** [comment]
The command I used is-
python3.6 preprocess.py \
	--source-lang en \
	--target-lang ja \
	--trainpref $datadir/$train.bpe.terms.clean \
	--validpref $datadir/$dev.bpe.clean \
	--testpref $datadir/$test.bpe.clean \
	--destdir ${datadirbin} \
	--srcdict $dirdicts/dict.$src.txt \
	--tgtdict $dirdicts/dict.$tgt.txt

**Comment by edunov** [comment]
@patelrajnath it shouldn't save any special symbols, check this line: 
https://github.com/pytorch/fairseq/blob/master/fairseq/data/dictionary.py#L195 

Can you paste here first and last 10 lines of your dictionary?

**Comment by patelrajnath** [comment]
@edunov 
Head of the dict-
<Lua heritage> 1
<pad> 1
</s> 2879723
<unk> 1
the 5841384
, 4352359
. 2941212
of 2837124
a 2572250
to 1776576

Tail of the dict-
rainfall 1
※ 1
 1
hiro@@ 1
 ⃝ 1
‹ 1
山 1
zt 1
embank@@ 1
⇔ 1
thwise 1
madeupword0000 0
madeupword0001 0
madeupword0002 0
madeupword0003 0

**Comment by edunov** [comment]
These thirst 4 lines are very strange: 
1
1
2879723
1

Are there some non-printable characters? How did you generate this file?

**Comment by patelrajnath** [comment]
Rendering issue with the symbols in angle bracket.
`<Lua heritage>` 1
`<pad>` 1
`</s>` 2879723
`<unk>` 1

**Comment by edunov** [comment]
These things shouldn't be in the file in the first place. I'm not sure how did they get in there. How did you generate this dictionary? Can you try re-generating it using clean code from fairseq master?

**Comment by patelrajnath** [comment]
Yes, you are right. With the updated code these symbols are not there. I'll try with the updated code if it works.
