### ISSUE TITLE
'Missing/Unexpected key(s) in state_dict:' while prunning layers from BART large

### ISSUE THREAD

**Issue by pdzong** [pytorch/fairseq#3037]
## 🐛 Bug

While setting 'layers_to_keep' parameter it might lead to Missing/Unexpected keys in state_dict. Problem occurs only in bart.large (bart.base works fine) and only if layers selected to keep are not in a sequence. For **--decoder-layers-to-keep 0,1,2,3,4** works ok, but **--decoder-layers-to-keep 0,1,2,3,5** leads to this issue. As mentioned, same config but for bart.base works correctly. 

It is just my guess, but it looks like some inconsistency in 'upgrade_state_dict' executed during state_dict loading in BaseFairseqModel. While loading bart.base 'upgrade_state_dict' does not change 'state_dict' at all, for bart.large some parameters/layers are added. 

### To Reproduce

1. Run:

```
python $FAIRSEQ_PATH/fairseq_cli/train.py $DATA \
    --restore-file bart.large/model.pt \
    --max-tokens 512 \
    --batch-size 16 \
    --task translation \
    --source-lang source --target-lang target \
    --layernorm-embedding \
    --share-all-embeddings \
    --share-decoder-input-output-embed \
    --reset-optimizer --reset-dataloader --reset-meters \
    --required-batch-size-multiple 1 \
    --arch bart_large \
    --criterion label_smoothed_cross_entropy \
    --label-smoothing 0.1 \
    --decoder-layerdrop 0.1 \
    --encoder-layers-to-keep 0,1,2,3,4,5,6,7,8,9,10,11 --decoder-layers-to-keep 0,1,2,3,5 \
    --dropout 0.1 --attention-dropout 0.1 \
    --weight-decay 0.01 --optimizer adam --adam-betas "(0.9, 0.999)" --adam-eps 1e-08 \
    --clip-norm 0.1 \
    --lr-scheduler polynomial_decay --lr 1e-5 --warmup-updates 100 --total-num-update 10000 --power 1.0 \
    --fp16 --update-freq 1 \
    --skip-invalid-size-inputs-valid-test\
    --max-epoch 10 \
    --seed 42 \
    --no-epoch-checkpoints \
    --find-unused-parameters;
```

2. See error

```
RuntimeError: Error(s) in loading state_dict for BARTModel:
	Missing key(s) in state_dict: "decoder.layers.4.self_attn.k_proj.weight", "decoder.layers.4.self_attn.k_proj.bias", "decoder.layers.4.self_attn.v_proj.weight", "decoder.layers.4.self_attn.v_proj.bias", "decoder.layers.4.self_attn.q_proj.weight", "decoder.layers.4.self_attn.q_proj.bias", "decoder.layers.4.encoder_attn.k_proj.weight", "decoder.layers.4.encoder_attn.k_proj.bias", "decoder.layers.4.encoder_attn.v_proj.weight", "decoder.layers.4.encoder_attn.v_proj.bias", "decoder.layers.4.encoder_attn.q_proj.weight", "decoder.layers.4.encoder_attn.q_proj.bias". 
	Unexpected key(s) in state_dict: "decoder.layers.4.self_attn.in_proj_weight", "decoder.layers.4.self_attn.in_proj_bias", "decoder.layers.4.encoder_attn.in_proj_weight", "decoder.layers.4.encoder_attn.in_proj_bias". 
```

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kpajak/virtualenvs/python3.7.6/lib/python3.7/site-packages/fairseq_cli/train.py", line 356, in <module>
    cli_main()
  File "/home/kpajak/virtualenvs/python3.7.6/lib/python3.7/site-packages/fairseq_cli/train.py", line 352, in cli_main
    distributed_utils.call_main(args, main)
  File "/home/kpajak/virtualenvs/python3.7.6/lib/python3.7/site-packages/fairseq/distributed_utils.py", line 301, in call_main
    main(args, **kwargs)
  File "/home/kpajak/virtualenvs/python3.7.6/lib/python3.7/site-packages/fairseq_cli/train.py", line 114, in main
    disable_iterator_cache=task.has_sharded_data("train"),
  File "/home/kpajak/virtualenvs/python3.7.6/lib/python3.7/site-packages/fairseq/checkpoint_utils.py", line 193, in load_checkpoint
    reset_meters=reset_meters,
  File "/home/kpajak/virtualenvs/python3.7.6/lib/python3.7/site-packages/fairseq/trainer.py", line 293, in load_checkpoint
    "please ensure that the architectures match.".format(filename)
Exception: Cannot load model parameters from checkpoint bart.large/model.pt; please ensure that the architectures match.
```

### Environment

 - fairseq Version: 0.10.1
 - PyTorch Version: 1.7 
 - OS: Debian 4.19.160-2
 - How you installed fairseq: pip
 - Python version: 3.7.6
 - CUDA/cuDNN version: 11

**Comment by Shengqiang-Zhang** [comment]
I have the same problem, is there any solution now?

**Comment by kurtabela** [comment]
Was any solution to this ever found?

**Comment by AlexNLP** [comment]
Wishing some wisdom aaaaa!
