### ISSUE TITLE
TypeError: forward() missing 1 required positional argument: 'tgt_tokens' Levenshtein Transformer

### ISSUE THREAD

**Issue by JustCunn** [pytorch/fairseq#3049]
Like the title, I experience this error when the model does its first forward pass when training a machine translation model;

```
Traceback (most recent call last):
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/fairseq_cli/train.py", line 296, in distributed_main
    main(args, init_distributed=True)
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/fairseq_cli/train.py", line 86, in main
    train(args, trainer, task, epoch_itr)
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/fairseq_cli/train.py", line 127, in train
    log_output = trainer.train_step(samples)
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/fairseq/trainer.py", line 330, in train_step
    sample, self.model, self.criterion, self.optimizer, ignore_grad
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/fairseq/tasks/fairseq_task.py", line 251, in train_step
    loss, sample_size, logging_output = criterion(model, sample)
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/fairseq/criterions/label_smoothed_cross_entropy.py", line 56, in forward
    net_output = model(**sample['net_input'])
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 511, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/ichec/home/users/aistrigh/.conda/envs/jupyter_tools/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'tgt_tokens'

```
 This is my config;
```
fairseq-train data-bin-0507-clean/AistNMT \
	--lr 5e-4 \
	--lr-scheduler inverse_sqrt \
	--optimizer adam\
  	--clip-norm 0.1 \
	--dropout 0.1 \
	--max-tokens 4096 \
  	--arch levenshtein_transformer \
        --encoder-learned-pos \
        --decoder-learned-pos \
	--fp16 \
        --criterion label_smoothed_cross_entropy \
        --encoder-layers 6 \
        --decoder-layers 6 \
        --adam-betas '(0.9,0.98)' \
        --label-smoothing 0.1 \
        --adam-eps 10e-9 \
        --warmup-updates 4000 \
        --warmup-init-lr '1e-07' \
```
 - fairseq Version (e.g., 1.0 or master): 1.0
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux): linux
 - How you installed fairseq (`pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by h-sugi** [comment]
try --criterion nat_loss and --task translation_lev. Maybe you should build_ext in fairseq directory.
The nat_loss option seems to be a key.

**Comment by Onkar-2803** [comment]
bump

**Comment by seongjunyun** [comment]
bump
