### ISSUE TITLE
Fine tuning stopping after 1 epoch

### ISSUE THREAD

**Issue by hassani24** [pytorch/fairseq#3132]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
During fine tuning, the training is stopping after 1 epoch and the output is only indicating "^C"
#### Code

running in a google colab enrironment

!python {FAIRSEQ} {DATADIR}  \
  --encoder-normalize-before --decoder-normalize-before \
  --arch "mbart_large" --layernorm-embedding \
  --task "translation_from_pretrained_bart" \
  --source-lang {SRC} --target-lang {TGT} \
  --criterion "label_smoothed_cross_entropy" --label-smoothing 0.2 \
  --optimizer "adam" --adam-eps 1e-06 --adam-betas '(0.9, 0.98)' \
  --lr-scheduler "polynomial_decay" --lr 3e-05 --warmup-updates 2500 --total-num-update 40000 \
  --dropout 0.3 --attention-dropout 0.1 --weight-decay 0.0 \
  --max-tokens 1024 --update-freq 2 \
  --save-interval 1 --save-interval-updates 5000 --keep-interval-updates 10 --no-epoch-checkpoints \
  --seed 222 --log-format "simple" --log-interval 2 \
  --restore-file {PRETRAIN} \
  --reset-optimizer --reset-meters --reset-dataloader --reset-lr-scheduler \
  --langs {langs} \
  --ddp-backend "no_c10d"

#### What have you tried?
tried changing the -no-stop-lr to -1 and 1e-10.  -1 performed the same as above.  

only deviation from the instructions is that I used the sentencepiece python import to tokenize the text instead of installing the c++ build and running externally to my code.

import sentencepiece as spm

spm.SentencePieceTrainer.train('--input={}/{}.{} --model_prefix={}/{}.spm.{}'.format(DATA, TRAIN, SRC, DATA, TRAIN, SRC ))
spm.SentencePieceTrainer.train('--input={}/{}.{} --model_prefix={}/{}.spm.{}'.format(DATA, TRAIN, TGT, DATA, TRAIN, TGT ))
spm.SentencePieceTrainer.train('--input={}/{}.{} --model_prefix={}/{}.spm.{}'.format(DATA, VALID, SRC, DATA, VALID, SRC ))
spm.SentencePieceTrainer.train('--input={}/{}.{} --model_prefix={}/{}.spm.{}'.format(DATA, VALID, TGT, DATA, VALID, TGT ))
spm.SentencePieceTrainer.train('--input={}/{}.{} --model_prefix={}/{}.spm.{}'.format(DATA, TEST, SRC, DATA, TEST, SRC ))
spm.SentencePieceTrainer.train('--input={}/{}.{} --model_prefix={}/{}.spm.{}'.format(DATA, TEST, TGT, DATA, TEST, TGT ))

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master):
 - ---master
 - PyTorch Version (e.g., 1.0)
 - ---1.7.0+cu101
 - OS (e.g., Linux):
 --- colab, linux
 - How you installed fairseq (`pip`, source):
 --- installed fairseq through the git repo (cloned and pip installed the directory)
 - Build command you used (if compiling from source):
 - Python version:
 - ---3.6.9
 - CUDA/cuDNN version:
---- - release 10.1, V10.1.243
 - GPU models and configuration:
 - Any other relevant information:

**Comment by hassani24** [comment]
Hello again -

This issue seems to be due to improper encoding using sentencepiece.  I was saving models instead of saving the encoding using your model.  changed to:

def encode(input_file, output_file, sp):
  print ("processing:: {} -> {}".format(input_file, output_file))
  with open(input_file, 'r') as rf, open(output_file, 'w') as wf:
    for count, line in enumerate(rf):
      wf.write(' '.join(sp.encode(line, out_type=str)))
  print ("wrote {} lines to {}".format(count, output_file))  

sp = spm.SentencePieceProcessor(model_file=MODEL)

input_file = '{}/{}.{}'.format(DATA, TRAIN, SRC)
output_file = '{}/{}.spm.{}'.format(DATA, TRAIN, SRC)
encode(input_file, output_file, sp)

**Comment by hassani24** [comment]
But now i'm having a new error and would appreciate any suggestions.

2021-01-16 19:33:57 | WARNING | fairseq.tasks.fairseq_task | 1 samples have invalid sizes and will be skipped, max_positions=(32, 32), first few sample ids=[0]
Traceback (most recent call last):
  File "/content/drive/MyDrive/translators/translation/fairseq/train.py", line 14, in <module>
    cli_main()
  File "/content/drive/MyDrive/translators/translation/fairseq/fairseq_cli/train.py", line 441, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/content/drive/MyDrive/translators/translation/fairseq/fairseq/distributed_utils.py", line 336, in call_main
    main(cfg, **kwargs)
  File "/content/drive/MyDrive/translators/translation/fairseq/fairseq_cli/train.py", line 120, in main
    disable_iterator_cache=task.has_sharded_data("train"),
  File "/content/drive/MyDrive/translators/translation/fairseq/fairseq/checkpoint_utils.py", line 221, in load_checkpoint
    epoch=1, load_dataset=True, **passthrough_args
  File "/content/drive/MyDrive/translators/translation/fairseq/fairseq/trainer.py", line 441, in get_train_iterator
    disable_iterator_cache=disable_iterator_cache,
  File "/content/drive/MyDrive/translators/translation/fairseq/fairseq/tasks/fairseq_task.py", line 248, in get_batch_iterator
    required_batch_size_multiple=required_batch_size_multiple,
  File "/content/drive/MyDrive/translators/translation/fairseq/fairseq/data/fairseq_dataset.py", line 152, in batch_by_size
    fixed_shapes=fixed_shapes,
  File "/content/drive/MyDrive/translators/translation/fairseq/fairseq/data/data_utils.py", line 342, in batch_by_size
    bsz_mult,
  File "fairseq/data/data_utils_fast.pyx", line 20, in fairseq.data.data_utils_fast.batch_by_size_vec
    cpdef list batch_by_size_vec(
  File "fairseq/data/data_utils_fast.pyx", line 27, in fairseq.data.data_utils_fast.batch_by_size_vec
    assert max_tokens <= 0 or np.max(num_tokens_vec) <= max_tokens, (
  File "<__array_function__ internals>", line 6, in amax
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 2706, in amax
    keepdims=keepdims, initial=initial, where=where)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity

**Comment by hassani24** [comment]
The issue was that my encode function was putting all of the text into one contiguous string.  

Updated to the following and the issue is resolved:

```
def encode(input_file, output_file, sp):
  print ("processing:: {} -> {}".format(input_file, output_file))
  with open(input_file, 'r') as rf, open(output_file, 'w') as wf:
    for count, line in enumerate(rf):
      wf.write(' '.join(sp.encode(line, out_type=str)))
      wf.write("\n")
  print ("wrote {} lines to {}".format(count, output_file))  
```
