### ISSUE TITLE
Trouble finetuning wav2vec 2.0 

### ISSUE THREAD

**Issue by AVSuni** [pytorch/fairseq#3143]
Many thanks for all your hard work on this repository.

I am trying to finetune wav2vec 2.0 XLRS-53 with Librispeech before moving on to other languages.   Here are my steps

1.  python wav2vec_manifest.py /LibriSpeech/dev-clean/ --dest /data_local/wav2vec2/ --ext flac --valid-percent 0.05
2.  wget https://dl.fbaipublicfiles.com/fairseq/wav2vec/dict.ltr.txt
3.  python libri_labels.py /workdir/train.tsv --output-dir /workdir/ --output-name train
4.  python libri_labels.py /workdir/valid.tsv --output-dir /workdir/ --output-name valid
5. fairseq-hydra-train     task.data=/workdir     model.w2v_path=/data_local/wav2vec2/xlsr_53_56k.pt     --config-dir /workdir/fairseq/examples/wav2vec/config/finetuning     --config-name base_100h

I get 

```2021-01-18 20:53:40 | INFO | fairseq.data.audio.raw_audio_dataset | loaded 114, skipped 0 samples
Traceback (most recent call last):
  File "/opt/conda/bin/fairseq-hydra-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-hydra-train')())
  File "/workdir/fairseq/fairseq_cli/hydra_train.py", line 66, in cli_main
    hydra_main()
  File "/opt/conda/lib/python3.6/site-packages/hydra/main.py", line 37, in decorated_main
    strict=strict,
  File "/opt/conda/lib/python3.6/site-packages/hydra/_internal/utils.py", line 347, in _run_hydra
    lambda: hydra.run(
  File "/opt/conda/lib/python3.6/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/opt/conda/lib/python3.6/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/opt/conda/lib/python3.6/site-packages/hydra/_internal/utils.py", line 350, in <lambda>
   overrides=args.overrides,
  File "/opt/conda/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 112, in run
    configure_logging=with_log_configuration,
  File "/opt/conda/lib/python3.6/site-packages/hydra/core/utils.py", line 128, in run_job
    ret.return_value = task_function(task_cfg)
  File "/workdir/fairseq/fairseq_cli/hydra_train.py", line 38, in hydra_main
    distributed_utils.call_main(cfg, pre_main)
  File "/workdir/fairseq/fairseq/distributed_utils.py", line 336, in call_main
    main(cfg, **kwargs)
  File "/workdir/fairseq/fairseq_cli/train.py", line 74, in main
    model = task.build_model(cfg.model)
  File "/workdir/fairseq/fairseq/tasks/audio_pretraining.py", line 201, in build_model
    model = super().build_model(model_cfg)
  File "/workdir/fairseq/fairseq/tasks/fairseq_task.py", line 282, in build_model
    model = models.build_model(cfg, self)
  File "/workdir/fairseq/fairseq/models/__init__.py", line 96, in build_model
    return model.build_model(cfg, task)
  File "/workdir/fairseq/fairseq/models/wav2vec/wav2vec2_asr.py", line 147, in build_model
    w2v_encoder = Wav2VecEncoder(cfg, task.target_dictionary)
  File "/workdir/fairseq/fairseq/models/wav2vec/wav2vec2_asr.py", line 298, in __init__
    task = tasks.setup_task(w2v_args.task)
  File "/workdir/fairseq/fairseq/tasks/__init__.py", line 39, in setup_task
    cfg = merge_with_parent(dc(), cfg)
  File "/workdir/fairseq/fairseq/dataclass/utils.py", line 449, in merge_with_parent
    merged_cfg = OmegaConf.merge(dc, cfg)
  File "/opt/conda/lib/python3.6/site-packages/omegaconf/omegaconf.py", line 321, in merge
    target.merge_with(*others[1:])
  File "/opt/conda/lib/python3.6/site-packages/omegaconf/basecontainer.py", line 331, in merge_with
    self._format_and_raise(key=None, value=None, cause=e)
  File "/opt/conda/lib/python3.6/site-packages/omegaconf/base.py", line 101, in _format_and_raise
    type_override=type_override,
  File "/opt/conda/lib/python3.6/site-packages/omegaconf/_utils.py", line 629, in format_and_raise
    _raise(ex, cause)
  File "/opt/conda/lib/python3.6/site-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
  File "/opt/conda/lib/python3.6/site-packages/omegaconf/basecontainer.py", line 329, in merge_with
    self._merge_with(*others)
  File "/opt/conda/lib/python3.6/site-packages/omegaconf/basecontainer.py", line 347, in _merge_with
    BaseContainer._map_merge(self, other)
  File "/opt/conda/lib/python3.6/site-packages/omegaconf/basecontainer.py", line 294, in _map_merge
    dest_node._merge_with(src_value)
  File "/opt/conda/lib/python3.6/site-packages/omegaconf/basecontainer.py", line 347, in _merge_with
    BaseContainer._map_merge(self, other)
  File "/opt/conda/lib/python3.6/site-packages/omegaconf/basecontainer.py", line 305, in _map_merge
    dest._format_and_raise(key=key, value=src_value, cause=e)
  File "/opt/conda/lib/python3.6/site-packages/omegaconf/base.py", line 101, in _format_and_raise
    type_override=type_override,
  File "/opt/conda/lib/python3.6/site-packages/omegaconf/_utils.py", line 694, in format_and_raise
    _raise(ex, cause)
  File "/opt/conda/lib/python3.6/site-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.ValidationError: Invalid value 'False', expected one of [hard, soft]
        full_key: eval_wer_config.print_alignment
        reference_type=GenerationConfig
        object_type=GenerationConfig
```

**Comment by assafmu** [comment]
This seems similar to this issue: #3042 . The model was reuploaded and fixed 7 days ago, consider re-downloading the model and trying again. 
If that doesn't work for you, can you comment in the mentioned issue?

**Comment by AVSuni** [comment]
Many thanks @assafmu . I am just re-downloading the model and will revert in the mentioned issue if the problem isn't fixed
