### ISSUE TITLE
m2m_100 model mismatched parameters

### ISSUE THREAD

**Issue by jjangsangy** [pytorch/fairseq#3147]
## 🐛 Bug

Running steps to generate on 418M and 1.2B models have mismatched parameters.

```
Traceback (most recent call last):
  File "/usr/local/bin/fairseq-generate", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-generate')())
  File "/content/fairseq/fairseq_cli/generate.py", line 404, in cli_main
    main(args)
  File "/content/fairseq/fairseq_cli/generate.py", line 49, in main
    return _main(cfg, sys.stdout)
  File "/content/fairseq/fairseq_cli/generate.py", line 102, in _main
    num_shards=cfg.checkpoint.checkpoint_shard_count,
  File "/content/fairseq/fairseq/checkpoint_utils.py", line 304, in load_model_ensemble
    state,
  File "/content/fairseq/fairseq/checkpoint_utils.py", line 355, in load_model_ensemble_and_task
    model.load_state_dict(state["model"], strict=strict, model_cfg=cfg.model)
  File "/content/fairseq/fairseq/models/fairseq_model.py", line 115, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for TransformerModel:
        size mismatch for encoder.embed_tokens.weight: copying a param with shape torch.Size([128112, 1024]) from checkpoint, the shape in current model is torch.Size([128006, 1024]).
        size mismatch for decoder.embed_tokens.weight: copying a param with shape torch.Size([128112, 1024]) from checkpoint, the shape in current model is torch.Size([128006, 1024]).
        size mismatch for decoder.output_projection.weight: copying a param with shape torch.Size([128112, 1024]) from checkpoint, the shape in current model is torch.Size([128006, 1024]).
```

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

#### Code sample
```sh
wget https://dl.fbaipublicfiles.com/m2m_100/418M_last_checkpoint.pt

sacrebleu --echo src -l de-fr -t wmt19 | head -n 20 > raw_input.de-fr.de
sacrebleu --echo ref -l de-fr -t wmt19 | head -n 20 > raw_input.de-fr.fr

wget https://dl.fbaipublicfiles.com/m2m_100/spm.128k.model
for lang in de fr ; do
    python scripts/spm_encode.py \
        --model spm.128k.model \
        --output_format=piece \
        --inputs=raw_input.de-fr.${lang} \
        --outputs=spm.de-fr.${lang}
done

wget https://dl.fbaipublicfiles.com/m2m_100/data_dict.128k.txt
fairseq-preprocess \
    --source-lang de --target-lang fr \
    --testpref spm.de-fr \
    --thresholdsrc 0 --thresholdtgt 0 \
    --destdir data_bin \
    --srcdict data_dict.128k.txt --tgtdict data_dict.128k.txt

fairseq-generate data_bin \
  --batch-size 32 \
  --path 418M_last_checkpoint.pt \
  -s de \
  -t fr \
  --remove-bpe 'sentencepiece' \
  --beam 5 \
  --task translation_multi_simple_epoch \
  --lang-pairs de-fr,fr-de \
  --decoder-langtok \
  --encoder-langtok src \
  --gen-subset test
```

### Environment

On Colab GPU instance with P100 GPU

 - fairseq Version: Master
 - PyTorch Version: 1.7.0+cu101
 - OS: Linux
 - How you installed fairseq: pip --editable
 - Build command you used (if compiling from source):
```sh
  git clone https://github.com/pytorch/fairseq.git
  ./fairseq/examples/m2m_100/install_dependecies.sh
  pip install -e ./fairseq sentencepiece
```
 - Python version: 3.6.9
 - CUDA/cuDNN version: 10.1

**Comment by ojasaar** [comment]
I encountered the same thing.
It seems that you just need to specify `--fixed-dictionary model_dict.128k.txt` when using `fairseq-generate`. The instructions in readme appear to be incorrect.

**Comment by huihuifan** [comment]
thanks, due to recent changes in fairseq it seems this is necessary now. I will update the readme. thanks for opening the task!
