### ISSUE TITLE
Hydra error when loading pretrained BART XSum model

### ISSUE THREAD

**Issue by keyonvafa** [pytorch/fairseq#3158]
## 🐛 Bug

When I load a pretrained BART XSum model with 
```
bart = BARTModel.from_pretrained('checkpoints/bart.large.xsum', checkpoint_file='model.pt')
```

I get the following error:

```
hydra.errors.ConfigCompositionException: Error merging override task.eval_bleu_args=null
```
### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Download BART XSum pretrained model
```
wget https://dl.fbaipublicfiles.com/fairseq/models/bart.large.xsum.tar.gz
tar -xzvf bart.large.xsum.tar.gz
```
2. Load model in Python
```
import torch
from fairseq.models.bart import BARTModel
bart = BARTModel.from_pretrained('checkpoints/bart.large.xsum', checkpoint_file='model.pt')
```
I get the following error:

```
Traceback (most recent call last):
  File "/env/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 513, in _apply_overrides_to_config
    OmegaConf.update(cfg, key, value, merge=True)
  File "/env/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 613, in update
    root.__setattr__(last_key, value)
  File "/env/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 285, in __setattr__
    raise e
  File "/env/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 282, in __setattr__
    self.__set_impl(key, value)
  File "/env/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 266, in __set_impl
    self._set_item_impl(key, value)
  File "/env/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 398, in _set_item_impl
    self._validate_set(key, value)
  File "/env/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 143, in _validate_set
    self._validate_set_merge_impl(key, value, is_assign=True)
  File "/env/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 156, in _validate_set_merge_impl
    self._format_and_raise(
  File "/env/lib/python3.8/site-packages/omegaconf/base.py", line 95, in _format_and_raise
    format_and_raise(
  File "/env/lib/python3.8/site-packages/omegaconf/_utils.py", line 694, in format_and_raise
    _raise(ex, cause)
  File "/env/lib/python3.8/site-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.ValidationError: child 'task.eval_bleu_args' is not Optional
        full_key: task.eval_bleu_args
        reference_type=Optional[TranslationConfig]
        object_type=TranslationConfig

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/proj/fairseq/fairseq/models/bart/model.py", line 128, in from_pretrained
    x = hub_utils.from_pretrained(
  File "/proj/fairseq/fairseq/hub_utils.py", line 74, in from_pretrained
    models, args, task = checkpoint_utils.load_model_ensemble_and_task(
  File "/proj/fairseq/fairseq/checkpoint_utils.py", line 339, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/proj/fairseq/fairseq/checkpoint_utils.py", line 273, in load_checkpoint_to_cpu
    state = _upgrade_state_dict(state)
  File "/proj/fairseq/fairseq/checkpoint_utils.py", line 550, in _upgrade_state_dict
    state["cfg"] = convert_namespace_to_omegaconf(state["args"])
  File "/proj/fairseq/fairseq/dataclass/utils.py", line 353, in convert_namespace_to_omegaconf
    composed_cfg = compose("config", overrides=overrides, strict=False)
  File "/env/lib/python3.8/site-packages/hydra/experimental/compose.py", line 31, in compose
    cfg = gh.hydra.compose_config(
  File "/env/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 507, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/env/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 151, in load_configuration
    return self._load_configuration(
  File "/env/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 277, in _load_configuration
    ConfigLoaderImpl._apply_overrides_to_config(config_overrides, cfg)
  File "/env/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 520, in _apply_overrides_to_config
    raise ConfigCompositionException(
hydra.errors.ConfigCompositionException: Error merging override task.eval_bleu_args=null
```

### Expected behavior

When I try the above with `bart.large` (not finetuned) or `bart.large.cnn` it works.

### Environment

 - fairseq Version (e.g., 1.0 or master): '1.0.0a0+cfbf0dd'
 - PyTorch Version (e.g., 1.0): 1.4
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): pip
 - Build command you used (if compiling from source): git clone + pip install
 - Python version: Python 3.8.5
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: Titan V
 - Any other relevant information:

Thank you!

**Comment by keyonvafa** [comment]
For now, I can get around this bug by using
```
bart = BARTModel.from_pretrained('checkpoints/bart.large.xsum', checkpoint_file='model.pt', 
                                  eval_bleu_args='', eval_bleu_detok_args='')
```

**Comment by louismartin** [comment]
Having the same bug with a model that I trained around summer 2020.
