### ISSUE TITLE
AttributeError: module 'signal' has no attribute 'SIGKILL'

### ISSUE THREAD

**Issue by zzxn** [pytorch/fairseq#3187]
## 🐛 Bug

On Windows 10, when import fairseq, a error message shows `AttributeError: module 'signal' has no attribute 'SIGKILL'`.
Consider to change to signal.SIGINT as Windows supports it? After I did this, everything seem OK.

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Install fairseq latest from GitHub on Windows
2. Run python code `import fairseq`

#### Code sample

```shell
$ python
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import fairseq
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "d:\pycharmprojects\fairseq\fairseq\__init__.py", line 20, in <module>
    from fairseq.distributed import utils as distributed_utils
  File "d:\pycharmprojects\fairseq\fairseq\distributed\__init__.py", line 6, in <module>
    from .distributed_timeout_wrapper import DistributedTimeoutWrapper
  File "d:\pycharmprojects\fairseq\fairseq\distributed\distributed_timeout_wrapper.py", line 17, in <module>
    class DistributedTimeoutWrapper(nn.Module):
  File "d:\pycharmprojects\fairseq\fairseq\distributed\distributed_timeout_wrapper.py", line 36, in DistributedTimeoutWrapper
    def __init__(self, module: nn.Module, timeout: int, signal=signal.SIGKILL):
AttributeError: module 'signal' has no attribute 'SIGKILL'
```

### Expected behavior

No error.

### Environment

 - fairseq Version (e.g., 1.0 or master): 1.0.0a0+148327d (latest of 2021-1-31)
 - PyTorch Version (e.g., 1.0): 1.7.1
 - OS (e.g., Linux): Windows 10
 - How you installed fairseq (`pip`, source): `pip`
 - Build command you used (if compiling from source):
 - Python version: 3.8.5
 - CUDA/cuDNN version: 10.2/7.0
 - GPU models and configuration: -
 - Any other relevant information: -

### Additional context

None

**Comment by zzxn** [comment]
I created a Pull Request for this issue: #3188
