### ISSUE TITLE
Binary incompatibility when using another machine

### ISSUE THREAD

**Issue by salvacarrion** [pytorch/fairseq#3203]
#### What is your question?

How do I use trained models in a different machine?

#### What have you tried?

1) In a remote machine, I have **trained a model and generate translations successfully** using this command:

`fairseq-generate data-bin/scielo_health_es_en/ --source-lang es --target-lang en --path checkpoints/transformer/checkpoint_best.pt --tokenizer moses --remove-bpe --beam 5 --scoring bleu`

2) Then, I backup the whole folder (checkpoints, data-bin,...) and I try to generate the translations again in a **different machine** to double check but this time I get a **binary incompatibility error:**

```bash
(mltests) salvacarrion@salva-desktop:~/Documents/Programming/Datasets/Scielo/fairseq/scielo_health_es_en--$ fairseq-generate data-bin/scielo_health_es_en/ --source-lang es --target-lang en --path checkpoints/transformer/checkpoint_best.pt --tokenizer moses --remove-bpe --beam 5 --scoring bleu
2021-02-02 20:36:01 | INFO | fairseq_cli.generate | {'_name': None, 'common': {'_name': None, 'no_progress_bar': False, 'log_interval': 100, 'log_format': None, 'tensorboard_logdir': None, 'wandb_project': None, 'azureml_logging': False, 'seed': 1, 'cpu': False, 'tpu': False, 'bf16': False, 'memory_efficient_bf16': False, 'fp16': False, 'memory_efficient_fp16': False, 'fp16_no_flatten_grads': False, 'fp16_init_scale': 128, 'fp16_scale_window': None, 'fp16_scale_tolerance': 0.0, 'min_loss_scale': 0.0001, 'threshold_loss_scale': None, 'user_dir': None, 'empty_cache_freq': 0, 'all_gather_list_size': 16384, 'model_parallel_size': 1, 'quantization_config_path': None, 'profile': False, 'reset_logging': False, 'suppress_crashes': False}, 'common_eval': {'_name': None, 'path': 'checkpoints/transformer/checkpoint_best.pt', 'post_process': 'subword_nmt', 'quiet': False, 'model_overrides': '{}', 'results_path': None}, 'distributed_training': {'_name': None, 'distributed_world_size': 1, 'distributed_rank': 0, 'distributed_backend': 'nccl', 'distributed_init_method': None, 'distributed_port': -1, 'device_id': 0, 'distributed_no_spawn': False, 'ddp_backend': 'pytorch_ddp', 'bucket_cap_mb': 25, 'fix_batches_to_gpus': False, 'find_unused_parameters': False, 'fast_stat_sync': False, 'heartbeat_timeout': -1, 'broadcast_buffers': False, 'slowmo_momentum': None, 'slowmo_algorithm': 'LocalSGD', 'localsgd_frequency': 3, 'nprocs_per_node': 1, 'pipeline_model_parallel': False, 'pipeline_balance': None, 'pipeline_devices': None, 'pipeline_chunks': 0, 'pipeline_encoder_balance': None, 'pipeline_encoder_devices': None, 'pipeline_decoder_balance': None, 'pipeline_decoder_devices': None, 'pipeline_checkpoint': 'never', 'zero_sharding': 'none', 'tpu': False}, 'dataset': {'_name': None, 'num_workers': 1, 'skip_invalid_size_inputs_valid_test': False, 'max_tokens': 12000, 'batch_size': None, 'required_batch_size_multiple': 8, 'required_seq_len_multiple': 1, 'dataset_impl': None, 'data_buffer_size': 10, 'train_subset': 'train', 'valid_subset': 'valid', 'validate_interval': 1, 'validate_interval_updates': 0, 'validate_after_updates': 0, 'fixed_validation_seed': None, 'disable_validation': False, 'max_tokens_valid': None, 'batch_size_valid': None, 'curriculum': 0, 'gen_subset': 'test', 'num_shards': 1, 'shard_id': 0}, 'optimization': {'_name': None, 'max_epoch': 0, 'max_update': 0, 'stop_time_hours': 0.0, 'clip_norm': 0.0, 'sentence_avg': False, 'update_freq': [1], 'lr': [0.25], 'stop_min_lr': -1.0, 'use_bmuf': False}, 'checkpoint': {'_name': None, 'save_dir': 'checkpoints', 'restore_file': 'checkpoint_last.pt', 'finetune_from_model': None, 'reset_dataloader': False, 'reset_lr_scheduler': False, 'reset_meters': False, 'reset_optimizer': False, 'optimizer_overrides': '{}', 'save_interval': 1, 'save_interval_updates': 0, 'keep_interval_updates': -1, 'keep_last_epochs': -1, 'keep_best_checkpoints': -1, 'no_save': False, 'no_epoch_checkpoints': False, 'no_last_checkpoints': False, 'no_save_optimizer_state': False, 'best_checkpoint_metric': 'loss', 'maximize_best_checkpoint_metric': False, 'patience': -1, 'checkpoint_suffix': '', 'checkpoint_shard_count': 1, 'load_checkpoint_on_all_dp_ranks': False, 'model_parallel_size': 1, 'distributed_rank': 0}, 'bmuf': {'_name': None, 'block_lr': 1.0, 'block_momentum': 0.875, 'global_sync_iter': 50, 'warmup_iterations': 500, 'use_nbm': False, 'average_sync': False, 'distributed_world_size': 1}, 'generation': {'_name': None, 'beam': 5, 'nbest': 1, 'max_len_a': 0.0, 'max_len_b': 200, 'min_len': 1, 'match_source_len': False, 'unnormalized': False, 'no_early_stop': False, 'no_beamable_mm': False, 'lenpen': 1.0, 'unkpen': 0.0, 'replace_unk': None, 'sacrebleu': False, 'score_reference': False, 'prefix_size': 0, 'no_repeat_ngram_size': 0, 'sampling': False, 'sampling_topk': -1, 'sampling_topp': -1.0, 'constraints': None, 'temperature': 1.0, 'diverse_beam_groups': -1, 'diverse_beam_strength': 0.5, 'diversity_rate': -1.0, 'print_alignment': None, 'print_step': False, 'lm_path': None, 'lm_weight': 0.0, 'iter_decode_eos_penalty': 0.0, 'iter_decode_max_iter': 10, 'iter_decode_force_max_iter': False, 'iter_decode_with_beam': 1, 'iter_decode_with_external_reranker': False, 'retain_iter_history': False, 'retain_dropout': False, 'retain_dropout_modules': None, 'decoding_format': None, 'no_seed_provided': False}, 'eval_lm': {'_name': None, 'output_word_probs': False, 'output_word_stats': False, 'context_window': 0, 'softmax_batch': 9223372036854775807}, 'interactive': {'_name': None, 'buffer_size': 0, 'input': '-'}, 'model': None, 'task': {'_name': 'translation', 'data': 'data-bin/scielo_health_es_en/', 'source_lang': 'es', 'target_lang': 'en', 'load_alignments': False, 'left_pad_source': True, 'left_pad_target': False, 'max_source_positions': 1024, 'max_target_positions': 1024, 'upsample_primary': -1, 'truncate_source': False, 'num_batch_buckets': 0, 'train_subset': 'train', 'dataset_impl': None, 'required_seq_len_multiple': 1, 'eval_bleu': False, 'eval_bleu_args': '{}', 'eval_bleu_detok': 'space', 'eval_bleu_detok_args': '{}', 'eval_tokenized_bleu': False, 'eval_bleu_remove_bpe': None, 'eval_bleu_print_samples': False}, 'criterion': {'_name': 'cross_entropy', 'sentence_avg': True}, 'optimizer': None, 'lr_scheduler': {'_name': 'fixed', 'force_anneal': None, 'lr_shrink': 0.1, 'warmup_updates': 0, 'lr': [0.25]}, 'scoring': {'_name': 'bleu', 'pad': 1, 'eos': 2, 'unk': 3}, 'bpe': None, 'tokenizer': {'_name': 'moses', 'source_lang': 'es', 'target_lang': 'en', 'moses_no_dash_splits': False, 'moses_no_escape': False}}
2021-02-02 20:36:01 | INFO | fairseq.tasks.translation | [es] dictionary: 26584 types
2021-02-02 20:36:01 | INFO | fairseq.tasks.translation | [en] dictionary: 24600 types
2021-02-02 20:36:01 | INFO | fairseq_cli.generate | loading model(s) from checkpoints/transformer/checkpoint_best.pt
2021-02-02 20:36:04 | INFO | fairseq.data.data_utils | loaded 4,816 examples from: data-bin/scielo_health_es_en/test.es-en.es
2021-02-02 20:36:04 | INFO | fairseq.data.data_utils | loaded 4,816 examples from: data-bin/scielo_health_es_en/test.es-en.en
2021-02-02 20:36:04 | INFO | fairseq.tasks.translation | data-bin/scielo_health_es_en/ test es-en 4816 examples
Traceback (most recent call last):
  File "/home/salvacarrion/anaconda3/envs/mltests/bin/fairseq-generate", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-generate')())
  File "/home/salvacarrion/Documents/Programming/Python/fairseq/fairseq_cli/generate.py", line 404, in cli_main
    main(args)
  File "/home/salvacarrion/Documents/Programming/Python/fairseq/fairseq_cli/generate.py", line 49, in main
    return _main(cfg, sys.stdout)
  File "/home/salvacarrion/Documents/Programming/Python/fairseq/fairseq_cli/generate.py", line 141, in _main
    itr = task.get_batch_iterator(
  File "/home/salvacarrion/Documents/Programming/Python/fairseq/fairseq/tasks/fairseq_task.py", line 244, in get_batch_iterator
    batch_sampler = dataset.batch_by_size(
  File "/home/salvacarrion/Documents/Programming/Python/fairseq/fairseq/data/fairseq_dataset.py", line 145, in batch_by_size
    return data_utils.batch_by_size(
  File "/home/salvacarrion/Documents/Programming/Python/fairseq/fairseq/data/data_utils.py", line 306, in batch_by_size
    from fairseq.data.data_utils_fast import (
  File "fairseq/data/data_utils_fast.pyx", line 1, in init fairseq.data.data_utils_fast
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
2021-02-02 20:36:05 | INFO | wandb.sdk.internal.internal | Internal process exited

```
#### What's your environment?

 - fairseq Version: master
 - PyTorch Version: 1.7.0
 - OS: Linux
 - How you installed fairseq: source
 - Build command you used (if compiling from source):
```
git clone https://github.com/pytorch/fairseq
cd fairseq
pip install --editable ./
```
 - Python version: Python 3.7.4
 - CUDA/cuDNN version: Driver Version: 450.51.05    CUDA Version: 11.0
 - GPU models and configuration: x2 Titan XP

**Comment by protonish** [comment]
I am getting same error but with `fairseq-train` on a simple IWSLT 14 trial run (from examples) :

```
2021-02-02 21:13:03 | INFO | fairseq_cli.train | task: TranslationTask
2021-02-02 21:13:03 | INFO | fairseq_cli.train | model: TransformerModel
2021-02-02 21:13:03 | INFO | fairseq_cli.train | criterion: LabelSmoothedCrossEntropyCriterion
2021-02-02 21:13:03 | INFO | fairseq_cli.train | num. model params: 41,938,944 (num. trained: 41,938,944)
2021-02-02 21:13:03 | INFO | fairseq.trainer | detected shared parameter: decoder.embed_tokens.weight <- decoder.output_projection.weight
2021-02-02 21:13:03 | INFO | fairseq.utils | ***********************CUDA enviroments for all 2 workers***********************
2021-02-02 21:13:03 | INFO | fairseq.utils | rank   0: capabilities =  7.5  ; total memory = 23.651 GB ; name = TITAN RTX                               
2021-02-02 21:13:03 | INFO | fairseq.utils | rank   1: capabilities =  7.5  ; total memory = 23.653 GB ; name = TITAN RTX                               
2021-02-02 21:13:03 | INFO | fairseq.utils | ***********************CUDA enviroments for all 2 workers***********************
2021-02-02 21:13:03 | INFO | fairseq_cli.train | training on 2 devices (GPUs/TPUs)
2021-02-02 21:13:03 | INFO | fairseq_cli.train | max tokens per GPU = 4000 and batch size per GPU = None
2021-02-02 21:13:03 | INFO | fairseq.trainer | Preparing to load checkpoint checkpoints/iwslt_test/checkpoint_last.pt
2021-02-02 21:13:03 | INFO | fairseq.trainer | No existing checkpoint found checkpoints/iwslt_test/checkpoint_last.pt
2021-02-02 21:13:03 | INFO | fairseq.trainer | loading train data for epoch 1
2021-02-02 21:13:03 | INFO | fairseq.data.data_utils | loaded 160,239 examples from: data-bin/iwslt14.tokenized.de-en/train.de-en.de
2021-02-02 21:13:03 | INFO | fairseq.data.data_utils | loaded 160,239 examples from: data-bin/iwslt14.tokenized.de-en/train.de-en.en
2021-02-02 21:13:03 | INFO | fairseq.tasks.translation | data-bin/iwslt14.tokenized.de-en train de-en 160239 examples
2021-02-02 21:13:03 | INFO | wandb.sdk.internal.internal | Internal process exited
Traceback (most recent call last):
  File "/cs/natlang-expts/nishant/anaconda3/envs/fair23/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/local-scratch/nishant/fair/fairmod2/fairseq_cli/train.py", line 449, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/local-scratch/nishant/fair/fairmod2/fairseq/distributed/utils.py", line 338, in call_main
    torch.multiprocessing.spawn(
  File "/cs/natlang-expts/nishant/anaconda3/envs/fair23/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/cs/natlang-expts/nishant/anaconda3/envs/fair23/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/cs/natlang-expts/nishant/anaconda3/envs/fair23/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/cs/natlang-expts/nishant/anaconda3/envs/fair23/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/local-scratch/nishant/fair/fairmod2/fairseq/distributed/utils.py", line 325, in distributed_main
    main(cfg, **kwargs)
  File "/local-scratch/nishant/fair/fairmod2/fairseq_cli/train.py", line 122, in main
    extra_state, epoch_itr = checkpoint_utils.load_checkpoint(
  File "/local-scratch/nishant/fair/fairmod2/fairseq/checkpoint_utils.py", line 220, in load_checkpoint
    epoch_itr = trainer.get_train_iterator(
  File "/local-scratch/nishant/fair/fairmod2/fairseq/trainer.py", line 443, in get_train_iterator
    batch_iterator = self.task.get_batch_iterator(
  File "/local-scratch/nishant/fair/fairmod2/fairseq/tasks/fairseq_task.py", line 244, in get_batch_iterator
    batch_sampler = dataset.batch_by_size(
  File "/local-scratch/nishant/fair/fairmod2/fairseq/data/fairseq_dataset.py", line 145, in batch_by_size
    return data_utils.batch_by_size(
  File "/local-scratch/nishant/fair/fairmod2/fairseq/data/data_utils.py", line 300, in batch_by_size
    from fairseq.data.data_utils_fast import (
  File "fairseq/data/data_utils_fast.pyx", line 1, in init fairseq.data.data_utils_fast
    # cython: language_level=3
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

I had a perfectly working code that I'd written since November on `fairseq 0.10.0`. I just updated to the latest version and started getting this error. --> Verified by running the same scripts on the older version and everything works fine.


- fairseq Version: master
- PyTorch Version: 1.7.1
- OS: Linux
- How you installed fairseq: source (--editable)
- Python version: Python 3.8.5
- CUDA 10.2
- GPU: 2 x TITAN RTX

**Comment by brxx122** [comment]
I got a similar error since 1/30. I have the same package version as before and have not changed any fairseq settings.
I follow the suggestion of [this](https://stackoverflow.com/questions/65974718/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility) and upgrade my numpy from 1.18.1 to 1.20.0 (although 1.18.1 works well five days ago). 
It works successfully. Hope this helps.

**Comment by salvacarrion** [comment]
@brxx122 Thank you! That worked for me.
