### ISSUE TITLE
Fairseq-hydra-train: str interpolation key 'hydra.job.name' not found

### ISSUE THREAD

**Issue by carlosep93** [pytorch/fairseq#3205]
## 🐛 Bug

When trying to run any example using fairseq-hydra-train and configurations I get an error stating that the str interpolation key 'hydra.job.name' is not found. 

### To Reproduce

Using fairseq from source (3rd February 2021), from master branch. Using Python 3.6 and Pytorch 1.7.1, Hydra 2.5 and Omegaconf 2.0.6

#### Code sample

Running any of the examples [here](https://github.com/pytorch/fairseq/tree/master/examples/wav2vec)

fairseq-hydra-train \
    task.data=/path/to/data \
    --config-dir /path/to/fairseq-py/examples/wav2vec/config/pretraining \
    --config-name wav2vec2_base_librispeech

### Expected behavior

Traceback (most recent call last):                                                                                                          
  File "/home/carlos/anaconda3/envs/fairseq010/bin/fairseq-hydra-train", line 33, in <module>                                               
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-hydra-train')())                                                       
  File "/home/carlos/Documentos/fairseq-0.10/fairseq/fairseq_cli/hydra_train.py", line 91, in cli_main                                      
    hydra_main()                                                                                                                            
  File "/home/carlos/anaconda3/envs/fairseq010/lib/python3.6/site-packages/hydra/main.py", line 37, in decorated_main                       
    strict=strict,                                                                                                                          
  File "/home/carlos/anaconda3/envs/fairseq010/lib/python3.6/site-packages/hydra/_internal/utils.py", line 347, in _run_hydra               
    lambda: hydra.run(                                                                                                                      
  File "/home/carlos/anaconda3/envs/fairseq010/lib/python3.6/site-packages/hydra/_internal/utils.py", line 201, in run_and_report           
    raise ex                                                                                                                                
  File "/home/carlos/anaconda3/envs/fairseq010/lib/python3.6/site-packages/hydra/_internal/utils.py", line 198, in run_and_report           
    return func()                                                                                                                           
  File "/home/carlos/anaconda3/envs/fairseq010/lib/python3.6/site-packages/hydra/_internal/utils.py", line 350, in <lambda>                 
    overrides=args.overrides,                                                                                                               
  File "/home/carlos/anaconda3/envs/fairseq010/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 112, in run                      
    configure_logging=with_log_configuration,                                                                                               
  File "/home/carlos/anaconda3/envs/fairseq010/lib/python3.6/site-packages/hydra/core/utils.py", line 128, in run_job                       
    ret.return_value = task_function(task_cfg)                                                                                              
  File "/home/carlos/Documentos/fairseq-0.10/fairseq/fairseq_cli/hydra_train.py", line 34, in hydra_main                                    
    cfg.job_logging_cfg = OmegaConf.to_container(HydraConfig.get().job_logging, resolve=True)
  File "/home/carlos/anaconda3/envs/fairseq010/lib/python3.6/site-packages/omegaconf/omegaconf.py", line 442, in to_container
    return BaseContainer._to_content(cfg, resolve=resolve, enum_to_str=enum_to_str)
  File "/home/carlos/anaconda3/envs/fairseq010/lib/python3.6/site-packages/omegaconf/basecontainer.py", line 195, in _to_content
    node, resolve=resolve, enum_to_str=enum_to_str
  File "/home/carlos/anaconda3/envs/fairseq010/lib/python3.6/site-packages/omegaconf/basecontainer.py", line 195, in _to_content
    node, resolve=resolve, enum_to_str=enum_to_str
  File "/home/carlos/anaconda3/envs/fairseq010/lib/python3.6/site-packages/omegaconf/basecontainer.py", line 189, in _to_content
    throw_on_missing=False, throw_on_resolution_failure=True
  File "/home/carlos/anaconda3/envs/fairseq010/lib/python3.6/site-packages/omegaconf/base.py", line 137, in _dereference_node
    throw_on_resolution_failure=throw_on_resolution_failure,
  File "/home/carlos/anaconda3/envs/fairseq010/lib/python3.6/site-packages/omegaconf/base.py", line 392, in _resolve_interpolation
    throw_on_resolution_failure=throw_on_resolution_failure,
  File "/home/carlos/anaconda3/envs/fairseq010/lib/python3.6/site-packages/omegaconf/base.py", line 328, in _resolve_simple_interpolation
    f"{inter_type} interpolation key '{inter_key}' not found"
omegaconf.errors.ConfigKeyError: str interpolation key 'hydra.job.name' not found

### Environment

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0): 1.7.1 
 - OS (e.g., Linux): Ubuntu 20.4
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source): pip install --editable ./
 - Python version: 3.6
 - CUDA/cuDNN version: 11.2
 - GPU models and configuration: gtx 950m 
 - Any other relevant information:

**Comment by JoungheeKim** [comment]
Hi i got same issue these day.
I fix this problem by downgrade 'hydra-core' version to 1.0.

In fairseq setup, "hydra-core" must be less than 1.1
https://github.com/pytorch/fairseq/blob/b4843681b4d5af442febf8caba58ca9600b01656/setup.py#L193

Good luck

**Comment by carlosep93** [comment]
Thank you! After checking the version I realized that it was a know hydra-core error fixed on release 1.0.6
I installed hydra-core from source and It fixed it.

I'm closing the issue as this is working now.
