### ISSUE TITLE
KeyError when reload from checkpoint which has no attribute

### ISSUE THREAD

**Issue by xuhu357** [pytorch/fairseq#3211]
## 🐛 Bug

When I want to reload the wmt19 ende transformer model for fine-tuning, KeyError occurred~!
It happens when reload the pre-trained model(wmt19.en-de.ffn8192.pt) which has no attribute "version".

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd 'fairseq-train \
$DATA_BIN_PATH \
    --arch transformer_vaswani_wmt_en_de_big --share-decoder-input-output-embed \
    --restore-file checkpoints/wmt19.en-de.ffn8192.pt \
    --tensorboard-logdir $tflog_dir \
    --fp16 \
    --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 \
    --reset-optimizer \
    --lr 1e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 \
    --dropout 0.3 --weight-decay 0.0001 \
    --criterion label_smoothed_cross_entropy --label-smoothing 0.1 \
    --max-tokens 3072 \
    --eval-bleu \
    --eval-bleu-args '{"beam": 5, "max_len_a": 1.2, "max_len_b": 10}' \
    --eval-bleu-detok moses \
    --eval-bleu-remove-bpe \
    --eval-bleu-print-samples \
    --best-checkpoint-metric bleu --maximize-best-checkpoint-metric \
    --keep-last-epochs 5 \
    --batch-size 32'
2. See error
`Traceback (most recent call last):
  File "/home/xuhu357/miniconda3/envs/env_fairseq/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/home/xuhu357/fairseq/fairseq_cli/train.py", line 449, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home/xuhu357/fairseq/fairseq/distributed/utils.py", line 346, in call_main
    join=True,
  File "/home/xuhu357/miniconda3/envs/env_fairseq/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/xuhu357/miniconda3/envs/env_fairseq/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/home/xuhu357/miniconda3/envs/env_fairseq/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception:

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/home/xuhu357/miniconda3/envs/env_fairseq/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/home/xuhu357/fairseq/fairseq/distributed/utils.py", line 326, in distributed_main
    main(cfg, **kwargs)
  File "/home/xuhu357/fairseq/fairseq_cli/train.py", line 126, in main
    disable_iterator_cache=task.has_sharded_data("train"),
  File "/home/xuhu357/fairseq/fairseq/checkpoint_utils.py", line 201, in load_checkpoint
    reset_meters=reset_meters,
  File "/home/xuhu357/fairseq/fairseq/trainer.py", line 402, in load_checkpoint
    if itr_state["version"] >= 2 and itr_state["iterations_in_epoch"] == 0:
KeyError: 'version'`

### Environment

 - fairseq Version (e.g., master 1.0.0a0):
 - PyTorch Version (e.g., 1.0): 1.6 cuda 10.1
 - OS (e.g., Linux): Ubuntu 16.04
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: v100
 - Any other relevant information:

**Comment by alexeib** [comment]
can you open a pr, since you seem to have fixed this?

**Comment by xuhu357** [comment]
I have been committed a pr related this issue here.

https://github.com/pytorch/fairseq/pull/3212

**Comment by lematt1991** [comment]
Looks like this was resolved by #3211
