### ISSUE TITLE
Loading mBART checkpoint for multilingual translation

### ISSUE THREAD

**Issue by wasiahmad** [pytorch/fairseq#3213]
I am trying to load the mBART checkpoint to perform multilingual translation as suggested [here](https://github.com/pytorch/fairseq/tree/master/examples/multilingual#training). When the program attempts to load the pre-trained checkpoint, it gives the following error.

```
Traceback (most recent call last):
  File "/local/wasiahmad/software/anaconda3/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/home/wasiahmad/workspace/fairseq/fairseq_cli/train.py", line 348, in cli_main
    distributed_utils.call_main(args, main)
  File "/home/wasiahmad/workspace/fairseq/fairseq/distributed_utils.py", line 187, in call_main
    main(args, **kwargs)
  File "/home/wasiahmad/workspace/fairseq/fairseq_cli/train.py", line 106, in main
    extra_state, epoch_itr = checkpoint_utils.load_checkpoint(args, trainer)
  File "/home/wasiahmad/workspace/fairseq/fairseq/checkpoint_utils.py", line 137, in load_checkpoint
    reset_meters=args.reset_meters,
  File "/home/wasiahmad/workspace/fairseq/fairseq/trainer.py", line 252, in load_checkpoint
    state = checkpoint_utils.load_checkpoint_to_cpu(filename)
  File "/home/wasiahmad/workspace/fairseq/fairseq/checkpoint_utils.py", line 169, in load_checkpoint_to_cpu
    f, map_location=lambda s, l: default_restore_location(s, "cpu")
  File "/local/wasiahmad/software/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 592, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/local/wasiahmad/software/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 852, in _load
    result = unpickler.load()
  File "/local/wasiahmad/software/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 844, in persistent_load
    load_tensor(data_type(size), size, key, _maybe_decode_ascii(location))
  File "/local/wasiahmad/software/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 830, in load_tensor
    tensor_file = io.BytesIO(size_long + zip_file.get_record(name))
RuntimeError: [enforce fail at inline_container.cc:143] . PytorchStreamReader failed reading file data/94565435476624: file read failed
```

Environment:

```
Name: fairseq, Version: 0.9.0
Name: torch, Version: 1.5.1
```

I tried to load the checkpoints by simply running the following python code snippet and it works.

```
path='path2checkpoint'
saved_params = torch.load(
    path, map_location=lambda storage, loc: storage
)
```

But when I try to load the mBART or CRISS model checkpoint with fairseq-train (using --restore-file), I get the above error.

**Comment by wasiahmad** [comment]
@myleott any suggestion?

**Comment by zhengxxn** [comment]
Hi, I got the same error, but I found that it goes well when using the model downloaded from [here](https://dl.fbaipublicfiles.com/fairseq/models/mbart/mbart.CC25.tar.gz), which is the mbart v1.
Nonetheless, I have no information about the difference between the model v2 and v1.

**Comment by wasiahmad** [comment]
@zhengxxn did you try the CRISS model? They have the same architecture as mBART. Can you check?

**Comment by wasiahmad** [comment]
I actually made the checkpoints work by simply loading and saving the checkpoints as follows.

```
def load_and_save():
    filename = 'path_2_models/criss_checkpoints/criss.3rd.pt'
    saved_state = torch.load(
        filename, map_location=lambda storage, loc: storage
    )
    torch.save(
        saved_state,
        'path_2_models/criss_checkpoints/model.pt'
    )
```

Loading from `model.pt` works perfectly.
