### ISSUE TITLE
Key error while accessing batch_iterator.first_batch

### ISSUE THREAD

**Issue by krishnanNuance** [pytorch/fairseq#3214]
## ❓ Questions and Help
I get a key errior after loading the train dataset

#### Code
Using lstm_lm model in fairseq

#### What have you tried?
train using fairseq-train command

#### What's your environment?
 - PyTorch Version (e.g., 1.0)1.6.0
 - OS (e.g., Linux): linux
 - How you installed fairseq (`pip`, source): pip
 - Build command you used (if compiling from source): pip install -e .
 - Python version: 3

####stack trace:
Traceback (most recent call last):
  File "fairseq_280/venv/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "fairseq_280/fairseq_cli/train.py", line 352, in cli_main
    distributed_utils.call_main(args, main)
  File "fairseq_280/fairseq/distributed_utils.py", line 301, in call_main
    main(args, **kwargs)
  File "fairseq_280/fairseq_cli/train.py", line 114, in main
    disable_iterator_cache=task.has_sharded_data("train"),
  File "fairseq_280/fairseq/checkpoint_utils.py", line 212, in load_checkpoint
    epoch=1, load_dataset=True, **passthrough_args
  File "fairseq_280/fairseq/trainer.py", line 382, in get_train_iterator
    self.reset_dummy_batch(batch_iterator.first_batch)
  File "fairseq_280/fairseq/data/iterators.py", line 288, in first_batch
    return self.collate_fn([self.dataset[i] for i in self.frozen_batches[0]])
  File "fairseq_280/fairseq/data/iterators.py", line 288, in <listcomp>
    return self.collate_fn([self.dataset[i] for i in self.frozen_batches[0]])
  File "fairseq_280/fairseq/data/monolingual_dataset.py", line 104, in __getitem__
    source, future_target, past_target = self.dataset[index]
  File "fairseq_280/fairseq/data/token_block_dataset.py", line 125, in __getitem__
    [self.dataset[idx] for idx in range(start_ds_idx, end_ds_idx + 1)]
  File "fairseq_280/fairseq/data/token_block_dataset.py", line 125, in <listcomp>
    [self.dataset[idx] for idx in range(start_ds_idx, end_ds_idx + 1)]
  File "fairseq_280/fairseq/data/indexed_dataset.py", line 234, in __getitem__
    ptx = self.cache_index[i]
KeyError: 11761183

**Comment by alexeib** [comment]
havent seen this before, maybe try rebuilding the dataset using the latest fairseq version's preprocess.py?

**Comment by lematt1991** [comment]
Closing due to inactivity

**Comment by NonvolatileMemory** [comment]
this bug usually caused by you use an old version preprocess.py to process the data then use the 0.10 version to train

**Comment by AllaeddineD** [comment]
> this bug usually caused by you use an old version preprocess.py to process the data then use the 0.10 version to train

Thank you ! I spent some time trying to find a solution, then I found your comment. The issue was the version of preprocess.py. It's solved now :)
