### ISSUE TITLE
TypeError: can't pickle SwigPyObject objects (MuST-C EN-DE speech translation)

### ISSUE THREAD

**Issue by smkim0220** [pytorch/fairseq#3217]
## 🐛 Bug

I followed up the example provided in https://github.com/pytorch/fairseq/blob/master/examples/speech_to_text/docs/mustc_example.md, but when I run fairseq-train I get TypeError: can't pickle SwigPyObject objects.

### To Reproduce

Run
MKL_THREADING_LAYER=GNU CUDA_VISIBLE_DEVICES=4,5,6,7 fairseq-train espnet/egs/must_c/st1/dataset/en-de   --config-yaml config_st.yaml --train-subset train_st --valid-subset dev_st --save-dir result/en-de --num-workers 4 --max-tokens 10000 --max-update 100000 --task speech_to_text --criterion label_smoothed_cross_entropy --report-accuracy --arch s2t_transformer_s --optimizer adam --lr 2e-3 --lr-scheduler inverse_sqrt --warmup-updates 10000 --clip-norm 10.0 --seed 1 --update-freq 8 --fp16 

Error

Traceback (most recent call last):                                                                             
  File "/home/smkim/anaconda3/envs/test/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/home/smkim/fairseq/fairseq_cli/train.py", line 449, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home/smkim/fairseq/fairseq/distributed/utils.py", line 345, in call_main
    join=True,
  File "/home/smkim/anaconda3/envs/test/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/smkim/anaconda3/envs/test/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/home/smkim/anaconda3/envs/test/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/smkim/anaconda3/envs/test/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/smkim/fairseq/fairseq/distributed/utils.py", line 325, in distributed_main
    main(cfg, **kwargs)
  File "/home/smkim/fairseq/fairseq_cli/train.py", line 143, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/home/smkim/anaconda3/envs/test/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/smkim/fairseq/fairseq_cli/train.py", line 239, in train
    for i, samples in enumerate(progress):
  File "/home/smkim/anaconda3/envs/test/lib/python3.6/site-packages/tqdm/std.py", line 1107, in __iter__
    for obj in iterable:
  File "/home/smkim/fairseq/fairseq/data/iterators.py", line 59, in __iter__
    for x in self.iterable:
  File "/home/smkim/fairseq/fairseq/data/iterators.py", line 528, in _chunk_iterator
    for x in itr:
  File "/home/smkim/fairseq/fairseq/data/iterators.py", line 59, in __iter__
    for x in self.iterable:
  File "/home/smkim/fairseq/fairseq/data/iterators.py", line 650, in __next__
    raise item
  File "/home/smkim/fairseq/fairseq/data/iterators.py", line 581, in run
    for item in self._source:
  File "/home/smkim/anaconda3/envs/test/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "/home/smkim/anaconda3/envs/test/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/smkim/anaconda3/envs/test/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 801, in __init__
    w.start()
  File "/home/smkim/anaconda3/envs/test/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/home/smkim/anaconda3/envs/test/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/smkim/anaconda3/envs/test/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/smkim/anaconda3/envs/test/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/smkim/anaconda3/envs/test/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/smkim/anaconda3/envs/test/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/smkim/anaconda3/envs/test/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle SwigPyObject objects

When I set --num-workers 0, it works fine but otherwise TypeError: can't pickle SwigPyObject objects appears.
I’m not using the server alone and with --num-workers 0 options, my code occupies all CPU of server.

#### Code sample
n/a

### Environment

 - fairseq Version (e.g., 1.0 or master): fairseq  1.0.0a0+148327d  /home/smkim/fairseq
 - PyTorch Version (e.g., 1.0): 1.7.1
 - OS (e.g., Linux): Linux 
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source):
git clone https://github.com/pytorch/fairseq
cd fairseq
pip install --editable ./
 - Python version: 3.6.10
 - CUDA/cuDNN version: 10.0.130/7.6.5
 - GPU models and configuration: 4*RTX2080
 - Any other relevant information:

**Comment by kahne** [comment]
What's the version of your `sentencepiece` installation (`pip list sentencepiece`) ?

**Comment by smkim0220** [comment]
> What's the version of your `sentencepiece` installation (`pip list sentencepiece`) ?

It's 0.1.86.
sentencepiece                    0.1.86

**Comment by kahne** [comment]
> > What's the version of your `sentencepiece` installation (`pip list sentencepiece`) ?
> 
> It's 0.1.86.
> sentencepiece 0.1.86

I see. Can you try with the latest one?
```
pip install --upgrade sentencepiece
```

**Comment by smkim0220** [comment]
It works fine. Thanks!!

**Comment by smkim0220** [comment]
> > > What's the version of your `sentencepiece` installation (`pip list sentencepiece`) ?
> > 
> > 
> > It's 0.1.86.
> > sentencepiece 0.1.86
> 
> I see. Can you try with the latest one?
> 
> ```
> pip install --upgrade sentencepiece
> ```

It works fine. Thanks!!
