### ISSUE TITLE
Omegaconf MissingMandatoryValue error trying to train a base model Wav2Vec2.0

### ISSUE THREAD

**Issue by gandroz** [pytorch/fairseq#3241]
### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. After building a manifest from LibriSpeech, I tried training a base model Wav2Vec2.0
2. Use the configuration `wav2vec/config/wav2vec2_base_librispeech.yml` 
3. Add task.data directly in the config file instead of passing the argument to the CLI 
4. Run command `HYDRA_FULL_ERROR=1 fairseq-hydra-train --config-dir ~/src/fairseq_dev --config-name wav2vec2_base_config` 

Traceback (most recent call last):
  File "/home/guillaume/miniconda/envs/fairseq/bin/fairseq-hydra-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-hydra-train')())
  File "/home/guillaume/src/fairseq/fairseq_cli/hydra_train.py", line 91, in cli_main
    hydra_main()
  File "/home/guillaume/miniconda/envs/fairseq/lib/python3.8/site-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/home/guillaume/miniconda/envs/fairseq/lib/python3.8/site-packages/hydra/_internal/utils.py", line 346, in _run_hydra
    run_and_report(
  File "/home/guillaume/miniconda/envs/fairseq/lib/python3.8/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/home/guillaume/miniconda/envs/fairseq/lib/python3.8/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/home/guillaume/miniconda/envs/fairseq/lib/python3.8/site-packages/hydra/_internal/utils.py", line 347, in <lambda>
    lambda: hydra.run(
  File "/home/guillaume/miniconda/envs/fairseq/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 107, in run
    return run_job(
  File "/home/guillaume/miniconda/envs/fairseq/lib/python3.8/site-packages/hydra/core/utils.py", line 127, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/guillaume/src/fairseq/fairseq_cli/hydra_train.py", line 27, in hydra_main
    add_defaults(cfg)
  File "/home/guillaume/src/fairseq/fairseq/dataclass/initialize.py", line 42, in add_defaults
    field_cfg = cfg.get(k)
  File "/home/guillaume/miniconda/envs/fairseq/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 357, in get
    self._format_and_raise(key=key, value=None, cause=e)
  File "/home/guillaume/miniconda/envs/fairseq/lib/python3.8/site-packages/omegaconf/base.py", line 95, in _format_and_raise
    format_and_raise(
  File "/home/guillaume/miniconda/envs/fairseq/lib/python3.8/site-packages/omegaconf/_utils.py", line 694, in format_and_raise
    _raise(ex, cause)
  File "/home/guillaume/miniconda/envs/fairseq/lib/python3.8/site-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.MissingMandatoryValue: Missing mandatory value: model
	full_key: model
	reference_type=Optional[FairseqConfig]
	object_type=FairseqConfig

### Environment

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0) 1.7
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed fairseq (`pip`, source): pip -e
 - Build command you used (if compiling from source):
 - Python version: 3.8
 - CUDA/cuDNN version: 11.0
 - GPU models and configuration: P4

**Comment by alexeib** [comment]
says it doesnt have a model field? 
actually i am not sure if hydra supports "yml" extensions, can you try yaml? if that doesnt work plz share your config

**Comment by gandroz** [comment]
@alexeib simple as that ! it was due to the `yml` extension.. changed to `yaml` and it works fine. Thanks
