### ISSUE TITLE
Problem with TensorboardX

### ISSUE THREAD

**Issue by salvacarrion** [pytorch/fairseq#3274]
## 🐛 Bug

Seems that there is a problem with tensorboardX and the multi-gpu training.
The first epoch trains correctly, but when it has to start with the logging or evaluation, I get a TypeError.

Ps.: If I set `CUDA_VISIBLE_DEVICES=0`, fairseq keeps using all GPUs

### To Reproduce

**Commands:**

```
# Train model
fairseq-train \
    $BASE_PATH/data-bin \
    --arch transformer \
    --optimizer adam \
    --criterion label_smoothed_cross_entropy --label-smoothing 0.1 \
    --max-tokens 4096 \
    --num-workers	$(nproc) \
    --max-epoch	50 \
    --seed 1 \
    --save-dir $BASE_PATH/checkpoints \
    --log-format simple \
    --no-epoch-checkpoints \
    --tensorboard-logdir $BASE_PATH/logdir \
    --update-freq 8 \
    --eval-bleu \
    --eval-bleu-args '{"beam": 5, "max_len_a": 1.2, "max_len_b": 10}' \
    --eval-bleu-detok moses \
    --eval-bleu-remove-bpe \
    --eval-bleu-print-samples \
    --best-checkpoint-metric bleu --maximize-best-checkpoint-metric \
    --clip-norm 1.0 \
    --lr 1e-3  \
    --lr-scheduler reduce_lr_on_plateau  \
    --warmup-updates 4000 \
    --dropout 0.1 --weight-decay 0.0001 \
    --patience 5

```

#### Output

```
2021-02-24 12:04:30 | INFO | fairseq.trainer | loading train data for epoch 1
2021-02-24 12:04:30 | INFO | fairseq.data.data_utils | loaded 575482 examples from: /home/scarrion/datasets/scielo/fairseq/scielo_health_es_en/data-bin/train.es-en.es
2021-02-24 12:04:30 | INFO | fairseq.data.data_utils | loaded 575482 examples from: /home/scarrion/datasets/scielo/fairseq/scielo_health_es_en/data-bin/train.es-en.en
2021-02-24 12:04:30 | INFO | fairseq.tasks.translation | /home/scarrion/datasets/scielo/fairseq/scielo_health_es_en/data-bin train es-en 575482 examples
2021-02-24 12:04:31 | INFO | fairseq.optim.adam | using FusedAdam
2021-02-24 12:04:31 | INFO | fairseq.trainer | begin training epoch 1
/home/scarrion/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/distributed.py:398: UserWarning: The `check_reduction` argument in `DistributedDataParallel` module is deprecated. Please avoid using it.
  "The `check_reduction` argument in `DistributedDataParallel` "
/home/scarrion/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/distributed.py:398: UserWarning: The `check_reduction` argument in `DistributedDataParallel` module is deprecated. Please avoid using it.
  "The `check_reduction` argument in `DistributedDataParallel` "
2021-02-24 12:04:44 | INFO | root | Reducer buckets have been rebuilt in this iteration.
2021-02-24 12:07:44 | INFO | train_inner | epoch 001:    100 / 326 loss=12.985, nll_loss=12.715, ppl=6725, wps=29783.4, ups=0.55, wpb=54148.3, bsz=1758, num_updates=100, lr=2.5e-05, gnorm=2.821, clip=98, train_wall=182, wall=194
2021-02-24 12:10:53 | INFO | train_inner | epoch 001:    200 / 326 loss=10.878, nll_loss=10.342, ppl=1297.6, wps=28988.4, ups=0.53, wpb=54737.5, bsz=1769, num_updates=200, lr=5e-05, gnorm=1.684, clip=96, train_wall=189, wall=382
2021-02-24 12:14:03 | INFO | train_inner | epoch 001:    300 / 326 loss=9.916, nll_loss=9.208, ppl=591.35, wps=28726.6, ups=0.53, wpb=54565.3, bsz=1767.5, num_updates=300, lr=7.5e-05, gnorm=1.819, clip=100, train_wall=190, wall=572
2021-02-24 12:14:53 | INFO | fairseq_cli.train | begin validation on "valid" subset
2021-02-24 12:15:04 | INFO | fairseq.tasks.translation | example hypothesis: Conclusions.
2021-02-24 12:15:04 | INFO | fairseq.tasks.translation | example reference: Conclusions.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/scarrion/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/scarrion/anaconda3/lib/python3.7/site-packages/tensorboardX/event_file_writer.py", line 202, in run
    data = self._queue.get(True, queue_wait_duration)
  File "/home/scarrion/anaconda3/lib/python3.7/multiprocessing/queues.py", line 108, in get
    res = self._recv_bytes()
  File "/home/scarrion/anaconda3/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/scarrion/anaconda3/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/scarrion/anaconda3/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

Traceback (most recent call last):
  File "/home/scarrion/anaconda3/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/home/scarrion/packages/fairseq-0.10.2/fairseq_cli/train.py", line 352, in cli_main
    distributed_utils.call_main(args, main)
  File "/home/scarrion/packages/fairseq-0.10.2/fairseq/distributed_utils.py", line 286, in call_main
    nprocs=args.distributed_num_procs,
  File "/home/scarrion/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/scarrion/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/home/scarrion/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/scarrion/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/scarrion/packages/fairseq-0.10.2/fairseq/distributed_utils.py", line 270, in distributed_main
    main(args, **kwargs)
  File "/home/scarrion/packages/fairseq-0.10.2/fairseq_cli/train.py", line 125, in main
    valid_losses, should_stop = train(args, trainer, task, epoch_itr)
  File "/home/scarrion/anaconda3/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/scarrion/packages/fairseq-0.10.2/fairseq_cli/train.py", line 223, in train
    args, trainer, task, epoch_itr, valid_subsets, end_of_epoch
  File "/home/scarrion/packages/fairseq-0.10.2/fairseq_cli/train.py", line 266, in validate_and_save
    valid_losses = validate(args, trainer, task, epoch_itr, valid_subsets)
  File "/home/scarrion/packages/fairseq-0.10.2/fairseq_cli/train.py", line 323, in validate
    trainer.valid_step(sample)
  File "/home/scarrion/anaconda3/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/scarrion/packages/fairseq-0.10.2/fairseq/trainer.py", line 764, in valid_step
    logging_output = self._reduce_and_log_stats(logging_outputs, sample_size)
  File "/home/scarrion/packages/fairseq-0.10.2/fairseq/trainer.py", line 1068, in _reduce_and_log_stats
    self.task.reduce_metrics(logging_outputs, self.get_criterion())
  File "/home/scarrion/packages/fairseq-0.10.2/fairseq/tasks/translation.py", line 375, in reduce_metrics
    metrics.log_scalar("_bleu_counts", np.array(counts))
  File "/home/scarrion/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 630, in __array__
    return self.numpy()
TypeError: can't convert cuda:1 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
```

### Environment

 - fairseq Version: 0.10.2
 - PyTorch Version: 1.7.0
 - tensorboardX version==2.1
 - OS: Linux
 - How you installed fairseq (`pip`, source): 
```
 (From releases)
pip install --editable ./
```
 - Python version: Python 3.7.4
 - CUDA/cuDNN version: CUDA Version: 11.0 
 - GPU models and configuration: Titan XP

**Comment by salvacarrion** [comment]
I'm closing this issue since it does not happen on master (c3d2beec96bd609f87d8da14cc2dffdbbd843b54)

**Comment by lorelupo** [comment]
Hi, do you have any idea about what was causing the issue?

**Comment by lorelupo** [comment]
I found the answer here: https://github.com/pytorch/fairseq/pull/3237
Thanks anyway
