### ISSUE TITLE
Cant run fairseq-hydra-train command in google colab

### ISSUE THREAD

**Issue by hamaadtahir** [pytorch/fairseq#3281]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?

I am trying to train base model of wav2vec2.0 as mentioned in the docs. Few days ago I was able to do it succesfully using this command in google colab:

!fairseq-hydra-train \
    task.data=/path/to/data \
    --config-dir /path/to/fairseq-py/examples/wav2vec/config/pretraining \
    --config-name wav2vec2_base_librispeech

But since yesterday, I havent been able to do so. Everytime I run this command I get this error:

Traceback (most recent call last):
  File "/usr/local/bin/fairseq-hydra-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-hydra-train')())
  File "/usr/local/bin/fairseq-hydra-train", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.7/dist-packages/importlib_metadata/__init__.py", line 96, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/content/drive/MyDrive/voxceleb/fairseq/fairseq_cli/hydra_train.py", line 11, in <module>
    from fairseq.dataclass.initialize import add_defaults, hydra_init
  File "/content/drive/MyDrive/voxceleb/fairseq/fairseq/__init__.py", line 32, in <module>
    import fairseq.criterions  # noqa
  File "/content/drive/MyDrive/voxceleb/fairseq/fairseq/criterions/__init__.py", line 36, in <module>
    importlib.import_module("fairseq.criterions." + file_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/content/drive/MyDrive/voxceleb/fairseq/fairseq/criterions/ctc.py", line 19, in <module>
    from fairseq.tasks import FairseqTask
  File "/content/drive/MyDrive/voxceleb/fairseq/fairseq/tasks/__init__.py", line 116, in <module>
    module = importlib.import_module("fairseq.tasks." + task_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/content/drive/MyDrive/voxceleb/fairseq/fairseq/tasks/multilingual_translation.py", line 19, in <module>
    from fairseq.models import FairseqMultiModel
  File "/content/drive/MyDrive/voxceleb/fairseq/fairseq/models/__init__.py", line 208, in <module>
    module = importlib.import_module("fairseq.models." + model_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/content/drive/MyDrive/voxceleb/fairseq/fairseq/models/speech_to_text/__init__.py", line 7, in <module>
    from .convtransformer import *  # noqa
  File "/content/drive/MyDrive/voxceleb/fairseq/fairseq/models/speech_to_text/convtransformer.py", line 10, in <module>
    from examples.simultaneous_translation.utils.data_utils import (
**ModuleNotFoundError: No module named 'examples.simultaneous_translation'**
#### What's your environment?

Google colab pro
 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0): 1.7.0+cu101
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):  source, git clone https://github.com/pytorch/fairseq
 - Build command you used (if compiling from source): pip install --editable ./
 - Python version: 3.7.10
 - CUDA/cuDNN version: 101
 - GPU models and configuration:
 - Any other relevant information:

**Comment by guobabaya** [comment]
Did you solve this problem, I have the same problem.
