### ISSUE TITLE
ImportError: cannot import name 'prune_state_dict'

### ISSUE THREAD

**Issue by zxpan** [pytorch/fairseq#3292]
## 🐛 Bug

After git commit 569c024ae6ee3e8c37c3b9dca975a3df50f7a03
The issue was not there before git commit d3890e593398c485f6593ab8512ac51d37dedc9c

>>> import fairseq
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./fairseq/fairseq/__init__.py", line 32, in <module>
    import fairseq.criterions  # noqa
  File "./fairseq/fairseq/criterions/__init__.py", line 36, in <module>
    importlib.import_module("fairseq.criterions." + file_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "./fairseq/fairseq/criterions/label_smoothed_cross_entropy_latency_augmented.py", line 6, in <module>
    from examples.simultaneous_translation.utils.latency import LatencyTraining
  File ./fairseq/examples/simultaneous_translation/__init__.py", line 6, in <module>
    from . import models  # noqa
  File "./fairseq/examples/simultaneous_translation/models/__init__.py", line 14, in <module>
    "examples.simultaneous_translation.models." + model_name
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "./fairseq/examples/simultaneous_translation/models/convtransformer_simul_trans.py", line 8, in <module>
    from fairseq import checkpoint_utils
  File "./fairseq/fairseq/checkpoint_utils.py", line 23, in <module>
    from fairseq.models import FairseqDecoder, FairseqEncoder
  File "./fairseq/fairseq/models/__init__.py", line 20, in <module>
    from .fairseq_model import (
  File "./fairseq/fairseq/models/fairseq_model.py", line 17, in <module>
    from fairseq.checkpoint_utils import prune_state_dict
ImportError: cannot import name 'prune_state_dict'

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd 'python3` and import fairseq
2. See error

**Comment by olafthiele** [comment]
There is already a PR for it. #3286

**Comment by zxpan** [comment]
great, you can close it now
