### ISSUE TITLE
Error while training wav2vec

### ISSUE THREAD

**Issue by sanakhamekhem** [pytorch/fairseq#3332]
Dear,

I 'm trying to train a mode using the following command: 

**fairseq-hydra-train task.data=$manifest_path --config-dir  $dirPretrained --config-name wav2vec2_base_librispeech_v1**

however, i have got this error:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pyEnv/lib/python3.8/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/home/ubuntu/anaconda3/envs/pyEnv/lib/python3.8/site-packages/hydra/_internal/utils.py", line 347, in <lambda>
    lambda: hydra.run(
  File "/home/ubuntu/anaconda3/envs/pyEnv/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 100, in run
    cfg = self.compose_config(
  File "/home/ubuntu/anaconda3/envs/pyEnv/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 507, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/home/ubuntu/anaconda3/envs/pyEnv/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 151, in load_configuration
    return self._load_configuration(
  File "/home/ubuntu/anaconda3/envs/pyEnv/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 277, in _load_configuration
    ConfigLoaderImpl._apply_overrides_to_config(config_overrides, cfg)
  File "/home/ubuntu/anaconda3/envs/pyEnv/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 502, in _apply_overrides_to_config
    if OmegaConf.select(
  File "/home/ubuntu/anaconda3/envs/pyEnv/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 552, in select
    format_and_raise(node=cfg, key=key, value=None, cause=e, msg=str(e))
  File "/home/ubuntu/anaconda3/envs/pyEnv/lib/python3.8/site-packages/omegaconf/_utils.py", line 694, in format_and_raise
    _raise(ex, cause)
  File "/home/ubuntu/anaconda3/envs/pyEnv/lib/python3.8/site-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
AssertionError:
       full_key: task.data
       reference_type=Optional[FairseqConfig]
       object_type=FairseqConfig

**Comment by sanakhamekhem** [comment]
I have resolved it

**Comment by SimoneMattioli98** [comment]
How didi you solve it?

**Comment by boleamol** [comment]
Can you write here how you have resolved? because we are facing same error.

**Comment by speechless-z** [comment]
HI, I have such a problem but do not know how to modify it, can you please tell me? Thank you so much.
