### ISSUE TITLE
SIGSEGV when training mBART with `translation_multi_simple_epoch` in FSDP

### ISSUE THREAD

**Issue by thpun** [pytorch/fairseq#3354]
## 🐛 Bug

Got `Exception: process 3 terminated with signal SIGSEGV` when trying to perform multilingual fine-tuning with mBART under `translation_multi_simple_epoch` task in fully sharded data parallel (FSDP).

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd
```bash
lang_pairs=<comma-separated list of lang pairs to be trained>
PREFIX=mbart-fsdp
DATA=/path/to/train/data
lang_list=models/$PREFIX/lang_list
MODEL=models/mbart.cc25/model.pt
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 fairseq-train $DATA \
  --finetune-from-model $MODEL \
  --encoder-normalize-before --decoder-normalize-before \
  --arch mbart_large --layernorm-embedding \
  --task translation_multi_simple_epoch \
  --sampling-method "temperature" \
  --sampling-temperature 5 \
  --encoder-langtok "src" --decoder-langtok \
  --lang-dict "$lang_list" --lang-pairs "$lang_pairs" \
  --source-dict $DATA/dict.en_XX.txt --target-dict $DATA/dict.en_XX.txt \
  --checkpoint-activations --fp16 --no-reshard-after-forward \
  --criterion label_smoothed_cross_entropy --label-smoothing 0.2 \
  --optimizer adam --adam-eps 1e-06 --adam-betas '(0.9, 0.98)' \
  --lr-scheduler inverse_sqrt --lr 6e-05 --stop-min-lr -1 --warmup-updates 2000 \
  --dropout 0.3 --attention-dropout 0.1 --weight-decay 0.0 \
  --max-tokens 1920 --update-freq 2 --upsample-primary 2 \
  --save-interval-updates 5000 --keep-interval-updates 10 --keep-best-checkpoints 10 \
  --patience 5 --max-epoch 150 \
  --seed 222 --log-format simple --log-interval 10 --ddp-backend fully_sharded \
  --save-dir models/$PREFIX
```

2. See error
```
2021-03-14 12:25:42 | INFO | fairseq.data.multilingual.multilingual_data_manager | main:en_XX-zh_CN src_langtok: 250004; tgt_langtok: 250025
2021-03-14 12:25:42 | INFO | fairseq.data.data_utils | loaded 5,983 examples from: path/to/valid.en_XX-zh_CN.en_XX
2021-03-14 12:25:42 | INFO | fairseq.data.data_utils | loaded 5,983 examples from: path/to/valid.en_XX-zh_CN.zh_CN
2021-03-14 12:25:42 | INFO | fairseq.data.multilingual.multilingual_data_manager | path/to valid en_XX-zh_CN 5983 examples
2021-03-14 12:25:42 | INFO | fairseq.data.multilingual.multilingual_data_manager | main:zh_CN-en_XX src_langtok: 250025; tgt_langtok: 250004
2021-03-14 12:25:42 | INFO | fairseq.data.data_utils | loaded 5,982 examples from: path/to/valid.zh_CN-en_XX.zh_CN
2021-03-14 12:25:42 | INFO | fairseq.data.data_utils | loaded 5,982 examples from: path/to/valid.zh_CN-en_XX.en_XX
2021-03-14 12:25:42 | INFO | fairseq.data.multilingual.multilingual_data_manager | path/to valid zh_CN-en_XX 5982 examples
2021-03-14 12:25:42 | INFO | fairseq.data.multilingual.multilingual_data_manager | main:en_XX-es_XX src_langtok: 250004; tgt_langtok: 250005
2021-03-14 12:25:42 | INFO | fairseq.data.data_utils | loaded 3,003 examples from: path/to/valid.en_XX-es_XX.en_XX
2021-03-14 12:25:42 | INFO | fairseq.data.data_utils | loaded 3,003 examples from: path/to/valid.en_XX-es_XX.es_XX
2021-03-14 12:25:42 | INFO | fairseq.data.multilingual.multilingual_data_manager | path/to valid en_XX-es_XX 3003 examples
2021-03-14 12:25:42 | INFO | fairseq.data.multilingual.multilingual_data_manager | main:es_XX-en_XX src_langtok: 250005; tgt_langtok: 250004
2021-03-14 12:25:42 | INFO | fairseq.data.data_utils | loaded 3,003 examples from: path/to/valid.en_XX-es_XX.es_XX
2021-03-14 12:25:42 | INFO | fairseq.data.data_utils | loaded 3,003 examples from: path/to/valid.en_XX-es_XX.en_XX
2021-03-14 12:25:42 | INFO | fairseq.data.multilingual.multilingual_data_manager | path/to valid es_XX-en_XX 3003 examples
Traceback (most recent call last):
  File "/opt/conda/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/workspace/fairseq/fairseq_cli/train.py", line 477, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/workspace/fairseq/fairseq/distributed/utils.py", line 349, in call_main
    join=True,
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 108, in join
    (error_index, name)
Exception: process 3 terminated with signal SIGSEGV
```

### Expected behavior

It is expected that either the training starts properly.

### Environment

 - fairseq Version (e.g., 1.0 or master): master, commit 252d5a9ae93e68254cfb1896fb5624cf11cda15e
 - PyTorch Version (e.g., 1.0) 1.7.0a0+8deb4fe
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source):
 ```bash
conda install gcc_linux-64 gxx_linux-64
git clone https://github.com/pytorch/fairseq.git
git clone https://github.com/facebookresearch/fairscale
cd fairseq
pip install opencc nni tensorboardX pyarrow deepspeed
pip install -U numpy cython
pip install --editable .
python setup.py build_ext --inplace
cd ../fairscale
pip install -r requirements.txt
pip install -e .
```
 - Python version: 3.6.10
 - CUDA/cuDNN version: 11.0
 - GPU models and configuration: V100
 - fairscale version: 0.3.1, commit `82986ca0f74a20e1e20e84161735b4b51c609148`

**Comment by tuhinjubcse** [comment]
could you get this resolved ?

**Comment by thpun** [comment]
I think this issue is somehow fixed in recent commits (but i'm not sure which exact commit in fairseq/fairscale, just use the latest commits in both repo).
But then I ran into another error which I think it's better to track with another issue (#3464) .

fairseq: ee0d5a0f65a25e5f5372776402aac5cb9c4adbf1
fairscale: e969397608e69222ebd6a034c5fbd958e0e9689d
