### ISSUE TITLE
Error in SimulST training using Wait-k on multi GPUs

### ISSUE THREAD

**Issue by sarapapi** [pytorch/fairseq#3357]
## 🐛 Bug
I'm following the SimulST README, I've downloaded the pre-trained ASR checkpoint that you made available few days ago and I've tried to run both the wait-k with fixed pre-decision module and the MMA examples. While the latter works on 1 or many GPUs, the former only works only on 1 GPU and shows this error on many GPUs (2 in this case):
```
Traceback (most recent call last):
  File "/home/fonorato/anaconda3/envs/myenv/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/home/fonorato/fairseqSLT/fairseq/fairseq_cli/train.py", line 473, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home/fonorato/fairseqSLT/fairseq/fairseq/distributed/utils.py", line 342, in call_main
    torch.multiprocessing.spawn(
  File "/home/fonorato/anaconda3/envs/myenv/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/fonorato/anaconda3/envs/myenv/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/fonorato/anaconda3/envs/myenv/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/fonorato/fairseqSLT/fairseq/fairseq/trainer.py", line 750, in train_step
    self._check_grad_norms(grad_norm)
  File "/home/fonorato/fairseqSLT/fairseq/fairseq/trainer.py", line 1229, in _check_grad_norms
    raise FloatingPointError(
FloatingPointError: Fatal error: gradients are inconsistent between workers. Try --ddp-backend=legacy_ddp. Or are you mixing up different generation of GPUs in training?
--------------------------------------------------------------------------------
grad_norm across the workers:
rank   0 = 35.95426559
rank   1 = 36.40999985

--------------------------------------------------------------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fonorato/anaconda3/envs/myenv/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/fonorato/fairseqSLT/fairseq/fairseq/distributed/utils.py", line 326, in distributed_main
    main(cfg, **kwargs)
  File "/home/fonorato/fairseqSLT/fairseq/fairseq_cli/train.py", line 157, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/home/fonorato/anaconda3/envs/myenv/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/fonorato/fairseqSLT/fairseq/fairseq_cli/train.py", line 267, in train
    log_output = trainer.train_step(samples)
  File "/home/fonorato/anaconda3/envs/myenv/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/fonorato/fairseqSLT/fairseq/fairseq/trainer.py", line 768, in train_step
    self.task.train_step(
  File "/home/fonorato/fairseqSLT/fairseq/fairseq/tasks/fairseq_task.py", line 475, in train_step
    loss, sample_size, logging_output = criterion(model, sample)
  File "/home/fonorato/anaconda3/envs/myenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fonorato/fairseqSLT/fairseq/fairseq/criterions/label_smoothed_cross_entropy.py", line 79, in forward
    net_output = model(**sample["net_input"])
  File "/home/fonorato/anaconda3/envs/myenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fonorato/fairseqSLT/fairseq/fairseq/distributed/module_proxy_wrapper.py", line 55, in forward
    return self.module(*args, **kwargs)
  File "/home/fonorato/anaconda3/envs/myenv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/fonorato/anaconda3/envs/myenv/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 692, in forward
    if self.reducer._rebuild_buckets():
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).

/home/fonorato/anaconda3/envs/myenv/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 16 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

### To Reproduce
Run Wait-K with fixed pre-decision module example code in the README file

### Environment
 - fairseq Version (e.g., 1.0 or master): up-to-date considering master
 - PyTorch Version (e.g., 1.0): 1.8.0
 - OS (e.g., Linux): Linux
 - Python version: 3.8.8
 - GPU models and configuration: 1/many GPUs K80

**Comment by mzaidi59** [comment]
Adding the argument `--ddp-backend legacy_ddp` removed the error for me. You can refer to the [docs](https://fairseq.readthedocs.io/en/latest/command_line_tools.html) for more details

**Comment by sarapapi** [comment]
> Adding the argument `--ddp-backend legacy_ddp` removed the error for me. You can refer to the [docs](https://fairseq.readthedocs.io/en/latest/command_line_tools.html) for more details

Unfortunately, this argument is not recognized using SimulST model

**Comment by mzaidi59** [comment]
Adding this argument solved the issue for me. Do you get the same error even after adding this?

I have another doubt
> I've downloaded the pre-trained ASR checkpoint

@sarapapi how did you load the provided checkpoints which are in zip format?

**Comment by sarapapi** [comment]
@mzaidi59 it seems that trying with another GPUs asset, it works (without adding any tag), I close this issue for now. Thank you!

**Comment by jalajthanaki** [comment]
@mzaidi59 , @sarapapi  Thanks for posting this issue. I also run into the same issue when I'm trying to replicate [translation](https://github.com/pytorch/fairseq/blob/master/examples/translation/README.md) example. 

I have tried  adding this `--ddp-backend legacy_ddp` flag but issue still persist. Any suggestions?

**Comment by mzaidi59** [comment]
Hey @jalajthanaki, can you post the actual error log with your setup details?

**Comment by mzaidi59** [comment]
@jalajthanaki, can you post the actual error log with your setup details?
