### ISSUE TITLE
How can I iteretively conduct inference and training?

### ISSUE THREAD

**Issue by Jxu-Thu** [pytorch/fairseq#3363]
My code is based on fairsep 0.8.0.

In the train loop 
for i, samples in enumerate(progress, start=epoch_itr.iterations_in_epoch):
    train_step()
    # build the validation set
subset = 'valid'
  
  itr = task.get_batch_iterator(
    dataset=task.dataset(subset),
    max_tokens=args.max_tokens_valid,
    max_sentences=args.max_sentences_valid,
    max_positions=utils.resolve_max_positions(
      task.max_positions(),
      trainer.get_model().max_positions(),
    ),
    ignore_invalid_inputs=args.skip_invalid_size_inputs_valid_test,
    required_batch_size_multiple=args.required_batch_size_multiple,
    seed=args.seed,
    num_shards=args.distributed_world_size,
    shard_id=args.distributed_rank,
    num_workers=args.num_workers,
  ).next_epoch_itr(shuffle=False)
  
  progress = progress_bar.build_progress_bar(
    args, itr, epoch_itr.epoch,
    prefix='valid on \'{}\' subset'.format(subset),
    no_progress_bar='simple'
  )
  
# validation for this train step
for ith, sample in enumerate(process):
    valid_step()

**It is ok to use single GPU . With multi GPU, I got the error as follows:**

Traceback (most recent call last):
  File "train.py", line 426, in <module>
    cli_main()
  File "train.py", line 418, in cli_main
    nprocs=args.distributed_world_size,
  File "/tmp/cache/python/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/tmp/cache/python/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "fairseq/distributed_utils.py", line 174, in all_gather_list
    result.append(pickle.loads(bytes(out_buffer[2 : size + 2].tolist())))
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/cache/python/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/blob/v-jinx/DistilNAS/FairSeq-DistilNAS-EXPLatSoTa/train_share_distil.py", line 385, in distributed_main
    main(args, init_distributed=True)
fairseq/distributed_utils.py", line 178, in all_gather_list
    'Unable to unpickle data from other workers. all_gather_list requires all '
Exception: Unable to unpickle data from other workers. all_gather_list requires all workers to enter the function together, so this error usually indicates that the workers have fallen out of sync somehow. Workers can fall out of sync if one of them runs out of memory, or if there are other conditions in your training script that can cause one worker to finish an epoch while other workers are still iterating over their portions of the data.

**Comment by Jxu-Thu** [comment]
If I conduct validation on every training step, the error comes in few training steps. If I conduct validation on every N (N>1) train step, the error comes in the later training steps. How to fix this problem?
