### ISSUE TITLE
Expected 3-dimensional input for 3-dimensional weight

### ISSUE THREAD

**Issue by roboticsai** [pytorch/fairseq#3376]
## 🐛 Bug
```

(fairseq) robot@lab:~/agi/fairseq$ python3 wav2vec.py 
Traceback (most recent call last):
  File "wav2vec.py", line 11, in <module>
    c = model.forward(z, mask=False, features_only=True)
  File "/home/robot/agi/fairseq/fairseq/models/wav2vec/wav2vec2.py", line 530, in forward
    features = self.feature_extractor(source)
  File "/home/robot/anaconda3/envs/fairseq/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/robot/agi/fairseq/fairseq/models/wav2vec/wav2vec2.py", line 761, in forward
    x = conv(x)
  File "/home/robot/anaconda3/envs/fairseq/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/robot/anaconda3/envs/fairseq/lib/python3.6/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/robot/anaconda3/envs/fairseq/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/robot/anaconda3/envs/fairseq/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 263, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/robot/anaconda3/envs/fairseq/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 260, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected 3-dimensional input for 3-dimensional weight [512, 1, 10], but got 4-dimensional input of size [1, 1, 512, 31] instead
```

### To Reproduce
python3 wav2vec.py where wav2vec.py contents are:
```
import torch
from fairseq.models.wav2vec.wav2vec2 import Wav2Vec2Model

cp = torch.load('/home/robot/Downloads/wav2vec_small.pt')
model = Wav2Vec2Model.build_model(cp['args'], task=None)
model.load_state_dict(cp['model'])
model.eval()

wav_input_16khz = torch.randn(1,10000)
z = model.feature_extractor(wav_input_16khz)
c = model.forward(z, mask=False, features_only=True)
print(c)
```

### Expected behavior

A text converted from input audio file. eg. MY NAME IS...

### Environment

 - fairseq Version (e.g., 1.0 or master): 0.10.2
 - PyTorch Version (e.g., 1.0): 1.8.0
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed fairseq (`pip`, source): From source as described in README.md file
 - Build command you used (if compiling from source): pip install --editable ./
 - Python version: 3.6.13

**Comment by AK391** [comment]
@roboticsai any update on this also got this error did you try unsqueeze(0)?

**Comment by hust-cxl** [comment]
> ## 🐛 Bug
> ```
> 
> (fairseq) robot@lab:~/agi/fairseq$ python3 wav2vec.py 
> Traceback (most recent call last):
>   File "wav2vec.py", line 11, in <module>
>     c = model.forward(z, mask=False, features_only=True)
>   File "/home/robot/agi/fairseq/fairseq/models/wav2vec/wav2vec2.py", line 530, in forward
>     features = self.feature_extractor(source)
>   File "/home/robot/anaconda3/envs/fairseq/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/robot/agi/fairseq/fairseq/models/wav2vec/wav2vec2.py", line 761, in forward
>     x = conv(x)
>   File "/home/robot/anaconda3/envs/fairseq/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/robot/anaconda3/envs/fairseq/lib/python3.6/site-packages/torch/nn/modules/container.py", line 119, in forward
>     input = module(input)
>   File "/home/robot/anaconda3/envs/fairseq/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
>     result = self.forward(*input, **kwargs)
>   File "/home/robot/anaconda3/envs/fairseq/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 263, in forward
>     return self._conv_forward(input, self.weight, self.bias)
>   File "/home/robot/anaconda3/envs/fairseq/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 260, in _conv_forward
>     self.padding, self.dilation, self.groups)
> RuntimeError: Expected 3-dimensional input for 3-dimensional weight [512, 1, 10], but got 4-dimensional input of size [1, 1, 512, 31] instead
> ```
> 
> ### To Reproduce
> python3 wav2vec.py where wav2vec.py contents are:
> 
> ```
> import torch
> from fairseq.models.wav2vec.wav2vec2 import Wav2Vec2Model
> 
> cp = torch.load('/home/robot/Downloads/wav2vec_small.pt')
> model = Wav2Vec2Model.build_model(cp['args'], task=None)
> model.load_state_dict(cp['model'])
> model.eval()
> 
> wav_input_16khz = torch.randn(1,10000)
> z = model.feature_extractor(wav_input_16khz)
> c = model.forward(z, mask=False, features_only=True)
> print(c)
> ```
> 
> ### Expected behavior
> A text converted from input audio file. eg. MY NAME IS...
> 
> ### Environment
> * fairseq Version (e.g., 1.0 or master): 0.10.2
> * PyTorch Version (e.g., 1.0): 1.8.0
> * OS (e.g., Linux): Ubuntu 20.04
> * How you installed fairseq (`pip`, source): From source as described in README.md file
> * Build command you used (if compiling from source): pip install --editable ./
> * Python version: 3.6.13

Have you solved this problem？ I face the same issue as you when I use conv1d, and I am sure I do not  use torch.unsqueeze(). Why was the input dimension expanded automatically?

**Comment by matthewkperez** [comment]
This happened to me because I had a stereo wav instead of a mono wav. I converted the wav file to a mono and it fixed the issue
