### ISSUE TITLE
Training a Multilingual system on multi-gpus

### ISSUE THREAD

**Issue by joao-alves97** [pytorch/fairseq#3378]
### What is your question?

Hello! 
I'm trying to train a multilingual model using a dataset with 15 language-pairs and 500M sentence pairs. I'm using a machine with 4 Tesla T4. When I try to run the training process I get an error.  It is a memory issue that I do not know how to solve. I have tried to use different dataset implementations (lazy and mmap). I'm using master version of fairseq.

**My question is** : What is the right way of training a multilingual model on multiple gpus? 

#### Preprocess for each language pair:

```bash
        fairseq-preprocess \
        --source-lang $source_language \
        --target-lang $target_language \
        --trainpref train \
        --validpref valid \
        --joined-dictionary \
        --tgtdict vocab_target \
        --destdir ${setup_directory}/data-bin \
        --workers $num_jobs
```
#### Train:

```bash       
fairseq-train \
        -- $data_bin \
        --ddp-backend=no_c10d \
        --save-dir ${setup_directory}/shared-model-checkpoints \
        --save-interval-updates $save_freq \
        --task translation_multi_simple_epoch \
        --arch transformer \
        --lang-pairs $lang_pairs \
        --lang-dict $lang_list \
        --sampling-method "$batch_sampling_method" \
        $sampling_temperature \
        --optimizer adam \
        --adam-betas '(0.9, 0.98)' \
        --clip-norm $clip_norm  \
        --lr $learn_rate \
        --lr-scheduler inverse_sqrt \
        --warmup-updates $lr_warmup \
        --warmup-init-lr '1e-07' \
        --dropout $dropout \
        --criterion $criterion \
        --label-smoothing $label_smoothing \
        --share-decoder-input-output-embed \
        --max-epoch $epochs \
        --patience $early_stopping \
        --keep-last-epochs $keep_last_checkpoints \
        --keep-best-checkpoints $keep_best_checkpoints \
        --max-tokens 4096 \
        --fp16 \
        --num-workers $num_jobs \
        --fix-batches-to-gpus 
```

### Log
```bash
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/mnt/data/venvs/fairseq/0.10.2/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/mnt/data/tools/fairseq/fairseq/distributed/utils.py", line 326, in distributed_main
    main(cfg, **kwargs)
  File "/mnt/data/tools/fairseq/fairseq_cli/train.py", line 157, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/home/ubuntu/anaconda3/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/mnt/data/tools/fairseq/fairseq_cli/train.py", line 263, in train
    for i, samples in enumerate(progress):
  File "/mnt/data/tools/fairseq/fairseq/logging/progress_bar.py", line 256, in __iter__
    for i, obj in enumerate(self.iterable, start=self.n):
  File "/mnt/data/tools/fairseq/fairseq/data/iterators.py", line 59, in __iter__
    for x in self.iterable:
  File "/mnt/data/tools/fairseq/fairseq/data/iterators.py", line 528, in _chunk_iterator
    for x in itr:
  File "/mnt/data/tools/fairseq/fairseq/data/iterators.py", line 59, in __iter__
    for x in self.iterable:
  File "/mnt/data/venvs/fairseq/0.10.2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 355, in __iter__
    return self._get_iterator()
  File "/mnt/data/venvs/fairseq/0.10.2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 301, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/mnt/data/venvs/fairseq/0.10.2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 914, in __init__
    w.start()
  File "/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
OverflowError: cannot serialize a bytes object larger than 4 GiB
```

### What have you tried?

- `--fix-batches-to-gpus`
-  `--dataset-impl` : `lazy` and `mmap`

**Comment by joao-alves97** [comment]
After solving the previous error, now I have this one:
```bash
TrainFairseq/Baseline.baseline: Traceback (most recent call last):TrainFairseq/Baseline.baseline:   File "/mnt/data/venvs/fairseq/0.10.2/bin/fairseq-train", line 33, in <module>TrainFairseq/Baseline.baseline:     sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())TrainFairseq/Baseline.baseline:   File "/mnt/data/tools/fairseq/fairseq_cli/train.py", line 477, in cli_mainTrainFairseq/Baseline.baseline:     distributed_utils.call_main(cfg, main)TrainFairseq/Baseline.baseline:   File "/mnt/data/tools/fairseq/fairseq/distributed/utils.py", line 349, in call_mainTrainFairseq/Baseline.baseline:     join=True,TrainFairseq/Baseline.baseline:   File "/mnt/data/venvs/fairseq/0.10.2/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawnTrainFairseq/Baseline.baseline:     return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')TrainFairseq/Baseline.baseline:   File "/mnt/data/venvs/fairseq/0.10.2/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processesTrainFairseq/Baseline.baseline:     while not context.join():TrainFairseq/Baseline.baseline:   File "/mnt/data/venvs/fairseq/0.10.2/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 136, in joinTrainFairseq/Baseline.baseline:     signal_name=nameTrainFairseq/Baseline.baseline: torch.multiprocessing.spawn.ProcessExitedException: process 3 terminated with signal SIGKILL
```

**Comment by sarthmit** [comment]
Hi, were you able to train a multilingual model from scratch?

**Comment by joao-alves97** [comment]
Hi, yes I was. I just used `--num-workers 0` and it worked

**Comment by sarthmit** [comment]
Would it be possible for you to share your setup? I don't know how to do the preprocessing of the datasets and the setup of the model.
