### ISSUE TITLE
Megatron 11b model parts not stitched together

### ISSUE THREAD

**Issue by himat** [pytorch/fairseq#3398]
### To Reproduce

After downloading the pretrained model from https://github.com/pytorch/fairseq/tree/master/examples/megatron_11b
the resulting folder has the model in multiple parts.
```
$ ls megatron_11b
dict.txt  model-model_part-0.pt  model-model_part-1.pt  model-model_part-2.pt  model-model_part-3.pt  model-model_part-4.pt  model-model_part-5.pt  model-model_part-6.pt  model-model_part-7.pt
```

The evaluation given on that same page however says to run
```
fairseq-eval-lm \
  $DATA_PATH \
  --path megatron_11b/model.pt \
   ....
```

How do we create the single `model.pt` file?

**Comment by himat** [comment]
I also tried passing in one of the model parts, but I get this error

```
2021-03-25 21:07:50 | INFO | fairseq_cli.eval_lm | loading model(s) from ../megatron_11b/model-model_part-0.pt
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/bin/fairseq-eval-lm", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-eval-lm')())
  File "/home/ubuntu/fairseq/fairseq_cli/eval_lm.py", line 343, in cli_main
    distributed_utils.call_main(convert_namespace_to_omegaconf(args), main)
  File "/home/ubuntu/fairseq/fairseq/distributed/utils.py", line 366, in call_main
    main(cfg, **kwargs)
  File "/home/ubuntu/fairseq/fairseq_cli/eval_lm.py", line 259, in main
    task=task,
  File "/home/ubuntu/fairseq/fairseq/checkpoint_utils.py", line 378, in load_model_ensemble_and_task
    model = task.build_model(cfg.model)
  File "/home/ubuntu/fairseq/fairseq/tasks/language_modeling.py", line 180, in build_model
    model = super().build_model(args)
  File "/home/ubuntu/fairseq/fairseq/tasks/fairseq_task.py", line 633, in build_model
    model = models.build_model(args, self)
  File "/home/ubuntu/fairseq/fairseq/models/__init__.py", line 96, in build_model
    return model.build_model(cfg, task)
  File "/home/ubuntu/fairseq/fairseq/model_parallel/models/transformer_lm.py", line 35, in build_model
    "\n\nPlease install the megatron submodule:"
ImportError:

Please install the megatron submodule:

  git submodule update --init fairseq/model_parallel/megatron
```

I ran `git submodule update --init fairseq/model_parallel/megatron` already but it keeps showing that same error.

**Comment by aijanai** [comment]
This is something happening to me too, even though I am just trying to train a Transformer on 4 GPUS.

**Comment by lokesh005** [comment]
I was also getting the same error and later I figure out that I had not installed the `apex` package. Can you try if `from apex.normalization.fused_layer_norm import FusedLayerNorm as LayerNorm` command is running successfully in your system?

Also,  please let me know if you know how to predict using a pre-trained Megatron model?
