### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'RTE-bin/input0/dict.txt'

### ISSUE THREAD

**Issue by Worien** [pytorch/fairseq#3400]
Trying to run training for rxf example for summarization. Faced with this error, but I do not even have RTE-bin folder, do I need to install something additionally to fairseq? 

```
Traceback (most recent call last):
  File "/home/pavel.pugach/.pyenv/versions/3.7.9/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/home/pavel.pugach/fairseq/fairseq_cli/train.py", line 477, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home/pavel.pugach/fairseq/fairseq/distributed/utils.py", line 364, in call_main
    main(cfg, **kwargs)
  File "/home/pavel.pugach/fairseq/fairseq_cli/train.py", line 82, in main
    task = tasks.setup_task(cfg.task)
  File "/home/pavel.pugach/fairseq/fairseq/tasks/__init__.py", line 44, in setup_task
    return task.setup_task(cfg, **kwargs)
  File "/home/pavel.pugach/fairseq/fairseq/tasks/sentence_prediction.py", line 118, in setup_task
    source=True,
  File "/home/pavel.pugach/fairseq/fairseq/tasks/sentence_prediction.py", line 106, in load_dictionary
    dictionary = Dictionary.load(filename)
  File "/home/pavel.pugach/fairseq/fairseq/data/dictionary.py", line 215, in load
    d.add_from_file(f)
  File "/home/pavel.pugach/fairseq/fairseq/data/dictionary.py", line 228, in add_from_file
    raise fnfe
  File "/home/pavel.pugach/fairseq/fairseq/data/dictionary.py", line 225, in add_from_file
    with open(PathManager.get_local_path(f), "r", encoding="utf-8") as fd:
FileNotFoundError: [Errno 2] No such file or directory: 'RTE-bin/input0/dict.txt'
```

Python 3.7.9
pytorch 1.8.0+cu111
Fairseq - cloned from current master branch

**Comment by jmusiel** [comment]
bump

**Comment by huchinlp** [comment]
Download the data and preprocess it, and if every thing goes smoothly, you will get the binarized data in the directory `RTE-bin`.
Do not forget replacing the `RTE-bin` arg in your command with the absolute path to your data directory.
