### ISSUE TITLE
Problems with SimulEval after recent update

### ISSUE THREAD

**Issue by sarapapi** [pytorch/fairseq#3415]
Hi again,
I've updated my local repository with the actual master branch, when I try to use SimulEval on waitk i got this error:
```
/home/spapi/anaconda3/envs/fairseq/lib/python3.8/site-packages/torchaudio/backend/utils.py:53: UserWarning: "sox" backend is being deprecated. The default backend will be changed to "sox_io" backend in 0.8.0 and "sox" backend will be removed in 0.9.0. Please migrate to "sox_io" backend. Please refer to https://github.com/pytorch/audio/issues/903 for the detail.
  warnings.warn(
/home/spapi/anaconda3/envs/fairseq/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
2021-03-30 10:48:15 | INFO     | simuleval.scorer | Evaluating on speech
2021-03-30 10:48:15 | INFO     | simuleval.scorer | Source: /storage/MT/sara/simultaneous/dataset/MuST-Cinema/en-it/wav/amara_splitted/src_audiopath_list.txt
2021-03-30 10:48:15 | INFO     | simuleval.scorer | Target: /storage/MT/sara/simultaneous/dataset/MuST-Cinema/en-it/amara.it
2021-03-30 10:48:15 | INFO     | simuleval.scorer | Number of sentences: 545
2021-03-30 10:48:15 | INFO     | simuleval.server | Evaluation Server Started (process id 1774886). Listening to port 6667
2021-03-30 10:49:15 | WARNING  | simuleval.scorer | Resetting scorer
2021-03-30 10:49:15 | INFO     | simuleval.cli    | Output dir: /storage/MT/sara/simultaneous/training/ST/waitk_tag/
2021-03-30 10:49:15 | INFO     | simuleval.cli    | Evaluating FairseqSimulSTAgent (process id 1774880) on instances from 0 to 544
2021-03-30 10:49:15 | INFO     | simuleval.cli    | Start data writer (process id 1775349)
2021-03-30 10:51:02 | INFO     | fairseq.tasks.speech_to_text | dictionary size (spm_unigram10000_st.txt): 10,000
[W NNPACK.cpp:80] Could not initialize NNPACK! Reason: Unsupported hardware.
/home/spapi/anaconda3/envs/fairseq/lib/python3.8/site-packages/torchaudio/compliance/kaldi.py:574: UserWarning: The function torch.rfft is deprecated and will be removed in a future PyTorch release. Use the new torch.fft module functions, instead, by importing torch.fft and calling torch.fft.fft or torch.fft.rfft. (Triggered internally at  /pytorch/aten/src/ATen/native/SpectralOps.cpp:590.)
  fft = torch.rfft(strided_input, 1, normalized=False, onesided=True)
Traceback (most recent call last):
  File "/home/spapi/anaconda3/envs/fairseq/bin/simuleval", line 33, in <module>
    sys.exit(load_entry_point('simuleval', 'console_scripts', 'simuleval')())
  File "/home/spapi/fairseq_simul/SimulEval/simuleval/cli.py", line 165, in main
    _main(args.client_only)
  File "/home/spapi/fairseq_simul/SimulEval/simuleval/cli.py", line 192, in _main
    evaluate(args, client, server_process)
  File "/home/spapi/fairseq_simul/SimulEval/simuleval/cli.py", line 145, in evaluate
    decode(args, client, result_queue, indices)
  File "/home/spapi/fairseq_simul/SimulEval/simuleval/cli.py", line 108, in decode
    action = agent.policy(states)
  File "/home/spapi/fairseq_simul/fairseq/examples/speech_to_text/simultaneous_translation/agents/fairseq_simul_st_agent.py", line 337, in policy
    if outputs["action"] == 0:
TypeError: tuple indices must be integers or slices, not str
2021-03-30 10:51:08 | INFO     | wandb.sdk.internal.internal | Internal process exited
```
I think that the problem is that with the recent update the decoder passes a NamedTuple and not a dict anymore.
How can I solve it? @jmp84 @cndn @sravyapopuri388

**Comment by xutaima** [comment]
Hi @sarapapi, thank you so much for reporting the bug, it has been fix by a recent update. Could you please pull the master and try again?

**Comment by jmp84** [comment]
@sarapapi closing this issue but please reopen if pulling doesn't help.
