### ISSUE TITLE
S2T interactive inference producing an error

### ISSUE THREAD

**Issue by BadriAhmed** [pytorch/fairseq#3423]
## FairSeq S2T Example: Speech Recognition (ASR) on LibriSpeech

After downloading an pretrained s2t_transformer model, and running inference using fairseq-interactive, i ran into a NoneType error
### To Reproduce

Steps to reproduce the behavior : 

1. Run on terminal fairseq-interactive FairSeq/lbasr/ --task speech_to_text --path librispeech_transformer_s.pt
2. Enter path
3. Get an error

#### Code sample

fairseq-interactive FairSeq/lbasr/ --task speech_to_text --path librispeech_transformer_s.pt
 in terminal : 
2021-03-31 12:38:08 | INFO | fairseq.tasks.speech_to_text | dictionary size (dict.txt): 10,000
2021-03-31 12:38:08 | INFO | fairseq_cli.interactive | loading model(s) from FairSeq/lbasr/librispeech_transformer_s.pt
2021-03-31 12:38:09 | INFO | fairseq_cli.interactive | NOTE: hypothesis and token scores are output in base 2
2021-03-31 12:38:09 | INFO | fairseq_cli.interactive | Type the input sentence and press return:
path/test.flac 
Traceback (most recent call last):
  File "/home/badri/anaconda3/envs/Dev/bin/fairseq-interactive", line 8, in <module>
    sys.exit(cli_main())
  File "/home/badri/anaconda3/envs/Dev/lib/python3.8/site-packages/fairseq_cli/interactive.py", line 307, in cli_main
    distributed_utils.call_main(args, main)
  File "/home/badri/anaconda3/envs/Dev/lib/python3.8/site-packages/fairseq/distributed_utils.py", line 302, in call_main
    main(args, **kwargs)
  File "/home/badri/anaconda3/envs/Dev/lib/python3.8/site-packages/fairseq_cli/interactive.py", line 205, in main
    for batch in make_batches(inputs, args, task, max_positions, encode_fn):
  File "/home/badri/anaconda3/envs/Dev/lib/python3.8/site-packages/fairseq_cli/interactive.py", line 75, in make_batches
    tokens = [
  File "/home/badri/anaconda3/envs/Dev/lib/python3.8/site-packages/fairseq_cli/interactive.py", line 76, in <listcomp>
    task.source_dictionary.encode_line(
AttributeError: 'NoneType' object has no attribute 'encode_line'

### Environment

 - fairseq Version ( master):
 - PyTorch 1.7.0
 - OS : Ubuntu 18.04 lts
 - fairseq installed via pip
 - Python 3.8:

I even tried on google colab, and I got the same error.

Thank you

**Comment by TingxunShi** [comment]
Hi, I found you closed the issue by yourself. Did you solve it? If you did, how? Thank you
