### ISSUE TITLE
the released model of pre-trained asr & streaming st cann't be loaded correctly

### ISSUE THREAD

**Issue by dqqcasia** [pytorch/fairseq#3450]
In simultaneous translation, the released model of pre-trained asr & st cann't be loaded correctly. 

the error information is:

Traceback (most recent call last):
  File "/data00/home/xxx/miniconda3/envs/fairseq_new/bin/simuleval", line 33, in <module>
    sys.exit(load_entry_point('simuleval', 'console_scripts', 'simuleval')())
  File "/data00/home/xxx/codes/SimulEval/simuleval/cli.py", line 167, in main
    _main(args.client_only)
  File "/data00/home/xxx/codes/SimulEval/simuleval/cli.py", line 194, in _main
    evaluate(args, client, server_process)
  File "/data00/home/xxx/codes/SimulEval/simuleval/cli.py", line 147, in evaluate
    decode(args, client, result_queue, indices)
  File "/data00/home/xxx/codes/SimulEval/simuleval/cli.py", line 91, in decode
    parser = options.general_parser()
  File "/data00/home/xxx/codes/fairseq/examples/speech_to_text/simultaneous_translation/agents/fairseq_simul_st_agent.py", line 139, in __init__
    self.load_model_vocab(args)
  File "/data00/home/xxx/codes/fairseq/examples/speech_to_text/simultaneous_translation/agents/fairseq_simul_st_agent.py", line 223, in load_model_vocab
    state = checkpoint_utils.load_checkpoint_to_cpu(filename)
  File "/data00/home/xxx/codes/fairseq/fairseq/checkpoint_utils.py", line 263, in load_checkpoint_to_cpu
    state = torch.load(f, map_location=torch.device("cpu"))
  File "/data00/home/xxx/miniconda3/envs/fairseq_new/lib/python3.7/site-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/data00/home/xxx/miniconda3/envs/fairseq_new/lib/python3.7/site-packages/torch/serialization.py", line 764, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.

**Comment by dqqcasia** [comment]
@xutaima Would you have a suggestion?
