### ISSUE TITLE
hydra: enum 'Choices' can't be pickled

### ISSUE THREAD

**Issue by villmow** [pytorch/fairseq#3482]
## 🐛 Bug

I'm doing some custom preprocessing in the dataset using multiprocessing. I recently switched to `hydra`, which works quite nice! 
I'm working with `FairseqDataclass` and structured Configs, which is really nice. In my dataset I pass the `cfg` object to a worker function. Without multiprocessing it works like a charm, but when I switch to multiprocessing it crashes with some error I don't understand. 

### To Reproduce

I don't have exact steps to reproduce, but maybe you guys have an idea:

```bash
Traceback (most recent call last):
  File "env/bin/fairseq-hydra-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-hydra-train')())
  File "./fairseq/fairseq_cli/hydra_train.py", line 91, in cli_main
    hydra_main()
  File "env/lib/python3.8/site-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "env/lib/python3.8/site-packages/hydra/_internal/utils.py", line 346, in _run_hydra
    run_and_report(
  File "env/lib/python3.8/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "env/lib/python3.8/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "env/lib/python3.8/site-packages/hydra/_internal/utils.py", line 347, in <lambda>
    lambda: hydra.run(
  File "env/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 107, in run
    return run_job(
  File "env/lib/python3.8/site-packages/hydra/core/utils.py", line 127, in run_job
    ret.return_value = task_function(task_cfg)
  File "./fairseq/fairseq_cli/hydra_train.py", line 45, in hydra_main
    distributed_utils.call_main(cfg, pre_main)
  File "./fairseq/fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "./fairseq/fairseq_cli/train.py", line 114, in main
    task.load_dataset(valid_sub_split, combine=False, epoch=1)
  File "./my_project/fairseq/my_task.py", line 156, in load_dataset
    dataset = dataset_for_epoch(
  File "./my_project/fairseq/my_dataset.py", line 523, in dataset_for_epoch
    processed_dataset = process_dataset(
  File "./my_project/augmentation.py", line 449, in process_dataset
    processed_dataset = dataset.map(
  File "env/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 1485, in map
    transformed_shards = [r.get() for r in results]
  File "env/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 1485, in <listcomp>
    transformed_shards = [r.get() for r in results]
  File "env/lib/python3.8/site-packages/multiprocess/pool.py", line 771, in get
    raise self._value
  File "env/lib/python3.8/site-packages/multiprocess/pool.py", line 537, in _handle_tasks
    put(task)
  File "env/lib/python3.8/site-packages/multiprocess/connection.py", line 209, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "env/lib/python3.8/site-packages/multiprocess/reduction.py", line 54, in dumps
    cls(buf, protocol, *args, **kwds).dump(obj)
  File "env/lib/python3.8/site-packages/dill/_dill.py", line 454, in dump
    StockPickler.dump(self, obj)
  File "env/lib/python3.8/pickle.py", line 485, in dump
    self.save(obj)
  File "env/lib/python3.8/pickle.py", line 558, in save
    f(self, obj)  # Call unbound method with explicit self
  File "env/lib/python3.8/pickle.py", line 899, in save_tuple
    save(element)
  File "env/lib/python3.8/pickle.py", line 558, in save
    f(self, obj)  # Call unbound method with explicit self
  File "env/lib/python3.8/site-packages/dill/_dill.py", line 941, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "env/lib/python3.8/pickle.py", line 969, in save_dict
    self._batch_setitems(obj.items())
  File "env/lib/python3.8/pickle.py", line 995, in _batch_setitems
    save(v)
  File "env/lib/python3.8/pickle.py", line 558, in save
    f(self, obj)  # Call unbound method with explicit self
  File "env/lib/python3.8/site-packages/dill/_dill.py", line 1444, in save_function
    pickler.save_reduce(_create_function, (obj.__code__,
  File "env/lib/python3.8/pickle.py", line 690, in save_reduce
    save(args)
  File "env/lib/python3.8/pickle.py", line 558, in save
    f(self, obj)  # Call unbound method with explicit self
  File "env/lib/python3.8/pickle.py", line 899, in save_tuple
    save(element)
  File "env/lib/python3.8/pickle.py", line 558, in save
    f(self, obj)  # Call unbound method with explicit self
  File "env/lib/python3.8/pickle.py", line 884, in save_tuple
    save(element)
  File "env/lib/python3.8/pickle.py", line 558, in save
    f(self, obj)  # Call unbound method with explicit self
  File "env/lib/python3.8/site-packages/dill/_dill.py", line 1178, in save_cell
    pickler.save_reduce(_create_cell, (f,), obj=obj)
  File "env/lib/python3.8/pickle.py", line 690, in save_reduce
    save(args)
  File "env/lib/python3.8/pickle.py", line 558, in save
    f(self, obj)  # Call unbound method with explicit self
  File "env/lib/python3.8/pickle.py", line 884, in save_tuple
    save(element)
  File "env/lib/python3.8/pickle.py", line 601, in save
    self.save_reduce(obj=obj, *rv)
  File "env/lib/python3.8/pickle.py", line 715, in save_reduce
    save(state)
  File "env/lib/python3.8/pickle.py", line 558, in save
    f(self, obj)  # Call unbound method with explicit self
  File "env/lib/python3.8/site-packages/dill/_dill.py", line 941, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "env/lib/python3.8/pickle.py", line 969, in save_dict
    self._batch_setitems(obj.items())
  File "env/lib/python3.8/pickle.py", line 995, in _batch_setitems
    save(v)
  File "env/lib/python3.8/pickle.py", line 601, in save
    self.save_reduce(obj=obj, *rv)
  File "env/lib/python3.8/pickle.py", line 715, in save_reduce
    save(state)
  File "env/lib/python3.8/pickle.py", line 558, in save
    f(self, obj)  # Call unbound method with explicit self
  File "env/lib/python3.8/site-packages/dill/_dill.py", line 941, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "env/lib/python3.8/pickle.py", line 969, in save_dict
    self._batch_setitems(obj.items())
  File "env/lib/python3.8/pickle.py", line 995, in _batch_setitems
    save(v)
  File "env/lib/python3.8/pickle.py", line 601, in save
    self.save_reduce(obj=obj, *rv)
  File "env/lib/python3.8/pickle.py", line 715, in save_reduce
    save(state)
  File "env/lib/python3.8/pickle.py", line 558, in save
    f(self, obj)  # Call unbound method with explicit self
  File "env/lib/python3.8/site-packages/dill/_dill.py", line 941, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "env/lib/python3.8/pickle.py", line 969, in save_dict
    self._batch_setitems(obj.items())
  File "env/lib/python3.8/pickle.py", line 995, in _batch_setitems
    save(v)
  File "env/lib/python3.8/pickle.py", line 558, in save
    f(self, obj)  # Call unbound method with explicit self
  File "env/lib/python3.8/site-packages/dill/_dill.py", line 941, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "env/lib/python3.8/pickle.py", line 969, in save_dict
    self._batch_setitems(obj.items())
  File "env/lib/python3.8/pickle.py", line 995, in _batch_setitems
    save(v)
  File "env/lib/python3.8/pickle.py", line 601, in save
    self.save_reduce(obj=obj, *rv)
  File "env/lib/python3.8/pickle.py", line 715, in save_reduce
    save(state)
  File "env/lib/python3.8/pickle.py", line 558, in save
    f(self, obj)  # Call unbound method with explicit self
  File "env/lib/python3.8/site-packages/dill/_dill.py", line 941, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "env/lib/python3.8/pickle.py", line 969, in save_dict
    self._batch_setitems(obj.items())
  File "env/lib/python3.8/pickle.py", line 995, in _batch_setitems
    save(v)
  File "env/lib/python3.8/pickle.py", line 558, in save
    f(self, obj)  # Call unbound method with explicit self
  File "env/lib/python3.8/site-packages/dill/_dill.py", line 1390, in save_type
    StockPickler.save_global(pickler, obj, name=name)
  File "env/lib/python3.8/pickle.py", line 1068, in save_global
    raise PicklingError(
_pickle.PicklingError: Can't pickle <enum 'Choices'>: it's not found as fairseq.dataclass.constants.Choices
```

I don't know why an enum Choices needs to be pickled, I don't import this anywhere. Do you have an idea?

I'm pretty confident, that the config object is the cause of problems. When I don't provide the config object to the worker, it does not crash. When I don't do multiprocessing it does not crash.

### Expected behavior

It shouldn't be a problem to pickle config objects.

### Environment

 - fairseq Version (e.g., 1.0 or master): master (updated yesterday)
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux): linux
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source): pip install -e .
 - Python version: 3.8
 - CUDA/cuDNN version: None
 - GPU models and configuration: None
 - Any other relevant information: Nope

**Comment by villmow** [comment]
Here is a complete example to reproduce. Insert the following lines at line 43 in `setup_task` (just after loading a `FairseqDataclass` cfg):
https://github.com/pytorch/fairseq/blob/89371294e54ef8c306f19733f2e8bab8233c401e/fairseq/tasks/__init__.py#L42-L44

```python
import pickle
pickle.dumps(cfg)
```

Then execute the command from the hydra tutorial:

```bash
$ fairseq-hydra-train \
    distributed_training.distributed_world_size=1 \
    dataset.batch_size=2 \
    task.data=data-bin \
    model=transformer_lm/transformer_lm_gpt \
    task=language_modeling \
    optimization.max_update=5000
```

You will receive the following error:

```bash
Traceback (most recent call last):
  File "./fairseq/fairseq_cli/hydra_train.py", line 45, in hydra_main
    distributed_utils.call_main(cfg, pre_main)
  File "./fairseq/fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "./fairseq/fairseq_cli/train.py", line 82, in main
    task = tasks.setup_task(cfg.task)
  File "./fairseq/fairseq/tasks/__init__.py", line 45, in setup_task
    pickle.dumps(cfg)
_pickle.PicklingError: Can't pickle <enum 'Choices'>: attribute lookup Choices on fairseq.dataclass.constants failed
```

**Comment by villmow** [comment]
For anyone that stumbles over the same problem, here is a quick solution until this is fixed:
```python
cfg = OmegaConf.merge(
        OmegaConf.structured(
             MyConfigWhichNeedsToBePickled
        ),
        OmegaConf.create(
            OmegaConf.to_yaml(cfg)
        )
    )
```
This creates an new `omegaconf.DictConfig` object, which can be pickled.

**Comment by harveenchadha** [comment]
Hi @villmow,

Can you please let me know where this code needs to be added and in which file?

Thanks!
