### ISSUE TITLE
dict' object has no attribute 'task'

### ISSUE THREAD

**Issue by roboticsai** [pytorch/fairseq#3488]
When i'm trying to run the inference with transformer language model which i'v trained i'm getting this error:
```
\INFO:__main__:Namespace(all_gather_list_size=16384, autoregressive=False, azureml_logging=False, batch_size=None, batch_size_valid=None, beam=5, beam_size_token=100, beam_threshold=25.0, best_checkpoint_metric='loss', bf16=False, bpe=None, broadcast_buffers=False, bucket_cap_mb=25, checkpoint_shard_count=1, checkpoint_suffix='', constraints=None, cpu=False, cpu_offload=False, criterion='ctc', curriculum=0, data='/root/dataset/restaurant_data/audio', data_buffer_size=10, dataset_impl=None, ddp_backend='pytorch_ddp', decoding_format=None, device_id=0, disable_validation=False, distributed_backend='nccl', distributed_init_method=None, distributed_no_spawn=False, distributed_port=-1, distributed_rank=0, distributed_world_size=1, diverse_beam_groups=-1, diverse_beam_strength=0.5, diversity_rate=-1.0, dump_emissions=None, dump_features=None, empty_cache_freq=0, enable_padding=False, eos=2, eval_wer=False, eval_wer_post_process='letter', eval_wer_tokenizer=None, fast_stat_sync=False, find_unused_parameters=False, finetune_from_model=None, fix_batches_to_gpus=False, fixed_validation_seed=None, force_anneal=None, fp16=False, fp16_init_scale=128, fp16_no_flatten_grads=False, fp16_scale_tolerance=0.0, fp16_scale_window=None, fp32_reduce_scatter=False, gen_subset='train', heartbeat_timeout=-1, iter_decode_eos_penalty=0.0, iter_decode_force_max_iter=False, iter_decode_max_iter=10, iter_decode_with_beam=1, iter_decode_with_external_reranker=False, keep_best_checkpoints=-1, keep_interval_updates=-1, keep_last_epochs=-1, kenlm_model='/root/dataset/checkpoints/restaurant_lm/checkpoint_best.pt', kspmodel=None, labels='ltr', lenpen=1, lexicon=None, lm_path=None, lm_weight=2.0, load_checkpoint_on_all_dp_ranks=False, load_emissions=None, localsgd_frequency=3, log_format=None, log_interval=100, lr_scheduler='fixed', lr_shrink=0.1, match_source_len=False, max_len_a=0, max_len_b=200, max_sample_size=None, max_tokens=4000000, max_tokens_valid=4000000, maximize_best_checkpoint_metric=False, memory_efficient_bf16=False, memory_efficient_fp16=False, min_len=1, min_loss_scale=0.0001, min_sample_size=None, model_overrides='{}', model_parallel_size=1, nbest=1, no_beamable_mm=False, no_early_stop=False, no_epoch_checkpoints=False, no_last_checkpoints=False, no_progress_bar=False, no_repeat_ngram_size=0, no_reshard_after_forward=False, no_save=False, no_save_optimizer_state=False, no_seed_provided=False, normalize=False, nprocs_per_node=1, num_shards=1, num_workers=1, optimizer=None, optimizer_overrides='{}', pad=1, path='/root/fairseq/outputs/2021-04-18/06-38-48/checkpoints/checkpoint_best.pt', patience=-1, pipeline_balance=None, pipeline_checkpoint='never', pipeline_chunks=0, pipeline_decoder_balance=None, pipeline_decoder_devices=None, pipeline_devices=None, pipeline_encoder_balance=None, pipeline_encoder_devices=None, pipeline_model_parallel=False, plasma_path='/tmp/plasma', post_process='letter', prefix_size=0, print_alignment=None, print_step=False, profile=False, quantization_config_path=None, quiet=False, replace_unk=None, required_batch_size_multiple=8, required_seq_len_multiple=1, reset_dataloader=False, reset_logging=False, reset_lr_scheduler=False, reset_meters=False, reset_optimizer=False, restore_file='checkpoint_last.pt', results_path='./', retain_dropout=False, retain_dropout_modules=None, retain_iter_history=False, rnnt_decoding_type='greedy', rnnt_len_penalty=-0.5, sacrebleu=False, sample_rate=16000, sampling=False, sampling_topk=-1, sampling_topp=-1.0, save_dir='checkpoints', save_interval=1, save_interval_updates=0, score_reference=False, scoring='bleu', seed=1, shard_id=0, sil_weight=0.0, simul_type=None, skip_invalid_size_inputs_valid_test=False, slowmo_algorithm='LocalSGD', slowmo_momentum=None, suppress_crashes=False, task='audio_pretraining', temperature=1.0, tensorboard_logdir=None, threshold_loss_scale=None, tokenizer=None, tpu=False, train_subset='train', unit_lm=False, unk=3, unk_weight=-inf, unkpen=0, unnormalized=False, use_plasma_view=False, user_dir=None, valid_subset='valid', validate_after_updates=0, validate_interval=1, validate_interval_updates=0, w2l_decoder='fairseqlm', wandb_project=None, warmup_updates=0, wer_args=None, wer_kenlm_model=None, wer_lexicon=None, wer_lm_weight=2.0, wer_word_score=-1.0, wfstlm=None, word_score=-1.0, write_checkpoints_asynchronously=False, zero_infinity=False, zero_sharding='none')
INFO:__main__:| decoding with criterion ctc
INFO:__main__:| loading model(s) from /root/fairseq/outputs/2021-04-18/06-38-48/checkpoints/checkpoint_best.pt
INFO:fairseq.data.audio.raw_audio_dataset:loaded 38, skipped 0 samples
INFO:__main__:| /root/dataset/restaurant_data/audio train 38 examples
Traceback (most recent call last):
  File "examples/speech_recognition/infer.py", line 427, in <module>
    cli_main()
  File "examples/speech_recognition/infer.py", line 423, in cli_main
    main(args)
  File "examples/speech_recognition/infer.py", line 283, in main
    generator = build_generator(args)
  File "examples/speech_recognition/infer.py", line 276, in build_generator
    return W2lFairseqLMDecoder(args, task.target_dictionary)
  File "/root/fairseq/examples/speech_recognition/w2l_decoder.py", line 383, in __init__
    with open_dict(lm_args.task):
AttributeError: 'dict' object has no attribute 'task'
```
The command i'm using to test this infer is:
```
python3 examples/speech_recognition/infer.py \
	/root/dataset/restaurant_data/audio \
	--task audio_pretraining \
	--nbest 1 \
	--path /root/fairseq/outputs/2021-04-18/06-38-48/checkpoints/checkpoint_best.pt \
	--gen-subset train \
	--results-path ./ \
	--w2l-decoder fairseqlm \
	--lm-model /root/dataset/checkpoints/restaurant_lm/checkpoint_best.pt \
	--lm-weight 2 \
	--word-score -1 \
	--sil-weight 0 \
	--criterion ctc \
	--labels ltr \
	--max-tokens 4000000 \
	--post-process letter 
```
I preprared the language model following [this](https://github.com/pytorch/fairseq/tree/master/examples/language_model) instructions.
When i'm using the `--w2l-decoder viterbi` without language model everything works fine. 
Environment:
ubuntu 20.04
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0
Docker version 20.10.5, build 55c4c88

**Comment by mukherjeesougata-eros** [comment]
Where have you added that line @RuABraun ?

**Comment by mukherjeesougata-eros** [comment]
Were you able to resolve that issue @roboticsai ?If yes then how?
