### ISSUE TITLE
max_positions error

### ISSUE THREAD

**Issue by ShiraKadosh** [pytorch/fairseq#349]
When finish first epoch I got this erro:

Traceback (most recent call last):
  File "/mlconvgec2018/software/fairseq-py/train.py", line 227, in <module>
    main()
  File "/mlconvgec2018/software/fairseq-py/train.py", line 102, in main
    val_loss = validate(args, epoch, trainer, criterion, dataset, subset, num_gpus)
  File "/mlconvgec2018/software/fairseq-py/train.py", line 193, in validate
    max_positions=args.max_positions)
  File "/mlconvgec2018/software/fairseq-py/fairseq/data.py", line 108, in dataloader
    max_positions=max_positions))
  File "/mlconvgec2018/software/fairseq-py/fairseq/data.py", line 229, in batches_by_size
 "size {} / {}.".format(idx, src.sizes[idx], dst.sizes[idx]))

Anyone can help understand what is the problem? 
Thanks

**Comment by ShiraKadosh** [comment]
I've noticed this post:
https://github.com/pytorch/fairseq/issues/44
And used --max-positions 16384, but the problem persists.
If I do not want to use the --skip-invalid-size-inputs-valid-test...
How can I solve this?

**Comment by myleott** [comment]
It looks like you’re using a very old version of fairseq. Are you able to update to the latest version?

That error indicates that the target is too small. In particular it says the source length is 4 and the target length is 1, but that includes the end-of-sentence marker, so actually your example has a target of length 0. Please fix this example in your data.

**Comment by ShiraKadosh** [comment]
Thanks @myleott that solve the problem, I just removed sentences with length shorter than 3 from my data set.
I wish to get the last version of fairseq but I'm using 
pytorch 0.2.0 is it possible?
