### ISSUE TITLE
`fairseq-train --help` raises error

### ISSUE THREAD

**Issue by louismartin** [pytorch/fairseq#3491]
`fairseq-train --help` raises error

I'm not sure if it's a bug on my install or if someone else can reproduce.
I installed fairseq from source using the latest version as of 19/04/2021.

```
(dev3.7) ~/tmp/camembert-base$ fairseq-train --help
WARNING:root:Torch AMP is not available on this platform
Traceback (most recent call last):
  File "/private/home/louismartin/miniconda3/envs/dev3.7/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/private/home/louismartin/dev/ext/fairseq/fairseq_cli/train.py", line 478, in cli_main
    args = options.parse_args_and_arch(parser, modify_parser=modify_parser)
  File "/private/home/louismartin/dev/ext/fairseq/fairseq/options.py", line 128, in parse_args_and_arch
    args, _ = parser.parse_known_args(input_args)
  File "/private/home/louismartin/miniconda3/envs/dev3.7/lib/python3.7/argparse.py", line 1781, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/private/home/louismartin/miniconda3/envs/dev3.7/lib/python3.7/argparse.py", line 1987, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/private/home/louismartin/miniconda3/envs/dev3.7/lib/python3.7/argparse.py", line 1927, in consume_optional
    take_action(action, args, option_string)
  File "/private/home/louismartin/miniconda3/envs/dev3.7/lib/python3.7/argparse.py", line 1855, in take_action
    action(self, namespace, argument_values, option_string)
  File "/private/home/louismartin/miniconda3/envs/dev3.7/lib/python3.7/argparse.py", line 1037, in __call__
    parser.print_help()
  File "/private/home/louismartin/miniconda3/envs/dev3.7/lib/python3.7/argparse.py", line 2474, in print_help
    self._print_message(self.format_help(), file)
  File "/private/home/louismartin/miniconda3/envs/dev3.7/lib/python3.7/argparse.py", line 2458, in format_help
    return formatter.format_help()
  File "/private/home/louismartin/miniconda3/envs/dev3.7/lib/python3.7/argparse.py", line 284, in format_help
    help = self._root_section.format_help()
  File "/private/home/louismartin/miniconda3/envs/dev3.7/lib/python3.7/argparse.py", line 215, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/private/home/louismartin/miniconda3/envs/dev3.7/lib/python3.7/argparse.py", line 215, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/private/home/louismartin/miniconda3/envs/dev3.7/lib/python3.7/argparse.py", line 215, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/private/home/louismartin/miniconda3/envs/dev3.7/lib/python3.7/argparse.py", line 215, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/private/home/louismartin/miniconda3/envs/dev3.7/lib/python3.7/argparse.py", line 525, in _format_action
    help_text = self._expand_help(action)
  File "/private/home/louismartin/miniconda3/envs/dev3.7/lib/python3.7/argparse.py", line 614, in _expand_help
    return self._get_help_string(action) % params
ValueError: unsupported format character 'k' (0x6b) at index 95
```

**Comment by cinjon** [comment]
Also getting this error when installing from source.

**Comment by lematt1991** [comment]
#3514 should resolve this.  Thanks for reporting!
