### ISSUE TITLE
Error in multi-node multi-gpu running with fairseq

### ISSUE THREAD

**Issue by Gavin90s** [pytorch/fairseq#3493]
## Error in multi-node multi-gpu running with fairseq

python3 -m torchelastic.distributed.launch  --nnodes=1:1 --rdzv_backend="etcd" --rdzv_endpoint="fission-elastic-etcd2.fission-system:2379" --rdzv_id=fairseq-wav2vec-pretrain-base-56p --nproc_per_node=8 --max_restarts=1 --rdzv_conf="timeout=86400" /workspace/train/././fairseq/fairseq-hydra-train.py --config-dir /workspace/train/fairseq/examples/wav2vec/config/pretraining --config-name wav2vec2_base_librispeech.yaml

---------------------------------------------------------------------
$cat wav2vec2_base_librispeech.yaml 
common:
  fp16: false
  log_format: json
  log_interval: 200

checkpoint:
  save_dir: /fairseq/model/wav2vec/zstart_gpu16_lr1e-04_maxtokens80k 
  save_interval_updates: 1000
  keep_interval_updates: 1
  no_epoch_checkpoints: true

task:
  _name: audio_pretraining
  data: /workspace/train/fairseq/manifest/train
  max_sample_size: 250000
  min_sample_size: 32000
  normalize: false

dataset:
  num_workers: 4
  max_tokens: 400000
  skip_invalid_size_inputs_valid_test: true

distributed_training:
  distributed_world_size: 8
  ddp_backend: legacy_ddp

criterion:
  _name: wav2vec
  infonce: true
  log_keys: ["prob_perplexity","code_perplexity","temp"]
  loss_weights: [0.1, 10]

optimization:
  max_update: 800000
  lr: [0.0001]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 32000

model:
  _name: wav2vec2
  quantize_targets: true
  final_dim: 256
  encoder_layerdrop: 0.05
  dropout_input: 0.1
  dropout_features: 0.1
  feature_grad_mult: 0.1
  encoder_embed_dim: 768

---------------------------------------------------------------------

[2021-04-20 07:07:16,784][fairseq.data.audio.raw_audio_dataset][INFO] - loaded 3164472, skipped 566116 samples
[2021-04-20 07:07:17,097][fairseq.tasks.fairseq_task][INFO] - dataset set epoch 1
Traceback (most recent call last):
  File "/workspace/train/fairseq/fairseq_cli/hydra_train.py", line 45, in hydra_main
    distributed_utils.call_main(cfg, pre_main)
  File "/workspace/train/fairseq/fairseq/distributed/utils.py", line 349, in call_main
    distributed_main(cfg.distributed_training.device_id, main, cfg, kwargs)
  File "/workspace/train/fairseq/fairseq/distributed/utils.py", line 326, in distributed_main
    main(cfg, **kwargs)
  File "/workspace/train/fairseq/fairseq_cli/train.py", line 126, in main
    disable_iterator_cache=task.has_sharded_data("train"),
  File "/workspace/train/fairseq/fairseq/checkpoint_utils.py", line 221, in load_checkpoint
    epoch=1, load_dataset=True, **passthrough_args
  File "/workspace/train/fairseq/fairseq/trainer.py", line 449, in get_train_iterator
    self.model.max_positions(),
  File "/workspace/train/fairseq/fairseq/trainer.py", line 199, in model
    device=self.device,
  File "/workspace/train/fairseq/fairseq/models/distributed_fairseq_model.py", line 71, in DistributedFairseqModel
    module=model.to(device),
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 607, in to
    return self._apply(convert)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 354, in _apply
    module._apply(fn)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 354, in _apply
    module._apply(fn)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 354, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 376, in _apply
    param_applied = fn(param)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 605, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 10.76 GiB total capacity; 343.91 MiB already allocated; 12.12 MiB free; 380.00 MiB reserved in total by PyTorch)

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
[ERROR] 2021-04-20 07:07:22,098 local_elastic_agent: [default] Worker group failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/torchelastic/agent/server/local_elastic_agent.py", line 190, in _monitor_workers
    if self._process_context.join(timeout=-1):
  File "/usr/local/lib64/python3.6/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 
 Process 4 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/usr/local/lib/python3.6/site-packages/torchelastic/agent/server/local_elastic_agent.py", line 79, in _wrap
    ret = fn(*args)
  File "/usr/local/lib/python3.6/site-packages/torchelastic/distributed/launch.py", line 392, in wrapper_fn
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-u', '/workspace/train/././fairseq/fairseq-hydra-train.py', '--config-dir', '/workspace/train/fairseq/examples/wav2vec/config/pretraining', '--config-name', 'wav2vec2_base_librispeech.yaml']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/torchelastic/distributed/launch.py", line 510, in <module>
    main()
  File "/usr/local/lib/python3.6/site-packages/torchelastic/distributed/launch.py", line 499, in main
    elastic_agent.run(spec.role)
  File "/usr/local/lib/python3.6/site-packages/torchelastic/agent/server/api.py", line 535, in run
    monitor_result.exceptions,
torchelastic.agent.server.api.WorkerGroupFailureException: [default] exceeded max_restarts=1
-------------------------------------------------

In one node multi-gpu mode, running the command below is ok.

fairseq-hydra-train --config-dir /workspace/train/fairseq/examples/wav2vec/config/pretraining --config-name wav2vec2_base_librispeech.yaml

-------------------------------------------------
Any help will be greatly appreciated!  @myleott @alexeib

**Comment by aijanai** [comment]
@Gavin90s would you please report how did you sort it out?

**Comment by heibaidaolx123** [comment]
Is there any example for fairseq-hydra-train multi-node training? @alexeib
