### ISSUE TITLE
omegaconf.errors.ValidationError: Invalid value 'simple', 

### ISSUE THREAD

**Issue by leonodelee** [pytorch/fairseq#3515]
### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd 'fairseq-generate $binarized_data_path --batch-size 32 --path /data2/liqiang/418M_last_checkpoint.pt --fixed-dictionary model_dict.128k.txt -s de -t fr --remove-bpe 'sentencepiece' --beam 5 --task translation_multi_simple_epoch --lang-pairs language_pairs_small_models.txt --decoder-langtok --encoder-langtok src --gen-subset test 
 '
2. See error
ERROR | fairseq.dataclass.utils | Error when composing. Overrides:[…]
…
omegaconf.errors.ValidationError: Invalid value 'simple', expected one of [c10d, fully_sharded, legacy_ddp, no_c10d, pytorch_ddp,_mo]
	full_key: distributed_training.ddp_backend
	reference_type=DistributedTrainingConfig
object_type=DistributedTrainingConfig

### Expected behavior

translation from de to fr 

### Environment

 - fairseq Version ( 1.0 or master):
 - PyTorch Version ( 1.0)
 - OS (Linux):
 - How you installed fairseq (source):
 - Build command you used (if compiling from source): pip install --editable ./
 - Python version: 3.8
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

### Additional context

Traceback (most recent call last):
  File "/data1/home/liqiang/anaconda3/envs/fairseq/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 513, pply_overrides_to_config
    OmegaConf.update(cfg, key, value, merge=True)
  File "/data1/home/liqiang/anaconda3/envs/fairseq/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 613, in update
    root.__setattr__(last_key, value)
  File "/data1/home/liqiang/anaconda3/envs/fairseq/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 286, in __setattr__
    self._format_and_raise(key=key, value=value, cause=e)
  File "/data1/home/liqiang/anaconda3/envs/fairseq/lib/python3.8/site-packages/omegaconf/base.py", line 95, in _format_and_raise
    format_and_raise(
  File "/data1/home/liqiang/anaconda3/envs/fairseq/lib/python3.8/site-packages/omegaconf/_utils.py", line 694, in format_and_rais
    _raise(ex, cause)
  File "/data1/home/liqiang/anaconda3/envs/fairseq/lib/python3.8/site-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.ValidationError: Invalid value 'simple', expected one of [c10d, fully_sharded, legacy_ddp, no_c10d, pytorch_ddp,_mo]
	full_key: distributed_training.ddp_backend
	reference_type=DistributedTrainingConfig
	object_type=DistributedTrainingConfig

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data1/home/liqiang/anaconda3/envs/fairseq/bin/fairseq-generate", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-generate')())
  File "/data1/home/liqiang/fairseq/fairseq_cli/generate.py", line 404, in cli_main
    main(args)
  File "/data1/home/liqiang/fairseq/fairseq_cli/generate.py", line 49, in main
    return _main(cfg, sys.stdout)
  File "/data1/home/liqiang/fairseq/fairseq_cli/generate.py", line 96, in _main
    models, saved_cfg = checkpoint_utils.load_model_ensemble(
  File "/data1/home/liqiang/fairseq/fairseq/checkpoint_utils.py", line 319, in load_model_ensemble
    ensemble, args, _task = load_model_ensemble_and_task(
  File "/data1/home/liqiang/fairseq/fairseq/checkpoint_utils.py", line 361, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/data1/home/liqiang/fairseq/fairseq/checkpoint_utils.py", line 295, in load_checkpoint_to_cpu
    state = _upgrade_state_dict(state)
  File "/data1/home/liqiang/fairseq/fairseq/checkpoint_utils.py", line 537, in _upgrade_state_dict
    state["cfg"] = convert_namespace_to_omegaconf(state["args"])
  File "/data1/home/liqiang/fairseq/fairseq/dataclass/utils.py", line 357, in convert_namespace_to_omegaconf
    composed_cfg = compose("config", overrides=overrides, strict=False)
  File "/data1/home/liqiang/anaconda3/envs/fairseq/lib/python3.8/site-packages/hydra/experimental/compose.py", line 31, in compos
    cfg = gh.hydra.compose_config(
  File "/data1/home/liqiang/anaconda3/envs/fairseq/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 507, in compose_co
    cfg = self.config_loader.load_configuration(
  File "/data1/home/liqiang/anaconda3/envs/fairseq/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 151, ad_configuration
    return self._load_configuration(
  File "/data1/home/liqiang/anaconda3/envs/fairseq/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 277, oad_configuration
    ConfigLoaderImpl._apply_overrides_to_config(config_overrides, cfg)
  File "/data1/home/liqiang/anaconda3/envs/fairseq/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 520, pply_overrides_to_config
    raise ConfigCompositionException(
hydra.errors.ConfigCompositionException: Error merging override distributed_training.ddp_backend='simple'

**Comment by nikhiljaiswal** [comment]
@leonodelee any updates on this? I am also facing the same issue.
