### ISSUE TITLE
Assertion error with audio_pretraining.py when using the infer.py script

### ISSUE THREAD

**Issue by aanchan** [pytorch/fairseq#3536]
### Before asking:   

I looked up the README here in trying to evaluate a CTC model: https://github.com/pytorch/fairseq/blob/master/examples/wav2vec/README.md#evaluating-a-ctc-model

## Related issue : https://github.com/pytorch/fairseq/issues/2734

I am running an equivalent command : `speech_recognition/infer.py . --task audio_pretraining --nbest 1 --path wav2vec_small_960h.pt --results-path /home/aanchan.mohan/work/data/results --w2l-decoder kenlm --lm-model lm_common_crawl_small_4gram_prun0-6-15_200kvocab.bin --lm-weight 2 --word-score -1 --sil-weight 0 --criterion ctc --labels ltr --max-tokens 4000000 --post-process letter --criterion ctc --lexicon lexicon.txt`

From the latest version of audio_pretraining.py I end up hitting an assertion from [this line](https://github.com/pytorch/fairseq/blob/a8c8f0be177649f8178fdcbae519c17894efd4d7/fairseq/tasks/audio_pretraining.py#L247) which appears like so:

 ```
INFO:__main__:Namespace(all_gather_list_size=16384, autoregressive=False, azureml_logging=False, batch_size=None, batch_size_valid=None, beam=5, beam_size_token=100, beam_threshold=25.0, best_checkpoint_metric='loss', bf16=False, binarized_dataset=False, bpe=None, broadcast_buffers=False, bucket_cap_mb=25, checkpoint_shard_count=1, checkpoint_suffix='', constraints=None, cpu=False, cpu_offload=False, criterion='ctc', curriculum=0, data='.', data_buffer_size=10, dataset_impl=None, ddp_backend='pytorch_ddp', decoding_format=None, device_id=0, disable_validation=False, distributed_backend='nccl', distributed_init_method=None, distributed_no_spawn=False, distributed_port=-1, distributed_rank=0, distributed_world_size=1, diverse_beam_groups=-1, diverse_beam_strength=0.5, diversity_rate=-1.0, dump_emissions=None, dump_features=None, empty_cache_freq=0, enable_padding=False, eos=2, eval_wer=False, eval_wer_post_process='letter', eval_wer_tokenizer=None, fast_stat_sync=False, find_unused_parameters=False, finetune_from_model=None, fix_batches_to_gpus=False, fixed_validation_seed=None, force_anneal=None, fp16=False, fp16_init_scale=128, fp16_no_flatten_grads=False, fp16_scale_tolerance=0.0, fp16_scale_window=None, fp32_reduce_scatter=False, gen_subset='test', heartbeat_timeout=-1, iter_decode_eos_penalty=0.0, iter_decode_force_max_iter=False, iter_decode_max_iter=10, iter_decode_with_beam=1, iter_decode_with_external_reranker=False, keep_best_checkpoints=-1, keep_interval_updates=-1, keep_interval_updates_pattern=-1, keep_last_epochs=-1, kenlm_model='lm_common_crawl_small_4gram_prun0-6-15_200kvocab.bin', kspmodel=None, labels='ltr', lenpen=1, lexicon='lexicon.txt', lm_path=None, lm_weight=2.0, load_checkpoint_on_all_dp_ranks=False, load_emissions=None, localsgd_frequency=3, log_file=None, log_format=None, log_interval=100, lr_scheduler='fixed', lr_shrink=0.1, match_source_len=False, max_len_a=0, max_len_b=200, max_sample_size=None, max_tokens=4000000, max_tokens_valid=4000000, max_valid_steps=None, maximize_best_checkpoint_metric=False, memory_efficient_bf16=False, memory_efficient_fp16=False, min_len=1, min_loss_scale=0.0001, min_sample_size=None, model_overrides='{}', model_parallel_size=1, nbest=1, no_beamable_mm=False, no_early_stop=False, no_epoch_checkpoints=False, no_last_checkpoints=False, no_progress_bar=False, no_repeat_ngram_size=0, no_reshard_after_forward=False, no_save=False, no_save_optimizer_state=False, no_seed_provided=False, normalize=False, nprocs_per_node=1, num_batch_buckets=0, num_shards=1, num_workers=1, optimizer=None, optimizer_overrides='{}', pad=1, path='wav2vec_small_960h.pt', patience=-1, pipeline_balance=None, pipeline_checkpoint='never', pipeline_chunks=0, pipeline_decoder_balance=None, pipeline_decoder_devices=None, pipeline_devices=None, pipeline_encoder_balance=None, pipeline_encoder_devices=None, pipeline_model_parallel=False, plasma_path='/tmp/plasma', post_process='letter', precompute_mask_indices=False, prefix_size=0, print_alignment=None, print_step=False, profile=False, quantization_config_path=None, quiet=False, replace_unk=None, required_batch_size_multiple=8, required_seq_len_multiple=1, reset_dataloader=False, reset_logging=False, reset_lr_scheduler=False, reset_meters=False, reset_optimizer=False, restore_file='checkpoint_last.pt', results_path='/home/aanchan.mohan/work/data/results', retain_dropout=False, retain_dropout_modules=None, retain_iter_history=False, rnnt_decoding_type='greedy', rnnt_len_penalty=-0.5, sacrebleu=False, sample_rate=16000, sampling=False, sampling_topk=-1, sampling_topp=-1.0, save_dir='checkpoints', save_interval=1, save_interval_updates=0, score_reference=False, scoring='bleu', seed=1, shard_id=0, sil_weight=0.0, simul_type=None, skip_invalid_size_inputs_valid_test=False, slowmo_algorithm='LocalSGD', slowmo_momentum=None, suppress_crashes=False, task='audio_pretraining', temperature=1.0, tensorboard_logdir=None, threshold_loss_scale=None, tokenizer=None, tpu=False, train_subset='train', unit_lm=False, unk=3, unk_weight=-inf, unkpen=0, unnormalized=False, use_plasma_view=False, user_dir=None, valid_subset='valid', validate_after_updates=0, validate_interval=1, validate_interval_updates=0, w2l_decoder='kenlm', wandb_project=None, warmup_updates=0, wer_args=None, wer_kenlm_model=None, wer_lexicon=None, wer_lm_weight=2.0, wer_word_score=-1.0, wfstlm=None, word_score=-1.0, write_checkpoints_asynchronously=False, zero_infinity=False, zero_sharding='none')
INFO:__main__:| decoding with criterion ctc
INFO:__main__:| loading model(s) from wav2vec_small_960h.pt
INFO:fairseq.data.audio.raw_audio_dataset:loaded 2703, skipped 0 samples
Traceback (most recent call last):
  File "/home/aanchan.mohan/work/pycharm/pycharm-community-2020.3.5/plugins/python-ce/helpers/pydev/pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/aanchan.mohan/work/pycharm/pycharm-community-2020.3.5/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/aanchan.mohan/work/fairseq/examples/speech_recognition/infer.py", line 427, in <module>
    cli_main()
  File "/home/aanchan.mohan/work/fairseq/examples/speech_recognition/infer.py", line 423, in cli_main
    main(args)
  File "/home/aanchan.mohan/work/fairseq/examples/speech_recognition/infer.py", line 239, in main
    task.load_dataset(args.gen_subset, task_cfg=saved_cfg.task)
  File "/home/aanchan.mohan/work/fairseq/fairseq/tasks/audio_pretraining.py", line 248, in load_dataset
    f"labels length ({len(labels)}) and dataset length "
AssertionError: labels length (28) and dataset length (2703) do not match
```

#### What have you tried?
It tries looking for a local letter file based on the manifest file name. I have a manifest file named `test.tsv` that looks like this:
```
home/aanchan.mohan/work/data/dev-clean/LibriSpeech
dev-clean/2078/142845/2078-142845-0019.flac	150480
dev-clean/2078/142845/2078-142845-0048.flac	35200
dev-clean/2078/142845/2078-142845-0031.flac	267840
dev-clean/2078/142845/2078-142845-0051.flac	165760
dev-clean/2078/142845/2078-142845-0012.flac	211840
dev-clean/2078/142845/2078-142845-0039.flac	335200
dev-clean/2078/142845/2078-142845-0035.flac	67520
dev-clean/2078/142845/2078-142845-0021.flac	98240
dev-clean/2078/142845/2078-142845-0041.flac	42560
dev-clean/2078/142845/2078-142845-0042.flac	67680
dev-clean/2078/142845/2078-142845-0034.flac	156080
dev-clean/2078/142845/2078-142845-0005.flac	502000
dev-clean/2078/142845/2078-142845-0013.flac	157680
```
I obtained the acoustic model from [here](https://github.com/pytorch/fairseq/tree/master/examples/wav2vec) as Wav2Vec 2.0 Base | 960 hours

I uppercased the vocabulary file and language model that I obtained from [here](https://github.com/flashlight/wav2letter/tree/master/recipes/rasr).

As the page says I obtained the letter dictionary from [here](https://dl.fbaipublicfiles.com/fairseq/wav2vec/dict.ltr.txt)
I renamed the letter dictionary to `test.ltr` as it specifically looks for that.

I could solve it if I knew the context for why that assertion had to be true. Clearly my letter file is something that it does not want. But I am not sure if I have the right letter file? Any help would be appreciated.

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0) : 1.8.1+cu102
 - OS (e.g., Linux): Ubuntu Bionic
 - How you installed fairseq (`pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: Python 3.7.5
 - CUDA/cuDNN version:CPU
 - GPU models and configuration: Model has been specified above
 - Any other relevant information:

**Comment by aanchan** [comment]
I did some more investigation. Removing the `--label ltr` _should_ avoid that code path. I now understand that the `--label` switch might be to provide a bunch of labels when training. So the need for the assert makes sense. But during inference, it should not really be needed. Removing it though throws up another bug : 

```
/speech_recognition/infer.py . --task audio_pretraining --nbest 1 --path wav2vec_small_960h.pt --results-path /home/aanchan.mohan/work/data/results --w2l-decoder kenlm --lm-model lm_common_crawl_small_4gram_prun0-6-15_200kvocab.bin --lm-weight 2 --word-score -1 --sil-weight 0 --criterion ctc --max-tokens 4000000 --post-process letter --criterion ctc --lexicon lexicon_upper.txt
Connected to pydev debugger (build 203.7717.81)
INFO:__main__:Namespace(all_gather_list_size=16384, autoregressive=False, azureml_logging=False, batch_size=None, batch_size_valid=None, beam=5, beam_size_token=100, beam_threshold=25.0, best_checkpoint_metric='loss', bf16=False, binarized_dataset=False, bpe=None, broadcast_buffers=False, bucket_cap_mb=25, checkpoint_shard_count=1, checkpoint_suffix='', constraints=None, cpu=False, cpu_offload=False, criterion='ctc', curriculum=0, data='.', data_buffer_size=10, dataset_impl=None, ddp_backend='pytorch_ddp', decoding_format=None, device_id=0, disable_validation=False, distributed_backend='nccl', distributed_init_method=None, distributed_no_spawn=False, distributed_port=-1, distributed_rank=0, distributed_world_size=1, diverse_beam_groups=-1, diverse_beam_strength=0.5, diversity_rate=-1.0, dump_emissions=None, dump_features=None, empty_cache_freq=0, enable_padding=False, eos=2, eval_wer=False, eval_wer_post_process='letter', eval_wer_tokenizer=None, fast_stat_sync=False, find_unused_parameters=False, finetune_from_model=None, fix_batches_to_gpus=False, fixed_validation_seed=None, force_anneal=None, fp16=False, fp16_init_scale=128, fp16_no_flatten_grads=False, fp16_scale_tolerance=0.0, fp16_scale_window=None, fp32_reduce_scatter=False, gen_subset='test', heartbeat_timeout=-1, iter_decode_eos_penalty=0.0, iter_decode_force_max_iter=False, iter_decode_max_iter=10, iter_decode_with_beam=1, iter_decode_with_external_reranker=False, keep_best_checkpoints=-1, keep_interval_updates=-1, keep_interval_updates_pattern=-1, keep_last_epochs=-1, kenlm_model='lm_common_crawl_small_4gram_prun0-6-15_200kvocab.bin', kspmodel=None, labels=None, lenpen=1, lexicon='lexicon_upper.txt', lm_path=None, lm_weight=2.0, load_checkpoint_on_all_dp_ranks=False, load_emissions=None, localsgd_frequency=3, log_file=None, log_format=None, log_interval=100, lr_scheduler='fixed', lr_shrink=0.1, match_source_len=False, max_len_a=0, max_len_b=200, max_sample_size=None, max_tokens=4000000, max_tokens_valid=4000000, max_valid_steps=None, maximize_best_checkpoint_metric=False, memory_efficient_bf16=False, memory_efficient_fp16=False, min_len=1, min_loss_scale=0.0001, min_sample_size=None, model_overrides='{}', model_parallel_size=1, nbest=1, no_beamable_mm=False, no_early_stop=False, no_epoch_checkpoints=False, no_last_checkpoints=False, no_progress_bar=False, no_repeat_ngram_size=0, no_reshard_after_forward=False, no_save=False, no_save_optimizer_state=False, no_seed_provided=False, normalize=False, nprocs_per_node=1, num_batch_buckets=0, num_shards=1, num_workers=1, optimizer=None, optimizer_overrides='{}', pad=1, path='wav2vec_small_960h.pt', patience=-1, pipeline_balance=None, pipeline_checkpoint='never', pipeline_chunks=0, pipeline_decoder_balance=None, pipeline_decoder_devices=None, pipeline_devices=None, pipeline_encoder_balance=None, pipeline_encoder_devices=None, pipeline_model_parallel=False, plasma_path='/tmp/plasma', post_process='letter', precompute_mask_indices=False, prefix_size=0, print_alignment=None, print_step=False, profile=False, quantization_config_path=None, quiet=False, replace_unk=None, required_batch_size_multiple=8, required_seq_len_multiple=1, reset_dataloader=False, reset_logging=False, reset_lr_scheduler=False, reset_meters=False, reset_optimizer=False, restore_file='checkpoint_last.pt', results_path='/home/aanchan.mohan/work/data/results', retain_dropout=False, retain_dropout_modules=None, retain_iter_history=False, rnnt_decoding_type='greedy', rnnt_len_penalty=-0.5, sacrebleu=False, sample_rate=16000, sampling=False, sampling_topk=-1, sampling_topp=-1.0, save_dir='checkpoints', save_interval=1, save_interval_updates=0, score_reference=False, scoring='bleu', seed=1, shard_id=0, sil_weight=0.0, simul_type=None, skip_invalid_size_inputs_valid_test=False, slowmo_algorithm='LocalSGD', slowmo_momentum=None, suppress_crashes=False, task='audio_pretraining', temperature=1.0, tensorboard_logdir=None, threshold_loss_scale=None, tokenizer=None, tpu=False, train_subset='train', unit_lm=False, unk=3, unk_weight=-inf, unkpen=0, unnormalized=False, use_plasma_view=False, user_dir=None, valid_subset='valid', validate_after_updates=0, validate_interval=1, validate_interval_updates=0, w2l_decoder='kenlm', wandb_project=None, warmup_updates=0, wer_args=None, wer_kenlm_model=None, wer_lexicon=None, wer_lm_weight=2.0, wer_word_score=-1.0, wfstlm=None, word_score=-1.0, write_checkpoints_asynchronously=False, zero_infinity=False, zero_sharding='none')
INFO:__main__:| decoding with criterion ctc
INFO:__main__:| loading model(s) from wav2vec_small_960h.pt
Traceback (most recent call last):
  File "/home/aanchan.mohan/work/pycharm/pycharm-community-2020.3.5/plugins/python-ce/helpers/pydev/pydevd.py", line 1477, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/aanchan.mohan/work/pycharm/pycharm-community-2020.3.5/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/aanchan.mohan/work/fairseq/examples/speech_recognition/infer.py", line 427, in <module>
    cli_main()
  File "/home/aanchan.mohan/work/fairseq/examples/speech_recognition/infer.py", line 423, in cli_main
    main(args)
  File "/home/aanchan.mohan/work/fairseq/examples/speech_recognition/infer.py", line 236, in main
    state=model_state,
  File "/home/aanchan.mohan/work/fairseq/fairseq/checkpoint_utils.py", line 389, in load_model_ensemble_and_task
    model.load_state_dict(state["model"], strict=strict, model_cfg=cfg.model)
  File "/home/aanchan.mohan/work/fairseq/fairseq/models/fairseq_model.py", line 125, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/home/aanchan.mohan/work/envs/flashlight/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1224, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Wav2VecCtc:
	Unexpected key(s) in state_dict: "w2v_encoder.proj.weight", "w2v_encoder.proj.bias". 
python-BaseException
```

Now I am at a loss to understand why it would think that the encoder parameters are unnecessary!
