### ISSUE TITLE
language modeling --distributed-no-spawn

### ISSUE THREAD

**Issue by apeterswu** [pytorch/fairseq#3538]
#### What is your question?
I try to run the language modeling task (wikitext-103) follow the example on 8 gpus. However, I found the issue when I using distributed_no_spawn or not. 
1. If I didn't use --distributed-no-spawn, the training will fill and comes out with this error:
```
Traceback (most recent call last):
  File "/opt/miniconda/bin/fairseq-train", line 8, in <module>
    sys.exit(cli_main())
  File "/opt/miniconda/lib/python3.7/site-packages/fairseq_cli/train.py", line 352, in cli_main
    distributed_utils.call_main(args, main)
  File "/opt/miniconda/lib/python3.7/site-packages/fairseq/distributed_utils.py", line 286, in call_main
    nprocs=args.distributed_num_procs,
  File "/opt/miniconda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/miniconda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/opt/miniconda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception:

-- Process 5 terminated with the following error:
Traceback (most recent call last):
  File "/opt/miniconda/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/opt/miniconda/lib/python3.7/site-packages/fairseq/distributed_utils.py", line 270, in distributed_main
    main(args, **kwargs)
  File "/opt/miniconda/lib/python3.7/site-packages/fairseq_cli/train.py", line 114, in main
    disable_iterator_cache=task.has_sharded_data("train"),
  File "/opt/miniconda/lib/python3.7/site-packages/fairseq/checkpoint_utils.py", line 213, in load_checkpoint
    epoch=1, load_dataset=True, **passthrough_args
  File "/opt/miniconda/lib/python3.7/site-packages/fairseq/trainer.py", line 382, in get_train_iterator
    self.reset_dummy_batch(batch_iterator.first_batch)
  File "/opt/miniconda/lib/python3.7/site-packages/fairseq/data/iterators.py", line 279, in first_batch
    return self.collate_fn([self.dataset[i] for i in self.frozen_batches[0]])
  File "/opt/miniconda/lib/python3.7/site-packages/fairseq/data/iterators.py", line 279, in <listcomp>
    return self.collate_fn([self.dataset[i] for i in self.frozen_batches[0]])
  File "/opt/miniconda/lib/python3.7/site-packages/fairseq/data/monolingual_dataset.py", line 104, in __getitem__
    source, future_target, past_target = self.dataset[index]
  File "/opt/miniconda/lib/python3.7/site-packages/fairseq/data/token_block_dataset.py", line 125, in __getitem__
    [self.dataset[idx] for idx in range(start_ds_idx, end_ds_idx + 1)]
  File "/opt/miniconda/lib/python3.7/site-packages/fairseq/data/token_block_dataset.py", line 125, in <listcomp>
    [self.dataset[idx] for idx in range(start_ds_idx, end_ds_idx + 1)]
  File "/opt/miniconda/lib/python3.7/site-packages/fairseq/data/indexed_dataset.py", line 234, in __getitem__
    ptx = self.cache_index[i]
KeyError: 1801347
```
It seems like the spawn or dataset problem. 

2. Therefore, when I add the --distributed-no-spawn option, it seems the job will only run on one gpu, and the process stucks, 
```
+ fairseq-train /blob2/v-lijuwu/data/lm_data/wikitext-103_bin --task language_modeling --arch transformer_lm --share-decoder-input-output-embed --save-dir /blob2/v-lijuwu/models/lm_transformer_lm_wikitext-103 --dropout 0.1 --optimizer adam --adam-betas '(0.9, 0.98)' --weight-decay 0.01 --clip-norm 0.0 --lr 0.0005 --lr-scheduler inverse_sqrt --warmup-updates 4000 --warmup-init-lr 1e-07 --tokens-per-sample 512 --sample-break-mode none --max-tokens 2048 --update-freq 16 --fp16 --ddp-backend=no_c10d --distributed-no-spawn --max-update 80000 --skip-invalid-size-inputs-valid-test --tensorboard-logdir /blob2/v-lijuwu/models/lm_transformer_lm_wikitext-103/tensorboard
2021-05-06 03:34:59 | INFO | fairseq.distributed_utils | distributed init (rank 0): tcp://localhost:15868
```
Could anyone help with the multi-gpu training language modeling? 

#### Code
The training script is like this:
```
export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7

fairseq-train $DATA_PATH \
  --task language_modeling \
  --arch $ARCH --share-decoder-input-output-embed \
  --save-dir $MODEL_PATH \
  --dropout 0.1 \
  --optimizer adam --adam-betas '(0.9, 0.98)' --weight-decay 0.01 --clip-norm 0.0 \
  --lr 0.0005 --lr-scheduler inverse_sqrt --warmup-updates 4000 --warmup-init-lr 1e-07 \
  --tokens-per-sample 512 --sample-break-mode none \
  --max-tokens 2048 --update-freq 16 \
  --fp16 --ddp-backend=no_c10d --distributed-no-spawn \
  --max-update 80000 --skip-invalid-size-inputs-valid-test \
  --tensorboard-logdir $MODEL_PATH/tensorboard
```
with or without --distributed-no-spawn 

#### What's your environment?

 - fairseq Version = 0.10.0:
 - PyTorch Version: 1.6
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): pip install
 - Python version: 3.7
 - CUDA/cuDNN version: 10.0
 - GPU models and configuration: v100

**Comment by apeterswu** [comment]
The problem comes from the different data process, I have an old version of processed wikitext-103 dataset. But it can not be compiled with the latest fairseq....
Therefore, I reprocess the data and it can run now.
