### ISSUE TITLE
Error when training LASER

### ISSUE THREAD

**Issue by virgulvirgul** [pytorch/fairseq#3540]
I tried to train LASER via example on examples/laser. 

I got an error

```
Traceback (most recent call last):
  File "/usr/local/bin/fairseq-train", line 8, in <module>
    sys.exit(cli_main())
  File "/usr/local/lib/python3.7/dist-packages/fairseq_cli/train.py", line 352, in cli_main
    distributed_utils.call_main(args, main)
  File "/usr/local/lib/python3.7/dist-packages/fairseq/distributed_utils.py", line 301, in call_main
    main(args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/fairseq_cli/train.py", line 114, in main
    disable_iterator_cache=task.has_sharded_data("train"),
  File "/usr/local/lib/python3.7/dist-packages/fairseq/checkpoint_utils.py", line 213, in load_checkpoint
    epoch=1, load_dataset=True, **passthrough_args
  File "/usr/local/lib/python3.7/dist-packages/fairseq/trainer.py", line 382, in get_train_iterator
    self.reset_dummy_batch(batch_iterator.first_batch)
AttributeError: 'MultidatasetEpochBatchIterator' object has no attribute 'first_batch'
```

My config.json:

```
{
  "src_vocab": "/de.en.bpe.cached/dict.de.txt",
  "tgt_vocab": "/de.en.bpe.cached/dict.en.txt",
  "train": [
    {
      "type": "translation",
      "id": 0,
      "src": "/de.en.bpe.cached/train.de-en.de",
      "tgt": "/de.en.bpe.cached/train.de-en.en"
    }
  ]
}
```

How can I fix this? Thanks!

**Comment by AlAntonov** [comment]
I've added 
@property
def first_batch(self):
    return "DUMMY"
to multitask_data_utils.py like https://github.com/search?q=EpochBatchIterating&type=commits And this helped me
