### ISSUE TITLE
wav2vecU missing import

### ISSUE THREAD

**Issue by BirgerMoell** [pytorch/fairseq#3567]
## 🐛 Bug

No module named 'speechproc' when running wav2vecU vads.py script inside colab

Traceback (most recent call last):
  File "scripts/vads.py", line 10, in <module>
    import speechproc
ModuleNotFoundError: No module named 'speechproc'

### To Reproduce
Inside a colab that has cloned the repo and downloaded common voice.
https://colab.research.google.com/drive/1JEHyCaeI5TKdOO9VEJ0RyRH_wCpjadPm?usp=sharing

1. !python scripts/vads.py /content/cv-corpus-6.1-2020-12-11/sv-SE/train.tsv train.vads

2. Traceback (most recent call last):
  File "scripts/vads.py", line 10, in <module>
    import speechproc
ModuleNotFoundError: No module named 'speechproc'

### Expected behavior
Expects the script to run and make a train.vads file

### Environment

 - fairseq Version (master):
 - PyTorch Version (1.8.1+cu101)
 - OS (Linux, colab):
 - How you installed fairseq (source):
 - Build command you used (git clone):
 - Python version: 3.7.10
 - CUDA/cuDNN version: colab setup
 - GPU models and configuration: colab setup
 - Any other relevant information: colab setup

### Additional context
Running inside google colab

**Comment by BirgerMoell** [comment]
I resolved it by downloading VADfast that was needed in order to use speechproc.

!git clone https://github.com/zhenghuatan/rVADfast
