### ISSUE TITLE
generate.py raise RuntimeError: inconsistent tensor size

### ISSUE THREAD

**Issue by ShiraKadosh** [pytorch/fairseq#357]
Hi, 
I run generate.py on trained fairseq model than run generate.py on test set, and got the next failure:
python3.5 /mlconvgec2018/software/fairseq-py/generate.py --no-progress-bar --path models/exp2_model/model1.pt --beam 1000 --nbest 1000 --interactive --workers 1000 processed/bin
Traceback (most recent call last):
  File "/mlconvgec2018/software/fairseq-py/generate.py", line 167, in <module>
    main()
  File "/mlconvgec2018/software/fairseq-py/generate.py", line 41, in main
    models, dataset = utils.load_ensemble_for_inference(args.path, args.data)
  File "/mlconvgec2018/software/fairseq-py/fairseq/utils.py", line 131, in load_ensemble_for_inference
    model.load_state_dict(state['model'])
  File "/usr/local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 388, in load_state_dict
    own_state[name].copy_(param)
RuntimeError: inconsistent tensor size, expected tensor [22947 x 500] and src [22933 x 500] to have the same number of elements, but got 11473500 and 11466500 elements respectively at /mlconvgec2018/software/fairseq-py/pytorch/torch/lib/TH/generic/THTensorCopy.c:86

Anyone can assist?
Thanks, Shira

**Comment by huihuifan** [comment]
It looks like generate.py is having issues loading the trained model, because it likely does not match in vocabulary size. Could you please check this?
