### ISSUE TITLE
wav2vec load_model_ensemble_and_task() not working for the example in README 

### ISSUE THREAD

**Issue by KangboLu** [pytorch/fairseq#3579]
## 🐛 Bug

The example snippet of the pretrained wav2vec model feature extraction doesn't work because the `speech_pretraining` key  
doesn't exist and returned a KeyError when loading the pretrained model.

```python
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([cp_path])
  File "D:\Anaconda3\envs\573\lib\site-packages\fairseq\checkpoint_utils.py", line 279, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "D:\Anaconda3\envs\573\lib\site-packages\fairseq\checkpoint_utils.py", line 232, in load_checkpoint_to_cpu
    state = _upgrade_state_dict(state)
  File "D:\Anaconda3\envs\573\lib\site-packages\fairseq\checkpoint_utils.py", line 434, in _upgrade_state_dict
    registry.set_defaults(state["args"], tasks.TASK_REGISTRY[state["args"].task])
KeyError: 'speech_pretraining'
```

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Create a .py script and copy the example code written below:
2. Download the model used below in the designated file path
3. Run the script you created above to get the error message mentioned above

Reference form the [README here](https://github.com/pytorch/fairseq/blob/master/examples/wav2vec/README.md) for the pre-trained model section:

## Pre-trained models

Description | Dataset | Model
---|---|---
Wav2Vec large | [Librispeech](http://www.openslr.org/12) | [download](https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_large.pt)

#### Example usage:
```python
import torch
import fairseq

cp_path = '/path/to/wav2vec.pt'
model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([cp_path])
model = model[0]
model.eval()

wav_input_16khz = torch.randn(1,10000)
z = model.feature_extractor(wav_input_16khz)
c = model.feature_aggregator(z)
```

### Expected behavior

This code chunk is expected to load the pretrained model and extract the features from the random example tensor.

### Environment

 - fairseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

Please help resolve the error for the wav2vec example mentioned in the README! Thanks.

**Comment by alexeib** [comment]
where did you get the checkpoint? i thought the ones we published were all upgraded to be compatible with public fairseq code

**Comment by alexeib** [comment]
how long ago did you download the checkpoint from there? speech_pretraining is my old dev branch. i just tried the wav2vec_large.pt and it is working (except for issue reported in #3574 which i am fixing)

**Comment by KangboLu** [comment]
I tried this one from the README example I mentioned above and got the error I listed above.
https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_large.pt
