### ISSUE TITLE
    raise EOFError("No valid references for a sentence!") EOFError: No valid references for a sentence!

### ISSUE THREAD

**Issue by fenimi** [pytorch/fairseq#3587]
I'm training an MT LSTM model but keep getting an error during validation after the first epoch. I have no empty lines in validation data and equal number of lines for the source and target. I will appreciate any help in solving this problem.

> 2021-06-01 07:42:50 | INFO | fairseq_cli.train | begin validation on "valid" subset
> /scratch/fenimi/fairseq/fairseq/utils.py:368: UserWarning: amp_C fused kernels unavailable, disabling multi_tensor_l2norm; you may get better performance by installing NVIDIA's apex library
>   warnings.warn(
> Traceback (most recent call last):
>   File "/home/fenimi/fairseqenv/bin/fairseq-train", line 33, in <module>
>     sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
>   File "/scratch/fenimi/fairseq/fairseq_cli/train.py", line 505, in cli_main
>     distributed_utils.call_main(cfg, main)
>   File "/scratch/fenimi/fairseq/fairseq/distributed/utils.py", line 369, in call_main
>     main(cfg, **kwargs)
>   File "/scratch/fenimi/fairseq/fairseq_cli/train.py", line 178, in main
>     valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
>   File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.2/lib/python3.8/contextlib.py", line 75, in inner
>     return func(*args, **kwds)
>   File "/scratch/fenimi/fairseq/fairseq_cli/train.py", line 303, in train
>     valid_losses, should_stop = validate_and_save(
>   File "/scratch/fenimi/fairseq/fairseq_cli/train.py", line 390, in validate_and_save
>     valid_losses = validate(cfg, trainer, task, epoch_itr, valid_subsets)
>   File "/scratch/fenimi/fairseq/fairseq_cli/train.py", line 460, in validate
>     trainer.valid_step(sample)
>   File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Core/python/3.8.2/lib/python3.8/contextlib.py", line 75, in inner
>     return func(*args, **kwds)
>   File "/scratch/fenimi/fairseq/fairseq/trainer.py", line 966, in valid_step
>     _loss, sample_size, logging_output = self.task.valid_step(
>   File "/scratch/fenimi/fairseq/fairseq/tasks/translation.py", line 385, in valid_step
>     bleu = self._inference_with_bleu(self.sequence_generator, sample, model)
>   File "/scratch/fenimi/fairseq/fairseq/tasks/translation.py", line 487, in _inference_with_bleu
>     return sacrebleu.corpus_bleu(hyps, [refs])
>   File "/home/fenimi/fairseqenv/lib/python3.8/site-packages/sacrebleu/compat.py", line 35, in corpus_bleu
>     return metric.corpus_score(
>   File "/home/fenimi/fairseqenv/lib/python3.8/site-packages/sacrebleu/metrics/bleu.py", line 286, in corpus_score
>     raise EOFError("No valid references for a sentence!")
> EOFError: No valid references for a sentence!

#### What's your environment?

 - fairseq Version: master
 - PyTorch Version:1.8.1
 - OS: linux
 - How you installed fairseq: source
 - Build command you used (if compiling from source): 
```
module load python
virtualenv --no-download newtorch
source newtorch/bin/activate
pip install --no-index torch
pip install --no-index torch torchvision torchtext torchaudio
git clone https://github.com/pytorch/fairseq
cd fairseq
pip install --editable ./
```
 - Python version: 3.8
 - CUDA/cuDNN version:
 - GPU models and configuration: Tesla V100-SXM2-32GB

**Comment by En-J-A** [comment]
Did you find a solution? @fenimi

**Comment by TingxunShi** [comment]
@fenimi @En-J-A I encountered the same problem. Please kindly check whether blank lines exist in your validation file, especially when you have sacrebleu >= 1.5.0

**Comment by En-J-A** [comment]
I really checked many times, there are no blank lines.

> @fenimi @En-J-A I encountered the same problem. Please kindly check whether blank lines exist in your validation file, especially when you have sacrebleu >= 1.5.0

**Comment by fenimi** [comment]
I found an empty line at the end of the file in one of the files. Once I removed the empty line, it started working.

**Comment by En-J-A** [comment]
"bump"
I really checked many times, there are no blank lines.
