### ISSUE TITLE
how to use many-to-one model setting of "Deep Transformers with Latent Depth"? 

### ISSUE THREAD

**Issue by tmtmaj** [pytorch/fairseq#3588]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?

how to use many-to-one model setting of "Deep Transformers with Latent Depth"? 

The script in example (`fairseq/examples/latent_depth/`) is only about one-to-many setting.

#### What have you tried?

I tried following setting for many-to-one (en,ru2zh) model.

```
lang_pairs_str="ru-zh,en-zh"
databin_dir={databin_dir}

CUDA_VISIBLE_DEVICES=0,1,2,3 fairseq-train ${databin_dir} \
  --user-dir examples/latent_depth/latent_depth_src \
  --lang-pairs "${lang_pairs_str}" \
  --arch latent_multilingual_transformer \
  --task multilingual_translation_latent_depth \
  --criterion label_smoothed_cross_entropy --label-smoothing 0.1 \
  --share-encoders \
  --share-decoders \
  --encoder-langtok "src"\
  --decoder-langtok \
  --share-decoder-input-output-embed \
  --dropout 0.3 --attention-dropout 0.3 \
  --optimizer adam --adam-eps 1e-06 --adam-betas '(0.9, 0.98)' \
  --lr-scheduler inverse_sqrt --stop-min-lr 1e-9 --warmup-init-lr 1e-7 --warmup-updates 8000 \
  --max-tokens 4096 --update-freq 8  \
  --lr 0.0015 \
  --clip-norm 1.0 \
  --seed 42 \
  --ddp-backend=legacy_ddp \
  --encoder-layers 24 \
  --decoder-layers 24 \
  --decoder-latent-layer \
  --encoder-latent-layer \
  --sparsity-weight 0.1 \
  --anneal-updates 5000 \
  --soft-update 500  \
  --target-layers 12 \
  --share-weight 0.1
```

```
2021-06-02 13:42:20 | INFO | fairseq_cli.train | Start iterating over samples
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home1/irteam/.pyenv/versions/3.6.5/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/home1/irteam/.pyenv/versions/3.6.5/lib/python3.6/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated
Traceback (most recent call last):
  File "/home1/irteam/.pyenv/versions/3.6.5/lib/python3.6/multiprocessing/resource_sharer.py", line 142, in _serve
    with self._listener.accept() as conn:
  File "/home1/irteam/.pyenv/versions/3.6.5/lib/python3.6/multiprocessing/connection.py", line 456, in accept
    answer_challenge(c, self._authkey)
  File "/home1/irteam/.pyenv/versions/3.6.5/lib/python3.6/multiprocessing/connection.py", line 737, in answer_challenge
    response = connection.recv_bytes(256)        # reject large message
  File "/home1/irteam/.pyenv/versions/3.6.5/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home1/irteam/.pyenv/versions/3.6.5/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home1/irteam/.pyenv/versions/3.6.5/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/home1/irteam/.pyenv/versions/jhpark_3.6.5/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/home1/irteam/users/parkjh/fairseq_210427/fairseq_cli/train.py", line 496, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home1/irteam/users/parkjh/fairseq_210427/fairseq/distributed/utils.py", line 351, in call_main
    join=True,
  File "/home1/irteam/.pyenv/versions/jhpark_3.6.5/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home1/irteam/.pyenv/versions/jhpark_3.6.5/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home1/irteam/.pyenv/versions/jhpark_3.6.5/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/home1/irteam/.pyenv/versions/jhpark_3.6.5/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home1/irteam/users/parkjh/fairseq_210427/fairseq/distributed/utils.py", line 328, in distributed_main
    main(cfg, **kwargs)
  File "/home1/irteam/users/parkjh/fairseq_210427/fairseq_cli/train.py", line 173, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/home1/irteam/.pyenv/versions/3.6.5/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home1/irteam/users/parkjh/fairseq_210427/fairseq_cli/train.py", line 284, in train
    log_output = trainer.train_step(samples)
  File "/home1/irteam/.pyenv/versions/3.6.5/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home1/irteam/users/parkjh/fairseq_210427/fairseq/trainer.py", line 674, in train_step
    ignore_grad=is_dummy_batch,
  File "/home1/irteam/users/parkjh/fairseq_210427/examples/latent_depth/latent_depth_src/multilingual_translation_latent_depth.py", line 119, in train_step
    sample, model, criterion, optimizer, update_num, ignore_grad
  File "/home1/irteam/users/parkjh/fairseq_210427/fairseq/tasks/multilingual_translation.py", line 365, in train_step
    ignore_grad,
  File "/home1/irteam/users/parkjh/fairseq_210427/examples/latent_depth/latent_depth_src/multilingual_translation_latent_depth.py", line 102, in _per_lang_pair_train_loss
    sample_size,
  File "/home1/irteam/.pyenv/versions/jhpark_3.6.5/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home1/irteam/users/parkjh/fairseq_210427/examples/latent_depth/latent_depth_src/loss/latent_depth.py", line 37, in forward
    kl_loss /= layer_samples[0].size()[0]
AttributeError: 'NoneType' object has no attribute 'size'
```

does anyone know a suitable configuration for many-to-one model?
thanks:)

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): 1
 - PyTorch Version (e.g., 1.0):1.8.1
 - OS (e.g., Linux):CentOS
 - How you installed fairseq (`pip`, source):pip 
 - Build command you used (if compiling from source):
 - Python version:3.6.7
 - CUDA/cuDNN version:10.2
 - GPU models and configuration:4 P40
 - Any other relevant information:

**Comment by michelleqyhqyh** [comment]
How did you solve this issure?
