### ISSUE TITLE
Loading HuBERT pretrained model, dictionaries cannot be properly loaded.

### ISSUE THREAD

**Issue by unilight** [pytorch/fairseq#3624]
## 🐛 Bug

I want to extract pretrained representations from HuBERT. Following https://github.com/pytorch/fairseq/tree/master/examples/hubert#load-a-pretrained-model, when loading a pretrained model from the provided checkpoints, something related to the dictionaries caused some errors.

### To Reproduce

1. Install the latest fairseq from source and download the pretrained model checkpoint.
2. Run the following with python. 
```
ckpt_path = "/path/to/the/checkpoint.pt"
models, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([ckpt_path], strict=False)
```
The stack trace:
```
...
  File "/home/huang18/VC/Experiments/espnet/tools/venv/envs/espnet/lib/python3.7/site-packages/fairseq/checkpoint_utils.py", line 446, in load_model_ensemble_and_task
    model = task.build_model(cfg.model)
  File "/home/huang18/VC/Experiments/espnet/tools/venv/envs/espnet/lib/python3.7/site-packages/fairseq/tasks/fairseq_task.py", line 324, in build_model
    model = models.build_model(cfg, self)
  File "/home/huang18/VC/Experiments/espnet/tools/venv/envs/espnet/lib/python3.7/site-packages/fairseq/models/__init__.py", line 96, in build_model
    return model.build_model(cfg, task)
  File "/home/huang18/VC/Experiments/espnet/tools/venv/envs/espnet/lib/python3.7/site-packages/fairseq/models/hubert/hubert.py", line 322, in build_model
    model = HubertModel(cfg, task.cfg, task.dictionaries)
  File "/home/huang18/VC/Experiments/espnet/tools/venv/envs/espnet/lib/python3.7/site-packages/fairseq/models/hubert/hubert.py", line 299, in __init__
    if any([d is None for d in dictionaries]):
TypeError: 'method' object is not iterable
```

If I print the `dictionaries`, it gives `<bound method HubertPretrainingTask.load_dictionaries of <fairseq.tasks.hubert_pretraining.HubertPretrainingTask object at 0x7fa533d4e2b0>>`. I think it is a function defined here: https://github.com/pytorch/fairseq/blob/afc77bdf4bb51453ce76f1572ef2ee6ddcda8eeb/fairseq/tasks/hubert_pretraining.py#L148. Instead of returning the dictionary, I think the function itself is mistakenly returned. I don't know if this is some error related to the codebase or the contents in the checkpoints.

### Expected behavior

Successful load of pretrained model.

### Environment

 - fairseq Version (e.g., 1.0 or master): fairseq-1.0.0a0+afc77bd
 - PyTorch Version (e.g., 1.0): 1.8.1
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source): `pip install --upgrade git+https://github.com/pytorch/fairseq.git`
 - Python version: 3.7
 - CUDA/cuDNN version: 11.2
 - GPU models and configuration: Not related
 - Any other relevant information: none.

### Additional context

None.

**Comment by xaiguy** [comment]
I got the same problem when trying to use the model for pretraining and finetuning. My environment matches the OP's, except that I installed with "pip install --editable ./".

**Comment by xiyue961** [comment]
fairseq/fairseq/tasks/hubert_pretraining.py  
  def load_dictionaries(self):
        label_dir = self.cfg.data if self.cfg.label_dir is None else self.cfg.label_dir
        dictionaries = [Dictionary.load(f"{label_dir}/dict.{label}.txt") for label in self.cfg.labels]
        return dictionaries[0] if self.cfg.fine_tuning else dictionaries

Here, what is this file "dict.{label}.txt"? It seems that the Kmeans training stage didn't generate this kind of file but the HuBERT pretraining stage needs to load this file.

**Comment by kfmn** [comment]
I have similar problems. I am trying to load a pretrained HuBERT model with the following simple code:

```
import fairseq

ckpt_path = "./hubert_large_ll60k.pt"
models, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([ckpt_path], strict=False)
```

While loading an error occurs with the following stack messages:

Traceback (most recent call last):
  File "simplest_example.py", line 4, in <module>
    models, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([ckpt_path], strict=False)
  File "/mnt/lc/korenevsky/fairseq/fairseq/checkpoint_utils.py", line 446, in load_model_ensemble_and_task
    model = task.build_model(cfg.model)
  File "/mnt/lc/korenevsky/fairseq/fairseq/tasks/fairseq_task.py", line 324, in build_model
    model = models.build_model(cfg, self)
  File "/mnt/lc/korenevsky/fairseq/fairseq/models/__init__.py", line 96, in build_model
    return model.build_model(cfg, task)
  File "/mnt/lc/korenevsky/fairseq/fairseq/models/hubert/hubert.py", line 321, in build_model
    model = HubertModel(cfg, task.cfg, task.dictionaries)
  File "/mnt/lc/korenevsky/fairseq/fairseq/tasks/hubert_pretraining.py", line 140, in dictionaries
    return self.state.dictionaries
  File "/mnt/lc/korenevsky/fairseq/fairseq/tasks/fairseq_task.py", line 41, in __getattr__
    self._state[name] = self._factories[name]()
  File "/mnt/lc/korenevsky/fairseq/fairseq/tasks/hubert_pretraining.py", line 150, in load_dictionaries
    dictionaries = [Dictionary.load(f"{label_dir}/dict.{label}.txt") for label in self.cfg.labels]
  File "/mnt/lc/korenevsky/fairseq/fairseq/tasks/hubert_pretraining.py", line 150, in <listcomp>
    dictionaries = [Dictionary.load(f"{label_dir}/dict.{label}.txt") for label in self.cfg.labels]
  File "/mnt/lc/korenevsky/fairseq/fairseq/data/dictionary.py", line 216, in load
    d.add_from_file(f)
  File "/mnt/lc/korenevsky/fairseq/fairseq/data/dictionary.py", line 229, in add_from_file
    raise fnfe
  File "/mnt/lc/korenevsky/fairseq/fairseq/data/dictionary.py", line 226, in add_from_file
    with open(PathManager.get_local_path(f), "r", encoding="utf-8") as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/checkpoint/wnhsu/experiments/hubert/kmeans_20210121/km_dataset_librivox.model_iter_2.all/dict.lyr9.km500.txt'


It seems like the code tries to load dictionary from the wrong path **/checkpoint/wnhsu/experiments/hubert/kmeans_20210121/km_dataset_librivox.model_iter_2.all/dict.lyr9.km500.txt** and fails

The error occurs on both pretrained models hubert_base_ls960.pt and hubert_large_ll60k.pt but DOES NOT occur on finetuned model hubert_large_ll60k_finetune_ls960.pt

**Comment by unilight** [comment]
For those looking for a quick fix: if you are just trying to **extract representations** (like me), you can add `return` at this line: https://github.com/pytorch/fairseq/blob/afc77bdf4bb51453ce76f1572ef2ee6ddcda8eeb/fairseq/models/hubert/hubert.py#L289 since the `dictionaries` variable is not referred to before this line.
**Disclaimer**: Not so sure if this is safe when you want to **perform fine-tuning**.

**Comment by chiluen** [comment]
@xiyue961 
I find out a useful link :
https://github.com/pytorch/fairseq/issues/2514

Just create a dict.km.txt file like below:
the first column is the labels which occur in train.km
the second column is the count of each label
It's work for me to pretrain HuBERT
```
10 100
23 300
35 500
...
```

**Comment by mthrok** [comment]
I looked at the commit history  https://github.com/pytorch/fairseq/commits/82e8a24bddc1cb5aecb267bb529f76f5b3901432/fairseq/tasks/hubert_pretraining.py and tried the past commits.

I could load all the HuBERT weights with e47a4c84da877382c4d37941be4e84449f99d186 and afc77bdf4bb51453ce76f1572ef2ee6ddcda8eeb, but 82e8a24bddc1cb5aecb267bb529f76f5b3901432 and 4aef9036cef814a24193dff3a678ce0f5c27309f caused an issue.

*note* this might change if they update the weights

Here are the configurations I have

<detail>

```
$ python -m 'torch.utils.collect_env'
Collecting environment information...
PyTorch version: 1.10.0.dev20210804
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.5.2 (x86_64)
GCC version: Could not collect
Clang version: 11.0.0 (clang-1100.0.33.16)
CMake version: version 3.20.2
Libc version: N/A

Python version: 3.8.5 (default, Sep  4 2020, 02:22:02)  [Clang 10.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.2
[pip3] pytorch-sphinx-theme==0.0.24
[pip3] torch==1.10.0.dev20210804
[pip3] torchaudio==0.10.0a0+8c85716
[conda] blas                      1.0                         mkl
[conda] mkl                       2021.2.0           hecd8cb5_269
[conda] mkl-service               2.3.0            py38h9ed2024_1
[conda] mkl_fft                   1.3.0            py38h4a7008c_2
[conda] mkl_random                1.2.1            py38hb2f4e1b_2
[conda] numpy                     1.20.2           py38h4b4dc7a_0
[conda] numpy-base                1.20.2           py38he0bd621_0
[conda] pytorch                   1.10.0.dev20210804         py3.8_0    pytorch-nightly
[conda] pytorch-sphinx-theme      0.0.24                   pypi_0    pypi
[conda] torch                     1.10.0.dev20210619          pypi_0    pypi
[conda] torchaudio                0.10.0a0+8c85716           dev_0    <develop>
```

```
$ gsha256sum hubert_*.pt
1703cf8d2cdc76f8c046f5f6a9bcd224e0e6caf4744cad1a1f4199c32cac8c8d  hubert_base_ls960.pt
c345287731fb3225a5cd0018fa5be4d8e87dd822a23e5410ef86db8544fcdcc3  hubert_large_ll60k.pt
1e37fb43b13f3f160625196bb81e3a29c5faf9df65e77e9ca1d0f5871cf97c0d  hubert_large_ll60k_finetune_ls960.pt
fccbc93bd2a3e5df248f99d2e048a991929b8ab6f050f2aa9471a116453882dc  hubert_xtralarge_ll60k.pt
2ae5e887d2251e71c84a09b30cb4962247c0124292e05bee1834892311b0f028  hubert_xtralarge_ll60k_finetune_ls960.pt
```
</detail>

**Comment by wnhsu** [comment]
Hi, we have updated the pre-trained checkpoints to include the dictionary in task_state. This should prevent the model from loading the dictionary from the disk.

https://github.com/pytorch/fairseq/blob/main/fairseq/checkpoint_utils.py#L434-L435
https://github.com/pytorch/fairseq/blob/main/fairseq/tasks/fairseq_task.py#L44-L45

Please make sure you use the latest commit and re-download the pre-trained models. Thanks.

**Comment by wnhsu** [comment]
> I looked at the commit history https://github.com/pytorch/fairseq/commits/82e8a24bddc1cb5aecb267bb529f76f5b3901432/fairseq/tasks/hubert_pretraining.py and tried the past commits.
> 
> I could load all the HuBERT weights with [e47a4c8](https://github.com/pytorch/fairseq/commit/e47a4c84da877382c4d37941be4e84449f99d186) and [afc77bd](https://github.com/pytorch/fairseq/commit/afc77bdf4bb51453ce76f1572ef2ee6ddcda8eeb), but [82e8a24](https://github.com/pytorch/fairseq/commit/82e8a24bddc1cb5aecb267bb529f76f5b3901432) and [4aef903](https://github.com/pytorch/fairseq/commit/4aef9036cef814a24193dff3a678ce0f5c27309f) caused an issue.
> 
> _note_ this might change if they update the weights
> 
> Here are the configurations I have
> 
> ```
> $ python -m 'torch.utils.collect_env'
> Collecting environment information...
> PyTorch version: 1.10.0.dev20210804
> Is debug build: False
> CUDA used to build PyTorch: None
> ROCM used to build PyTorch: N/A
> 
> OS: macOS 11.5.2 (x86_64)
> GCC version: Could not collect
> Clang version: 11.0.0 (clang-1100.0.33.16)
> CMake version: version 3.20.2
> Libc version: N/A
> 
> Python version: 3.8.5 (default, Sep  4 2020, 02:22:02)  [Clang 10.0.0 ] (64-bit runtime)
> Python platform: macOS-10.16-x86_64-i386-64bit
> Is CUDA available: False
> CUDA runtime version: No CUDA
> GPU models and configuration: No CUDA
> Nvidia driver version: No CUDA
> cuDNN version: No CUDA
> HIP runtime version: N/A
> MIOpen runtime version: N/A
> 
> Versions of relevant libraries:
> [pip3] numpy==1.20.2
> [pip3] pytorch-sphinx-theme==0.0.24
> [pip3] torch==1.10.0.dev20210804
> [pip3] torchaudio==0.10.0a0+8c85716
> [conda] blas                      1.0                         mkl
> [conda] mkl                       2021.2.0           hecd8cb5_269
> [conda] mkl-service               2.3.0            py38h9ed2024_1
> [conda] mkl_fft                   1.3.0            py38h4a7008c_2
> [conda] mkl_random                1.2.1            py38hb2f4e1b_2
> [conda] numpy                     1.20.2           py38h4b4dc7a_0
> [conda] numpy-base                1.20.2           py38he0bd621_0
> [conda] pytorch                   1.10.0.dev20210804         py3.8_0    pytorch-nightly
> [conda] pytorch-sphinx-theme      0.0.24                   pypi_0    pypi
> [conda] torch                     1.10.0.dev20210619          pypi_0    pypi
> [conda] torchaudio                0.10.0a0+8c85716           dev_0    <develop>
> ```
> 
> ```
> $ sha256sum hubert_*.pt
> 1703cf8d2cdc76f8c046f5f6a9bcd224e0e6caf4744cad1a1f4199c32cac8c8d  hubert_base_ls960.pt
> c345287731fb3225a5cd0018fa5be4d8e87dd822a23e5410ef86db8544fcdcc3  hubert_large_ll60k.pt
> 1e37fb43b13f3f160625196bb81e3a29c5faf9df65e77e9ca1d0f5871cf97c0d  hubert_large_ll60k_finetune_ls960.pt
> fccbc93bd2a3e5df248f99d2e048a991929b8ab6f050f2aa9471a116453882dc  hubert_xtralarge_ll60k.pt
> 2ae5e887d2251e71c84a09b30cb4962247c0124292e05bee1834892311b0f028  hubert_xtralarge_ll60k_finetune_ls960.pt
> ```

could you share what was the error message when you use the latest branch to load the checkpoints?

**Comment by cshanbo** [comment]
> 

still not working in 2022 :)  main branch

**Comment by cshanbo** [comment]
> Hi, we have updated the pre-trained checkpoints to include the dictionary in task_state. This should prevent the model from loading the dictionary from the disk.
> 
> https://github.com/pytorch/fairseq/blob/main/fairseq/checkpoint_utils.py#L434-L435 https://github.com/pytorch/fairseq/blob/main/fairseq/tasks/fairseq_task.py#L44-L45
> 
> Please make sure you use the latest commit and re-download the pre-trained models. Thanks.

Still doesn't work in 2022. When loading `hubert_large_ll60k_finetune_ls960.pt`, the error log says
```
2022-01-27 16:42:27 | INFO | fairseq.tasks.hubert_pretraining | HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': '/checkpoint/abdo/old_checkpoint02/datasets/librispeech/960h/raw', 'fine_tuning': False, 'labels': ['ltr'], 'label_dir': None, 'label_rate': -1, 'sample_rate': 16000, 'normalize': True, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': None, 'min_sample_size': None, 'single_target': True, 'random_crop': False, 'pad_audio': False}
2022-01-27 16:42:27 | INFO | fairseq.tasks.hubert_pretraining | current directory is /data00/home/chengshanbo/workspace/hubert_test
2022-01-27 16:42:27 | INFO | fairseq.tasks.hubert_pretraining | HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': '/checkpoint/abdo/old_checkpoint02/datasets/librispeech/960h/raw', 'fine_tuning': False, 'labels': ['lyr9.km500'], 'label_dir': '/checkpoint/wnhsu/experiments/hubert/kmeans_20210121/km_dataset_librivox.model_iter_2.all', 'label_rate': 50, 'sample_rate': 16000, 'normalize': True, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False}
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    models, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([ckpt_path])
  File "/data00/home/chengshanbo/workspace/codes/fairseq/fairseq/checkpoint_utils.py", line 469, in load_model_ensemble_and_task
    model = task.build_model(cfg.model, from_checkpoint=True)
  File "/data00/home/chengshanbo/workspace/codes/fairseq/fairseq/tasks/fairseq_task.py", line 335, in build_model
    model = models.build_model(cfg, self, from_checkpoint)
  File "/data00/home/chengshanbo/workspace/codes/fairseq/fairseq/models/__init__.py", line 106, in build_model
    return model.build_model(cfg, task)
  File "/data00/home/chengshanbo/workspace/codes/fairseq/fairseq/models/hubert/hubert_asr.py", line 146, in build_model
    w2v_encoder = HubertEncoder(cfg, task.target_dictionary)
  File "/data00/home/chengshanbo/workspace/codes/fairseq/fairseq/models/hubert/hubert_asr.py", line 272, in __init__
    model = task.build_model(w2v_args.model, from_checkpoint=True)
  File "/data00/home/chengshanbo/workspace/codes/fairseq/fairseq/tasks/fairseq_task.py", line 335, in build_model
    model = models.build_model(cfg, self, from_checkpoint)
  File "/data00/home/chengshanbo/workspace/codes/fairseq/fairseq/models/__init__.py", line 106, in build_model
    return model.build_model(cfg, task)
  File "/data00/home/chengshanbo/workspace/codes/fairseq/fairseq/models/hubert/hubert.py", line 307, in build_model
    model = HubertModel(cfg, task.cfg, task.dictionaries)
  File "/data00/home/chengshanbo/workspace/codes/fairseq/fairseq/tasks/hubert_pretraining.py", line 139, in dictionaries
    return self.state.dictionaries
  File "/data00/home/chengshanbo/workspace/codes/fairseq/fairseq/tasks/fairseq_task.py", line 41, in __getattr__
    self._state[name] = self._factories[name]()
  File "/data00/home/chengshanbo/workspace/codes/fairseq/fairseq/tasks/hubert_pretraining.py", line 151, in load_dictionaries
    for label in self.cfg.labels
  File "/data00/home/chengshanbo/workspace/codes/fairseq/fairseq/tasks/hubert_pretraining.py", line 151, in <listcomp>
    for label in self.cfg.labels
  File "/data00/home/chengshanbo/workspace/codes/fairseq/fairseq/data/dictionary.py", line 226, in load
    d.add_from_file(f)
  File "/data00/home/chengshanbo/workspace/codes/fairseq/fairseq/data/dictionary.py", line 239, in add_from_file
    raise fnfe
  File "/data00/home/chengshanbo/workspace/codes/fairseq/fairseq/data/dictionary.py", line 236, in add_from_file
    with open(PathManager.get_local_path(f), "r", encoding="utf-8") as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/checkpoint/wnhsu/experiments/hubert/kmeans_20210121/km_dataset_librivox.model_iter_2.all/dict.lyr9.km500.txt'
```

While loading other models, eg `hubert_large_ll60k.pt`, the log says
```
  File "/data00/home/chengshanbo/workspace/codes/fairseq/fairseq/checkpoint_utils.py", line 469, in load_model_ensemble_and_task
    model = task.build_model(cfg.model, from_checkpoint=True)
  File "/data00/home/chengshanbo/workspace/codes/fairseq/fairseq/tasks/fairseq_task.py", line 335, in build_model
    model = models.build_model(cfg, self, from_checkpoint)
  File "/data00/home/chengshanbo/workspace/codes/fairseq/fairseq/models/__init__.py", line 106, in build_model
    return model.build_model(cfg, task)
  File "/data00/home/chengshanbo/workspace/codes/fairseq/fairseq/models/hubert/hubert.py", line 307, in build_model
    model = HubertModel(cfg, task.cfg, task.dictionaries)
  File "/data00/home/chengshanbo/workspace/codes/fairseq/fairseq/models/hubert/hubert.py", line 270, in __init__
    self.encoder = TransformerEncoder(cfg)
  File "/data00/home/chengshanbo/workspace/codes/fairseq/fairseq/models/wav2vec/wav2vec2.py", line 952, in __init__
    self.required_seq_len_multiple = args.required_seq_len_multiple
  File "/data00/home/chengshanbo/miniconda3/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 305, in __getattr__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/data00/home/chengshanbo/miniconda3/lib/python3.7/site-packages/omegaconf/base.py", line 101, in _format_and_raise
    type_override=type_override,
  File "/data00/home/chengshanbo/miniconda3/lib/python3.7/site-packages/omegaconf/_utils.py", line 629, in format_and_raise
    _raise(ex, cause)
  File "/data00/home/chengshanbo/miniconda3/lib/python3.7/site-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
  File "/data00/home/chengshanbo/miniconda3/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 303, in __getattr__
    return self._get_impl(key=key, default_value=DEFAULT_VALUE_MARKER)
  File "/data00/home/chengshanbo/miniconda3/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 361, in _get_impl
    node = self._get_node(key=key)
  File "/data00/home/chengshanbo/miniconda3/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 383, in _get_node
    self._validate_get(key)
  File "/data00/home/chengshanbo/miniconda3/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 136, in _validate_get
    key=key, value=value, cause=ConfigAttributeError(msg)
  File "/data00/home/chengshanbo/miniconda3/lib/python3.7/site-packages/omegaconf/base.py", line 101, in _format_and_raise
    type_override=type_override,
  File "/data00/home/chengshanbo/miniconda3/lib/python3.7/site-packages/omegaconf/_utils.py", line 694, in format_and_raise
    _raise(ex, cause)
  File "/data00/home/chengshanbo/miniconda3/lib/python3.7/site-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.ConfigAttributeError: Key 'required_seq_len_multiple' not in 'HubertConfig'
	full_key: required_seq_len_multiple
	reference_type=Optional[HubertConfig]
	object_type=HubertConfig
```

**Comment by wnhsu** [comment]
There are several bugs introduced by recent commits (miss config, etc.) The current branch with [this commit](https://github.com/pytorch/fairseq/commit/272c4c5197250997148fb12c0db6306035f166a4) should work fine

**Comment by shangeth** [comment]
How to change the config of a pretrained model? I want to change the **label_rate** of the pretrained Hubert Model from 50 to 100. 

Right now I am loading pretrained model(label_rate=50) and copying its weights to the model(label_rate=100). Is there any other easier method to change the config?
