### ISSUE TITLE
 generate.py RuntimeError: cublas runtime error : library not initialized at torch/lib/THC/THCGeneral.c

### ISSUE THREAD

**Issue by ShiraKadosh** [pytorch/fairseq#363]
Hi All,
Trying to run generate.py to test my new model I get the following error:

/mlconvgec2018/software/fairseq-py/pytorch/torch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [173,0,0], thread: [62,0,0] Assertion srcIndex < srcSelectDimSize failed.
/mlconvgec2018/software/fairseq-py/pytorch/torch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [173,0,0], thread: [63,0,0] Assertion srcIndex < srcSelectDimSize failed.
Traceback (most recent call last):
File "/mlconvgec2018/software/fairseq-py/generate.py", line 167, in 
main()
File "/mlconvgec2018/software/fairseq-py/generate.py", line 108, in main
translations = translator.generate(Variable(tokens.view(1, -1)), Variable(positions.view(1, -1)))
File "/mlconvgec2018/software/fairseq-py/fairseq/sequence_generator.py", line 86, in generate
return self._generate(src_tokens, src_positions, beam_size, maxlen)
File "/mlconvgec2018/software/fairseq-py/fairseq/sequence_generator.py", line 99, in _generate
encoder_out = model.encoder(src_tokens, src_positions)
File "/usr/local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 252, in call
result = self.forward(*input, **kwargs)
File "/mlconvgec2018/software/fairseq-py/fairseq/models/fconv.py", line 125, in forward
x = self.fc1(x)
File "/usr/local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 252, in call
result = self.forward(*input, **kwargs)
File "/usr/local/lib/python3.5/site-packages/torch/nn/modules/linear.py", line 55, in forward
return F.linear(input, self.weight, self.bias)
File "/usr/local/lib/python3.5/site-packages/torch/nn/functional.py", line 575, in linear
output = input.matmul(weight.t())
File "/usr/local/lib/python3.5/site-packages/torch/autograd/variable.py", line 561, in matmul
return torch.matmul(self, other)
File "/usr/local/lib/python3.5/site-packages/torch/functional.py", line 191, in matmul
output = torch.mm(tensor1, tensor2)
File "/usr/local/lib/python3.5/site-packages/torch/autograd/variable.py", line 580, in mm
return Addmm.apply(output, self, matrix, 0, 1, True)
File "/usr/local/lib/python3.5/site-packages/torch/autograd/_functions/blas.py", line 26, in forward
matrix1, matrix2, out=output)
RuntimeError: cublas runtime error : library not initialized at /mlconvgec2018/software/fairseq-py/pytorch/torch/lib/THC/THCGeneral.c:405

I run this script on the same model and test data on Linux (Ubuntu 16.04) docker container and it worked fine
Then I pulled the image (created from this container) to Centos 7 machine and tried to run generate.py to test the model and got this error.
Also I run train.py of fairseq to build the fconv model and it did worked fine on the Centos 7 machine.
Only the generate.py is not working...

Any ideas?
Thanks,
Shira

**Comment by myleott** [comment]
If the same model/code works on one machine but not another, then it seems like maybe it's some configuration issue with pytorch, or maybe there's a bug in the pytorch version installed on the Centos machine?

Can you share more details about pytorch version, model config, args you passed to generate.py, etc.?

**Comment by ShiraKadosh** [comment]
Sure @myleott :
pytorch version is 0.2.0
model config:
python3.5 /mlconvgec2018/software/fairseq-py/generate.py --no-progress-bar --path models/mlconv_embed/model_exp41000_old/checkpoint_best.pt --beam 12 --nbest 12 --interactive --workers 12 processed/bin

**Comment by myleott** [comment]
Oh, that's a really old version of pytorch. Presumably you're also using a very old version of fairseq (since the latest version doesn't work with pytorch 0.2)? Can you try updating to a newer pytorch + fairseq? Old model checkpoints should continue working with the latest fairseq.

**Comment by ShiraKadosh** [comment]
Yes, I'll do that, hope it will solve the problem, Thanks @myleott

**Comment by ShiraKadosh** [comment]
Problem solved! thanks @myleott

**Comment by genbei** [comment]
> 问题解决了！谢谢@myleott

How did you solve it in the end, I also encountered this problem
