### ISSUE TITLE
enum Choices can't be pickled in multi-GPU training

### ISSUE THREAD

**Issue by minghao-wu** [pytorch/fairseq#3634]
## 🐛 Bug

I am using fairseq for my new research project. I wrote my own task, dataset, criterion and related dataclasses.

 When running on single GPU, everything works very well. When running on multiple GPUs, an error is reported.
```

2021-06-21 19:20:06 | INFO | fairseq.trainer | begin training epoch 1
2021-06-21 19:20:06 | INFO | fairseq_cli.train | Start iterating over samples
Traceback (most recent call last):
  File "/home/hiai-wmh/discnmt-project/discnmt/fairseq/fairseq_cli/train.py", line 498, in <module>
    cli_main()
  File "/home/hiai-wmh/discnmt-project/discnmt/fairseq/fairseq_cli/train.py", line 491, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home/hiai-wmh/discnmt-project/discnmt/fairseq/fairseq/distributed/utils.py", line 351, in call_main
    join=True,
  File "/home/hiai-wmh/anaconda3/envs/discnmt/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/hiai-wmh/anaconda3/envs/discnmt/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/hiai-wmh/anaconda3/envs/discnmt/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/hiai-wmh/anaconda3/envs/discnmt/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/hiai-wmh/discnmt-project/discnmt/fairseq/fairseq/distributed/utils.py", line 328, in distributed_main
    main(cfg, **kwargs)
  File "/home/hiai-wmh/discnmt-project/discnmt/fairseq/fairseq_cli/train.py", line 169, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/home/hiai-wmh/anaconda3/envs/discnmt/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/hiai-wmh/discnmt-project/discnmt/fairseq/fairseq_cli/train.py", line 275, in train
    for i, samples in enumerate(progress):
  File "/home/hiai-wmh/discnmt-project/discnmt/fairseq/fairseq/logging/progress_bar.py", line 256, in __iter__
    for i, obj in enumerate(self.iterable, start=self.n):
  File "/home/hiai-wmh/discnmt-project/discnmt/fairseq/fairseq/data/iterators.py", line 59, in __iter__
    for x in self.iterable:
  File "/home/hiai-wmh/discnmt-project/discnmt/fairseq/fairseq/data/iterators.py", line 528, in _chunk_iterator
    for x in itr:
  File "/home/hiai-wmh/discnmt-project/discnmt/fairseq/fairseq/data/iterators.py", line 59, in __iter__
    for x in self.iterable:
  File "/home/hiai-wmh/discnmt-project/discnmt/fairseq/fairseq/data/iterators.py", line 650, in __next__
    raise item
  File "/home/hiai-wmh/discnmt-project/discnmt/fairseq/fairseq/data/iterators.py", line 581, in run
    for item in self._source:
  File "/home/hiai-wmh/anaconda3/envs/discnmt/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "/home/hiai-wmh/anaconda3/envs/discnmt/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/hiai-wmh/anaconda3/envs/discnmt/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 918, in __init__
    w.start()
  File "/home/hiai-wmh/anaconda3/envs/discnmt/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/hiai-wmh/anaconda3/envs/discnmt/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/hiai-wmh/anaconda3/envs/discnmt/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/hiai-wmh/anaconda3/envs/discnmt/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/hiai-wmh/anaconda3/envs/discnmt/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/hiai-wmh/anaconda3/envs/discnmt/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/hiai-wmh/anaconda3/envs/discnmt/lib/python3.7/multiprocessing/reduction.py", line 65, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <enum 'Choices'>: attribute lookup Choices on fairseq.dataclass.constants failed

```

### To Reproduce

I really have no clue on how to provide a code snippet to reproduce this error.

### Expected behavior

I am trying to train my custom task with multiple GPUs.

### Environment

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0): 1.9.0
 - OS (e.g., Linux): Linux (Ubuntu 16.04.7 LTS)
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source): pip install --editable ./
 - Python version: Python 3.7.10
 - CUDA/cuDNN version: 10.2/No idea...
 - GPU models and configuration: Tesla V100
 - Any other relevant information:

### Additional context

Something similar yet still different was reported at https://github.com/pytorch/fairseq/issues/3503 and https://github.com/pytorch/fairseq/issues/3482.
The solution given in https://github.com/pytorch/fairseq/issues/3503 and https://github.com/pytorch/fairseq/issues/3482 is to insert following snippt at line 460 in fairseq/fairseq/dataclass/utils.py and I replace `MyConfigClassWhichNeedsToBePickled` with my own dataclass. 
This solution does not work in my case.
```python3
cfg = OmegaConf.merge(
    OmegaConf.structured(
         MyConfigClassWhichNeedsToBePickled
    ),
    OmegaConf.create(
        OmegaConf.to_yaml(cfg, resolve=True)
    )
)
```

**Comment by minghao-wu** [comment]
Hi guys,

My problem is solved.

After setting `--num-workers 0`, my code runs smoothly on 8 V100 GPUs.

This is a long-standing bug in data.DataLoader. The PyTorch team is aware of it but fixing it requires a huge amount of workload.

**Comment by shen9712** [comment]
> Hi guys,
> 
> My problem is solved.
> 
> After setting `--num-workers 0`, my code runs smoothly on 8 V100 GPUs.
> 
> This is a long-standing bug in data.DataLoader. The PyTorch team is aware of it but fixing it requires a huge amount of workload.

I tried both inserting the snippt at line 460 in fairseq/fairseq/dataclass/utils.py and set dataset.num_workers=0 but still got the error. Any other solutions? \
