### ISSUE TITLE
Runtime Errors when begins to pre-train wav2vec2.0 in virtual machine environment with multi GPUs

### ISSUE THREAD

**Issue by Megumu2597** [pytorch/fairseq#3638]
## 🐛 Bug
How can I get pretraining WAV2VEC2.0 running with virtual machine instances with 8GPUs (made by gcloud compute instances create) ?

### To Reproduce
When I run the command below, with configure file for 8GPUs, Runtime error occurs saying that "please report this to the fairseq developers" between loading training data and training.

I have confirmed pretrining works well with 4 GPUs in my environments.
The only one different between 4GPU and 8GPU is "distributed_world_size" argument in config file. 

fairseq-hydra-train \
    task.data=/path/to/data \
    --config-dir /path/to/fairseq-py/examples/wav2vec/config/pretraining \
    --config-name wav2vec2_for_8gpu

in config file (wac2vec2_for_8gpu.yaml),
dataset:
  num_workers: 6
  max_tokens: 1200000
  skip_invalid_size_inputs_valid_test: true
  batch_size: 4

distributed_training:
  distributed_world_size: 8
  ddp_backend: no_c10d

other arguments follow the sample config. (config/wav2vec2_large_librivox.yaml)

###Error messge 

[2021-06-23 06:03:11,782][fairseq.trainer][INFO] - loading train data for epoch 19
[2021-06-23 06:03:11,983][fairseq.data.audio.raw_audio_dataset][INFO] - loaded 48745, skipped 13803 samples
Traceback (most recent call last):
  File "../fairseq/fairseq_cli/hydra_train.py", line 80, in <module>
    cli_main()
  File "../fairseq/fairseq_cli/hydra_train.py", line 76, in cli_main
    hydra_main()
  File "/usr/local/lib/python3.6/dist-packages/hydra/main.py", line 37, in decorated_main
    strict=strict,
  File "/usr/local/lib/python3.6/dist-packages/hydra/_internal/utils.py", line 347, in _run_hydra
    lambda: hydra.run(
  File "/usr/local/lib/python3.6/dist-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/usr/local/lib/python3.6/dist-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/usr/local/lib/python3.6/dist-packages/hydra/_internal/utils.py", line 350, in <lambda>
    overrides=args.overrides,
  File "/usr/local/lib/python3.6/dist-packages/hydra/_internal/hydra.py", line 112, in run
    configure_logging=with_log_configuration,
  File "/usr/local/lib/python3.6/dist-packages/hydra/core/utils.py", line 127, in run_job
    ret.return_value = task_function(task_cfg)
  File "../fairseq/fairseq_cli/hydra_train.py", line 45, in hydra_main
    distributed_utils.call_main(cfg, pre_main)
  File "/app/fairseq/fairseq/distributed/utils.py", line 351, in call_main
    join=True,
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/app/fairseq/fairseq/distributed/utils.py", line 328, in distributed_main
    main(cfg, **kwargs)
  File "/app/fairseq/fairseq_cli/train.py", line 157, in main
    disable_iterator_cache=task.has_sharded_data("train"),
  File "/app/fairseq/fairseq/checkpoint_utils.py", line 259, in load_checkpoint
    epoch_itr.load_state_dict(itr_state)
  File "/app/fairseq/fairseq/data/iterators.py", line 423, in load_state_dict
    "Cannot resume training due to dataloader mismatch, please "
RuntimeError: Cannot resume training due to dataloader mismatch, please report this to the fairseq developers. You can relaunch training with `--reset-dataloader` and it should work.

### Expected behavior
 I have confirmed that it works with 4GPU environments, and will move on to begin learning like this.

[2021-06-23 06:36:38,954][fairseq.data.audio.raw_audio_dataset][INFO] - loaded 48745, skipped 13803 samples
[2021-06-23 06:36:40,121][fairseq.trainer][INFO] - begin training epoch 19

### Environment
 - fairseq Version  master:
 - torch==1.6.0+cu101 
 - torchvision==0.7.0+cu101
 - OS Linux:
 - CPU&GPU are made by Compute Engine virtual machine instances(gcloud compute instances create)
 ・n1-standard-32（vCPU x 32、memory 120 GB）
 ・8 x NVIDIA Tesla V100(8GPU)

### Additional context
##Fixed problem
Before stacking on this error I faced another error (https://github.com/huggingface/transformers/issues/3660)
I solve the problem by enhancing CPU from n1-standard-4(vCPU x 4、memory 15 GB） to n1-standard-32（vCPU x 32、memory 120 GB）.

**Comment by Megumu2597** [comment]
Adding --reset-dataloader  works well. 
So I close this issue.
