### ISSUE TITLE
What is the best practice to use streaming-based dataset on multi-GPUs?

### ISSUE THREAD

**Issue by ryonakamura** [pytorch/fairseq#3652]
Since our data is very large, we are creating a dataset by getting 10M samples from Elasticsearch every epoch.
This works well on a single GPU, but we do not know the proper way to make it work on multi-GPUs.
Our understanding is that Fairseq loads a fixed dataset in multiple processes and iterates over different batches of the dataset with `ShardedIterator` to achieve data parallelism.
In our approach, each process loads a different dataset, so we cannot use `ShardedIterator`.
We tried to do `num_shards=1` and `shard_id=0` on multi-GPUs, but got an error.

```python
    distributed_utils.call_main(cfg, main)
  File "/home/ubuntu/fairseq/fairseq/distributed/utils.py", line 344, in call_main
    torch.multiprocessing.spawn(
  File "/home/ubuntu/.pyenv/versions/3.8.6/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/ubuntu/.pyenv/versions/3.8.6/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/ubuntu/.pyenv/versions/3.8.6/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.8.6/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
  File "/home/ubuntu/fairseq/fairseq/distributed/utils.py", line 328, in distributed_main
  File "/home/ubuntu/fairseq/fairseq_cli/train.py", line 180, in main
  File "/home/ubuntu/.pyenv/versions/3.8.6/lib/python3.8/contextlib.py", line 75, in inner
  File "/home/ubuntu/fairseq/fairseq_cli/train.py", line 287, in train
  File "/home/ubuntu/fairseq/fairseq/logging/progress_bar.py", line 261, in __iter__
  File "/home/ubuntu/fairseq/fairseq/data/iterators.py", line 56, in __next__
  File "/home/ubuntu/fairseq/fairseq/data/iterators.py", line 508, in _chunk_iterator
  File "/home/ubuntu/fairseq/fairseq/data/iterators.py", line 56, in __next__
  File "/home/ubuntu/fairseq/fairseq/data/iterators.py", line 636, in __next__
  File "/home/ubuntu/fairseq/fairseq/data/iterators.py", line 566, in run
  File "/home/ubuntu/.pyenv/versions/3.8.6/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 355, in __iter__
  File "/home/ubuntu/.pyenv/versions/3.8.6/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 301, in _get_iterator
  File "/home/ubuntu/.pyenv/versions/3.8.6/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 914, in __init__
  File "/home/ubuntu/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/process.py", line 121, in start
  File "/home/ubuntu/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
  File "/home/ubuntu/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
  File "/home/ubuntu/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
  File "/home/ubuntu/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
  File "/home/ubuntu/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
  File "/home/ubuntu/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
  File "/home/ubuntu/.pyenv/versions/3.8.6/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 321, in reduce_storage
RuntimeError: unable to open shared memory object </torch_14262_621126431> in read-write mode

/home/ubuntu/.pyenv/versions/3.8.6/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 12 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

__What is the best practice for this situation?__

The practice we have already done is:

- Create the dataset only in the `data_parallel_rank=0` process, serialize/unserialize it using the pickle module, and share the same dataset to other processes. This way, serialize/unserialize became a big overhead (tens of minutes).

**Comment by ryonakamura** [comment]
`RuntimeError: unable to open shared memory object in read-write mode` was caused by pickle.
In `num_workers` >= 1 and Multi-GPU, holding LongTensor in dataset causes this error in the `torch.utils.data.DataLoader` because the dataloader uses pickle internally when copying datasets from caller to worker, but it cannot serialize LongTensor, so we should convert the list of integers  to LongTensor in `__next__` or `collate_fn`, not `__init__`.
