### ISSUE TITLE
Failed  extracting features for HUBERT ? 

### ISSUE THREAD

**Issue by Enescigdem** [pytorch/fairseq#3663]
Hello, I tried to extract features for HUBERT then this gives an error about the absence of the file /checkpoint/wnhsu/data/librispeech/960h/iter/250K_50hz_km100_mp0_65_v2/dict.layer6.km500.txt.
What should I do about this?
The line I ran ==>
python dump_hubert_feature.py data train  pretrained/hubert_base_ls960.pt 0 36 0  data/feats_hubert

**Comment by EmreOzkose** [comment]
I think that the actual problem is loading model. 

```
Python 3.8.10 (default, May 19 2021, 18:05:58) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fairseq
>>> ckpt_path = "../pretrained/hubert_large_ll60k.pt"
>>> models, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([ckpt_path])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "path/to/fairseq/fairseq/fairseq/checkpoint_utils.py", line 446, in load_model_ensemble_and_task
    model = task.build_model(cfg.model)
  File "path/to/fairseq/fairseq/fairseq/tasks/fairseq_task.py", line 324, in build_model
    model = models.build_model(cfg, self)
  File "path/to/fairseq/fairseq/fairseq/models/__init__.py", line 96, in build_model
    return model.build_model(cfg, task)
  File "path/to/fairseq/fairseq/fairseq/models/hubert/hubert.py", line 320, in build_model
    model = HubertModel(cfg, task.cfg, task.dictionaries)
  File "path/to/fairseq/fairseq/fairseq/tasks/hubert_pretraining.py", line 140, in dictionaries
    return self.state.dictionaries
  File "path/tofairseq/fairseq/fairseq/tasks/fairseq_task.py", line 41, in __getattr__
    self._state[name] = self._factories[name]()
  File "path/to/fairseq/fairseq/fairseq/tasks/hubert_pretraining.py", line 150, in load_dictionaries
    dictionaries = [Dictionary.load(f"{label_dir}/dict.{label}.txt") for label in self.cfg.labels]
  File "path/to/fairseq/fairseq/tasks/hubert_pretraining.py", line 150, in <listcomp>
    dictionaries = [Dictionary.load(f"{label_dir}/dict.{label}.txt") for label in self.cfg.labels]
  File "path/to/fairseq/fairseq/fairseq/data/dictionary.py", line 225, in load
    d.add_from_file(f)
  File "path/tofairseq/fairseq/fairseq/data/dictionary.py", line 238, in add_from_file
    raise fnfe
  File "path/to/fairseq/fairseq/fairseq/data/dictionary.py", line 235, in add_from_file
    with open(PathManager.get_local_path(f), "r", encoding="utf-8") as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/checkpoint/wnhsu/experiments/hubert/kmeans_20210121/km_dataset_librivox.model_iter_2.all/dict.lyr9.km500.txt'
```

I don't know what is that path `'/checkpoint/wnhsu/experiments/hubert/kmeans_20210121/km_dataset_librivox.model_iter_2.all/dict.lyr9.km500.txt'`

**Comment by deepspike** [comment]
Do you guys have any workaround for this issue?

**Comment by Enescigdem** [comment]
> Do you guys have any workaround for this issue?

Unfortunately Not

**Comment by richwhitjr** [comment]
I was able to work around this issue by checking out commit `e47a4c84da877382c4d37941be4e84449f99d186` then building according to the readme `pip install --editable ./`

**Comment by wnhsu** [comment]
Hi, we have updated the pre-trained checkpoints to include the dictionary in `task_state`. This should prevent the model from loading the dictionary from the disk. 

https://github.com/pytorch/fairseq/blob/main/fairseq/checkpoint_utils.py#L434-L435
https://github.com/pytorch/fairseq/blob/main/fairseq/tasks/fairseq_task.py#L44-L45

Please make sure you use the latest commit and re-download the pre-trained models. Thanks.
