### ISSUE TITLE
wav2vec-u, prepare_audio.sh, wav2vec_extract_features.py, crash when using wav2vec_big_960h.pt

### ISSUE THREAD

**Issue by cdleong** [pytorch/fairseq#3678]
## 🐛 Bug

When ordered to load https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_big_960h.pt, https://github.com/pytorch/fairseq/blob/master/examples/wav2vec/unsupervised/scripts/wav2vec_extract_features.py attempts to load a specific file, and crashes: `/checkpoint/abaevski/data/speech/libri/960h/wav2vec/raw/dict.ltr.txt`

However, when given https://dl.fbaipublicfiles.com/fairseq/wav2vec/xlsr_53_56k.pt, the program does not crash. 

Testing indicates that the configuration dictionary in wav2vec_big_960h.pt contains a "labels: 'ltr'" field which, when it gets to checkpoint_utils.load_model_ensemble_and_task() and later audio_pretraining.load_target_dictionary(), may be the cause. 

### To Reproduce

Given that the steps for setting up the environment for wav2vec-u is its own complicated separate issue (see https://github.com/pytorch/fairseq/issues/3591#), I will simply say that if you have gotten to the point where you can run prepare_audio.sh, you can reproduce this. You can either use the command I did, or run wav2vec_extract_features.py alone (see below)

Command I used: `zsh $FAIRSEQ_ROOT/examples/wav2vec/unsupervised/scripts/prepare_audio.sh "$WITHOUT_SILENCES/updated_tsv_for_silences/" $PREPARED_AUDIO_OUT $PRETRAINED_MODEL 512 14`

where 
* FAIRSEQ_ROOT points to a cloned copy of fairseq, commit cdc1a553eb2af4fac720880aff4ee2566a28ad21
* WITHOUT_SILENCES is the folder with .tsv and "clips" subfolder containing .wav files. 
* PREPARED_AUDIO_OUT is the folder I'm outputting to, 
* PRETRAINED_MODEL points to wav2vec_big_960h.pt

I did manage to get the same error by running wav2vec_extract_features.py directly thus: 
```
python $FAIRSEQ_ROOT/examples/wav2vec/unsupervised/scripts/wav2vec_extract_features.py $WITHOUT_SILENCES --split train --save-dir $PREPARED_AUDIO_OUT --checkpoint $PRETRAINED_MODEL --layer 14
```

Result in either case:
```
Traceback (most recent call last):
  File "/home/jovyan/fairseq/examples/wav2vec/unsupervised/scripts/wav2vec_extract_features.py", line 121, in <module>
    main()
  File "/home/jovyan/fairseq/examples/wav2vec/unsupervised/scripts/wav2vec_extract_features.py", line 109, in main
    generator, num = get_iterator(args)
  File "/home/jovyan/fairseq/examples/wav2vec/unsupervised/scripts/wav2vec_extract_features.py", line 78, in get_iterator
    reader = Wav2VecFeatureReader(args.checkpoint, args.layer)
  File "/home/jovyan/fairseq/examples/wav2vec/unsupervised/scripts/wav2vec_extract_features.py", line 40, in __init__
    [cp_file]
  File "/home/jovyan/fairseq/fairseq/checkpoint_utils.py", line 486, in load_model_ensemble_and_task
    model = task.build_model(cfg.model)
  File "/home/jovyan/fairseq/fairseq/tasks/audio_pretraining.py", line 297, in build_model
    model = super().build_model(model_cfg)
  File "/home/jovyan/fairseq/fairseq/tasks/fairseq_task.py", line 324, in build_model
    model = models.build_model(cfg, self)
  File "/home/jovyan/fairseq/fairseq/models/__init__.py", line 96, in build_model
    return model.build_model(cfg, task)
  File "/home/jovyan/fairseq/fairseq/models/wav2vec/wav2vec2_asr.py", line 178, in build_model
    w2v_encoder = Wav2VecEncoder(cfg, len(task.target_dictionary))
  File "/home/jovyan/fairseq/fairseq/tasks/audio_pretraining.py", line 270, in target_dictionary
    return self.state.target_dictionary
  File "/home/jovyan/fairseq/fairseq/tasks/fairseq_task.py", line 41, in __getattr__
    self._state[name] = self._factories[name]()
  File "/home/jovyan/fairseq/fairseq/tasks/audio_pretraining.py", line 181, in load_target_dictionary
    return Dictionary.load(dict_path)
  File "/home/jovyan/fairseq/fairseq/data/dictionary.py", line 225, in load
    d.add_from_file(f)
  File "/home/jovyan/fairseq/fairseq/data/dictionary.py", line 239, in add_from_file
    raise fnfe
  File "/home/jovyan/fairseq/fairseq/data/dictionary.py", line 236, in add_from_file
    with open(PathManager.get_local_path(f), "r", encoding="utf-8") as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/checkpoint/abaevski/data/speech/libri/960h/wav2vec/raw/dict.ltr.txt'
```

### Environment
* fairseq, installed with pip install editable from commit cdc1a553eb2af4fac720880aff4ee2566a28ad21
* Ubuntu 20.04.2 LTS

conda list output: 
```
# packages in environment at /opt/conda/envs/wav2vecu:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
antlr4-python3-runtime    4.8                      pypi_0    pypi
ca-certificates           2021.5.30            ha878542_0    conda-forge
certifi                   2021.5.30        py37h89c1867_0    conda-forge
cffi                      1.14.5                   pypi_0    pypi
cudatoolkit               11.2.2               he111cf0_8    conda-forge
cython                    0.29.23                  pypi_0    pypi
fairseq                   1.0.0a0+cdc1a55           dev_0    <develop>
faiss                     1.7.0           py37cuda112h7ce9dcd_8_cuda    conda-forge
faiss-gpu                 1.7.0                h788eb59_8    conda-forge
hydra-core                1.0.6                    pypi_0    pypi
importlib-resources       5.2.0                    pypi_0    pypi
ld_impl_linux-64          2.36.1               hea4e1c9_0    conda-forge
libblas                   3.9.0                9_openblas    conda-forge
libcblas                  3.9.0                9_openblas    conda-forge
libfaiss                  1.7.0           cuda112h5bea7ad_8_cuda    conda-forge
libfaiss-avx2             1.7.0           cuda112h1234567_8_cuda    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
libgfortran-ng            9.3.0               hff62375_19    conda-forge
libgfortran5              9.3.0               hff62375_19    conda-forge
libgomp                   9.3.0               h2828fa1_19    conda-forge
liblapack                 3.9.0                9_openblas    conda-forge
libopenblas               0.3.15          pthreads_h8fe5266_1    conda-forge
libstdcxx-ng              9.3.0               h6de172a_19    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
npy-append-array          0.9.6                    pypi_0    pypi
numpy                     1.21.0           py37h038b26d_0    conda-forge
omegaconf                 2.0.6                    pypi_0    pypi
openblas                  0.3.15          pthreads_h4748800_1    conda-forge
openssl                   1.1.1k               h7f98852_0    conda-forge
pip                       21.1.3             pyhd8ed1ab_0    conda-forge
portalocker               2.0.0                    pypi_0    pypi
pycparser                 2.20                     pypi_0    pypi
pykaldi                   0.1.3            py37h14c3975_1    pykaldi
python                    3.7.10          hffdb5ce_100_cpython    conda-forge
python_abi                3.7                     2_cp37m    conda-forge
pyyaml                    5.4.1                    pypi_0    pypi
readline                  8.1                  h46c0cb4_0    conda-forge
regex                     2021.4.4                 pypi_0    pypi
sacrebleu                 1.5.1                    pypi_0    pypi
scipy                     1.7.0                    pypi_0    pypi
setuptools                49.6.0           py37h89c1867_3    conda-forge
soundfile                 0.10.3.post1             pypi_0    pypi
sqlite                    3.36.0               h9cd32fc_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
torch                     1.9.0                    pypi_0    pypi
torchaudio                0.9.0                    pypi_0    pypi
tqdm                      4.61.1                   pypi_0    pypi
typing-extensions         3.10.0.0                 pypi_0    pypi
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zipp                      3.4.1                    pypi_0    pypi
zlib                      1.2.11            h516909a_1010    conda-forge
```

#### 960h .pt file has `labels: 'ltr'` 
After a while of going back and forth between the two .pt files, I went to https://github.com/pytorch/fairseq/blob/master/fairseq/checkpoint_utils.py#L270, and added some print statements to see what's in there, right before the return statement. 
* When I load the XLSR 53 pretrained model and look at `state["cfg"]["task"]` I see that the XLSR one has `'data': '/private/home/aconneau/projects/XLSR/MLS/53bis/', 'labels': None` in it. 
* When I look at the 960h one, I see that it has `'data': '/checkpoint/abaevski/data/speech/libri/960h/wav2vec/raw/', 'labels': 'ltr'` in it. 

#### audio_pretraining.py line 176 is where the nonexistent filepath is built
I also note that https://github.com/pytorch/fairseq/blob/cdc1a553eb2af4fac720880aff4ee2566a28ad21/fairseq/tasks/audio_pretraining.py#L176 checks whether labels are None

Also, this is where the actual filepath from the FileNotFoundError originates. 

#### in checkpoint_utils, cfg is set in different ways: state["args"] for the 960h one
Via print debugging, I determined that the 960h one triggers this: https://github.com/pytorch/fairseq/blob/cdc1a553eb2af4fac720880aff4ee2566a28ad21/fairseq/checkpoint_utils.py#L412

whereas the xlsr one triggers this one using state["cfg"] https://github.com/pytorch/fairseq/blob/cdc1a553eb2af4fac720880aff4ee2566a28ad21/fairseq/checkpoint_utils.py#L414

**Comment by SanzharMrz** [comment]
Hello, thanks for sharing, I hava a problem partially linked with yours, its about loading
pretrained russian wav2vec2.0 pt file, from huggingface https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-russian
My crash log looks like this:

**LOG:**
```bash
File "/home/s.murzakhmetov/bee/fair/fairseq/examples/wav2vec/unsupervised/scripts/wav2vec_extract_features.py", line 119, in <module>
    main()
  File "/home/s.murzakhmetov/bee/fair/fairseq/examples/wav2vec/unsupervised/scripts/wav2vec_extract_features.py", line 107, in main
    generator, num = get_iterator(args)
  File "/home/s.murzakhmetov/bee/fair/fairseq/examples/wav2vec/unsupervised/scripts/wav2vec_extract_features.py", line 76, in get_iterator
    reader = Wav2VecFeatureReader(args.checkpoint, args.layer)
  File "/home/s.murzakhmetov/bee/fair/fairseq/examples/wav2vec/unsupervised/scripts/wav2vec_extract_features.py", line 39, in __init__
    [cp_file]
  File "/home/s.murzakhmetov/bee/fair/fairseq/fairseq/checkpoint_utils.py", line 410, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/home/s.murzakhmetov/bee/fair/fairseq/fairseq/checkpoint_utils.py", line 328, in load_checkpoint_to_cpu
    state = _upgrade_state_dict(state)
  File "/home/s.murzakhmetov/bee/fair/fairseq/fairseq/checkpoint_utils.py", line 519, in _upgrade_state_dict
    {"criterion_name": "CrossEntropyCriterion", "best_loss": state["best_loss"]}
KeyError: 'best_loss'
```

I found (from this  [link](https://ask.csdn.net/questions/3649421) ) that it happens because of upgrading state dict in `fairseq/fairseq/checkpoint_utils.py`,  and in my state_dict there are no any meta information about training process, but their advices didnt help me. Should i skip this process?
