### ISSUE TITLE
fairseq_cli/preprocess.py do not generate phones/dict.txt and phones/dict.phn.txt as it used to be(Using wav2vec unsupervised)

### ISSUE THREAD

**Issue by ZurabDz** [pytorch/fairseq#3682]
#### What is your question?
First of alll, I am sorry if my question is not fully "baked", it's actually my first time creating an issue on github.

The issue I have problem is with preprocess.py in fairseq_cli. On server and on personal laptop it gives me two different resuls.
To be specific phones/dict.txt and phones/dict.phn.txt on laptop is almost empty only 3 lines and with the same argument on server it gives me "normal"(much more 34 lines)  results. Fairseq, wav2vec u and all of  it's dependencies are installed by me on both machines.
#### Code

`python $FAIRSEQ_ROOT/fairseq_cli/preprocess.py --dataset-impl mmap --trainpref $target_dir/phones.txt --only-source --destdir $target_dir/phones --thresholdsrc $min_phones --padding-factor 1 --dict-only`

in given file `from fairseq.file_chunker_utils import find_offsets` is used instead of `from fairseq.binarizer import Binarizer`. The reason I am saying that is cause on server fairseq was install a month or 2 month ago and on my laptop 2 days ago.

from my limited knowledge this file does not generates those results for some reason. Again all the parameters and text input are the same on both machine.

#### What have you tried?
I have tried searching any possible issue related to this problem but not luck so far.

##### On Server:
 - OS: CentOS7 
 - fairseq version: pip install --upgrade git+https://github.com/pytorch/fairseq.git (1.0.0a0+cd5775f)

##### On Laptop:
 - OS: Debian 10
 - fairseq version: pip install --upgrade git+https://github.com/pytorch/fairseq.git (1.0.0a0+cdc1a55)

Again I am honestly desperate and sorry at the same time. I think more information is needed to solve it but not sure what should I provide. Maybe I am doing something wrong not sure but obvious things such as passing same arguments and text data are not the one 

#### ERROR:
```
Traceback (most recent call last):
  File "/home/penguin/Documents/wav2vec_u/fairseq/fairseq_cli/preprocess.py", line 407, in <module>
    cli_main()
  File "/home/penguin/Documents/wav2vec_u/fairseq/fairseq_cli/preprocess.py", line 403, in cli_main
    main(args)
  File "/home/penguin/Documents/wav2vec_u/fairseq/fairseq_cli/preprocess.py", line 297, in main
    make_all(args.source_lang, src_dict)
  File "/home/penguin/Documents/wav2vec_u/fairseq/fairseq_cli/preprocess.py", line 265, in make_all
    make_dataset(vocab, args.trainpref, "train", lang, num_workers=args.workers)
  File "/home/penguin/Documents/wav2vec_u/fairseq/fairseq_cli/preprocess.py", line 261, in make_dataset
    make_binary_dataset(vocab, input_prefix, output_prefix, lang, num_workers)
  File "/home/penguin/Documents/wav2vec_u/fairseq/fairseq_cli/preprocess.py", line 191, in make_binary_dataset
    100 * sum(replaced.values()) / n_seq_tok[1],
ZeroDivisionError: division by zero
```

**Comment by ZurabDz** [comment]
I found a problem it seems like versioning of fairseq really doesn't matter but versioning of espeak does. Not sure exactly why, I just downgraded it and works like a charm
