### ISSUE TITLE
omegaconf.errors.ConfigKeyError while trying to run hydra_train.py

### ISSUE THREAD

**Issue by harunuz** [pytorch/fairseq#3689]
## 🐛 Bug

When I run hydra-train.py it raises omegaconf.errors.ConfigKeyError. I think it does not see the common config. This happened after I pulled the most recent changes in the main branch.

### To Reproduce

Normally with the arguments below I was able to run hydra_train.py (or fairseq-hydra-train command):
```
task.data=/home/olympos/Projects/fairseq/finetuning_manifests-v2 distributed_training.distributed_world_size=1 model.w2v_path=/home/olympos/Projects/fairseq/fairseq_cli/outputs/2021-06-05/01-11-34/checkpoints/checkpoint_best.pt --config-dir /home/olympos/Projects/fairseq/examples/wav2vec/config/finetuning --config-name base_100h
```

But now it raises 

`omegaconf.errors.ConfigKeyError: str interpolation key 'common.tpu' not found`

And the full stack trace is below.
```
home/olympos/Projects/fairseq/venv/bin/python /home/olympos/Projects/fairseq/fairseq_cli/hydra_train.py task.data=/home/olympos/Projects/fairseq/finetuning_manifests-v2 distributed_training.distributed_world_size=1 model.w2v_path=/home/olympos/Projects/fairseq/fairseq_cli/outputs/2021-06-05/01-11-34/checkpoints/checkpoint_best.pt --config-dir /home/olympos/Projects/fairseq/examples/wav2vec/config/finetuning --config-name base_100h
Traceback (most recent call last):
  File "/home/olympos/Projects/fairseq/fairseq_cli/hydra_train.py", line 80, in <module>
    cli_main()
  File "/home/olympos/Projects/fairseq/fairseq_cli/hydra_train.py", line 76, in cli_main
    hydra_main()
  File "/home/olympos/Projects/fairseq/venv/lib/python3.8/site-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/home/olympos/Projects/fairseq/venv/lib/python3.8/site-packages/hydra/_internal/utils.py", line 346, in _run_hydra
    run_and_report(
  File "/home/olympos/Projects/fairseq/venv/lib/python3.8/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/home/olympos/Projects/fairseq/venv/lib/python3.8/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/home/olympos/Projects/fairseq/venv/lib/python3.8/site-packages/hydra/_internal/utils.py", line 347, in <lambda>
    lambda: hydra.run(
  File "/home/olympos/Projects/fairseq/venv/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 107, in run
    return run_job(
  File "/home/olympos/Projects/fairseq/venv/lib/python3.8/site-packages/hydra/core/utils.py", line 127, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/olympos/Projects/fairseq/fairseq_cli/hydra_train.py", line 36, in hydra_main
    cfg = OmegaConf.create(OmegaConf.to_container(cfg, resolve=True, enum_to_str=True))
  File "/home/olympos/Projects/fairseq/venv/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 442, in to_container
    return BaseContainer._to_content(cfg, resolve=resolve, enum_to_str=enum_to_str)
  File "/home/olympos/Projects/fairseq/venv/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 194, in _to_content
    retdict[key] = BaseContainer._to_content(
  File "/home/olympos/Projects/fairseq/venv/lib/python3.8/site-packages/omegaconf/basecontainer.py", line 188, in _to_content
    node = node._dereference_node(
  File "/home/olympos/Projects/fairseq/venv/lib/python3.8/site-packages/omegaconf/base.py", line 123, in _dereference_node
    v = parent._resolve_simple_interpolation(
  File "/home/olympos/Projects/fairseq/venv/lib/python3.8/site-packages/omegaconf/base.py", line 327, in _resolve_simple_interpolation
    raise ConfigKeyError(
omegaconf.errors.ConfigKeyError: str interpolation key 'common.tpu' not found

Process finished with exit code 1
```
### Expected behavior
Training should have been started successfully with the given arguments.

### Environment

 - fairseq Version: master
 - PyTorch Version: 1.7.1
 - OS: Ubuntu 18.04
 - How you installed fairseq: `git pull and pip install --editable ./`
 - Python version: 3.8.9
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: 1 Titan RTX
 - hydra-core version: 1.0.6
 - omegaconf version: 2.0.6

### Additional context
The config.yaml in the output folder seems to be missing most of the common parameters. You can see the [config.yaml](https://github.com/pytorch/fairseq/files/6773098/config.txt)

**Comment by soroushhashemifar** [comment]
I faced the same issue. No solution yet!

**Comment by jubick1337** [comment]
I faced the same issue. Temporally switched to 0794f9a

**Comment by freewym** [comment]
I found that reverting the change at this line from a recent PR can solve the problem.

**Comment by harun-loodos** [comment]
This issue has been resolved with the recent changes. We can close it.
