### ISSUE TITLE
Error when using Wav2vec-u to launch GAN training

### ISSUE THREAD

**Issue by Ning107** [pytorch/fairseq#3693]
## ❓ Questions and Help

Hi, everyone. I am using the wav2vec Unsupervised by following indicates on [README](https://github.com/pytorch/fairseq/tree/01576be513488601e936df67e65e2817d18f576e/examples/wav2vec/unsupervised). However, when I executed the below command, it raised the error `AttributeError: 'NoneType' object has no attribute 'transpose'`. 
Commands :
```bash
PREFIX=w2v_unsup_gan_xp
TASK_DATA=/workspace/wav2vec_u/fairseq/examples/wav2vec/dataset/prepare_audio/precompute_pca512_cls128_mean_pooled
TEXT_DATA=/workspace/wav2vec_u/fairseq/examples/wav2vec/dataset/data/phones
KENLM_PATH=/workspace/wav2vec_u/fairseq/examples/wav2vec/dataset/data/phones/lm.phones.filtered.04.bin
fairseq-hydra-train \
    -m --config-dir unsupervised/config/gan \
    --config-name w2vu \
    task.data=${TASK_DATA} \
    task.text_data=${TEXT_DATA} \
    task.kenlm_path=${KENLM_PATH} \
    common.user_dir=examples/wav2vec/unsupervised \
    model.code_penalty=2,4 model.gradient_penalty=1.5,2.0 \
    model.smoothness_weight=0.5,0.75,1.0 'common.seed=range(0,5)'
```
Here is all the log and error information.
```bash
[2021-07-08 13:50:57,269][fairseq_cli.train][INFO] - task: UnpairedAudioText
[2021-07-08 13:50:57,269][fairseq_cli.train][INFO] - model: Wav2vec_U
[2021-07-08 13:50:57,269][fairseq_cli.train][INFO] - criterion: ModelCriterion
[2021-07-08 13:50:57,269][fairseq_cli.train][INFO] - num. shared model params: 1,166,337 (num. trained: 1,166,337)
[2021-07-08 13:50:57,269][fairseq_cli.train][INFO] - num. expert model params: 0 (num. trained: 0)
[2021-07-08 13:50:57,276][unsupervised.data.extracted_features_dataset][INFO] - loaded 1680, skipped 0 samples
[2021-07-08 13:50:57,276][unsupervised.tasks.unpaired_audio_text][INFO] - split valid has unpaired text? False
[2021-07-08 13:50:58,923][fairseq.utils][INFO] - ***********************CUDA enviroments for all 1 workers***********************
[2021-07-08 13:50:58,924][fairseq.utils][INFO] - rank   0: capabilities =  6.1  ; total memory = 10.917 GB ; name = GeForce GTX 1080 Ti                     
[2021-07-08 13:50:58,924][fairseq.utils][INFO] - ***********************CUDA enviroments for all 1 workers***********************
[2021-07-08 13:50:58,924][fairseq_cli.train][INFO] - training on 1 devices (GPUs/TPUs)
[2021-07-08 13:50:58,924][fairseq_cli.train][INFO] - max tokens per device = 200000 and max sentences per device = 16
[2021-07-08 13:50:58,925][fairseq.trainer][INFO] - Preparing to load checkpoint ./checkpoint_last.pt
[2021-07-08 13:50:58,926][fairseq.trainer][INFO] - No existing checkpoint found ./checkpoint_last.pt
[2021-07-08 13:50:58,926][fairseq.trainer][INFO] - loading train data for epoch 1
[2021-07-08 13:50:58,942][unsupervised.data.extracted_features_dataset][INFO] - loaded 4620, skipped 0 samples
[2021-07-08 13:50:58,942][unsupervised.tasks.unpaired_audio_text][INFO] - split train has unpaired text? False
[2021-07-08 13:50:59,080][fairseq.optim.adam][INFO] - using FusedAdam
[2021-07-08 13:50:59,146][fairseq.optim.adam][INFO] - using FusedAdam
[2021-07-08 13:50:59,154][fairseq.logging.progress_bar][WARNING] - tensorboard not found, please install with: pip install tensorboard
[2021-07-08 13:50:59,157][fairseq.trainer][INFO] - begin training epoch 1
[2021-07-08 13:50:59,157][fairseq_cli.train][INFO] - Start iterating over samples
Traceback (most recent call last):
  File "/tmp/fairseq/fairseq_cli/hydra_train.py", line 45, in hydra_main
    distributed_utils.call_main(cfg, pre_main)
  File "/tmp/fairseq/fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "/tmp/fairseq/fairseq_cli/train.py", line 180, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/tmp/fairseq/fairseq_cli/train.py", line 291, in train
    log_output = trainer.train_step(samples)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/tmp/fairseq/fairseq/trainer.py", line 710, in train_step
    ignore_grad=is_dummy_batch,
  File "/tmp/fairseq/fairseq/tasks/fairseq_task.py", line 502, in train_step
    loss, sample_size, logging_output = criterion(model, sample)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/tmp/fairseq/fairseq/criterions/model_criterion.py", line 50, in forward
    net_output = model(**sample["net_input"])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/tmp/fairseq/fairseq/../examples/wav2vec/unsupervised/models/wav2vec_u.py", line 567, in forward
    token_y = self.discriminator(token_x, token_padding_mask)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/tmp/fairseq/fairseq/../examples/wav2vec/unsupervised/models/wav2vec_u.py", line 266, in forward
    x = x.transpose(1, 2)  # BTC -> BCT
AttributeError: 'NoneType' object has no attribute 'transpose'
```
Can someone help on this ? Thanks a lot in advance.

**Comment by innarid** [comment]
Same issue. random_label is None for some reason

**Comment by xiabingquan** [comment]
The argument `random_label` is None. Carefully check your dataset.

**Comment by EomSooHwan** [comment]
@xiabingquan If you don't mind me asking, could you elaborate more on your explanation? I have the same issue, and I am not clear about what exactly I have to do. Should I change the argument `random_label` or prepare audio features again?
