### ISSUE TITLE
Errors when trying to execute infer.py file for wav2vec

### ISSUE THREAD

**Issue by HippolyteKarakostas** [pytorch/fairseq#3712]
## ❓ Questions and Help

Hello everyone,

I am trying to test some pre-trained models of wav2vec on LibriSpeech dataset. I saw that there were multiple subfolders in fairseq repository in order to do that, but I focused on the subfolder `fairseq/examples/speech_recognition`.

In that section, you have first to execute 

`./examples/speech_recognition/datasets/prepare-librispeech.sh $DIR_TO_SAVE_RAW_DATA $DIR_FOR_PREPROCESSED_DATA`

command line in order to download, unzip and prepare LibriSpeech dataset.
That command worked fine for me, and it created two folders `rawlibri` and `preproclibri` in my `/home`, just next to the `fairseq` repository.

Then, I have to execute the code for inference. In my case, it is

`python examples/speech_recognition/infer.py $DIR_FOR_PREPROCESSED_DATA --task speech_recognition --max-tokens 25000 --nbest 1 --path $MODEL_PATH/wav2vec_small_960h.pt --beam 20 --results-path $RES_DIR --batch-size 40 --gen-subset $SET --user-dir examples/speech_recognition`

where I am inside fairseq repository and I have downloaded the pre-trained model called wav2vec_small_960h.pt 

But this time, I get some errors, that I cannot understand:

`Traceback (most recent call last):
  File "examples/speech_recognition/infer.py", line 427, in <module>
    cli_main()
  File "examples/speech_recognition/infer.py", line 421, in cli_main
    parser = make_parser()
  File "examples/speech_recognition/infer.py", line 415, in make_parser
    parser = options.get_generation_parser()
  File "/home/hkarakostanoglou@quantmetry.com/fairseq/fairseq/options.py", line 47, in get_generation_parser
    parser = get_parser("Generation", default_task)
  File "/home/hkarakostanoglou@quantmetry.com/fairseq/fairseq/options.py", line 217, in get_parser
    utils.import_user_module(usr_args)
  File "/home/hkarakostanoglou@quantmetry.com/fairseq/fairseq/utils.py", line 488, in import_user_module
    import_tasks(tasks_path, f"{module_name}.tasks")
  File "/home/hkarakostanoglou@quantmetry.com/fairseq/fairseq/tasks/__init__.py", line 126, in import_tasks
    importlib.import_module(namespace + "." + task_name)
  File "/home/hkarakostanoglou@quantmetry.com/miniconda3/envs/wav2vec2/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/hkarakostanoglou@quantmetry.com/fairseq/examples/speech_recognition/tasks/speech_recognition.py", line 69, in <module>
    class SpeechRecognitionTask(LegacyFairseqTask):
  File "/home/hkarakostanoglou@quantmetry.com/fairseq/fairseq/tasks/__init__.py", line 75, in register_task_cls
    raise ValueError("Cannot register duplicate task ({})".format(name))
ValueError: Cannot register duplicate task (speech_recognition)`

I fall to understand what exactly the infer.py script does, but it seems that the problem comes from the file `fairseq/fairseq/tasks/__init__.py`

Can someone help me please?

By the way, just to see what happens, I tried to comment the if-statement which raises the exception `ValueError: Cannot register duplicate task` in the /tasks/__init__.py file, and I got this error this time:

`Traceback (most recent call last):
  File "examples/speech_recognition/infer.py", line 427, in <module>
    cli_main()
  File "examples/speech_recognition/infer.py", line 421, in cli_main
    parser = make_parser()
  File "examples/speech_recognition/infer.py", line 415, in make_parser
    parser = options.get_generation_parser()
  File "/home/hkarakostanoglou@quantmetry.com/fairseq/fairseq/options.py", line 47, in get_generation_parser
    parser = get_parser("Generation", default_task)
  File "/home/hkarakostanoglou@quantmetry.com/fairseq/fairseq/options.py", line 217, in get_parser
    utils.import_user_module(usr_args)
  File "/home/hkarakostanoglou@quantmetry.com/fairseq/fairseq/utils.py", line 488, in import_user_module
    import_tasks(tasks_path, f"{module_name}.tasks")
  File "/home/hkarakostanoglou@quantmetry.com/fairseq/fairseq/tasks/__init__.py", line 126, in import_tasks
    importlib.import_module(namespace + "." + task_name)
  File "/home/hkarakostanoglou@quantmetry.com/miniconda3/envs/wav2vec2/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/hkarakostanoglou@quantmetry.com/fairseq/examples/speech_recognition/tasks/speech_recognition.py", line 69, in <module>
    class SpeechRecognitionTask(LegacyFairseqTask):
  File "/home/hkarakostanoglou@quantmetry.com/fairseq/fairseq/tasks/__init__.py", line 83, in register_task_cls
    raise ValueError(
ValueError: Cannot register task with duplicate class name (SpeechRecognitionTask)`

This time, I figured out that there were multiple such if-statements to raise such exceptions in the /tasks/__init__.py file, and also in the /models/__init__.py file. 
So, just to see what happens, I tried to comment every such section in the code.
Then, I got this new error:

`INFO:__main__:| loading model(s) from /home/hkarakostanoglou@quantmetry.com/wav2vec_small_960h.pt
Traceback (most recent call last):
  File "examples/speech_recognition/infer.py", line 427, in <module>
    cli_main()
  File "examples/speech_recognition/infer.py", line 423, in cli_main
    main(args)
  File "examples/speech_recognition/infer.py", line 229, in main
    models, saved_cfg, task = checkpoint_utils.load_model_ensemble_and_task(
  File "/home/hkarakostanoglou@quantmetry.com/fairseq/fairseq/checkpoint_utils.py", line 447, in load_model_ensemble_and_task
    model.load_state_dict(
  File "/home/hkarakostanoglou@quantmetry.com/fairseq/fairseq/models/fairseq_model.py", line 125, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/home/hkarakostanoglou@quantmetry.com/miniconda3/envs/wav2vec2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1406, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Wav2VecCtc:
        size mismatch for w2v_encoder.proj.weight: copying a param with shape torch.Size([32, 768]) from checkpoint, the shape in current model is torch.Size([5000, 768]).
        size mismatch for w2v_encoder.proj.bias: copying a param with shape torch.Size([32]) from checkpoint, the shape in current model is torch.Size([5000]).`

Can someone help me for that also please?

My environment:

 - fairseq Version : master
 - PyTorch Version 1.9.0
 - OS : Debian GNU/Linux 10 (buster)
 - I installed fairseq with git clone from the html adress then setup.py
 - Python version: 3.8.10
 - CUDA version: 11.4.48

Thank you very much in advance!

**Comment by AngeloMendes** [comment]
same problem

**Comment by lovecambi** [comment]
In the latest fairseq, the module import for usr-dir has been moved to https://github.com/pytorch/fairseq/blob/597a8fc5e36110450c6a7251506d17b42b635643/fairseq/utils.py#L456

So you don't have to setup the customized import, and you should remove the code for the module import in files, e.g.,
https://github.com/pytorch/fairseq/blob/master/examples/speech_recognition/tasks/__init__.py
https://github.com/pytorch/fairseq/blob/master/examples/speech_recognition/models/__init__.py
