### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for TransformerLanguageModel: Unexpected key(s) in state_dict: "decoder.layer_norm.weight", "decoder.layer_norm.bias". 

### ISSUE THREAD

**Issue by damyana79** [pytorch/fairseq#3737]
## 🐛 Bug

I tried to load a pretrained language model. It seems that the state dictionary of my language model is not up to date with the current version of fairseq any more.

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):
1. Command
`custom_lm = TransformerLanguageModel.from_pretrained('/fairseq_train/lm_models/LM_de', 'checkpoint_best.pt')`
2. Error

Traceback (most recent call last):
  File "/raid/bin/daga01/fairseq/fairseq_cli/generate.py", line 20, in <module>
    from fairseq import checkpoint_utils, options, scoring, tasks, utils
  File "/raid/bin/daga01/fairseq/fairseq/__init__.py", line 32, in <module>
    import fairseq.criterions  # noqa
  File "/raid/bin/daga01/fairseq/fairseq/criterions/__init__.py", line 36, in <module>
    importlib.import_module("fairseq.criterions." + file_name)
  File "/home/gateva/miniconda3/envs/fs_curr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/raid/bin/daga01/fairseq/fairseq/criterions/ctc.py", line 19, in <module>
    from fairseq.tasks import FairseqTask
  File "/raid/bin/daga01/fairseq/fairseq/tasks/__init__.py", line 116, in <module>
    module = importlib.import_module("fairseq.tasks." + task_name)
  File "/home/gateva/miniconda3/envs/fs_curr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/raid/bin/daga01/fairseq/fairseq/tasks/semisupervised_translation.py", line 23, in <module>
    from fairseq.sequence_generator import SequenceGenerator
  File "/raid/bin/daga01/fairseq/fairseq/sequence_generator.py", line 16, in <module>
    from fairseq.distance_calculator import *
  File "/raid/bin/daga01/fairseq/fairseq/distance_calculator.py", line 45, in <module>
    custom_lm = TransformerLanguageModel.from_pretrained('/raid/data/daga01/fairseq_train/lm_models/my_LM_de', 'checkpoint_best.pt')
  File "/raid/bin/daga01/fairseq/fairseq/models/fairseq_model.py", line 264, in from_pretrained
    x = hub_utils.from_pretrained(
  File "/raid/bin/daga01/fairseq/fairseq/hub_utils.py", line 73, in from_pretrained
    models, args, task = checkpoint_utils.load_model_ensemble_and_task(
  File "/raid/bin/daga01/fairseq/fairseq/checkpoint_utils.py", line 447, in load_model_ensemble_and_task
    model.load_state_dict(
  File "/raid/bin/daga01/fairseq/fairseq/models/fairseq_model.py", line 125, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/home/gateva/miniconda3/envs/fs_curr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for TransformerLanguageModel:
	Unexpected key(s) in state_dict: "decoder.layer_norm.weight", "decoder.layer_norm.bias".

**Comment by glowinthedark** [comment]
There seems to this in the docs:
- https://fairseq.readthedocs.io/en/v0.7.2/models.html#fairseq.models.fconv.FConvDecoder.upgrade_state_dict
-  https://fairseq.readthedocs.io/en/v0.7.2/models.html#fairseq.models.transformer.TransformerEncoderLayer.upgrade_state_dict_named

apparently, the dictionaries need migrating for use with the latest version of `fairseq` or the module needs to be downgraded to the latest compatible dictionary version.
