### ISSUE TITLE
RuntimeError when execute w2vu_generate.py

### ISSUE THREAD

**Issue by Ning107** [pytorch/fairseq#3749]
## ❓ Questions and Help

Hi, I am using Wav2vec Unsupervised (wav2vec-U) framework and at the step of generation by follow command 
```bash
python3 w2vu_generate.py --config-dir config/generate --config-name viterbi \ 
fairseq.common.user_dir=$FAIRSEQ_ROOT/examples/wav2vec/unsupervised \
fairseq.task.data=/workspace/wav2vec_u/workplace/prepare_timit/unmatched/feat \
fairseq.common_eval.path=/workspace/wav2vec_u/fairseq2/examples/wav2vec/unsupervised/multirun/2021-07-28/08-50-33/0/checkpoint_last.pt \
fairseq.dataset.gen_subset=valid \
results_path=./transcriptions \
lm_model=/workspace/wav2vec_u/workplace/prepare_timit/unmatched/phones/train_text_phn.04.bin \
```
I got an RuntimeError as below : 
```python
[2021-07-28 10:23:17,042][__main__][INFO] - | loading model(s) from /workspace/wav2vec_u/fairseq2/examples/wav2vec/unsupervised/multirun/2021-07-28/08-50-33/0/checkpoint_last.pt
[2021-07-28 10:23:22,497][unsupervised.data.extracted_features_dataset][INFO] - loaded 620, skipped 0 samples
[2021-07-28 10:23:22,497][unsupervised.tasks.unpaired_audio_text][INFO] - split valid has unpaired text? False
[2021-07-28 10:23:22,498][__main__][INFO] - | /workspace/wav2vec_u/workplace/prepare_timit/unmatched/feat valid 620 examples
Traceback (most recent call last):                                                                                                                                                         
  File "w2vu_generate.py", line 692, in hydra_main
    _, score = main(cfg)
  File "w2vu_generate.py", line 621, in main
    gen_result = generate(cfg, models, saved_cfg, use_cuda)
  File "w2vu_generate.py", line 456, in generate
    generator, models, num_feats, sample, task, use_cuda
  File "w2vu_generate.py", line 568, in gen_hypos
    hypos = task.inference_step(generator, models, sample, None)
  File "/workspace/wav2vec_u/fairseq2/fairseq/tasks/fairseq_task.py", line 528, in inference_step
    models, sample, prefix_tokens=prefix_tokens, constraints=constraints
  File "/workspace/wav2vec_u/fairseq2/examples/speech_recognition/w2l_decoder.py", line 76, in generate
    emissions = self.get_emissions(models, encoder_input)
  File "/workspace/wav2vec_u/fairseq2/examples/speech_recognition/w2l_decoder.py", line 82, in get_emissions
    encoder_out = model(**encoder_input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/wav2vec_u/fairseq2/examples/wav2vec/unsupervised/models/wav2vec_u.py", line 538, in forward
    gen_result = self.generator(features, random_label, padding_mask)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/workspace/wav2vec_u/fairseq2/examples/wav2vec/unsupervised/models/wav2vec_u.py", line 310, in forward
    dense_x = self.proj(dense_x)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 263, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/conv.py", line 260, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [43, 512, 4], expected input[1, 1024, 237] to have 512 channels, but got 1024 channels instead
```
I don't get where the error is. Can someone help ? Thanks in advance !

**Comment by prokotg** [comment]
Seems like you use initial features

`fairseq.task.data=/workspace/wav2vec_u/workplace/prepare_timit/unmatched/feat`

instead of processed feats in subfolders, probably something like:

`fairseq.task.data=/workspace/wav2vec_u/workplace/prepare_timit/unmatched/feat/precompute_pca512_cls128_mean_pooled`
