### ISSUE TITLE
Pre-train a HuBERT model

### ISSUE THREAD

**Issue by 1017549629** [pytorch/fairseq#3795]
`python fairseq_cli/hydra_train.py \
  --config-dir examples/hubert/config/pretrain \
  --config-name hubert_base_librispeech \
  task.data=data/wav.tsv \
  task.label_dir=data/mfcc/labels/wav.km \
  model.label_rate=100`

I follow the [https://github.com/pytorch/fairseq/tree/master/examples/hubert#pre-train-a-hubert-model], May I right? I meet
 the following errors. How can I fix it, thanks.

Traceback (most recent call last):
  File "fairseq_cli/hydra_train.py", line 28, in hydra_main
    _hydra_main(cfg)
  File "fairseq_cli/hydra_train.py", line 53, in _hydra_main
    distributed_utils.call_main(cfg, pre_main, **kwargs)
  File "/tsdata/kaldi/egs/tfc/gnn/fairseq/fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "/tsdata/kaldi/egs/tfc/gnn/fairseq/fairseq_cli/train.py", line 97, in main
    model = task.build_model(cfg.model)
  File "/tsdata/kaldi/egs/tfc/gnn/fairseq/fairseq/tasks/fairseq_task.py", line 320, in build_model
    model = models.build_model(cfg, self)
  File "/tsdata/kaldi/egs/tfc/gnn/fairseq/fairseq/models/__init__.py", line 107, in build_model
    return model.build_model(cfg, task)
  File "/tsdata/kaldi/egs/tfc/gnn/fairseq/fairseq/models/hubert/hubert.py", line 320, in build_model
    model = HubertModel(cfg, task.cfg, task.dictionaries)
  File "/tsdata/kaldi/egs/tfc/gnn/fairseq/fairseq/tasks/hubert_pretraining.py", line 142, in dictionaries
    return self.state.dictionaries
  File "/tsdata/kaldi/egs/tfc/gnn/fairseq/fairseq/tasks/fairseq_task.py", line 42, in __getattr__
    self._state[name] = self._factories[name]()
  File "/tsdata/kaldi/egs/tfc/gnn/fairseq/fairseq/tasks/hubert_pretraining.py", line 152, in load_dictionaries
    print(self.cfg.labels)
omegaconf.errors.MissingMandatoryValue: Missing mandatory value: labels
        full_key: labels
        reference_type=Optional[HubertPretrainingConfig]
        object_type=HubertPretrainingConfig

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by namtp-ai** [comment]
Just add ` task.labels='["km"]'` affter ` task.label_dir=data/mfcc/labels/wav.km`
