### ISSUE TITLE
--eval bleu metric used in fairseq-train raises AttributeError in sacrebleu module 

### ISSUE THREAD

**Issue by Aiden-Frost** [pytorch/fairseq#3806]
## 🐛 Bug

When using the --eval bleu metric in fairseq-train, during validation it raises: `AttributeError: module 'sacrebleu' has no attribute 'compute_bleu'
`
### To Reproduce

```
fairseq-train final_bin/ \
--arch transformer \
--max-source-positions=200 \
--max-target-positions 200 \
--dropout 0.2 \
--encoder-embed-dim 768 \
--encoder-ffn-embed-dim 1536 \
--encoder-layers 4 \
--encoder-attention-heads 16 \
--encoder-learned-pos \
--decoder-embed-dim 768 \
--decoder-ffn-embed-dim 1536 \
--decoder-layers 4 \
--decoder-attention-heads 16 \
--decoder-learned-pos \
--optimizer adam \
--adam-betas "(0.9,0.98)" \
--clip-norm 0.0 \
--lr 5e-4 \
--warmup-init-lr 1e-07 \
--warmup-updates 4000 \
--batch-size 64 \
--seed 1 \
--save-dir model/ \
--wandb-project "hermes" \
--ddp-backend=no_c10d \
--skip-invalid-size-inputs-valid-test \
--update-freq 3 \
--lr-scheduler inverse_sqrt \
--criterion label_smoothed_cross_entropy \
--label-smoothing 0.1 \
--eval-bleu \
--eval-bleu-print-samples \
--best-checkpoint-metric bleu 
```

Steps to reproduce the behavior (**always include the command you ran**):

1. Run the above command on fairseq-preprocess data
2. See error

### Error Stack Trace
```
/opt/conda/lib/python3.7/site-packages/torch/_tensor.py:575: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  /pytorch/aten/src/ATen/native/BinaryOps.cpp:467.)
  return torch.floor_divide(self, other)
Traceback (most recent call last):
  File "/opt/conda/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/home/jupyter/kn-en/fairseq/fairseq_cli/train.py", line 507, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home/jupyter/kn-en/fairseq/fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "/home/jupyter/kn-en/fairseq/fairseq_cli/train.py", line 180, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/opt/conda/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/jupyter/kn-en/fairseq/fairseq_cli/train.py", line 306, in train
    cfg, trainer, task, epoch_itr, valid_subsets, end_of_epoch
  File "/home/jupyter/kn-en/fairseq/fairseq_cli/train.py", line 392, in validate_and_save
    valid_losses = validate(cfg, trainer, task, epoch_itr, valid_subsets)
  File "/home/jupyter/kn-en/fairseq/fairseq_cli/train.py", line 462, in validate
    trainer.valid_step(sample)
  File "/opt/conda/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/jupyter/kn-en/fairseq/fairseq/trainer.py", line 993, in valid_step
    logging_output = self._reduce_and_log_stats(logging_outputs, sample_size)
  File "/home/jupyter/kn-en/fairseq/fairseq/trainer.py", line 1363, in _reduce_and_log_stats
    logging_output = agg.get_smoothed_values()
  File "/home/jupyter/kn-en/fairseq/fairseq/logging/meters.py", line 304, in get_smoothed_values
    for key in self.keys()
  File "/home/jupyter/kn-en/fairseq/fairseq/logging/meters.py", line 305, in <listcomp>
    if not key.startswith("_")
  File "/home/jupyter/kn-en/fairseq/fairseq/logging/meters.py", line 295, in get_smoothed_value
    return meter.fn(self)
  File "/home/jupyter/kn-en/fairseq/fairseq/tasks/translation.py", line 423, in compute_bleu
    fn_sig = inspect.getfullargspec(sacrebleu.compute_bleu)[0]
AttributeError: module 'sacrebleu' has no attribute 'compute_bleu'
```

### Expected behavior

When the --eval metric is set to loss (default) the model trains as expected.
### Environment

 - fairseq Version - master
 - PyTorch Version - 1.9.0+cu111
 - OS (e.g., Linux) - Linux 18.0.4
 - How you installed fairseq - `git clone https://github.com/pytorch/fairseq`
 - Build command you used -  `pip install --editable ./`
 - Python version - 3.7.10
 - CUDA/cuDNN version - 11.0
 - GPU models and configuration - Tesla T4
 - Any other relevant information - Complete setup on GCP AI platform notebook.

### Additional context

This exact command used to work 2 months back in google colab.

**Comment by lovecambi** [comment]
Maybe because sacrebleu is updated to 2.0.0. You can try 1.5.1.

**Comment by Aiden-Frost** [comment]
> Maybe because sacrebleu is updated to 2.0.0. You can try 1.5.1.

Yup, this seems to be the issue. Now it's working as expected. Thanks a lot. Now I'll close the issue.
