### ISSUE TITLE
Wav2vec CTC fine tuning model error

### ISSUE THREAD

**Issue by v-manhlt3** [pytorch/fairseq#3831]
## ❓ Questions and Help
Hi everyone, I am going to do fine-tuning my custom dataset using the `wav2vec_small_960h.pt`.

However, I got an error which details as below:
`
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/ubuntu/.conda/envs/fairseq/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/ubuntu/manhlt/fairseq/fairseq/distributed/utils.py", line 328, in distributed_main
    main(cfg, **kwargs)
  File "/home/ubuntu/manhlt/fairseq/fairseq_cli/train.py", line 97, in main
    model = task.build_model(cfg.model)
  File "/home/ubuntu/manhlt/fairseq/fairseq/tasks/audio_finetuning.py", line 190, in build_model
    model = super().build_model(model_cfg)
  File "/home/ubuntu/manhlt/fairseq/fairseq/tasks/audio_pretraining.py", line 198, in build_model
    model = super().build_model(model_cfg)
  File "/home/ubuntu/manhlt/fairseq/fairseq/tasks/fairseq_task.py", line 320, in build_model
    model = models.build_model(cfg, self)
  File "/home/ubuntu/manhlt/fairseq/fairseq/models/__init__.py", line 107, in build_model
    return model.build_model(cfg, task)
  File "/home/ubuntu/manhlt/fairseq/fairseq/models/wav2vec/wav2vec2_asr.py", line 176, in build_model
    w2v_encoder = Wav2VecEncoder(cfg, len(task.target_dictionary))
  File "/home/ubuntu/manhlt/fairseq/fairseq/models/wav2vec/wav2vec2_asr.py", line 356, in __init__
    model = task.build_model(w2v_args.model)
  File "/home/ubuntu/manhlt/fairseq/fairseq/tasks/audio_pretraining.py", line 198, in build_model
    model = super().build_model(model_cfg)
  File "/home/ubuntu/manhlt/fairseq/fairseq/tasks/fairseq_task.py", line 320, in build_model
    model = models.build_model(cfg, self)
  File "/home/ubuntu/manhlt/fairseq/fairseq/models/__init__.py", line 107, in build_model
    return model.build_model(cfg, task)
  File "/home/ubuntu/manhlt/fairseq/fairseq/models/wav2vec/wav2vec2_asr.py", line 176, in build_model
    w2v_encoder = Wav2VecEncoder(cfg, len(task.target_dictionary))
TypeError: object of type 'NoneType' has no len()
`
#### Code
here is my running script:
`
fairseq-hydra-train task.data=/home/ubuntu/manhlt/phoST-ASR/format_dataset/phost-fairseq-test/ \
                    model.w2v_path=/home/ubuntu/wav2vec_small_960h.pt \
                    --config-dir config/finetuning \
                    --config-name base_100h
`
I already have these files in the data folder:
- dict.ltr.txt
- train.ltr
- train.wrd
- valid.ltr
- valid.wrd
- train.tsv
- valid.tsv
- lexicon.txt
   

#### What's your environment?

 - fairseq Version : 1.0.0a0+6f847c8
 - PyTorch Version: 1.9
 - OS linux: Ubuntu 18.04
 - How you installed fairseq (`pip`, source): from source
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version: Cuda 11.0
 - GPU models and configuration: NVIDIA V100
 - Any other relevant information:

**Comment by xiaoch2004** [comment]
wav2vec_small_960h.pt is the model after finetuned. You should use wav2vec_small.pt instead

**Comment by v-manhlt3** [comment]
Thanks for your quick response! the problem is solved.
