### ISSUE TITLE
wav2vec-U training is difficult to converge

### ISSUE THREAD

**Issue by ace8090** [pytorch/fairseq#3839]
First, I want to implement the wav2vec-u project. My environment is built based on the docker environment（[wav2vec-u-exp](https://github.com/voidful/wav2vec-u-exp)）, and I implemented the training and testing process on the docker environment. But now I train and test on the timit data set, and the WER obtained is 82%, and the loss of the training process is difficult to converge. I will describe the problem in detail below:

**Environment**：[wav2vec-u-exp](https://github.com/voidful/wav2vec-u-exp)

**GPU**：1080Ti

**Pytorch**：torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0

<br/>

Create docker：

```
docker run -v $(pwd):/workspace/data --gpus all -it -p 2333:22 --name asr --ipc=host voidful/wav2vec-u:1.0.0 bash
```

Next, prepare text and voice data according to the readme on the docker image. My problem occurred during the training process：

**When I run the training script directly, I may encounter the first problem below. After I solve the first problem in my way, I will encounter the second problem again. After searching for solutions on the Internet, I will encounter the second problem again. Will encounter the third problem. The following section records the errors and my own solutions when these three problems occurred.**

- The first question is:
When executing the running training script, a memory error may occur. The solution is to add *CUDA_LAUNCH_BLOCKING=1* when running the script.

```sh
#training script,
PYTHONPATH=$FAIRSEQ_ROOT PREFIX=$PREFIX fairseq-hydra-train \
    -m --config-dir /workspace/project/fairseq/examples/wav2vec/unsupervised/config/gan \
    --config-name w2vu \
    task.data=${TASK_DATA} \
    task.text_data=${TEXT_DATA} \
    task.kenlm_path=${KENLM_PATH} \
    common.user_dir=${FAIRSEQ_ROOT}/examples/wav2vec/unsupervised \
    model.code_penalty=2 model.gradient_penalty=1.5 \
    model.smoothness_weight=0.5 'common.seed=range(0,5)'
```

```sh
#Error RuntimeError: CUDA error: an illegal memory access was encountered
Traceback (most recent call last):
  File "/opt/conda/bin/fairseq-hydra-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-hydra-train')())
  File "/workspace/project/fairseq/fairseq_cli/hydra_train.py", line 76, in cli_main
    hydra_main()
  File "/opt/conda/lib/python3.8/site-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 354, in _run_hydra
    run_and_report(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 355, in <lambda>
    lambda: hydra.multirun(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 136, in multirun
    return sweeper.sweep(arguments=task_overrides)
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/core_plugins/basic_sweeper.py", line 154, in sweep
    results = self.launcher.launch(batch, initial_job_idx=initial_job_idx)
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/core_plugins/basic_launcher.py", line 76, in launch
    ret = run_job(
  File "/opt/conda/lib/python3.8/site-packages/hydra/core/utils.py", line 127, in run_job
    ret.return_value = task_function(task_cfg)
  File "/workspace/project/fairseq/fairseq_cli/hydra_train.py", line 45, in hydra_main
    distributed_utils.call_main(cfg, pre_main)
  File "/workspace/project/fairseq/fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "/workspace/project/fairseq/fairseq_cli/train.py", line 180, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/project/fairseq/fairseq_cli/train.py", line 291, in train
    log_output = trainer.train_step(samples)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/project/fairseq/fairseq/trainer.py", line 739, in train_step
    raise e
  File "/workspace/project/fairseq/fairseq/trainer.py", line 707, in train_step
    loss, sample_size_i, logging_output = self.task.train_step(
  File "/workspace/project/fairseq/fairseq/tasks/fairseq_task.py", line 492, in train_step
    loss, sample_size, logging_output = criterion(model, sample)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/project/fairseq/fairseq/criterions/model_criterion.py", line 87, in forward
    logging_output[lk] = float(net_output[lk])
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

```

```sh
#Solution
#Add this code CUDA_LAUNCH_BLOCKING=1
CUDA_LAUNCH_BLOCKING=1 PYTHONPATH=$FAIRSEQ_ROOT PREFIX=$PREFIX fairseq-hydra-train \
    -m --config-dir /workspace/project/fairseq/examples/wav2vec/unsupervised/config/gan \
    --config-name w2vu \
    task.data=${TASK_DATA} \
    task.text_data=${TEXT_DATA} \
    task.kenlm_path=${KENLM_PATH} \
    common.user_dir=${FAIRSEQ_ROOT}/examples/wav2vec/unsupervised \
    model.code_penalty=2 model.gradient_penalty=1.5 \
    model.smoothness_weight=0.5 'common.seed=range(0,5)'
```

<br/>

- The second question is:
A cudnn error occurred when running the training script.

```sh
#training script
CUDA_LAUNCH_BLOCKING=1 PYTHONPATH=$FAIRSEQ_ROOT PREFIX=$PREFIX fairseq-hydra-train \
    -m --config-dir /workspace/project/fairseq/examples/wav2vec/unsupervised/config/gan \
    --config-name w2vu \
    task.data=${TASK_DATA} \
    task.text_data=${TEXT_DATA} \
    task.kenlm_path=${KENLM_PATH} \
    common.user_dir=${FAIRSEQ_ROOT}/examples/wav2vec/unsupervised \
    model.code_penalty=2 model.gradient_penalty=1.5 \
    model.smoothness_weight=0.5 'common.seed=range(0,5)'
```

```sh
#Error RuntimeError: Unable to find a valid cuDNN algorithm to run convolution
Traceback (most recent call last):
  File "/opt/conda/bin/fairseq-hydra-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-hydra-train')())
  File "/workspace/project/fairseq/fairseq_cli/hydra_train.py", line 76, in cli_main
    hydra_main()
  File "/opt/conda/lib/python3.8/site-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 354, in _run_hydra
    run_and_report(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 355, in <lambda>
    lambda: hydra.multirun(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 136, in multirun
    return sweeper.sweep(arguments=task_overrides)
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/core_plugins/basic_sweeper.py", line 154, in sweep
    results = self.launcher.launch(batch, initial_job_idx=initial_job_idx)
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/core_plugins/basic_launcher.py", line 76, in launch
    ret = run_job(
  File "/opt/conda/lib/python3.8/site-packages/hydra/core/utils.py", line 127, in run_job
    ret.return_value = task_function(task_cfg)
  File "/workspace/project/fairseq/fairseq_cli/hydra_train.py", line 45, in hydra_main
    distributed_utils.call_main(cfg, pre_main)
  File "/workspace/project/fairseq/fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "/workspace/project/fairseq/fairseq_cli/train.py", line 180, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/project/fairseq/fairseq_cli/train.py", line 291, in train
    log_output = trainer.train_step(samples)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/project/fairseq/fairseq/trainer.py", line 739, in train_step
    raise e
  File "/workspace/project/fairseq/fairseq/trainer.py", line 707, in train_step
    loss, sample_size_i, logging_output = self.task.train_step(
  File "/workspace/project/fairseq/fairseq/tasks/fairseq_task.py", line 492, in train_step
    loss, sample_size, logging_output = criterion(model, sample)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/project/fairseq/fairseq/criterions/model_criterion.py", line 50, in forward
    net_output = model(**sample["net_input"])
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/project/fairseq/examples/wav2vec/unsupervised/models/wav2vec_u.py", line 594, in forward
    grad_pen = self.calc_gradient_penalty(token_x, dense_x)
  File "/workspace/project/fairseq/examples/wav2vec/unsupervised/models/wav2vec_u.py", line 379, in calc_gradient_penalty
    gradients = autograd.grad(
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py", line 226, in grad
    return Variable._execution_engine.run_backward(
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution
root@9923932ef97d:/workspace/data# 

```

```sh
#Solution
vim /workspace/project/fairseq/fairseq_cli/hydra_train.py
#Paste the content below to line 76
#close cudnn
torch.backends.cudnn.enabled = False

```

<br/>

- Question third is:
Problems during training

```sh
#training script
#Added content on line 76 of hydra_train.py

CUDA_LAUNCH_BLOCKING=1 PYTHONPATH=$FAIRSEQ_ROOT PREFIX=$PREFIX fairseq-hydra-train \
    -m --config-dir /workspace/project/fairseq/examples/wav2vec/unsupervised/config/gan \
    --config-name w2vu \
    task.data=${TASK_DATA} \
    task.text_data=${TEXT_DATA} \
    task.kenlm_path=${KENLM_PATH} \
    common.user_dir=${FAIRSEQ_ROOT}/examples/wav2vec/unsupervised \
    model.code_penalty=2 model.gradient_penalty=1.5 \
    model.smoothness_weight=0.5 'common.seed=range(0,5)'
```

```sh
#RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
Traceback (most recent call last):
  File "/opt/conda/bin/fairseq-hydra-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-hydra-train')())
  File "/workspace/project/fairseq/fairseq_cli/hydra_train.py", line 76, in cli_main
    hydra_main()
  File "/opt/conda/lib/python3.8/site-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 354, in _run_hydra
    run_and_report(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 355, in <lambda>
    lambda: hydra.multirun(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 136, in multirun
    return sweeper.sweep(arguments=task_overrides)
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/core_plugins/basic_sweeper.py", line 154, in sweep
    results = self.launcher.launch(batch, initial_job_idx=initial_job_idx)
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/core_plugins/basic_launcher.py", line 76, in launch
    ret = run_job(
  File "/opt/conda/lib/python3.8/site-packages/hydra/core/utils.py", line 127, in run_job
    ret.return_value = task_function(task_cfg)
  File "/workspace/project/fairseq/fairseq_cli/hydra_train.py", line 45, in hydra_main
    distributed_utils.call_main(cfg, pre_main)
  File "/workspace/project/fairseq/fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "/workspace/project/fairseq/fairseq_cli/train.py", line 180, in main
    valid_losses, should_stop = train(cfg, trainer, task, epoch_itr)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/project/fairseq/fairseq_cli/train.py", line 291, in train
    log_output = trainer.train_step(samples)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/project/fairseq/fairseq/trainer.py", line 739, in train_step
    raise e
  File "/workspace/project/fairseq/fairseq/trainer.py", line 707, in train_step
    loss, sample_size_i, logging_output = self.task.train_step(
  File "/workspace/project/fairseq/fairseq/tasks/fairseq_task.py", line 492, in train_step
    loss, sample_size, logging_output = criterion(model, sample)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/project/fairseq/fairseq/criterions/model_criterion.py", line 50, in forward
    net_output = model(**sample["net_input"])
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/project/fairseq/examples/wav2vec/unsupervised/models/wav2vec_u.py", line 594, in forward
    grad_pen = self.calc_gradient_penalty(token_x, dense_x)
  File "/workspace/project/fairseq/examples/wav2vec/unsupervised/models/wav2vec_u.py", line 379, in calc_gradient_penalty
    gradients = autograd.grad(
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/__init__.py", line 226, in grad
    return Variable._execution_engine.run_backward(
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.

import torch
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.benchmark = False
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([24, 65, 1, 68], dtype=torch.float, device='cuda', requires_grad=True)
net = torch.nn.Conv2d(65, 384, kernel_size=[1, 6], padding=[0, 5], stride=[1, 1], dilation=[1, 1], groups=1)
net = net.cuda().float()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()

ConvolutionParams 
    data_type = CUDNN_DATA_FLOAT
    padding = [0, 5, 0]
    stride = [1, 1, 0]
    dilation = [1, 1, 0]
    groups = 1
    deterministic = false
    allow_tf32 = true
input: TensorDescriptor 0x7f45b00fe100
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 24, 65, 1, 68, 
    strideA = 4420, 68, 68, 1, 
output: TensorDescriptor 0x7f45b00fc000
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 24, 384, 1, 73, 
    strideA = 28032, 73, 73, 1, 
weight: FilterDescriptor 0x7f45b010eb30
    type = CUDNN_DATA_FLOAT
    tensor_format = CUDNN_TENSOR_NCHW
    nbDims = 4
    dimA = 384, 65, 1, 6, 
Pointer addresses: 
    input: 0x7f4572ccf400
    output: 0x7f4592000000
    weight: 0x7f45c1000000
Additional pointer addresses: 
    grad_output: 0x7f4592000000
    grad_input: 0x7f4572ccf400
Backward data algorithm: 1

```

```sh
#Solution

vim /workspace/project/fairseq/examples/wav2vec/unsupervised/config/gan/w2vu.yaml
#Adjust batch_size
#For example: batch_size=10
```

<br/>

In the end, I completed the training by reducing the batch_size and then tested it. The WER on the TIMIT dataset was 82%. And I found that the loss during the training process has been unstable, and it may be difficult to converge. The following shows the output results during the training process？

```sh
[2021-08-26 21:54:24,446][fairseq.trainer][INFO] - begin training epoch 292
[2021-08-26 21:54:24,448][fairseq_cli.train][INFO] - Start iterating over samples
[2021-08-26 21:54:30,016][train_inner][INFO] - {"epoch": 292, "update": 291.126, "loss": "2.851", "ntokens": "8", "nsentences": "8", "temp": "0.1", "code_ppl": "16.418", "loss_code_pen": "0.427", "loss_smoothness": "1.647", "loss_dense_g": "3.436", "lm_score_sum": 0.0, "num_pred_chars": 0.0, "loss_grad_pen": "0.105", "loss_dense_d": "0.045", "loss_token_d": "0.041", "wps": "87.4", "ups": "10.93", "wpb": "8", "bsz": "8", "num_updates": "134500", "lr_discriminator": "0.0005", "lr_generator": "0.0004", "gnorm": "23.855", "clip": "76", "train_wall": "8", "gb_free": "9.9", "wall": "11388"}
[2021-08-26 21:54:38,810][train_inner][INFO] - {"epoch": 292, "update": 291.342, "loss": "2.828", "ntokens": "8", "nsentences": "8", "temp": "0.1", "code_ppl": "16.71", "loss_code_pen": "0.451", "loss_smoothness": "1.658", "loss_dense_g": "3.343", "lm_score_sum": 0.0, "num_pred_chars": 0.0, "loss_grad_pen": "0.108", "loss_dense_d": "0.048", "loss_token_d": "0.049", "wps": "91.1", "ups": "11.38", "wpb": "8", "bsz": "8", "num_updates": "134600", "lr_discriminator": "0.0005", "lr_generator": "0.0004", "gnorm": "22.105", "clip": "78", "train_wall": "8", "gb_free": "9.9", "wall": "11397"}
[2021-08-26 21:54:47,029][train_inner][INFO] - {"epoch": 292, "update": 291.558, "loss": "2.834", "ntokens": "8", "nsentences": "8", "temp": "0.1", "code_ppl": "16.747", "loss_code_pen": "0.436", "loss_smoothness": "1.629", "loss_dense_g": "3.414", "lm_score_sum": 0.0, "num_pred_chars": 0.0, "loss_grad_pen": "0.099", "loss_dense_d": "0.045", "loss_token_d": "0.045", "wps": "97.4", "ups": "12.18", "wpb": "8", "bsz": "8", "num_updates": "134700", "lr_discriminator": "0.0005", "lr_generator": "0.0004", "gnorm": "22.553", "clip": "83", "train_wall": "8", "gb_free": "9.9", "wall": "11405"}
[2021-08-26 21:54:55,466][train_inner][INFO] - {"epoch": 292, "update": 291.775, "loss": "2.81", "ntokens": "8", "nsentences": "8", "temp": "0.1", "code_ppl": "16.494", "loss_code_pen": "0.467", "loss_smoothness": "1.678", "loss_dense_g": "3.298", "lm_score_sum": 0.0, "num_pred_chars": 0.0, "loss_grad_pen": "0.091", "loss_dense_d": "0.044", "loss_token_d": "0.042", "wps": "94.9", "ups": "11.86", "wpb": "8", "bsz": "8", "num_updates": "134800", "lr_discriminator": "0.0005", "lr_generator": "0.0004", "gnorm": "23.059", "clip": "84", "train_wall": "8", "gb_free": "9.9", "wall": "11413"}
[2021-08-26 21:55:04,362][train_inner][INFO] - {"epoch": 292, "update": 291.991, "loss": "2.857", "ntokens": "8", "nsentences": "8", "temp": "0.1", "code_ppl": "16.435", "loss_code_pen": "0.442", "loss_smoothness": "1.656", "loss_dense_g": "3.434", "lm_score_sum": 0.0, "num_pred_chars": 0.0, "loss_grad_pen": "0.098", "loss_dense_d": "0.042", "loss_token_d": "0.042", "wps": "90", "ups": "11.25", "wpb": "8", "bsz": "8", "num_updates": "134900", "lr_discriminator": "0.0005", "lr_generator": "0.0004", "gnorm": "23.513", "clip": "75", "train_wall": "9", "gb_free": "9.9", "wall": "11422"}
[2021-08-26 21:55:04,692][fairseq_cli.train][INFO] - end of epoch 292 (average epoch stats below)
[2021-08-26 21:55:04,700][train][INFO] - {"epoch": 292, "train_loss": "2.837", "train_ntokens": "8", "train_nsentences": "8", "train_temp": "0.1", "train_code_ppl": "16.611", "train_loss_code_pen": "0.447", "train_loss_smoothness": "1.659", "train_loss_dense_g": "3.382", "train_lm_score_sum": 0.0, "train_num_pred_chars": 0.0, "train_loss_grad_pen": "0.098", "train_loss_dense_d": "0.045", "train_loss_token_d": "0.044", "train_wps": "91.8", "train_ups": "11.47", "train_wpb": "8", "train_bsz": "8", "train_num_updates": "134904", "train_lr_discriminator": "0.0005", "train_lr_generator": "0.0004", "train_gnorm": "22.931", "train_clip": "79.4", "train_train_wall": "38", "train_gb_free": "9.9", "train_wall": "11422"}
[2021-08-26 21:55:04,723][fairseq.trainer][INFO] - begin training epoch 293
[2021-08-26 21:55:04,725][fairseq_cli.train][INFO] - Start iterating over samples
[2021-08-26 21:55:13,466][train_inner][INFO] - {"epoch": 293, "update": 292.208, "loss": "2.866", "ntokens": "8", "nsentences": "8", "temp": "0.1", "code_ppl": "16.901", "loss_code_pen": "0.476", "loss_smoothness": "1.696", "loss_dense_g": "3.342", "lm_score_sum": 0.0, "num_pred_chars": 0.0, "loss_grad_pen": "0.133", "loss_dense_d": "0.042", "loss_token_d": "0.044", "wps": "87.9", "ups": "10.99", "wpb": "8", "bsz": "8", "num_updates": "135000", "lr_discriminator": "0.0005", "lr_generator": "0.0004", "gnorm": "23.113", "clip": "79", "train_wall": "8", "gb_free": "9.9", "wall": "11431"}
[2021-08-26 21:55:13,469][fairseq_cli.train][INFO] - begin validation on "valid" subset
[2021-08-26 21:55:15,093][unsupervised.tasks.unpaired_audio_text][INFO] - REF: sil b r ih sil k s aa r er n aa l sil t er n ih sil t ih v sil
[2021-08-26 21:55:15,102][unsupervised.tasks.unpaired_audio_text][INFO] - HYP: sil iy z f d ih dx ih n uw sil t sil ah s sil jh ow z ah l m ow f ih n sil
[2021-08-26 21:55:15,109][unsupervised.tasks.unpaired_audio_text][INFO] - LM [REF]: -24.27172088623047, 10.264119592730438
[2021-08-26 21:55:15,117][unsupervised.tasks.unpaired_audio_text][INFO] - LM [HYP]: -42.13520812988281, 31.976348004258387
[2021-08-26 21:55:15,558][valid][INFO] - {"epoch": 293, "valid_loss": "0.915", "valid_ntokens": "301.14", "valid_nsentences": "8", "valid_lm_score_sum": "-23851.5", "valid_num_pred_chars": "16944", "valid_vocab_seen_pct": "0.953333", "valid_uer": "91.5056", "valid_weighted_lm_ppl": "26.1043", "valid_lm_ppl": "23.7248", "valid_wps": "8948.3", "valid_wpb": "301.1", "valid_bsz": "8", "valid_num_updates": "135000", "valid_best_weighted_lm_ppl": "24.2628"}
[2021-08-26 21:55:15,563][fairseq.checkpoint_utils][INFO] - Preparing to save checkpoint for epoch 293 @ 135000 updates
[2021-08-26 21:55:15,565][fairseq.trainer][INFO] - Saving checkpoint to ./checkpoint_293_135000.pt
[2021-08-26 21:55:15,639][fairseq.trainer][INFO] - Finished saving checkpoint to ./checkpoint_293_135000.pt
[2021-08-26 21:55:15,672][fairseq.checkpoint_utils][INFO] - Saved checkpoint ./checkpoint_293_135000.pt (epoch 293 @ 135000 updates, score 26.104344410133677) (writing took 0.108856263999769 seconds)
[2021-08-26 21:55:24,382][train_inner][INFO] - {"epoch": 293, "update": 292.424, "loss": "2.754", "ntokens": "8", "nsentences": "8", "temp": "0.1", "code_ppl": "16.309", "loss_code_pen": "0.413", "loss_smoothness": "1.6", "loss_dense_g": "3.275", "lm_score_sum": 0.0, "num_pred_chars": 0.0, "loss_grad_pen": "0.13", "loss_dense_d": "0.045", "loss_token_d": "0.047", "wps": "73.3", "ups": "9.17", "wpb": "8", "bsz": "8", "num_updates": "135100", "lr_discriminator": "0.0005", "lr_generator": "0.0004", "gnorm": "22.759", "clip": "84", "train_wall": "8", "gb_free": "9.9", "wall": "11442"}
[2021-08-26 21:55:33,158][train_inner][INFO] - {"epoch": 293, "update": 292.641, "loss": "2.852", "ntokens": "8", "nsentences": "8", "temp": "0.1", "code_ppl": "16.721", "loss_code_pen": "0.46", "loss_smoothness": "1.667", "loss_dense_g": "3.406", "lm_score_sum": 0.0, "num_pred_chars": 0.0, "loss_grad_pen": "0.085", "loss_dense_d": "0.045", "loss_token_d": "0.042", "wps": "91.2", "ups": "11.41", "wpb": "8", "bsz": "8", "num_updates": "135200", "lr_discriminator": "0.0005", "lr_generator": "0.0004", "gnorm": "22.263", "clip": "77", "train_wall": "8", "gb_free": "9.9", "wall": "11451"}
[2021-08-26 21:55:41,679][train_inner][INFO] - {"epoch": 293, "update": 292.857, "loss": "2.909", "ntokens": "8", "nsentences": "8", "temp": "0.1", "code_ppl": "16.719", "loss_code_pen": "0.46", "loss_smoothness": "1.691", "loss_dense_g": "3.492", "lm_score_sum": 0.0, "num_pred_chars": 0.0, "loss_grad_pen": "0.096", "loss_dense_d": "0.039", "loss_token_d": "0.04", "wps": "94", "ups": "11.74", "wpb": "8", "bsz": "8", "num_updates": "135300", "lr_discriminator": "0.0005", "lr_generator": "0.0004", "gnorm": "24.048", "clip": "86", "train_wall": "8", "gb_free": "9.9", "wall": "11459"}
[2021-08-26 21:55:47,397][fairseq_cli.train][INFO] - end of epoch 293 (average epoch stats below)
[2021-08-26 21:55:47,404][train][INFO] - {"epoch": 293, "train_loss": "2.852", "train_ntokens": "8", "train_nsentences": "8", "train_temp": "0.1", "train_code_ppl": "16.712", "train_loss_code_pen": "0.453", "train_loss_smoothness": "1.67", "train_loss_dense_g": "3.382", "train_lm_score_sum": 0.0, "train_num_pred_chars": 0.0, "train_loss_grad_pen": "0.114", "train_loss_dense_d": "0.043", "train_loss_token_d": "0.043", "train_wps": "86.6", "train_ups": "10.82", "train_wpb": "8", "train_bsz": "8", "train_num_updates": "135366", "train_lr_discriminator": "0.0005", "train_lr_generator": "0.0004", "train_gnorm": "23.047", "train_clip": "81", "train_train_wall": "38", "train_gb_free": "9.9", "train_wall": "11465"}
[2021-08-26 21:55:47,424][fairseq.trainer][INFO] - begin training epoch 294
[2021-08-26 21:55:47,426][fairseq_cli.train][INFO] - Start iterating over samples
[2021-08-26 21:55:50,931][train_inner][INFO] - {"epoch": 294, "update": 293.074, "loss": "2.854", "ntokens": "8", "nsentences": "8", "temp": "0.1", "code_ppl": "16.917", "loss_code_pen": "0.457", "loss_smoothness": "1.699", "loss_dense_g": "3.339", "lm_score_sum": 0.0, "num_pred_chars": 0.0, "loss_grad_pen": "0.127", "loss_dense_d": "0.042", "loss_token_d": "0.042", "wps": "86.6", "ups": "10.82", "wpb": "8", "bsz": "8", "num_updates": "135400", "lr_discriminator": "0.0005", "lr_generator": "0.0004", "gnorm": "23.025", "clip": "79", "train_wall": "9", "gb_free": "9.9", "wall": "11469"}
[2021-08-26 21:55:59,705][train_inner][INFO] - {"epoch": 294, "update": 293.29, "loss": "2.837", "ntokens": "8", "nsentences": "8", "temp": "0.1", "code_ppl": "16.568", "loss_code_pen": "0.445", "loss_smoothness": "1.652", "loss_dense_g": "3.386", "lm_score_sum": 0.0, "num_pred_chars": 0.0, "loss_grad_pen": "0.099", "loss_dense_d": "0.046", "loss_token_d": "0.045", "wps": "91.3", "ups": "11.41", "wpb": "8", "bsz": "8", "num_updates": "135500", "lr_discriminator": "0.0005", "lr_generator": "0.0004", "gnorm": "23.563", "clip": "84", "train_wall": "8", "gb_free": "9.9", "wall": "11477"}
[2021-08-26 21:56:08,088][train_inner][INFO] - {"epoch": 294, "update": 293.506, "loss": "2.929", "ntokens": "8", "nsentences": "8", "temp": "0.1", "code_ppl": "16.718", "loss_code_pen": "0.442", "loss_smoothness": "1.683", "loss_dense_g": "3.547", "lm_score_sum": 0.0, "num_pred_chars": 0.0, "loss_grad_pen": "0.1", "loss_dense_d": "0.044", "loss_token_d": "0.043", "wps": "95.5", "ups": "11.94", "wpb": "8", "bsz": "8", "num_updates": "135600", "lr_discriminator": "0.0005", "lr_generator": "0.0004", "gnorm": "23.75", "clip": "79", "train_wall": "8", "gb_free": "9.9", "wall": "11486"}
[2021-08-26 21:56:16,572][train_inner][INFO] - {"epoch": 294, "update": 293.723, "loss": "2.876", "ntokens": "8", "nsentences": "8", "temp": "0.1", "code_ppl": "16.655", "loss_code_pen": "0.468", "loss_smoothness": "1.727", "loss_dense_g": "3.355", "lm_score_sum": 0.0, "num_pred_chars": 0.0, "loss_grad_pen": "0.116", "loss_dense_d": "0.043", "loss_token_d": "0.043", "wps": "94.4", "ups": "11.8", "wpb": "8", "bsz": "8", "num_updates": "135700", "lr_discriminator": "0.0005", "lr_generator": "0.0004", "gnorm": "22.889", "clip": "80", "train_wall": "8", "gb_free": "9.9", "wall": "11494"}
[2021-08-26 21:56:24,901][train_inner][INFO] - {"epoch": 294, "update": 293.939, "loss": "2.825", "ntokens": "8", "nsentences": "8", "temp": "0.1", "code_ppl": "16.516", "loss_code_pen": "0.448", "loss_smoothness": "1.671", "loss_dense_g": "3.339", "lm_score_sum": 0.0, "num_pred_chars": 0.0, "loss_grad_pen": "0.102", "loss_dense_d": "0.047", "loss_token_d": "0.043", "wps": "96.1", "ups": "12.02", "wpb": "8", "bsz": "8", "num_updates": "135800", "lr_discriminator": "0.0005", "lr_generator": "0.0004", "gnorm": "22.482", "clip": "83", "train_wall": "8", "gb_free": "9.9", "wall": "11503"}
[2021-08-26 21:56:27,179][fairseq_cli.train][INFO] - end of epoch 294 (average epoch stats below)
[2021-08-26 21:56:27,186][train][INFO] - {"epoch": 294, "train_loss": "2.86", "train_ntokens": "8", "train_nsentences": "8", "train_temp": "0.1", "train_code_ppl": "16.663", "train_loss_code_pen": "0.451", "train_loss_smoothness": "1.681", "train_loss_dense_g": "3.395", "train_lm_score_sum": 0.0, "train_num_pred_chars": 0.0, "train_loss_grad_pen": "0.104", "train_loss_dense_d": "0.045", "train_loss_token_d": "0.043", "train_wps": "92.9", "train_ups": "11.62", "train_wpb": "8", "train_bsz": "8", "train_num_updates": "135828", "train_lr_discriminator": "0.0005", "train_lr_generator": "0.0004", "train_gnorm": "23.148", "train_clip": "81.2", "train_train_wall": "38", "train_gb_free": "9.9", "train_wall": "11505"}

```

loss cannot converge, very unstable

The result of the verification is shown below

![timit_matched](https://user-images.githubusercontent.com/48873278/131878634-4b0974e3-2dd1-44a9-8ecb-97211d51a9eb.png)

<br/>

The reason I can think of may be that the batch_size setting is too small, but when I increase the batch_size, the above problems 1, 2 and 3 will appear. I don’t know if it is a problem with my setting, how can I improve it to get An experimental result as credible as in the paper？

<br/>

If anyone can help me, I would be very grateful.

**Comment by XR1988** [comment]
我也是，我这边的loos和uer在开始训练的几分钟内就不再下降了，loss卡在36，uer卡在90。
