### ISSUE TITLE
"Finetuning RoBERTa on GLUE tasks" seems outdated

### ISSUE THREAD

**Issue by chengrunyang** [pytorch/fairseq#3840]
Hi, the first step of "Finetuning RoBERTa on GLUE tasks" at https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.glue.md seems outdated.

When I run `python download_glue_data.py --data_dir glue_data --tasks all`, after changing `download_and_extract()` to

```
def download_and_extract(task, data_dir):
    print("Downloading and extracting %s..." % task)
    data_file = "%s.zip" % task
    url = TASK2PATH[task]
    r = requests.get(url)
    with open(data_file, 'wb') as outfile:
        outfile.write(r.content)
    with zipfile.ZipFile(data_file) as zip_ref:
        zip_ref.extractall(data_dir)
    os.remove(data_file)
    print("\tCompleted!")
```

to fix a `urllib.error.HTTPError: HTTP Error 403: Forbidden` error, I then get the following error:

```
Downloading and extracting CoLA...
Traceback (most recent call last):
  File "download_glue_data.py", line 146, in <module>
    sys.exit(main(sys.argv[1:]))
  File "download_glue_data.py", line 142, in main
    download_and_extract(task, args.data_dir)
  File "download_glue_data.py", line 53, in download_and_extract
    with zipfile.ZipFile(data_file) as zip_ref:
  File "/home/anaconda3/lib/python3.8/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "/home/anaconda3/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

Looks like it's an issue with the urls in the `TASK2PATH` dictionary, but I do not have enough expertise to fix it. Could someone help take a look? Thanks!

**Comment by chengrunyang** [comment]
Update: problem solved. To everyone with the same issue: please try https://github.com/nyu-mll/GLUE-baselines#downloading-glue.

**Comment by daskol** [comment]
Despite the fact the fact that link provided by @chengrunyang allows to download GLUE datasets, the issue is not solve. Download links are still forbidden.
```
$ python download_glue_data.py --data_dir glue --tasks all
Downloading and extracting CoLA...
Traceback (most recent call last):

    ...................................

  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```
