### ISSUE TITLE
Which encoder should I specify?

### ISSUE THREAD

**Issue by chengrunyang** [pytorch/fairseq#3844]
Hi! I got some errors when running Step 3 of the "Finetuning RoBERTa on GLUE tasks" tutorial at https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.glue.md to Fine-tuning on the GLUE task.

The error I got when running the command `ROBERTA_PATH=</path/to/roberta/model.pt>; CUDA_VISIBLE_DEVICES=0 fairseq-hydra-train --config-dir examples/roberta/config/finetuning --config-name cola task.data=/home/craig/glue/fairseq/CoLA-bin checkpoint.restore_file=$ROBERTA_PATH` is:

```
[2021-09-04 23:17:44,541][fairseq_cli.train][INFO] - {'_name': None, 'common': {'_name': None, 'no_progress_bar': False, 'log_interval': 200, 'log_format': 'json', 'log_file': None, 'tensorboard_logdir': None, 'wandb_project': None, 'azureml_logging': False, 'seed': 1, 'cpu': False, 'tpu': False, 'bf16': False, 'memory_efficient_bf16': False, 'fp16': True, 'memory_efficient_fp16': False, 'fp16_no_flatten_grads': False, 'fp16_init_scale': 4, 'fp16_scale_window': 128, 'fp16_scale_tolerance': 0.0, 'on_cpu_convert_precision': False, 'min_loss_scale': 0.0001, 'threshold_loss_scale': 1.0, 'amp': False, 'amp_batch_retries': 2, 'amp_init_scale': 128, 'amp_scale_window': None, 'user_dir': None, 'empty_cache_freq': 0, 'all_gather_list_size': 16384, 'model_parallel_size': 1, 'quantization_config_path': None, 'profile': False, 'reset_logging': False, 'suppress_crashes': False, 'use_plasma_view': False, 'plasma_path': '/tmp/plasma'}, 'common_eval': {'_name': None, 'path': None, 'post_process': None, 'quiet': False, 'model_overrides': '{}', 'results_path': None}, 'distributed_training': {'_name': None, 'distributed_world_size': 1, 'distributed_num_procs': 1, 'distributed_rank': 0, 'distributed_backend': 'nccl', 'distributed_init_method': None, 'distributed_port': -1, 'device_id': 0, 'distributed_no_spawn': False, 'ddp_backend': 'pytorch_ddp', 'ddp_comm_hook': 'none', 'bucket_cap_mb': 25, 'fix_batches_to_gpus': False, 'find_unused_parameters': True, 'fast_stat_sync': False, 'heartbeat_timeout': -1, 'broadcast_buffers': False, 'slowmo_momentum': None, 'slowmo_algorithm': 'LocalSGD', 'localsgd_frequency': 3, 'nprocs_per_node': 1, 'pipeline_model_parallel': False, 'pipeline_balance': None, 'pipeline_devices': None, 'pipeline_chunks': 0, 'pipeline_encoder_balance': None, 'pipeline_encoder_devices': None, 'pipeline_decoder_balance': None, 'pipeline_decoder_devices': None, 'pipeline_checkpoint': 'never', 'zero_sharding': 'none', 'fp16': True, 'memory_efficient_fp16': False, 'tpu': False, 'no_reshard_after_forward': False, 'fp32_reduce_scatter': False, 'cpu_offload': False, 'use_sharded_state': False}, 'dataset': {'_name': None, 'num_workers': 1, 'skip_invalid_size_inputs_valid_test': False, 'max_tokens': 4400, 'batch_size': 16, 'required_batch_size_multiple': 1, 'required_seq_len_multiple': 1, 'dataset_impl': None, 'data_buffer_size': 10, 'train_subset': 'train', 'valid_subset': 'valid', 'combine_valid_subsets': None, 'ignore_unused_valid_subsets': False, 'validate_interval': 1, 'validate_interval_updates': 0, 'validate_after_updates': 0, 'fixed_validation_seed': None, 'disable_validation': False, 'max_tokens_valid': 4400, 'batch_size_valid': 16, 'max_valid_steps': None, 'curriculum': 0, 'gen_subset': 'test', 'num_shards': 1, 'shard_id': 0}, 'optimization': {'_name': None, 'max_epoch': 10, 'max_update': 5336, 'stop_time_hours': 0.0, 'clip_norm': 0.0, 'sentence_avg': False, 'update_freq': [1], 'lr': [1e-05], 'stop_min_lr': -1.0, 'use_bmuf': False}, 'checkpoint': {'_name': None, 'save_dir': 'checkpoints', 'restore_file': '/home/craig/glue/roberta.large/model.pt', 'finetune_from_model': None, 'reset_dataloader': True, 'reset_lr_scheduler': False, 'reset_meters': True, 'reset_optimizer': True, 'optimizer_overrides': '{}', 'save_interval': 1, 'save_interval_updates': 0, 'keep_interval_updates': -1, 'keep_interval_updates_pattern': -1, 'keep_last_epochs': -1, 'keep_best_checkpoints': -1, 'no_save': False, 'no_epoch_checkpoints': True, 'no_last_checkpoints': False, 'no_save_optimizer_state': False, 'best_checkpoint_metric': 'accuracy', 'maximize_best_checkpoint_metric': True, 'patience': -1, 'checkpoint_suffix': '', 'checkpoint_shard_count': 1, 'load_checkpoint_on_all_dp_ranks': False, 'write_checkpoints_asynchronously': False, 'model_parallel_size': 1}, 'bmuf': {'_name': None, 'block_lr': 1.0, 'block_momentum': 0.875, 'global_sync_iter': 50, 'warmup_iterations': 500, 'use_nbm': False, 'average_sync': False, 'distributed_world_size': 1}, 'generation': {'_name': None, 'beam': 5, 'nbest': 1, 'max_len_a': 0.0, 'max_len_b': 200, 'min_len': 1, 'match_source_len': False, 'unnormalized': False, 'no_early_stop': False, 'no_beamable_mm': False, 'lenpen': 1.0, 'unkpen': 0.0, 'replace_unk': None, 'sacrebleu': False, 'score_reference': False, 'prefix_size': 0, 'no_repeat_ngram_size': 0, 'sampling': False, 'sampling_topk': -1, 'sampling_topp': -1.0, 'constraints': None, 'temperature': 1.0, 'diverse_beam_groups': -1, 'diverse_beam_strength': 0.5, 'diversity_rate': -1.0, 'print_alignment': None, 'print_step': False, 'lm_path': None, 'lm_weight': 0.0, 'iter_decode_eos_penalty': 0.0, 'iter_decode_max_iter': 10, 'iter_decode_force_max_iter': False, 'iter_decode_with_beam': 1, 'iter_decode_with_external_reranker': False, 'retain_iter_history': False, 'retain_dropout': False, 'retain_dropout_modules': None, 'decoding_format': None, 'no_seed_provided': False}, 'eval_lm': {'_name': None, 'output_word_probs': False, 'output_word_stats': False, 'context_window': 0, 'softmax_batch': 9223372036854775807}, 'interactive': {'_name': None, 'buffer_size': 0, 'input': '-'}, 'model': {'_name': 'roberta', 'dropout': 0.1, 'attention_dropout': 0.1}, 'task': {'_name': 'sentence_prediction', 'data': '/home/craig/glue/fairseq/CoLA-bin', 'num_classes': 2, 'init_token': 0, 'separator_token': 2, 'no_shuffle': False, 'shorten_method': 'none', 'shorten_data_split_list': '', 'add_prev_output_tokens': False, 'max_positions': 512, 'regression_target': False, 'classification_head_name': 'sentence_classification_head', 'seed': 1}, 'criterion': {'_name': 'sentence_prediction', 'classification_head_name': 'sentence_classification_head', 'regression_target': False}, 'optimizer': {'_name': 'adam', 'adam_betas': '(0.9,0.98)', 'adam_eps': 1e-06, 'weight_decay': 0.1, 'use_old_adam': False, 'fp16_adam_stats': False, 'tpu': False, 'lr': [1e-05]}, 'lr_scheduler': {'_name': 'polynomial_decay', 'warmup_updates': 320, 'force_anneal': None, 'end_learning_rate': 0.0, 'power': 1.0, 'total_num_update': 5336, 'lr': [1e-05]}, 'scoring': None, 'bpe': None, 'tokenizer': None, 'ema': {'_name': None, 'store_ema': False, 'ema_decay': 0.9999, 'ema_start_update': 0, 'ema_seed_model': None, 'ema_update_freq': 1, 'ema_fp32': False}, 'job_logging_cfg': {'version': 1, 'formatters': {'simple': {'format': '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'}}, 'handlers': {'console': {'class': 'logging.StreamHandler', 'formatter': 'simple', 'stream': 'ext://sys.stdout'}, 'file': {'class': 'logging.FileHandler', 'formatter': 'simple', 'filename': 'hydra_train.log'}}, 'root': {'level': 'INFO', 'handlers': ['console', 'file']}, 'disable_existing_loggers': False}}
[2021-09-04 23:17:44,600][fairseq.tasks.sentence_prediction][INFO] - [input] dictionary: 50265 types
[2021-09-04 23:17:44,602][fairseq.tasks.sentence_prediction][INFO] - [label] dictionary: 9 types

Traceback (most recent call last):
  File "/home/craig/glue/fairseq/fairseq_cli/hydra_train.py", line 28, in hydra_main
    _hydra_main(cfg)
  File "/home/craig/glue/fairseq/fairseq_cli/hydra_train.py", line 53, in _hydra_main
    distributed_utils.call_main(cfg, pre_main, **kwargs)
  File "/home/craig/glue/fairseq/fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "/home/craig/glue/fairseq/fairseq_cli/train.py", line 97, in main
    model = task.build_model(cfg.model)
  File "/home/craig/glue/fairseq/fairseq/tasks/sentence_prediction.py", line 264, in build_model
    model = models.build_model(cfg, self)
  File "/home/craig/glue/fairseq/fairseq/models/__init__.py", line 107, in build_model
    return model.build_model(cfg, task)
  File "/home/craig/glue/fairseq/fairseq/models/roberta/model.py", line 205, in build_model
    encoder = RobertaEncoder(args, task.source_dictionary)
  File "/home/craig/glue/fairseq/fairseq/models/roberta/model.py", line 448, in __init__
    self.sentence_encoder = self.build_encoder(args, dictionary, embed_tokens)
  File "/home/craig/glue/fairseq/fairseq/models/roberta/model.py", line 465, in build_encoder
    encoder = TransformerEncoder(args, dictionary, embed_tokens)
  File "/home/craig/glue/fairseq/fairseq/models/transformer/transformer_encoder.py", line 333, in __init__
    TransformerConfig.from_namespace(args),
  File "/home/craig/glue/fairseq/fairseq/models/transformer/transformer_config.py", line 292, in from_namespace
    config.encoder = EncDecBaseConfig(**args.encoder)
TypeError: type object argument after ** must be a mapping, not NoneType

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

For reference, the `args` variable in the `config.encoder = EncDecBaseConfig(**args.encoder)` step is
```
{'_name': 'roberta', 'dropout': 0.1, 'attention_dropout': 0.1, 'max_positions': 512, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_dropout': 0.0, 'pooler_dropout': 0.0, 'max_source_positions': 512, 'no_token_positional_embeddings': False, 'encoder_learned_pos': True, 'layernorm_embedding': True, 'no_scale_embedding': True, 'activation_fn': 'gelu', 'encoder_normalize_before': False, 'pooler_activation_fn': 'tanh', 'untie_weights_roberta': False, 'adaptive_input': False, 'encoder_layerdrop': 0.0, 'encoder_layers_to_keep': None, 'quant_noise_pq': 0, 'quant_noise_pq_block_size': 8, 'quant_noise_scalar': 0, 'spectral_norm_classification_head': False}
```
which doesn't have an `encoder` key. 

It looks like I need to have an `encoder` flag in the `fairseq-hydra-train` command. Are there any suggestions on what I should have for this flag? Thanks!

**Comment by Why1005** [comment]
Do you solve this problem ? I meet same bug while pretraining RoBERTa with custom data.

**Comment by chengrunyang** [comment]
@Why1005 Not yet...Please feel free to update this issue in case you find the answer.

**Comment by Why1005** [comment]
You can modify fairseq/fairseq/models/roberta/model.py/base_architecture(args) like this

encoder_config = EncDecBaseConfig()
encoder_config.embed_dim = safe_getattr(args, "encoder_embed_dim", 768)
encoder_config.ffn_embed_dim = safe_getattr(args, "encoder_ffn_embed_dim", 3072)
encoder_config.layers = safe_getattr(args, "encoder_layers", 12)
encoder_config.attention_heads = safe_getattr(args, "encoder_attention_heads", 12)
encoder_config.learned_pos = safe_getattr(args, "encoder_learned_pos", True)
encoder_config.normalize_before = safe_getattr(args, "encoder_normalize_before", False)
encoder_config.layerdrop = safe_getattr(args, "encoder_layerdrop", 0.0)
encoder_config.layers_to_keep = safe_getattr(args, "encoder_layers_to_keep", None)
args.encoder = encoder_config

or use fairseq-train instead of fairseq-hydra-train

**Comment by chengrunyang** [comment]
Thanks @Why1005! I followed this direction to modify `fairseq/fairseq/models/roberta/model.py`, but it looks like there are many arguments I need to add, like `encoder`, `decoder`, `quant_noise`, etc. Would you be able to share a more complete version of your `fairseq/fairseq/models/roberta/model.py`?

**Comment by Why1005** [comment]
def base_architecture(args):
'''
    encoder_config = EncDecBaseConfig()
    encoder_config.embed_dim = safe_getattr(args, "encoder_embed_dim", 768)
    encoder_config.ffn_embed_dim = safe_getattr(args, "encoder_ffn_embed_dim", 3072)
    encoder_config.layers = safe_getattr(args, "encoder_layers", 12)
    encoder_config.attention_heads = safe_getattr(args, "encoder_attention_heads", 12)
    encoder_config.learned_pos = safe_getattr(args, "encoder_learned_pos", True)
    encoder_config.normalize_before = safe_getattr(args, "encoder_normalize_before", False)
    encoder_config.layerdrop = safe_getattr(args, "encoder_layerdrop", 0.0)
    encoder_config.layers_to_keep = safe_getattr(args, "encoder_layers_to_keep", None)
    args.encoder = encoder_config
    '''
    args.encoder_layers = safe_getattr(args, "encoder_layers", 12)
    args.encoder_embed_dim = safe_getattr(args, "encoder_embed_dim", 768)
    args.encoder_ffn_embed_dim = safe_getattr(args, "encoder_ffn_embed_dim", 3072)
    args.encoder_attention_heads = safe_getattr(args, "encoder_attention_heads", 12)

    args.dropout = safe_getattr(args, "dropout", 0.1)
    args.attention_dropout = safe_getattr(args, "attention_dropout", 0.1)
    args.activation_dropout = safe_getattr(args, "activation_dropout", 0.0)
    args.pooler_dropout = safe_getattr(args, "pooler_dropout", 0.0)

    args.max_source_positions = safe_getattr(args, "max_positions", 512)
    args.no_token_positional_embeddings = safe_getattr(
        args, "no_token_positional_embeddings", False
    )

    # BERT has a few structural differences compared to the original Transformer
    args.encoder_learned_pos = safe_getattr(args, "encoder_learned_pos", True)
    args.layernorm_embedding = safe_getattr(args, "layernorm_embedding", True)
    args.no_scale_embedding = safe_getattr(args, "no_scale_embedding", True)
    args.activation_fn = safe_getattr(args, "activation_fn", "gelu")
    args.encoder_normalize_before = safe_getattr(args, "encoder_normalize_before", False)
    args.pooler_activation_fn = safe_getattr(args, "pooler_activation_fn", "tanh")
    args.untie_weights_roberta = safe_getattr(args, "untie_weights_roberta", False)

    # Adaptive input config
    args.adaptive_input = safe_getattr(args, "adaptive_input", False)

    # LayerDrop config
    args.encoder_layerdrop = safe_getattr(args, "encoder_layerdrop", 0.0)
    args.encoder_layers_to_keep = safe_getattr(args, "encoder_layers_to_keep", None)

    # Quantization noise config
    '''
    quant_noise = QuantNoiseConfig()
    quant_noise.pq = safe_getattr(args, "quant_noise_pq", 0)
    quant_noise.pq_block_size = safe_getattr(args, "quant_noise_pq_block_size", 8)
    quant_noise.scalar = safe_getattr(args, "quant_noise_scalar", 0)
    args.quant_noise = quant_noise
    '''

    args.quant_noise_pq = safe_getattr(args, "quant_noise_pq", 0)
    args.quant_noise_pq_block_size = safe_getattr(args, "quant_noise_pq_block_size", 8)
    args.quant_noise_scalar = safe_getattr(args, "quant_noise_scalar", 0)

    # R4F config
    args.spectral_norm_classification_head = safe_getattr(
        args, "spectral_norm_classification_head", False
    )


** I advise that you can use fairseq-train and manually add param with cmd tools, if you use fairseq-hydra-train, except for model.py, you need to make more debugs ...

**Comment by chengrunyang** [comment]
@Why1005 Thanks! I'll try `fairseq-train`. Are you using the above `def base_architecture(args):` for `fairseq-train` or `fairseq-hydra-train`?

Alternatively, you can try `huggingface` for GLUE classification: a tutorial is at https://github.com/huggingface/transformers/tree/master/examples/pytorch/text-classification, and I verified that it works on a Ubuntu machine with NVIDIA 3090 GPUs.

**Comment by Why1005** [comment]
I use these on fairseq-train, you can delete ''' ... ''' part ,  then make some debugs... to start with fairseq-hydra-train.

**Comment by kere-nel** [comment]
Encountered the same error and this [PR](https://github.com/pytorch/fairseq/pull/3953) fixed it for me.

**Comment by chengrunyang** [comment]
Thanks @Lynx1820 ! I just double checked that this issue has been fixed in Commit c5ff181125c7e6126b49a85e5ebdd5f5b6a07914.
