### ISSUE TITLE
Wikitext language model training is broken

### ISSUE THREAD

**Issue by RuABraun** [pytorch/fairseq#3854]
## 🐛 Bug

Executed the commands described [here](https://github.com/pytorch/fairseq/tree/master/examples/language_model) to train a LM does not work.

### To Reproduce

1. Do preprocessing
2. Call
```
fairseq-train --task language_modeling wikidata-bin --save-dir wikimodel --arch transformer_lm --share-decoder-input-output-embed --dropout 0.1 --optimizer adam --adam-betas '(0.9, 0.98)' --weight-decay 0.01 --clip-norm 0.0 --lr 0.0005 --lr-scheduler inverse_sqrt --warmup-updates 4000 --warmup-init-lr 1e-07 --tokens-per-sample 512 --sample-break-mode none --max-tokens 2048 --update-freq 32 --fp16 --max-update 50000
```
Get error
```
Traceback (most recent call last):
  File "/idiap/temp/rbraun/programs/anaconda3/envs/speech/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/remote/idiap.svm/temp.speech01/rbraun/code/fairseq/fairseq_cli/train.py", line 496, in cli_main
    cfg = convert_namespace_to_omegaconf(args)
  File "/remote/idiap.svm/temp.speech01/rbraun/code/fairseq/fairseq/dataclass/utils.py", line 389, in convert_namespace_to_omegaconf
    composed_cfg = compose("config", overrides=overrides, strict=False)
  File "/idiap/temp/rbraun/programs/anaconda3/envs/speech/lib/python3.8/site-packages/hydra/experimental/compose.py", line 31, in compose
    cfg = gh.hydra.compose_config(
  File "/idiap/temp/rbraun/programs/anaconda3/envs/speech/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 507, in compose_config
    cfg = self.config_loader.load_configuration(
  File "/idiap/temp/rbraun/programs/anaconda3/envs/speech/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 151, in load_configuration
    return self._load_configuration(
  File "/idiap/temp/rbraun/programs/anaconda3/envs/speech/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 256, in _load_configuration
    cfg = self._merge_defaults_into_config(
  File "/idiap/temp/rbraun/programs/anaconda3/envs/speech/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 805, in _merge_defaults_into_config
    hydra_cfg = merge_defaults_list_into_config(hydra_cfg, user_list)
  File "/idiap/temp/rbraun/programs/anaconda3/envs/speech/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 787, in merge_defaults_list_into_config
    merged_cfg = self._merge_config(
  File "/idiap/temp/rbraun/programs/anaconda3/envs/speech/lib/python3.8/site-packages/hydra/_internal/config_loader_impl.py", line 704, in _merge_config
    raise MissingConfigException(msg, new_cfg)
hydra.errors.MissingConfigException: Could not load _self_
```
### Environment

 - fairseq Version (e.g., 1.0 or master): master, commit 50b65368639ac25663764e1d4b3cf46b821975ec
 - PyTorch Version (e.g., 1.0): 1.8.0
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source): `python -m pip install -e`
 - Python version: 3.8.5
 - CUDA/cuDNN version: 11.1
 - GPU models and configuration: 1080ti, ampere

**Comment by RuABraun** [comment]
Don't know what happened. While testing while an editable install might have been the problem the issue was resolved. tl;dr reinstall fixed it.
