### ISSUE TITLE
Textless NLP. Missed code_dict data

### ISSUE THREAD

**Issue by patkinm** [pytorch/fairseq#3870]
## 🐛 Bug

Missed code_dict data for fairseq/examples/textless_nlp/gslm/unit2speech/tacotron2/utils.py 

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd 
!PYTHONPATH=. \
python /home/ubuntu/fairseq/examples/textless_nlp/gslm/tools/resynthesize_speech.py\
--feature_type hubert     \
--acoustic_model_path /home/ubuntu/hubert_base_ls960.pt\
--layer 12     \
--kmeans_model_path /home/ubuntu/km.bin  \
--tts_model_path /home/ubuntu/tts_checkpoint_best.pt    \
--waveglow_path  /home/ubuntu/waveglow_256channels_new.pt \
--max_decoder_steps 2000

2. See error
[2021-09-12 12:18:20,486] [INFO]: Namespace(acoustic_model_path='/home/ubuntu/hubert_base_ls960.pt', denoiser_strength=0.1, feature_type='hubert', kmeans_model_path='/home/ubuntu/km.bin', layer=12, max_decoder_steps=2000, tts_model_path='/home/ubuntu/tts_checkpoint_best.pt', waveglow_path='/home/ubuntu/waveglow_256channels_new.pt')
[2021-09-12 12:18:20,486] [INFO]: Loading acoustic model from /home/ubuntu/tts_checkpoint_best.pt...
[2021-09-12 12:18:25,261] [INFO]: current directory is /home/ubuntu/fairseq
[2021-09-12 12:18:25,262] [INFO]: HubertPretrainingTask Config {'_name': 'hubert_pretraining', 'data': '/checkpoint/wnhsu/data/librispeech/960h/iter/250K_50hz_km100_mp0_65_v2', 'fine_tuning': False, 'labels': ['layer6.km500'], 'label_dir': None, 'label_rate': 50, 'sample_rate': 16000, 'normalize': False, 'enable_padding': False, 'max_keep_size': None, 'max_sample_size': 250000, 'min_sample_size': 32000, 'single_target': False, 'random_crop': True, 'pad_audio': False}
[2021-09-12 12:18:25,275] [INFO]: HubertModel Config: {'_name': 'hubert', 'label_rate': 50, 'extractor_mode': default, 'encoder_layers': 12, 'encoder_embed_dim': 768, 'encoder_ffn_embed_dim': 3072, 'encoder_attention_heads': 12, 'activation_fn': gelu, 'dropout': 0.1, 'attention_dropout': 0.1, 'activation_dropout': 0.0, 'encoder_layerdrop': 0.05, 'dropout_input': 0.1, 'dropout_features': 0.1, 'final_dim': 256, 'untie_final_proj': False, 'layer_norm_first': False, 'conv_feature_layers': '[(512,10,5)] + [(512,3,2)] * 4 + [(512,2,2)] * 2', 'conv_bias': False, 'logit_temp': 0.1, 'target_glu': False, 'feature_grad_mult': 0.1, 'mask_length': 10, 'mask_prob': 0.8, 'mask_selection': static, 'mask_other': 0.0, 'no_mask_overlap': False, 'mask_min_space': 1, 'mask_channel_length': 10, 'mask_channel_prob': 0.0, 'mask_channel_selection': static, 'mask_channel_other': 0.0, 'no_mask_channel_overlap': False, 'mask_channel_min_space': 1, 'conv_pos': 128, 'conv_pos_groups': 16, 'latent_temp': [2.0, 0.5, 0.999995], 'skip_masked': False, 'skip_nomask': False}
[2021-09-12 12:18:27,194] [WARNING]: ===Jit: state["model"] does not contain key "_metadata"=====
[2021-09-12 12:18:27,194] [WARNING]: ===Jit: we will be filling in with current model's meta-data instead.
[2021-09-12 12:18:31,669] [INFO]: Loading K-means model from /home/ubuntu/km.bin ...
/home/ubuntu/miniconda3/envs/fairseq/lib/python3.7/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator MiniBatchKMeans from version 0.24.0 when using version 0.24.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
[2021-09-12 12:18:31,670] [INFO]: Loading TTS model from /home/ubuntu/tts_checkpoint_best.pt...
[2021-09-12 12:18:32,221] [INFO]: Loading Waveglow model from /home/ubuntu/waveglow_256channels_new.pt...
Traceback (most recent call last):
  File "/home/ubuntu/fairseq/examples/textless_nlp/gslm/tools/resynthesize_speech.py", line 138, in <module>
    main(args, logger)
  File "/home/ubuntu/fairseq/examples/textless_nlp/gslm/tools/resynthesize_speech.py", line 100, in main
    tts_dataset = TacotronInputDataset(hparams)
  File "/home/ubuntu/fairseq/examples/textless_nlp/gslm/unit2speech/tts_data.py", line 24, in __init__
    self.code_dict = load_code_dict(hparams.code_dict)
  File "/home/ubuntu/fairseq/examples/textless_nlp/gslm/unit2speech/tacotron2/utils.py", line 65, in load_code_dict
    with open(path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/checkpoint/kushall/experiments/speechbot/tts/filelists/cpc_85_clustering-LL6k_gru2_kmeans100/code_dict_cpc_km100'

I've tried to use all unit to speech HuBERT models:

HuBERT Base + KM50
HuBERT Base + KM100 
HuBERT Base + KM200
HuBERT Base + KM500

Same issue...

Maybe I'm doing something wrong. 

Thank you,
Michael

**Comment by ahazeemi** [comment]
I am facing the same issue.

**Comment by bhawna-gupta** [comment]
I am also facing the same issue with all Models(Hubert,CPC,Wav2vec)

**Comment by hosytuyen** [comment]
I am also facing the same problem, is there any solution for this? Tks so much

**Comment by hikushalhere** [comment]
This can be fixed by accepting a `code_dict` file in the resynthesis tool. The `code_dict` file is a text file containing the codes, one per line, e.g., for systems using k-means with 50 units the file contains 1 through 50. I will submit a PR.
Cc: @wnhsu

**Comment by bhawna-gupta** [comment]
Can anyone please tell what can be the valid value of layer here ?
!PYTHONPATH=.
python /home/ubuntu/fairseq/examples/textless_nlp/gslm/tools/resynthesize_speech.py
--feature_type hubert
--acoustic_model_path /home/ubuntu/hubert_base_ls960.pt
--layer 12
--kmeans_model_path /home/ubuntu/km.bin
--tts_model_path /home/ubuntu/tts_checkpoint_best.pt
--waveglow_path /home/ubuntu/waveglow_256channels_new.pt
--max_decoder_steps 2000

Default was -1  and it was giving error.

**Comment by hikushalhere** [comment]
If you're using HuBERT-Base then the layers can be 0 through 11.

**Comment by bhawna-gupta** [comment]
Hi Kushal,
I used your code and made a dict containing 1 to 50  one per line with layer =10 ,but getting this error.
Could you please help?


Traceback (most recent call last):
File "/tmp/fairseq/examples/textless_nlp/gslm/tools/resynthesize_speech.py", line 132, in <module>
main(args, logger)
File "/tmp/fairseq/examples/textless_nlp/gslm/tools/resynthesize_speech.py", line 116, in main
mel, aud, aud_dn, has_eos = synthesize_audio(
File "/tmp/fairseq/examples/textless_nlp/gslm/unit2speech/utils.py", line 32, in synthesize_audio
_, mel, _, ali, has_eos = model.inference(inp, lab, ret_has_eos=True)
File "/tmp/fairseq/examples/textless_nlp/gslm/unit2speech/tacotron2/model.py", line 636, in inference
encoder_outputs = self.encoder.inference(embedded_inputs)
File "/tmp/fairseq/examples/textless_nlp/gslm/unit2speech/tacotron2/model.py", line 200, in inference
outputs, _ = self.lstm(x)
File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
return forward_call(*input, **kwargs)
File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 679, in forward
result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

**Comment by bhawna-gupta** [comment]
I am still getting error even after using author's merged code. Did anyone else face same issue ?

**Comment by ahazeemi** [comment]
> I am still getting error even after using author's merged code. Did anyone else face same issue ?

@bhawna-gupta I am getting the same error: CUDNN_STATUS_EXECUTION_FAILED. 

I ran the following command:
```
python /content/fairseq/examples/textless_nlp/gslm/tools/resynthesize_speech.py \
    --feature_type hubert \
    --acoustic_model_path /content/fairseq/hubert_base_ls960.pt \
    --layer 6 \
    --kmeans_model_path /content/fairseq/km.bin \
    --tts_model_path /content/fairseq/tts_checkpoint_best.pt \
    --waveglow_path  /content/fairseq/waveglow_256channels_new.pt\
    --code_dict_path /content/code_dict \
    --max_decoder_steps 2000
```

Disabling cudnn (`torch.backends.cudnn.enabled = False`) reveals another error:

```
  File "/content/fairseq/examples/textless_nlp/gslm/tools/resynthesize_speech.py", line 133, in <module>
    main(args, logger)
  File "/content/fairseq/examples/textless_nlp/gslm/tools/resynthesize_speech.py", line 113, in main
    quantized_units = kmeans_model.predict(feats)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/cluster/_kmeans.py", line 1765, in predict
    X = self._check_test_data(X)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/cluster/_kmeans.py", line 811, in _check_test_data
    X = check_array(X, accept_sparse='csr', dtype=FLOAT_DTYPES)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py", line 578, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py", line 60, in _assert_all_finite
    msg_dtype if msg_dtype is not None else X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').
```

I tried with the wav2vec model too. Although it doesn't throw any error, the output wav file doesn't contain any audio. 

@hikushalhere Can you please help us here. Thanks!

**Comment by bradgrimm** [comment]
I was running into similar problems. When I dug in a little deeper I noticed that the torch file (for the 500 kmeans model) has `n_symbols=494` not 500.

For me the fix was to generate a code_dict with 494 symbols.
```
for i in range(1, 494+1):
    print(i)
```

To check the torch file you are working with:
```
model_dict = torch.load('/mnt/large/data/pretrained/hubert_base_km500.pt')
model_dict['hparams'].n_symbols
```

**Comment by osyvokon** [comment]
Sorry to hijack the thread, but did anyone succeed in speech resynthesis? No matter what I try, I keep getting gibberish 😿

Here are more details: https://github.com/pytorch/fairseq/issues/3970 Any help appreciated!

**Comment by bradgrimm** [comment]
@asivokon It was just gibberish for me too. I've only tried the Hubert 500 km model, but it definitely didn't seem to be working.

**Comment by miguelamavel** [comment]
Feels to me that those codes in the missing code_dict should be more than just a 1 to n list, but rather something more meaningful. I too am only getting gibberish.
