### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by helloeboy** [pytorch/fairseq#465]
Hi All,
I got a trouble when using lstm model (There is no problem with fconv and transformer).
CUDA : 10.0
GPU : RTX 2080Ti
And there is nothing wrong with my old machine (1080/cuda 9.0)
What might be wrong ? 
Thank you!!

```
Traceback (most recent call last):
  File "train.py", line 402, in <module>
    main(args)
  File "train.py", line 58, in main
    trainer = Trainer(args, task, model, criterion, dummy_batch, oom_batch)
  File "/workspace/fairseq/fairseq/trainer.py", line 44, in __init__
    self._model = self._model.cuda()
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 260, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 117, in _apply
    self.flatten_parameters()
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 113, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
```

**Comment by igormq** [comment]
How did you solve this?
