### ISSUE TITLE
view() does not accept tensor aruments

### ISSUE THREAD

**Issue by arendu** [pytorch/fairseq#507]
In this line:
https://github.com/pytorch/fairseq/blob/9998bbfab7267d0bc82c8eb10fb2d9310139c689/fairseq/modules/sinusoidal_positional_embedding.py#L85

I encounter an issue:
```
Traceback (most recent call last):
  File "/export/b19/arenduc1/fairseq/train.py", line 411, in <module>
    cli_main()
  File "/export/b19/arenduc1/fairseq/train.py", line 407, in cli_main
    main(args)
  File "/export/b19/arenduc1/fairseq/train.py", line 94, in main
    trainer.dummy_train_step([dummy_batch])
  File "/export/b19/arenduc1/fairseq/fairseq/trainer.py", line 352, in dummy_train_step
    self.train_step(dummy_batch, dummy_batch=True)
  File "/export/b19/arenduc1/fairseq/fairseq/trainer.py", line 203, in train_step
    ignore_grad
  File "/export/b19/arenduc1/fairseq/fairseq/tasks/fairseq_task.py", line 205, in train_step
    loss, sample_size, logging_output = criterion(model, sample)
  File "/home/arenduc1/anaconda3/envs/fairseqenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/export/b19/arenduc1/fairseq/fairseq/criterions/label_smoothed_cross_entropy.py", line 38, in forward
    net_output = model(**sample['net_input'])
  File "/home/arenduc1/anaconda3/envs/fairseqenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/export/b19/arenduc1/fairseq/fairseq/models/fairseq_model.py", line 178, in forward
    encoder_out = self.encoder(src_tokens, src_lengths)
  File "/home/arenduc1/anaconda3/envs/fairseqenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/export/b19/arenduc1/fairseq/fairseq/models/transformer.py", line 320, in forward
    x = self.embed_scale * self.embed_tokens(src_tokens)
  File "/home/arenduc1/anaconda3/envs/fairseqenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/export/b19/arenduc1/fairseq/fairseq/modules/sinusoidal_positional_embedding.py", line 87, in forward
    return self.weights.index_select(0, positions.view(-1)).view(bsz, seq_len, -1)
TypeError: view(): argument 'size' (position 1) must be tuple of ints, not Tenso
```

It can be fixed by adding `.item()` to the arguments, i.e.
```
return self.weights.index_select(0, positions.view(-1)).view(bsz.item(), seq_len.item(), -1).detach()
```

**Comment by arendu** [comment]
Missed the last line of the error msg:
```
TypeError: view(): argument 'size' (position 1) must be tuple of ints, not Tensor
```

**Comment by myleott** [comment]
I haven't observed this issue, but I suspect it's something to do with the `torch.onnx.operators.shape_as_tensor` call in there. What version of pytorch and fairseq are you using?

**Comment by arendu** [comment]
I'm using `0.4.1` pytorch. I am working on [this](https://github.com/arendu/fairseq/tree/mult-src-feats) fork of fairseq ( I recently merged with master branch with pytorch/fairseq official repo)

**Comment by myleott** [comment]
Ah, we only support PyTorch >= 1.0 now. Most things probably still work on 0.4.1, but we won't be supporting it going forward :/
