### ISSUE TITLE
nmt_scaling training fails after "overflow detected, setting loss scale to: 0.0001220703125"

### ISSUE THREAD

**Issue by asispatra** [pytorch/fairseq#512]
nmt_scaling training fails after "overflow detected, setting loss scale to: 0.0001220703125". 
You can find the error logs below:
```
| epoch 027 | loss 6.343 | nll_loss 4.984 | ppl 31.65 | wps 164346 | ups 0.4 | wpb 364096 | bsz 11907 | num_updates 10198 | lr 0.000626286 | gnorm 0.390 | clip 0% | oom 0 | loss_scale 0.500 | wall 23080 | train_wall 21383
| epoch 027 | valid on 'valid' subset | valid_loss 8.30118 | valid_nll_loss 7.15366 | valid_ppl 142.39 | num_updates 10198 | best 4.46376
| WARNING: overflow detected, setting loss scale to: 0.25
| WARNING: overflow detected, setting loss scale to: 0.125
| WARNING: overflow detected, setting loss scale to: 0.0625
| WARNING: overflow detected, setting loss scale to: 0.03125
| WARNING: overflow detected, setting loss scale to: 0.015625
| WARNING: overflow detected, setting loss scale to: 0.0078125
| WARNING: overflow detected, setting loss scale to: 0.00390625
| WARNING: overflow detected, setting loss scale to: 0.001953125
| WARNING: overflow detected, setting loss scale to: 0.0009765625
| WARNING: overflow detected, setting loss scale to: 0.00048828125
| WARNING: overflow detected, setting loss scale to: 0.000244140625
| WARNING: overflow detected, setting loss scale to: 0.0001220703125
Traceback (most recent call last):
  File "train.py", line 392, in <module>
Traceback (most recent call last):
  File "train.py", line 392, in <module>
Traceback (most recent call last):
  File "train.py", line 392, in <module>
    distributed_main(args.device_id, args)
  File "train.py", line 380, in distributed_main
    distributed_main(args.device_id, args)
    main(args, init_distributed=True)
  File "train.py", line 380, in distributed_main
  File "train.py", line 106, in main
    train(args, trainer, task, epoch_itr)
  File "train.py", line 141, in train
    distributed_main(args.device_id, args)
  File "train.py", line 380, in distributed_main
    main(args, init_distributed=True)
  File "train.py", line 106, in main
    log_output = trainer.train_step(samples)
  File "/home/pytorch/test/fairseq/fairseq/trainer.py", line 248, in train_step
    train(args, trainer, task, epoch_itr)
  File "train.py", line 141, in train
    main(args, init_distributed=True)
  File "train.py", line 106, in main
    log_output = trainer.train_step(samples)
  File "/home/pytorch/test/fairseq/fairseq/trainer.py", line 248, in train_step
    grad_norm = self.optimizer.clip_grad_norm(self.args.clip_norm)
  File "/home/pytorch/test/fairseq/fairseq/optim/fp16_optimizer.py", line 178, in clip_grad_norm
    train(args, trainer, task, epoch_itr)
  File "train.py", line 141, in train
    ).format(self.args.min_loss_scale))
    grad_norm = self.optimizer.clip_grad_norm(self.args.clip_norm)
  File "/home/pytorch/test/fairseq/fairseq/optim/fp16_optimizer.py", line 178, in clip_grad_norm
    log_output = trainer.train_step(samples)
  File "/home/pytorch/test/fairseq/fairseq/trainer.py", line 248, in train_step
FloatingPointError: Minimum loss scale reached (0.0001). Your loss is probably exploding. Try lowering the learning rate, using gradient clipping or increasing the batch size.
    ).format(self.args.min_loss_scale))
FloatingPointError: Minimum loss scale reached (0.0001). Your loss is probably exploding. Try lowering the learning rate, using gradient clipping or increasing the batch size.
    grad_norm = self.optimizer.clip_grad_norm(self.args.clip_norm)
  File "/home/pytorch/test/fairseq/fairseq/optim/fp16_optimizer.py", line 178, in clip_grad_norm
    ).format(self.args.min_loss_scale))
FloatingPointError: Minimum loss scale reached (0.0001). Your loss is probably exploding. Try lowering the learning rate, using gradient clipping or increasing the batch size.
Traceback (most recent call last):
  File "train.py", line 392, in <module>
    distributed_main(args.device_id, args)
  File "train.py", line 380, in distributed_main
    main(args, init_distributed=True)
  File "train.py", line 106, in main
    train(args, trainer, task, epoch_itr)
  File "train.py", line 141, in train
    log_output = trainer.train_step(samples)
  File "/home/pytorch/test/fairseq/fairseq/trainer.py", line 248, in train_step
    grad_norm = self.optimizer.clip_grad_norm(self.args.clip_norm)
  File "/home/pytorch/test/fairseq/fairseq/optim/fp16_optimizer.py", line 178, in clip_grad_norm
    ).format(self.args.min_loss_scale))
FloatingPointError: Minimum loss scale reached (0.0001). Your loss is probably exploding. Try lowering the learning rate, using gradient clipping or increasing the batch size.
```

Please let me know if you required additional info.

**Comment by libeineu** [comment]
Hi, I meet the same problem when I train transformer model within FP16 mode.  It seems like that the valid_ppl explode up to a huge number, the loss scale behave oppositely

**Comment by myleott** [comment]
Probably your batch size is too small or learning rate is too big. Can you share your training command? How many GPUs are you training on?

You can increase the batch size using the `--update-freq` option.

**Comment by myleott** [comment]
Actually this is the same issue as #515. Let's close this and discuss there. The decrease in loss scale is a symptom of the loss exploding.

**Comment by Mr-SR** [comment]
Hi, I meet the same problem when I train transformer model within FP16 mode. How did you finally solve this problem?
