### ISSUE TITLE
Importing fairseq causes joblib to crash

### ISSUE THREAD

**Issue by louismartin** [pytorch/fairseq#517]
I have a weird bug that causes joblib parallel jobs to crash when any of my script imports fairseq.

I have made a minimal repro:

Script `test.py`:
```
import fairseq


def test():
    pass
```

Script `main.py`:
```
from joblib import Parallel, delayed

from test import test


if __name__ == '__main__':
    Parallel(n_jobs=2)([delayed(test)()])
```

Error when running `python main.py`:
```
joblib.externals.loky.process_executor._RemoteTraceback:
'''
Traceback (most recent call last):
  File "/private/home/louismartin/miniconda3/envs/test/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 391, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "/private/home/louismartin/miniconda3/envs/test/lib/python3.7/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/private/home/louismartin/tmp/fairseq_repro/test.py", line 1, in <module>
    import fairseq
  File "/private/home/louismartin/miniconda3/envs/test/lib/python3.7/site-packages/fairseq/__init__.py", line 8, in <module>
    from .multiprocessing_pdb import pdb
  File "/private/home/louismartin/miniconda3/envs/test/lib/python3.7/site-packages/fairseq/multiprocessing_pdb.py", line 14, in <module>
    class MultiprocessingPdb(pdb.Pdb):
  File "/private/home/louismartin/miniconda3/envs/test/lib/python3.7/site-packages/fairseq/multiprocessing_pdb.py", line 20, in MultiprocessingPdb
    _stdin_fd = sys.stdin.fileno()
AttributeError: 'NoneType' object has no attribute 'fileno'
'''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 5, in <module>
    Parallel(n_jobs=2)([delayed(test)()])
  File "/private/home/louismartin/miniconda3/envs/test/lib/python3.7/site-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/private/home/louismartin/miniconda3/envs/test/lib/python3.7/site-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/private/home/louismartin/miniconda3/envs/test/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "/private/home/louismartin/miniconda3/envs/test/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/private/home/louismartin/miniconda3/envs/test/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.
```

This works as soon as we remove the `import fairseq` statement or if we move the import to `main.py`.

Tested in a brand new conda environment:
- python 3.7.2
- fairseq 0.6.1
- joblib 0.13.2

Any idea?

**Comment by myleott** [comment]
MultiprocessingPdb in fairseq is a convenience wrapper around Pdb that works better when using multiprocessing. But we instantiate an instance on import: https://github.com/pytorch/fairseq/blob/master/fairseq/multiprocessing_pdb.py#L39. It should be an easy fix.

**Comment by myleott** [comment]
Can you try patching #516?

**Comment by louismartin** [comment]
I still get the error when using joblib:
```
Traceback (most recent call last):
  File "/private/home/louismartin/miniconda3/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 391, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "/private/home/louismartin/miniconda3/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/private/home/louismartin/tmp/fairseq_repro/test.py", line 1, in <module>
    import fairseq
  File "/private/home/louismartin/dev/ext/fairseq/fairseq/__init__.py", line 16, in <module>
    import fairseq.pdb
  File "/private/home/louismartin/dev/ext/fairseq/fairseq/pdb.py", line 17, in <module>
    _stdin_fd = sys.stdin.fileno()
AttributeError: 'NoneType' object has no attribute 'fileno'
```


I also get an error when running tests with pytest:
```
self = <_pytest.capture.DontReadFromInput object at 0x7f15b757b710>

    def fileno(self):
>       raise UnsupportedOperation("redirected stdin is pseudofile, " "has no fileno()")
E       io.UnsupportedOperation: redirected stdin is pseudofile, has no fileno()

../../miniconda3/lib/python3.6/site-packages/_pytest/capture.py:599: UnsupportedOperation
```

I think that relying on `fileno()` is error prone and should maybe be moved inside the `_cmdloop()` method so that scripts that import fairseq don't crash.

Maybe a simple fix like this could work?  (see PR #553)

**Comment by myleott** [comment]
Unfortunately it doesn't seem to work well with multiprocessing unless this happens before the fork. Can we instead catch the exceptions and ignore them?

**Comment by louismartin** [comment]
Good idea, I edited the PR
