### ISSUE TITLE
'module' object is not callable when running DynamicConv

### ISSUE THREAD

**Issue by gxzks** [pytorch/fairseq#547]
Here is the error log:
Traceback (most recent call last):
  File "~/anaconda2/envs/fairseq/bin/fairseq-train", line 10, in <module>
    sys.exit(cli_main())
  File "~/anaconda2/envs/fairseq/lib/python3.6/site-packages/fairseq_cli/train.py", line 407, in cli_main
    main(args)
  File "~/anaconda2/envs/fairseq/lib/python3.6/site-packages/fairseq_cli/train.py", line 106, in main
    train(args, trainer, task, epoch_itr)
  File "~/anaconda2/envs/fairseq/lib/python3.6/site-packages/fairseq_cli/train.py", line 141, in train
    log_output = trainer.train_step(samples)
  File "~/anaconda2/envs/fairseq/lib/python3.6/site-packages/fairseq/trainer.py", line 196, in train_step
    ignore_grad
  File "~/anaconda2/envs/fairseq/lib/python3.6/site-packages/fairseq/tasks/fairseq_task.py", line 205, in train_step
    loss, sample_size, logging_output = criterion(model, sample)
  File "~/anaconda2/envs/fairseq/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "~/anaconda2/envs/fairseq/lib/python3.6/site-packages/fairseq/criterions/label_smoothed_cross_entropy.py", line 38, in forward
    net_output = model(**sample['net_input'])
  File "~/anaconda2/envs/fairseq/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "~/anaconda2/envs/fairseq/lib/python3.6/site-packages/fairseq/models/fairseq_model.py", line 178, in forward
    encoder_out = self.encoder(src_tokens, src_lengths)
  File "~/anaconda2/envs/fairseq/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "~/anaconda2/envs/fairseq/lib/python3.6/site-packages/fairseq/models/lightconv.py", line 356, in forward
    x = layer(x, encoder_padding_mask)
  File "~/anaconda2/envs/fairseq/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "~/anaconda2/envs/fairseq/lib/python3.6/site-packages/fairseq/models/lightconv.py", line 606, in forward
    x = self.conv(x)
  File "~/anaconda2/envs/fairseq/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "~/anaconda2/envs/fairseq/lib/python3.6/site-packages/fairseq/modules/dynamic_convolution.py", line 97, in forward
    output = self._forward_unfolded(x, incremental_state, query)
  File "~/anaconda2/envs/fairseq/lib/python3.6/site-packages/fairseq/modules/dynamic_convolution.py", line 137, in _forward_unfolded
    x_unfold = unfold1d(x, K, padding_l, 0)
TypeError: 'module' object is not callable

This error sometimes occurs when I train a few updates but sometimes in the very beginning.

**Comment by hanavitor** [comment]
Similar problem, I'm using a 6gb gtx1060, here's the log:

Traceback (most recent call last):
File "train.py", line 411, in <module>
cli_main()
File "train.py", line 407, in cli_main
main(args)
File "train.py", line 106, in main
train(args, trainer, task, epoch_itr)
File "train.py", line 141, in train
log_output = trainer.train_step(samples)
File "/home/user/Documents/fairseq/fairseq/trainer.py", line 196, in train_step
ignore_grad
File "/home/user/Documents/fairseq/fairseq/tasks/fairseq_task.py", line 205, in train_step
loss, sample_size, logging_output = criterion(model, sample)
File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
result = self.forward(*input, **kwargs)
File "/home/user/Documents/fairseq/fairseq/criterions/label_smoothed_cross_entropy.py", line 38, in forward
net_output = model(**sample['net_input'])
File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
result = self.forward(*input, **kwargs)
File "/home/user/Documents/fairseq/fairseq/models/fairseq_model.py", line 178, in forward
encoder_out = self.encoder(src_tokens, src_lengths)
File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
result = self.forward(*input, **kwargs)
File "/home/user/Documents/fairseq/fairseq/models/lightconv.py", line 356, in forward
x = layer(x, encoder_padding_mask)
File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
result = self.forward(*input, **kwargs)
File "/home/user/Documents/fairseq/fairseq/models/lightconv.py", line 606, in forward
x = self.conv(x)
File "/home/user/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
result = self.forward(*input, **kwargs)
File "/home/user/Documents/fairseq/fairseq/modules/dynamic_convolution.py", line 97, in forward
output = self._forward_unfolded(x, incremental_state, query)
File "/home/user/Documents/fairseq/fairseq/modules/dynamic_convolution.py", line 137, in _forward_unfolded
x_unfold = unfold1d(x, K, padding_l, 0)
TypeError: 'module' object is not callable

**Comment by nxphi47** [comment]
the file unfold1d.py and module unfold1d and the function unfold1d() inside it all have the same name `unfold1d `. So you need to go into the code and change to function name to `unfold1d _fn` and change to function used in dynamic_convolution.py to `unfold1d `. Then it should work.

**Comment by gxzks** [comment]
Actually it works!

Thanks, @nxphi47

**Comment by mali-nuist** [comment]
i also encountered this problem... i think you can open this issue currently ...

**Comment by gxzks** [comment]
Just change 

> unfold1d()

 to 

> unfold1d.unfold1d()

 in dynamic_convolution.py
@mali-nuist

**Comment by mali-nuist** [comment]
@gxzks  Thanks ~~~
