### ISSUE TITLE
Nvidia GPU Cloud docker container: cannot train fp16 multi gpus

### ISSUE THREAD

**Issue by nxphi47** [pytorch/fairseq#549]
I trained the lightconv model on 2 GPUs (V100) with docker container from nvidia:

`docker pull nvcr.io/nvidia/pytorch:19.02-py3`

However, I cannot train on it for multi-gpus with fp16 (the logs are below). In fact, I cannot train any multi-gnu setting inside the container.

In addition, I can run multi-gpus with fp16 outside the container using normal conda installation. However, the training time is extremely slow: 150 iterations for 30 minutes, way slower than when I train on 1 GPU inside the container

Please help. Thank you

```
| model lightconv_wmt_en_de, criterion LabelSmoothedCrossEntropyCriterion
| num. model params: 65449984 (num. trained: 65449984)
| training on 2 GPUs
| max tokens per GPU = 8192 and max sentences per GPU = None
| no existing checkpoint found /projects/nmt/train_fairseq_v2/wmt14_en_de/lightconv_wmt_en_de-b8192-gpu2-upfre2-1fp16-id3/checkpoint_last.pt
Unexpected end of /proc/mounts line `overlay / overlay rw,relatime,lowerdir=/var/lib/docker/overlay2/l/E2P56YFQLCHKVHNQKCIUC37HQG:/var/lib/docker/overlay2/l/EAAUN5KRUSXOUXMIVYQH6JXIYE:/var/lib/docker/overlay2/l/R6QLI7RG2Y7SZEPEANLA2SYUAT:/var/lib/docker/overlay2/l/UNX7KEGOOK5ESDM5GX7JABEA7O:/var/lib/docker/overlay2/l/4ZZGVNOB3CZ6UM52TDSMI4VRCK:/var/lib/docker/overlay2/l/EHABKTZDOYP6DJHIIVOBTZWTCU:/var/lib/docker/overlay2/l/6TN47UA6OLSHH7TLZKCIQKTJ5T:/var/lib/docker/overlay2/l/JFDYSXMV2PWL5CRAMAB5W6BAK5:/var/lib/docker/overlay2/l/DV6MGRRAPN57B'
Unexpected end of /proc/mounts line `MOC6LQN64H7D2:/var/lib/docker/overlay2/l/PXSLKB6RZCZDAGVOFJJ4KHJW3E:/var/lib/docker/overlay2/l/U62WFV6HG5MPKGTEKL32ZS7R4M:/var/lib/docker/overlay2/l/5V6UASB3PBD6ABBS5DY3GGVM4I:/var/lib/docker/overlay2/l/MODI26AHNZJS4P42QSTP53HNK5:/var/lib/docker/overlay2/l/BL24EQTAKQQQDXWP727M22VHLC:/var/lib/docker/overlay2/l/ZZD4MNPYH7JWYBYX4NYG3UW2L6:/var/lib/docker/overlay2/l/R624FCC4BODYHWWWYRMPNTXWHH:/var/lib/docker/overlay2/l/VGMLEDC56A44XMVVD3EUAMOUUS:/var/lib/docker/overlay2/l/PBY3XZNGCZXIBH3XU2D52P6OAY:/var/lib/do'
Unexpected end of /proc/mounts line `cker/overlay2/l/MNRKDCVIJ4MQXJKQO6BC4EXDU5:/var/lib/docker/overlay2/l/7B3NMK42XYZ5EDI3LIO5NNF7EC:/var/lib/docker/overlay2/l/ZFE2M6YW2UMHAPXKPXYKNMNOAE:/var/lib/docker/overlay2/l/IYUYWIEZB5EMYCBXPODVK7PQIT:/var/lib/docker/overlay2/l/66H3HZMWZOE6GSLN5UF2QPCGUV:/var/lib/docker/overlay2/l/SAQLI2EHLG2VU3HX2VV3QG5ICQ:/var/lib/docker/overlay2/l/JEWMJ2ALWN4VPOJYCXEDIEZIY5:/var/lib/docker/overlay2/l/DW6M3C6PIGX5U4RZDHT5Z2KPDW:/var/lib/docker/overlay2/l/24LMMQ4G3Z7GERWR6QIT3CYB42:/var/lib/docker/overlay2/l/A3IRKS3OK'
Unexpected end of /proc/mounts line `A5I2N2INORLLLJK4H:/var/lib/docker/overlay2/l/VIUZQGWELFINMY6I4JNQIY3T5D:/var/lib/docker/overlay2/l/D2KWCLRJ4VS3UGLIRV3WF2VO5F:/var/lib/docker/overlay2/l/TZBHNMYMSEHRYUDEZGCTIISXBV:/var/lib/docker/overlay2/l/GWVQGUO3ORWN35YTB3VQYWVYDP:/var/lib/docker/overlay2/l/5ASC6KJHEVXEHGL5J2M56D3F74:/var/lib/docker/overlay2/l/Q6FAI5GAHX5AHZL5UX53HDCUUX:/var/lib/docker/overlay2/l/VXELQ4XLOENQCDCK5CX4IPO5WL:/var/lib/docker/overlay2/l/I6SEZQSZ3EKVJXYU6I3R4YYF3R:/var/lib/docker/overlay2/l/BOSRSFNQISBSKYJ5KHZOZNC6ZS:/var/li'
Unexpected end of /proc/mounts line `b/docker/overlay2/l/RPOAEC2BWBGVHOAS5BCAT2CJVC:/var/lib/docker/overlay2/l/E73WAJZEID4NUWD2LVF7B5FYWA:/var/lib/docker/overlay2/l/OWH4GCEQSUYWEXYYPKNHIK2GV5:/var/lib/docker/overlay2/l/WBPZ5OCYJYY6N7LPPKJTNRQN2Z:/var/lib/docker/overlay2/l/J5PMN7ZRYKNRO2SAPXI74DKVJP:/var/lib/docker/overlay2/l/VGDU5OSG27XOWKG53SHRMOFYBU:/var/lib/docker/overlay2/l/4F64LOLLFAG3XYM32XUVLE27RA:/var/lib/docker/overlay2/l/LBSX74NEML6EWS7OSPGCD4JHRZ:/var/lib/docker/overlay2/l/DAOJ3CGMHHPXGWYQTYWF6M5BDZ:/var/lib/docker/overlay2/l/KTAQZ'
Unexpected end of /proc/mounts line `overlay / overlay rw,relatime,lowerdir=/var/lib/docker/overlay2/l/E2P56YFQLCHKVHNQKCIUC37HQG:/var/lib/docker/overlay2/l/EAAUN5KRUSXOUXMIVYQH6JXIYE:/var/lib/docker/overlay2/l/R6QLI7RG2Y7SZEPEANLA2SYUAT:/var/lib/docker/overlay2/l/UNX7KEGOOK5ESDM5GX7JABEA7O:/var/lib/docker/overlay2/l/4ZZGVNOB3CZ6UM52TDSMI4VRCK:/var/lib/docker/overlay2/l/EHABKTZDOYP6DJHIIVOBTZWTCU:/var/lib/docker/overlay2/l/6TN47UA6OLSHH7TLZKCIQKTJ5T:/var/lib/docker/overlay2/l/JFDYSXMV2PWL5CRAMAB5W6BAK5:/var/lib/docker/overlay2/l/DV6MGRRAPN57B'
Unexpected end of /proc/mounts line `MOC6LQN64H7D2:/var/lib/docker/overlay2/l/PXSLKB6RZCZDAGVOFJJ4KHJW3E:/var/lib/docker/overlay2/l/U62WFV6HG5MPKGTEKL32ZS7R4M:/var/lib/docker/overlay2/l/5V6UASB3PBD6ABBS5DY3GGVM4I:/var/lib/docker/overlay2/l/MODI26AHNZJS4P42QSTP53HNK5:/var/lib/docker/overlay2/l/BL24EQTAKQQQDXWP727M22VHLC:/var/lib/docker/overlay2/l/ZZD4MNPYH7JWYBYX4NYG3UW2L6:/var/lib/docker/overlay2/l/R624FCC4BODYHWWWYRMPNTXWHH:/var/lib/docker/overlay2/l/VGMLEDC56A44XMVVD3EUAMOUUS:/var/lib/docker/overlay2/l/PBY3XZNGCZXIBH3XU2D52P6OAY:/var/lib/do'
Unexpected end of /proc/mounts line `cker/overlay2/l/MNRKDCVIJ4MQXJKQO6BC4EXDU5:/var/lib/docker/overlay2/l/7B3NMK42XYZ5EDI3LIO5NNF7EC:/var/lib/docker/overlay2/l/ZFE2M6YW2UMHAPXKPXYKNMNOAE:/var/lib/docker/overlay2/l/IYUYWIEZB5EMYCBXPODVK7PQIT:/var/lib/docker/overlay2/l/66H3HZMWZOE6GSLN5UF2QPCGUV:/var/lib/docker/overlay2/l/SAQLI2EHLG2VU3HX2VV3QG5ICQ:/var/lib/docker/overlay2/l/JEWMJ2ALWN4VPOJYCXEDIEZIY5:/var/lib/docker/overlay2/l/DW6M3C6PIGX5U4RZDHT5Z2KPDW:/var/lib/docker/overlay2/l/24LMMQ4G3Z7GERWR6QIT3CYB42:/var/lib/docker/overlay2/l/A3IRKS3OK'
Unexpected end of /proc/mounts line `A5I2N2INORLLLJK4H:/var/lib/docker/overlay2/l/VIUZQGWELFINMY6I4JNQIY3T5D:/var/lib/docker/overlay2/l/D2KWCLRJ4VS3UGLIRV3WF2VO5F:/var/lib/docker/overlay2/l/TZBHNMYMSEHRYUDEZGCTIISXBV:/var/lib/docker/overlay2/l/GWVQGUO3ORWN35YTB3VQYWVYDP:/var/lib/docker/overlay2/l/5ASC6KJHEVXEHGL5J2M56D3F74:/var/lib/docker/overlay2/l/Q6FAI5GAHX5AHZL5UX53HDCUUX:/var/lib/docker/overlay2/l/VXELQ4XLOENQCDCK5CX4IPO5WL:/var/lib/docker/overlay2/l/I6SEZQSZ3EKVJXYU6I3R4YYF3R:/var/lib/docker/overlay2/l/BOSRSFNQISBSKYJ5KHZOZNC6ZS:/var/li'
Unexpected end of /proc/mounts line `b/docker/overlay2/l/RPOAEC2BWBGVHOAS5BCAT2CJVC:/var/lib/docker/overlay2/l/E73WAJZEID4NUWD2LVF7B5FYWA:/var/lib/docker/overlay2/l/OWH4GCEQSUYWEXYYPKNHIK2GV5:/var/lib/docker/overlay2/l/WBPZ5OCYJYY6N7LPPKJTNRQN2Z:/var/lib/docker/overlay2/l/J5PMN7ZRYKNRO2SAPXI74DKVJP:/var/lib/docker/overlay2/l/VGDU5OSG27XOWKG53SHRMOFYBU:/var/lib/docker/overlay2/l/4F64LOLLFAG3XYM32XUVLE27RA:/var/lib/docker/overlay2/l/LBSX74NEML6EWS7OSPGCD4JHRZ:/var/lib/docker/overlay2/l/DAOJ3CGMHHPXGWYQTYWF6M5BDZ:/var/lib/docker/overlay2/l/KTAQZ'
Traceback (most recent call last):
  File "train.py", line 410, in <module>
    nprocs=args.distributed_world_size,
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 167, in spawn
    while not spawn_context.join():
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 114, in join
    raise Exception(msg)
Exception: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/projects/nmt/fairseq_fifi/train.py", line 377, in distributed_main
    main(args)
  File "/projects/nmt/fairseq_fifi/train.py", line 100, in main
    train(args, trainer, task, epoch_itr)
  File "/projects/nmt/fairseq_fifi/train.py", line 134, in train
    for i, samples in enumerate(progress, start=epoch_itr.iterations_in_epoch):
  File "/projects/nmt/fairseq_fifi/fairseq/progress_bar.py", line 170, in __iter__
    for i, obj in enumerate(self.iterable):
  File "/projects/nmt/fairseq_fifi/fairseq/data/iterators.py", line 213, in __next__
    chunk.append(next(self.itr))
  File "/projects/nmt/fairseq_fifi/fairseq/data/iterators.py", line 43, in __next__
    return next(self.itr)
  File "/projects/nmt/fairseq_fifi/fairseq/data/iterators.py", line 38, in __iter__
    for x in self.iterable:
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 124, in __iter__
    return _DataLoaderIter(self)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 400, in __init__
    w.start()
  File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/opt/conda/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/opt/conda/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/opt/conda/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/conda/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/conda/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/opt/conda/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot serialize '_io.FileIO' object

```

**Comment by howlinghuffy** [comment]
+1 I am getting the same error when training fp16 on multiple GPUs

**Comment by myleott** [comment]
Sorry, we didn't get a chance to look into this and now the issue is quite stale, so it may be difficult to debug.

Closing for now, but please open a new issue following one of the new Issue templates if needed, thanks!
