### ISSUE TITLE
ran out of memory causing ZeroDivisionError: division by zero 

### ISSUE THREAD

**Issue by afaq-ahmad** [pytorch/fairseq#569]
| epoch 013:    100 / 1899 loss=4.386, nll_loss=4.386, ppl=20.91, wps=188, ups=2.5, wpb=74, bsz=8, num_updates=22889, lr=0.0001, gnorm=2.193, clip=100%, oom=0.0012233
| WARNING: ran out of memory, skipping batch
C:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\torch\autograd\function.py:41: UserWarning: mark_shared_storage is deprecated. Tensors with shared storages are automatically tracked. Note that calls to `set_()` are not tracked
  'mark_shared_storage is deprecated. '
C:\Users\Gangolian's PC\Desktop\WikiHow Text Summary\Step 5\Topic-ConvS2S\fairseq\trainer.py:195: UserWarning: torch.nn.utils.clip_grad_norm is now deprecated in favor of torch.nn.utils.clip_grad_norm_.
  grad_norm = utils.item(torch.nn.utils.clip_grad_norm(self.model.parameters(), self.args.clip_norm))
Traceback (most recent call last):
  File "Topic-ConvS2S/train.py", line 29, in <module>
    main(args)
  File "Topic-ConvS2S/train.py", line 23, in main
    singleprocess_main(args)
  File "C:\Users\Gangolian's PC\Desktop\WikiHow Text Summary\Step 5\Topic-ConvS2S\singleprocess_train.py", line 86, in main
    train(args, trainer, dataset, epoch, batch_offset)
  File "C:\Users\Gangolian's PC\Desktop\WikiHow Text Summary\Step 5\Topic-ConvS2S\singleprocess_train.py", line 150, in train
    log_output = trainer.train_step(sample)
  File "C:\Users\Gangolian's PC\Desktop\WikiHow Text Summary\Step 5\Topic-ConvS2S\fairseq\trainer.py", line 102, in train_step
    agg_logging_output = self.criterion.__class__.aggregate_logging_outputs(logging_outputs)
  File "C:\Users\Gangolian's PC\Desktop\WikiHow Text Summary\Step 5\Topic-ConvS2S\fairseq\criterions\label_smoothed_cross_entropy.py", line 68, in aggregate_logging_outputs
    'loss': sum(log.get('loss', 0) for log in logging_outputs) / sample_size / math.log(2),
ZeroDivisionError: division by zero

**Comment by huihuifan** [comment]
It looks like the sample size might be 0 because there is nothing in your batch. Can you look into why you are running out of memory? Perhaps cap the number of tokens that can be in your batch.

**Comment by afaq-ahmad** [comment]
This problem solved by decreasing the sentence size. But doesn't yet sure why sample size becomes zero.
