### ISSUE TITLE
Error when --no-early-stop is set during beam search for translation

### ISSUE THREAD

**Issue by freewym** [pytorch/fairseq#588]
I followed the example usage  in [https://github.com/pytorch/fairseq/blob/master/examples/translation/README.md](url) to train an fconv model and then did a beam search with the command:

`fairseq-generate data-bin/iwslt14.tokenized.de-en \
  --path checkpoints/fconv/checkpoint_best.pt \
  --batch-size 128 --beam 5 --remove-bpe` 

which went well. However, when I added `--no-early-stop` to the above command, it gave and index error:

`| [de] dictionary: 8848 types
| [en] dictionary: 6632 types
| data-bin/iwslt14.tokenized.de-en test 6750 examples
| ['data-bin/iwslt14.tokenized.de-en'] test 6750 examples
| loading model(s) from checkpoints/fconv/checkpoint_best.pt
  0%|                                                                                                                                                      | 0/53 [00:00<?, ?it/s]Traceback (most recent call last):
  File "generate.py", line 192, in <module>
    cli_main()
  File "generate.py", line 188, in cli_main
    main(args)
  File "generate.py", line 106, in main
    hypos = task.inference_step(generator, models, sample, prefix_tokens)
  File "/home/ywang/fairseq3/fairseq/tasks/fairseq_task.py", line 242, in inference_step
    return generator.generate(models, sample, prefix_tokens=prefix_tokens)
  File "/home/ywang/anaconda3/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 43, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/ywang/fairseq3/fairseq/sequence_generator.py", line 417, in generate
    finalized_sents = finalize_hypos(step, eos_bbsz_idx, eos_scores, cand_scores)
  File "/home/ywang/fairseq3/fairseq/sequence_generator.py", line 290, in finalize_hypos
    if not finished[sent] and is_finished(sent, step, unfinalized_scores):
  File "/home/ywang/fairseq3/fairseq/sequence_generator.py", line 193, in is_finished
    best_unfinalized_score = unfinalized_scores[sent].max()
IndexError: index 127 is out of bounds for dimension 0 with size 127`

The problem only took place when batch-size > 1. I didn't change anything in the code. Does anyone know how to fix it? Thanks!

**Comment by zherowolf** [comment]
same question.
