### ISSUE TITLE
Cannot replace unk because alignment is None

### ISSUE THREAD

**Issue by feralvam** [pytorch/fairseq#686]
Hi,
After training a model (Transformer architecture), I tried to generate predictions using this command:

```
fairseq-interactive "${data_dir}/bin" \
  --path "${model_dir}/checkpoint_avg10.pt" \
  --input "${data_dir}/test.tok.aner.low.orig" \
  --source-lang ${src_lang} --target-lang ${tgt_lang} \
  --buffer-size 64 --beam 5 --cpu --replace-unk | tee "${experiment_dir}/outputs/checkpoint_avg10.out"
```

However, I get the following error:

```
Traceback (most recent call last):
  File "/home/falva/anaconda3/envs/mtl4ts/bin/fairseq-interactive", line 11, in <module>
Namespace(beam=5, buffer_size=64, cpu=True, data=['/experiments/falva/mtl4ts/runs/tok_aner_low/data/bin'], diverse_beam_groups=-1, diverse_beam_strength=0.5, fp16=False, fp16_init_scale=128, fp16_scale_tolerance=0.0, fp16_scale_window=None, gen_subset='test', input='/experiments/falva/mtl4ts/runs/tok_aner_low/data/test.tok.aner.low.orig', lazy_load=False, left_pad_source='True', left_pad_target='False', lenpen=1, log_format=None, log_interval=1000, match_source_len=False, max_len_a=0, max_len_b=200, max_sentences=1, max_source_positions=1024, max_target_positions=1024, max_tokens=None, memory_efficient_fp16=False, min_len=1, min_loss_scale=0.0001, model_overrides='{}', nbest=1, no_beamable_mm=False, no_early_stop=False, no_progress_bar=False, no_repeat_ngram_size=0, num_shards=1, num_workers=0, path='/experiments/falva/mtl4ts/runs/tok_aner_low/model/checkpoint_avg10.pt', prefix_size=0, print_alignment=False, quiet=False, raw_text=False, remove_bpe=None, replace_unk=True, required_batch_size_multiple=8, results_path=None, sacrebleu=False, sampling=False, sampling_temperature=1, sampling_topk=-1, score_reference=False, seed=1, shard_id=0, skip_invalid_size_inputs_valid_test=False, source_lang='orig', target_lang='simp', task='translation', tensorboard_logdir='', threshold_loss_scale=None, unkpen=0, unnormalized=False, upsample_primary=1, user_dir=None)
| [orig] dictionary: 10008 types
| [simp] dictionary: 10008 types
| loading model(s) from /experiments/falva/mtl4ts/runs/tok_aner_low/model/checkpoint_avg10.pt
| Sentence buffer size: 64
| Type the input sentence and press return:
S-0     one side of the armed conflicts is composed mainly of the <unk> military and the organization@1 , a <unk> militia group recruited mostly from the <unk> <unk> tribes of the northern location@1 region in location@2 .
    load_entry_point('fairseq', 'console_scripts', 'fairseq-interactive')()
  File "/tools/fairseq/fairseq_cli/interactive.py", line 170, in cli_main
    main(args)
  File "/tools/fairseq/fairseq_cli/interactive.py", line 150, in main
    remove_bpe=args.remove_bpe,
  File "/tools/fairseq/fairseq/utils.py", line 153, in post_process_prediction
    hypo_str = replace_unk(hypo_str, src_str, alignment, align_dict, tgt_dict.unk_string())
  File "/tools/fairseq/fairseq/utils.py", line 143, in replace_unk
    src_token = src_tokens[alignment[i]]
TypeError: 'NoneType' object is not subscriptable
```

This is because `alignment` is None. What could be the cause of these?

Some additional information:

1. I did not use BPE. The reason is that, for this particular experiment, I want to check the effect that BPE has (if any) in the training of the model.

2. The original data is already tokenised and NER-anonymised. So, I only used this command for pre-processing:

```
fairseq-preprocess --source-lang ${src_lang} --target-lang ${tgt_lang} \
                   --trainpref "${data_dir}/train.tok.aner.low" --validpref "${data_dir}/valid.tok.aner.low" --testpref "${data_dir}/test.tok.aner.low" \
                   --destdir "${data_dir}/bin" --nwordssrc 10001 --nwordstgt 10001
```

3. I used `interactive` and not `generate` because the latter did not generate the output sentences in the same order as they were input. 

Any help you could provide is welcome. Thanks.

**Comment by Lucianod28** [comment]
Did you ever figure this out? I'm having the same issue.

**Comment by feralvam** [comment]
@Lucianod28 I ended up using BPE, so it was no longer a problem.
