### ISSUE TITLE
RuntimeError: copy_if failed to synchronize: device-side assert triggered

### ISSUE THREAD

**Issue by xwuShirley** [pytorch/fairseq#724]
Hi I am new to fairseq. It would be great if someone can help with following issue :) Thanks in advanced! 
I use 2 GPU 
`python train.py data/wmt16.s2s.en-de/  --arch transformer_wmt_en_de --share-all-embeddings           --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0             --lr-scheduler inverse_sqrt --warmup-init-lr 1e-07 --warmup-updates 4000               --lr 0.0005 --min-lr 1e-09              --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --weight-decay 0.0              --max-tokens  4096   --save-dir checkpoints/en-de              --update-freq 2 --no-progress-bar --log-format json --log-interval 50             --save-interval-updates  1000`

The following are the output;
```
{"epoch": 1, "update": 0.005, "loss": "14.943", "nll_loss": "14.855", "ppl": "29640.53", "wps": "24921", "ups": "1", "wpb": "14618.039", "bsz": "459.451", "num_updates": "51", "lr": "6.47373e-06", "gnorm": "4.121", "clip": "0.000", "oom": "0.000", "wall": "79", "train_wall": "29"}
{"epoch": 1, "update": 0.011, "loss": "14.340", "nll_loss": "14.182", "ppl": "18582.22", "wps": "24869", "ups": "1", "wpb": "14686.139", "bsz": "471.525", "num_updates": "101", "lr": "1.27225e-05", "gnorm": "2.800", "clip": "0.000", "oom": "0.000", "wall": "109", "train_wall": "57"}
{"epoch": 1, "update": 0.016, "loss": "13.963", "nll_loss": "13.763", "ppl": "13897.87", "wps": "24655", "ups": "1", "wpb": "14570.219", "bsz": "465.219", "num_updates": "151", "lr": "1.89712e-05", "gnorm": "2.294", "clip": "0.000", "oom": "0.000", "wall": "138", "train_wall": "86"}
/opt/conda/conda-bld/pytorch-nightly_1552108073159/work/aten/src/THC/THCTensorIndex.cu:362: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [98,0,0], thread: [64,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
.....
-- Process 0 terminated with the following error:
Traceback (most recent call last):
File "python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
fn(i, *args)
File "./fairseq/train.py", line 387, in distributed_main
main(args)
File "./fairseq/train.py", line 99, in main
train(args, trainer, task, epoch_itr)
File "./fairseq/train.py", line 134, in train
log_output = trainer.train_step(samples)
File "./fairseq/fairseq/trainer.py", line 240, in train_step
raise e
File "./fairseq/fairseq/trainer.py", line 217, in train_step
ignore_grad
File "./fairseq/fairseq/tasks/fairseq_task.py", line 228, in train_step
loss, sample_size, logging_output = criterion(model, sample)
File "python3.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
result = self.forward(*input, **kwargs)
File "./fairseq/fairseq/criterions/label_smoothed_cross_entropy.py", line 39, in forward
loss, nll_loss = self.compute_loss(model, net_output, sample, reduce=reduce)
File "./fairseq/fairseq/criterions/label_smoothed_cross_entropy.py", line 55, in compute_loss
nll_loss = -lprobs.gather(dim=-1, index=target)[non_pad_mask]
RuntimeError: copy_if failed to synchronize: device-side assert triggered
```

**Comment by xwuShirley** [comment]
I found something similar but I am not sure how to fix

https://github.com/pytorch/pytorch/issues/1204

**Comment by qazwsx74269** [comment]
I encountered the mostly same problem with this. You can find this message in your traceback.

> Assertion `srcIndex < srcSelectDimSize` failed.
It means that the function--index_select receive wrong input. In details, the index dim you want to select is larger than the dimsize of your input . For example, a = [1,2,3], a.index_select(1,[0,2]), a has just one dim but index dim is 1 which trigger Assert Error. I fixed this problem by modified my dataset making it following the source dataset(like IndexedRawDataset.etc) provided by fairseq.
