### ISSUE TITLE
Missing key(s) in state_dict with translation_moe while generating

### ISSUE THREAD

**Issue by JohannesTK** [pytorch/fairseq#742]
Hi.

Following [Mixture Models for Diverse Machine Translation: Tricks of the Trade](https://github.com/pytorch/fairseq/blob/master/examples/translation_moe/README.md) ends up with missing key(s) in state_dict error while generating:

```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/bin/fairseq-interactive", line 11, in <module>
    sys.exit(cli_main())
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fairseq_cli/interactive.py", line 169, in cli_main
    main(args)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fairseq_cli/interactive.py", line 81, in main
    args.path.split(':'), task, model_arg_overrides=eval(args.model_overrides),
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fairseq/utils.py", line 168, in load_ensemble_for_inference
    model.load_state_dict(state['model'], strict=True)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fairseq/models/fairseq_model.py", line 66, in load_state_dict
    super().load_state_dict(state_dict, strict)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for TransformerModel:
	Missing key(s) in state_dict: "gating_network.fc1.weight", "gating_network.fc1.bias", "gating_network.fc2.weight", "gating_network.fc2.bias".
```

Steps I took:

1. Prepared data

```
cd examples/translation/
bash prepare-wmt14en2fr.sh
cd ../..

# Binarize the dataset:
TEXT=examples/translation/wmt14_en_fr

nohup fairseq-preprocess --source-lang fr --target-lang en \
  --trainpref $TEXT/train --validpref $TEXT/valid --testpref $TEXT/test \
  --destdir data-bin/wmt14_en_fr --thresholdtgt 0 --thresholdsrc 0 --joined-dictionary &
```

2. Trained

```
nohup fairseq-train data-bin/wmt14_fr_en \
  --max-update 400000 \
  --task translation_moe \
  --method hMoEup --mean-pool-gating-network \
  --num-experts 3 \
  --arch transformer_vaswani_wmt_en_fr_big --share-all-embeddings \
  --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 \
  --lr-scheduler inverse_sqrt --warmup-init-lr 1e-07 --warmup-updates 4000 \
  --lr 0.0007 --min-lr 1e-09 \
  --dropout 0.1 --weight-decay 0.0 --criterion cross_entropy \
  --max-tokens 3584 \
  --update-freq 8 --tensorboard-logdir=write_tensorboard_logs \
  --save-dir=fr_to_en_diverse_checkpoints --save-interval-updates=20000 \
  --keep-interval-updates=10  &>> logs.txt &
```

3. Generated (ends up with the traceback)

```
fairseq-generate data-bin/wmt14_fr_en \
    --path fr_to_en_diverse_checkpoints/checkpoint_best.pt \
    --beam 1 --remove-bpe \
    --task translation_moe \
    --method hMoElp --mean-pool-gating-network \
    --num-experts 3 \
    --gen-expert 0 -s en -t fr
```

What's the solution? Thanks in advance!

**Comment by myleott** [comment]
You trained with a uniform prior (`--method hMoEup`) and are evaluating with a learned prior (`--method hMoElp`). The latter requires a gating network while the former does not.

You should be able to generate by swapping `hMoEup` into your generate command.

**Comment by JohannesTK** [comment]
My bad, thank you for the catch!
