### ISSUE TITLE
Evaluating perplexity of translation task

### ISSUE THREAD

**Issue by hc09141** [pytorch/fairseq#751]
I'm trying to evaluate the perplexity of a translation model I trained  using the following command and encountered an error (also listed below). 

fairseq-eval-lm fairseq-data/data-bin/en --source-lang en --target-lang de--path fairseq-data/en-de/checkpoint_best.pt --task translation --max-sentences 8

Traceback (most recent call last):
  File "/usr/local/bin/fairseq-eval-lm", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-eval-lm')()
  File "/local/scratch/hjc68/masters/fairseq/fairseq_cli/eval_lm.py", line 222, in cli_main
    main(args)
  File "/local/scratch/hjc68/masters/fairseq/fairseq_cli/eval_lm.py", line 76, in main
    args.tokens_per_sample -= args.context_window
AttributeError: 'Namespace' object has no attribute 'tokens_per_sample'

**Comment by nng555** [comment]
Perplexity (within NLP) is a measure of how well a language model can predict the next word in a sequence. It is not usually used to measure the performance of a translation model.

If you want to evaluate your translation model, you can use generate.py to translate a test dataset, and it will output a BLEU score that you can use to compare to other models.

**Comment by hc09141** [comment]
Thanks for your response. I was using the Hierarchical Story Generation architecture and saw that on another issue the --task translation flag could be used with eval_lm #368 . Regardless of whether I am using the model for translation or story generation, should I be able to use the eval_lm as described in #368?

**Comment by huihuifan** [comment]
try:

`python eval_lm.py data-bin/writingPrompts \
  --path fusion_checkpoint.pt \
  --model-overrides "{'pretrained_checkpoint':'pretrained_checkpoint.pt'}" \
  --task translation --max-sentences 8
(...)
| [wp_source] dictionary: 19025 types
| [wp_target] dictionary: 104960 types
| loading model(s) from /checkpoint/myleott/stories/fusion_checkpoint.pt
| loading pretrained model
| [wp_source] dictionary: 19025 types
| [wp_target] dictionary: 104960 types
| /private/home/myleott/data/data-bin/writingPrompts/ test 15138 examples
| ['/private/home/myleott/data/data-bin/writingPrompts/'] test 15138 examples
num. model params: 194005760
| Evaluated 8982054 tokens in 495.6s (18121.84 tokens/s)
| Loss: 3.5839, Perplexity: 36.01`

**Comment by ehsan-soe** [comment]
@huihuifan I am getting the same error when running the command you said.

```
Traceback (most recent call last):
  File "eval_lm.py", line 223, in <module>
    cli_main()
  File "eval_lm.py", line 219, in cli_main
    main(args)
  File "eval_lm.py", line 73, in main
    args.tokens_per_sample -= args.context_window
AttributeError: 'Namespace' object has no attribute 'tokens_per_sample'
```

should we add 'tokens_per_sample' to option.py somehow?

**Comment by huihuifan** [comment]
Looks like --tokens-per-sample is only included for language models, not translation models, so a code change that added this args.tokens_per_sample makes it not compatible. Instead, I believe you can use generate.py with the --score-reference option, which will output "H" lines that have the log likelihood of each sample

**Comment by lematt1991** [comment]
Closing due to inactivity.
