### ISSUE TITLE
Failed to load XLM checkpoints

### ISSUE THREAD

**Issue by yilinyang7** [pytorch/fairseq#787]
Hi team,

I was trying to load pre-trained XLM checkpoint into NMT model with --arch transformer_from_pretrained_xlm, and --task translation_from_pretrained_xlm, but ends up facing "KeyError: 'best_loss'" from loading XLM checkpoints.

Here's the command and traceback:

> python train.py data-bin/xlmbpe_wmt14_en_de --arch transformer_from_pretrained_xlm --share-all-embeddings --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 --lr-scheduler inverse_sqrt --warmup-init-lr 1e-07 --warmup-updates 4000 --lr 0.0007 --min-lr 1e-09 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --weight-decay 0.0 --max-tokens 8192  --no-progress-bar --log-format json --log-interval 50 --dropout 0.1 --save-dir checkpoints/xlmbpe_wmt14_en_de --distributed-world-size 1 --pretrained-xlm-checkpoint pretrain_tlm_from_scratch/checkpoint.pth --task translation_from_pretrained_xlm

```python
Traceback (most recent call last):
  File "train.py", line 306, in <module>
    cli_main()
  File "train.py", line 302, in cli_main
    main(args)
  File "train.py", line 49, in main
    model = task.build_model(args)
  File "/app/home/on_fire/xlm_fairseq/fairseq/tasks/fairseq_task.py", line 169, in build_model
    return models.build_model(args, self)
  File "/app/home/on_fire/xlm_fairseq/fairseq/models/__init__.py", line 50, in build_model
    return ARCH_MODEL_REGISTRY[args.arch].build_model(args, task)
  File "/app/home/on_fire/xlm_fairseq/fairseq/models/transformer_from_pretrained_xlm.py", line 65, in build_model
    return super().build_model(args, task)
  File "/app/home/on_fire/xlm_fairseq/fairseq/models/transformer.py", line 156, in build_model
    encoder = cls.build_encoder(args, src_dict, encoder_embed_tokens)
  File "/app/home/on_fire/xlm_fairseq/fairseq/models/transformer_from_pretrained_xlm.py", line 69, in build_encoder
    return TransformerEncoderFromPretrainedXLM(args, src_dict, embed_tokens)
  File "/app/home/on_fire/xlm_fairseq/fairseq/models/transformer_from_pretrained_xlm.py", line 127, in __init__
    pretrained_xlm_checkpoint=args.pretrained_xlm_checkpoint,
  File "/app/home/on_fire/xlm_fairseq/fairseq/models/transformer_from_pretrained_xlm.py", line 95, in upgrade_state_dict_with_xlm_weights
    state = checkpoint_utils.load_checkpoint_to_cpu(pretrained_xlm_checkpoint)
  File "/app/home/on_fire/xlm_fairseq/fairseq/checkpoint_utils.py", line 135, in load_checkpoint_to_cpu
    state = _upgrade_state_dict(state)
  File "/app/home/on_fire/xlm_fairseq/fairseq/checkpoint_utils.py", line 244, in _upgrade_state_dict
    'best_loss': state['best_loss'],
KeyError: 'best_loss'
```

**Comment by PlayDeep** [comment]
@yilinyang7 Do you have solve this problem? I have same trouble like this and I thought this pretrained_xlm_checkpoint is not compatible with the public xlm checkpoint in [https://github.com/facebookresearch/XLM#pretrained-xlmmlm-models](url)

**Comment by weissercn** [comment]
Has there been any progress on this? Am I missing something?

**Comment by ruitedk6** [comment]
I am also curious. I have a pre-trained XLM model (using https://github.com/facebookresearch/XLM). How is it possible to load this into fairseq using translation_from_pretrained_xlm?

**Comment by steve3p0** [comment]
bump
