### ISSUE TITLE
Issue with train script (translation task) - fairseq v0.7.0

### ISSUE THREAD

**Issue by lengockyquang** [pytorch/fairseq#820]
Hi fairseq team, i have cloned latest version of fairseq and use it to train new translation model. The preprocess works fine but with train script, it gave me below error
The train script:

> !CUDA_VISIBLE_DEVICES=0 fairseq-train fairseq/data-bin \
--dropout 0.2 \
--max-tokens 4000 \
--arch lstm \
--max-epoch=20 \
--save-dir checkpoints \
--fp16 --encoder-bidirectional \
--optimizer nag --lr 0.01 \

And error:

> | model lstm, criterion CrossEntropyCriterion
| num. model params: 40918008 (num. trained: 40918008)
| training on 1 GPUs
| max tokens per GPU = 4000 and max sentences per GPU = None
| no existing checkpoint found checkpoints/checkpoint_last.pt
| loading train data for epoch 0
| fairseq/data-bin train en-vi 133318 examples
| epoch 001:   0% 0/970 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/usr/local/bin/fairseq-train", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-train')()
  File "/content/fairseq/fairseq_cli/train.py", line 302, in cli_main
    main(args)
  File "/content/fairseq/fairseq_cli/train.py", line 80, in main
    train(args, trainer, task, epoch_itr)
  File "/content/fairseq/fairseq_cli/train.py", line 121, in train
    log_output = trainer.train_step(samples)
  File "/content/fairseq/fairseq/trainer.py", line 236, in train_step
    sample = self._prepare_sample(sample, self.args.fp16)
  File "/content/fairseq/fairseq/trainer.py", line 496, in _prepare_sample
    sample = utils.move_to_cuda(sample)
  File "/content/fairseq/fairseq/utils.py", line 53, in move_to_cuda
    return apply(_move_to_cuda, sample)
  File "/content/fairseq/fairseq/utils.py", line 42, in apply
    for key, value in sample.items()
  File "/content/fairseq/fairseq/utils.py", line 42, in <dictcomp>
    for key, value in sample.items()
  File "/content/fairseq/fairseq/utils.py", line 35, in apply
    if len(sample) == 0:
TypeError: object of type 'int' has no len()

I have tested with previous fairseq (0.6.2) and it works fine

**Comment by lengockyquang** [comment]
Fix with fairseq v0.7.1
