### ISSUE TITLE
cpp:272, unhandled system error

### ISSUE THREAD

**Issue by sany2009** [pytorch/fairseq#826]
I am trying to run distributed training with Pytorch Version (1.2.0a0+63ca908) and FAIRSEQ Release 0.7.1 for 8 GPU on a AWS P3dn EC2 Instance. 
NCCL Version - 2.4.6 and CUDA 10
I am getting this error. Please provide a solution

ip-172-31-34-232:63799:64163 [7] include/socket.h:387 NCCL WARN Connect to 172.31.34.232<52473> failed : Connection refused

Traceback (most recent call last):
  File "train.py", line 306, in <module>
    cli_main()
  File "train.py", line 283, in cli_main
    nprocs=torch.cuda.device_count(),
  File "/home/ec2-user/anaconda3/envs/ps_2.4.6_env/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 167, in spawn
    while not spawn_context.join():
  File "/home/ec2-user/anaconda3/envs/ps_2.4.6_env/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 114, in join
    raise Exception(msg)
Exception: 

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/ps_2.4.6_env/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/ec2-user/fairseq/train.py", line 265, in distributed_main
    main(args, init_distributed=True)
  File "/home/ec2-user/fairseq/train.py", line 36, in main
    args.distributed_rank = distributed_utils.distributed_init(args)
  File "/home/ec2-user/fairseq/fairseq/distributed_utils.py", line 85, in distributed_init
    dist.all_reduce(torch.rand(1).cuda())
  File "/home/ec2-user/anaconda3/envs/ps_2.4.6_env/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 900, in all_reduce
    work = _default_pg.allreduce([tensor], opts)
RuntimeError: NCCL error in: ../torch/lib/c10d/ProcessGroupNCCL.cpp:272, unhandled system error

**Comment by raxxerwan** [comment]
Hi, I've met exactly the same problem with you now. Did you find any solutions or get any ideas?

**Comment by sany2009** [comment]
Nope !!
Thanks,
Sany | 408-673-8709

**Comment by huihuifan** [comment]
What command did you use? Do you have 8 GPU on one machine? If so, you don't need distributed training?

**Comment by huihuifan** [comment]
Thanks @Bournet ! @sany2009 and @raxxerwan, could you try this out?

**Comment by lematt1991** [comment]
Sounds like this is resolved.
