### ISSUE TITLE
eval-lm on raw texts fails

### ISSUE THREAD

**Issue by nicolabertoldi** [pytorch/fairseq#853]
I am trying to get acquainted with language_modeling task
I was able to train properly an engine

but I am not able to run the evaluation on raw text data.

If I use the binarized dataset running this command, everything works well
```
fairseq-eval-lm data-bin/wikitext-103_SMALL/ --path ./checkpoints/transformer_wikitext-103/checkpoint_best.pt --sample-break-mode eos --max-tokens 3072 --context-window 128 --softmax-batch 9192
```

but I add the `--raw-text` parameter as follows:
```
fairseq-eval-lm data-bin/wikitext-103_SMALL/ --path ./checkpoints/transformer_wikitext-103/checkpoint_best.pt --sample-break-mode eos --max-tokens 3072 --context-window 128 --softmax-batch 9192 --raw-text
```
I got this error
```
Traceback (most recent call last):
  File "/usr/local/bin/fairseq-eval-lm", line 11, in <module>
    sys.exit(cli_main())
  File "/usr/local/lib/python3.6/dist-packages/fairseq_cli/eval_lm.py", line 212, in cli_main
    main(args)
  File "/usr/local/lib/python3.6/dist-packages/fairseq_cli/eval_lm.py", line 75, in main
    task.load_dataset(args.gen_subset)
  File "/usr/local/lib/python3.6/dist-packages/fairseq/tasks/language_modeling.py", line 161, in load_dataset
    raise FileNotFoundError('Dataset not found: {} ({})'.format(split, self.args.data))
FileNotFoundError: Dataset not found: test (data-bin/wikitext-103_SMALL/)
```

Which is the right command?
Which is the right format of the raw data to pass?

**Comment by myleott** [comment]
Command is fine. To generate with raw text it will look in `os.path.join(args.data, args.gen_subset)`. So in your case it's looking for a plaintext file named "data-bin/wikitext-103_SMALL/test" and can't find it.
