### ISSUE TITLE
UnicodeEncodeError in interactive

### ISSUE THREAD

**Issue by t-ludel** [pytorch/fairseq#855]
I am trying to run interactive.py with a simple input, "how do I reset my password," which I put in a file test2.en. This is the bash I am running:
```bash
file=data/test2.en
checkpoint=checkpoint/checkpoint_2_152000.pt

cat $file | CUDA_VISIBLE_DEVICES=1 python fairseq/interactive.py ./data --path $checkpoint `--is-rev-tgt
```
and this is the error I'm getting:
```
Namespace(beam=5, bleu_dir='', buffer_size=1, cpu=False, custom_philly_tools='/blob/v-wechen/philly_tools', data=['./data'], diverse_beam_groups=1, diverse_beam_strength=0.5, fp16=False, fp16_init_scale=128, gen_candi=False, gen_subset='test', is_rev_tgt=True, lazy_load=False, left_pad_source='True', left_pad_target='False', lenpen=1, log_format=None, log_interval=1000, max_len_a=0, max_len_b=200, max_sentences=1, max_source_positions=1024, max_target_positions=1024, max_tokens=None, min_len=1, model_overrides='{}', nbest=1, no_beamable_mm=False, no_early_stop=False, no_progress_bar=False, num_shards=1, path='checkpoint/checkpoint_2_152000.pt', prefix_size=0, print_alignment=False, quiet=False, raw_text=False, remove_bpe=None, replace_unk=None, sampling=False, sampling_temperature=1, sampling_topk=-1, score_reference=False, seed=1, shard_id=0, skip_invalid_size_inputs_valid_test=False, source_lang=None, target_lang=None, task='translation', test_bleu=False, unkpen=0, unnormalized=False, upsample_primary=1)
| [en] dictionary: 40000 types
| [zh] dictionary: 40000 types
| loading model(s) from checkpoint/checkpoint_2_152000.pt
| Type the input sentence and press return:
O       How do I reset my password
Traceback (most recent call last):
  File "fairseq/interactive.py", line 185, in <module>
    main(args)
  File "fairseq/interactive.py", line 176, in main
    print(hypo)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 22-23: character maps to <undefined>
```
Any idea what could be causing this? Thanks!

**Comment by t-ludel** [comment]
This was in git bash. I tried running in Ubuntu and it works.
