### ISSUE TITLE
permission denied with multi-gpu training

### ISSUE THREAD

**Issue by MichaelZhouwang** [pytorch/fairseq#857]
I tried using four gpus to train a new model but I got an error like this:

2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002: Traceback (most recent call last):
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002:   File "<string>", line 1, in <module>
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002:   File "/opt/conda/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002:     exitcode = _main(fd)
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002:   File "/opt/conda/lib/python3.6/multiprocessing/spawn.py", line 114, in _main
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002:     prepare(preparation_data)
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002:   File "/opt/conda/lib/python3.6/multiprocessing/spawn.py", line 214, in prepare
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002:     os.chdir(data['dir'])
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002: PermissionError: [Errno 13] Permission denied: '/root'
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002: Traceback (most recent call last):
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002:   File "<string>", line 1, in <module>
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002:   File "/opt/conda/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002:     exitcode = _main(fd)
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002:   File "/opt/conda/lib/python3.6/multiprocessing/spawn.py", line 114, in _main
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002:     prepare(preparation_data)
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002:   File "/opt/conda/lib/python3.6/multiprocessing/spawn.py", line 214, in prepare
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002:     os.chdir(data['dir'])
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002: PermissionError: [Errno 13] Permission denied: '/root'
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002: Traceback (most recent call last):
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002:   File "<string>", line 1, in <module>
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002:   File "/opt/conda/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002:     exitcode = _main(fd)
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002:   File "/opt/conda/lib/python3.6/multiprocessing/spawn.py", line 114, in _main
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002:     prepare(preparation_data)
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002:   File "/opt/conda/lib/python3.6/multiprocessing/spawn.py", line 214, in prepare
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002:     os.chdir(data['dir'])
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002: PermissionError: [Errno 13] Permission denied: '/root'
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002: Traceback (most recent call last):
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002:   File "/opt/conda/bin/fairseq-train", line 10, in <module>
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002:     sys.exit(cli_main())
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002:   File "/opt/conda/lib/python3.6/site-packages/fairseq_cli/train.py", line 298, in cli_main
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002:     nprocs=args.distributed_world_size,
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002:   File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 167, in spawn
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002:     while not spawn_context.join():
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002:   File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 108, in join
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002:     (error_index, exitcode)
2019-07-04T06:18:48.000Z /container_e559_1557431881457_79419_05_000002: Exception: process 0 terminated with exit code 1

It seems that I have not permission to write to /dev/shm. However I used a docker in which I have already chmod 777 /dev/shm and then commit and push the changes. After that I still got this error, any advices? Thanks A LOT!!

**Comment by huihuifan** [comment]
Hello, this is very difficult for us to help you with, as it seems like an issue with your system. You could try to write to another directory.
