### ISSUE TITLE
Different shape between input and pretrained model

### ISSUE THREAD

**Issue by ivokun** [pytorch/fairseq#861]
Hi, I'm looking for generating story from WritingPrompt model. But, it shown an error like below.

```
RuntimeError: Error(s) in loading state_dict for FConvModelSelfAtt:
        size mismatch for decoder.embed_tokens.weight: copying a param with shape torch.Size([104960, 256]) from checkpoint, the shape in current model is torch.Size([112832, 256]).
        size mismatch for decoder.fc3.weight: copying a param with shape torch.Size([104960, 256]) from checkpoint, the shape in current model is torch.Size([112832, 256]).
        size mismatch for decoder.fc3.bias: copying a param with shape torch.Size([104960]) from checkpoint, the shape in current model is torch.Size([112832]).
```

I followed instructions from https://github.com/pytorch/fairseq/blob/master/examples/stories/README.md

and ran it with

`python generate.py data-bin/writingPrompts --path models/fusion_check
point.pt --batch-size 32 --beam 1 --sampling --sampling-topk 10 --temperature 0.8 --nbest 1 --model-overrides "{'pret
rained_checkpoint':'models/pretrained_checkpoint.pt'}"`

Maybe because different of dataset between existing dataset and the model?

**Comment by ivokun** [comment]
It seems after I preprocessing dataset again the issue is gone.

**Comment by ehsan-soe** [comment]
@ivokun I am having the same issue. DO you mean you've not preprocess the data in the first attempt? or you just did preprocess again and the issue resolved? how?

**Comment by taineleau** [comment]
Got the same problem today. Followed the document already.
`Fairseq version: 1.0.0a0+1c0439b`
error log:
```
2021-06-11 12:05:29 | INFO | fairseq.tasks.translation | [wp_source] dictionary: 19025 types
2021-06-11 12:05:29 | INFO | fairseq.tasks.translation | [wp_target] dictionary: 112832 types
2021-06-11 12:05:29 | INFO | fairseq_cli.generate | loading model(s) from ./examples/stories/models/fusion_checkpoint.pt
2021-06-11 12:05:31 | INFO | fairseq.models.fconv_self_att | loading pretrained model
Traceback (most recent call last):
  File "/home/danlu/anaconda3/bin/fairseq-generate", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-generate')())
  File "/home/danlu/2021/beam_search/fairseq/fairseq_cli/generate.py", line 404, in cli_main
    main(args)
  File "/home/danlu/2021/beam_search/fairseq/fairseq_cli/generate.py", line 49, in main
    return _main(cfg, sys.stdout)
  File "/home/danlu/2021/beam_search/fairseq/fairseq_cli/generate.py", line 102, in _main
    num_shards=cfg.checkpoint.checkpoint_shard_count,
  File "/home/danlu/2021/beam_search/fairseq/fairseq/checkpoint_utils.py", line 304, in load_model_ensemble
    state,
  File "/home/danlu/2021/beam_search/fairseq/fairseq/checkpoint_utils.py", line 356, in load_model_ensemble_and_task
    model = task.build_model(cfg.model)
  File "/home/danlu/2021/beam_search/fairseq/fairseq/tasks/translation.py", line 365, in build_model
    model = super().build_model(cfg)
  File "/home/danlu/2021/beam_search/fairseq/fairseq/tasks/fairseq_task.py", line 323, in build_model
    model = models.build_model(cfg, self)
  File "/home/danlu/2021/beam_search/fairseq/fairseq/models/__init__.py", line 96, in build_model
    return model.build_model(cfg, task)
  File "/home/danlu/2021/beam_search/fairseq/fairseq/models/fconv_self_att.py", line 126, in build_model
    task=task,
  File "/home/danlu/2021/beam_search/fairseq/fairseq/checkpoint_utils.py", line 304, in load_model_ensemble
    state,
  File "/home/danlu/2021/beam_search/fairseq/fairseq/checkpoint_utils.py", line 358, in load_model_ensemble_and_task
    model.load_state_dict(state["model"], strict=strict, model_cfg=cfg.model)
  File "/home/danlu/2021/beam_search/fairseq/fairseq/models/fairseq_model.py", line 117, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/home/danlu/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for FConvModelSelfAtt:
        size mismatch for decoder.embed_tokens.weight: copying a param with shape torch.Size([104960, 256]) from checkpoint, the shape in current model is torch.Size([112832, 256]).
        size mismatch for decoder.fc3.weight: copying a param with shape torch.Size([104960, 256]) from checkpoint, the shape in current model is torch.Size([112832, 256]).
        size mismatch for decoder.fc3.bias: copying a param with shape torch.Size([104960]) from checkpoint, the shape in current model is torch.Size([112832]).
```
The pre-trained model and the fusion model are downloaded from the stories's readme, and the data was processed as the instruction said. Is the tokenizer/fairseq-preprocess changed?
