### ISSUE TITLE
Cannot load dictionary

### ISSUE THREAD

**Issue by Dobatymo** [pytorch/fairseq#865]
Following the example usage here: https://github.com/pytorch/fairseq/blob/master/examples/language_model/README.md

```
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
```

```python
Using cache found in C:\Users\<...>/.cache\torch\hub\pytorch_fairseq_master
loading archive file https://dl.fbaipublicfiles.com/fairseq/models/lm/adaptive_lm_wiki103.tar.bz2 from cache at C:\Users\<...>\.cache\torch\pytorch_fairseq\8f5513900ccbfa5196131abf5c673ce3b924f1b01df911ee9b70c3aedf3eaf09
C:\Users\<...>\.cache\torch\pytorch_fairseq\8f5513900ccbfa5196131abf5c673ce3b924f1b01df911ee9b70c3aedf3eaf09\data-bin
Traceback (most recent call last):
  File "fairseq-lm.py", line 3, in <module>
    lm = torch.hub.load('pytorch/fairseq', 'transformer_lm', model_name_or_path='transformer_lm.wiki103.adaptive', data_name_or_path='./data-bin', tokenizer='moses', aggressive_dash_splits=True, no_escape=True, beam=1, sampling=True, sampling_topk=10, temperature=0.8)
  File "D:\<...>\APPS\Programs\Python\Python37\lib\site-packages\torch\hub.py", line 341, in load
    model = entry(*args, **kwargs)
  File "C:\Users\<...>/.cache\torch\hub\pytorch_fairseq_master\fairseq\models\fairseq_model.py", line 196, in from_pretrained
    arg_overrides=kwargs,
  File "C:\Users\<...>/.cache\torch\hub\pytorch_fairseq_master\fairseq\checkpoint_utils.py", line 171, in _load_model_ensemble
    task = tasks.setup_task(args)
  File "C:\Users\<...>/.cache\torch\hub\pytorch_fairseq_master\fairseq\tasks\__init__.py", line 19, in setup_task
    return TASK_REGISTRY[args.task].setup_task(args, **kwargs)
  File "C:\Users\<...>/.cache\torch\hub\pytorch_fairseq_master\fairseq\tasks\language_modeling.py", line 118, in setup_task
    dictionary = Dictionary.load(os.path.join(paths[0], 'dict.txt'))
  File "C:\Users\<...>/.cache\torch\hub\pytorch_fairseq_master\fairseq\data\dictionary.py", line 184, in load
    d.add_from_file(f, ignore_utf_errors)
  File "C:\Users\<...>/.cache\torch\hub\pytorch_fairseq_master\fairseq\data\dictionary.py", line 201, in add_from_file
    raise fnfe
  File "C:\Users\<...>/.cache\torch\hub\pytorch_fairseq_master\fairseq\data\dictionary.py", line 195, in add_from_file
    with open(f, 'r', encoding='utf-8') as fd:
FileNotFoundError: [Errno 2] No such file or directory: 'C\\dict.txt'
```

It can be fixed (I think) be changing `paths = args.data.split(':')` to `paths = [args.data]` in `language_modeling.py` `setup_task`.

**Comment by myleott** [comment]
Ah, right, our path splitting convention doesn't really support Windows. If you want to add some logic to check if the user is on Windows and apply smarter splitting, PRs are welcome :)

You can of course locally apply your fix and things will work, as you observed.
