### ISSUE TITLE
Cannot handle the OOM exception

### ISSUE THREAD

**Issue by fuzihaofzh** [pytorch/fairseq#869]
Hi, I trained the model on multi GPUs and one of the node triggered the OOM problem. It seems it fails to handle with this OOM exception and the whole program crashed. Simply reduce the batch_size maks the GPU not fully utilized. I should only use 40% of the whole GPU memory and reserve 60% for the abnormal sample. I checked the code and found that "self._oom_batch" is None which makes it impossible to enter the oom handler function. 

 The log is as follows:

```
| WARNING: ran out of memory with exception: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 7.93 GiB total capacity; 7.20 GiB already allocated; 17.56 MiB free; 46.25 MiB cached);
 Skipping batch
Traceback (most recent call last):
  File "./fairseq/train.py", line 306, in <module>
    cli_main()
  File "./fairseq/train.py", line 298, in cli_main
    nprocs=args.distributed_world_size,
  File "/miniconda3/envs/py36/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 167, in spawn
    while not spawn_context.join():
  File "/miniconda3/envs/py36/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 114, in join
    raise Exception(msg)
Exception:

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/misc/projdata11-1/info_fil/zhfu/workbench/explore/github/fairseq/fairseq/fairseq/distributed_utils.py", line 169, in all_gather_list
    result.append(pickle.loads(bytes(out_buffer[2 : size + 2].tolist())))
_pickle.UnpicklingError: invalid load key, '\xa4'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/miniconda3/envs/py36/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/misc/projdata11-1/info_fil/zhfu/workbench/explore/github/fairseq/fairseq/train.py", line 265, in distributed_main
    main(args, init_distributed=True)
  File "/misc/projdata11-1/info_fil/zhfu/workbench/explore/github/fairseq/fairseq/train.py", line 80, in main
    train(args, trainer, task, epoch_itr)
  File "/misc/projdata11-1/info_fil/zhfu/workbench/explore/github/fairseq/fairseq/train.py", line 121, in train
    log_output = trainer.train_step(samples)
  File "/misc/projdata11-1/info_fil/zhfu/workbench/explore/github/fairseq/fairseq/fairseq/trainer.py", line 301, in train_step
    [logging_outputs, sample_sizes, ooms, self._prev_grad_norm],
  File "/misc/projdata11-1/info_fil/zhfu/workbench/explore/github/fairseq/fairseq/fairseq/distributed_utils.py", line 173, in all_gather_list
    'Unable to unpickle data from other workers. all_gather_list requires all '
Exception: Unable to unpickle data from other workers. all_gather_list requires all workers to enter the function together, so this error usually indicates that the workers have fallen out of sync somehow. Workers can fall out of sync if one of them runs out of memory, or if there are other conditions in your training script that can cause one worker to finish an epoch while other workers are still iterating over their portions of the data.

/miniconda3/envs/py36/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
```

**Comment by myleott** [comment]
OOM recovery is unreliable in general, so it's probably not good to depend on it. One of the main challenges is that it's very difficult to recover from OOM in a distributed setting with the latest version of DistributedDataParallel. We've kept the functionality around for some special cases, but I recommend instead using `--max-tokens` to define your batch size (which will dynamically increase/reduce the number of sentences depending on their lengths) or alternatively throwing away long inputs with `--max-source-positions`, `--max-target-positions`.

**Comment by huihuifan** [comment]
Yes, set the max tokens or trim your dataset so that example is smaller. For example, if you have a dataset where all of the inputs are 1000 words but 1 input is 10,000 words, you can trim that extra-long input to 1000 words. Or set the max source/max target positions, which will skip inputs that are too long.
