### ISSUE TITLE
TypeError when trying the translation example

### ISSUE THREAD

**Issue by Youwei-Liang** [pytorch/fairseq#954]
I am trying the example in Translation task:
```
>>> import torch
>>> torch.hub.list('pytorch/fairseq')
[..., 'transformer.wmt14.en-fr', 'transformer.wmt16.en-de', 'transformer.wmt18.en-de', ... ]
>>> en2de = torch.hub.load(
...   'pytorch/fairseq',
...   'transformer.wmt16.en-de',
...   data_name_or_path='.',
...   tokenizer='moses',
...   bpe='subword_nmt',
... )
>>> print(en2de.models[0].__class__)
<class 'fairseq.models.transformer.TransformerModel'>
>>> print(en2de.generate('Hello world!'))
Hallo Welt!
```
I got the following error. It seems  that `en2de.generate` should get an argument of type `torch.tensor`. I think in the example `print(en2de.generate('Hello world!'))` should be `print(en2de.translate('Hello world!'))`.

```
Traceback (most recent call last):
  File "fairseq_en_de.py", line 20, in <module>
    print(en2de.generate('Hello world!'))
  File "C:\Users\youwei/.cache\torch\hub\pytorch_fairseq_master\fairseq\hub_utils.py", line 107, in generate
    sample = self._build_sample(tokens)
  File "C:\Users\youwei/.cache\torch\hub\pytorch_fairseq_master\fairseq\hub_utils.py", line 173, in _build_sample
    assert torch.is_tensor(src_tokens)
AssertionError
```

**Comment by myleott** [comment]
Yes, the README is out of date, will submit a fix shortly.

**Comment by myleott** [comment]
Fixed in https://github.com/pytorch/fairseq/commit/abb7ed4c91b55b1b714021d8163f0a8c73f82f46.

**Comment by ink1** [comment]
I'm trying to run the new examples https://github.com/pytorch/fairseq/tree/master/examples/wmt19 and I'm getting a similar error
```
    en_lm.generate("Machine learning is")
  File "$USER/.cache/torch/hub/pytorch_fairseq_master/fairseq/hub_utils.py", line 109, in generate
    sample = self._build_sample(tokens)
  File "$USER/.cache/torch/hub/pytorch_fairseq_master/fairseq/hub_utils.py", line 180, in _build_sample
    assert torch.is_tensor(src_tokens)
AssertionError
```
The same error happens for translation.

**Comment by ink1** [comment]
Could this be possibly related to pytorch version? I'm using the latest 1.1.0
