### ISSUE TITLE
RuntimeError: Missing dependencies: fastBPE, sacremoses, subword_nmt

### ISSUE THREAD

**Issue by easonnie** [pytorch/fairseq#958]
I tried load roberta using torch.hub.
```
roberta = torch.hub.load('pytorch/fairseq', 'roberta.large')
roberta.eval()  # disable dropout (or leave in train mode to finetune)
print(roberta)
```
Output:
```
Traceback (most recent call last):
    roberta = torch.hub.load('pytorch/fairseq', 'roberta.large')
  File "---/.conda/envs/ynie_default_env/lib/python3.7/site-packages/torch/hub.py", line 338, in load
    entry = _load_entry_from_hubconf(hub_module, model)
  File "---/.conda/envs/ynie_default_env/lib/python3.7/site-packages/torch/hub.py", line 211, in _load_entry_from_hubconf
    _check_dependencies(m)
  File "---/.conda/envs/ynie_default_env/lib/python3.7/site-packages/torch/hub.py", line 200, in _check_dependencies
    raise RuntimeError('Missing dependencies: {}'.format(', '.join(missing_deps)))
RuntimeError: Missing dependencies: fastBPE, sacremoses, subword_nmt
```

**Comment by myleott** [comment]
Please add `force_reload=True` to torch.hub.load:
```
roberta = torch.hub.load('pytorch/fairseq', 'roberta.large')
```

**Comment by easonnie** [comment]
Thanks!
