### ISSUE TITLE
UnicodeDecodeError when reading file 'bpecodes' for en-de translation

### ISSUE THREAD

**Issue by Youwei-Liang** [pytorch/fairseq#961]
When I ran the  translation example:
```
>>> import torch
>>> torch.hub.list('pytorch/fairseq')
[..., 'transformer.wmt14.en-fr', 'transformer.wmt16.en-de', 'transformer.wmt18.en-de', ... ]
>>> en2de = torch.hub.load(
...   'pytorch/fairseq',
...   'transformer.wmt16.en-de',
...   data_name_or_path='.',
...   tokenizer='moses',
...   bpe='subword_nmt',
... )
>>> print(en2de.models[0].__class__)
<class 'fairseq.models.transformer.TransformerModel'>
>>> print(en2de.generate('Hello world!'))
Hallo Welt!
```
I encountered the following error:
```
Traceback (most recent call last):
  File "fairseq_en_de.py", line 16, in <module>
    bpe='subword_nmt')
  File "H:\Research\torch\env\lib\site-packages\torch\hub.py", line 340, in load
    model = entry(*args, **kwargs)
  File "C:\Users\youwei/.cache\torch\hub\pytorch_fairseq_master\fairseq\models\fairseq_model.py", line 176, in from_pretrained
    return hub_utils.GeneratorHubInterface(x['args'], x['task'], x['models'])
  File "C:\Users\youwei/.cache\torch\hub\pytorch_fairseq_master\fairseq\hub_utils.py", line 92, in __init__
    self.bpe = encoders.build_bpe(args)
  File "C:\Users\youwei/.cache\torch\hub\pytorch_fairseq_master\fairseq\registry.py", line 41, in build_x
    return builder(args, *extra_args, **extra_kwargs)
  File "C:\Users\youwei/.cache\torch\hub\pytorch_fairseq_master\fairseq\data\encoders\subword_nmt_bpe.py", line 41, in __init__
    bpe_args.glossaries,
  File "H:\Research\torch\env\lib\site-packages\subword_nmt\apply_bpe.py", line 37, in __init__
    firstline = codes.readline()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 3259: illegal multibyte sequence
```
This error is caused by a wrong encoding when reading the file 'bpecodes'. However, I couldn't find the code for opening it. It seems that the file is opened by the `bpe_parser`. Therefore, I have to fix the error by reopening the file by adding `bpe_args.codes.close(); bpe_args.codes = open(codes, 'r', encoding='utf-8')` in `\fairseq\data\encoders\subword_nmt_bpe.py`, as the following codes show.

```
def __init__(self, args):
        if args.bpe_codes is None:
            raise ValueError('--bpe-codes is required for --bpe=subword_nmt')
        print(args.bpe_codes)
        codes = file_utils.cached_path(args.bpe_codes)
        print(codes)
        try:
            from subword_nmt import apply_bpe
            bpe_parser = apply_bpe.create_parser()
            bpe_args = bpe_parser.parse_args([
                '--codes', codes,
                '--separator', args.bpe_separator,
            ])

            bpe_args.codes.close()
            bpe_args.codes = open(codes, 'r', encoding='utf-8')

            self.bpe = apply_bpe.BPE(
                bpe_args.codes,
                bpe_args.merges,
                bpe_args.separator,
                None,
                bpe_args.glossaries,
            )
            self.bpe_symbol = bpe_args.separator + ' '
        except ImportError:
            raise ImportError('Please install subword_nmt with: pip install subword-nmt')
```

**Comment by lematt1991** [comment]
This sounds like an issue for subword-nmt.  I believe the relevant line that opens the file is [here](https://github.com/rsennrich/subword-nmt/blob/master/subword_nmt/apply_bpe.py#L134).  Maybe post an issue there to see if they can help you to resolve it.
