### ISSUE TITLE
An Error When I try to finetune RoBERTa using multiple GPU

### ISSUE THREAD

**Issue by chengfx** [pytorch/fairseq#962]
Hi, There is an error when I want to finetune RoBERTa using multi-gpu. Could you guys help me take a look?

Here is the command:
```
CUDA_VISIBLE_DEVICES=0,1 python train.py $input_data_dir \
--restore-file models/pretrained/roberta.large/ \
--max-positions 512 \
--max-sentences $BATCH_SIZE \
--max-tokens 4400 \
--task sentence_prediction \
--reset-optimizer --reset-dataloader --reset-meters \
--required-batch-size-multiple 1 \
--init-token 0 --separator-token 2 \
--arch roberta_large \
--criterion sentence_prediction \
--num-classes $NUM_CLASSES \
--dropout 0.1 --attention-dropout 0.1 \
--weight-decay 0.1 --optimizer adam --adam-betas "(0.9, 0.98)" --adam-eps 1e-06 \
--clip-norm 0.0 \
--lr-scheduler polynomial_decay --lr $LR --total-num-update $TOTAL_NUM_UPDATES --warmup-updates $WARMUP_UPDATES \
--max-epoch 10 \
--best-checkpoint-metric accuracy --maximize-best-checkpoint-metric \
--truncate-sequence \
--update-freq 4 \
--save-interval-updates 15000 \
--keep-interval-updates -1 \
```

Here is the error information
```
| epoch 001:   0%|                                                                                      | 0/19494 [00:00<?, ?it/s]                                                                                 /usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphore                                                                                 s to clean up at shutdown
  len(cache))
Traceback (most recent call last):
  File "train.py", line 325, in <module>
    cli_main()
  File "train.py", line 317, in cli_main
    nprocs=args.distributed_world_size,
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 167, in spawn
    while not spawn_context.join():
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 114, in join
    raise Exception(msg)
Exception:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/fecheng/project/fairseq/train.py", line 284, in distributed_main
    main(args, init_distributed=True)
  File "/home/fecheng/project/fairseq/train.py", line 80, in main
    train(args, trainer, task, epoch_itr)
  File "/home/fecheng/project/fairseq/train.py", line 121, in train
    log_output = trainer.train_step(samples)
  File "/home/fecheng/project/fairseq/fairseq/trainer.py", line 264, in train_step
    ignore_grad
  File "/home/fecheng/project/fairseq/fairseq/tasks/fairseq_task.py", line 233, in train_step
    optimizer.backward(loss)
  File "/home/fecheng/project/fairseq/fairseq/optim/fairseq_optimizer.py", line 75, in backward
    loss.backward()
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/distributed.py", line 445, in distributed_data_parallel_hook
    self._queue_reduction(bucket_idx)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/distributed.py", line 475, in _queue_reduction
    self.device_ids)
TypeError: _queue_reduction(): incompatible function arguments. The following argument types are supported:
    1. (process_group: torch.distributed.ProcessGroup, grads_batch: List[List[at::Tensor]], devices: List[int]) -> Tuple[torch.dis                                                                                 tributed.Work, at::Tensor]

Invoked with: <torch.distributed.ProcessGroupNCCL object at 0x7fc840b0f378>, [[tensor([-0.0079, -0.0194, -0.0129,  ..., -0.0305,                                                                                   0.0143,  0.0341],
       device='cuda:0'), tensor([ 0.0013, -0.0488, -0.0382,  ..., -0.0085, -0.0244,  0.0345],
       device='cuda:0'), tensor([-0.0076, -0.0181, -0.0226,  ..., -0.0243,  0.0252,  0.0297],
       device='cuda:0'), tensor([ 0.0036, -0.0052,  0.0246,  ...,  0.0150, -0.0405,  0.0098],
       device='cuda:0'), tensor([ 0.0317,  0.0590, -0.0189,  ..., -0.0151, -0.0186,  0.0094],
       device='cuda:0'), None, None, None, None, None, tensor([[-0.0058,  0.1681,  0.1569,  ...,  0.0349, -0.0840,  0.0942],
        [ 0.0019, -0.0936, -0.0867,  ..., -0.0109,  0.0483, -0.0552],
        [-0.0285,  0.0757,  0.0928,  ...,  0.0342, -0.0570,  0.0400],
        ...,
        [ 0.0024,  0.0522,  0.0472,  ...,  0.0128, -0.0246,  0.0306],
        [-0.0054,  0.0339,  0.0393,  ...,  0.0086, -0.0207,  0.0218],
        [ 0.0151, -0.1101, -0.1103,  ..., -0.0230,  0.0609, -0.0643]],
       device='cuda:0'), tensor([ 0.0987, -0.0553,  0.0507,  ...,  0.0323,  0.0211, -0.0642],
       device='cuda:0'), tensor([[ 0.2051, -0.1739,  1.4588,  ..., -0.1755,  1.3977, -1.0086],
        [-0.2051,  0.1739, -1.4588,  ...,  0.1755, -1.3977,  1.0086]],
       device='cuda:0'), tensor([ 2.1315, -2.1315], device='cuda:0')]], [0]

fecheng@be8eef1d-12e2-4689-897f-d637cfd7afe7:~/project/fairseq$ /usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 12 leaked semaphores to clean up at shutdown
  len(cache))
/usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
```

**Comment by myleott** [comment]
I think @ngoyal2707 saw this error once, what was the fix?

**Comment by ngoyal2707** [comment]
@chengfx Thanks for reporting this issue. It should be resolved now. 

Can you please pull latest master and add `--find-unused-parameters` to your training command? That should solve your issue. Let me know how if you it doesn't work for you.

**Comment by chengfx** [comment]
It works now. Thanks very much

**Comment by chengfx** [comment]
Hi @ngoyal2707 . It works in my machine but fails in docker of cluster
Below is the command
```
input_data_dir=data/list_qp_train_en_filter.tsv/
TOTAL_NUM_UPDATES=187500  # after TOTAL_NUM_UPDATES, lr will be 0
WARMUP_UPDATES=500      # 6 percent of the number of updates
LR=5e-6
NUM_CLASSES=2
BATCH_SIZE=16
max_positions=150
save_dir=checkpoints/lr${LR}_mp${max_positions}
train_log=$save_dir/train.log
mkdir -p $save_dir

CUDA_VISIBLE_DEVICES=0,1 python -u train.py $input_data_dir \
--restore-file models/pretrained/roberta.large/ \
--max-positions $max_positions \
--max-sentences $BATCH_SIZE \
--max-tokens 4400 \
--task sentence_prediction \
--reset-optimizer --reset-dataloader --reset-meters \
--required-batch-size-multiple 1 \
--init-token 0 --separator-token 2 \
--arch roberta_large \
--criterion sentence_prediction \
--num-classes $NUM_CLASSES \
--dropout 0.1 --attention-dropout 0.1 \
--weight-decay 0.1 --optimizer adam --adam-betas "(0.9, 0.98)" --adam-eps 1e-06 \
--clip-norm 0.0 \
--lr-scheduler polynomial_decay --lr $LR --total-num-update $TOTAL_NUM_UPDATES --warmup-updates $WARMUP_UPDATES \
--max-epoch 10 \
--best-checkpoint-metric accuracy --maximize-best-checkpoint-metric \
--truncate-sequence \
--update-freq 1 \
--save-dir $save_dir \
--save-interval-updates 6000 \
--keep-interval-updates -1 \
--log-format tqdm \
--find-unused-parameters 
```

Below is the error information
```
| epoch 001:   0%|                                      | 1/38988 [00:02<27:27:40,  2.54s/it, loss=1.017, nll_loss=0.011, ppl=1.01, wps=197, ups=0, wpb=2874.000, bsz=32.000, num_updates=1, lr=1e-08, gnorm=7.269, clip=0.000, oom=0.000, wall=15, train_wall=2, accuracy=0.5]/usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
/usr/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
Traceback (most recent call last):
  File "train.py", line 325, in <module>
    cli_main()
  File "train.py", line 317, in cli_main
    nprocs=args.distributed_world_size,
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 167, in spawn
    while not spawn_context.join():
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 114, in join
    raise Exception(msg)
Exception:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/fecheng/project/fairseq/train.py", line 284, in distributed_main
    main(args, init_distributed=True)
  File "/home/fecheng/project/fairseq/train.py", line 80, in main
    train(args, trainer, task, epoch_itr)
  File "/home/fecheng/project/fairseq/train.py", line 121, in train
    log_output = trainer.train_step(samples)
  File "/home/fecheng/project/fairseq/fairseq/trainer.py", line 264, in train_step
    ignore_grad
  File "/home/fecheng/project/fairseq/fairseq/tasks/fairseq_task.py", line 233, in train_step
    optimizer.backward(loss)
  File "/home/fecheng/project/fairseq/fairseq/optim/fairseq_optimizer.py", line 75, in backward
    loss.backward()
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/distributed.py", line 445, in distributed_data_parallel_hook
    self._queue_reduction(bucket_idx)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/parallel/distributed.py", line 475, in _queue_reduction
    self.device_ids)
TypeError: _queue_reduction(): incompatible function arguments. The following argument types are supported:
    1. (process_group: torch.distributed.ProcessGroup, grads_batch: List[List[at::Tensor]], devices: List[int]) -> Tuple[torch.distributed.Work, at::Tensor]

Invoked with: <torch.distributed.ProcessGroupNCCL object at 0x7f978494f5e0>, [[tensor([-7.7137e-05, -7.7398e-05, -9.9708e-04,  ...,  7.8375e-04,
        -5.7834e-04, -2.7236e-04], device='cuda:1'), tensor([-0.0011, -0.0065,  0.0034,  ..., -0.0132, -0.0137, -0.0097],
       device='cuda:1'), tensor([-6.0075e-05,  5.9439e-04, -3.1828e-04,  ...,  5.0858e-04,
        -6.9407e-04, -7.4547e-04], device='cuda:1'), tensor([-5.9036e-04,  6.3898e-04,  8.8195e-04,  ..., -1.7639e-04,
         4.3905e-05, -2.0035e-04], device='cuda:1'), tensor([ 0.0036,  0.0023, -0.0040,  ..., -0.0020, -0.0018, -0.0066],
       device='cuda:1'), None, None, None, None, None, tensor([[ 0.0019, -0.0041, -0.0032,  ..., -0.0150,  0.0074,  0.0106],
        [-0.0047, -0.0041, -0.0026,  ..., -0.0695,  0.0357,  0.0400],
        [ 0.0049, -0.0004, -0.0002,  ..., -0.0520,  0.0217,  0.0263],
        ...,
        [-0.0026,  0.0008, -0.0004,  ...,  0.0121, -0.0060, -0.0054],
        [-0.0005,  0.0014, -0.0002,  ...,  0.0229, -0.0148, -0.0124],
        [-0.0017,  0.0004,  0.0005,  ...,  0.0059, -0.0030, -0.0029]],
       device='cuda:1'), tensor([-0.0143, -0.0572, -0.0409,  ...,  0.0102,  0.0185,  0.0052],
       device='cuda:1'), tensor([[ 0.5627, -0.2471,  0.5647,  ..., -0.4491,  0.8094, -0.4265],
        [-0.5627,  0.2471, -0.5647,  ...,  0.4491, -0.8094,  0.4265]],
       device='cuda:1'), tensor([-1.5383,  1.5383], device='cuda:1')]], [1]
```

**Comment by ngoyal2707** [comment]
That could be due to version difference of pytorch between your local machine and docker. Can you please make sure, you have same version of PT in docker also?
