### ISSUE TITLE
Unable to call ../preprocess.py

### ISSUE THREAD

**Issue by gmhafiz** [pytorch/fairseq#988]
Error when calling ../preprocess.py when running glue dataset finetuning

OS: Ubuntu 18.04 LTS
python 3.6
torch 1.1.0

Steps to reproduce:
```
git clone https://github.com/pytorch/fairseq
cd fairseq
virtualenv env
source env/bin/activate
pip3 install regex
pip3 install fairseq
pip3 install --editable .
wget https://gist.githubusercontent.com/W4ngatang/60c2bdb54d156a41194446737ce03e2e/raw/17b8dd0d724281ed7c3b2aeeda662b92809aadd5/download_glue_data.py
python3 download_glue_data.py --data_dir glue_data --tasks all
sed -i 's/mkdir/mkdir -p/g' ./examples/roberta/preprocess_GLUE_tasks.sh
./examples/roberta/preprocess_GLUE_tasks.sh glue_data STS-B
```

Error output:

```
Preprocessing STS-B
Raw data as downloaded from glue website: glue_data//STS-B
BPE encoding train/input0
BPE encoding train/input1
BPE encoding dev/input0
BPE encoding dev/input1
BPE encoding test/input0
BPE encoding test/input1
Traceback (most recent call last):
  File "~/fairseq/env/bin/fairseq-preprocess", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-preprocess')()
  File "~/fairseqn/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "~/fairseq/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "~/fairseq/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "~/fairseq/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "~/fairseq/fairseq_cli/preprocess.py", line 1
    ../preprocess.py
    ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "~/fairseq/env/bin/fairseq-preprocess", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-preprocess')()
  File "~/fairseq/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "~/fairseq/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "~/fairseq/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "~/fairseq/env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "~/fairseq/fairseq_cli/preprocess.py", line 1
    ../preprocess.py
    ^
SyntaxError: invalid syntax
```

**Comment by myleott** [comment]
I reran these exact commands and can't repro. Can you try the following:
```
cd ~/fairseq
pip3 uninstall -y fairseq
pip3 install --editable .
./examples/roberta/preprocess_GLUE_tasks.sh glue_data STS-B
```

**Comment by gmhafiz** [comment]
I redone the steps without `pip3 install fairseq` and it works now. Cannot have both `pip3 install fairseq` and `pip3 install --editable .` run.
