### ISSUE TITLE
AttributeError: 'MMapIndexedDataset' object has no attribute 'set_epoch'

### ISSUE THREAD

**Issue by ksboy** [pytorch/fairseq#989]
I tried to fine-tune RTE task of GLUE.

As recommended, the command is  https://github.com/pytorch/fairseq/blob/master/examples/roberta/README.finetune_glue.md#3-fine-tuning-on-glue-task

But I got error as follows:
```
| model roberta_large, criterion SentencePredictionCriterion
| num. model params: 356462683 (num. trained: 356462683)
| training on 1 GPUs
| max tokens per GPU = 4400 and max sentences per GPU = 16
Overwriting classification_heads.sentence_classification_head.dense.weight
Overwriting classification_heads.sentence_classification_head.dense.bias
Overwriting classification_heads.sentence_classification_head.out_proj.weight
Overwriting classification_heads.sentence_classification_head.out_proj.bias
| loaded checkpoint ../roberta.large.mnli/../roberta.large.mnli/model.pt (epoch 0 @ 0 updates)
| WARNING: your device does NOT support faster training with --fp16, please switch to FP32 which is likely to be faster
| loading train data for epoch 0
| loaded 2490 examples from: RTE-bin/input0/train
| loaded 2490 examples from: RTE-bin/input1/train
| loaded 2490 examples from: RTE-bin/label/train
| Loaded train with #samples: 2490
Traceback (most recent call last):
  File "train.py", line 347, in <module>
    cli_main()
  File "train.py", line 343, in cli_main
    main(args)
  File "train.py", line 82, in main
    train(args, trainer, task, epoch_itr)
  File "train.py", line 112, in train
    shuffle=False,
  File "/data/houwei/fairseq/fairseq/data/iterators.py", line 182, in next_epoch_itr
    self.dataset.set_epoch(self.epoch)
  File "/data/houwei/fairseq/fairseq/data/nested_dictionary_dataset.py", line 116, in set_epoch
    ds.set_epoch(epoch)
  File "/data/houwei/fairseq/fairseq/data/base_wrapper_dataset.py", line 51, in set_epoch
    self.dataset.set_epoch(epoch)
  File "/data/houwei/fairseq/fairseq/data/base_wrapper_dataset.py", line 51, in set_epoch
    self.dataset.set_epoch(epoch)
AttributeError: 'MMapIndexedDataset' object has no attribute 'set_epoch'
```

**Comment by ngoyal2707** [comment]
Looking at it, I think it got broken in recent commits. Thanks for reporting the issue
