### ISSUE TITLE
roberta: cannot import name 'BPEHubInterface'

### ISSUE THREAD

**Issue by rush86999** [pytorch/fairseq#992]
hello,

 I am using pytorch 1.1 with python 3.6 on aws ec2 ami with p3.2xlarge machine. 

here's the error i get:
```
Using cache found in /home/ec2-user/.cache/torch/hub/pytorch_fairseq_master
Traceback (most recent call last):
  File "paraphrase_train_roberta.py", line 308, in <module>
    train(args, device_id)
  File "paraphrase_train_roberta.py", line 129, in train
    d_k=args.d_k, d_v=args.d_v)
  File "/home/ec2-user/snips-extractor/src/models/model_builder_roberta.py", line 257, in __init__
    roberta = torch.hub.load('pytorch/fairseq', 'roberta.base')
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/hub.py", line 336, in load
    hub_module = import_module(MODULE_HUBCONF, repo_dir + '/' + MODULE_HUBCONF)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/hub.py", line 70, in import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ec2-user/.cache/torch/hub/pytorch_fairseq_master/hubconf.py", line 8, in <module>
    from fairseq.hub_utils import BPEHubInterface as bpe  # noqa
ImportError: cannot import name 'BPEHubInterface'
```

i m stumped. I have no idea what's wrong here. I followed the instructions including installing the nccl package and pip install fairseq. Any help is appreciated.

**Comment by myleott** [comment]
Can you try `roberta = torch.hub.load('pytorch/fairseq', 'roberta.base', force_reload=True)`?

**Comment by rush86999** [comment]
that did not work same error. I also installed the nvidia nccl network repository, i m not sure if it makes a difference.

**Comment by rush86999** [comment]
```
Using cache found in /home/ec2-user/.cache/torch/hub/pytorch_fairseq_master
Traceback (most recent call last):
  File "paraphrase_train_roberta.py", line 308, in <module>
    train(args, device_id)
  File "paraphrase_train_roberta.py", line 129, in train
    d_k=args.d_k, d_v=args.d_v)
  File "/home/ec2-user/snips-extractor/src/models/model_builder_roberta.py", line 257, in __init__
    roberta = torch.hub.load('pytorch/fairseq', 'roberta.base')
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/hub.py", line 336, in load
    hub_module = import_module(MODULE_HUBCONF, repo_dir + '/' + MODULE_HUBCONF)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/hub.py", line 70, in import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ec2-user/.cache/torch/hub/pytorch_fairseq_master/hubconf.py", line 8, in <module>
    from fairseq.hub_utils import BPEHubInterface as bpe  # noqa
ImportError: cannot import name 'BPEHubInterface'
```

**Comment by rush86999** [comment]
```
Downloading: "https://github.com/pytorch/fairseq/archive/master.zip" to /home/ec2-user/.cache/torch/hub/master.zip
Traceback (most recent call last):
  File "paraphrase_train_roberta.py", line 308, in <module>
    train(args, device_id)
  File "paraphrase_train_roberta.py", line 129, in train
    d_k=args.d_k, d_v=args.d_v)
  File "/home/ec2-user/snips-extractor/src/models/model_builder_roberta.py", line 257, in __init__
    roberta = torch.hub.load('pytorch/fairseq', 'roberta.base', force_reload=True)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/hub.py", line 336, in load
    hub_module = import_module(MODULE_HUBCONF, repo_dir + '/' + MODULE_HUBCONF)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/hub.py", line 70, in import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ec2-user/.cache/torch/hub/pytorch_fairseq_master/hubconf.py", line 8, in <module>
    from fairseq.hub_utils import BPEHubInterface as bpe  # noqa
ImportError: cannot import name 'BPEHubInterface'
```

**Comment by rush86999** [comment]
as you can see i updated to 
```
File "/home/ec2-user/snips-extractor/src/models/model_builder_roberta.py", line 257, in __init__
    roberta = torch.hub.load('pytorch/fairseq', 'roberta.base', force_reload=True)
```

**Comment by myleott** [comment]
Can you run `pip uninstall fairseq` and try again? The torch.hub interface doesn't require fairseq to be installed to work, just torch. It seems like you're somehow pulling in an old version of fairseq that doesn't have the BPEHubInterface code :/

**Comment by rush86999** [comment]
can we do ```pip install fairseq==version``` to install the specific version? what version should I install?

**Comment by rush86999** [comment]
oh so i don't need fairseq at all for this to work? just torch.hub. Is that what you are saying to use roberta?

**Comment by rush86999** [comment]
```
Uninstalling fairseq-0.7.2:
  Would remove:
    /home/ec2-user/anaconda3/envs/pytorch_p36/bin/fairseq-eval-lm
    /home/ec2-user/anaconda3/envs/pytorch_p36/bin/fairseq-generate
    /home/ec2-user/anaconda3/envs/pytorch_p36/bin/fairseq-interactive
    /home/ec2-user/anaconda3/envs/pytorch_p36/bin/fairseq-preprocess
    /home/ec2-user/anaconda3/envs/pytorch_p36/bin/fairseq-score
    /home/ec2-user/anaconda3/envs/pytorch_p36/bin/fairseq-train
    /home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fairseq-0.7.2.dist-info/*
    /home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fairseq/*
    /home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/fairseq_cli/*
```
and did pip install again. did not work. same version is installed

**Comment by rush86999** [comment]
```
Traceback (most recent call last):
  File "paraphrase_train_roberta.py", line 15, in <module>
    from models import data_loader_roberta, model_builder_roberta
  File "/home/ec2-user/snips-extractor/src/models/data_loader_roberta.py", line 9, in <module>
    from fairseq.data.data_utils import collate_tokens
ModuleNotFoundError: No module named 'fairseq'
```
```
Collecting fairseq
Requirement already satisfied: cffi in /home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from fairseq) (1.11.5)
Requirement already satisfied: tqdm in /home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from fairseq) (4.32.1)
Requirement already satisfied: torch in /home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from fairseq) (1.1.0)
Requirement already satisfied: numpy in /home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from fairseq) (1.15.4)
Requirement already satisfied: sacrebleu in /home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from fairseq) (1.3.7)
Requirement already satisfied: pycparser in /home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from cffi->fairseq) (2.18)
Requirement already satisfied: portalocker in /home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from sacrebleu->fairseq) (1.5.1)
Requirement already satisfied: typing in /home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages (from sacrebleu->fairseq) (3.6.4)
Installing collected packages: fairseq
Successfully installed fairseq-0.7.2
```
```
Downloading: "https://github.com/pytorch/fairseq/archive/master.zip" to /home/ec2-user/.cache/torch/hub/master.zip
Traceback (most recent call last):
  File "paraphrase_train_roberta.py", line 308, in <module>
    train(args, device_id)
  File "paraphrase_train_roberta.py", line 129, in train
    d_k=args.d_k, d_v=args.d_v)
  File "/home/ec2-user/snips-extractor/src/models/model_builder_roberta.py", line 257, in __init__
    roberta = torch.hub.load('pytorch/fairseq', 'roberta.base', force_reload=True)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/hub.py", line 336, in load
    hub_module = import_module(MODULE_HUBCONF, repo_dir + '/' + MODULE_HUBCONF)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/hub.py", line 70, in import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ec2-user/.cache/torch/hub/pytorch_fairseq_master/hubconf.py", line 8, in <module>
    from fairseq.hub_utils import BPEHubInterface as bpe  # noqa
ImportError: cannot import name 'BPEHubInterface'
```

**Comment by myleott** [comment]
> oh so i don't need fairseq at all for this to work? just torch.hub. Is that what you are saying to use roberta?

Correct.

Please try this (without reinstalling fairseq):
```
$ pip uninstall fairseq
$ python
>>> import torch
>>> roberta = torch.hub.load('pytorch/fairseq', 'roberta.base', force_reload=True)
```

**Comment by rush86999** [comment]
but you see I'm also using the helper function: ```fairseq.data.data_utils import collate_tokens```
i m creating batches for tokens using ```collate_tokens```. Is there a workaround to this?  should I just copy the functionality into a new module so it is no longer dependent?

**Comment by rush86999** [comment]
I am also using ```PositionalEncoding``` from  ```fairseq.modules``` as well

**Comment by rush86999** [comment]
ok seems to work . I took out the necessary code into a new module and uninstalled fairseq so no longer an issue thans for your help
